cockroachdb/docs

_includes/v20.2/faq/auto-generate-unique-ids.html, _includes/v20.2/faq/sequential-numbers.md, _includes/v21.1/faq/auto-generate-unique-ids.html, _includes/v21.1/faq/sequential-numbers.md, _includes/v21.2/faq/auto-generate-unique-ids.html, _includes/v21.2/faq/sequential-numbers.md, _includes/v22.1/faq/auto-generate-unique-ids.html, _includes/v22.1/faq/sequential-numbers.md, v20.2/performance-best-practices-overview.md, v20.2/uuid.md, v21.1/add-constraint.md, v21.1/performance-best-practices-overview.md, v21.1/uuid.md, v21.2/add-constraint.md, v21.2/uuid.md, v22.1/add-constraint.md, v22.1/uuid.md
https://cockroachlabs.atlassian.net/browse/DOC-1600
=> Eliminate rowid, row ID confusion.

_includes/v22.1/misc/declarative-schema-changer-note.md, v22.1/drop-database.md, v22.1/drop-schema.md, v22.1/drop-table.md, v22.1/drop-type.md, v22.1/online-schema-changes.md
=> DOC-2842: Add note about new declarative schema changer

_includes/v22.1/misc/session-vars.md, v22.1/alter-type.md
=> DOC-3442: Remove experimental designation for ALTER TYPE..DROP VALUE

v22.1/create-index.md
=> DOC-2670: Added info about PK columns added as STORING to unique indexes

v21.2/configure-cockroachdb-kubernetes.md, v22.1/configure-cockroachdb-kubernetes.md
Fixes DOC-2118.
- Document HTTP and SQL ingress configuration with the K8s Operator.
=> k8s operator ingress configuration

v22.1/known-limitations.md
=> transaction_rows_read_err / transaction_rows_written_err known limitation

v21.1/build-a-nodejs-app-with-cockroachdb-prisma.md, v21.2/build-a-nodejs-app-with-cockroachdb-prisma.md, v22.1/build-a-nodejs-app-with-cockroachdb-prisma.md
=> fix(build-a-nodejs-app-with-cockroachdb-prisma): Remove mention of preview for Prisma+CockroachDB

_includes/cockroachcloud/ccloud/install-ccloud.md, _includes/cockroachcloud/ccloud/quickstart.md, _includes/cockroachcloud/quickstart/database-url-environment-variable.md, cockroachcloud/ccloud-get-started.md, cockroachcloud/quickstart.md
=> Adding ccloud option to Quickstart.

_includes/v22.1/sql/enable-super-region-primary-region-changes.md
=> Update super region var for primary region changes

v21.2/changefeed-examples.md, v22.1/changefeed-examples.md
Fixes [DOC-3425](https://cockroachlabs.atlassian.net/browse/DOC-3425)
=> Correction to Changefeed Examples page header levels

_includes/head.html
Include docs for all EOL versions.
=> Update list of docs version to exclude from search

StyleGuide.md
Add note about Vale in Style Guide
=> Add note about Vale in Style Guide

_includes/v22.1/sidebar-data/reference.json
Enterprise should not have code formatting.
=> Fix formatting.

cockroachcloud/upgrade-policy.md
https://cockroachlabs.atlassian.net/browse/DOC-3562
=> Latest patch rollback clarification

cockroachcloud/frequently-asked-questions.md
Just noticed it was out of date
=> Update FAQ for API

v22.1/known-limitations.md
=> Add cockroach-sql known limitations

advisories/a82309.md
Addresses: DOC-3712
- Issues new TA 82309, affecting changefeeds in v22.1.0
[advisories/a82309.md](https://deploy-preview-14012--cockroachdb-docs.netlify.app/docs/advisories/a82309)
=> DOC-3712 Issue TA 82309

releases/cloud.md
https://cockroachlabs.atlassian.net/browse/DOC-3658
=> June cloud release notes

StyleGuide.md
Fixes [DOC-2181](https://cockroachlabs.atlassian.net/browse/DOC-2181)
Added some guidance to the File Conventions section of the style guide regarding file naming.
=> Added guidance on file naming to style guide

_includes/v21.1/performance/lease-preference-system-database.md, _includes/v21.2/performance/lease-preference-system-database.md, _includes/v22.1/performance/lease-preference-system-database.md, netlify/vale/vocab.txt, v21.1/multiregion-overview.md, v21.1/online-schema-changes.md, v21.2/multiregion-overview.md, v21.2/online-schema-changes.md, v22.1/multiregion-overview.md, v22.1/online-schema-changes.md
=> DOC-3448: Add tip on improving schema change latency for MR

_includes/v22.1/orchestration/kubernetes-upgrade-cluster-helm.md, _includes/v22.1/orchestration/kubernetes-upgrade-cluster-manual.md
=> fix K8s upgrade step

v22.1/as-of-system-time.md, v22.1/follower-reads.md
https://cockroachlabs.atlassian.net/browse/DOC-3766
=> Emphasize that follower reads are consistent.

v22.1/show-default-privileges.md
=> DOC-3097: Add example to SHOW DEFAULT PRIVILEGES

v20.2/show-schedules.md, v21.1/show-schedules.md, v21.2/show-schedules.md, v22.1/show-schedules.md
Related issue: https://github.com/cockroachdb/docs/issues/11710
=> Clarified Behaviour

_includes/v22.1/known-limitations/cdc.md
Fixes [DOC-3633](https://cockroachlabs.atlassian.net/browse/DOC-3633)
Small change to the wording in the target CDC known limitation to include column families
=> Include column families as targets in known limitation

_includes/v21.1/orchestration/test-cluster-secure.md, _includes/v21.2/orchestration/test-cluster-secure.md, _includes/v22.1/orchestration/test-cluster-secure.md
Fixes [DOC-3745](https://cockroachlabs.atlassian.net/browse/DOC-3745).
=> fix Helm SQL container steps

v22.1/row-level-ttl.md
=> Update TTL docs with backup/restore and CDC info

_includes/v21.1/sql/preloaded-databases.md, _includes/v21.2/sql/preloaded-databases.md, _includes/v22.1/sql/preloaded-databases.md, v21.1/show-databases.md, v21.1/sql-name-resolution.md, v21.2/show-databases.md, v21.2/sql-name-resolution.md, v22.1/show-databases.md, v22.1/sql-name-resolution.md
=> DOC-1102: Add information about the `system` database

v21.1/comment-on.md, v21.2/comment-on.md, v22.1/comment-on.md
=> DOC-2898: Add details on how to remove a comment from an object

_includes/v21.1/sql/unsupported-postgres-features.md, _includes/v21.2/sql/unsupported-postgres-features.md, _includes/v22.1/sql/unsupported-postgres-features.md
=> DOC-2370: Add note about unsupported syntax

v21.1/primary-key.md, v21.2/primary-key.md, v22.1/primary-key.md
=> DOC-3291: Clarify use of PRIMARY KEY in tables

v22.1/cost-based-optimizer.md
https://cockroachlabs.atlassian.net/browse/DOC-1298
=> Add force zigzag hint.

_config_base.yml, _data/releases.csv, _includes/releases/v22.1/v22.1.2.md
=> DOC-2249: Added v22.1.2 release note

v21.2/scalar-expressions.md, v22.1/scalar-expressions.md
See https://github.com/cockroachdb/cockroach/issues/82498
=> Clarify evaluation of conditional branches

_includes/v21.2/cdc/create-core-changefeed-avro.md, _includes/v21.2/cdc/create-core-changefeed.md, _includes/v22.1/cdc/create-core-changefeed-avro.md, _includes/v22.1/cdc/create-core-changefeed.md, v21.2/changefeed-examples.md, v21.2/cockroach-start-single-node.md, v21.2/demo-serializable.md, v22.1/changefeed-examples.md, v22.1/cockroach-start-single-node.md, v22.1/demo-serializable.md
=> Remove cockroach quit

_includes/v22.1/ui/statistics.md
=> Address statistics cleanup controls.

_includes/cockroachcloud/cmek-private-preview.md, _includes/v22.1/sidebar-data/manage.json, _includes/v22.1/sidebar-data/reference.json, cockroachcloud/cmek-faq.md, cockroachcloud/cmek.md, cockroachcloud/managing-cmek.md, netlify/vale/vocab.txt, v22.1/security-reference/encryption.md
DOC-3661
DOC-3663
DOC-302
Previews of pages with substantial changes:
https://deploy-preview-13963--cockroachdb-docs.netlify.app/docs/cockroachcloud/cmek.html
https://deploy-preview-13963--cockroachdb-docs.netlify.app/docs/v22.1/encryption.html
https://deploy-preview-13963--cockroachdb-docs.netlify.app/docs/v22.1/security-reference/encryption.html
TODO: Combine / de-duplicate the FAQs.
=> [DOC-3661][DOC-3663] Add a concept for CMEK

v21.2/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md, v22.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
DOC-3429
See the duplicated first bullet at https://www.cockroachlabs.com/docs/v21.2/orchestrate-cockroachdb-with-kubernetes-multi-cluster.html#step-3-use-the-built-in-sql-client.
=> [DOC-3429] Fix ordered list numbering in filtered content

advisories/a81448.md
Updated TA metadata to today's publish date.
=> correct advisory date

StyleGuide.md
Fixes [DOC-2069](https://cockroachlabs.atlassian.net/browse/DOC-2069)
Short PR to add guidance on whether different punctuation should go inside/outside of quotation marks.
=> Style: Punctuation inside/outside quotation marks

.github/workflows/changed_files.yml
This reverts commit fe1641a7c707609c0f3ab537771f49858a24100a.
=> Revert "DOC-4630 support downstream forks"

cockroachcloud/create-your-cluster.md
Change to "we recommend" 150 GiB limitation
=> Language nit for unrestricted dedicated storage options

_includes/v21.1/computed-columns/jsonb.md, _includes/v21.2/computed-columns/jsonb.md, _includes/v22.1/computed-columns/jsonb.md
=> Add a stored column with a coerced type.

v21.2/create-security-certificates-custom-ca.md, v22.1/create-security-certificates-custom-ca.md
[DOC-3407]
Reviewers: Let's try using only Github for this review and skipping Reviewable. Thanks!
=> [DOC-3407] Provide info about re-reading certificates on k8s-managed clusters

_includes/v21.1/start-in-docker/mac-linux-steps.md, _includes/v21.2/start-in-docker/mac-linux-steps.md, _includes/v22.1/start-in-docker/mac-linux-steps.md
Fixes DOC-3408.
These steps were actually fixed and working as of v20.2 (I made the changes long ago), but were apparently lost when the v21.1 docs branch was cut (presumably from an older version). I've restored the changes from v20.2 to the subsequent versions.
@smcvey Thank you very much for locating the issue!
=> fix Docker start steps

_includes/v1.1/orchestration/kubernetes-limitations.md, _includes/v19.1/orchestration/kubernetes-limitations.md, _includes/v19.2/orchestration/kubernetes-limitations.md, _includes/v2.0/orchestration/kubernetes-limitations.md, _includes/v2.1/orchestration/kubernetes-limitations.md, _includes/v20.1/orchestration/kubernetes-limitations.md, _includes/v20.2/orchestration/kubernetes-limitations.md, v21.2/kubernetes-performance.md, v22.1/kubernetes-performance.md
Fixes [DOC-1623](https://cockroachlabs.atlassian.net/browse/DOC-1623).
- Added DaemonSet warning to Kubernetes Performance doc
- Removed DaemonSet recommendations in all docs versions
- Some opportunistic updates to Kubernetes Performance doc (which remains in need of a broader update)
=> remove DaemonSet recommendation; add warning

v22.1/crdb-internal.md
=> Index stat reset.

cockroachcloud/ccloud-get-started.md, cockroachcloud/cloud-api.md
=> Clarify that users created using the API/ccloud have the admin role.

releases/cloud.md
https://cockroachlabs.atlassian.net/browse/DOC-4619
=> Cloud July 2022 Release Notes

v22.1/serial.md
=> DOC-698: Added new SERIAL generation type

v22.1/online-schema-changes.md
=> DOC-3036: Some schema change jobs pause if node runs out of disk

v22.1/migrate-from-postgres.md, v22.1/performance-best-practices-overview.md
=> DOC-1010: Add clarification note of CRDB antipatterns

v22.1/sql-faqs.md
=> Add full text search faq

v22.1/functions-and-operators.md
=> Fix bug in JSONB operators.

netlify/vale/vocab.txt, v21.2/aws-dms.md, v22.1/aws-dms.md
=> DOC-4892: Added clarification points on AWS DMS docs

cockroachcloud/backups-page.md
Fixes [DOC-4905](https://cockroachlabs.atlassian.net/browse/DOC-4905)
Added an additional workflow to the Dedicated section of the CockroachCloud Restore page. This includes the matching of regions between databases.
=> Added Dedicated multi-region restore workflow

v21.1/build-a-nodejs-app-with-cockroachdb-prisma.md, v21.2/build-a-nodejs-app-with-cockroachdb-prisma.md, v22.1/build-a-nodejs-app-with-cockroachdb-prisma.md
=> DOC-5005: Update prisma command call

v22.1/functions-and-operators.md, v22.1/jsonb.md
=> Fix formatting bugs and switched examples.

jekyll-algolia-dev/lib/jekyll/algolia/hooks.rb
=> DOC-5012: Update Algolia search index to include TAs and API docs

v22.1/aws-dms.md
Add supported source databases to DMS docs
=> Add supported source databases to DMS docs

netlify/vale/vocab.txt, v22.1/community-tooling.md
=> Adding Elixir/Postgrex to community tooling page with link to example.

_includes/v21.1/orchestration/kubernetes-limitations.md, _includes/v21.2/orchestration/kubernetes-limitations.md, _includes/v22.1/orchestration/kubernetes-limitations.md
[Preview](https://deploy-preview-14473--cockroachdb-docs.netlify.app/docs/stable/deploy-cockroachdb-with-kubernetes.html#limitations)
=> [DOC-587] Add info about Helm 2 issues

advisories/a84144.md
Reverts cockroachdb/docs#14564
=> Republish TA-84144

v20.2/cluster-setup-troubleshooting.md, v21.1/cluster-setup-troubleshooting.md, v21.2/cluster-setup-troubleshooting.md, v22.1/cluster-setup-troubleshooting.md
Add missing bullet point to docs added in #14528.
=> fix add bullet

v22.1/explain.md
=> Update for effect of limit on estimated row counts.

v22.1/explain-analyze.md
=> Add join example.

v22.1/query-behavior-troubleshooting.md
=> Add memory error to query troubleshooting.

v21.2/explain-analyze.md
=> Propagate mem usage for lookup join to 21.2

v22.1/refresh.md
=> Add diagram.

v21.2/cost-based-optimizer.md, v21.2/explain.md, v21.2/indexes.md, v22.1/cost-based-optimizer.md, v22.1/explain.md
=> Document session variables related to full scans.

_layouts/homepage.html
=> Update home page to reference 2022 Cloud Report

v22.1/security-reference/authorization.md
=> DOC-3505: Add statement about default privilege change

v22.1/hash-sharded-indexes.md, v22.1/multiregion-overview.md
=> DOC-2711: Implicitly partitioned tables can use HSIs

cockroachcloud/quickstart.md, v22.1/migrate-from-mysql.md, v22.1/migrate-from-postgres.md
=> DOC-543: Add link to Migration docs from Quickstart

StyleGuide.md, advisories/a30821.md, advisories/a42567.md, advisories/a44166.md, advisories/a44299.md, advisories/a44348.md, advisories/a48860.md, advisories/a50587.md, advisories/a58932.md, advisories/a62842.md, advisories/a63162.md, advisories/a68005.md, advisories/a74736.md, advisories/a75758.md, advisories/a76522.md, advisories/a78681.md, advisories/a79066.md, advisories/a79281.md, advisories/a79384.md, advisories/a81315.md, advisories/a81448.md, advisories/a82079.md, advisories/a82309.md, advisories/a82576.md, advisories/a84144.md
Fixes DOC-4596.
Also updated style guide to reflect this usage.
=> update style for version ranges; reformat TA table

_includes/v22.1/sidebar-data/reference.json, netlify/vale/vocab.txt, v22.1/api-support-policy.md, v22.1/cluster-api.md, v22.1/system-catalogs.md
=> API support policy

v22.1/alter-default-privileges.md
=> Update for IN SCHEMA.

v22.1/information-schema.md
=> Fix incorrect description.

v21.2/configure-cockroachdb-kubernetes.md, v22.1/configure-cockroachdb-kubernetes.md, v22.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
Followup from #14620
Previews:
https://deploy-preview-14676--cockroachdb-docs.netlify.app/docs/v21.2/configure-cockroachdb-kubernetes.html?#ingress
https://deploy-preview-14676--cockroachdb-docs.netlify.app/docs/v22.1/configure-cockroachdb-kubernetes.html?#ingress
https://deploy-preview-14676--cockroachdb-docs.netlify.app/docs/v22.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.html?filters=eks#step-2-configure-your-network
=> Update more Kubernetes Operator links from master to tagged versions

v22.1/show-super-regions.md
=> DOC-5221: Fix super region diagram

v21.2/build-a-nodejs-app-with-cockroachdb.md, v22.1/build-a-nodejs-app-with-cockroachdb.md
Just noticed the file path is missing a word
=> Node app filepath fix

_includes/v22.1/sidebar-data/reference.json, netlify/vale/vocab.txt, v22.1/data-types.md, v22.1/oid.md
=> Add OID type.

v20.2/upgrade-cockroach-version.md, v21.1/upgrade-cockroach-version.md, v21.2/upgrade-cockroach-version.md, v22.1/upgrade-cockroach-version.md
=> Upgrade decommission

v22.1/foreign-key.md
=> Expand FK to crdb_region

v21.2/node-shutdown.md, v22.1/node-shutdown.md
Fixes [DOC-2815](https://cockroachlabs.atlassian.net/browse/DOC-2815).
=> use liquid syntax in snippets

_includes/v21.2/orchestration/start-cockroachdb-secure.md, _includes/v22.1/orchestration/start-cockroachdb-secure.md
=> [DOC-296] Add info about deploying manual StatefulSet into a different namespace

_includes/v22.1/performance/lease-preference-system-database.md
=> Disable zone config after schema update.

v22.1/alter-type.md
=> Expand on why you can cancel alter type that drops enum values.

v22.1/alter-primary-key.md
Fix the output to match current behavior.
=> Fix output.

v22.1/explain.md
=> Add Explain Alter example.

v22.1/alter-index.md, v22.1/alter-table.md, v22.1/split-at.md, v22.1/unsplit-at.md
=> Improve ALTER INDEX and UNSPLIT AT. Doc UNSPLIT ALL.

cockroachcloud/alerts-page.md
https://cockroachlabs.atlassian.net/browse/DOC-4978
=> Add note that CC admins receive alerts for minor upgrades

_includes/v22.1/performance/statement-contention.md, _includes/v22.1/sql/select-for-update-example-partial.md, netlify/vale/vocab.txt, v22.1/crdb-internal.md, v22.1/select-for-update.md
=> Add docs on crdb_internal.cluster_locks

cockroachcloud/quickstart.md
=> Fix quickstart page typo

_includes/cockroachcloud/private-preview.md, cockroachcloud/cloud-sso.md
[DOC-5351]
https://deploy-preview-14827--cockroachdb-docs.netlify.app/docs/cockroachcloud/managing-cmek
https://deploy-preview-14827--cockroachdb-docs.netlify.app/docs/cockroachcloud/export-logs
https://deploy-preview-14827--cockroachdb-docs.netlify.app/docs/cockroachcloud/cloud-sso
=> [DOC-5351] Update language for private previews

releases/index.md
=> Change download links for SQL shells to archives/tarballs

releases/cloud.md
Just a quick version update. One day this will be automated...
=> Cloud on 22.1.5

v22.1/cockroach-debug-encryption-active-key.md, v22.1/disaster-recovery.md, v22.1/hashicorp-integration.md, v22.1/recommended-production-settings.md, v22.1/security-reference/security-overview.md, v22.2/cockroach-debug-encryption-active-key.md, v22.2/disaster-recovery.md, v22.2/hashicorp-integration.md, v22.2/recommended-production-settings.md, v22.2/security-reference/security-overview.md
=> [DOC-2772] Get consistent about Encryption At Rest / In Flight terminology

StyleGuide.md
=> DOC-2321: Add instructions on using filter tabs

_config_base.yml, _data/releases.csv, _includes/releases/v21.2/v21.2.15.md
https://cockroachlabs.atlassian.net/browse/DOC-1902
=> v21.2.15 release notes

StyleGuide.md
=> Remove non-public content

v21.2/cost-based-optimizer.md, v22.1/cost-based-optimizer.md, v22.2/cost-based-optimizer.md
Fixes [DOC-5265](https://cockroachlabs.atlassian.net/browse/DOC-5265).
=> clarify query plan cache behavior

_includes/v22.1/performance/statement-contention.md, _includes/v22.2/performance/statement-contention.md, v22.1/error-handling-and-troubleshooting.md, v22.1/query-behavior-troubleshooting.md, v22.2/error-handling-and-troubleshooting.md, v22.2/query-behavior-troubleshooting.md
=> Add long running transactions KB

v22.1/row-level-ttl.md, v22.2/row-level-ttl.md
=> Clarify that outbox use case for TTL requires CDC

cockroachcloud/billing-management.md
https://cockroachlabs.atlassian.net/browse/CC-7167
And "Credits" is capitalized
=> Change CRCC to Credits

v22.1/serial.md, v22.2/serial.md
refs https://github.com/cockroachdb/cockroach/issues/87290
=> Fix options for serial_normalization

_config_base.yml, _data/releases.csv, _includes/releases/v22.2/v22.2.0-alpha.3.md, netlify/vale/vocab.txt
=> Add release notes for v22.2.0-alpha.3

v22.1/performance-benchmarking-with-tpcc-local-multiregion.md, v22.2/performance-benchmarking-with-tpcc-local-multiregion.md
=> Update multiregion TPCC instructions

_includes/footer.html, _includes/main-menu-serverless.html, _includes/sidebar.html, _includes/unsupported-version-soon.md, _includes/unsupported-version.md, _layouts/default.html, _layouts/page.html
Fixes DOC-5659 and the following:
- Tidies up the default and page layouts
- Moves certain elements to include_cached for better performance
=> DOC-5659: Excluded the sidebar from search engine indexing

Makefile, githooks/pre-commit
=> DEVINF-446: Block AWS credentials from being committed

_config_base.yml, _data/releases.csv, _includes/releases/v22.1/v22.1.7.md, netlify/vale/vocab.txt
=> Add v22.1.7 release notes

cockroachcloud/migrations-page.md, v21.2/migration-overview.md, v22.1/migration-overview.md, v22.2/migration-overview.md
- Add Molt naming
- Clarify edit/save functionality on SCT
=> Molt + clarify Edit/Save functionality

v22.2/crdb-internal.md
=> Update column name.

_config_base.yml, _data/releases.csv, _includes/releases/v22.2/v22.2.0-alpha.4.md, netlify/vale/vocab.txt
=> Release notes for CockroachDB v22.2.0-alpha.4

cockroachcloud/quickstart.md
=> Link to updated videos in Quickstart

_redirects, v21.2/migrate-from-mysql.md, v21.2/migrate-from-oracle.md, v21.2/migrate-from-postgres.md, v21.2/migration-overview.md, v22.1/migrate-from-mysql.md, v22.1/migrate-from-oracle.md, v22.1/migrate-from-postgres.md, v22.1/migration-overview.md, v22.2/migrate-from-mysql.md, v22.2/migrate-from-oracle.md, v22.2/migrate-from-postgres.md, v22.2/migration-overview.md
=> redirect away from stale migration pages; add clearer callout

_includes/releases/release-downloads-docker-image.md, releases/index.md
[releases/releases.md](https://deploy-preview-15208--cockroachdb-docs.netlify.app/docs/releases/releases.html)
[releases/index.md](https://deploy-preview-15208--cockroachdb-docs.netlify.app/docs/releases/index.html)
=> Followup after [DOC-4748]

_includes/common/ui/statements-page.md
=> Use $1 as placeholder.

_includes/common/ui/statements-page.md
DOC-5749
Corrects https://github.com/cockroachdb/docs/pull/15219
=> Fix fingerprints.

v22.2/show-backup.md
=> Fix path to diagram.

_layouts/default.html, _layouts/page.html, css/components/_toc.scss, css/customstyles.scss, js/customscripts.js, v20.1/foreign-key.md, v21.2/foreign-key.md, v22.1/foreign-key.md, v22.2/foreign-key.md
Feats:
- improve cls on toc
fix:
- contain youtube videos properly
=> feat: Improve cls on toc

v22.1/build-a-rust-app-with-cockroachdb.md, v22.2/build-a-rust-app-with-cockroachdb.md
=> Updated rust simple CRUD topic for new code and full support.

cockroachcloud/cloud-sso.md
https://cockroachlabs.atlassian.net/browse/DOC-5308
=> add couple of FAQ items to cloud SSO FAQ

_config_base.yml, _data/releases.csv, _includes/releases/v21.2/v21.2.16.md
=> Add release notes for v21.2.16

_layouts/page.html
Fix:
- Show contribute btn also when right toc not available
=> fix: show contribute when no right toc available

cockroachcloud/alerts-page.md
Previously we added additional customer alerts in managed-service/10041, we are looking to add these options to the docs to reflect these changes.
=> alerts: add additional options for alert types

v22.2/ui-statements-page.md, v22.2/ui-transactions-page.md
Add icons to features new in 22.2.
=> Add new in icons.

v21.2/aws-dms.md, v22.1/aws-dms.md
After https://github.com/cockroachdb/cockroach/issues/88229, we want to advertise a higher minimum version.
=> update minimum recommended versions for AWS DMS

cockroachcloud/migrations-page.md
Reflects UX change in https://github.com/cockroachlabs/managed-service/pull/10148
=> remove finalize modal step

_includes/main-menu-serverless.html
Fixes this: https://app.asana.com/0/1199169690303781/1203118067492693/f
=> Update link to Start Instantly

cockroachcloud/migrate-from-serverless-to-dedicated.md
Resolves https://cockroachlabs.atlassian.net/browse/DOC-5805.
=> replace IMPORT TABLE on Migrate from Serverless doc

v21.2/aws-dms.md, v22.1/aws-dms.md, v22.2/aws-dms.md
Addresses further comments in https://github.com/cockroachdb/docs/pull/15098.
=> follow-up corrections to AWS DMS docs

_config_base.yml, _data/releases.csv, _includes/releases/v22.2/v22.2.0-beta.3.md
Fixes [DOC-4605](https://cockroachlabs.atlassian.net/browse/DOC-4605)
=> Release notes for v22.2.0-beta.3

cockroachcloud/create-a-serverless-cluster.md, cockroachcloud/create-your-cluster.md, cockroachcloud/frequently-asked-questions.md
=> Clarify how Cloud interacts with cloud providers

_includes/common/quickstart/start-demo.md, cockroachcloud/quickstart.md
Fixes DOC-5875.
The companion code PR should merge at the same time as these changes. https://github.com/cockroachdb/quickstart-code-samples/pull/9
=> Fixing language visibility for local demo clusters

_config_base.yml, _data/releases.csv, _includes/releases/v22.2/v22.2.0-beta.4.md
[DOC-4576]
[releases/v22.2.md](https://deploy-preview-15369--cockroachdb-docs.netlify.app/docs/releases/v22.2.html)
=> [DOC-4606] Release notes for v22.2.0-beta.4

advisories/a88993.md
Relates to [DOC-4576]
[advisories/a88993.md](https://deploy-preview-15384--cockroachdb-docs.netlify.app/docs/advisories/a88993.html)
=> Add TA-88993

_includes/v22.1/misc/tooling.md, _includes/v22.2/misc/tooling.md
=> Adding link to Terraform provider

v22.2/sql-feature-support.md
=> Add docs for `CREATE EXTENSION "uuid-ossp"`

_includes/sidebar-data-cockroachcloud.json, _includes/v22.1/sidebar-data/manage.json, _includes/v22.2/sidebar-data/manage.json
[Preview](https://deploy-preview-15412--cockroachdb-docs.netlify.app/docs/cockroachcloud/cloud-org-audit-logs.html)
=> Add cloud org audit log page to the correct navs

v22.1/connection-pooling.md, v22.1/performance-best-practices-overview.md, v22.1/upsert.md, v22.2/connection-pooling.md, v22.2/performance-best-practices-overview.md, v22.2/upsert.md
=> Add links to blog

js/customscripts.js, search.html
Reverts cockroachdb/docs#15437
=> Revert "Update search page to bring users to /dev and /stable instead of /vXX.Y"

js/customscripts.js, search.html
I found the original problem. `customscripts.js` had a debug statement that caused that JS component to fail to load properly. This should now fix it.
=> Take two: update search paths to /dev and /stable from /vXX.Y

v22.1/cockroach-sql-binary.md, v22.2/cockroach-sql-binary.md
=> Fixing Mac install instructions for cockroach-sql

_data/products.yml
https://cockroachlabs.atlassian.net/browse/DOC-5939
=> Decapitalize product names

advisories/a88042.md
[DOC-5725]
[advisories/a88042.md](https://deploy-preview-15464--cockroachdb-docs.netlify.app/docs/advisories/a88042.html)
=> [DOC-5725] Publish TA-88042

_includes/v22.1/prod-deployment/provision-disk-io.md, _includes/v22.1/prod-deployment/provision-storage.md, _includes/v22.2/prod-deployment/provision-disk-io.md, _includes/v22.2/prod-deployment/provision-storage.md, v22.1/common-issues-to-monitor.md, v22.1/recommended-production-settings.md, v22.2/common-issues-to-monitor.md, v22.2/recommended-production-settings.md
[DOC-5841]
[v22.1/recommended-production-settings.md](https://deploy-preview-15410--cockroachdb-docs.netlify.app/docs/v22.1/recommended-production-settings.html)
[v22.1/common-issues-to-monitor.md](https://deploy-preview-15410--cockroachdb-docs.netlify.app/docs/v22.1/common-issues-to-monitor.html)
[v22.2/recommended-production-settings.md](https://deploy-preview-15410--cockroachdb-docs.netlify.app/docs/v22.2/recommended-production-settings.html)
[v22.2/common-issues-to-monitor.md](https://deploy-preview-15410--cockroachdb-docs.netlify.app/docs/v22.2/common-issues-to-monitor.html)
=> [DOC-5841] Update storage density recommendations

advisories/a88042.md
[DOC-5725]
[advisories/a88042.md](https://deploy-preview-15467--cockroachdb-docs.netlify.app/docs/advisories/a88042.html)
=> Followup after [DOC-5725]

advisories/a88042.md
Hopefully the last one.
[DOC-5725]
=> Followup to [DOC-5725]

v22.1/kubernetes-overview.md, v22.2/kubernetes-overview.md
[DOC-6045]
Also fixes some unrelated whitespace issues in the same files
=> [DOC-6045] Remove stray sentence fragment

v22.2/cost-based-optimizer.md
=> document non-default stats retention

v22.2/show-statistics.md
=> enhance WITH FORECAST docs

_includes/v22.1/ui/statements-filter.md, _includes/v22.1/ui/transactions-filter.md, _includes/v22.2/ui/statements-filter.md, _includes/v22.2/ui/transactions-filter.md
Addresses: DOC-6008
- Trivial typo fix `present` --> `preset`
Staging:
- [v22.2/ui/statements-filter.md](https://deploy-preview-15446--cockroachdb-docs.netlify.app/docs/cockroachcloud/statements-page.html#time-interval)
- [v22.2/ui/transactions-filter.md](https://deploy-preview-15446--cockroachdb-docs.netlify.app/docs/cockroachcloud/transactions-page.html#time-interval)
=> DOC-6008 typo present to preset

v21.2/ui-custom-chart-debug-page.md, v22.1/ui-custom-chart-debug-page.md, v22.2/ui-custom-chart-debug-page.md
Addresses: DOC-1449 
- Added mention of new feature: drag within a Custom Chart to set a custom time range.
- Feautre backported through to v21.2, so including this text backwards likewise.
Staging:
- [ui-custom-chart-debug-page.md](https://deploy-preview-15461--cockroachdb-docs.netlify.app/docs/stable/ui-custom-chart-debug-page.html#use-the-custom-chart-page)
=> DOC-1449 new custom drag time selection

releases/index.md
[DOC-6042]
[releases/index.md](https://deploy-preview-15546--cockroachdb-docs.netlify.app/docs/releases/index.html)
=> [DOC-6042] Fix Docker table

cockroachcloud/configure-cloud-org-sso.md
=> [DOC-5454] Followup

_includes/v22.1/prod-deployment/provision-storage.md, _includes/v22.2/prod-deployment/provision-storage.md, cockroachcloud/create-your-cluster.md, v22.1/recommended-production-settings.md, v22.2/recommended-production-settings.md
[DOC-5841]
[cockroachcloud/create-your-cluster.md](https://deploy-preview-15480--cockroachdb-docs.netlify.app/docs/cockroachcloud/create-your-cluster.html)
[v22.2/recommended-production-settings.md](https://deploy-preview-15480--cockroachdb-docs.netlify.app/docs/v22.2/recommended-production-settings.html)
[v22.1/recommended-production-settings.md](https://deploy-preview-15480--cockroachdb-docs.netlify.app/docs/v22.1/recommended-production-settings.html)
=> Followup to [DOC-5841]

cockroachcloud/serverless-faqs.md
https://cockroachlabs.atlassian.net/browse/DOC-5887
=> Clarify that we don't support an http api for serverless

v22.1/licensing-faqs.md
The text comes from Dan Hegwood.
=> licensing faq: add note on patents

cockroachcloud/optimize-serverless-workload.md
https://cockroachlabs.atlassian.net/browse/DOC-6141
=> Clarify serverless workload costs

v22.1/cockroach-debug-zip.md
Addresses: DOC-5919
- Mostly just a verbatim backport of #15404 , with the following tweak:
- Small copy change to `--redact-logs` entry: it is not entirely replaced by `--redact` as in v22.2. Still listing as deprecated.
- Thanks for great notes to [#88739](https://github.com/cockroachdb/cockroach/pull/88739)! I have opted not to include specific redaction / omission differences between v22.2 and v22.1 implementation of this feature, as noted in your desc, until we have the list of redacted / omissions for v22.2 that I understand is in the works. Once ready, I'll update each with their respective lists. Hope this makes sense!
Staging:
[v22.1/cockroach-debug-zip.md](https://deploy-preview-15598--cockroachdb-docs.netlify.app/docs/stable/cockroach-debug-zip.html)
=> DOC-5919 debug zip redact backport 22.1

_config_base.yml, _data/releases.csv, _includes/releases/v22.1/v22.1.11.md
Fixes [DOC-4579](https://cockroachlabs.atlassian.net/browse/DOC-4579)
=> Release notes v22.1.11

v22.2/common-table-expressions.md
DOC-4747
Add an example of a loose index scan using a recursive CTE.
=> loose index scan with recursive CTE

_includes/cockroachcloud/ccloud/install-ccloud.md, cockroachcloud/ccloud-get-started.md
This PR bumps the ccloud version and adds a section on disabling telemetry events.
=> Bump version and add section on disabling telemetry.

_includes/v22.2/sql/privileges.md, v21.2/revoke.md, v22.1/grant.md, v22.2/grant.md, v22.2/revoke.md, v22.2/schema-design-overview.md
DOC-4757
DOC-3469
DOC-3470
- Document syntax for sequence grant/revoke
- Add sequences to privileges list where applicable
- Make some opportunistic corrections and small improvements to the corresponding SQL docs
=> sequence grants; grant and revoke corrections

_config_base.yml, _data/releases.csv, _includes/releases/v22.2/v22.2.0-rc.3.md
Closes [DOC-6216](https://cockroachlabs.atlassian.net/browse/DOC-6216)
=> V22.2.0 rc.3 release notes

_includes/v21.1/orchestration/kubernetes-limitations.md, _includes/v21.1/orchestration/start-cockroachdb-helm-secure.md, _includes/v21.2/orchestration/kubernetes-limitations.md, _includes/v21.2/orchestration/start-cockroachdb-helm-secure.md, _includes/v22.1/orchestration/kubernetes-limitations.md, _includes/v22.1/orchestration/start-cockroachdb-helm-secure.md, _includes/v22.2/orchestration/kubernetes-limitations.md, _includes/v22.2/orchestration/start-cockroachdb-helm-secure.md
[DOC-6183]
[v21.1/deploy-cockroachdb-with-kubernetes-insecure.md](https://deploy-preview-15664--cockroachdb-docs.netlify.app/docs/v21.1/deploy-cockroachdb-with-kubernetes-insecure.html)
[v21.1/deploy-cockroachdb-with-kubernetes.md](https://deploy-preview-15664--cockroachdb-docs.netlify.app/docs/v21.1/deploy-cockroachdb-with-kubernetes.html)
[v21.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md](https://deploy-preview-15664--cockroachdb-docs.netlify.app/docs/v21.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.html)
[v21.1/orchestrate-a-local-cluster-with-kubernetes.md](https://deploy-preview-15664--cockroachdb-docs.netlify.app/docs/v21.1/orchestrate-a-local-cluster-with-kubernetes.html)
[v21.2/deploy-cockroachdb-with-kubernetes-insecure.md](https://deploy-preview-15664--co …
=> [DOC-6183] Add clarifying language about Helm support

Makefile, _includes/head.html, css/global/_fonts.scss, css/global/_variables.scss
Fix:
- Stop loading fonts from 2 places
- Use CDN from google with the just needed fonts
=> fix: fonts improvement

cockroachcloud/serverless-faqs.md
https://cockroachlabs.atlassian.net/browse/DOC-5895
=> Add serverless faq on increasing storage

cockroachcloud/frequently-asked-questions.md, cockroachcloud/quickstart-trial-cluster.md
https://cockroachlabs.atlassian.net/browse/DOC-3278
Just some minor additions to prompt trial dedicated users to create multi-region clusters
=> Promote multi-region trial clusters on CockroachDB dedicated

v22.1/local-testing.md, v22.2/local-testing.md
The setting has been removed in v22.1.
=> Remove schemachanger.backfiller.buffer_increment in docs

_includes/v22.2/sidebar-data/manage.json, cockroachcloud/upgrade-to-v22.1.md, cockroachcloud/upgrade-to-v22.2.md
This PR adds instructions for Dedicated users to upgrade their clusters to v22.2.
Closes DOC-5808.
=> Upgrade Dedicated clusters to v22.2

v22.1/licensing-faqs.md, v22.2/licensing-faqs.md
https://cockroachlabs.atlassian.net/browse/DOC-5818
=> Update licensing timeline for 22.2 GA

cockroachcloud/create-a-serverless-cluster.md, cockroachcloud/create-your-cluster.md, cockroachcloud/frequently-asked-questions.md, cockroachcloud/serverless-faqs.md
https://cockroachlabs.atlassian.net/browse/DOC-5794
List of available regions.
=> List available cloud regions

_includes/v21.2/sidebar-data/manage.json, _includes/v22.1/sidebar-data/manage.json, _includes/v22.2/sidebar-data/manage.json, v21.2/restore.md, v21.2/restoring-backups-across-versions.md, v22.1/restore.md, v22.1/restoring-backups-across-versions.md, v22.2/restore.md, v22.2/restoring-backups-across-versions.md
Fixes [DOC-1221](https://cockroachlabs.atlassian.net/browse/DOC-1221)
Initial draft policy for restoring backups across major versions.
https://deploy-preview-15447--cockroachdb-docs.netlify.app/docs/dev/restoring-backups-across-versions.html
=> Docs for restoring backups across versions

v21.2/owner-to.md, v22.1/owner-to.md, v22.2/owner-to.md
=> update OWNER TO coverage

v21.2/build-a-nodejs-app-with-cockroachdb-knexjs.md, v22.1/build-a-nodejs-app-with-cockroachdb-knexjs.md, v22.2/build-a-nodejs-app-with-cockroachdb-knexjs.md
https://cockroachlabs.atlassian.net/browse/DOC-6169
`npm run` has to be changed to `npm start`
once https://github.com/cockroachlabs/example-app-node-knex/pull/4 is merged
=> Fix knex example app npm run command

_includes/v22.2/sql/select-for-update-overview.md, v22.2/select-for-update.md
=> support SKIP LOCKED

v22.2/expression-indexes.md, v22.2/partial-indexes.md, v22.2/trigram-indexes.md
DOC-5262
- Updated several examples that became outdated due to this change. 
- Made a few opportunistic updates to example output that also seemed incorrect/out of date.
=> update EXPLAIN example output

v22.2/inverted-indexes.md, v22.2/trigram-indexes.md
[DOC-3816](https://cockroachlabs.atlassian.net/browse/DOC-3816)
=> jsonb_ops and array_ops opclasses

_includes/v22.2/metric-names.md
Addresses: DOC-3462
- Going to start merging metrics additions directly; they don't appear to interest many reviewers.
=> DOC-3462 sql txn contended metric

_includes/v22.2/metric-names.md
Manual fix for now, per comment to https://github.com/cockroachdb/docs/pull/15827. TY Ryan.
=> Fix upstream phrasing

v22.2/upgrade-cockroach-version.md
=> schema change jobs during upgrade finalization

v22.2/joins.md
DOC-5302
@DrewKimball After looking through the test data in your PR, it seemed most straightforward to use parts of your PR description for the doc. I left two inline comments (questions) for you below.
=> lookup joins with inequality filters

_includes/v22.1/prod-deployment/insecure-scale-cluster.md, _includes/v22.1/prod-deployment/insecure-start-nodes.md, _includes/v22.1/prod-deployment/insecurecockroachdb.service, _includes/v22.1/prod-deployment/securecockroachdb.service, _includes/v22.2/prod-deployment/insecure-scale-cluster.md, _includes/v22.2/prod-deployment/insecure-start-nodes.md, _includes/v22.2/prod-deployment/insecurecockroachdb.service, _includes/v22.2/prod-deployment/securecockroachdb.service
=> Update recommended TimeoutStopSec to 300 seconds

advisories/a93314.md
Addresses: DOC-6449
- Added TA-93314
Staging
[a93314.md](https://deploy-preview-15915--cockroachdb-docs.netlify.app/docs/advisories/a93314)
=> DOC-6449 TA-93314

_includes/nav-product.html
Closes #15545 
I have increased the margin between the buttons 'Our Product' and 'Pricing'. Kindly review and merge the PR
=> Increased the margin between the buttons

_includes/v22.1/cdc/note-changefeed-message-page.md, _includes/v22.2/cdc/note-changefeed-message-page.md, v22.1/changefeed-sinks.md, v22.2/changefeed-messages.md, v22.2/changefeed-sinks.md
Fixes DOC-6225
Added examples of message output format for each of the sinks.
https://deploy-preview-15848--cockroachdb-docs.netlify.app/docs/stable/changefeed-sinks.html#pub-sub-sink-messages
=> Added changefeed message output to the sink page for examples

_includes/v21.2/sql/global-table-description.md, _includes/v22.1/sql/global-table-description.md, _includes/v22.2/sql/global-table-description.md, v21.2/global-tables.md, v21.2/multiregion-overview.md, v22.1/follower-reads.md, v22.1/global-tables.md, v22.1/multiregion-overview.md, v22.2/follower-reads.md, v22.2/global-tables.md, v22.2/multiregion-overview.md
Fixes DOC-6501
- Update 'Global Tables' page with a 'Troubleshooting > High follower read latency on global tables' section that describes the problem and solution
- Add more linkage from 'Multiregion Overview' to 'Global Tables', so people can find this information
- Add more linkage from 'Follower Reads' to 'Global Tables' so people can find this
=> Troubleshooting follower reads on global tables

css/layouts/_sidebar.scss
Fix
- Add a max width to the sidebar to avoid layout jump
=> fix: add max width to sidebar

cockroachcloud/ccloud-get-started.md
This PR includes fixes from Cameron's feedback that came in after I had merged the original PR.
=> Updates to ccloud SSO docs

_includes/head.html
Fixes DOC-5851
I've added comments in the event we want to put it back.
=> DOC-5851: Undo noindex in the docs

_includes/cockroachcloud/ccloud/install-ccloud.md
=> Bump ccloud version to 0.3.7

cockroachcloud/optimize-serverless-workload.md
A minor code error was found after merging the previous PR. This PR fixes it.
=> Minor SQL code fix.

_redirects, cockroachcloud/jobs-page.md
- Remove redirect - Closes DOC-5825.
- Update liquid - Closes DOC-5824.
=> Minor updates for v22.2 as stable

v22.2/error-handling-and-troubleshooting.md
=> Fix SCRAM downgrade instructions

_data/products.yml
https://cockroachlabs.atlassian.net/browse/DOC-6658
=> Capitalize product names

v22.1/changefeed-examples.md, v22.2/changefeed-examples.md
=> Add Linux flag to base64 command PubSub

v19.1/cost-based-optimizer.md, v19.2/cost-based-optimizer.md, v20.1/cost-based-optimizer.md, v20.2/cost-based-optimizer.md, v21.1/cost-based-optimizer.md, v21.2/cost-based-optimizer.md, v22.1/cost-based-optimizer.md, v22.2/cost-based-optimizer.md
[DOC-5679](https://cockroachlabs.atlassian.net/browse/DOC-5679)
=> update join hint example

v21.2/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md, v22.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md, v22.2/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
[DOC-1629](https://cockroachlabs.atlassian.net/browse/DOC-1629)
[DOC-5607](https://cockroachlabs.atlassian.net/browse/DOC-5607)
=> correct step in EKS multi-region doc

v22.2/upgrade-cockroach-version.md
[DOC-6330](https://cockroachlabs.atlassian.net/browse/DOC-6330)
cc @mdlinville for visibility
=> remove 'v' from downgrade version variable

StyleGuide.md, v22.2/api-support-policy.md, v22.2/kubernetes-performance.md, v22.2/monitoring-and-alerting.md, v22.2/performance.md, v22.2/schema-design-database.md, v22.2/schema-design-indexes.md, v22.2/schema-design-schema.md, v22.2/schema-design-table.md, v22.2/schema-design-update.md, v22.2/security-reference/security-overview.md
[DOC-2070](https://cockroachlabs.atlassian.net/browse/DOC-2070)
=> add possession rule & update punctuation

_includes/v21.2/misc/delete-statistics.md, _includes/v22.1/misc/delete-statistics.md, _includes/v22.2/misc/delete-statistics.md
[DOC-5347](https://cockroachlabs.atlassian.net/browse/DOC-5347)
=> remove outdated delete statistics guidance

_includes/v21.2/prod-deployment/synchronize-clocks.md, _includes/v22.1/prod-deployment/synchronize-clocks.md, _includes/v22.2/prod-deployment/synchronize-clocks.md
[DOC-5832](https://cockroachlabs.atlassian.net/browse/DOC-5832)
=> fix Azure deploy string

v22.1/show-create.md
Fixes DOC-5962
Relates to DOC-2589
=> SHOW CREATE v22.1+ does not show single col fams

_includes/v22.2/sql/unsupported-postgres-features.md
=> Update PG compat page to mention UDFs

_includes/v22.2/ui/statistics.md
=> Update link name on SQL stmts page

v22.1/restore.md, v22.2/restore.md
=> Add PITR example when there is no rev history in backup

cockroachcloud/cluster-management.md
https://cockroachlabs.atlassian.net/browse/DOC-6123
Add requested details to remove region functionality for dedicated clusters
=> Add detail to remove region for dedicated

v22.2/cockroachdb-in-comparison.md
=> Update MongoDB comparison info

advisories/a96029.md
Addresses: DOC-6696
- Publish TA-96029
- To be updated again once v22.2.4 is released.
Staging
[a96029.md](https://deploy-preview-16139--cockroachdb-docs.netlify.app/docs/advisories/a96029)
=> DOC-6696 publish TA-96029

v22.2/security-reference/scram-authentication.md
=> SCRAM doesn't work with Looker/Google Data Studio

Gemfile, build/build-cloudflare.sh, build/build-vercel.sh, css/bs/_card.scss, css/bs/_carousel.scss, css/bs/_custom-forms.scss, css/bs/_forms.scss, css/bs/_functions.scss, css/bs/_images.scss, css/bs/_jumbotron.scss, css/bs/_modal.scss, css/bs/_popover.scss, css/bs/_tooltip.scss, css/bs/_variables.scss, css/bs/mixins/_forms.scss, css/bs/mixins/_grid-framework.scss, css/bs/mixins/_grid.scss, css/bs/utilities/_embed.scss, css/bs/vendor/_rfs.scss
Reverts cockroachdb/docs#15994
Also forces us onto an older version of jekyll-sass-converter
Also forces the versions plug-in to do a hard copy instead of a symbolic link
=> Revert "Fix deprecated SASS syntax to help reduce Netlify build log size"

StyleGuide.md
=> Add style guide rule about using "we"

v22.1/create-user.md, v22.2/create-user.md
Addresses DOC-5839:
- usernames cannot start with a letter
- fixed v22.2, v22.1
Preview:
- [Create User](https://deploy-preview-16099--cockroachdb-docs.netlify.app/docs/stable/create-user.html#create-a-user)
=> [DOC-5839] fixed username constraints

_config_base.yml, _data/releases.csv, _includes/releases/v22.1/v22.1.14.md
https://cockroachlabs.atlassian.net/browse/DOC-6400
=> v22.1.14 release notes

v22.2/alter-database.md, v22.2/alter-table.md
- Fixed a link that was pointing to the wrong subheading.
- Fixed a parameter description that was incorrect.
=> fix link and parameter

v22.1/aws-dms.md
This PR contains the commit from https://github.com/cockroachdb/docs/pull/16128 that pertains specifically to v22.1.14+.
=> add DMS session var workaround for 22.1.14

_config_base.yml, _data/releases.csv, _includes/releases/v22.2/v22.2.4.md, v23.1/spatial-tutorial.md
=> Add v22.2.4 release notes

v22.2/security-reference/scram-authentication.md, v23.1/security-reference/scram-authentication.md
=> Add note re: SCRAM auth vs. Amazon Quicksight

v22.2/aws-dms.md
This PR contains the commit from https://github.com/cockroachdb/docs/pull/16128 that pertains specifically to v22.2.4+.
=> add DMS session var workaround for 22.2.4

v22.2/grant.md, v23.1/grant.md
Fixes DOC-3192
- Update `GRANT` docs:
- Note that when a role/user is granted privileges for a database, new tables will *not* inherit those privileges
- Show how to grant all privileges on existing tables to User X
- Show how to make sure when a new table is created, all privileges on that table are granted to User X
- Update some SQL outputs to match the new reality
- Sprinkle some `IF NOT EXISTS` on a few SQL statements to make them ~idempotent for easier testing
=> Update GRANT re: v22.2+ DB privilege inheritance

v20.2/example-apps.md, v21.1/example-apps.md, v21.2/example-apps.md, v21.2/kubernetes-overview.md, v22.1/example-apps.md, v22.1/features-in-preview.md, v22.1/kubernetes-overview.md, v22.2/example-apps.md, v22.2/features-in-preview.md, v22.2/kubernetes-overview.md, v23.1/example-apps.md, v23.1/features-in-preview.md, v23.1/kubernetes-overview.md
=> DOC-6864: Tie renamed pages together in the version switcher

advisories/a97178.md
Add Technical Advisory 97178 from [draft text](https://docs.google.com/document/d/1a_fQX8NaHRwTW3deYOst-VPfBlS-FzxJT6521CGfwWs).
[advisories/a97178.md](https://deploy-preview-16277--cockroachdb-docs.netlify.app/docs/advisories/a97178.html)
=> Add A-97178

cockroachcloud/cluster-overview-page.md, cockroachcloud/connect-to-a-serverless-cluster.md, cockroachcloud/databases-page.md, cockroachcloud/jobs-page.md, cockroachcloud/migrations-page.md, cockroachcloud/monitoring-page.md, cockroachcloud/serverless-cluster-management.md, cockroachcloud/sessions-page.md, cockroachcloud/statements-page.md, cockroachcloud/transactions-page.md, cockroachcloud/use-managed-service-backups.md, cockroachcloud/user-authorization.md
https://cockroachlabs.atlassian.net/browse/DOC-6846
=> Update cloud docs for new sidebar organization

v22.2/inverted-indexes.md, v23.1/inverted-indexes.md
=> Link from inverted index to trigram index docs

_includes/sidebar-releases.json
=> DOC-6964: Fix an issue where advisories wouldn't appear in the sidenav

_redirects, v23.1/use-cloud-storage.md
Addresses DOC-6275
- continuation of changing the nav and renaming 'Use Cloud Storage' page
- fixes dropdown error for v23.1
=> DOC-6275 added key for v23

_includes/v22.1/performance/statement-contention.md, _includes/v22.2/performance/statement-contention.md, _includes/v23.1/performance/statement-contention.md, v22.1/cockroach-workload.md, v22.1/crdb-internal.md, v22.2/cockroach-workload.md, v22.2/crdb-internal.md, v23.1/cockroach-workload.md, v23.1/crdb-internal.md
Addresses some of the spirit of DOC-3395
Helps out with DOC-6663 and friends as well
=> crdb_internal.cluster_contention_events examples++

v22.1/use-cloud-storage-for-bulk-operations.md, v22.2/use-cloud-storage.md, v23.1/use-cloud-storage.md
Quick fix to alternate two sentences introducing object locking.
=> Correct sentence introducing object locking

StyleGuide.md
Completes **Docs Style Fixit 1/25/23** issue https://cockroachlabs.atlassian.net/browse/DOC-2075
=> Guidance on shortened product names

v22.2/cockroachdb-feature-availability.md, v23.1/cockroachdb-feature-availability.md
Quick follow for https://github.com/cockroachdb/docs/pull/16291
=> GTM - minor table update for consistency

_includes/head.html
Fixes DOC-2180
Partially fixes DOC-6886
=> DOC-2180: Added OpenGraph and Google site markup

cockroachcloud/cmek-faq.md
Update CMEK Faq
- Request: https://cockroachlabs.slack.com/archives/C02Q8MLFFE0/p1677380623240759
- Add two questions
- Update one question
- Reorganization
[cockroachcloud/cmek-faq.md](https://deploy-preview-16365--cockroachdb-docs.netlify.app/docs/cockroachcloud/cmek-faq.html)
=> Update CMEK FAQ

_includes/v22.2/misc/tooling.md, _includes/v23.1/misc/tooling.md, v22.2/aws-dms.md, v23.1/aws-dms.md
DOC-6170
- Add a step for data validation in DMS.
- Update DMS support level on the third-party tooling page to `Full` (v22.2 and v23.1).
=> DMS validation and support level

_includes/v22.1/topology-patterns/fundamentals.md, _includes/v22.2/topology-patterns/fundamentals.md, _includes/v23.1/topology-patterns/fundamentals.md, v22.1/recommended-production-settings.md, v22.2/recommended-production-settings.md, v23.1/recommended-production-settings.md
[DOC-273] Recommend homogenous cluster nodes
[v22.1/recommended-production-settings.md](https://deploy-preview-16354--cockroachdb-docs.netlify.app/docs/v22.1/recommended-production-settings.html)
[v22.1/topology-development.md](https://deploy-preview-16354--cockroachdb-docs.netlify.app/docs/v22.1/topology-development.html)
[v22.1/ui-network-latency-page.md](https://deploy-preview-16354--cockroachdb-docs.netlify.app/docs/v22.1/ui-network-latency-page.html)
[v22.1/topology-geo-partitioned-replicas.md](https://deploy-preview-16354--cockroachdb-docs.netlify.app/docs/v22.1/topology-geo-partitioned-replicas.html)
[v22.1/topology-follower-reads.md](https://deploy-preview-16354--cockroachdb-docs.netlify.app/docs/v22.1/topology-follower-reads.html) …
=> [DOC-273] Recommend homogenous cluster nodes

_config_base.yml, _data/releases.csv, _includes/releases/v22.2/v22.2.6.md
=> Release notes v22.2.6

v22.2/cost-based-optimizer.md, v23.1/cost-based-optimizer.md
Add guidance to which the error message for https://github.com/cockroachdb/cockroach/pull/97827 can be linked.
=> enhance guidance on enforce_home_region

_includes/v22.2/misc/tooling.md, _includes/v22.2/sidebar-data/migrate.json, _includes/v23.1/misc/tooling.md, _includes/v23.1/sidebar-data/migrate.json, v21.2/aws-dms.md, v22.1/aws-dms.md, v22.2/aws-dms.md, v22.2/qlik.md, v23.1/aws-dms.md, v23.1/qlik.md
DOC-6986
- Add a high-level page for Qlik Replicate.
- Update third-party tooling table.
- Adjust Migrate nav with third-party tooling options.
- Minor updates to DMS docs.
=> add Qlik page, adjust Migration nav, tweak DMS docs

_includes/v22.1/ui/index-details.md, _includes/v22.1/ui/statistics.md, _includes/v22.2/ui/index-details.md, _includes/v22.2/ui/statistics.md, _includes/v23.1/ui/index-details.md, _includes/v23.1/ui/statistics.md
Addresses: DOC-6621, DOC-6635, DOC-6667, DOC-6669
- Clarifies that the `reset SQL stats` link/button under **SQL Activity > Statements** and **SQL Activity > Transactions** is only shown for admin users.
- Clarifies that `Reset all index stats` link/button on the **Databases** page is only shown for admin users.
Question
- Is this change also appropriate for CC? I assumed: yes, and as such the change also appears [here](https://deploy-preview-16443--cockroachdb-docs.netlify.app/docs/cockroachcloud/statements-page.html#statement-statistics) and [here](https://deploy-preview-16443--cockroachdb-docs.netlify.app/docs/cockroachcloud/transactions-page.html#transaction-statistics) and [here](https://deploy-preview-16443--cockroachdb-docs.netlify.app/docs/cockroachcloud/databases-page.html#index-d …
=> DOC-6621, DOC-6635, DOC-6667, DOC-6669, admin reset sql stats

v22.2/pg-catalog.md, v22.2/set-vars.md, v23.1/pg-catalog.md, v23.1/set-vars.md
Fixes DOC-6448, DOC-6485, DOC-6474
=> Add pg_timezone_names info and example

v23.1/operational-faqs.md
=> Add details about time-series DB disk use to v23.1

_includes/v22.1/sidebar-data/reference.json, _includes/v22.2/sidebar-data/reference.json, _includes/v23.1/sidebar-data/reference.json, cockroachcloud/pci-dss.md
Fixes DOC-5240
[HTML Preview](https://deploy-preview-14741--cockroachdb-docs.netlify.app/docs/cockroachcloud/pci-dss)
=> [DOC-5240] Add PCI-DSS concept

_config_base.yml, _data/releases.yml, _includes/releases/v22.2/v22.2.7.md
This reverts commit 5e5153b0f8fa537ec08949915824c1101c2befa0.
=> Revert "Revert "v22.2.7 release notes (#16588)" (#16621)"

v22.1/authentication.md, v22.2/authentication.md, v23.1/authentication.md
=> Fix indentation to render codeblocks correctly

v22.1/export.md, v22.2/export.md, v23.1/export.md
=> Clarify that EXPORT doesn't require AOST

.github/workflows/master-to-main.yml
This can only be run by me while I test these changes.
=> Add master to main pipeline in GitHub

_includes/youtube.html, css/customstyles.scss, v20.1/foreign-key.md, v21.2/foreign-key.md, v22.1/foreign-key.md, v22.2/foreign-key.md, v22.2/online-schema-changes.md, v23.1/foreign-key.md, v23.1/online-schema-changes.md
=> Add video to Online Schema Changes

.github/workflows/master-to-main.yml
Further tweaks to the master-to-main pipeline
=> First commit with monorepo structure

_includes/v23.1/sql/shell-shortcuts.md
This PR adds new shortcuts in the v23.1 SQL shell.
Fixes DOC-7274.
=> New keyboard shortcuts in SQL shell

_data/releases.yml
=> DOC-7115: Add linux_intel_fips and linux_arm_fips to releases.yml

css/customstyles.scss
=> DOC-7423: Add overflow scrolling to all table elements

v22.2/error-handling-and-troubleshooting.md, v22.2/security-reference/scram-authentication.md, v23.1/error-handling-and-troubleshooting.md, v23.1/security-reference/scram-authentication.md
=> Update SCRAM docs on upgrade/downgrade procedure

_includes/cockroachcloud/ccloud/install-ccloud.md, v22.2/cockroach-sql-binary.md, v23.1/cockroach-sql-binary.md
=> Homebrew instructions for cockroach-sql

_includes/cockroachcloud/cc-no-user-certs.md, _includes/cockroachcloud/cockroachcloud-ask-admin.md, cockroachcloud/alerts-page.md, cockroachcloud/authorization.md, cockroachcloud/billing-management.md, cockroachcloud/cloud-org-sso.md, cockroachcloud/configure-cloud-org-sso.md, cockroachcloud/connect-to-a-serverless-cluster.md, cockroachcloud/connect-to-your-cluster.md, cockroachcloud/create-a-serverless-cluster.md, cockroachcloud/create-an-account.md, cockroachcloud/create-your-cluster.md, cockroachcloud/egress-perimeter-controls.md, cockroachcloud/export-logs.md, cockroachcloud/frequently-asked-questions.md, cockroachcloud/learn-about-pricing.md, cockroachcloud/managing-access.md, cockroachcloud/provision-a-cluster-with-terraform.md, cockroachcloud/upgrade-policy.md, cockroachcloud/upgrade-to-v20.1.md, cockroachcloud/upgrade-to-v20.2.md, cockroachcloud/upgrade-to-v21.1.md, cockroachcloud/upgrade-to-v21.2.md, cockroachcloud/upgrade-to-v22.1.md
[FGAC phase 1 follow up](https://cockroachlabs.atlassian.net/jira/software/c/projects/DOC/boards/239?modal=detail&selectedIssue=DOC-7458)
=> FGAC phase 1 follow up

_data/releases.yml, _includes/releases/current-cloud-version.md, _includes/releases/release-downloads-docker-image.md, _includes/unsupported-version.md, _redirects, releases/index.md, releases/v1.0.md, releases/v1.1.md, releases/v19.1.md, releases/v19.2.md, releases/v2.0.md, releases/v2.1.md, releases/v20.1.md, releases/v20.2.md, releases/v21.1.md, releases/v21.2.md, releases/v22.1.md, releases/v22.2.md, releases/v23.1.md, v21.1/upgrade-cockroach-version.md, v21.2/upgrade-cockroach-version.md, v22.1/upgrade-cockroach-version.md, v22.2/upgrade-cockroach-version.md, v23.1/upgrade-cockroach-version.md
=> DOC-7325: Rename variables to something more logical

_includes/v22.1/orchestration/kubernetes-upgrade-cluster-helm.md, _includes/v22.1/orchestration/kubernetes-upgrade-cluster-manual.md, _includes/v22.2/orchestration/kubernetes-upgrade-cluster-helm.md, _includes/v22.2/orchestration/kubernetes-upgrade-cluster-manual.md, _includes/v23.1/orchestration/kubernetes-upgrade-cluster-helm.md, _includes/v23.1/orchestration/kubernetes-upgrade-cluster-manual.md
Ref: https://cockroachlabs.slack.com/archives/C01PHNMUFLN/p1681692646576259
=> Fix cluster.preserve_downgrade_option examples

advisories/a99796.md
[DOC-7406] Publish A-99796
[advisories/a99796.md](https://deploy-preview-16770--cockroachdb-docs.netlify.app/docs/advisories/a99796.html)
=> [DOC-7406] Publish A-99796

_config_base.yml, _data/releases.yml, _includes/releases/v23.1/v23.1.0-beta.2.md
=> Add v23.1.0-beta.2 release notes

v23.1/online-schema-changes.md
=> Add statements automatically using Declartive Schema Changer

v23.1/alter-type.md, v23.1/create-type.md, v23.1/data-types.md, v23.1/drop-type.md, v23.1/enum.md, v23.1/grant.md, v23.1/revoke.md, v23.1/schema-design-table.md, v23.1/show-enums.md, v23.1/show-grants.md, v23.1/show-types.md
=> Add docs for user-defined composite types

_includes/releases/v22.2/v22.2.8.md, _includes/releases/v23.1/v23.1.0-alpha.9.md
=> Fix RN for prepared_statements_cache_size

v22.2/show-statements.md, v23.1/show-statements.md
=> Remove incorrect perms info from SHOW STATEMENTS

_includes/v22.2/misc/enterprise-features.md, _includes/v23.1/misc/enterprise-features.md, v22.1/licensing-faqs.md, v22.2/licensing-faqs.md, v23.1/licensing-faqs.md
=> Update licensing timeline for 23.1 GA

v23.1/cockroachdb-feature-availability.md
https://cockroachlabs.atlassian.net/browse/DOC-7563
=> Remove leftover features in limited access

_config_base.yml, _data/releases.yml, _includes/releases/v23.1/v23.1.0-rc.1.md, v23.1/set-cluster-setting.md
[DOC-6523] v23.1.0-rc.1 Release Notes
[releases/v23.1.md](https://deploy-preview-16871--cockroachdb-docs.netlify.app/docs/releases/v23.1.html)
=> [DOC-6523] v23.1.0-rc.1 Release Notes

_includes/common/basic-terms.md, _includes/v22.1/sidebar-data/manage.json, _includes/v22.2/sidebar-data/manage.json, _includes/v23.1/sidebar-data/manage.json, cockroachcloud/authentication.md, cockroachcloud/authorization.md, cockroachcloud/client-certs-dedicated.md, cockroachcloud/managing-access.md, cockroachcloud/security-overview.md, v21.2/security-reference/config-secure-hba.md, v22.1/manage-certs-vault.md, v23.1/managing-tls-certs-cli.html, v23.1/security-reference/transport-layer-security.md
https://cockroachlabs.atlassian.net/jira/software/c/projects/DOC/boards/239?modal=detail&selectedIssue=DOC-4832
=> Add client-certificate based authentication for CockroachDB Cloud

_config_base.yml, _data/releases.yml, _includes/releases/v23.1/v23.1.0-rc.2.md
=> v23.1.0-rc.2 release notes

_config_base.yml, v19.1/cluster-settings.md, v19.1/functions-and-operators.md, v19.2/cluster-settings.md, v19.2/functions-and-operators.md, v20.1/cluster-settings.md, v20.1/functions-and-operators.md, v20.2/alter-partition.md, v20.2/cluster-settings.md, v20.2/functions-and-operators.md, v21.1/alter-partition.md, v21.1/cluster-settings.md, v21.1/eventlog.md, v21.1/functions-and-operators.md
=> DOC-7380: Remove some tech debt around remote include branch names

_config_base.yml, _data/releases.yml, _includes/releases/v22.2/v22.2.9.md
=> Add release notes for v22.2.9

_includes/v22.1/misc/tooling.md, _includes/v22.2/misc/tooling.md, _includes/v23.1/misc/tooling.md
=> DOC-5491: Add definition of Partner supported

_data/releases.yml
The v22.2.8 release has been withdrawn.
=> Withdraw v22.2.8.

_includes/releases/cloud/2023-05-10.md, _includes/v22.2/misc/note-egress-perimeter-cdc-backup.md, _includes/v23.1/misc/note-egress-perimeter-cdc-backup.md, cockroachcloud/egress-perimeter-controls.md, v22.2/cockroachdb-feature-availability.md, v23.1/cockroachdb-feature-availability.md
Ref: https://cockroachlabs.slack.com/archives/C03GUEQ308N/p1683666753481909
[releases/cloud.md](https://deploy-preview-16916--cockroachdb-docs.netlify.app/docs/releases/cloud.html)
[v22.2/use-cloud-storage.md](https://deploy-preview-16916--cockroachdb-docs.netlify.app/docs/v22.2/use-cloud-storage.html)
[v22.2/changefeed-sinks.md](https://deploy-preview-16916--cockroachdb-docs.netlify.app/docs/v22.2/changefeed-sinks.html)
[v22.2/backup-and-restore-overview.md](https://deploy-preview-16916--cockroachdb-docs.netlify.app/docs/v22.2/backup-and-restore-overview.html)
[v23.1/use-cloud-storage.md](https://deploy-preview-16916--cockroachdb-docs.netlify.app/docs/v23.1/use-cloud-storage.html)
[v23.1/changefeed-sinks.md](https://deploy-preview-16916--cockroachdb-docs.netlify.app/docs/v23.1/changefeed- …
=> Egress Perimeter Controls GA

advisories/a102375.md
=> Publish A-102375

_config_base.yml, _data/releases.yml, _includes/releases/v22.1/v22.1.20.md
Preview:
- [v22.1.20](https://deploy-preview-16923--cockroachdb-docs.netlify.app/docs/releases/v22.1.html#v22-1-20)
=> v22.1.20 release notes

_includes/v23.1/sql/privileges.md, v23.1/upgrade-cockroach-version.md
Fixes DOC-7384.
Fixes DOC-7184.
=> Add v23.1 features that require finalization

_includes/v22.2/sql/privileges.md, _includes/v23.1/sql/privileges.md
fixes https://github.com/cockroachdb/docs/issues/14059
=> Remove GRANT privilege

v23.1/known-limitations.md
=> Add COPY known limitation

v23.1/known-limitations.md
Follow up to #16982
Sorry for being annoying and not catching that I wrote this in the wrong (Unresolved limitations) section
=> Move COPY KL up in list

_includes/cockroachcloud/nodes-limitation.md, _includes/feature-phases/azure-limited-access.md, _includes/v22.2/sidebar-data/deploy.json, _includes/v23.1/sidebar-data/deploy.json, build/build-netlify.sh, cockroachcloud/architecture.md, cockroachcloud/authentication.md, cockroachcloud/cloud-api.md, cockroachcloud/cluster-management.md, cockroachcloud/cmek.md, cockroachcloud/cockroachdb-dedicated-on-azure.md, cockroachcloud/connect-to-your-cluster.md, cockroachcloud/create-a-serverless-cluster.md, cockroachcloud/create-your-cluster.md, cockroachcloud/egress-perimeter-controls.md, cockroachcloud/export-logs.md, cockroachcloud/frequently-asked-questions.md, cockroachcloud/managing-cmek.md, cockroachcloud/network-authorization.md, cockroachcloud/pci-dss.md, cockroachcloud/private-clusters.md, cockroachcloud/provision-a-cluster-with-terraform.md, cockroachcloud/security-overview.md, cockroachcloud/use-managed-service-backups.md
[DOC-7183] Document CC on Azure Limited Access
- FAQs
- Limitations
- Cluster creation
- API doc updates
- Release note
[releases/cloud.md](https://deploy-preview-16893--cockroachdb-azure-docs.netlify.app/docs/releases/cloud.html)
[cockroachcloud/architecture.md](https://deploy-preview-16893--cockroachdb-azure-docs.netlify.app/docs/cockroachcloud/architecture.html)
[cockroachcloud/authentication.md](https://deploy-preview-16893--cockroachdb-azure-docs.netlify.app/docs/cockroachcloud/authentication.html)
[cockroachcloud/cloud-api.md](https://deploy-preview-16893--cockroachdb-azure-docs.netlify.app/docs/cockroachcloud/cloud-api.html)
[cockroachcloud/cluster-management.md](https://deploy-preview-16893--cockroachdb-azure-docs.netlify.app/docs/cockroachcloud/cluster-management.html) …
=> [DOC-7183] Document CC on Azure Limited Access cluster creation

v23.1/restoring-backups-across-versions.md
Discovered an extra period and removed it
Preview
https://deploy-preview-17005--cockroachdb-docs.netlify.app/docs/stable/upgrade-cockroach-version.html#back-up-cluster
=> DOC-6738 remove extra period

v22.2/drop-view.md, v23.1/drop-view.md
=> Updated example output for DROP VIEW

v23.1/copy-from.md
DOC-7662
The path to the COPY diagram was updated.
=> fix link to COPY diagram

_includes/v22.2/ui/statement-details.md, _includes/v23.1/ui/statement-details.md
Addresses: [DOC-7624](https://cockroachlabs.atlassian.net/browse/DOC-7624)
=> DOC-7624: Update Activate diagnostics collection with warning

_includes/v23.1/misc/debug-subcommands.md, _includes/v23.1/sidebar-data/reference.json, v23.1/cockroach-debug-encryption-decrypt.md
[DOC-5938] Document `debug encryption-decrypt` command
Main:
[v23.1/cockroach-debug-encryption-decrypt.md](https://deploy-preview-16978--cockroachdb-docs.netlify.app/docs/v23.1/cockroach-debug-encryption-decrypt.html)
Minor:
[v23.1/cockroach-debug-encryption-active-key.md](https://deploy-preview-16978--cockroachdb-docs.netlify.app/docs/v23.1/cockroach-debug-encryption-active-key.html)
[v23.1/cockroach-debug-merge-logs.md](https://deploy-preview-16978--cockroachdb-docs.netlify.app/docs/v23.1/cockroach-debug-merge-logs.html)
[v23.1/cockroach-debug-job-trace.md](https://deploy-preview-16978--cockroachdb-docs.netlify.app/docs/v23.1/cockroach-debug-job-trace.html)
[v23.1/cockroach-debug-zip.md](https://deploy-preview-16978--cockroachdb-docs.netlify.app/docs/v23.1/cockroach-debug-zip.html) …
=> [DOC-5938] Document debug encryption-decrypt command

cockroachcloud/cluster-management.md
=> azure link fix

_includes/v23.1/metric-names.md
[DOC-6547][DOC-6548] Metrics updates for v23.1
[v23.1/metrics.md](https://deploy-preview-17007--cockroachdb-docs.netlify.app/docs/v23.1/metrics.html)
[v23.1/ui-custom-chart-debug-page.md](https://deploy-preview-17007--cockroachdb-docs.netlify.app/docs/v23.1/ui-custom-chart-debug-page.html)
=> [DOC-6547][DOC-6548] Metrics updates for v23.1

_includes/v23.1/sidebar-data/deploy.json, cockroachcloud/create-a-serverless-cluster.md, cockroachcloud/create-your-cluster.md, cockroachcloud/frequently-asked-questions.md, cockroachcloud/regions.md
[DOC-7692] Create Cloud Regions page
[cockroachcloud/create-a-serverless-cluster.md](https://deploy-preview-17035--cockroachdb-docs.netlify.app/docs/cockroachcloud/create-a-serverless-cluster.html)
[cockroachcloud/create-your-cluster.md](https://deploy-preview-17035--cockroachdb-docs.netlify.app/docs/cockroachcloud/create-your-cluster.html)
[cockroachcloud/frequently-asked-questions.md](https://deploy-preview-17035--cockroachdb-docs.netlify.app/docs/cockroachcloud/frequently-asked-questions.html)
[cockroachcloud/regions.md](https://deploy-preview-17035--cockroachdb-docs.netlify.app/docs/cockroachcloud/regions.html)
=> [DOC-7692] Create Cloud Regions page

.github/workflows/pr-reviews.yml
This will allow for secrets to be used to run the script needed to check for the necessary PR reviews across forks.
Additionally, each time a commit is pushed or auto-merge is enabled, the script will run.
=> Update pr-reviews.yml to run on pull request target

_layouts/homepage.html
https://cockroachlabs.atlassian.net/browse/DOC-7761
=> Fix start a local cluster links on homepage

src/current/_includes/v21.2/prod-deployment/provision-cpu.md, src/current/_includes/v22.1/prod-deployment/provision-cpu.md, src/current/v22.2/common-issues-to-monitor.md, src/current/v22.2/recommended-production-settings.md, src/current/v23.1/common-issues-to-monitor.md, src/current/v23.1/recommended-production-settings.md
[DOC-7703] Strengthen the minimum vCPU requirement
[DOC-7745] Separate the vCPU minimum and maximum
- In Common Issues, separate the minimum and maximum into separate bullets.
- Add a new absolute minimum
- Move the maximum recommendation into an include
- Parameterize the include
[v23.1/common-issues-to-monitor.md](https://deploy-preview-17107--cockroachdb-docs.netlify.app/docs/v23.1/common-issues-to-monitor.html)
[v23.1/recommended-production-settings.md](https://deploy-preview-17107--cockroachdb-docs.netlify.app/docs/v23.1/recommended-production-settings.html)
[v22.2/common-issues-to-monitor.md](https://deploy-preview-17107--cockroachdb-docs.netlify.app/docs/v22.2/common-issues-to-monitor.html)
[v22.2/recommended-production-settings.md](https://deploy-preview-17107--cockroachdb-docs.net …
=> [DOC-7703][DOC-7745] Improve vCPU recommendations

src/current/v22.2/array.md, src/current/v23.1/array.md
Fixes [DOC-7598](https://cockroachlabs.atlassian.net/browse/DOC-7598)
=> Clarify which query operations GIN indexes accelerate for ARRAY columns

src/current/v21.1/alter-view.md, src/current/v21.2/alter-view.md, src/current/v22.1/alter-view.md, src/current/v22.2/alter-view.md, src/current/v23.1/alter-view.md
Reapplies changes in #17049 across all versions
=> Reapply #17049

src/current/v19.2/delete-data.md, src/current/v20.1/delete-data.md, src/current/v20.2/delete-data.md, src/current/v21.1/delete-data.md, src/current/v21.2/delete-data.md, src/current/v22.1/delete-data.md, src/current/v22.2/delete-data.md, src/current/v23.1/delete-data.md
Reapply the changes from #16954 to main
=> Reapply #16954

src/current/v21.2/security-reference/security-overview.md, src/current/v22.1/security-reference/security-overview.md, src/current/v22.2/security-reference/security-overview.md, src/current/v23.1/security-reference/security-overview.md
Reapply the changes in #16689 to main branch
=> Reapply #16689

src/current/v20.2/schema-design-overview.md, src/current/v21.1/schema-design-overview.md, src/current/v21.2/schema-design-overview.md, src/current/v22.1/schema-design-overview.md, src/current/v22.2/schema-design-overview.md, src/current/v23.1/schema-design-overview.md
=> Reapply #15356

src/current/v22.1/build-a-go-app-with-cockroachdb-gorm.md, src/current/v22.2/build-a-go-app-with-cockroachdb-gorm.md, src/current/v23.1/build-a-go-app-with-cockroachdb-gorm.md
=> Reapply #15452

src/current/_includes/v21.2/prod-deployment/recommended-instances-aws.md, src/current/_includes/v22.1/prod-deployment/recommended-instances-aws.md, src/current/_includes/v22.2/prod-deployment/recommended-instances-aws.md, src/current/_includes/v23.1/prod-deployment/recommended-instances-aws.md, src/current/v21.2/deploy-cockroachdb-on-aws.md, src/current/v21.2/recommended-production-settings.md, src/current/v22.1/deploy-cockroachdb-on-aws.md, src/current/v22.1/recommended-production-settings.md, src/current/v22.2/deploy-cockroachdb-on-aws.md, src/current/v22.2/recommended-production-settings.md, src/current/v23.1/deploy-cockroachdb-on-aws.md, src/current/v23.1/recommended-production-settings.md
=> Revert 16634

src/current/v1.0/monitor-cockroachdb-with-prometheus.md, src/current/v1.1/monitor-cockroachdb-with-prometheus.md, src/current/v19.1/monitor-cockroachdb-with-prometheus.md, src/current/v19.2/monitor-cockroachdb-with-prometheus.md, src/current/v2.0/monitor-cockroachdb-with-prometheus.md, src/current/v2.1/monitor-cockroachdb-with-prometheus.md, src/current/v20.1/monitor-cockroachdb-with-prometheus.md, src/current/v20.2/monitor-cockroachdb-with-prometheus.md, src/current/v21.1/monitor-cockroachdb-with-prometheus.md
Reapply #15171 to the main branch
=> Reapply #15171

src/current/v20.1/import-performance-best-practices.md, src/current/v20.2/import-performance-best-practices.md, src/current/v21.1/import-performance-best-practices.md
=> Reapply #8616

src/current/_includes/v22.2/start-in-docker/mac-linux-steps.md, src/current/_includes/v23.1/start-in-docker/mac-linux-steps.md, src/current/v22.2/start-a-local-cluster-in-docker-windows.md, src/current/v23.1/start-a-local-cluster-in-docker-windows.md
[DOC-7089] Upgrade go to 1.19.6 for 22.2 and 23.1
=> [DOC-7089] Upgrade go to 1.19.6 for 22.2 and 23.1

src/current/_includes/footer.html
=> DOC-8173: Remove Events link from page footer

src/current/cockroachcloud/upgrade-to-v22.1.md, src/current/cockroachcloud/upgrade-to-v22.2.md, src/current/cockroachcloud/upgrade-to-v23.1.md, src/current/v22.1/upgrade-cockroach-version.md, src/current/v22.2/upgrade-cockroach-version.md, src/current/v23.1/upgrade-cockroach-version.md
[DOC-795] Give advice about query performance in a mixed-version cluster
[src/current/cockroachcloud/upgrade-to-v22.1.md](https://deploy-preview-17318--cockroachdb-docs.netlify.app/docs/cockroachcloud/upgrade-to-v22.1.html)
[src/current/cockroachcloud/upgrade-to-v22.2.md](https://deploy-preview-17318--cockroachdb-docs.netlify.app/docs/cockroachcloud/upgrade-to-v22.2.html)
[src/current/cockroachcloud/upgrade-to-v23.1.md](https://deploy-preview-17318--cockroachdb-docs.netlify.app/docs/cockroachcloud/upgrade-to-v23.1.html)
[src/current/v22.1/upgrade-cockroach-version.md](https://deploy-preview-17318--cockroachdb-docs.netlify.app/docs/v22.1/upgrade-cockroach-version.html)
[src/current/v22.2/upgrade-cockroach-version.md](https://deploy-preview-17318--cockroachdb-docs.netlify.app/docs/v22.2/upgr …
=> [DOC-795] Give advice about query performance in a mixed-version cluster

src/current/_includes/contribute-options.html, src/current/_includes/feedback-widget-bottom.html, src/current/_includes/feedback-widget-toc.html
Also correct `target="blank"` to `target="_blank"` in a few spots
=> Add a link to Contribute to view page source

src/current/v22.1/security-reference/scram-authentication.md, src/current/v22.2/security-reference/scram-authentication.md, src/current/v23.1/security-reference/scram-authentication.md
https://cockroachlabs.atlassian.net/browse/DOC-7595
Docs site previews:
[src/current/v22.1/security-reference/scram-authentication.md](https://deploy-preview-17332--cockroachdb-docs.netlify.app/docs/v22.1/security-reference/scram-authentication.html)
[src/current/v22.2/security-reference/scram-authentication.md](https://deploy-preview-17332--cockroachdb-docs.netlify.app/docs/v22.2/security-reference/scram-authentication.html)
[src/current/v23.1/security-reference/scram-authentication.md](https://deploy-preview-17332--cockroachdb-docs.netlify.app/docs/v23.1/security-reference/scram-authentication.html)
=> Update SCRAM docs to show correct output

src/current/v22.2/ui-sql-dashboard.md
Addresses: DOC-6365
Updated 22.2 SQL Dashboard page, added P99.9 and P99.99 latency
=> DOC-6365: PR #92591 - ui: add 99.9th and 99.99th SQL latency charts

src/current/cockroachcloud/alerts-page.md
[DOC-8083] Updates to Alerts page for Azure
- Small general improvements
- Temporarily remove CMEK alert for encrypted backup until it works
- No Azure-specific changes
[src/current/cockroachcloud/alerts-page.md](https://deploy-preview-17328--cockroachdb-docs.netlify.app/docs/cockroachcloud/alerts-page.html)
=> [DOC-8083] Updates to Alerts page for Azure

src/current/_config_base.yml, src/current/_data/releases.yml, src/current/_includes/releases/v22.2/v22.2.11.md
=> Add release notes for v22.2.11

src/current/_includes/v23.1/sidebar-data/migrate.json, src/current/v23.1/molt-verify.md
[DOC-6940](https://cockroachlabs.atlassian.net/browse/DOC-6940) Docs for Migration Verification Tool
@taroface do we know where this doc should be in the sidebar nav? (I remember a discussion about creating a new section for migration tools)
=> DOC-6940: Document the MOLT Verify tool

src/current/_includes/v22.2/ui/statements-filter.md, src/current/_includes/v22.2/ui/transactions-filter.md, src/current/_includes/v23.1/ui/statements-filter.md, src/current/_includes/v23.1/ui/transactions-filter.md
Addresses: DOC-7975
Updated Statements and Transactions pages, (1) added Search Criteria section. (2) In Search and Filter section, added info callout.
=> DOC-7975: Document 'Code Yellow' console UX changes

src/current/cockroachcloud/cloud-sso-sql.md, src/current/v22.2/sso-sql.md, src/current/v23.1/sso-sql.md
[DOC-8222] Fix broken link, add What's Next section
[src/current/cockroachcloud/cloud-sso-sql.md](https://deploy-preview-17367--cockroachdb-docs.netlify.app/docs/cockroachcloud/cloud-sso-sql.html)
[src/current/v22.2/sso-sql.md](https://deploy-preview-17367--cockroachdb-docs.netlify.app/docs/v22.2/sso-sql.html)
[src/current/v23.1/sso-sql.md](https://deploy-preview-17367--cockroachdb-docs.netlify.app/docs/v23.1/sso-sql.html)
=> [DOC-8222] Fix broken link, add What's Next section

src/current/cockroachcloud/configure-scim-provisioning.md, src/current/cockroachcloud/managing-access.md
[DOC-7548][DOC-7549] SCIM provisioning doc improvements
- New groups UI
- More about Group Push
- Troubleshooting
[src/current/cockroachcloud/configure-scim-provisioning.md](https://deploy-preview-17278--cockroachdb-docs.netlify.app/docs/cockroachcloud/configure-scim-provisioning.html)
[src/current/cockroachcloud/managing-access.md](https://deploy-preview-17278--cockroachdb-docs.netlify.app/docs/cockroachcloud/managing-access.html)
=> [DOC-7548][DOC-7549] SCIM provisioning doc improvements

src/current/_data/redirects.yml
Continuation of https://github.com/cockroachdb/docs/pull/17028
=> Add redirect from Pony docs to Example Apps

src/current/v23.1/ui-hot-ranges-page.md
Addresses: DOC-6706
Updated Hot Ranges, added new statistic columns and modified QPS description.
=> DOC-6706: PR #95190 - ui: display more load stats on /hotranges page

src/current/cockroachcloud/quickstart.md
https://cockroachlabs.atlassian.net/browse/DOC-8192
Add node back to the Quickstart (using same language and code sample that was previously part of this page, not really new content)
=> Add node.js back to Quickstart

src/current/v22.2/ui-sql-dashboard.md, src/current/v23.1/ui-sql-dashboard.md
Addresses: DOC-7798
Updated SQL Dashboard page, added SQL Connection Rate section.
=> DOC-7798: PR #104072 - ui: add Created SQL Connections chart on SQL dashboard

src/current/v23.1/ui-overview.md
Addresses: DOC-7541
Updated DB Console Overview, added DB Console timezone configuration.
=> DOC-7541: PR #102195 - ui: display configurable timezone in DB Console

src/current/_includes/v23.1/sidebar-data/migrate.json, src/current/v23.1/migration-overview.md, src/current/v23.1/migration-strategy-lift-and-shift.md
Fixes [DOC-7561](https://cockroachlabs.atlassian.net/browse/DOC-7561)
- Add a new page 'Migration Strategy: Lift and Shift' that discusses the 'big bang' data migration approach, pros and cons, considerations, etc.
=> Add docs on 'Lift and Shift' migration strategy

src/current/_includes/sidebar.html, src/current/_includes/sidebar.js.html, src/current/_layouts/default.html
Caching the sidenav, because the only thing it uses to load itself is which version's JSON file to load.
Fixes DOC-8363
=> Improving performance of Jekyll build

src/current/cockroachcloud/network-authorization.md, src/current/v23.1/ui-overview.md
[DOC-5263](https://cockroachlabs.atlassian.net/browse/DOC-5263)
Static IPs for DB Console endpoints in Dedicated
=> DOC-5263 static IPs for DB Console endpoints in Dedicated

src/current/css/layouts/_sidebar.scss
=> DOC-7512: Make sidenav scroll independently of main content

src/current/advisories/index.md
=> Add signup link to Technical Advisory page

src/current/advisories/a99561.md
=> Update language around releases for TA

src/current/v23.1/change-data-capture-overview.md
=> CDC overview quick typo fix

src/current/_includes/v23.1/sidebar-data/reference.json
- Removed the old manage.json file as it's no longer used
- Removed the erroneous security links from the Reference > Cockroach Commands section
- Reordered the Reference > Security section to match the proposal
=> IA security / CLI edits

src/current/_includes/v22.1/prod-deployment/secure-test-load-balancing.md, src/current/_includes/v22.2/prod-deployment/secure-test-load-balancing.md, src/current/_includes/v23.1/prod-deployment/secure-test-load-balancing.md, src/current/v22.1/deploy-cockroachdb-on-premises.md, src/current/v22.2/deploy-cockroachdb-on-premises.md, src/current/v23.1/deploy-cockroachdb-on-premises.md
[DOC-8441] Fix formatting issues in deployment topic
=> [DOC-8441] Fix formatting issues in deployment topic

src/current/_includes/head.html
Don't index the page if both of the following criteria are true:
- The page canonical doesn't match the visited URL
- The version of the docs is expired
=> Noindex docs pages based on the following criteria:

src/current/_includes/sidebar-all-releases.json, src/current/_includes/sidebar-data-v23.1.json, src/current/_includes/sidebar-latest-releases.json, src/current/_includes/v23.1/sidebar-data/all-releases.json, src/current/_includes/v23.1/sidebar-data/latest-releases.json, src/current/_includes/v23.1/sidebar-data/releases.json
=> DOC-8089: Phase 5 of IA rollout

src/current/cockroachcloud/create-your-cluster.md
Also correct an include reference
Preview: [src/current/cockroachcloud/create-your-cluster.md](https://deploy-preview-17556--cockroachdb-docs.netlify.app/docs/cockroachcloud/create-your-cluster.html)
=> Correct Azure link

src/current/_config_base.yml, src/current/_data/releases.yml, src/current/_includes/releases/v23.1/v23.1.8.md
Added v23.1.8 release notes. Modified with review suggestions. Corrected release_date.
=> v23.1.8 release notes

src/current/_includes/v23.1/sidebar-data/cloud-deployments.json, src/current/cockroachcloud/aws-privatelink.md, src/current/cockroachcloud/client-certs-dedicated.md, src/current/cockroachcloud/cmek-ops-aws.md, src/current/cockroachcloud/cmek-ops-gcp.md, src/current/cockroachcloud/cmek.md, src/current/cockroachcloud/configure-cloud-org-sso.md, src/current/cockroachcloud/managing-access.md, src/current/cockroachcloud/managing-cmek.md, src/current/v22.2/sso-sql.md, src/current/v23.1/sso-sql.md
https://cockroachlabs.atlassian.net/browse/DOC-8403
=> DOC-8403 Security title and nav improvements

StyleGuide.md
Fixes DOC-8540
Preview: https://github.com/cockroachdb/docs/blob/doc-8540/StyleGuide.md#links
=> DOC-8540: Update Style Guide to reflect new linking strategies

src/current/v23.1/configure-cockroachdb-kubernetes.md
=> DOC-8166: Fix broken link in k8s docs

src/current/_config_base.yml, src/current/_data/releases.yml, src/current/_includes/releases/v22.1/v22.1.22.md
[DOC-8516] Release notes for v22.1.22
Preview: [releases/v22.1.md](https://deploy-preview-17654--cockroachdb-docs.netlify.app/docs/releases/v22.1.html)
=> [DOC-8516] Release notes for v22.1.22

src/current/_includes/cockroachcloud/download-the-binary.md, src/current/cockroachcloud/connect-to-your-cluster.md, src/current/cockroachcloud/quickstart-trial-cluster.md, src/current/v22.2/install-cockroachdb-windows.md, src/current/v23.1/install-cockroachdb-windows.md
[DOC-5508][DOC-7977] Improve PowerShell commands for Windows quickstart and install
[src/current/cockroachcloud/deploy-a-python-to-do-app-with-flask-kubernetes-and-cockroachcloud.md](https://deploy-preview-17355--cockroachdb-docs.netlify.app/docs/cockroachcloud/deploy-a-python-to-do-app-with-flask-kubernetes-and-cockroachcloud.html)
[src/current/cockroachcloud/quickstart-trial-cluster.md](https://deploy-preview-17355--cockroachdb-docs.netlify.app/docs/cockroachcloud/quickstart-trial-cluster.html)
[src/current/cockroachcloud/connect-to-your-cluster.md](https://deploy-preview-17355--cockroachdb-docs.netlify.app/docs/cockroachcloud/connect-to-your-cluster.html)
[src/current/v22.2/install-cockroachdb-windows.md](https://deploy-preview-17355--cockroachdb-docs.netlify.app/docs/v22.2/install-cock …
=> [DOC-5508][DOC-7977]  Improve PowerShell commands for Windows quickstart and install

src/current/v23.1/security-reference/security-overview.md
This was a direct product request:
https://cockroachlabs.slack.com/archives/C01PHNMUFLN/p1692291727879799?thread_ts=1692281978.236079&cid=C01PHNMUFLN
https://cockroachlabs.atlassian.net/browse/DOC-8593
=> self-hosted core in overview table

src/current/_includes/releases/v19.1/v2.2.0-alpha.20190114.md, src/current/v22.1/jsonb.md, src/current/v22.2/jsonb.md, src/current/v23.1/jsonb.md
=> DOC-6278: Fix instances of multiple h1s in a single page

src/current/_includes/landing-page.md
https://deploy-preview-17736--cockroachdb-docs.netlify.app/docs/v22.2/developer-guide-overview
https://deploy-preview-17736--cockroachdb-docs.netlify.app/docs/stable/developer-guide-overview
=> Remove extra h1 from landing pages

src/current/v22.1/recommended-production-settings.md, src/current/v22.2/recommended-production-settings.md, src/current/v23.1/recommended-production-settings.md
[DOC-8110] Remove opinionated language from Production Checklist
[src/current/v22.1/recommended-production-settings.md](https://deploy-preview-17744--cockroachdb-docs.netlify.app/docs/v22.1/recommended-production-settings.html)
[src/current/v22.2/recommended-production-settings.md](https://deploy-preview-17744--cockroachdb-docs.netlify.app/docs/v22.2/recommended-production-settings.html)
[src/current/v23.1/recommended-production-settings.md](https://deploy-preview-17744--cockroachdb-docs.netlify.app/docs/v23.1/recommended-production-settings.html)
=> [DOC-8110] Remove opinionated language from Production Checklist

src/current/advisories/internal/advisories.json, src/current/internal/version-data.json, src/current/releases/internal/cloud-release-info.json, src/current/releases/internal/cloud-releases.json, src/current/releases/internal/release-info.json, src/current/releases/internal/releases.json, src/current/releases/internal/versions.json, src/current/v1.0/internal/version-switcher-page-data.json, src/current/v1.1/internal/version-switcher-page-data.json, src/current/v19.1/internal/version-switcher-page-data.json, src/current/v19.2/internal/version-switcher-page-data.json, src/current/v2.0/internal/version-switcher-page-data.json, src/current/v2.1/internal/version-switcher-page-data.json, src/current/v20.1/internal/version-switcher-page-data.json, src/current/v20.2/internal/version-switcher-page-data.json, src/current/v21.1/internal/version-switcher-page-data.json, src/current/v21.2/internal/version-switcher-page-data.json, src/current/v22.1/internal/version-switcher-page-data.json, src/current/v22.2/internal/version-switcher-page-data.json, src/current/v23.1/internal/sidebar-data.json, src/current/v23.1/internal/version-switcher-page-data.json
Fixes DOC-8468
Preview links:
https://deploy-preview-17720--cockroachdb-docs.netlify.app/docs/advisories/internal/advisories.json
https://deploy-preview-17720--cockroachdb-docs.netlify.app/docs/internal/version-data.json
https://deploy-preview-17720--cockroachdb-docs.netlify.app/docs/releases/internal/cloud-release-info.json
https://deploy-preview-17720--cockroachdb-docs.netlify.app/docs/releases/internal/cloud-releases.json
https://deploy-preview-17720--cockroachdb-docs.netlify.app/docs/releases/internal/release-info.json
https://deploy-preview-17720--cockroachdb-docs.netlify.app/docs/releases/internal/releases.json
https://deploy-preview-17720--cockroachdb-docs.netlify.app/docs/releases/internal/versions.json
https://deploy-preview-17720--cockroachdb-docs.netlify.app/docs/v1.0/internal/v …
=> DOC-8468: Make Jekyll data available on the public internet

src/current/_includes/v22.1/sql/super-region-considerations.md, src/current/_includes/v22.2/sql/super-region-considerations.md, src/current/_includes/v23.1/sql/super-region-considerations.md, src/current/_includes/v23.2/sql/super-region-considerations.md
=> Super regions can use *one or more* DB regions

src/current/_includes/v22.2/sql/privileges.md, src/current/_includes/v23.1/sql/privileges.md, src/current/_includes/v23.2/sql/privileges.md
=> Add descriptions to privilege table

src/current/advisories/a110363.md
https://cockroachlabs.atlassian.net/browse/DOC-8778
=> Technical advisory 110363

src/current/_config_base.yml, src/current/_data/releases.yml, src/current/_includes/releases/release-downloads-docker-image.md, src/current/_includes/releases/v22.2/v22.2.14.md, src/current/releases/index.md
Addresses DOC-8667
Add release notes for v22.2.14
=> DOC-8667: Release notes for v22.2.14

src/current/_config_base.yml, src/current/_data/releases.yml, src/current/_includes/releases/v23.1/v23.1.10.md
=> v23.1.10 release notes

src/current/_includes/v22.2/orchestration/kubernetes-limitations.md, src/current/_includes/v23.1/orchestration/kubernetes-limitations.md, src/current/_includes/v23.2/orchestration/kubernetes-limitations.md
[DOC-1028] Remove mention of Helm from multi-cluster k8s deployment topic
=> [DOC-1028] Remove mention of Helm from multi-cluster k8s deployment topic

src/current/cockroachcloud/folders.md
Give a bit more info about the structure being open-ended, based on feedback like https://cockroachlabs.slack.com/archives/CHKQGKYEM/p1692611400123129
=> Add a bit more info about folders use cases

src/current/_config_cockroachdb.yml, src/current/_data/releases.yml, src/current/_includes/releases/current-cloud-version.md, src/current/_includes/releases/v23.1/v23.1.11.md
Deploy previews:
https://deploy-preview-17930--cockroachdb-docs.netlify.app/docs/releases
https://deploy-preview-17930--cockroachdb-docs.netlify.app/docs/releases/v23.1
https://deploy-preview-17930--cockroachdb-docs.netlify.app/docs/releases/cloud
=> Release v23.1.11 to the public

src/current/_includes/feature-phases/azure-limited-access.md, src/current/_includes/releases/cloud/2023-10-02.md, src/current/cockroachcloud/architecture.md, src/current/cockroachcloud/cloud-api.md, src/current/cockroachcloud/cluster-management.md, src/current/cockroachcloud/cmek.md, src/current/cockroachcloud/cockroachdb-dedicated-on-azure.md, src/current/cockroachcloud/connect-to-your-cluster.md, src/current/cockroachcloud/create-your-cluster.md, src/current/cockroachcloud/egress-perimeter-controls.md, src/current/cockroachcloud/frequently-asked-questions.md, src/current/cockroachcloud/managing-cmek.md, src/current/cockroachcloud/network-authorization.md, src/current/cockroachcloud/pci-dss.md, src/current/cockroachcloud/private-clusters.md, src/current/cockroachcloud/provision-a-cluster-with-terraform.md, src/current/cockroachcloud/regions.md
[DOC-7931] CockroachDB Dedicated on Azure is GA
[DOC-8902] Document how IOPS works on Azure
Also found a few things we missed in last week's release.
[releases/cloud.md](https://deploy-preview-17931--cockroachdb-docs.netlify.app/docs/releases/cloud.html)
[src/current/cockroachcloud/architecture.md](https://deploy-preview-17931--cockroachdb-docs.netlify.app/docs/cockroachcloud/architecture.html)
[src/current/cockroachcloud/cloud-api.md](https://deploy-preview-17931--cockroachdb-docs.netlify.app/docs/cockroachcloud/cloud-api.html)
[src/current/cockroachcloud/cluster-management.md](https://deploy-preview-17931--cockroachdb-docs.netlify.app/docs/cockroachcloud/cluster-management.html)
[src/current/cockroachcloud/cmek.md](https://deploy-preview-17931--cockroachdb-docs.netlify.app/docs/cockroach …
=> [DOC-7931][DOC-8902] CockroachDB Dedicated on Azure is GA

src/current/v21.2/local-testing.md, src/current/v22.1/local-testing.md, src/current/v22.2/local-testing.md, src/current/v23.1/local-testing.md, src/current/v23.2/local-testing.md
=> Do not recommend customizing an unsafe setting for local testing

src/current/_includes/version-switcher.html, src/current/_plugins/versions.rb, src/current/_plugins/versions/generator.rb, src/current/_plugins/versions/release_info.rb, src/current/_plugins/versions/version.rb, src/current/_plugins/versions/versioned_page.rb
This reverts commit e4c89568777f48973b938b7366f0f681605148d3 as the likely cause of an issue found with docs search.
=> Revert "Make version switcher work across folders (#17948)" DOC-9018

src/current/v22.2/timestamp.md, src/current/v23.1/timestamp.md, src/current/v23.2/timestamp.md
Fixes DOC-644
h/t Bram Gruneir for sharing these!
Tasks:
=> Add more TIMESTAMP conversion examples

src/current/cockroachcloud/ccloud-get-started.md
[DOC-9058]
Ref [Slack thread](https://cockroachlabs.slack.com/archives/C01J7MGJ3S7/p1680727768830509)
Preview: [src/current/cockroachcloud/ccloud-get-started.md](https://deploy-preview-17990--cockroachdb-docs.netlify.app/docs/cockroachcloud/ccloud-get-started.html)
=> [DOC-9058] Add --vanity-name flag to ccloud docs

src/current/_data/releases.yml, src/current/_includes/releases/v22.2/v22.2.15.md
Addresses DOC-7780
edited v22.2.15.md
=> DOC-7780: v22.2.15 release notes

src/current/_data/releases.yml, src/current/_includes/releases/v22.2/v22.2.16.md
=> v22.2.16 release notes

src/current/v22.2/secure-cockroachdb-kubernetes.md, src/current/v23.1/secure-cockroachdb-kubernetes.md, src/current/v23.2/secure-cockroachdb-kubernetes.md
Compare with https://www.cockroachlabs.com/docs/v23.1/secure-cockroachdb-kubernetes?filters=helm#deploy-cert-manager-for-mtls
=> Followup to fix display bugs introduced in #18023

src/current/v23.2/configure-logs.md
Addresses DOC-8095 DOC-8100
Updated Configure Logs page, added section datetime field for JSON format.
=> DOC-8095: PR #104265 - util/log: MVP of customizable 'datetime' field for JSON output

src/current/_includes/releases/v23.1/v23.1.12.md, src/current/releases/v23.1.md
v23.1.12 is now available on self-hosted
=> Updated release notes for self-hosted

src/current/v23.1/live-migration-service.md, src/current/v23.1/molt-verify.md, src/current/v23.2/live-migration-service.md, src/current/v23.2/molt-verify.md
Update the MOLT Verify and LMS download links per DOC-9228 and 9070.
=> update MOLT LMS and Verify download links

src/current/_data/releases.yml, src/current/_includes/releases/v22.2/v22.2.17.md
=> Add v22.2.17 release notes

src/current/_data/releases.yml, src/current/_includes/releases/v23.2/v23.2.0-beta.1.md
=> Release Notes v23.2.0-beta.1

src/current/v22.2/connection-pooling.md, src/current/v22.2/node-shutdown.md, src/current/v23.1/connection-pooling.md, src/current/v23.1/node-shutdown.md, src/current/v23.2/connection-pooling.md, src/current/v23.2/node-shutdown.md
=> Additional guidance on max connection lifetime

src/current/advisories/a114393.md
Addresses: DOC-9232
Added Technical Advisory 114393.
=> DOC-9232: Edit / Publish Technical Advisory 114393

src/current/_data/releases.yml, src/current/_includes/releases/v23.1/v23.1.13.md, src/current/releases/v23.1.md
=> Update v23.1.13 release notes for self-hosted

src/current/advisories/a114393.md
Fixes DOC-9331
Added links to v23.1.13.
=> DOC-9331 Update language around release for TA

src/current/_includes/v23.1/ui/sessions.md, src/current/_includes/v23.2/ui/sessions.md
Addresses DOC-9255
Updated Sessions page, added Closed session cache section.
=> DOC-9255: Provide explanation in the docs clarifying session details page

src/current/v22.1/cockroach-sql.md, src/current/v23.1/cockroach-sql.md, src/current/v23.2/cockroach-sql.md
[DOC-6504] Document how to verify the cluster ID for clusters in CockroachDB Cloud
=> [DOC-6504] Document how to verify the cluster ID for clusters in CockroachDB Cloud

src/current/v22.2/cockroach-workload.md, src/current/v23.1/cockroach-workload.md, src/current/v23.2/cockroach-workload.md
`cockroach workload` uses random seeds by default
- [DOC-6670] (22.2)
- [DOC-7097] (23.1+)
=> [DOC-6670][DOC-7097] cockroach workload uses random seeds by default

src/current/v22.2/install-cockroachdb-mac.md, src/current/v23.1/install-cockroachdb-mac.md, src/current/v23.2/install-cockroachdb-mac.md
[DOC-474] Document upgrading via Homebrew, along with caveats
=> [DOC-474] Document upgrading via Homebrew, along with caveats

src/current/_includes/v23.2/ui/ui-metrics-navigation.md
Fixes DOC-8962
Updated Dashboard navigation on Metrics pages, added graph title tooltip.
=> DOC-8962 ui: show metric on charts tooltip

src/current/v23.2/alter-virtual-cluster.md, src/current/v23.2/create-virtual-cluster.md, src/current/v23.2/cutover-replication.md, src/current/v23.2/drop-virtual-cluster.md, src/current/v23.2/physical-cluster-replication-monitoring.md, src/current/v23.2/set-up-physical-cluster-replication.md, src/current/v23.2/show-virtual-cluster.md
[DOC-9445] Update standby cluster's virtual cluster name in docs
=> [DOC-9445] Update standby cluster's virtual cluster name in docs

src/current/v22.2/admission-control.md, src/current/v23.1/admission-control.md, src/current/v23.2/admission-control.md
... using `SET LOCAL`
Fixes DOC-9454
Relates to https://github.com/cockroachdb/cockroach/issues/76624#issuecomment-1875810329
=> Add docs for per-transaction admission control

src/current/_data/releases.yml, src/current/_includes/releases/v23.2/v23.2.0-rc.2.md
=> v23.2.0-rc.2 release notes

src/current/v22.2/change-data-capture-overview.md, src/current/v22.2/changefeed-examples.md, src/current/v23.1/change-data-capture-overview.md, src/current/v23.1/changefeed-examples.md, src/current/v23.2/change-data-capture-overview.md, src/current/v23.2/changefeed-examples.md
=> Correct the serverless + enterprise license language for enterprise changefeeds

src/current/v23.2/monitoring-and-alerting.md
Fixes DOC-9386
Updated Monitoring and Alerting page, critical nodes endpoint examples to use multi-region sql abstractions and zone config extensions.
=> DOC-9386 Update critical nodes endpoint examples

src/current/_config_cockroachdb.yml, src/current/_data/releases.yml
Addresses [DOC-9536](https://cockroachlabs.atlassian.net/browse/DOC-9536)
=> Update v23.1.14 availability

src/current/_includes/releases/v23.2/v23.2.0.md, src/current/v23.2/alter-procedure.md, src/current/v23.2/call.md, src/current/v23.2/cockroachdb-feature-availability.md, src/current/v23.2/create-procedure.md, src/current/v23.2/drop-procedure.md
- Amended & added Read Committed listings on v23.2 feature pages.
- Add "new in v23.2" callout to stored proc SQL commands.
=> add preview & version notes for Read Committed and stored procs

src/current/v22.2/aws-dms.md, src/current/v23.1/aws-dms.md, src/current/v23.2/aws-dms.md
DOC-9384
DOC-9222
DOC-9062
DOC-9245
=> add some DMS best practices

src/current/cockroachcloud/folders.md
This is the PR to document the limitations that are deployed in Production today
=> [DOC-9552] Document limitations on folder names

src/current/cockroachcloud/cloud-org-sso.md, src/current/cockroachcloud/configure-cloud-org-sso.md
[DOC-9504] Document that before using the IdP-initiated SAML flow, you must contact support to be enabled
This may be part 1 of N, depending on an ongoing investigation.
[src/current/cockroachcloud/cloud-org-sso.md](https://deploy-preview-18244--cockroachdb-docs.netlify.app/docs/cockroachcloud/cloud-org-sso.html)
[src/current/cockroachcloud/configure-cloud-org-sso.md](https://deploy-preview-18244--cockroachdb-docs.netlify.app/docs/cockroachcloud/configure-cloud-org-sso.html)
=> [DOC-9504] Document that before using the IdP-initiated SAML flow, you must contact support to be enabled

src/current/cockroachcloud/client-certs-dedicated.md
[DOC-9553] Correct the note about updating the CA certificate, document how to roll out a CA certificate update gradually
=> [DOC-9553] Correct the note about updating the CA certificate, document how to roll out a CA certificate update gradually

src/current/_data/releases.yml, src/current/_includes/sidebar-all-releases.json, src/current/releases/index.md, src/current/releases/staged-release-process.md
Addresses [DOC-9563](https://cockroachlabs.atlassian.net/browse/DOC-9563)
=> Document Staged Release Process

src/current/cockroachcloud/client-certs-dedicated.md
Per [internal thread](https://cockroachlabs.slack.com/archives/CHKQGKYEM/p1706544300020549?thread_ts=1705678793.241899&cid=CHKQGKYEM)
=> Remove details about multiple CA certs on Cloud

src/current/v23.2/cockroachdb-feature-availability.md
https://cockroachlabs.atlassian.net/browse/DOC-9367
=> Clarifications to feature phases info [DOC-9367]

src/current/_data/releases.yml, src/current/_includes/releases/v22.2/v22.2.18.md
=> v22.2.18 release notes

src/current/_data/releases.yml, src/current/_includes/releases/v23.2/v23.2.1.md
=> Add v23.2.1 cloud-first release notes

src/current/_data/products.yml, src/current/cockroachcloud/create-an-account.md, src/current/cockroachcloud/create-your-cluster.md, src/current/cockroachcloud/learn-cockroachdb-sql.md, src/current/netlify/build.sh
Updated the product name variables
=> Updated the product name variables

src/current/advisories/a99561.md
=> Correct statement in TA 99561 query

src/current/v22.2/zone-config-extensions.md, src/current/v23.1/zone-config-extensions.md, src/current/v23.2/zone-config-extensions.md
=> Add direct link to Zone Config Extensions examples

src/current/v23.2/changefeed-examples.md
=> Correct duplicate sentence on Changefeed Examples page

src/current/releases/index.md
The pre-production preview variable must be updated in CC upgrade topics and in release/index.md.
=> Fix pre-production preview variable

src/current/cockroachcloud/regions.md
[DOC-9834] Add northerneurope region for Azure
Preview: [src/current/cockroachcloud/regions.md](https://deploy-preview-18364--cockroachdb-docs.netlify.app/docs/cockroachcloud/regions.html)
=> [DOC-9834] Add northerneurope region for Azure

src/current/v23.1/community-tooling.md, src/current/v23.2/community-tooling.md, src/current/v24.1/community-tooling.md
=> Touch 3rd-party community tools page for Cloud 2.0

src/current/v23.1/admission-control.md, src/current/v23.2/admission-control.md, src/current/v24.1/admission-control.md
=> Update 'Admission Control' page for Cloud 2.0

src/current/v23.1/cloud-storage-authentication.md, src/current/v23.2/cloud-storage-authentication.md, src/current/v24.1/cloud-storage-authentication.md
Fixes DOC-9849
Updates the Cloud Storage Authentication page for Cloud 2.0.
=> Update the Cloud Storage Auth page for Cloud 2.0

src/current/v23.1/multiregion-scale-application.md, src/current/v23.2/multiregion-scale-application.md, src/current/v24.1/multiregion-scale-application.md
=> Update 'Scale to multiple regions' for Cloud 2.0

src/current/v23.1/schema-design-update.md, src/current/v23.2/schema-design-update.md, src/current/v24.1/schema-design-update.md
=> Update 'Add/remove schema objects' for Cloud 2.0

src/current/v23.1/schema-design-table.md, src/current/v23.2/schema-design-table.md, src/current/v24.1/schema-design-table.md
=> Update 'Create a Table' docs for Cloud 2.0

src/current/_data/releases.yml, src/current/_includes/releases/v24.1/v24.1.0-alpha.4.md
=> v24.1.0-alpha.4 release notes

src/current/v23.1/bulk-delete-data.md, src/current/v23.1/bulk-update-data.md, src/current/v23.1/delete-data.md, src/current/v23.1/insert-data.md, src/current/v23.1/query-behavior-troubleshooting.md, src/current/v23.1/query-data.md, src/current/v23.1/schema-design-indexes.md, src/current/v23.1/update-data.md, src/current/v23.2/bulk-delete-data.md, src/current/v23.2/bulk-update-data.md, src/current/v23.2/delete-data.md, src/current/v23.2/insert-data.md, src/current/v23.2/query-behavior-troubleshooting.md, src/current/v23.2/query-data.md, src/current/v23.2/schema-design-indexes.md, src/current/v23.2/update-data.md, src/current/v24.1/bulk-delete-data.md, src/current/v24.1/bulk-update-data.md, src/current/v24.1/delete-data.md, src/current/v24.1/insert-data.md, src/current/v24.1/query-behavior-troubleshooting.md, src/current/v24.1/query-data.md, src/current/v24.1/schema-design-indexes.md, src/current/v24.1/update-data.md
DOC-9732
DOC-9856
DOC-9858
DOC-9859
DOC-9860
DOC-9861
DOC-9862
DOC-9863
DOC-9864
=> update SQL queries docs for Cloud 2.0

src/current/cockroachcloud/plan-your-cluster.md
Addresses [DOC-9756](https://cockroachlabs.atlassian.net/browse/DOC-9756)
=> Plan a cluster docs updates

src/current/.bundle/config, src/current/_includes/cockroachcloud/quickstart/create-a-free-cluster.md, src/current/_includes/cockroachcloud/quickstart/create-free-trial-standard-cluster.md, src/current/cockroachcloud/connect-to-your-cluster.md, src/current/cockroachcloud/quickstart-trial-cluster.md, src/current/cockroachcloud/quickstart.md
Addresses [DOC-9713](https://cockroachlabs.atlassian.net/browse/DOC-9713)
=> Updated quickstart guides for Cloud 2.0

.github/workflows/pr-reviews.yml
Revert https://github.com/cockroachdb/docs/pull/18437/ per [thread](https://cockroachlabs.slack.com/archives/CJ0H8Q97C/p1712089799343009).
=> Re-add pr-reviews check workflow

src/current/_data/releases.yml, src/current/_includes/releases/v24.1/v24.1.0-beta.1.md
Fixes [DOC-10030](https://cockroachlabs.atlassian.net/browse/DOC-10030)
=> v24.1.0-beta.1 release notes

src/current/cockroachcloud/create-your-cluster.md
=> Fix broken external link to Cloud Console

src/current/_data/releases.yml, src/current/_includes/releases/v24.1/v24.1.0-rc.1.md, src/current/cockroachcloud/upgrade-to-v24.1.md
=> v24.1.0-rc.1 release notes

src/current/_data/releases.yml, src/current/_includes/releases/v24.1/v24.1.0-rc.2.md
=> v24.1.0-rc.2 release notes

src/current/v24.1/cutover-replication.md
Hey, @kathancox!
I looks like a merge was not quite finished. Please let me know if I've accepted the right version (I went for the incoming change) 🙂
=> Accept incoming merge change

src/current/_includes/releases/v24.1/v24.1.0.md
Per [internal thread](https://cockroachlabs.slack.com/archives/C01C3B15GQ1/p1716383705362429)
=> Fix WAL Cloud availability

src/current/_data/releases.yml
Updated the v23.1.22 release notes for self-hosted
=> v23.1.22 self-hosted release notes

src/current/_data/releases.yml
=> Make 24.1.0 binaries available

src/current/cockroachcloud/sql-shell.md
Addresses [DOC-10321](https://cockroachlabs.atlassian.net/browse/DOC-10321)
Updated the SQL Shell doc to ask users to contact us to get access to the shell for Dedicated advanced clusters.
=> Updated SQL shell limitation

src/current/v22.2/changefeed-sinks.md, src/current/v23.1/changefeed-sinks.md, src/current/v23.2/changefeed-sinks.md, src/current/v24.1/changefeed-sinks.md
=> Correct JSON config for kafka_sink_config option

src/current/_includes/releases/whats-new-intro.md, src/current/releases/index.md, src/current/releases/v1.0.md, src/current/releases/v1.1.md, src/current/releases/v19.1.md, src/current/releases/v19.2.md, src/current/releases/v2.0.md, src/current/releases/v2.1.md, src/current/releases/v20.1.md, src/current/releases/v20.2.md, src/current/releases/v21.1.md, src/current/releases/v21.2.md, src/current/releases/v22.1.md, src/current/releases/v22.2.md, src/current/releases/v23.1.md, src/current/releases/v23.2.md, src/current/releases/v24.1.md
=> Add What's New page intro and Releases page Licenses section

src/current/_data/releases.yml
=> Publish v23.2.6 binaries

src/current/cockroachcloud/connect-to-your-cluster.md
=> Fix unbalanced bold

src/current/cockroachcloud/managing-access.md
=> [REL-1144] Test

src/current/_includes/releases/v23.2/v23.2.7.md
=> Correct v23.2.7 docs for cdc bulk oracle setting name

src/current/_data/releases.yml
=> Update v24.1.2 for self-hosted release

src/current/cockroachcloud/migrations-page.md
[DOC-9109](https://cockroachlabs.atlassian.net/browse/DOC-9109)
=> clarify SCT requirements

src/current/_includes/v24.2/known-limitations/plpgsql-limitations.md, src/current/_includes/v24.2/known-limitations/routine-limitations.md, src/current/_includes/v24.2/known-limitations/stored-proc-limitations.md, src/current/_includes/v24.2/known-limitations/udf-limitations.md, src/current/v24.2/known-limitations.md
https://cockroachlabs.atlassian.net/browse/DOC-10704
=> move SQL Queries KLs from New -> Existing

src/current/_includes/v23.2/physical-replication/show-virtual-cluster-data-state.md, src/current/_includes/v24.1/physical-replication/show-virtual-cluster-data-state.md, src/current/_includes/v24.2/physical-replication/show-virtual-cluster-data-state.md, src/current/v23.2/alter-virtual-cluster.md, src/current/v24.1/alter-virtual-cluster.md, src/current/v24.2/alter-virtual-cluster.md
=> Correct statement error for alter virtual cluster pages

src/current/_includes/releases/cloud/2024-06-12.md, src/current/_includes/releases/cloud/2024-06-14.md, src/current/_includes/releases/cloud/2024-06-17.md, src/current/_includes/releases/cloud/2024-06-26.md, src/current/_includes/releases/cloud/2024-07-18.md, src/current/_includes/releases/cloud/2024-07-19.md
=> Fix level of Cloud release note date headings

src/current/_data/releases.yml
=> release v23.1.24 binaries

src/current/_includes/head.html
=> Add kapa script tag to docs head

src/current/_data/releases.yml
=> v24.1.3 publish binaries

src/current/_includes/v23.2/known-limitations/physical-cluster-replication.md
=> Update the PCR KLs for performance numbers

src/current/releases/molt.md
=> add MOLT 1.1.4 release notes

src/current/releases/molt.md
Fix disappearing MOLT changelog. There was an extra section tag preventing it from appearing.
=> remove extraneous section tag

src/current/molt/molt-fetch.md, src/current/releases/molt.md, src/current/v23.2/migration-overview.md, src/current/v24.1/migration-overview.md, src/current/v24.2/migration-overview.md
Revert MOLT Fetch modes update until the 1.1.5 MOLT release is cut.
=> revert MOLT Fetch modes update

src/current/_includes/v24.2/cdc/sink-list.md, src/current/v24.2/changefeed-sinks.md, src/current/v24.2/create-and-configure-changefeeds.md, src/current/v24.2/create-changefeed.md
Fixes DOC-10946
Adds an include file for a list of changefeeds sinks.
=> Add a sink list include for changefeeds

src/current/_data/releases.yml
=> Publish binaries v23.1.25

src/current/releases/molt.md
https://cockroachlabs.atlassian.net/browse/DOC-10974
=> MOLT 1.1.7 release note

src/current/v23.1/architecture/glossary.md, src/current/v23.1/security-reference/authorization.md, src/current/v23.2/architecture/glossary.md, src/current/v23.2/security-reference/authorization.md, src/current/v24.1/architecture/glossary.md, src/current/v24.1/security-reference/authorization.md, src/current/v24.2/architecture/glossary.md, src/current/v24.2/security-reference/authorization.md
=> Port #18850 to cloud 2.0

src/current/releases/index.md
Intent is to automate this ASAP; for now we must manually update.
=> Update manual listing of latest patches

src/current/_data/releases.yml
=> expose binary links for v23.2.10

src/current/cockroachcloud/regions.md
[DOC-9721] Region updates for new tiers
Preview: [src/current/cockroachcloud/regions.md](https://deploy-preview-18892--cockroachdb-docs.netlify.app/docs/cockroachcloud/regions.html)
=> [DOC-9721] Region updates for new tiers

src/current/cockroachcloud/cluster-management.md
[DOC-10492] Document manual upgrades for Standard
=> [DOC-10492] Document manual upgrades for Standard

src/current/_data/releases.yml, src/current/_includes/releases/v23.2/v23.2.11.md
=> Release notes v23.2.11

src/current/v23.2/read-committed.md, src/current/v24.1/read-committed.md, src/current/v24.2/read-committed.md
=> fix read committed connection parameter

src/current/_data/releases.yml, src/current/_includes/releases/v24.2/v24.2.2.md
=> v24.2.2 release note (hot fix)

src/current/cockroachcloud/cloud-api.md
[DOC-11174] Update info about default CC-Version
=> [DOC-11174] Update info about default CC-Version

src/current/_includes/cockroachcloud/cdc/create-core-changefeed.md, src/current/_includes/v23.1/cdc/metrics-labels.md, src/current/_includes/v23.2/cdc/metrics-labels.md, src/current/_includes/v24.1/cdc/cdc-cloud-rangefeed.md, src/current/_includes/v24.1/cdc/metrics-labels.md, src/current/_includes/v24.2/cdc/cdc-cloud-rangefeed.md, src/current/_includes/v24.2/cdc/metrics-labels.md, src/current/v24.1/change-data-capture-overview.md, src/current/v24.1/changefeed-examples.md, src/current/v24.1/connect-to-a-changefeed-kafka-sink-with-oauth-using-okta.md, src/current/v24.1/create-changefeed.md, src/current/v24.1/create-schedule-for-changefeed.md, src/current/v24.1/stream-a-changefeed-to-a-confluent-cloud-kafka-cluster.md, src/current/v24.2/change-data-capture-overview.md, src/current/v24.2/changefeed-examples.md, src/current/v24.2/connect-to-a-changefeed-kafka-sink-with-oauth-using-okta.md, src/current/v24.2/create-changefeed.md, src/current/v24.2/create-schedule-for-changefeed.md, src/current/v24.2/stream-a-changefeed-to-a-confluent-cloud-kafka-cluster.md
=> Correct serverless cdc

src/current/_data/releases.yml, src/current/_includes/releases/v24.1/v24.1.5.md
=> v24.1.5 release notes

src/current/_data/releases.yml, src/current/_includes/releases/v23.2/v23.2.12.md
=> Add cloud-first release notes for v23.2.12

src/current/cockroachcloud/upgrade-policy.md, src/current/releases/cloud.md
[DOC-11064] Update Cloud Upgrade Policy
=> [DOC-11064] Update Cloud Upgrade Policy

src/current/_data/releases.yml
=> Release v24.1.5 add binaries

src/current/cockroachcloud/costs.md, src/current/releases/cloud.md
Per discussion with @awoods187
=> Fix RN wording

src/current/cockroachcloud/authorization.md
[DOC-10403] Add details about network authorization to Cluster Operator role description
=> [DOC-10403] Add details about network authorization to Cluster Operator role description

src/current/_includes/releases/v23.2/v23.2.7.md
=> Correct cdc planning release note in v23.2.7

src/current/_data/releases.yml, src/current/_includes/releases/v23.1/v23.1.27.md
Fixes REL-1570
edited release notes
=> REL-1570 v23.1.27 (hot fix): [Docs] Generate release notes for download/SH

src/current/v23.1/security-reference/authentication.md, src/current/v23.2/security-reference/authentication.md, src/current/v24.1/security-reference/authentication.md, src/current/v24.2/security-reference/authentication.md, src/current/v24.3/security-reference/authentication.md
[DOC-11324] Fix errors about authentication policies
=> [DOC-11324] Fix errors about authentication policies

src/current/v24.1/physical-cluster-replication-overview.md, src/current/v24.2/physical-cluster-replication-overview.md, src/current/v24.3/physical-cluster-replication-overview.md
Fixes DOC-11079
This updates the PCR performance section and removes some of the previous content.
=> Update the pcr performance section

src/current/advisories/a131639.md
Per team [discussion](https://cockroachlabs.slack.com/archives/CSPK16V51/p1728406971557139?thread_ts=1727718256.922899&cid=CSPK16V51)
=> Minor TA wording improvement

src/current/advisories/a131639.md
Per [thread](https://cockroachlabs.slack.com/archives/C01PHNMUFLN/p1728668856083069).
=> Update SQL in Technical Advisory 131639

src/current/cockroachcloud/costs.md
=> Update costs.md to add anchor used in UI

src/current/advisories/a131639.md
- Update the SQL query
- Light copyedit about `AS OF SYSTEM TIME` b/c there is only one clause
- Removal of a few "please"s
=> Followups to a131639

src/current/_includes/releases/v24.3/v24.3.0-alpha.2.md
Preview: https://deploy-preview-19014--cockroachdb-docs.netlify.app/docs/releases/v24.3#v24-3-0-alpha-2-operational-changes
=> Add link text to underspecified link

src/current/_data/releases.yml, src/current/_includes/releases/v23.2/v23.2.13.md
[REL-1405] Release notes for v23.2.13
=> [REL-1405] Release notes for v23.2.13

src/current/_data/releases.yml
=> publish v24.1.6 binaries

src/current/_data/releases.yml
=> [REL-1408] Enable downloads for v23.2.13

src/current/_data/redirects.yml, src/current/cockroachcloud/managing-cmek.md
[DOC-11531] Fix rendering issues in CMEK content
Also add redirects for `cmek-ops*` pages that no longer exist
Preview: [src/current/cockroachcloud/managing-cmek.md](https://deploy-preview-19042--cockroachdb-docs.netlify.app/docs/cockroachcloud/managing-cmek.html)
=> [DOC-11531] Fix rendering issues in CMEK content

src/current/_includes/nav-customers.html
Per [thread](https://cockroachlabs.slack.com/archives/C03TH7EEMAA/p1730148127888199)
=> Update nav-customers.html to fix Roachfest link

src/current/v24.3/known-limitations.md
Quick fix to update the version number on the v24.3 KL page.
=> Update version number on Known Limitations page

src/current/v24.2/demo-cockroachdb-resilience.md
=> Correct Demo title in v24.2

src/current/releases/molt.md
=> MOLT 1.2.0 release notes

src/current/_includes/v23.1/prod-deployment/recommended-instances-azure.md, src/current/_includes/v23.2/prod-deployment/recommended-instances-azure.md, src/current/_includes/v24.1/prod-deployment/recommended-instances-azure.md, src/current/_includes/v24.2/prod-deployment/recommended-instances-azure.md, src/current/_includes/v24.3/prod-deployment/recommended-instances-azure.md
[DOC-10179] Remove outdated details from Azure VM warning
=> [DOC-10179] Remove outdated details from Azure VM warning

src/current/v23.1/deploy-cockroachdb-with-kubernetes-openshift.md, src/current/v23.2/deploy-cockroachdb-with-kubernetes-openshift.md, src/current/v24.1/deploy-cockroachdb-with-kubernetes-openshift.md, src/current/v24.2/deploy-cockroachdb-with-kubernetes-openshift.md, src/current/v24.3/deploy-cockroachdb-with-kubernetes-openshift.md
[DOC-7600] Update Openshift doc link
=> [DOC-7600] Update Openshift doc link

src/current/v23.1/configure-logs.md, src/current/v23.2/configure-logs.md, src/current/v24.1/configure-logs.md, src/current/v24.2/configure-logs.md, src/current/v24.3/configure-logs.md
[DOC-10073] Fix incorrect info about cockroach debug check-log-config
=> [DOC-10073] Fix incorrect info about cockroach debug check-log-config

src/current/v23.1/performance-benchmarking-with-tpcc-medium.md, src/current/v23.2/performance-benchmarking-with-tpcc-medium.md, src/current/v24.1/performance-benchmarking-with-tpcc-medium.md, src/current/v24.2/performance-benchmarking-with-tpcc-medium.md, src/current/v24.3/performance-benchmarking-with-tpcc-medium.md
[DOC-8890] Remove mention of cluster setting rocksdb.ingest_backpressure.pending_compaction_threshold
=> [DOC-8890] Remove mention of cluster setting rocksdb.ingest_backpressure.pending_compaction_threshold

src/current/cockroachcloud/costs.md, src/current/releases/cloud.md, src/current/v23.2/cockroachdb-feature-availability.md, src/current/v24.1/cockroachdb-feature-availability.md, src/current/v24.2/cockroachdb-feature-availability.md
=> Update Cloud Costs page and add Cloud release note

src/current/Gemfile, src/current/css/bs/_variables.scss, src/current/css/bs/mixins/_forms.scss, src/current/css/bs/mixins/_grid.scss, src/current/css/bs/utilities/_embed.scss, src/current/css/bs/vendor/_rfs.scss, src/interactive-tutorials/Gemfile
This reverts commit af65df26c29d3fe5529f101ef2457a42d49df6f0, reversing changes made to 527cf10131640dbd09412f7f440d393f81f45ada.
=> Revert "Merge pull request #19090 from cockroachdb/sass_warning_fix"

src/current/_includes/common/upgrade-cockroach-version-license-limitations.md, src/current/v24.3/upgrade-cockroach-version.md
=> Update upgrade docs with license key info

src/current/_includes/v23.1/sidebar-data/reference.json, src/current/_includes/v23.2/sidebar-data/reference.json, src/current/_includes/v24.1/sidebar-data/reference.json, src/current/_includes/v24.2/sidebar-data/reference.json, src/current/v23.1/telemetry.md, src/current/v23.2/telemetry.md, src/current/v24.1/telemetry.md, src/current/v24.2/telemetry.md
=> Backport telemetry docs from #19131

src/current/v23.1/upgrade-cockroach-version.md, src/current/v23.2/upgrade-cockroach-version.md, src/current/v24.1/upgrade-cockroach-version.md, src/current/v24.2/upgrade-cockroach-version.md
=> Backport upgrade license info from #19125

src/current/v24.3/data-resilience.md
=> Link LDR on the Data Resilience page

src/current/v24.3/create-and-configure-changefeeds.md
Missed adding the link in merged PR https://github.com/cockroachdb/docs/pull/19155
This PR fixes that.
=> Quick fix link on changefeed page

src/current/_includes/v23.2/ui/databases.md, src/current/_includes/v24.1/ui/databases.md, src/current/_includes/v24.2/ui/databases.md
Fixes DOC-11561 DOC-11562 DOC-11563
In databases.md include files, removed mention of Range Count.
- [Databases](https://deploy-preview-19185--cockroachdb-docs.netlify.app/docs/v23.2/ui-databases-page#databases)
=> DOC-11561 PR #133271 - ui: remove "Range Count" column from db page

src/current/v23.1/alter-index.md, src/current/v23.1/indexes.md, src/current/v23.2/alter-index.md, src/current/v23.2/indexes.md, src/current/v24.1/alter-index.md, src/current/v24.1/indexes.md, src/current/v24.2/alter-index.md, src/current/v24.2/indexes.md, src/current/v24.3/alter-index.md, src/current/v24.3/indexes.md
Branched from #19117.
@mgartner I adapted your language and made some further tweaks. PTAL.
=> Clarify NOT VISIBLE indexes

src/current/v24.1/set-up-physical-cluster-replication.md, src/current/v24.2/set-up-physical-cluster-replication.md, src/current/v24.3/set-up-physical-cluster-replication.md
=> Remove } from entire pcr uri

src/current/_data/releases.yml, src/current/_includes/releases/v23.1/v23.1.30.md
=> v23.1.30 release notes (Cloud-first)

src/current/_data/releases.yml, src/current/_includes/releases/v23.2/v23.2.17.md
=> Add cloud-first release notes for v23.2.17

src/current/_data/releases.yml
Need to correct some release dates per this thread: https://cockroachlabs.slack.com/archives/C07GE2Q1QN8/p1734030522724559
=> update release dates to Nov 18

src/current/_data/releases.yml
=> publish v23.1.30 binary links

src/current/_data/releases.yml
=> Release binaries for v23.2.17, v24.1.8, 24.2.6

src/current/v24.3/sql-feature-support.md
- Removed the (outdated) version from the page title
- Shortened the intro and added a liquid variable for the current version
- Updated entry for Triggers support 😬
=> update SQL Feature Support page

src/current/v21.2/common-issues-to-monitor.md, src/current/v22.1/common-issues-to-monitor.md, src/current/v22.2/common-issues-to-monitor.md, src/current/v23.1/common-issues-to-monitor.md, src/current/v23.2/common-issues-to-monitor.md, src/current/v24.1/common-issues-to-monitor.md, src/current/v24.2/common-issues-to-monitor.md, src/current/v24.3/common-issues-to-monitor.md, src/current/v25.1/common-issues-to-monitor.md
[DOC-12057](https://cockroachlabs.atlassian.net/browse/DOC-12057)
=> remove confusing disk IOPs guidance

src/current/_includes/releases/v24.2/feature-highlights-observability.html, src/current/_includes/releases/v24.2/feature-highlights-sql.html
=> Fix links to 'CockroachDB Feature Availability'

src/current/_includes/common/licensing-faqs.md
=> Update Licensing FAQ with info re: gov't entities

src/current/_data/releases.yml, src/current/_includes/releases/v24.1/v24.1.10.md
=> Add cloud-first release notes for v24.1.10

src/current/_data/releases.yml
Fixes REL-1858, REL-1849, REL-1840, REL-1831
=> Add binaries for Jan 13 25 releases

src/current/_includes/v24.2/cdc/msk-dedicated-support.md, src/current/_includes/v24.3/cdc/msk-dedicated-support.md, src/current/_includes/v25.1/cdc/msk-dedicated-support.md
Fixes DOC-12103
Updates the note around contacting the CRL account team for connections to MSK for clarity.
=> Update note around CRDB to MSK Serverless

src/current/_data/releases.yml, src/current/_includes/releases/v24.3/v24.3.4.md
=> v24.3.4 release notes

src/current/_includes/feature-phases/preview.md, src/current/cockroachcloud/folders.md
=> Updated the preview include to streamline sentences

src/current/_data/releases.yml, src/current/_includes/releases/v24.2/v24.2.10.md
=> Add release notes for v24.2.10

src/current/_data/releases.yml
=> Enable binary downloads for v24.2.10

src/current/_includes/common/licensing-faqs.md
=> Update Licensing FAQs re: Enterprise Free deploys

src/current/_data/releases.yml, src/current/_includes/releases/v24.1/v24.1.11.md, src/current/_includes/releases/v24.1/v24.1.12.md, src/current/_includes/releases/v24.1/v24.1.13.md
=> v24.1.13 Release Notes

src/current/_includes/common/licensing-faqs.md
=> Update Licensing FAQs re: Enterprise Free usage

src/current/_data/releases.yml
=> Publish binaries for v25.1.0

src/current/v23.1/take-and-restore-encrypted-backups.md, src/current/v23.2/take-and-restore-encrypted-backups.md, src/current/v24.1/take-and-restore-encrypted-backups.md, src/current/v24.2/take-and-restore-encrypted-backups.md, src/current/v24.3/take-and-restore-encrypted-backups.md, src/current/v25.1/take-and-restore-encrypted-backups.md
=> Add AWS_ENDPOINT param to KMS backup page

src/current/_data/releases.yml, src/current/_includes/releases/v23.2/v23.2.21.md
=> v23.2.21 Release Notes

src/current/_data/releases.yml, src/current/_includes/releases/v24.1/v24.1.14.md
=> Publish cloud-first release notes for v24.1.14

src/current/_data/releases.yml
=> Add binaries to v23.2.21 release notes

src/current/v24.3/schema-design-overview.md, src/current/v25.1/schema-design-overview.md
=> Remove duplicate sentence on schemas page

.github/workflows/vale.yml
=> vale: pin commit for a GH Action that had its tags compromised

src/current/_includes/common/upgrade/overview.md
=> Append detail on automatic upgrade for basic and standard clusters

src/current/molt/molt-fetch.md
=> fix defaultGTIDSet example

src/current/v23.1/cdc-queries.md, src/current/v23.2/cdc-queries.md, src/current/v24.1/cdc-queries.md, src/current/v24.2/cdc-queries.md, src/current/v24.3/cdc-queries.md, src/current/v25.1/cdc-queries.md
=> Remove EXPLAIN tip from cdc queries page

src/current/_data/releases.yml
=> Publish binaries v23.2.22

src/current/_data/releases.yml
[REL-2153](https://cockroachlabs.atlassian.net/browse/REL-2153)
=> publish v24.3.9 binaries

src/current/releases/molt.md
=> add MOLT 1.2.5 release note

src/current/cockroachcloud/configure-cloud-org-sso.md, src/current/cockroachcloud/configure-scim-provisioning.md
- Updated configure-cloud-org-sso
- Added Supported sign-in flows
- Added Steps for SP-Initiated Single Sign-On (SSO)
- Added Supported SAML Attribute
=> Fixes DOC-13145 : Updated configure-cloud-org-sso

src/current/_includes/releases/v24.3/v24.3.12.md
=> Final tweaks based on reviewer feedback in #19573

src/current/_data/releases.yml
Fixes:
- REL-2375
- REL-2385
- REL-2394
=> Publish SH for v23.2.25, v24.1.18, v24.3.12

src/current/_includes/releases/v23.1/v23.1.0.md, src/current/v22.2/take-full-and-incremental-backups.md, src/current/v23.1/take-full-and-incremental-backups.md, src/current/v23.2/take-full-and-incremental-backups.md, src/current/v24.1/take-full-and-incremental-backups.md, src/current/v24.2/take-full-and-incremental-backups.md, src/current/v24.3/take-full-and-incremental-backups.md, src/current/v25.1/take-full-and-incremental-backups.md, src/current/v25.2/take-full-and-incremental-backups.md
=> Remove unsupported guidance from docs on incremental backups

src/current/_data/releases.yml
Per [thread](https://cockroachlabs.slack.com/archives/C01PHNMUFLN/p1747091551149549)
=> Readd v25.2.0-rc.1 release entry

src/current/_data/releases.yml, src/current/_includes/releases/v25.1/v25.1.6.md
Fixes [REL-2402](https://cockroachlabs.atlassian.net/browse/REL-2402)
=> Publish SH for v25.1.6

src/current/_data/releases.yml
[Source](https://cockroachlabs.atlassian.net/browse/REL-2502?focusedCommentId=286436)
=> Fix SHA in releases.yml

src/current/v25.2/architecture/transaction-layer.md, src/current/v25.2/cockroachdb-feature-availability.md
=> Add docs on Buffered Writes (Preview)

src/current/_includes/releases/v25.2/v25.2.0.md
Fixes DOC-13752
In v25.2.0.md, updated patch versions for hotspots release note.
- [Hotspots release note](https://deploy-preview-19635--cockroachdb-docs.netlify.app/docs/releases/v25.2#v25-2-0)
=> DOC-13752 Update 25.2.0 release note for hotspots

src/current/_includes/cockroachcloud/backups/costs-link.md, src/current/cockroachcloud/costs.md, src/current/cockroachcloud/managed-backups-advanced.md, src/current/cockroachcloud/managed-backups-basic.md, src/current/cockroachcloud/managed-backups.md
=> Add note to CC costs managed backups charge continue until deletion

src/current/_includes/cockroachcloud/backups/managed-backup-perms.md, src/current/cockroachcloud/managed-backups-advanced.md, src/current/cockroachcloud/managed-backups-basic.md, src/current/cockroachcloud/managed-backups.md
=> Add permission requirements for restoring managed backups

src/current/cockroachcloud/egress-perimeter-controls.md
Fixes DOC-14529
In egress-perimeter-controls.md, removed text regarding that Azure not supported.
=> DOC-14529 Update egress perimeter controls documentation for Azure suppor

src/current/_includes/v25.3/sidebar-data/cloud-deployments.json, src/current/cockroachcloud/egress-private-endpoints.md, src/current/cockroachcloud/security-overview.md, src/current/v25.3/cockroachdb-feature-availability.md
https://cockroachlabs.atlassian.net/browse/DOC-9981
=> Add documentation for egress private endpoints

src/current/v25.3/deploy-cockroachdb-with-cockroachdb-operator.md, src/current/v25.3/scale-cockroachdb-operator.md
https://cockroachlabs.atlassian.net/browse/DOC-14575
- Update example of pod list in scaling guide to use correct pod naming scheme
- Add `list pods` validation step to deployment guide with appropriate example
=> Update pod list examples

src/current/cockroachcloud/ccloud-faq.md
Collab w. Joe, for "Paul's awesome first docs PR"
=> Add link to Cluster Creator role in cloud FAQ

src/current/cockroachcloud/billing-management.md, src/current/cockroachcloud/cloud-api.md
https://cockroachlabs.atlassian.net/browse/DOC-12994
Follow up to https://github.com/cockroachlabs/managed-service/pull/21170
- Add info about seeing the current/in-progress invoice in the Console
- Add a section to the Cloud API docs about getting invoices via the `invoices` endpoint
=> Add get invoices section to the cloud API docs

src/current/v25.3/ldap-authentication.md
=> Fix LDAP enablement cluster setting name

src/current/_includes/v24.1/sql/session-variable-precedence-order.md, src/current/_includes/v24.3/sql/session-variable-precedence-order.md, src/current/_includes/v25.1/sql/session-variable-precedence-order.md, src/current/_includes/v25.2/sql/session-variable-precedence-order.md, src/current/_includes/v25.3/sql/session-variable-precedence-order.md, src/current/v24.1/alter-database.md, src/current/v24.1/alter-role.md, src/current/v24.1/session-variables.md, src/current/v24.1/set-vars.md, src/current/v24.3/alter-database.md, src/current/v24.3/alter-role.md, src/current/v24.3/session-variables.md, src/current/v24.3/set-vars.md, src/current/v25.1/alter-database.md, src/current/v25.1/alter-role.md, src/current/v25.1/session-variables.md, src/current/v25.1/set-vars.md, src/current/v25.2/alter-database.md, src/current/v25.2/alter-role.md, src/current/v25.2/session-variables.md, src/current/v25.2/set-vars.md, src/current/v25.3/alter-database.md, src/current/v25.3/alter-role.md, src/current/v25.3/session-variables.md, src/current/v25.3/set-vars.md
=> Add docs on session variable precedence order

src/current/_data/releases.yml
Fixes:
- REL-3056
- REL-3079
- REL-3088
=> Self-hosted downloads: v24.1.23, v24.3.19, v25.2.5

src/current/_data/releases.yml, src/current/_includes/releases/v24.1/v24.1.24.md, src/current/_includes/releases/v24.3/v24.3.20.md, src/current/_includes/releases/v25.2/v25.2.6.md, src/current/_includes/releases/v25.3/v25.3.2.md
Fixes:
- REL-3131
- REL-3145
- REL-3159
- REL-3168
=> Release: v24.1.24, v24.3.20, v25.2.6, v25.3.2

src/current/v24.1/physical-cluster-replication-overview.md, src/current/v24.3/physical-cluster-replication-overview.md, src/current/v25.2/physical-cluster-replication-overview.md, src/current/v25.3/physical-cluster-replication-overview.md, src/current/v25.4/physical-cluster-replication-overview.md
https://cockroachlabs.atlassian.net/browse/DOC-12338
Changes the youtube video ID on five supported doc versions
=> Correct demo video link for PCR Overview page

src/current/v25.2/set-up-logical-data-replication.md, src/current/v25.2/set-up-physical-cluster-replication.md, src/current/v25.3/set-up-logical-data-replication.md, src/current/v25.3/set-up-physical-cluster-replication.md
Backport of https://cockroachlabs.atlassian.net/browse/DOC-14875
@peachdawnleach fyi
=> Backport PCR/LDR through gateway docs
