cockroachdb/docs

StyleGuide.md
netlify/vale/vocab.txt

Fixes [DOC-2074](https://cockroachlabs.atlassian.net/browse/DOC-2074)
This is additional work to the **and** + **or** guidance in the style guide.

Added guidance on using and/or to style guide

---

v21.2/changefeed-sinks.md
v22.1/changefeed-sinks.md

Fixes [DOC-2687](https://cockroachlabs.atlassian.net/browse/DOC-2687) and [DOC-3625](https://cockroachlabs.atlassian.net/browse/DOC-3625)
Added missing configurations options to `kafka_sink_config` (`Bytes` and `Messages`). Also rearranged the format of the section to match the same in the webhook configuration.

Added missing kafka config fields & rearranged section format

---

_includes/v22.1/sidebar-data/manage.json
v22.1/hashicorp-database-secrets.md
v22.1/hashicorp-integration.md
v22.1/vault-db-secrets-tutorial.md

Create a tutorial on using Vault dynamic secrets for CRDB credentials, as part of our integration with Vault.
https://cockroachlabs.atlassian.net/browse/DOC-3308

Hashicorp Vault database secrets engine tutorial

---

v21.1/multiregion-overview.md
v21.2/multiregion-overview.md
v22.1/multiregion-overview.md

Fixes DOC-3573
- Previously we were talking about "maintaining a local quorum in the
leaseholder's region", which is not possible in a 3-node cluster with
3 database regions.  In such clusters the replica distribution would
be 2+2+1.
- Now we revise the paragraph to restate that for region survival goals,
reads are fast and writes pay to cross regions (in exchange for
resiliency).

Fix incorrect language about region survival goals

---

_includes/v22.1/sidebar-data/manage.json
v22.1/backup-and-restore-overview.md

Fixes [DOC-2458](https://cockroachlabs.atlassian.net/browse/DOC-2458)
This PR adds a Backup and Restore Overview page at the top of the BU/Restore navigation. The intention for this page is provide a landing area for users to understand bu/restore types, product availability, and useful features. Moving forward as significant features are added to both operations this gives us a space to direct our users through the doc set.

Draft of backup/restore overview

---

v22.1/migrate-from-csv.md

The link for the first reference IMPORT INTO reference was broken because it used brackets instead of parentheses. This replaces the brackets to make the link valid.

Make the first IMPORT INTO reference a valid link

---

v21.2/cockroach-node.md
v21.2/node-shutdown.md
v22.1/cockroach-node.md

Fixes [DOC-3623](https://cockroachlabs.atlassian.net/browse/DOC-3623).
The `--self` flag and node IDs cannot be passed with `cockroach node drain` in v21.2. This PR corrects the `cockroach node` doc and the example commands in the Node Shutdown doc, which use `cockroach node drain --host={address of node to drain}`.

fix node drain flags for v21.2

---

.github/workflows/changed_files.yml
_includes/v22.1/known-limitations/cdc.md

Addresses: DOC-4530
- Tightens `grep` match on `$filename` on our `changed_files.yaml` GH action to capture cases where `filename.md` is actually `more-to-filename.md`; current `grep` syntax matches both.
- `cdc.md` file in here to test that this works, will pull for final merge ofc.

DOC-4530 tighten grep filename match

---

_includes/sidebar-data-cockroach-university.json

The overall organization and sequence of courses
is changing. For now, we can just point users
to the CU landing page.

Remove sepcific CU courses from docs sidenav

---

_includes/v21.2/metric-names.md
_includes/v22.1/metric-names.md

Addresses: DOC-49
- Clarified that `livebytes` metric also counts unreplicated data. This is the only mention of `livebytes` in the corpus.
[v22.1/metric-names.md](url) | [v21.2/metric-names.md](url)

DOC-49 clarify livebytes metric

---

v21.1/cluster-setup-troubleshooting.md
v21.2/cluster-setup-troubleshooting.md
v22.1/cluster-setup-troubleshooting.md

Addresses: DOC-937
- Adds brief mention to _Troubleshoot Cluster Setup_ guide that covers partial availability scenario where `server.eventlog` table might not be available: set `sever.eventlog.enabled` to `false` to try to recover.
- Since this setting was first introduced in 21.1, I have propagated this docs change back to include it.
Note: this setting is not covered anywhere else in the corpus (excluding the generated [cluster-settings list](https://deploy-preview-14294--cockroachdb-docs.netlify.app/docs/v22.1/cluster-settings)). If this troubleshooting-focused inclusion is deemed unnecessary, I would suggest that this ticket is instead a no-op.
[v22.1/cluster-setup-troubleshooting.md](https://deploy-preview-14294--cockroachdb-docs.netlify.app/docs/stable/cluster-setup-troubleshooting. …

DOC-937 add server.eventlog.enabled troubleshooting

---

_includes/v21.1/sql/movr-statements-geo-partitioned-replicas.md
_includes/v21.2/sql/movr-statements-geo-partitioned-replicas.md
_includes/v22.1/sql/movr-statements-geo-partitioned-replicas.md
v21.1/topology-duplicate-indexes.md
v21.1/topology-geo-partitioned-leaseholders.md
v21.1/topology-geo-partitioned-replicas.md
v21.2/topology-duplicate-indexes.md
v21.2/topology-geo-partitioned-leaseholders.md
v21.2/topology-geo-partitioned-replicas.md
v22.1/topology-duplicate-indexes.md
v22.1/topology-geo-partitioned-leaseholders.md
v22.1/topology-geo-partitioned-replicas.md

Followup to https://github.com/cockroachdb/docs/pull/13167.
Complete restoration by:
- Updating docs to point to current version instead of v20.2.
- Updating restored pages to point to correct image path.

Zone config restoration followup.

---

v22.1/schema-design-indexes.md

Needs the update in https://github.com/cockroachdb/docs/pull/13999 that adds index recommendations to the plan properties for the link to make sense.

Add link to index recommendations from best practices.

---

_includes/v22.1/sidebar-data/reference.json
cockroachcloud/serverless-unsupported-features.md

Fixes DOC-3650.
A new topic that explicitly outlines which features are either fully or partially supported in Serverless clusters.

Topic outlining feature gaps in Serverless clusters.

---

_includes/v22.1/misc/tooling.md
_includes/v22.1/sidebar-data/develop.json
_includes/v22.1/sidebar-data/migrate.json
v22.1/aws-dms.md
v22.1/migrate-from-mysql.md
v22.1/migrate-from-oracle.md
v22.1/migrate-from-postgres.md

Fixes DOC-3681
Also adds references to AWS DMS inside existing DB migration docs

DOC-3681: Update location of AWS DMS doc in sidebar

---

advisories/a81448.md

Fixes DOC-3445.
Publish date is set to today, but can/will be updated before actually merging.

draft TA-81448

---

v21.1/install-client-drivers.md
v21.2/connect-to-the-database.md
v21.2/install-client-drivers.md
v22.1/connect-to-the-database.md
v22.1/install-client-drivers.md

- Fixes "official TypeORM documentation" broken link
- Fixes the SQLAlchemy broken link
- Fixes the outdated Django project links (updated from 3.0 to 4.0)

Update broken / outdated links

---

.github/workflows/changed_files.yml

Addresses: DOC-4630
- Extends `changed_files.yml`'s on-run logic to include PRs triggered from forks.
Note: since `changed_files,yml` only triggers on PR creation, and the test case is for a PR made from a fork, I can't think of a way to safely test this short of merging this and trying. If you can come up with a safer test, I'm all for it. Barring that, here's the change I think we need to make to support this, and we can test it live with a few mock PRs.

DOC-4630 support downstream forks

---

_includes/v22.1/sql/jsonb-comparison.md
v22.1/functions-and-operators.md
v22.1/jsonb.md

DOC-285, DOC-315, DOC-506, DOC-507.
- Added JSONB operators to Operator precedence table.
- Added example for each function in JSONB page.
- Added `#>`, `#>>`, `>@`, `?`, `?|`, `?&` operators and examples.
- Moved all limitations to Known limitations section.

JSONB example and reference improvements.

---

v22.1/changefeed-sinks.md
v22.1/create-changefeed.md

Fixes [DOC-2316](https://cockroachlabs.atlassian.net/browse/DOC-2316)
Added the webhook sink to the `client_cert` and `client_key` params on the `CREATE CHANGEFEED` page. Also added these parameters to the webhook section of the sinks page to improve discoverability.

Added changefeed webhook sink to `client_cert` and `client_key` parameter

---

cockroachcloud/quickstart.md
v21.2/connect-to-the-database.md
v22.1/connect-to-the-database.md

Remove references to downloading cockroach binary and running the "convert-url" since the cluster connect modal now provides a jdbc compatible connection url and these steps are no longer necessary.
The relevant changed pages are:
[/docs/cockroachcloud/quickstart.html?filters=java&](https://deploy-preview-14393--cockroachdb-docs.netlify.app/docs/cockroachcloud/quickstart.html?filters=java&) and  [/docs/stable/connect-to-the-database.html?filters=java](https://deploy-preview-14393--cockroachdb-docs.netlify.app/docs/stable/connect-to-the-database.html?filters=java)

Update JDBC instructions

---

cockroachcloud/serverless-faqs.md
cockroachcloud/serverless-unsupported-features.md
releases/cloud.md

This PR adds a section on managing ranges to the unsupported Serverless features topic, and adds additional cross links to the topic from the Serverless FAQ and main Cloud release notes page.

Updates to Serverless feature gap doc.

---

v22.1/ui-storage-dashboard.md

Addresses: DOC-2882
- Added three new graphs from #[77558](https://github.com/cockroachdb/cockroach/pull/77558) to `ui-storage-dashboard` listing under **Other graphs**:
- This list has been converted into a table
- Each now has a basic description, drawn from hover-text of graph title in DB Console
- Where appropriate, terms are linked to reference material
- Also added missing **Write Stalls** graph
[v22.1/ui-storage-dashboard](https://deploy-preview-14437--cockroachdb-docs.netlify.app/docs/v22.1/ui-storage-dashboard#other-graphs)

DOC-2882 add missing storage graphs

---

_includes/v22.1/known-limitations/row-level-ttl-limitations.md
v22.1/row-level-ttl.md

Fixes DOC-3545
- Note that TTL update runs a schema change; also add some specifics
around per-row overrides vs. updating the whole table
- High metrics cardinality can lead to bad perf (see CDC doc
description)
- List required privileges for TTL
- Show an example of updating `ttl_expire_after` once already set

Update row-level TTL docs with add'l details

---

v21.1/cockroach-debug-merge-logs.md
v21.2/cockroach-debug-merge-logs.md
v22.1/cockroach-debug-merge-logs.md

Addresses: DOC-995
- Fixes time range example for `cockroach debug merge-logs` for v22.1, v21.2, and v21.1.
Note: We don't normally go back any further in docs edits (not even supposed to do v21.1 in fact now!) but I see you filed the original issue against v20.1. If you like, I'll extend this fix back that far also, just let me know.
[v22.1/cockroach-debug-zip.md](https://deploy-preview-14534--cockroachdb-docs.netlify.app/docs/stable/cockroach-debug-merge-logs.html#example) | [v21.2/cockroach-debug-zip.md](https://deploy-preview-14534--cockroachdb-docs.netlify.app/docs/v21.2/cockroach-debug-merge-logs#example) | [v21.1/cockroach-debug-zip.md](https://deploy-preview-14534--cockroachdb-docs.netlify.app/docs/v21.1/cockroach-debug-merge-logs)

DOC-995 fix debug merge-logs time range example

---

_includes/contribute-options.html
_layouts/page.html

These options were accidentally removed as part of
experiments in https://github.com/cockroachdb/docs/pull/14436.
Adding these back with a few changes:
- The drop-down now offers 2 options: Edit This Page and Report Doc Issue.
The previous third option, Suggest New Content, rarely got engagement
and is probably covered by Report Doc Issue.
- The Report Doc Issue now uses the same GH issue template as the
Was this page helpful? No vote.

Add back contribute options to docs pages

---

v21.1/ui-cluster-overview-page.md

Addresses: DOC-2875
- Added note to `ui-cluster-overview-page.md` for version v21.1 only indicating that Capacity metric may be incorrect, linking to known issue entry for 21.1.
[21.1/ui-cluster-overview-page.md](https://deploy-preview-14541--cockroachdb-docs.netlify.app/docs/v21.1/ui-cluster-overview-page#cluster-overview-panel)

DOC-2875 note capacity incorrect for 21.1 only

---

v21.2/show-backup.md
v22.1/show-backup.md

Fixes [DOC-3224](https://cockroachlabs.atlassian.net/browse/DOC-3224) and [DOC-3207](https://cockroachlabs.atlassian.net/browse/DOC-3207)
These docs issues were both related to adding the byte size and row count to the output for tenant backups. This doesn't need documentation separately, but while checking this, noticed that `rows` was missing from the responses table on the `SHOW BACKUP` page. It is already included in the example output. This PR adds that.

Added rows output to the show backup response table

---

v22.1/build-a-python-app-with-cockroachdb.md

Tag `{{ site.data.products.db }} ` expands as `CockroachDB Cloud` regardless of tab selected. This causes users who select the "Use a Local Cluster" tab to still see the direction: "connect to your CockroachDB Cloud cluster" in [Step 4](https://www.cockroachlabs.com/docs/stable/build-a-python-app-with-cockroachdb.html?filters=local#step-4-run-the-code).
This commit truncates the directive to simply "connect to your cluster".
[v22.1/build-a-python-app-with-cockroachdb.md](https://deploy-preview-14553--cockroachdb-docs.netlify.app/docs/v22.1/build-a-python-app-with-cockroachdb.html)

Genericize cluster description

---

_includes/v21.2/prod-deployment/cloud-report.md
_includes/v21.2/prod-deployment/recommended-instances-aws.md
_includes/v21.2/prod-deployment/recommended-instances-azure.md
_includes/v21.2/prod-deployment/recommended-instances-gcp.md
_includes/v22.1/prod-deployment/cloud-report.md
_includes/v22.1/prod-deployment/recommended-instances-aws.md
_includes/v22.1/prod-deployment/recommended-instances-azure.md
_includes/v22.1/prod-deployment/recommended-instances-gcp.md
v21.2/deploy-cockroachdb-on-aws.md
v21.2/deploy-cockroachdb-on-google-cloud-platform-insecure.md
v21.2/deploy-cockroachdb-on-google-cloud-platform.md
v21.2/deploy-cockroachdb-on-microsoft-azure-insecure.md
v21.2/deploy-cockroachdb-on-microsoft-azure.md
v21.2/performance-benchmarking-with-tpcc-large.md
v21.2/performance-benchmarking-with-tpcc-medium.md
v21.2/performance-benchmarking-with-tpcc-small.md
v21.2/performance.md
v21.2/recommended-production-settings.md
v22.1/deploy-cockroachdb-on-aws.md
v22.1/deploy-cockroachdb-on-google-cloud-platform-insecure.md
v22.1/deploy-cockroachdb-on-google-cloud-platform.md
v22.1/deploy-cockroachdb-on-microsoft-azure-insecure.md
v22.1/deploy-cockroachdb-on-microsoft-azure.md
v22.1/performance-benchmarking-with-tpcc-large.md
v22.1/performance-benchmarking-with-tpcc-medium.md
v22.1/performance-benchmarking-with-tpcc-small.md
v22.1/performance.md
v22.1/recommended-production-settings.md

Fixes DOC-3742.
Fixes DOC-3391.
Updated the following per 2022 Cloud Report:
- Recommended instance types for GCP, AWS, Azure
- Added some additional workload-specific recommendations
Also moved the instance recs into includes so that these are updated across all docs.

update recs per 2022 Cloud Report

---

_includes/v21.1/prod-deployment/secure-scale-cluster.md
_includes/v21.1/prod-deployment/secure-start-nodes.md
_includes/v21.2/prod-deployment/secure-scale-cluster.md
_includes/v21.2/prod-deployment/secure-start-nodes.md
_includes/v22.1/prod-deployment/secure-scale-cluster.md
_includes/v22.1/prod-deployment/secure-start-nodes.md

Addresses: DOC-5141
- (versions v22.1, v21.2, v21.1) Fixed `chown` step in deployment docs to use `cockroach:cockroach` to properly set ownership for both user and group.
[v22.1/deploy-cockroachdb-on-premises.md](https://deploy-preview-14607--cockroachdb-docs.netlify.app/docs/stable/deploy-cockroachdb-on-premises.html?filters=systemd#step-3-start-nodes) | [v21.2/deploy-cockroachdb-on-premises.md](https://deploy-preview-14607--cockroachdb-docs.netlify.app/docs/v21.2/deploy-cockroachdb-on-premises.html?filters=systemd#step-3-start-nodes) | [v21.1/deploy-cockroachdb-on-premises.md](https://deploy-preview-14607--cockroachdb-docs.netlify.app/docs/v21.1/deploy-cockroachdb-on-premises.html?filters=systemd#step-3-start-nodes)

DOC-5141 fix deploy systemd chown

---

v21.1/ui-sql-dashboard.md
v21.2/ui-sql-dashboard.md
v22.1/ui-sql-dashboard.md

This came up as a point of confusion on this community slack thread: https://cockroachdb.slack.com/archives/CP4D9LD5F/p1646720306266029

Clarify wording for Open SQL Transactions chart

---

v21.2/ui-debug-pages.md
v21.2/ui-overview.md
v22.1/ui-debug-pages.md
v22.1/ui-overview.md

Addresses: DOC-2567
- Expanded Ryan's DOC-2821 to also address `v21.2` (backported in #[76694](https://github.com/cockroachdb/cockroach/pull/76694)): re-used his copy as base.
- Expanded above to also introduce `?remote_node_id=` and to mention that this setting is also reused for **Profiling UI** section.
- Added new _Proxy DB Console_ section to `ui_overview` for both `v22.1` and `v21.2` to detail two methods for proxying: Advanced Debug > Web server, and `?remote_node_id=`.
- To keep sensical ordering of subheadings, created new _Console security considerations_ heading to house two security subheadings and be able to retain `Access to DB Console is a function` statement.
Note: This PR omits the third proxy option of manually setting a cookie, as that is likely not useful to end users …

DOC-2567 DB Console proxy to any node

---

v22.1/backup.md
v22.1/import-into.md
v22.1/import.md
v22.1/restore.md

Fixes [DOC-3506](https://cockroachlabs.atlassian.net/browse/DOC-3506)
Added a note to the performance section of `RESTORE`, `IMPORT`, & `BACKUP` on pausing if reaching maximum retries. 
Also, opportunistic edit adding new version feature to a prior bullet that I missed in the original PR. 
Furthermore, added `IMPORT` performance bullets to `IMPORT INTO` as I believe these all belong there too and had been missing.

Added note to performance section on pausing jobs after max retries

---

_includes/cockroachcloud/ccloud/quickstart.md
_includes/v22.1/setup/init-bank-sample.md
_includes/v22.1/setup/sample-setup-certs.md
_includes/v22.1/setup/sample-setup-jdbc.md
_includes/v22.1/setup/sample-setup-parameters-certs.md
_includes/v22.1/setup/sample-setup-parameters.md
_includes/v22.1/setup/sample-setup.md
cockroachcloud/quickstart.md
v22.1/build-a-go-app-with-cockroachdb-gorm.md
v22.1/build-a-go-app-with-cockroachdb-pq.md
v22.1/build-a-java-app-with-cockroachdb.md
v22.1/build-a-nodejs-app-with-cockroachdb-knexjs.md
v22.1/build-a-nodejs-app-with-cockroachdb-prisma.md
v22.1/build-a-nodejs-app-with-cockroachdb-sequelize.md
v22.1/build-a-python-app-with-cockroachdb-django.md
v22.1/build-a-python-app-with-cockroachdb.md
v22.1/build-a-ruby-app-with-cockroachdb-activerecord.md
v22.1/build-a-ruby-app-with-cockroachdb.md

This PR updates the simple CRUD tutorials with a `ccloud` option.
Fixes DOC-3635.

Update simple CRUD examples with ccloud option

---

StyleGuide.md
netlify/vale/vocab.txt

Fixes DOC-1927
- Add a new section to the style guide on include files, including:
- What they are
- When to use them (and that one should consider not using them, if
possible)
- How to use them (basic and more advanced methods)
- Technical limitations

Update style guide re: include file usage

---

_config_base.yml
_includes/latest_operator_version.md
_includes/v20.2/orchestration/kubernetes-stop-cluster.md
_includes/v20.2/orchestration/start-cockroachdb-operator-secure.md
_includes/v21.1/orchestration/kubernetes-stop-cluster.md
_includes/v21.1/orchestration/start-cockroachdb-operator-secure.md
_includes/v21.1/orchestration/test-cluster-secure.md
_includes/v21.2/orchestration/kubernetes-stop-cluster.md
_includes/v21.2/orchestration/start-cockroachdb-operator-secure.md
_includes/v21.2/orchestration/test-cluster-secure.md
_includes/v22.1/orchestration/kubernetes-stop-cluster.md
_includes/v22.1/orchestration/start-cockroachdb-operator-secure.md
_includes/v22.1/orchestration/test-cluster-secure.md
netlify/vale/vocab.txt
releases/kubernetes-operator.md
v21.1/deploy-cockroachdb-with-kubernetes-openshift.md
v21.1/operate-cockroachdb-kubernetes.md
v21.2/deploy-cockroachdb-with-kubernetes-openshift.md
v21.2/scale-cockroachdb-kubernetes.md
v21.2/schedule-cockroachdb-kubernetes.md
v22.1/deploy-cockroachdb-with-kubernetes-openshift.md
v22.1/kubernetes-overview.md
v22.1/scale-cockroachdb-kubernetes.md
v22.1/schedule-cockroachdb-kubernetes.md

Followup work from https://github.com/cockroachdb/cockroach-operator/pull/924
The second commit replaces a site-wide variable for the Operator version with a remote include that dynamically pulls the version from the upstream repo. That's the reason this PR touches so many old files.
**Non-docs reviewers: You need only check the 2.8.0 section of `kubernetes-operator.md` and the first preview link in this list:**
Sampling of previews, sorted by CRDB version:
- https://deploy-preview-14620--cockroachdb-docs.netlify.app/docs/releases/kubernetes-operator.html
- https://deploy-preview-14620--cockroachdb-docs.netlify.app/docs/v22.1/schedule-cockroachdb-kubernetes.html
- https://deploy-preview-14620--cockroachdb-docs.netlify.app/docs/v22.1/deploy-cockroachdb-with-kubernetes.html#step-5-stop-the-c …

Kubernetes Operator 2.8.0 release notes

---

v21.1/schema-design-indexes.md
v21.2/schema-design-indexes.md
v22.1/schema-design-indexes.md

Fixes DOC-313
- In composite indexes, columns with a higher cardinality (higher number of distinct values) should go before columns with lower cardinality.

DOC-313: Added note about cardinality for composite indexes

---

_config_base.yml
_data/releases.csv
_includes/releases/v22.1/v22.1.5.md

Addresses: DOC-4573
- Release notes for v22.1.5
Guess: the following selected changelog entries might not be intended for end users:
```
- Fixed the following builtins so that users can only run them if they have [`SELECT`](../v22.1/selection-queries.html) privileges on the relevant tables: `crdb_internal.revalidate_unique_constraints_in_all_tables`, `crdb_internal.revalidate_unique_constraints_in_table`, and `crdb_internal.revalidate_unique_constraint`. [#84269][#84269]
- `crdb_internal.decode_plan_gist` will no longer produce an internal error when it is used to decode a plan gist for which no schema information is available. [#84726][#84726]
- The [sampled query telemetry log] ... (x2) (as Telemetry channel is described as "Telemetry events for internal usage")
- Introduced a new …
```

DOC-4573 v22.1.5 release notes

---

_config_base.yml
_data/releases.csv
_includes/releases/v21.2/v21.2.14.md

Addresses: DOC-1901
- Release notes for v21.2.14
[v21.2.md](https://deploy-preview-14684--cockroachdb-docs.netlify.app/docs/releases/v21.2.html#v21-2-14)

DOC-1901 v21.2.14 release notes

---

v22.1/backup-architecture.md

Quick fix to a copy error in from feedback in backup arch docs.

Fix to copy error

---

_includes/v22.1/sidebar-data/reference.json

This is a quick fix to the alphabetical order of the SQL statements. Seems like there was some sort of clash between PRs as the `ADD SUPER REGION` docs were added that changed the ordering on `ALTER BACKUP`.

Correct alpha order of SQL statements

---

releases/v22.1.md

When a new version of the docs is cut, this page will be prepared
to handle users who may try to manually access this URL in between
when the docs are cut and the first alpha becomes available.

Update the splash screen for new versions of docs

---

v22.1/build-a-python-app-with-cockroachdb.md

This PR updates the output of the psycopg2 example to match the changes to use [UUIDs for the primary keys in the example source repo](https://github.com/cockroachlabs/hello-world-python-psycopg2/pull/9).
Part of DOC-4903.

Updated output for refactored example that uses UUIDs for the PK.

---

cockroachcloud/monitoring-page.md

Addresses: DOC-5229
- Added new section to Datadog integration setup steps to advise of the need to explicitly enable percentiles for the `DISTRIBUTION` type metrics from Dedicated.
Question:
- I'm not certain about its location on page -- good place?
- ~Did I extrapolate correctly with my assumption-ridden final two sentences? Please correct me if I guess wrong!~
- ~What if I ran DD intergration overnight but forgot this step until this morning. Does enabling percentiles now allow me to suddenly see last night's data too? Or only moving forwards once enabled?~ Thanks Alex for the assist!
[cockroachcloud/monitoring-page.md](https://deploy-preview-14709--cockroachdb-docs.netlify.app/docs/cockroachcloud/monitoring-page#enable-percentiles-for-selected-metrics)

DOC-5229 enable percentiles for some DD metrics

---

StyleGuide.md

Quick update to Style Guide to remove the duplicate reference to Serverless under product naming.

Removed duplicate Serverless listing from Style Guide

---

cockroachcloud/upgrade-policy.md

https://cockroachlabs.atlassian.net/browse/DOC-3007
Part of the ticket request was to put the self-hosted and cloud support policies on the same page, which I don't think would make sense. Confirmed instead that each support policy page specifies which product it's for and links to the other one.

Clarify Support Policy for Cloud vs Self-Hosted

---

_includes/sidebar-data-v20.1.json
_includes/sidebar-data-v20.2.json
_includes/v21.1/sidebar-data-reference.json
_includes/v21.2/sidebar-data/reference.json
_includes/v22.1/sidebar-data/reference.json
v20.1/cockroach-auth-session.md
v20.1/cockroach-commands.md
v20.2/cockroach-auth-session.md
v20.2/cockroach-commands.md
v21.1/cockroach-auth-session.md
v21.1/cockroach-commands.md
v21.2/cockroach-auth-session.md
v21.2/cockroach-commands.md
v22.1/cockroach-auth-session.md
v22.1/cockroach-commands.md

Addresses: DOC-436
- Adds reference documentation for the `cockroach auth-session` command, incl. its three subcommands `login`, `logout`, and `list`, as well as command-specific flags `--expire-after` and `--only-cookie`.
- Provides some general-use examples, including an example of using `--only-cookie` with `curl`.
Note:
- This effort goes back further than we usually go, given `auth-session` was introduced in `20.1` and has strong backwards compatibility (is client-change-only). Please verify that things like the `_status/logfiles/local` example I use is appropriate for, say, v20.1. Happy to replace with a version-appropriate example if needed (concerned about something like, say, api v1 vs. v2 for example). Alternately, if the example I use is not helpful, happy to replace with one …

DOC-436 auth-session reference

---

_includes/v22.1/metric-names.md

Addresses: DOC-3006
- Adds `range.snapshots.rcvd-bytes` and `range.snapshots.sent-bytes` to `v22.1` metrics listing. This is the only place in the corpus we list / refer to these raw metrics, so this is a tiny PR.
**Note:** the table housing these metrics is prefaced by a [note](https://www.cockroachlabs.com/docs/stable/ui-custom-chart-debug-page.html#available-metrics) that explains: `This list is taken directly from the source code ...` Does this indicate that this list is programmatically generated elsewhere and that I should instead be editing the source script?
[metric-names.md](https://deploy-preview-13968--cockroachdb-docs.netlify.app/docs/v22.1/ui-custom-chart-debug-page#available-metrics)

DOC-3006 add metric snapshot bytes sent/recv

---

v22.1/cockroach-node.md
v22.1/node-shutdown.md

Addresses: DOC-3033
This feature has now been backported to v22.1 (#[79516](https://github.com/cockroachdb/cockroach/pull/79516))
- `node-shutdown.md` : added mention of `possible decommission stall detected` message to both "Decommissioning" and "Decommission the node" sections
- `cockroach-node.md` : added mention of `possible decommission stall detected` message to "`node decommission`" output section.
[v22.1/node-shutdown.md](https://deploy-preview-14547--cockroachdb-docs.netlify.app/docs/stable/node-shutdown.html?filters=decommission#decommissioning) | [v22.1/cockroach-node.md](https://deploy-preview-14547--cockroachdb-docs.netlify.app/docs/stable/cockroach-node.html#node-decommission)

DOC-3033 report stuck replicas in decom

---

v22.1/manage-certs-vault.md
v22.2/manage-certs-vault.md

Addresses: DOC-5371
- Converts hardcoded CRDB versions to dynamic for v22.2 and v22.1:
- Only appeared on one page in both versions: `manage-certs-vault.md`
- Will need DOCs writer approval, as specific tag may be required for a reason I could not determine from copy on-page.
- Please note that v22.2 binary naming omits specific minor, as v22.2 does not yet have a first alpha. This is in keeping with existing approach for dev docs, as seen also [here](https://deploy-preview-14862--cockroachdb-docs.netlify.app/docs/dev/deploy-cockroachdb-on-premises.html#step-3-start-nodes). This will auto-populate corrected with issuance of first alpha.
[v22.2/manage-certs-vault.md](https://deploy-preview-14862--cockroachdb-docs.netlify.app/docs/dev/manage-certs-vault.html#install-cockroachdb-on-each-node- …

DOC-5371 convert hardcoded versions

---

_includes/head.html
_layouts/default.html
js/comparison-chart.js

Fix:
- select2 loading issue on comparison charts
Feat:
- remove extra jquery load
Next Task:
- Add a default behavior for comparison chart instead of loading everything (select2 does the job but we want to have something not switching while is loading)
Fixes DOC-5415

fix: select2 loading issue

---

v21.2/install-cockroachdb-mac.md
v22.1/install-cockroachdb-mac.md
v22.2/install-cockroachdb-mac.md

[DOC-417] Provide workaround to run the cockroach binary on macOS

---

v21.2/restore.md
v22.1/restore.md
v22.2/restore.md

Fixes [DOC-1130](https://cockroachlabs.atlassian.net/browse/DOC-1130)
Added points to the full cluster restore section on the changes in behavior to restore for temp tables and pre-loaded databases.

Added to full cluster restore on temp tables and default dbs

---

v21.2/use-cloud-storage-for-bulk-operations.md
v22.1/use-cloud-storage-for-bulk-operations.md
v22.2/use-cloud-storage-for-bulk-operations.md

To fix the filter issue on the Use Cloud Storage for Bulk Ops page, adjusted the name ID of the second filter. Although this means the filters won't adjust together between the two relevant sections, it seems a worthwhile trade-off to keep the filters in both sections that are distinct from one another. Also, this makes the most sense in the case that further _different_ storage options are added, or where storage options aren't applicable to the two sections in question. https://www.cockroachlabs.com/docs/v21.2/use-cloud-storage-for-bulk-operations

Fix to filter issue on cloud storage bulk ops pages

---

_includes/v22.1/known-limitations/copy-syntax.md
_includes/v22.2/known-limitations/copy-syntax.md
v22.1/copy-from.md
v22.2/copy-from.md

Fixes DOC-3052
- Change COPY FROM docs to use `cockroach sql` instead of `psql`, since it works in v22.1+
- Add info about `COPY ... FROM STDIN WITH CSV [DELIMITER ... ESCAPE ...]`

Update COPY FROM docs with v22.1 improvements

---

cockroachcloud/console-access-management.md

DOC-2884
Developers have sql admin privs on a cluster. Calling this out under both the SQL User and Developer sections as it can be a security issue.

Developer vs sql admin clarification

---

cockroachcloud/troubleshooting-page.md

The introduction of the Create Database feature removes the need for a user to consult documentation to recover form a db-less state.

Remove deleted non-system db instructions

---

.gitattributes

... by setting up the .gitattributes file to recognize Markdown
files (*.md).
This will result in diffs that are easier to read since the hunk context
will prefer to display nearby Markdown headings rather than random
nearby text.
Hopefully a small quality of life improvement.

Tell git to make nicer diffs for Markdown files

---

StyleGuide.md

Clarifying use of bold text when documenting UI elements, and explicitly recommending when to avoid this.

clarify use of bold text with UI elements

---

StyleGuide.md
_includes/v20.1/orchestration/kubernetes-limitations.md
_includes/v20.2/orchestration/kubernetes-limitations.md
_includes/v21.1/orchestration/kubernetes-limitations.md
_includes/v21.2/orchestration/kubernetes-limitations.md
_includes/v22.1/orchestration/kubernetes-limitations.md
_includes/v22.2/orchestration/kubernetes-limitations.md

Also add a style guide entry about referring to CRDB versions.
🙏 
- @meridional The k8s doc changes (only need to review the latest version)
- @nickvigilante The style guide update and the way I'm using the variables in the k8s content
- @stbof Overall content reviewer

Update language about minimum supported k8s version

---

_data/releases.csv
_includes/releases/release-downloads-docker-image.md

Addresses: DOC-5586
- Fixed SQL-only binary DL path to include extension, affecting Linux, macOS, and Windows. Currently they 404. This is for v22.2 only.
- Removed sql-only download links for v22.1 non-prod releases, as they were also 404ing, and releases team approved.
[v22.2.md](https://deploy-preview-15017--cockroachdb-docs.netlify.app/docs/releases/v22.2.html) | [releases.md](https://deploy-preview-15017--cockroachdb-docs.netlify.app/docs/releases/index.html)

DOC-5586 fix sql-only binary dl

---

_includes/cockroachcloud/private-preview.md
_includes/feature-phases/preview-opt-in.md
_includes/feature-phases/preview.md
_includes/feature-phases/private-preview.md
cockroachcloud/cloud-sso.md
cockroachcloud/cmek.md
cockroachcloud/export-logs.md

This PR does the following:
- Creates a new `_includes/feature-phases` directory
- Updates the existing `private-preview` include to be in the new directory. Also changes this existing include to be called `preview-opt-in` instead of `private-preview`
- Creates a new `preview` include for features that are available to all users (not just those who opt-in)
- Creates a new `private-preview` include
Closes DOC-3758

DOC-5378 Add includes for Preview/Private Preview callouts

---

_includes/v21.2/metric-names.md

Addresses: DOC-3085
- Simple docs update for v21.2 backport: https://github.com/cockroachdb/cockroach/pull/79056
[metric-names.md](https://deploy-preview-14869--cockroachdb-docs.netlify.app/docs/v21.2/ui-custom-chart-debug-page#available-metrics)

DOC-3085 add metric snapshot bytes 21.2

---

v21.1/cluster-api.md
v21.2/cluster-api.md
v22.1/cluster-api.md
v22.2/cluster-api.md

Addresses: DOC-5260
- Added mention of newly-doc'd `auth-session` CLI to the Cluster API reference landing page for versions v21.1 - v22.2 incl.
- Removed sentence that was `/login`-endpoint-specific, now that `auth-session` is also avail.
[v22.2/cluster-api.md](https://deploy-preview-14867--cockroachdb-docs.netlify.app/docs/dev/cluster-api.html#requirements) | [v22.1/cluster-api.md](https://deploy-preview-14867--cockroachdb-docs.netlify.app/docs/stable/cluster-api.html#requirements) | [v21.2/cluster-api.md](https://deploy-preview-14867--cockroachdb-docs.netlify.app/docs/v21.2/cluster-api.html#requirements) | [v21.1/cluster-api.md](https://deploy-preview-14867--cockroachdb-docs.netlify.app/docs/v21.1/cluster-api.html#requirements)

DOC-5260 add auth-session to cluster api ref

---

Gemfile

This PR supports the changes needed to get our site to build on Ubuntu Focal.

Migrate Netlify build from Xenial to Focal

---

_includes/head.html
_includes/stable_page_names.md
sitemap.xml

Enhancements:
1. Updated head.html to inject robots noindex tag for all pages that don't belong to the sitemap.
2. The sitemap now includes all pages in dev/ that don't exist in stable/.
Fixes DOC-5567

Improve sitemap rendering and meta tagging for SEO

---

_includes/head.html

We don't want the docs site itself not to be indexed. This fixes that bug.

Remove noindex tag from main docs index

---

netlify/build

`go get` is deprecated and it was causing funky things with the build. This will take care of that.

Update htmltest to use curl instead of go get

---

_includes/releases/v22.1/v22.1.4.md
_includes/releases/v22.1/v22.1.5.md
v22.1/known-limitations.md

Addresses: DOC-5379
- Added brief known limitation to v22.1.4 and v22.1.5 release notes advising of DB Console metrics page load failure / slowness.
- Added same mention to v22.1 standard `known-limitations` page.
NOTE: Indicating that v22.1.6 contains the fix. Confirming this is the case?
EDIT: v22.1.6 is now actually live, so amending text to accommodate.
[v22.1.md](https://deploy-preview-14854--cockroachdb-docs.netlify.app/docs/releases/v22.1.html#v22-1-5) | [known-limitations.md](https://deploy-preview-14854--cockroachdb-docs.netlify.app/docs/stable/known-limitations.html#new-limitations)

DOC-5379 add dbconsole metrics known issue

---

v22.2/node-shutdown.md

Addresses: DOC-5372
- Updates all CLI output for `cockroach node` commands to reflect running v22.2 output, now that alpha is live.
- Obfuscated username in filepath while in here.
- Checked all other `md `files under `v22.2/` path, this is the only file that needed to be updated.
[node-shutdown.md](https://deploy-preview-15000--cockroachdb-docs.netlify.app/docs/v22.2/node-shutdown)

DOC-5372 update node shutdown with v22.2 output

---

_config_base.yml
_data/releases.csv
_includes/releases/v21.1/v21.1.21.md

Addresses: DOC-5662
- v21.1.21 release notes.
[v21.1.md](https://deploy-preview-15095--cockroachdb-docs.netlify.app/docs/releases/v21.1.html#v21-1-21)

DOC-5662 v21.1.21 release notes

---

Gemfile
_config_base.yml
sitemap.xml

Fixes DOC-5593
This helps pave the way for Google to effectively identify when content changes, with the exception of modifying any includes referenced in the file. After this is merged, we can then trigger a sitemap update during the Netlify build and have Google identify which pages need to change.

DOC-5593: Add lastmod tag to sitemap

---

v22.1/connection-parameters.md
v22.2/connection-parameters.md

Addresses DOC-5704
- removed typo from v22.2 and v22.1
Staging:
[v22.1 Connection Parameters](https://deploy-preview-15163--cockroachdb-docs.netlify.app/docs/stable/connection-parameters.html#connect-using-discrete-parameters)
[v22.2 Connection Parameters](https://deploy-preview-15163--cockroachdb-docs.netlify.app/docs/dev/connection-parameters.html#connect-using-discrete-parameters)

DOC-5704 removed typo

---

_includes/v22.1/metric-names-serverless.md
_includes/v22.2/metric-names-serverless.md
v22.1/ui-custom-chart-debug-page.md
v22.2/ui-custom-chart-debug-page.md

Addresses: DOC-4858
- Added new discrete metrics listing just for Serverless
- Added for both v22.1 and v22.2, with output tested against live v22.1 and v22.2 `chartcatalog` output respectively.
- Added tab support to Custom chart page
Question: [Upstream metrics listing](https://github.com/cockroachlabs/managed-service/blob/master/pkg/otel/assets/metrics.yaml) format permutes metrics names in a way I am not aware of. I guessed:
```
echo $METRICNAME | sed 's%\.%_%g'
echo $METRICNAME | sed 's%\-%_%g'
```
As well as, of course, any originating `_` characters already present retained as-is. Example showing all three in action:
```
admission.wait_sum.sql-sql-response --> admission_wait_sum_sql_sql_response
```
However, this approach leaves us missing `4` metrics from the v22.1 results, and …

DOC-4858 serverless obs metrics

---

v21.1/monitor-cockroachdb-kubernetes.md
v21.2/monitor-cockroachdb-kubernetes.md
v22.1/monitor-cockroachdb-kubernetes.md
v22.2/monitor-cockroachdb-kubernetes.md

Addresses: DOC-3670
- Updates hardlink to CoreOS Prometheus Operator to `v0.58.0` from `v0.47.1`
- Doubles up on notice to replace example hardcoded version with latest version
- Adds `--server-side` to `apply` step
- Updates command output to match use of `--server-side`
Question:
- Your ZD ticket has the end user split the yaml payload into two files, and only suggests using `--server-side` with one of them. Is that because your client already had an extant config, and new users -- i.e. those following this docs page -- would not need to split as you have?
Alternatives:
- If approach: "look up latest, then replace hardcoded with your findings" is too cumbersome, we can instead just direct users to download latest `bundle.yaml` from …

DOC-3670 update prometheus operator

---

v22.1/ui-insights-page.md

The 22.2 Insights UI pages point to `/docs/stable/ui-insights-page.html` but that page won't exist until GA.  In fact, `/docs/dev/ui-insights-page.html` probably won't be published either when the beta is released because [the PR](https://github.com/cockroachdb/docs/pull/15074) is still under development.  This is a placeholder page in `/docs/v22.1/ui-insights-page.html` which maps to  `/docs/stable/ui-insights-page.html` that says the feature is under development so that the link from the UI doesn't return 404.

Provide a placeholder for the link to the Insights page in the Insights UI.

---

_includes/head.html

Using Segment for page tracking enables consistent user IDs with the CockroachDB Cloud console, and allows us to configure where events are sent without redeploying this site. Add the standard Segment snippet, which fires a page impression on-load by default.

infra: add Segment snippet + page impression to all pages

---

cockroachcloud/export-logs.md

Addresses: DOC-5661
- Adds a new FAQ entry advising that an AWS External ID is not supported for use with log export targeting AWS CloudWatch.
[export-logs.md](https://deploy-preview-15102--cockroachdb-docs.netlify.app/docs/cockroachcloud/export-logs#can-i-use-an-aws-external-id-with-the-log-export-feature)

DOC-5661 log export externalid not supported

---

v21.2/cockroach-start.md
v22.1/cockroach-start.md
v22.2/cockroach-start.md

Fixes DOC-896
Fixes DOC-5570
- Update `cockroach start` page to use `--locality` flag as expected by our multiregion SQL statements
- ... including the usage example in the `--locality` section
- and adding a new 'Examples > Start a multi-region cluster' section
- Further, sprinkle in some more links to the 'Multi-region Capabilities Overview' page so folks go there first before partitioning, zone configs, etc.
- Also updated the tip at top of page to add a link to the 'Test Your Application' page which has some info for devs about what settings etc to use for local testing of apps using CRDB

Update cockroach start docs with MOAR MULTIREGION

---

_data/releases.csv

Related to https://github.com/cockroachdb/cockroach/issues/88833. The `cockroach-sql` binary was incorrectly bundled as the full binary for v22.1.7 and v22.1.6. This PR removes the download from the docs.

Removing cockroach-sql for v22.1.7 and v22.1.6.

---

_data/releases.csv

SQL binary is still the full binary in v22.1.8. This PR removes the download link.

Removing SQL binary download for v22.1.8

---

_config_base.yml
_data/releases.csv
_includes/releases/v22.2/v22.2.0-beta.2.md

Addresses: DOC-4604
- Release notes for v22.2.0-beta.2
[v22.2.md](https://deploy-preview-15270--cockroachdb-docs.netlify.app/docs/releases/v22.2.html#v22-2-0-beta-2)

DOC-4604 v22.2.0-beta.2 release notes

---

_includes/head.html

The Segment JS client library locally persists the user’s ID and traits [1] and the user’s group ID and group properties [2] by default, using predefined names to store those values. Unfortunately, this means that any other Segment integration on the same domain that *doesn't* limit its persistence to a specific subdomain [3] (e.g. Open edX instance hosted on university.cockroachlabs.com) will overwrite any values persisted by any other Segment integration on that domain. In other words, the most recent analytics.identify() call sets the user ID for all other subdomains.
For example, loading cockroachlabs.cloud would correctly set the CC user ID for www.cockroachlabs.com, but loading university.cockroachlabs.com would overwrite the CC user ID until the user reloads cockroachlabs.cloud. …

analytics: persist Segment user and group ID & traits with non-standard names

---

_redirects
sitemap.xml
v22.1/build-a-python-app-with-cockroachdb-peewee.md
v22.1/install-cockroachdb.md
v22.1/topology-duplicate-indexes.md
v22.1/topology-geo-partitioned-leaseholders.md
v22.1/topology-geo-partitioned-replicas.md
v22.2/build-a-python-app-with-cockroachdb-peewee.md
v22.2/install-cockroachdb.md
v22.2/topology-duplicate-indexes.md
v22.2/topology-geo-partitioned-leaseholders.md
v22.2/topology-geo-partitioned-replicas.md

- Some pages like `install-cockroachdb.md` and the Python Peewee wrapper serve as in-page redirects and are hurting our SEO. I'm excluding those from the sitemap.
- Other pages that are redirected inside of the `_redirects` file should also be excluded because they are also hurting our SEO.
- We also have issues not being able to index the releases and advisories indexes properly, so Google can't actually process those pages. I've removed the redirects that are causing this.

Removed pages with redirects from the sitemap

---

api/cloud/v1.md

Until we work out the CORS issues between cockroachlabs.com and cockroaclabs.cloud, we need to disable using the API from the reference docs.

Disable using the API from the reference docs

---

_includes/head.html

Currently, we have some new pages, such as `ALTER FUNCTION` to support UDFs. We want these pages to be part of our search index, but Google can't index them because the canonical of these pages is set to v22.2/ instead of dev/. This PR fixes that.

Force any /dev/ canonical pages to redirect to /dev/

---

_redirects

- Asterisks are not supported inside destination URLs. It is treated as a plaintext asterisk. I replaced them with `:version` placeholders per the [Netlify documentation](https://docs.netlify.com/routing/redirects/redirect-options/#placeholders).
- For pages that have only temporarily moved, update the status code from 301 to 302.

Fix certain redirect items

---

_config_base.yml
_data/releases.csv
_includes/releases/v21.2/v21.2.17.md

Addresses: DOC-5948
- Release notes for v21.2.17, scheduled for Monday, October 17.
[v21.2.md](https://deploy-preview-15365--cockroachdb-docs.netlify.app/docs/releases/v21.2.html#v21-2-17)

DOC-5948 v21.2.17 release notes

---

_includes/v22.1/scram-authentication-recommendations.md
_includes/v22.2/scram-authentication-recommendations.md
v22.1/error-handling-and-troubleshooting.md
v22.1/security-reference/scram-authentication.md
v22.2/error-handling-and-troubleshooting.md
v22.2/security-reference/scram-authentication.md

- Also update some section headings to use non-gerund verbs, per the style guide
- Also change "plaintext" to "cleartext" when referring to passwords
[v22.2/error-handling-and-troubleshooting.md](https://deploy-preview-15254--cockroachdb-docs.netlify.app/docs/v22.2/error-handling-and-troubleshooting.html)
[v22.2/security-reference/scram-authentication.md](https://deploy-preview-15254--cockroachdb-docs.netlify.app/docs/v22.2/security-reference/scram-authentication.html)
[v22.1/error-handling-and-troubleshooting.md](https://deploy-preview-15254--cockroachdb-docs.netlify.app/docs/v22.1/error-handling-and-troubleshooting.html)
[v22.1/security-reference/scram-authentication.md](https://deploy-preview-15254--cockroachdb-docs.netlify.app/docs/v22.1/security-reference/scram-authentication.html)

[DOC-5572] Document CPU exhaustion scenario and workaround when SCRAM Authentication is enabled

---

_includes/v21.2/sidebar-data/manage.json
_includes/v22.1/sidebar-data/manage.json
_includes/v22.2/sidebar-data/manage.json
cockroachcloud/frequently-asked-questions.md
cockroachcloud/monitoring-page.md
releases/cloud.md
v21.2/datadog.md
v22.1/datadog.md
v22.2/datadog.md

Addresses: DOC-5759
- Added notice to Self-Hosted DD page advising of discrete Dedicated DD page, clarified that DD supports this integration directly, and reshuffled the intro to accommodate this additional info.
- Added Limitations section to Self-Hosted DD page, to advise that metrics are averaged over entire cluster, and granular filtering by node is not presently supported.
- Changed page name to "Monitor CockroachDB Self-Hosted with Datadog" on page and in left-nav sidebar to further clarify from Dedicated offering.
- Removed mention that there is no CC compatible monitoring endpoint -- there is now!
NOTES:
- Only made change to v22.2 for now. Once LGTM, will propagate these changes back through to v21.1 (version at which DD integration was first introduced).
- Opted not to link to …

DOC-5759 clarify datadog cloud support

---

_includes/sidebar-data-v21.1.json
_includes/v21.2/sidebar-data/develop.json
_includes/v22.1/sidebar-data/develop.json
_includes/v22.2/sidebar-data/develop.json
v21.1/local-testing.md
v21.2/local-testing.md
v22.1/local-testing.md
v22.2/local-testing.md

Addresses DOC-2290
- Included 'local' in header, nav, first sentence
- Changed v22.2, 22.1, 21.2, 21.1 
[Staging](https://deploy-preview-15359--cockroachdb-docs.netlify.app/docs/stable/local-testing.html)

clarified testing page for local env

---

_includes/sidebar-data-cockroachcloud.json
cockroachcloud/cloud-api.md
cockroachcloud/cloud-audit-logs.md
cockroachcloud/cloud-org-audit-logs.md

[DOC-4826]
Reviewers:
- Please review directly in Github rather than ReviewBoard.
[cockroachcloud/cloud-api.md](https://deploy-preview-15349--cockroachdb-docs.netlify.app/docs/cockroachcloud/cloud-api.html)
[cockroachcloud/cloud-org-audit-logs.md](https://deploy-preview-15349--cockroachdb-docs.netlify.app/docs/cockroachcloud/cloud-org-audit-logs.html)

[DOC-4826] Document Cloud organization audit log API

---

_data/cloud_api_releases.csv
api/cloud/v1.md

Fixes DOC-5986.
This PR adds the audit log Private Preview spec to the version selector. It also adds the ability to set the version as a query parameter by setting `version=<version>`. The version is the date for GA specs, and the subdirectory of `https://cockroachlabs.cloud/assets/docs/private-preview/` for Private Preview specs.
E.g. for audit logs, the URL is `/docs/api/cloud/v1.html?version=audit-logs`.

Add audit logs Private Preview spec, query param version

---

js/customscripts.js
search.html

This change now points users to go to `/dev` and `/stable` URLs instead of `/vXX.Y`.

Update search page to bring users to /dev and /stable instead of /vXX.Y

---

_config_base.yml
_includes/sidebar.js.html
netlify/build
search.html

This will help remove some of the burden Google has to navigate multiple URLs while crawling our site. The hope is that this will increase our crawl budget. This should not have any end-user impact.
Additionally, this now allows search to search the local instance running Jekyll, whether that be the Netlify build or the local `make standard` target.

DOC-5726: Force absolute URLs in sidebar

---

v21.2/cluster-setup-troubleshooting.md
v22.1/cluster-setup-troubleshooting.md
v22.2/cluster-setup-troubleshooting.md

[DOC-2956]
NB: Also fixes some trailing whitespace issues in the edited files.
[v21.2/cluster-setup-troubleshooting.md](https://deploy-preview-15466--cockroachdb-docs.netlify.app/docs/v21.2/cluster-setup-troubleshooting.html)
[v22.1/cluster-setup-troubleshooting.md](https://deploy-preview-15466--cockroachdb-docs.netlify.app/docs/v22.1/cluster-setup-troubleshooting.html)
[v22.2/cluster-setup-troubleshooting.md](https://deploy-preview-15466--cockroachdb-docs.netlify.app/docs/v22.2/cluster-setup-troubleshooting.html)

[DOC-2956] Remove inaccurate memory-leak info

---

_includes/v22.2/sql/sql-defaults-cluster-settings-deprecation-notice.md
v22.2/alter-role.md
v22.2/cluster-settings.md
v22.2/cost-based-optimizer.md
v22.2/data-domiciling.md
v22.2/date.md
v22.2/hash-sharded-indexes.md
v22.2/indexes.md
v22.2/int.md
v22.2/interval.md
v22.2/node-shutdown.md
v22.2/online-schema-changes.md
v22.2/placement-restricted.md
v22.2/restore.md
v22.2/schema-design-table.md
v22.2/serial.md
v22.2/set-cluster-setting.md
v22.2/timestamp.md
v22.2/transactions.md

Fixes DOC-4754
- Add a `sql.defaults.*` notice as an include
- Add that include to all the places in the docs where `sql.defaults.*`
is mentioned
- NB. We did *not* change all uses of `SET CLUSTER SETTING
sql.defaults.*` to use `ALTER ROLE ALL` for the following reasons:
- Making a docs change of that scope and ensuring we don't break the
pages in question would require a large amount of manual QA
- The use of `ALTER ROLE` is merely encouraged (the old settings are
not yet officially _deprecated_), and the SQL client prints a
message to the user. So that amount of work is not strictly required
yet.

Steer users away from sql.defaults.* settings

---

_includes/head.html
_includes/releases/v22.2/v22.2.0-alpha.1.md
v1.1/known-limitations.md

During one of the most recent Lumar web crawls, we were given several errors related to a nested file called `css/css/.../css/customstyles.css`, which caused a sharp rise in 404s. This PR should fix that.
Additionally, this fixes 404s in v1.1/known-limitations and in the v22.2.0-alpha.1 release notes.

 Various 404 fixes to docs

---

_includes/sidebar-data-cockroachcloud.json
cockroachcloud/network-authorization.md
cockroachcloud/private-clusters.md
cockroachcloud/security-overview.md

[DOC-4822]
Describe private clusters for CockroachDB Dedicated
Reviewers: Please leave feedback using Github directly, rather than ReviewBoard.
[cockroachcloud/private-clusters.md](https://deploy-preview-15342--cockroachdb-docs.netlify.app/docs/cockroachcloud/private-clusters.html)
[cockroachcloud/network-authorization.md](https://deploy-preview-15342--cockroachdb-docs.netlify.app/docs/cockroachcloud/network-authorization.html)
[cockroachcloud/security-overview.md](https://deploy-preview-15342--cockroachdb-docs.netlify.app/docs/cockroachcloud/security-overview.html)

[DOC-4822] Docs for private clusters

---

_includes/v22.2/cdc/privilege-model.md
_includes/v22.2/sql/privileges.md
v22.2/changefeed-for.md
v22.2/changefeed-sinks.md
v22.2/create-changefeed.md

Fixes [DOC-4731](https://cockroachlabs.atlassian.net/browse/DOC-4731), [DOC-5658](https://cockroachlabs.atlassian.net/browse/DOC-5658)
Added docs for the newer changefeed privilege model. This includes both Enterprise and Core changefeeds.

Added docs for the granular CHANGEFEED privilege model

---

_redirects

Navigating directly to https://www.cockroachlabs.com/docs/advisories/ and https://www.cockroachlabs.com/docs/releases/ doesn't expand the sidebar properly. This should resolve that.

Restore advisories and releases redirects

---

_includes/v22.2/metric-names.md

Addresses: DOC-5442
- Added new `storage.keys.range-key-set.count` metric to `metric-names.md`
Note:
- Assuming this is not avail for Serverless given nature of metric. Pls correct if not the case (as I would need to also add to `metric-names-serverless.md`)
Staging:
- [metric-names.md](https://deploy-preview-15428--cockroachdb-docs.netlify.app/docs/v22.2/ui-custom-chart-debug-page#available-metrics)

DOC-5442 new range-key-set metric

---

_includes/v22.2/metric-names.md

Addresses: DOC-5237
- Added 4 new metrics to `metric-names.md`: `rangekeybytes`, `rangekeycount`, `rangevalbytes`, and `rangevalcount`.
Question:
- Assuming these are not for Serverless also, or I'd need to also update `metric-names-serverless.md`.
Staging:
[metric-names.md](https://deploy-preview-15431--cockroachdb-docs.netlify.app/docs/v22.2/ui-custom-chart-debug-page#available-metrics)

DOC-5237 add 4 mvcc range metrics

---

v22.2/cost-based-optimizer.md

Clarified what makes a column "non-default", as per this [comment](https://github.com/cockroachdb/docs/pull/15338#issuecomment-1298903765).

clarify meaning of non-default column

---

v22.2/changefeed-sinks.md
v22.2/use-cloud-storage-for-bulk-operations.md

Fixes [DOC-4829](https://cockroachlabs.atlassian.net/browse/DOC-4829), [DOC-4791](https://cockroachlabs.atlassian.net/browse/DOC-4791), [DOC-5156](https://cockroachlabs.atlassian.net/browse/DOC-5156), [DOC-4802](https://cockroachlabs.atlassian.net/browse/DOC-4802), [DOC-5102](https://cockroachlabs.atlassian.net/browse/DOC-5102), [DOC-3690](https://cockroachlabs.atlassian.net/browse/DOC-3690), [DOC-4555](https://cockroachlabs.atlassian.net/browse/DOC-4555)
Added docs for assume role auth to GCP resources that includes cloud storage bulk & changefeeds and Pub/Sub for changefeeds.
This follows a similar pattern to the AWS version. Procedural steps through the setup for the service accounts with the nuances of GCP covered.
Docs PRs to follow include assume role work relating to workload …

Added docs for GCP assume role authentication

---

v22.2/ui-replication-dashboard.md

Addresses: DOC-3627
- Changed description of `Circuit Breaker Tripped Events` DB Console graph tooltip to reflect that metric is now a rate per second.
- The image did not need to be updated.
Staging:
- [v22.2/ui-replication-dashboard.md](https://deploy-preview-15439--cockroachdb-docs.netlify.app/docs/v22.2/ui-replication-dashboard#circuit-breaker-tripped-events)

DOC-3627 circuit breaker tripped events as rate

---

jekyll-algolia-dev/lib/jekyll/algolia/indexer.rb

This should enable our docs on not visible indexes to surface when someone searches "invisible indexes".

add "invisible" and "not visible" as synonyms

---

v21.2/monitor-cockroachdb-with-prometheus.md
v22.1/monitor-cockroachdb-with-prometheus.md
v22.2/monitor-cockroachdb-with-prometheus.md

Addresses: DOC-6020
- Engineering changed the name of an upstream resource from `replicas.json` to `replication.json`. This docs PR to update the docs to use the new name.
- Upstream rename was introduced for CRDB v21.2, so sending this change back that far.
Staging:
[monitor-cockroachdb-with-prometheus.md](https://deploy-preview-15460--cockroachdb-docs.netlify.app/docs/stable/monitor-cockroachdb-with-prometheus.html#step-5-visualize-metrics-in-grafana)

DOC-6020 fix broken Grafana replication url

---

cockroachcloud/backups-page.md
cockroachcloud/frequently-asked-questions.md
cockroachcloud/run-bulk-operations.md

In the middle of reviewing Ashley's work on CC backup types, I noticed an error on the FAQ page around that implied full and incremental automated backups were available to both Serverless and Dedicated customers. This is not the case and this PR fixes that.

Correction to CC FAQ page on backups

---

.github/workflows/changed_files.yml
.github/workflows/vale.yml

- Any actions from the `actions` organization now use main
- Update all other actions to the latest available version

DOC-6142: Update to use the latest version of GitHub Actions

---

v21.2/changefeed-examples.md
v21.2/changefeed-for.md
v21.2/changefeed-sinks.md
v21.2/create-schedule-for-backup.md
v21.2/monitor-and-debug-changefeeds.md
v22.1/changefeed-examples.md
v22.1/changefeed-for.md
v22.1/changefeed-sinks.md
v22.1/create-schedule-for-backup.md
v22.1/monitor-and-debug-changefeeds.md
v22.2/changefeed-examples.md
v22.2/changefeed-for.md
v22.2/changefeed-sinks.md
v22.2/create-schedule-for-backup.md
v22.2/monitor-and-debug-changefeeds.md

Fixes DOC-5403 
Replaced beta and experimental labels with preview for the new GTM phases. Changed all features in the DR & CDC docs that had references to the previous labels.

Replaced beta/experimental for preview in CDC & DR docs

---

_includes/v22.1/backups/show-backup-replace-diagram.html
_includes/v22.2/backups/show-backup-replace-diagram.html
v22.1/show-backup.md
v22.2/show-backup.md

Fixes DOC-3010
Replaced the remote include for the show backup SQL diagrams for 22.1 & 22.2 since the diagram pulling from the `cockroach` repo exposes some parts of the show backup SQL that are not intended for users. Added a local include instead with the intention of figuring out how to resolve the misalignment between what's in the `cockroach` SQL.y file and what should be user facing.

Added replacement `show backup` diagram as local

---

v22.2/cockroach-debug-zip.md

Addresses: DOC-4804, DOC-5728
- Added `--redact` flag to `cockroach debug zip` doc
- Noted that `--redact-logs` flag is deprecated, and will be interpreted as `--redact` moving forward.
- Updated `--redact-logs` example to `--redact`
Note:
- Not attempting to document what is redacted at present, as conversation (linked from comment in DOC-4804) is still ongoing. Let's use this PR to doc new `--redact` flag, and create a new PR for "what specifically is redacted when using `--redact`" when we have that information.  Cursorily,  it looks like I could just document the columns defined as `NonSensitiveColumns` in `pkg/cli/zip_table_registry.go`: presenting a collected table of "columns included per table with `--redact`" or similar. Happy also to wait for linked conversation > linked …

DOC-4804 redact flag 22.2

---

v21.2/local-testing.md
v22.1/local-testing.md
v22.2/local-testing.md

Fixes DOC-6160
NB. Applied to v21.2, v22.1, v22.2

Bump GC settings in local app testing instructions

---

v22.2/migrate-to-multiregion-sql.md

- Update note at top of 'Migrate to Multi-Region SQL' to direct users who are already using Multiregion SQL to the page 'Scale to multiple regions', where they can learn how to go from 1 to n regions.
- This PR was prompted by an internal user report that searching for "cockroachdb migrate from single region to multi-region" in Google was giving them the 'Migrate to Multi-region SQL' page

Add links from multi-region migration docs

---

v22.2/node-shutdown.md

[DOC-4750]
Relates to https://github.com/cockroachdb/cockroach/commit/3ce0fd5483a6bf3d4a5102da9cf9775904f5c572#diff-0ef17f0a19fa72bb8e62ee9059086c15959d49920b702da3f8d1aa2659cc225eR90
[v22.2/node-shutdown.md](https://deploy-preview-15615--cockroachdb-docs.netlify.app/docs/v22.2/node-shutdown.html)

[DOC-4750] Document kv.allocator.recovery_store_selector cluster setting

---

v22.2/cockroach-node.md
v22.2/node-shutdown.md

Addresses: DOC-2388
- Added notice to `cockroach node drain --drain-wait` reference entry on `cockroach-node.md`, and to the "Drain timeout" section on `node-shutdown.md` advising that CRDB v22.2 now increases log verbosity if a lease transfer stall is detected during a normal graceful drain. Let me know if you'd like this data elsewhere (instead | in addition).
Question:
- There were some references to internal variable tracking to toggle this feature in the code. Just confirming that this is not explicitly-toggle-able by the end user: only an automatic internal toggle. Thanks!
Staging:
- [node-shutdown.md](https://deploy-preview-15406--cockroachdb-docs.netlify.app/docs/dev/cockroach-node.html#general)
- [cockroach-node.md](https://deploy-preview-15406--cockroachdb-docs.netlify.app/docs/d …

DOC-2388 verbose log lease transfer stall

---

v21.2/show-range-for-row.md
v22.1/show-range-for-row.md
v22.2/show-range-for-row.md

Addresses: DOC-5577
- Updated `v21.2`, `v22.1`, and `v22.2` versions of `SHOW RANGE FOR ROW` reference page to use new `Preview` language include.
Staging:
[v22.2/show-range-for-row.md](https://deploy-preview-15610--cockroachdb-docs.netlify.app/docs/dev/show-range-for-row.html)

DOC-5577 preview range for row

---

v21.2/experimental-audit.md
v21.2/logging-use-cases.md
v21.2/sql-audit-logging.md
v22.1/experimental-audit.md
v22.1/logging-use-cases.md
v22.1/sql-audit-logging.md
v22.2/experimental-audit.md
v22.2/logging-use-cases.md
v22.2/sql-audit-logging.md

Addresses: DOC-5579
- Updated `v21.2`, `v22.1`, and `v22.2` versions of EXPERIMENTAL_AUDIT reference page to use new `Preview` language include.
Note:
- Assuming that closely-related `SENSITIVE_ACCESS` log channel is also [in need of this change](https://www.cockroachlabs.com/docs/stable/logging-use-cases.html#sensitive_access), so making it here (no explicit ticket for this log channel to D O C - 3 7 5 8, so using this ticket to accomplish.)
Staging:
- [experimental-audit.md](https://deploy-preview-15611--cockroachdb-docs.netlify.app/docs/dev/experimental-audit.html)
- [logging-use-cases.md](https://deploy-preview-15611--cockroachdb-docs.netlify.app/docs/dev/logging-use-cases.html#sensitive_access)
- [sql-audit-logging.md](https://deploy-preview-15611--cockroachdb-docs.netlify.app/docs/de …

DOC-5579 preview experimental audit

---

releases/index.md
v22.2/upgrade-cockroach-version.md

[DOC-5483]
Relates to https://github.com/cockroachdb/cockroach/pull/86345
[releases/index.md](https://deploy-preview-15666--cockroachdb-docs.netlify.app/docs/releases/index.html)
[v22.2/upgrade-cockroach-version.md](https://deploy-preview-15666--cockroachdb-docs.netlify.app/docs/v22.2/upgrade-cockroach-version.html)

[DOC-5483] Document new limitation when upgrading to an alpha version or manual build

---

_includes/v22.2/backups/control-schedule-privileges.md
v22.2/drop-schedules.md
v22.2/pause-schedules.md
v22.2/resume-schedules.md
v22.2/show-schedules.md

Fixes DOC-5616
Adjusted the privileges section for pause, drop, resume, show schedule statements so that it lists owners of scheduled backups can use these statements to control schedules.

Added docs on changes 22.2 to control schedule privileges

---

v21.2/node-shutdown.md
v22.1/node-shutdown.md
v22.2/node-shutdown.md

[DOC-3269]
[v22.2/node-shutdown.md](https://deploy-preview-15678--cockroachdb-docs.netlify.app/docs/v22.2/node-shutdown.html)
[v22.1/node-shutdown.md](https://deploy-preview-15678--cockroachdb-docs.netlify.app/docs/v22.1/node-shutdown.html)
[v21.2/node-shutdown.md](https://deploy-preview-15678--cockroachdb-docs.netlify.app/docs/v21.2/node-shutdown.html)

[DOC-3269] Remove misleading section, add clarifying details about decommissioning with too few nodes

---

v22.2/install-cockroachdb-mac.md

[DOC-6237]
[v22.2/install-cockroachdb-mac.md](https://deploy-preview-15673--cockroachdb-docs.netlify.app/docs/v22.2/install-cockroachdb-mac.html)

[DOC-6237] Document workaround for GEOS library for macOS ARM

---

_includes/v22.2/sidebar-data/reference.json
v22.2/show-system-grants.md

Addresses: DOC-5513
- Added new reference page for `SHOW SYSTEM GRANTS`
- Added to **Reference > SQL Statements** sidebar nav
Staging
[show-system-grants.md](https://deploy-preview-15671--cockroachdb-docs.netlify.app/docs/dev/show-system-grants.html)

DOC-5513 show system grants

---

v22.2/create-database.md

Previously, it was using an h2 which was causing it not to nest properly under the *Example* section in the page TOC.
With this change, it's an h3 and does nest properly.

Properly indent secondary region in examples list

---

_includes/releases/v22.1/v22.1.0-alpha.1.md
v22.1/alter-range-relocate.md
v22.1/experimental-features.md
v22.2/alter-range-relocate.md
v22.2/experimental-features.md

In v22.* and greater, users should use `ALTER RANGE ... RELOCATE` to move leases and replicas.
Fixes DOC-5405
- Remove mention of `EXPERIMENTAL_RELOCATE` from 'Experimental Features' page
- Remove mention of `EXPERIMENTAL_RELOCATE` as an alternative from the `ALTER RANGE ... RELOCATE` page

Remove docs for deprecated `EXPERIMENTAL_RELOCATE`

---

css/components/_filtertabs.scss
v21.2/node-shutdown.md
v22.1/node-shutdown.md
v22.2/node-shutdown.md

Filtered content does not filter or display correctly when a section block is part of a list (I think I'm the only one who has tried this). In order to filter and display properly, the entire list can be formatted in HTML rather than Markdown. Example:
```
<ul>
<li>blah</li>
<li>blah</li>
<section class="filter-content" markdown="1" data-scope="filter">
<li>filtered blah</li>
</section>
<li>blah</li>
</ul>
```
To avoid inconsistent line spacing, the filtered section needs to display as `inline` rather than `block`. After testing on some existing docs, this CSS change doesn't appear to affect how other filtered content is displayed. I believe it only improves the situation described above. Let me know if I should add any explicit tests to this PR.

display filtered content inline

---

_includes/releases/testing-release-notice.md

This will update the logic so that the testing release notice is suppressed if a release date is passed in, to make the deploy previews appear closer to the final product after a major version release note is published.

Fix testing-release-notice.md

---

v21.2/performance.md
v22.1/performance.md
v22.2/performance.md

Fixes DOC-5815
Partially addresses DOC-5511
- Update performance overview page to:
- Clarify that the versions under discussion are v21.1 and v19.2
- Remove the misleading "p95 latency" metric from the chart on that page, which was confusing because it showed a higher value for the "better" result.  More docs are needed around this to explain the nuances (based on the convo in DOC-5511), but at least removing the misleading stuff for now
- Reviewed other pages in the performance benchmarking section and did not find anything else that mentions specific versions of CockroachDB

Update performance benchmarking docs for v22.2

---

_includes/v22.2/sql/unsupported-postgres-features.md
v22.2/data-types.md
v22.2/keywords-and-identifiers.md
v22.2/sql-feature-support.md
v22.2/sql-name-resolution.md

Fixes DOC-5814
Fixes DOC-2158
Informs closing of old issue DOC-299
- In a few cases, we have docs for workarounds to standard SQL features, so I added links
- There were a few things missing from the SQL feature support that were in e.g. the Data Types page, so I added them
- Also updated our PG compat page with the lack of foreign data wrappers
- Took the opportunity to add some linkage between keywords/identifiers and SQL name resolution docs that could be useful, since they are related

Update SQL Feature Support reference docs

---

_includes/v22.2/sql/privileges.md
v22.2/grant.md
v22.2/revoke.md
v22.2/set-cluster-setting.md
v22.2/show-default-privileges.md

Fixes DOC-4749
Fixes DOC-4597
- Add new Global privilege to list of privileges
- Add 'Grant global privileges on the entire cluster' example to `GRANT` docs
- Add 'Revoke global privileges on the entire cluster' example to `REVOKE` docs
- Update the required privileges in the `SET CLUSTER SETTING` docs
- Drive-by add `SHOW ROLES` link to the `SHOW DEFAULT PRIVILEGES` doc

Add docs on global MODIFYCLUSTERSETTING privilege

---

_includes/v22.2/known-limitations/old-multi-col-stats.md
_includes/v22.2/known-limitations/single-col-stats-deletion.md
v22.2/cost-based-optimizer.md
v22.2/known-limitations.md
v22.2/user-defined-functions.md

Fixes DOC-5810
Fixes DOC-5811
* Add https://github.com/cockroachdb/cockroach/issues/90476
* Add https://github.com/cockroachdb/cockroach/issues/88149
* Add https://github.com/cockroachdb/cockroach/issues/87699
* Add https://github.com/cockroachdb/cockroach/issues/93049
* Add https://github.com/cockroachdb/cockroach/issues/87291
* Add https://github.com/cockroachdb/cockroach/issues/87289
* Add https://github.com/cockroachdb/cockroach/issues/90080
* Add https://github.com/cockroachdb/cockroach/issues/92961
* Add https://github.com/cockroachdb/cockroach/issues/93049
* Add https://github.com/cockroachdb/cockroach/issues/92570
* Remove https://github.com/cockroachdb/cockroach/issues/67407
* Delete `_includes/v22.2/known-limitations/old-multi-col-stats.md`
* Delete …

Add new known limitations for 22.2 / Remove resolved limitations

---

_includes/v22.2/ui/jobs.md
v22.1/show-jobs.md
v22.1/ui-jobs-page.md
v22.2/show-jobs.md

Fixes DOC-1113
There are a couple transient jobs status that were missing from the `SHOW JOBS` docs and the DB Console Jobs Page docs. This PR adds them: `pause-requested`, `cancel-requested`, and `revert failed`.
https://deploy-preview-15711--cockroachdb-docs.netlify.app/docs/stable/show-jobs.html#job-status
https://deploy-preview-15711--cockroachdb-docs.netlify.app/docs/stable/ui-jobs-page.html

Updated missing jobs status fields on `show jobs` and DB console pages

---

_includes/v22.2/sql/role-options.md
v22.2/alter-role.md
v22.2/alter-user.md
v22.2/create-role.md

Addresses: DOC-6228
- Removed `### Role options` header from include, and ensured it was consistently present in including parent files, thereby removing dupe header on `create-user.md`( [live](https://www.cockroachlabs.com/docs/dev/create-user.html#role-options) | [staging](https://deploy-preview-15669--cockroachdb-docs.netlify.app/docs/dev/create-user.html#role-options) )
- Ensured parent page anchor targets to `#role-options` continue to work as intended.
Staging
[alter-user.md](https://deploy-preview-15669--cockroachdb-docs.netlify.app/docs/dev/alter-user.html#role-options) | [create-role.md](https://deploy-preview-15669--cockroachdb-docs.netlify.app/docs/stable/create-role.html#role-options) | [alter-role.md](https://deploy-preview-15669--cockroachdb-docs.netlify.app/docs/stable/alter …

DOC-6228 fix double role options header

---

_includes/v22.2/known-limitations/drop-owned-by-function-limitations.md
_includes/v22.2/known-limitations/drop-owned-by-role-limitations.md
_includes/v22.2/sidebar-data/reference.json
v22.2/drop-owned-by.md
v22.2/known-limitations.md
v22.2/sql-statements.md

DOC-4770
DOC-5465  Depends on system privileges.
Blocks https://github.com/cockroachdb/docs/pull/15298

Add DROP OWNED BY

---

cockroachcloud/migrations-page.md
v22.2/aws-dms.md

- Remove preview label for AWS DMS (v22.2)
- Remove preview label for SCT in PostgreSQL (keeping for MySQL, Oracle, SQL Server)

remove DMS and SCT preview status

---

_includes/v22.2/metric-names.md

Addresses: DOC-4615
- Added `cluster.preserve-downgrade-option.last-updated` metric to `metric-names.md`.
Notes:
- We don't presently doc the banner at top of Overview (i.e. for "setting set for over 48h" banner), but plans exist to expand this post-GA. For now, just documenting the new metric.
- Assuming this is not avail for Serverless given nature of metric. Pls correct if not the case (as I would need to also add to `metric-names-serverless.md`).
Staging:
- [metric-names.md](https://deploy-preview-15427--cockroachdb-docs.netlify.app/docs/v22.2/ui-custom-chart-debug-page#available-metrics)

DOC-4615 add preserve-downgrade metric

---

_includes/v22.2/metric-names.md

Addresses: DOC-6000
- Renames two metrics (actually, DOCS didn't know these existed, so we're actually just adding them!)
Note:
- The renamed metrics also appear on the DB Console  > Metrics > TTL dashboard, but we don't currently document this dashboard. Plans exist!
Staging:
[metric-names.md](https://deploy-preview-15599--cockroachdb-docs.netlify.app/docs/stable/ui-custom-chart-debug-page.html#available-metrics)

DOC-6000 rename ttl metrics

---

_includes/v22.2/metric-names.md

Addresses: DOC-3710
- Adds 6 new metrics:
- `range.snapshots.rebalancing.rcvd-bytes`
- `range.snapshots.rebalancing.sent-bytes`
- `range.snapshots.recovery.rcvd-bytes`
- `range.snapshots.recovery.sent-bytes`
- `range.snapshots.unknown.rcvd-bytes`
- `range.snapshots.unknown.sent-bytes`
Staging:
- [metric-names.md](https://deploy-preview-15438--cockroachdb-docs.netlify.app/docs/v22.2/ui-custom-chart-debug-page#available-metrics)

DOC-3710 new range snapshot metrics

---

v21.2/architecture/admission-control.md
v22.1/admission-control.md
v22.2/admission-control.md

This threshold is incorrect, it's 32 (by default). See: 
https://github.com/cockroachdb/cockroach/blob/af9c69c17232cccfb19452956045da23ea18e5ad/pkg/util/admission/kv_slot_adjuster.go#L21-L29

Minor correction for "Runnable goroutines per CPU" threshold on Admission Control page

---

_includes/v22.1/metric-names.md
_includes/v22.2/metric-names.md

Addresses: DOC-6247, DOC-6248, DOC-6119
- Added new `replicas.leaders_invalid_lease` metric, for both v22.2 and v22.1 (which will also appear in future v23.1 per DOC-6119).
Staging
[v22.2/metric-names.md](https://deploy-preview-15785--cockroachdb-docs.netlify.app/docs/stable/ui-custom-chart-debug-page.html#available-metrics) | [v22.1/metric-names.md](https://deploy-preview-15785--cockroachdb-docs.netlify.app/docs/v22.1/ui-custom-chart-debug-page#available-metrics)

DOC-6247 invalid_lease metrics

---

v22.2/security-reference/authorization.md

Addresses: DOC-6264
- Added a central place for all new system privilege / RBAC content on the existing `v22.2/security-reference/authorization.md` page.
- Added support chart, incl which privs replace which roles, and which are net-new
- Did a first pass at introducing the concept of RBAC & inheritance
- Tried to de-obfuscate nearly-identically-named concepts with a generous peppering of `{{site.data.alerts.callout_info}}`
- Tried to describe things to users that haven't really been described to me. Did I guess right?
Research
- Some engineers call it [global](https://github.com/cockroachdb/docs/pull/15641#pullrequestreview-1190712479), some engineers call it [system](https://github.com/cockroachdb/docs/pull/15652#issuecomment-1330919151), some engineers use …

DOC-6264 central place for RBAC content

---

v22.2/jsonb.md
v22.2/scalar-expressions.md

DOC-4652
@otan I have updated the example output in `JSONB.md` to reflect the latest version. However, is it an issue that both column names are either `?column?` or `user_profile` (per the example)?

JSON subscripting operators and examples

---

v22.2/changefeed-sinks.md

Fixes DOC-3533
Users can now use a more limited Pub/Sub role in their G service account if the topics that the changefeed is writing to already exist. This PR includes a point to this effect.

Update the Pub/Sub roles for topic permissions

---

cockroachcloud/export-logs.md

Addresses: DOC-6309, DOC-6227
- Uses `jq` to simplify some steps for configuring log export, especially for GCP, especially especially for problematic step 5 (now 3).
- Dupes all of https://github.com/cockroachdb/docs/pull/15681 also, since those changes are small and used in this also.
Staging:
[export-logs.md](https://deploy-preview-15725--cockroachdb-docs.netlify.app/docs/cockroachcloud/export-logs.html)

DOC-6309 log export process improvements

---

_includes/v22.2/sql/select-for-update-overview.md

Fixes DOC-6257
- Add a paragraph to the "SELECT FOR UPDATE" overview that notes that the locking provided by SFU does not guarantee ordering in *all* cases and can result in serializable errors (40001)
- We also make sure the magic "retry error" strings appear for searchability: specifically, `40001` and `restart transaction`.
- h/t @kai-niemi for the language here, which is adapted from his work in an internal design document (hence no link, otherwise we would add it)

Update SELECT FOR UPDATE re: serialization errors

---

_includes/releases/v22.2/v22.2.0-alpha.1.md
_includes/v22.2/known-limitations/drop-owned-by-role-limitations.md
_includes/v22.2/sql/privileges.md
v22.2/drop-owned-by.md
v22.2/grant.md
v22.2/known-limitations.md
v22.2/revoke.md
v22.2/set-cluster-setting.md

Addresses: DOC-6405
- Standardized language around v22.2's RBAC feature: system-level privileges.
- This is just for Rich's PRs -- those organically his and those inherited from others (See https://github.com/cockroachdb/docs/pull/15826 for Kathryn's side of things). Essentially:
- `MODIFYCLUSTERSETTING`
- `GRANT`
- `REVOKE`
- `DROP OWNED BY`
- Standardized linking to new [central resource](https://www.cockroachlabs.com/docs/stable/security-reference/authorization.html#system-level-privileges).
Staging (selected):
[v22.2.md](https://deploy-preview-15824--cockroachdb-docs.netlify.app/docs/releases/v22.2.html) | [drop-owned-by.md](https://deploy-preview-15824--cockroachdb-docs.netlify.app/docs/stable/drop-owned-by.html#required-privileges) | …

DOC-6405 standardize sys priv language - Rich's PRs

---

v21.2/hash-sharded-indexes.md
v22.1/hash-sharded-indexes.md
v22.2/hash-sharded-indexes.md

DOC-3491
- Document `DROP INDEX ... CASCADE` for dropping `STORED` columns created by hash-sharded indexes
- Update v21.2-v22.2 docs (added some basic info on hash-sharded indexes that appeared to be missing in v21.2; not sure if fully correct)
It looks like the `CASCADE` requirement is only in v22.2, which means the guidance will differ in both v22.1 and v21.2. Let me know if this isn't correct.

DROP INDEX behavior in hash-sharded indexes

---

_layouts/default.html
css/customstyles.scss

Part of CRDB-18740
This CSS will allow us to use the `.anchored` class and add page anchors with the hoverable link button.

CRDB-18740: Add CSS to handle new table anchors for cluster settings

---

_includes/releases/v23.1/v23.1.0-alpha.1.md

Quick fix to 23.1 alpha.1 release notes for naming of Change Data Capture transformations (no longer named CDC expressions)

Correction on CDC expressions to transformations naming rn

---

v22.2/changefeed-messages.md
v22.2/monitor-and-debug-changefeeds.md

Fixes DOC-1286
Added docs to outline the new default retryable errors in changefeeds. Included descriptions of the kind of non-retryable error users can expect.
This shouldn't be merged until v22.2.1 is released. **NOTE** This is to be added to backward-incompatible changes in the v22.2.1 release notes. [DOC-4610](https://cockroachlabs.atlassian.net/browse/DOC-4610)
https://deploy-preview-15723--cockroachdb-docs.netlify.app/docs/dev/monitor-and-debug-changefeeds.html

Added docs for default retryable errors and details for non-retryable errors

---

releases/kubernetes-operator.md

Relates to https://github.com/cockroachdb/cockroach-operator/commit/54d6fcdd7eeec7147c1be026ffc9c5d8e10050e9
[releases/kubernetes-operator.md](https://deploy-preview-15875--cockroachdb-docs.netlify.app/docs/releases/kubernetes-operator.html)

Release notes for Operator 2.9.0

---

v21.1/upgrade-cockroach-version.md
v21.2/upgrade-cockroach-version.md
v22.1/upgrade-cockroach-version.md
v22.2/upgrade-cockroach-version.md

[DOC-5888] Followup
[DOC-88]
[v21.1/upgrade-cockroach-version.md](https://deploy-preview-15786--cockroachdb-docs.netlify.app/docs/v21.1/upgrade-cockroach-version.html)
[v21.2/upgrade-cockroach-version.md](https://deploy-preview-15786--cockroachdb-docs.netlify.app/docs/v21.2/upgrade-cockroach-version.html)
[v22.1/upgrade-cockroach-version.md](https://deploy-preview-15786--cockroachdb-docs.netlify.app/docs/v22.1/upgrade-cockroach-version.html)
[v22.2/upgrade-cockroach-version.md](https://deploy-preview-15786--cockroachdb-docs.netlify.app/docs/v22.2/upgrade-cockroach-version.html)

[DOC-5888][DOC-88] Followup: Improve docs about partially-decommissioned nodes during upgrade

---

cockroachcloud/migrate-from-serverless-to-dedicated.md
cockroachcloud/run-bulk-operations.md
cockroachcloud/serverless-faqs.md
v22.1/migrate-from-csv.md
v22.2/migrate-from-csv.md

DOC-2622
- Update serverless -> dedicated migration steps to use `EXPORT` rather than local storage
- Fix some misformatted links elsewhere

update serverless -> dedicated migration steps

---

_config_base.yml
_data/releases.csv
_includes/releases/v22.2/v22.2.2.md

Addresses: DOC-4611
- CRDB v22.2.2 release notes.
Staging
[v22.2.md](https://deploy-preview-15910--cockroachdb-docs.netlify.app/docs/releases/v22.2.html#v22-2-2)

DOC-4611 v22.2.2 release notes

---

v22.2/monitor-and-debug-changefeeds.md

Fixes DOC-6383
Added a short section to recommend changefeed metrics to track. Included links to Prometheus setup for CockroachDB and stronger recommendations to set this up for tracking changefeed retryable and non-retryable errors.
https://deploy-preview-15912--cockroachdb-docs.netlify.app/docs/stable/monitor-and-debug-changefeeds.html#recommended-changefeed-metrics

Recommended metrics to track for changefeeds

---

v22.1/monitor-cockroachdb-with-prometheus.md
v22.2/monitor-cockroachdb-with-prometheus.md

Addresses: DOC-6399
- Added an example `receivers` configuration for `alertmanager.yml`
- Added link to Alertmanager rules reference material from final sub step to step 4.
- Sent back to v22.1 as well.
Thanks for the great idea Kathryn!
Staging
[monitor-cockroachdb-with-prometheus.md](https://deploy-preview-15937--cockroachdb-docs.netlify.app/docs/stable/monitor-cockroachdb-with-prometheus.html#step-4-send-notifications-with-alertmanager)

DOC-6399 improve alertmanager steps

---

_data/releases.csv
_includes/releases/release-downloads-docker-image.md
releases/index.md
v22.2/install-cockroachdb-linux.md

This PR renames Linux and MacOS ARM release tarballs.
`linux-3.7.10-gnu-aarch64` -> `linux-arm64`
`darwin-11.0-aarch64` -> `darwin-11.0-arm64`
Additionally, I removed MacOS ARM64 from beta 4.

Rename aarch64 to arm64

---

v19.1/interval.md
v19.2/interval.md
v2.1/interval.md
v20.1/interval.md
v20.2/interval.md
v21.1/interval.md
v21.2/interval.md
v22.1/interval.md
v22.2/interval.md

Previous versions described the Interval::Float cast as producing picoseconds.
Since v2.1.0 (SHA f0dd1dc2d2500155c8b36330ae3d6932c13c1027), this has actually been in seconds
(Updated in 2018, SHA 01de891d9149f007cf439398e62e75cb3a18ecfd, by knz).

Correct error in description of Interval casting.

---

vale/Vocab/CockroachDB/accept.txt

The `accept.txt` file is case-sensitive.

Fix Vale errors

---

_includes/v22.2/sidebar-data/deploy.json

https://cockroachlabs.atlassian.net/browse/DOC-6513
The serverless pricing and RU info pages got removed from the nav in v22.2. This PR adds them back in.

Add lost serverless pages back to nav

---

_config_cockroachdb.yml

Dedicated on 22.2.2 and serverless on 22.1.12
(Some serverless clusters are on 22.2 now but rollout will be completed on Jan 18)

Cloud version update

---

v22.2/restore.md

Fixes DOC-5503
Add a reference that when a cluster is upgrading and in a mixed-version state, a full-cluster restore will fail.

Added note that mixed-version cluster states cause cluster restore fail

---

v22.2/show-grants.md

Addresses: DOC-5514
- Added notice of support for `EXTERNAL CONNECTION` grant target to `SHOW GRANTS`, with two examples.
Question:
- Command output returns the following columns: ` name | grantee | privilege | grantable` which differs in 3/4 of these headers from the existing `SHOW GRANTS ON X` output for other grant targets, as listed in [this table](https://deploy-preview-15683--cockroachdb-docs.netlify.app/docs/dev/show-grants.html#privilege-grants). I've listed verbatim output `name` here, retained existing `privilege_type` over this PR's `privilege` and retained existing `is_grantable` over this PR's `grantable`. But probably we need a CRDB issue to match the latter two to existing, and update our `name` to `connection_name` or similar. What do you think?
Staging:
- …

DOC-5514 show grants external connection

---

cockroachcloud/cloud-org-sso.md
cockroachcloud/configure-cloud-org-sso.md

Cloud Org SSO is no longer in preview, this came in as a one-off request to remove the preview flag ASAP as the feature is being opened up on production.

remove preview flag from cloud org sso stuff

---

_includes/v22.2/sidebar-data/manage.json
cockroachcloud/export-metrics.md
v22.2/third-party-monitoring-tools.md

Addresses: DOC-4727
- Added new procedure for enabling, monitoring, and disabling metrics export from CRDB dedicated to: Datadog and AWS CloudWatch.
- Updated third-party metrics integration page with new options, and clarified that existing procedures apply to Self-Hosted only.
- Similar approach overall to [log export](https://www.cockroachlabs.com/docs/cockroachcloud/export-logs.html), with some steps verbatim.
Questions
- Are there any limitations, FAQ items, or further troubleshooting you'd like to be sure we share with the user?
- Are GCP-backed dedicated clusters also constrained by a specific creation date to use this feature? GCP-backed dedicated clusters can export metrics to AWS CloudWatch, right?
Staging
- [export-metrics.md](https://deploy-preview-15932--cockroachdb-docs.netli …

DOC-4727 dedicated metrics export

---

advisories/c20230118.md

Addresses: DOC-6643
- Fixes links to non-CC content that 404d. These links were not caught as broken by the builder, as https://github.com/cockroachdb/docs/pull/16016 passed all checks for build & merge - spawning separate investigation in D O C - 6 6 4 4 to troubleshoot.
Staging
WIP

DOC-6643 fix links missed by builder

---

v22.2/error-handling-and-troubleshooting.md
v22.2/security-reference/scram-authentication.md

Fixes DOC-6319
- Update the 'Troubleshoot Common Problems' page with instructions for downgrading from SCRAM auth to bcrypt password hashing. While there, also:
- Break out the SCRAM high CPU content into sections for easier scanning and linking
- Add some links to the 'Connection Pooling' and 'Transactions' pages where those things are mentioned
- Add the detail that if the connection pooling software is configured to close idle connections eagerly, this can also contribute to high CPU
- Update the 'SASL/SCRAM-SHA-256 Secure Password-based Authentication' page with specific upgrade instructions showing the SQL statements to type in

Document SCRAM authentication upgrade/downgrade

---

v22.1/recommended-production-settings.md
v22.2/recommended-production-settings.md

Address DOC-2213, DOC-688
- Added description and links for production purposes
Q's
- Where should the backup section go on the page? Is there a specific order the headings are following for the existing content on the page?
- How detailed should the section be? The page already looks to have a lot of information and the current sections vary in lengths
Staging:
- [Production Settings](https://deploy-preview-15707--cockroachdb-docs.netlify.app/docs/stable/recommended-production-settings.html#backup-and-restore)

DOC-2213 added backup descr for prod checklist

---

cockroachcloud/export-logs.md
cockroachcloud/export-metrics.md

Addresses: DOC-6674
- Recapitalizes two instances of manual lowercase product name for Dedicated in two locations that couldn't make use of liquid tags (because front matter), now that Marketing has recanted and Gemma has merged https://github.com/cockroachdb/docs/pull/16065.

DOC-6674 recapitalize product names - obs

---

v22.1/security-reference/authentication.md
v22.2/security-reference/authentication.md

Addresses: DOC-5383
- Added whitespace to avoid render-by-zero.
- Affects both v22.2 and v22.1
Staging
- [v22.2/security-reference/authentication.html](https://deploy-preview-16120--cockroachdb-docs.netlify.app/docs/stable/security-reference/authentication.html#the-unstated-unchangeable-root-access-rule)
- [v22.1/security-reference/authentication.html](https://deploy-preview-16120--cockroachdb-docs.netlify.app/docs/v22.1/security-reference/authentication#the-unstated-unchangeable-root-access-rule)

DOC-5383 fix auth code broken formatting

---

v22.2/set-locality.md

Addresses DOC-5622:
- Code blocks in Step 7 can now be copied
Questions:
- I tried fixing the sub-steps in Step 7 but couldn't get it to change. Currently they are all 'step a.' when the steps should be a, b, c. 
Preview
- [SET LOCALITY](https://deploy-preview-16115--cockroachdb-docs.netlify.app/docs/stable/set-locality.html#example)

[DOC-5622] fixed copy buttons for step 7

---

StyleGuide.md
v22.2/cluster-settings.md
v22.2/file-an-issue.md
v22.2/foreign-key.md
v22.2/recommended-production-settings.md
v22.2/srid-4326.md

[DOC-2070](https://cockroachlabs.atlassian.net/browse/DOC-2070)
- Removed "please" specifically for technical instructions.
- Updated style guide. I'm not sure if this wording is clear enough.

remove "please" from instructions

---

_includes/v21.2/ui/statistics.md
_includes/v22.1/ui/statistics.md
_includes/v22.2/ui/statistics.md

Statement and Transactions pages incorrectly list 10mil rows as default limit for persisted stats, 1 mil is correct.
https://cockroachlabs.atlassian.net/browse/DOC-5893

Statement and Transactions pages correction

---

cockroachcloud/backups-page.md

https://cockroachlabs.atlassian.net/browse/DOC-6022
Customer requested info on where their multi-region cluster's backups would be stored. Added clarification that they are stored in the primary region.

Clarify where backups are stored

---

_includes/v21.2/prod-deployment/healthy-disk-ops-in-progress.md
_includes/v22.1/prod-deployment/healthy-disk-ops-in-progress.md
_includes/v22.2/prod-deployment/healthy-disk-ops-in-progress.md

Addresses: DOC-6510
- Corrected include that referred to disk ops counter in milliseconds, as it is a raw numeric increment.
- The modified include is included in two places: verified that this change is correct to make for both.
Thanks Mark for the great feedback!!
Staging
[ui-hardware-dashboard.html](https://deploy-preview-16116--cockroachdb-docs.netlify.app/docs/stable/ui-hardware-dashboard.html#disk-ops-in-progress)

DOC-6510 correct disk ops include values

---

v21.2/update.md
v22.1/update.md
v22.2/update.md

Fixes DOC-253
According to the issue filer the MySQL function is not really related to how RETURNING works, so could cause confusion.

Remove unnecessary ref to MySQL function

---

_includes/v22.2/sql/unsupported-postgres-features.md
v22.2/sql-faqs.md
v22.2/trigram-indexes.md

Fixes DOC-6318
- Update the SQL FAQ entry on full text search to mention that we do have trigram indexes, which may meet some users' needs, and link to stuff about trigram indexes
- Update the list of unsupported Postgres features on the PG compat page to mention that even though we don't have full text search, we do have trigram indexes now, which could help
- Add a link from the official trigram indexes doc to the also very informative trigram indexes blog post (which also has a video showing them off)

Update SQL FAQ, PG compat doc re: trigram indexes

---

_includes/v22.2/misc/note-egress-perimeter-cdc-backup.md
v22.2/backup-and-restore-overview.md
v22.2/changefeed-sinks.md
v22.2/use-cloud-storage-for-bulk-operations.md

Fixes DOC-6226
Adds a note that reference Egress Perimeter Controls to the Changefeed Sink, Backup/Restore Overview/storage page, and Cloud Storage page.

Add reference to Egress Perimeter Controls in CDC/Backup docs

---

v22.1/create-and-configure-changefeeds.md
v22.1/create-changefeed.md
v22.2/create-and-configure-changefeeds.md
v22.2/create-changefeed.md

Fixes DOC-5180
Brief update to mention that enterprise changefeeds created without a sink and the format option will create a core-style changefeed. 
Currently, we only mention this in an example on the CDC Transformations page https://www.cockroachlabs.com/docs/v22.2/cdc-transformations#view-recent-changes-to-a-row. 
This PR adds to the `CREATE CHANGEFEED` page and the Create and Configure Changefeed overview page. 
(A couple of small tidy-up edits too.)
https://deploy-preview-16025--cockroachdb-docs.netlify.app/docs/stable/create-and-configure-changefeeds.html#create

Include reference to enterprise changefeeds created without a sink

---

cockroachcloud/learn-cockroachdb-sql.md
v22.1/learn-cockroachdb-sql.md
v22.2/learn-cockroachdb-sql.md

Fixes DOC-6493
- Update Cloud version of 'Learn CockroachDB SQL' to address various issues with the page that were leading to low CSAT, including:
- Remove Instruqt tutorial that had various issues (very slow load times, sometimes "crashes" from user POV, etc., strange UX of being punted to external platform with different button location, etc.)
- Fix logic errors in order of presentation of SQL commands that would lead to errors when typed into the SQL client in order
- Add 'See Also' section at bottom of page with links to relevant SQL statements, FAQs, app tutorials, etc. so users have a "next place" to go
- Add note to page making clearer that this page is for Cloud users, with link to Self-hosted version of these instructions
- Update Self-hosted version of the …

Update 'Learn CockroachDB SQL' (Cloud version)

---

_includes/v22.1/metric-names.md
_includes/v22.1/sidebar-data/reference.json
_includes/v22.2/metric-names.md
_includes/v22.2/sidebar-data/reference.json
cockroachcloud/monitoring-page.md
v22.1/cockroach-debug-zip.md
v22.1/common-issues-to-monitor.md
v22.1/datadog.md
v22.1/metrics.md
v22.1/monitor-cockroachdb-kubernetes.md
v22.1/monitor-cockroachdb-with-prometheus.md
v22.1/monitoring-and-alerting.md
v22.1/third-party-monitoring-tools.md
v22.2/cockroach-debug-zip.md
v22.2/common-issues-to-monitor.md
v22.2/datadog.md
v22.2/metrics.md
v22.2/monitor-cockroachdb-kubernetes.md
v22.2/monitor-cockroachdb-with-prometheus.md
v22.2/monitoring-and-alerting.md
v22.2/third-party-monitoring-tools.md

Addresses: DOC-6611
- Added new `metrics.md` page, which includes current `metric-names.md` and `metric-names-serverless.md` includes.
- Updated `reference` left-nav to include `metrics.md` page at top-level underneath it.
- Updated all links site-wide that previously pointed to `ui-custom-chart-debug-page.html#available-metrics` to point instead to `metrics.html` (there were only a few).
- Added new **See Also** links to new metrics page where it seemed to make sense.
- Because we modify one cloud page ( `cockroachcloud/monitoring-page.md`), and because `{{site.current_cloud_version}}` is still at v22.1, I have to perform all of this to v22.1 also.
Staging
- [v22.2/metrics.md](https://deploy-preview-16136--cockroachdb-docs.netlify.app/docs/stable/metrics.html)
- …

DOC-6611 metrics reference page

---

_includes/corestyle.scss
_includes/sidebar.js.html

We added an SEO tweak to ensure that our sidebar produced full URLs
in our sidebar to limit the scope to which Google could crawl URLs on
our docs site. The problem is we're now using absolute URLs instead of
relative URLs in each of our Netlify builds, which are adding a hamper
on the speed of our builds. This PR should fix that.

Performance fix on the sidebar

---

v22.2/query-behavior-troubleshooting.md
v23.1/query-behavior-troubleshooting.md

Corrected some things that weren't caught in review of [#15916](https://github.com/cockroachdb/docs/pull/15074):
- Link to the slow query log had been removed.
- There was a redundant sentence.

corrections to slow query troubleshooting doc

---

_config_base.yml
_includes/corestyle.scss
_includes/head.html
_includes/sidebar.js.html
sitemap.xml

We removed all references to "site.url" across our docs to keep build previews consistent with our main site.

Additional perf fixes

---

v22.2/build-a-csharp-app-with-cockroachdb.md

Addresses: DOC-5969
- Removes alert warning of .NET Npgsql driver validation difference, given that there is no longer such a difference.
- Updates two instances of code sample to use updated ssl params.
- PR to upstream: https://github.com/cockroachlabs/hello-world-csharp/pull/4
Staging
[build-a-csharp-app-with-cockroachdb.md](https://deploy-preview-16101--cockroachdb-docs.netlify.app/docs/stable/build-a-csharp-app-with-cockroachdb.html) (obviously, upstream include changes are not reflected in docs staging, until upstream PR is merged)

DOC-5969 update sslmode guidance npgsql

---

v23.1/build-a-csharp-app-with-cockroachdb.md

Addresses: DOC-5969
- Foreport of https://github.com/cockroachdb/docs/pull/16101 to v23.1 directory.
Staging
[build-a-csharp-app-with-cockroachdb.md](https://deploy-preview-16239--cockroachdb-docs.netlify.app/docs/stable/build-a-csharp-app-with-cockroachdb.html)

DOC-5969 foreport to v23.1

---

_config_base.yml
_data/releases.csv
_includes/releases/v22.2/v22.2.5.md

Release notes for v22.2.5
[releases/v22.2.md#v22-2-5](https://deploy-preview-16278--cockroachdb-docs.netlify.app/docs/releases/v22.2.html#v22-2-5)

Release notes for v22.2.5

---

advisories/a96029.md

Addresses: DOC-6865, DOC-6698
- Added guidance on using new `COCKROACH_ENABLE_HDR_HISTOGRAMS` environment variable to TA-96029.
- ~Will only merge once v22.2.4 goes live (likely next week).~
- UPDATE: v22.2.4 has been pulled. This PR is edited to direct users to v22.2.5 instead.
Staging
[a96029.md](https://deploy-preview-16238--cockroachdb-docs.netlify.app/docs/advisories/a96029#statement)

DOC-6865 TA-96029 add env var

---

v22.1/upgrade-cockroach-version.md
v22.2/upgrade-cockroach-version.md
v23.1/upgrade-cockroach-version.md

[DOC-6963]
[v22.1/upgrade-cockroach-version.md](https://deploy-preview-16283--cockroachdb-docs.netlify.app/docs/v22.1/upgrade-cockroach-version.html)
[v22.2/upgrade-cockroach-version.md](https://deploy-preview-16283--cockroachdb-docs.netlify.app/docs/v22.2/upgrade-cockroach-version.html)
[v23.1/upgrade-cockroach-version.md](https://deploy-preview-16283--cockroachdb-docs.netlify.app/docs/v23.1/upgrade-cockroach-version.html)

[DOC-6963] Add docs about rolling back a self-hosted upgrade

---

cockroachcloud/export-logs.md

Addresses: DOC-6919
- Clarified that the service account referenced in GCP steps is the CCloud service account - not a GCP service account.
- Tagged most references to `service account` under the GCP tab with `CockroachDB Cloud` to clarify.
- Added new FAQ item explicitly calling this out.
Staging
[export-logs.md](https://deploy-preview-16237--cockroachdb-docs.netlify.app/docs/cockroachcloud/export-logs.html)

DOC-6919 clarify ccloud service account

---

_includes/v21.2/misc/debug-subcommands.md
_includes/v21.2/sidebar-data/reference.json
_includes/v22.1/misc/debug-subcommands.md
_includes/v22.1/sidebar-data/reference.json
_includes/v22.2/misc/debug-subcommands.md
_includes/v22.2/sidebar-data/reference.json
v21.2/cockroach-commands.md
v21.2/cockroach-debug-tsdump.md
v22.1/cockroach-commands.md
v22.1/cockroach-debug-tsdump.md
v22.2/cockroach-commands.md
v22.2/cockroach-debug-tsdump.md
vale/Vocab/CockroachDB/accept.txt

Addresses: DOC-5444
- Added new reference page for `cockroach debug tsdump` and added to various commands list includes.
- Added to docs for v22.2, v22.1, and v21.2. All changes identical across versions.
Staging
[v22.2/cockroach-debug-tsdump.md](https://deploy-preview-15980--cockroachdb-docs.netlify.app/docs/stable/cockroach-debug-tsdump.html) | [v22.2/cockroach-commands.md](https://deploy-preview-15980--cockroachdb-docs.netlify.app/docs/stable/cockroach-commands.html#commands)

DOC-5444 debug tsdump

---

_includes/v23.1/misc/debug-subcommands.md
_includes/v23.1/sidebar-data/reference.json
v23.1/cockroach-commands.md
v23.1/cockroach-debug-tsdump.md

Addresses: DOC-7005 (v23.1 foreport of DOC-5444)
- Foreports DOC-5444 to v23.1 verbatim (no version-specific changes other than wholesale foreport)
Staging
[cockroach-debug-tsdump.md](https://deploy-preview-16323--cockroachdb-docs.netlify.app/docs/dev/cockroach-debug-tsdump.html)

DOC-7005 foreport debug tsdump to v23.1

---

cockroachcloud/export-metrics.md

Addresses: DOC-6988
- Switches GTM include from `preview-opt-in.md` to `preview.md`, removing "enroll" language.
Staging
[export-metrics.md](https://deploy-preview-16319--cockroachdb-docs.netlify.app/docs/cockroachcloud/export-metrics.html)

DOC-6988 metrics export GTM preview

---

_includes/feature-phases/limited-access.md
cockroachcloud/export-logs.md

Addresses: DOC-6987
- Created new "limited access" include, similar to existing "private preview" include.
- Directed log export docs to use this new "limited access" include.
Staging
[export-logs.md](https://deploy-preview-16318--cockroachdb-docs.netlify.app/docs/cockroachcloud/export-logs.html)

DOC-6987 log export GTM limited access

---

_includes/v22.1/known-limitations/schema-changes-within-transactions.md
_includes/v22.1/sql/dev-schema-change-limits.md
_includes/v22.2/known-limitations/schema-changes-within-transactions.md
_includes/v22.2/sql/dev-schema-change-limits.md
_includes/v23.1/known-limitations/schema-changes-within-transactions.md
_includes/v23.1/sql/dev-schema-change-limits.md
v22.1/liquibase.md
v22.1/online-schema-changes.md
v22.1/schema-design-indexes.md
v22.2/liquibase.md
v22.2/online-schema-changes.md
v22.2/schema-design-indexes.md
v23.1/liquibase.md
v23.1/online-schema-changes.md
v23.1/schema-design-indexes.md

This PR clarifies that CockroachDB doesn't support fully atomic multi-DDL statements within transactions, and that users should use single-statement transactions when executing schema changes.
It also removes the examples of failing multi-statement transactions.
Fixes DOC-6948.
Fixes DOC-6949.

Multi-DDL statements shouldn't be run in txns

---

_includes/cockroachcloud/migration/sct-self-hosted.md
_includes/v22.2/known-limitations/copy-syntax.md
_includes/v23.1/known-limitations/copy-syntax.md
cockroachcloud/migrations-page.md
v22.1/aws-dms.md
v22.2/aws-dms.md
v22.2/copy-from.md
v22.2/import-into.md
v22.2/import-performance-best-practices.md
v22.2/import.md
v22.2/migration-overview.md
v23.1/aws-dms.md
v23.1/copy-from.md
v23.1/import-into.md
v23.1/import-performance-best-practices.md
v23.1/import.md
v23.1/migration-overview.md

DOC-6723
DOC-6887
This is an interim update to get our migration docs up to date on the data ingestion options.
- Added deprecation notice to `IMPORT` docs (23.1 and 22.2, specifying "as of v23.1" in both).
- Updated & lightly restructured Migration Overview to recommend `COPY FROM`, `IMPORT INTO`, and AWS DMS with some considerations for each. (**Reviewers:** I'd like to enhance these considerations with more detail, if possible.)
- Lightly updated & restructured `COPY FROM` and `IMPORT INTO` reference docs for usability.
- Clarified that schema can be exported from SCT for use with self-hosted cluster.
- Added recommendation for "latest production release" on DMS docs while I'm here.

update IMPORT/COPY guidance

---

StyleGuide.md

Fixes DOC-1757
Added a different link to the imperative mood reference in the style guide. This webpage seems to give more actionable guidance on forming the imperative mood for those that might need additional resources here. 
Reviewer: alternative option https://www.grammarly.com/blog/imperative-verbs/

Docs fixit: Add more helpful imperative mood link

---

v22.1/cockroach-node.md
v22.2/cockroach-node.md
v23.1/cockroach-node.md

Addresses: DOC-267
- Adds clarity and context around `is_live` and `is_available` returned values from `cockroach node`.
Staging
WIP

DOC-267 clarify node status live avail

---

v23.1/row-level-ttl.md

Adds an example of using `ttl_expiration_expression` with a `DATE` column and explicitly setting the timezone.
Closes DOC-6918.

Add example of using dates in ttl expressions

---

cockroachcloud/export-metrics.md

Addresses: DOC-7102
- Corrects AWS step 6 to use standard permissions template from log export.
Staging
[export-metrics.md](https://deploy-preview-16396--cockroachdb-docs.netlify.app/docs/cockroachcloud/export-metrics.html)

DOC-7102 fix metrics export step 6

---

_includes/head.html

We were getting an error because the summary in one page had unescaped double quotes. This should fix that.

Fix structured content in page header

---

cockroachcloud/cmek-ops-aws.md

[DOC-7103] Remove mention of external ID from AWS CMEK docs
This is a temporary change and I'll prepare a revert as soon as it is merged.
[cockroachcloud/cmek-ops-aws.md](https://deploy-preview-16398--cockroachdb-docs.netlify.app/docs/cockroachcloud/cmek-ops-aws.html)

[DOC-7103] Remove mention of external ID from AWS CMEK docs

---

_config_base.yml
_data/releases.csv
_includes/releases/v23.1/v23.1.0-alpha.5.md

[DOC-7137] Release notes for v23.1.0-alpha.5
Ref: https://cockroachlabs.slack.com/archives/C04E562A58F/p1677692194695609
[releases/v23.1.md](https://deploy-preview-16422--cockroachdb-docs.netlify.app/docs/releases/v23.1.html#v23-1-0-alpha-5)

DOC-7137 Release notes for v23.1.0-alpha.5

---

v22.1/stream-a-changefeed-to-a-confluent-cloud-kafka-cluster.md
v22.2/stream-a-changefeed-to-a-confluent-cloud-kafka-cluster.md
v23.1/stream-a-changefeed-to-a-confluent-cloud-kafka-cluster.md

Fixes DOC-7146
Bug in the Confluent Cloud tutorial docs. The Confluent CLI version has updates to the flags that are used in the tutorial.
https://deploy-preview-16432--cockroachdb-docs.netlify.app/docs/stable/stream-a-changefeed-to-a-confluent-cloud-kafka-cluster.html#step-6-create-a-kafka-consumer

Update to Confluent CLI & flags in changefeed tutorial

---

Gemfile
_config_base.yml

Also add a locked-in version for the jekyll-sass-converter

Silence deprecation warnings for SASS

---

v22.2/show-backup.md
v23.1/known-limitations.md
v23.1/show-backup.md

Addresses DOC-3566:
- Users can now pass locality-aware backup URIs to SHOW BACKUP
- Users can not yet run SHOW BACKUP for locality aware backups created using the
incremental_location parameter
Preview:
- [22.2 Show a locality-aware backup](https://deploy-preview-16341--cockroachdb-docs.netlify.app/docs/stable/show-backup.html#show-a-locality-aware-backup)
- [23.1 Show a locality-aware backup](https://deploy-preview-16341--cockroachdb-docs.netlify.app/docs/dev/show-backup.html#show-a-locality-aware-backup)

[DOC-3566] added example for locality aware show backup

---

_includes/v23.1/metric-names.md

Addresses: DOC-6442 (but also net-new adds these metrics, no ticket for that either)
- Updated description for (added in the first place) two existing (new) metrics:
- `queue.gc.info.clearrangefailed`
- `queue.gc.info.clearrangesuccess`
Staging
[metrics.md](https://deploy-preview-16518--cockroachdb-docs.netlify.app/docs/stable/metrics.html)

DOC-6442 queue.gc.info.clearrange metrics

---

_includes/v22.1/sql/select-for-update-limitations.md
_includes/v22.2/sql/select-for-update-limitations.md
v22.1/architecture/transaction-layer.md
v22.1/known-limitations.md
v22.1/select-for-update.md
v22.2/architecture/transaction-layer.md
v22.2/known-limitations.md
v22.2/select-for-update.md

Followup to https://github.com/cockroachdb/docs/pull/16434 to backport that content to v22.1 and v22.2 (v21.2 is nearly out of support)
Addresses DOC-6276 and DOC-7124

SELECT FOR UPDATE uses unreplicated locks

---

_includes/v22.2/ui/statement-details.md
_includes/v23.1/ui/statement-details.md

Quick fix to the DB Console Statements Page Docs --> duplicate See Also section hidden in an include was causing issues on the sidebar TOC, and wasn't necessary.

Correction to duplicate See also Statements Page

---

v22.2/create-external-connection.md
v22.2/drop-external-connection.md
v23.1/create-external-connection.md
v23.1/drop-external-connection.md

Fixes DOC-5781
This is a small addition to the `DROP EXTERNAL CONNECTION` page to add a `GRANT` statement to match the `CREATE EXTERNAL CONNECTION` page.

Include grant statement for drop ext connection

---

_includes/v23.1/ui/index-details.md

Addresses: DOC-6692
- Adds new sentence to index details section on **Databases** page that appraises user of visibility into executed statement fingerprints which have used the selected index, and also that such visibility is limited to admin users only.
Staging
[v23.1/ui-databases-page](https://deploy-preview-16460--cockroachdb-docs.netlify.app/docs/v23.1/ui-databases-page#index-details)

DOC-6692 index stmt fingerprint admin only

---

_includes/v22.1/ui/ui-metrics-navigation.md
_includes/v22.2/ui/ui-metrics-navigation.md
_includes/v23.1/ui/ui-metrics-navigation.md

Addresses: DOC-6534 (and its two backports, unticketed)
- Added mention of new click-to-stick functionality on include that appears on all metrics dashbaords (incl ui-overview).
Staging
[v23.1/ui-overview-dashboard.md](https://deploy-preview-16517--cockroachdb-docs.netlify.app/docs/dev/ui-overview-dashboard.html#dashboard-navigation) | [v22.2/ui-overview-dashboard.md](https://deploy-preview-16517--cockroachdb-docs.netlify.app/docs/stable/ui-overview-dashboard.html#dashboard-navigation) | [v22.1/ui-overview-dashboard.md](https://deploy-preview-16517--cockroachdb-docs.netlify.app/docs/v22.1/ui-overview-dashboard.html#dashboard-navigation)

DOC-6534 click to stick

---

v23.1/cockroach-auth-session.md

Addresses: DOC-6211, DOC-6212
- Added one tiny sentence to the sole mention of `system.web_sessions` in the docs corpus to now advise of its GC tunability.
- Remainder of docs corpus does not mention / describe any of  `system.eventlog`, `system.rangelog`, or `system.web_sessions` in a manner where GC tunability would be a relevant topic.
- The cluster settings themselves (deprecated or renamed), are automatically reflected, for now, in an upstream include, accessible here: `docs/generated/settings/settings.html`, which is exposed to the end user as copy [here](https://deploy-preview-16535--cockroachdb-docs.netlify.app/docs/dev/cluster-settings.html).
Alternative
- Also OK if you think we don't need any docs changes at all.
Staging …

DOC-6211, DOC-6212 system log gc

---

v22.2/build-a-csharp-app-with-cockroachdb.md
v23.1/build-a-csharp-app-with-cockroachdb.md

Npgsql no longer in beta support level, and the Serverless parameters need updating.
Fixes CC-6542.

Removing beta label, update params for Serverless

---

cockroachcloud/export-metrics.md

Addresses: DOC-7210
- Introduced duality of metrics export endpoints: `metricexport/cloudwatch` and `metricexport/datadog`, replacing previous singular instance of `metricexport`.
- Updated `curl` examples per Jenn's super-helpful testing document && Jira comment -- thank you!!
Staging
[export-metrics.md](https://deploy-preview-16534--cockroachdb-docs.netlify.app/docs/cockroachcloud/export-metrics.html#the-metricexport-endpoint)

DOC-7210 metrics export endpoints

---

_includes/v23.1/metric-names.md

Addresses: DOC-6039
- Updates descriptions for 5 metrics.
- Adds a sixth.
- Thanks for updating metrics descriptions.
Staging
[metrics.md](https://deploy-preview-16587--cockroachdb-docs.netlify.app/docs/dev/metrics.html)

DOC-6039 update rebalancing metric descs

---

_includes/v22.2/metric-names.md
_includes/v23.1/metric-names.md

Addresses: DOC-5772
- Adds 14 new metrics in form: `storage.$LEVEL-level-{size,score}` of $LEVEL `0` through `6`.
- If you disagree with a metric's description, please change it here: [pkg/kv/kvserver/metrics.go](https://github.com/cockroachdb/cockroach/pull/88504/files#diff-13de2cd5fd804cc3efbfb6f5d16ca58d33e1a9e297461d018b82dd087e662876).
- EDIT: just noticed that you [backported](https://github.com/cockroachdb/cockroach/pull/88592) this. Docs had no idea. I've backported the docs change now too.
Staging
- [v23.1/metrics.md](https://deploy-preview-16584--cockroachdb-docs.netlify.app/docs/dev/metrics.html)
- [v22.2/metrics.md](https://deploy-preview-16584--cockroachdb-docs.netlify.app/docs/stable/metrics.html)

DOC-5772 storage level metrics

---

v22.2/ui-insights-page.md
v23.1/ui-insights-page.md

Addresses: DOC-6634, DOC-6679
- Adds notice to v23.1 and v22.2 versions of DB Console **Insights** page indicating that the "action button" to enact index change recommendations is only available to admins.
Staging
[v23.1/ui-insights-page.md](https://deploy-preview-16459--cockroachdb-docs.netlify.app/docs/dev/ui-insights-page.html#schema-insights-view) | [v22.2/ui-insights-page.md](https://deploy-preview-16459--cockroachdb-docs.netlify.app/docs/stable/ui-insights-page.html#schema-insights-view)

DOC-6634, DOC-6679 insights page apply button admin only

---

Makefile

We advise people to install htmltest via brew, and using go get/install to install htmltest is not the supported way in the htmltest docs.

[skip ci] Update Makefile

---

StyleGuide.md

Addresses: DOC-7358
- Added guidance on using tabsets, linking into them from without of them, synchronizing state across tabsets, etc.
Original PR: https://github.com/cockroachdb/docs/pull/14940
Staging
[StyleGuide.md](https://deploy-preview-16658--cockroachdb-docs.netlify.app/docs/StyleGuide.md)

DOC-7358 Add tabset guidance

---

v22.2/common-errors.md
v22.2/recommended-production-settings.md
v23.1/common-errors.md
v23.1/recommended-production-settings.md

[DOC-243] Add more context about --max-sql-memory and 'memory budget exceeded' errors
[v22.2/common-errors.md](https://deploy-preview-16475--cockroachdb-docs.netlify.app/docs/v22.2/common-errors.html)
[v22.2/recommended-production-settings.md](https://deploy-preview-16475--cockroachdb-docs.netlify.app/docs/v22.2/recommended-production-settings.html)
[v23.1/common-errors.md](https://deploy-preview-16475--cockroachdb-docs.netlify.app/docs/v23.1/common-errors.html)
[v23.1/recommended-production-settings.md](https://deploy-preview-16475--cockroachdb-docs.netlify.app/docs/v23.1/recommended-production-settings.html)

[DOC-243] Add more context about --max-sql-memory and 'memory budget exceeded' errors

---

_config_base.yml
_data/releases.yml
_includes/releases/v23.1/v23.1.0-alpha.8.md
_includes/releases/v23.1/v23.1.0-alpha.9.md

[DOC-6519]
- Also remove CRL employees from first-time contributors to v23.1.0-alpha.8
[releases/v23.1.md](https://deploy-preview-16683--cockroachdb-docs.netlify.app/docs/releases/v23.1.html)

[DOC-6519] Release notes for v23.1.0-alpha.9

---

cockroachcloud/quickstart.md

Change the pared down quickstart from ccloud-only to console-only due to multiple bugs coming up with ccloud in the past weeks
Related bug: https://cockroachlabs.atlassian.net/browse/CC-9799

Quickstart with Cloud Console

---

cockroachcloud/use-managed-service-backups.md

- Fixed Serverless section due to missing content
Preview:
[Use Managed Service Backups](https://deploy-preview-16711--cockroachdb-docs.netlify.app/docs/cockroachcloud/use-managed-service-backups.html?filters=dedicated)

Fix serverless content on use managed backups page

---

v22.2/build-a-go-app-with-cockroachdb.md
v23.1/build-a-go-app-with-cockroachdb.md

This PR updates the pgx tutorial to use pgx v5. It also eliminates the need to run a separate command to create the database.
Depends on https://github.com/cockroachlabs/example-app-go-pgx/pull/6
Fixes DOC-7275.

Update pgx example for v5

---

v21.2/architecture/storage-layer.md
v22.1/architecture/storage-layer.md
v22.2/architecture/storage-layer.md
v23.1/architecture/storage-layer.md

Fixes DOC-5193
Relates to https://github.com/cockroachdb/cockroach/pull/68043

IMPORT, schema changes don't use protected ts

---

_config_base.yml
_data/releases.yml
_includes/releases/v23.1/v23.1.0-beta.1.md

Addresses: DOC-6520
- Release notes for v23.1.0-beta.1
Staging
[v23.1.md](https://deploy-preview-16710--cockroachdb-docs.netlify.app/docs/releases/v23.1.html#v23-1-0-beta-1)

DOC-6520 v23.1.0-beta.1 release notes

---

_includes/v23.1/ui/admin-access.md
cockroachcloud/export-metrics.md
v23.1/datadog.md
v23.1/kibana.md
v23.1/monitor-cockroachdb-with-prometheus.md
v23.1/monitoring-and-alerting.md
v23.1/operational-faqs.md
v23.1/ui-overview-dashboard.md
v23.1/ui-sessions-page.md
v23.1/ui-statements-page.md
v23.1/ui-transactions-page.md

[DOC-6974] Document Console observability's impact on cluster performance
- Primarily add advice about disabling DB Console metric persistence if you use the Prometheus endpoint with a third-party tool
- Light copyedit
- Done for 23.1 and Cloud. Will backport to 22.2 and 22.1 after technical agreement is reached
- Out of scope: Mention of visus, which will happen in a follow-up PR against the same JIRA.
[cockroachcloud/export-metrics.md](https://deploy-preview-16520--cockroachdb-docs.netlify.app/docs/cockroachcloud/export-metrics.html)
[v23.1/datadog.md](https://deploy-preview-16520--cockroachdb-docs.netlify.app/docs/v23.1/datadog.html)
[v23.1/kibana.md](https://deploy-preview-16520--cockroachdb-docs.netlify.app/docs/v23.1/kibana.html) …

[DOC-6974] Document Console observability's impact on cluster performance

---

v21.2/security-reference/security-overview.md
v22.1/security-reference/security-overview.md
v22.2/security-reference/security-overview.md
v23.1/security-reference/security-overview.md

The acronym for the encryption algorithm currently reads "AED". It should read "AES", which stands for Advanced encryption Standard.

Fix typo in security reference

---

_config_base.yml

We've been getting the following warning in our production builds:
```
4:08:42 PM: [jekyll-algolia] Configuration mismatch:
4:08:42 PM: It seems that your index settings have been edited from outside of the
4:08:42 PM: jekyll-algolia plugin.
4:08:42 PM: This can happen if you manually edited them from the Algolia dashboard, for
4:08:42 PM: example. Don't worry, they will still be honored (for now).
4:08:42 PM: Still, we strongly encourage you to save any custom config inside the
4:08:42 PM: algolia.settings key of your _config.yml instead. Any value set there will
4:08:42 PM: always take precedence over anything you manually set in your dashboard.
4:08:42 PM: This is the best way to be sure your settings will not be lost in the future.
```
This PR fixes that drift.

Fix Algolia drift

---

v22.2/export-data-with-changefeeds.md
v22.2/export.md
v23.1/export-data-with-changefeeds.md
v23.1/export.md

Fixes DOC-7323
This PR adds the following to encourage users to create changefeeds for data export over `EXPORT`:
- Note to the top of the `EXPORT` page 
- Additional benefits of changefeeds to Export Data with Changefeeds page

Recommend changefeeds for exporting data over `EXPORT`

---

cockroachcloud/cluster-management.md

Addresses DOC-6404:
- Updated the restore section on the Dedicated Cluster Management page
- Linked out to the relevant pages for Console restores and manual backups and restores
Questions:
- Should we include the 'Note' section? Is this still applicable?
- Do we care about the URL naming convention for the page? For Serverless, the URL is `serverless-cluster-management.html` while this page is `cluster-management.html`. We could change it to `dedicated-cluster-management.html` for consistency. 
Preview:
- [Manage Dedicated Cluster](https://deploy-preview-16806--cockroachdb-docs.netlify.app/docs/cockroachcloud/cluster-management.html#restore-data-from-a-backup)

DOC-6404 updated restore section for manage Dedicated cluster page

---

jekyll-algolia-dev/lib/jekyll/algolia/indexer.rb

DOC-6143
Add `SCT` as a search synonym for `schema conversion tool`.

add SCT as search synonym

---

_includes/v22.1/cdc/configure-all-changefeed.md
_includes/v22.2/cdc/configure-all-changefeed.md
_includes/v23.1/cdc/configure-all-changefeed.md

Fixes DOC-7484
Fix a doc bug with configuring all changefeeds. The `job_id` needs to be included for this to run and pause or resume jobs successfully.

Fix missing job_id from configure all resume/pause changefeeds

---

cockroachcloud/serverless-unsupported-features.md

https://cockroachlabs.atlassian.net/browse/DOC-7072
The following SQL O11Y features are not yet surfaced directly in the CC console until we have proper FGAC:
Statement diagnostic bundles (Statements page)
Dropping unused indexes (Insights and Databases pages)
Creating missing indexes (Insights)
Replacing existing indexes (Insights)
Also removed the Jobs page from unsupported features because it does exist in the Cloud Console and added a few links.

Document unsupported console observability features

---

_includes/v22.2/sql/preloaded-databases.md
_includes/v23.1/sql/preloaded-databases.md
v22.2/show-databases.md
v23.1/show-databases.md

This PR fixes the example output of `SHOW DATABASES` to match the current output, and fixes the incorrect list of default database.
Fixes DOC-7511.
Fixes DOC-7374.

Update SHOW DATABASES example output

---

_includes/v22.2/sql/grant-revoke-schema-changes.md
_includes/v23.1/sql/grant-revoke-schema-changes.md
v22.2/grant.md
v22.2/revoke.md
v23.1/grant.md
v23.1/revoke.md

... as well as a note about GRANT operations inside transactions potentially blocking other transactions on the system, since they touch role memberships, which are used by most other transactions as well. Therefore the other concurrent transactions accessing the role information will be blocked and have to wait.
Unless they use the new cluster setting added in v23.1.
This change adds:
- The note about GRANT ops inside a transaction to the v22.2 and v23.1 docs
- The info about the new cluster setting to the v23.1 docs.
Fixes DOC-6345, DOC-6733, DOC-7205

Add setting to adjust grant lease options

---

_includes/v22.2/sql/privileges.md
v22.2/security-reference/authorization.md

Fixes DOC-7574
Removed `CHANGEFEED` priv from system-level privilege table in v22.2 and added to supported privilege table.

Correct changefeed from system priv v22.2

---

v23.1/changefeed-examples.md
v23.1/changefeed-sinks.md
v23.1/cockroachdb-feature-availability.md
v23.1/create-changefeed.md

Fixes DOC-7149
Removed the preview label from webhook sink across the changefeed docs.
Updated the "beta" label on Pub/Sub to "Preview" that was missed on one of the pages.

Remove the preview label from changefeed webhook sink

---

_includes/cockroachcloud/cockroachcloud-pricing.md
cockroachcloud/create-your-cluster.md

https://cockroachlabs.atlassian.net/browse/DOC-7589
Linked out to pricing docs instead of table.
Removed temporarily disabled region note (has been there as long as I can recall).
Left the "custom IP ranges" note as it seemed more necessary to know while creating a cluster.

Remove direct pricing info and disabled regions

---

_includes/v23.1/sql/crdb-internal-is-not-supported-for-production-use.md
_includes/v23.1/sql/show-ranges-output-deprecation-notice.md
v23.1/alter-range.md
v23.1/crdb-internal.md
v23.1/show-ranges.md

Fixes:
- DOC-6468
- DOC-6469
- DOC-6470
- DOC-6471
- DOC-6472
- DOC-6473
- DOC-6732
- DOC-6839
- DOC-7311
- DOC-7327
- Update `SHOW RANGES` docs to use the new syntax and output, and note the deprecation of the old output.
- Also, let users know that the updated `SHOW RANGES` is the place to get detailed information about leaseholders, etc., *not*  `crdb_internal.ranges*`

Update docs on range inspection with SHOW RANGES

---

_includes/v23.1/prod-deployment/decommission-pre-flight-checks.md
v23.1/cockroach-node.md
v23.1/node-shutdown.md

Fixes DOC-6744
- Update 'Node Shutdown' page with information about the new decommissioning pre-flight checks, including how they work at a high level, and with an example of the error message format
- Since this page mentions decommissioning in several places, we share the info across those places using an include
- Small opportunistic edit to add a sub-TOC to make the node removal process a little easier to follow
- Update `cockroach node decommission` docs with the new `--checks` flag

Add docs for decommissioning pre-flight checks

---

cockroachcloud/use-managed-service-backups.md

Addresses DOC-7485:
- Added the Limited Access tag as feature is currently behind a feature flag
Preview:
- [Self-Service Cluster Restore](https://deploy-preview-16952--cockroachdb-docs.netlify.app/docs/cockroachcloud/use-managed-service-backups.html?filters=dedicated#restore-a-cluster)

DOC-7485 self service restore limited access

---

_includes/v23.1/sidebar-data/manage.json
cockroachcloud/upgrade-to-v23.1.md
v23.1/upgrade-cockroach-version.md

[DOC-7250][DOC-7391] 23.1 general upgrade for self-hosted and cloud
[cockroachcloud/upgrade-to-v23.1.md](https://deploy-preview-16957--cockroachdb-docs.netlify.app/docs/cockroachcloud/upgrade-to-v23.1.html)
[v23.1/upgrade-cockroach-version.md](https://deploy-preview-16957--cockroachdb-docs.netlify.app/docs/v23.1/upgrade-cockroach-version.html)

[DOC-7250][DOC-7391] 23.1 upgrade for self-hosted and cloud

---

_includes/v22.2/sidebar-data/deploy.json
_includes/v23.1/sidebar-data/deploy.json
v23.1/fips-compliance.md
v23.1/install-cockroachdb-linux.md
vale/Vocab/CockroachDB/accept.txt

[DOC-6998] Document FIPS-ready runtimes
[v23.1/fips-compliance.md](https://deploy-preview-16462--cockroachdb-docs.netlify.app/docs/v23.1/fips-compliance.html)
[v23.1/install-cockroachdb-linux.md](https://deploy-preview-16462--cockroachdb-docs.netlify.app/docs/v23.1/install-cockroachdb-linux.html)

[DOC-6998] Document FIPS-ready CockroachDB runtimes

---

.github/workflows/changed_files.yml
.github/workflows/vale.yml
v22.2/online-schema-changes.md
v23.1/online-schema-changes.md

This PR adds some additional guidance on storage requirements before performing online schema changes.
After talking with engineering, it appears that we have product limitations in v22.2 and v23.1.0 that prevent accurate estimates of range sizes with `SHOW RANGES`/`SHOW INDEXES`, `crdb_internal` queries, and the DB Console.
When the fixes get incorporated/backfilled we will require a follow-up PR. But in the meantime, I've made the decision to include the queries in this PR because it's better to have a very rough and possibly inaccurate estimate of range size than to give absolutely no insight at all.
Fixes DOC-262.

Online schema change best practices

---

v23.1/sql-feature-support.md

Add TSVECTOR and TSQUERY to the list of supported data types on the SQL Feature Support page. This page was already updated in #16887 but I had missed updating the "row values" table.

add tsvector/tsquery to supported SQL row values

---

_includes/releases/v23.1/v23.1.0.md
_includes/version-switcher.html

Quick follow on 23.1.0 release notes

---

v23.1/known-limitations.md

Fixes a link and adds a tracking issue for the v23.1 COPY known limitation.

Fix COPY KL

---

v23.1/take-full-and-incremental-backups.md

Addresses DOC-6775:
- Arbitrarily long incremental backup chain are now available for users who wish to do incremental backups with increasing frequency, up to 400 incremental backups
- Docs provide guidance on the range available for customers to take incremental backups 
Preview:
- [Take Incremental Backups](https://deploy-preview-16839--cockroachdb-docs.netlify.app/docs/dev/take-full-and-incremental-backups.html#incremental-backups)

DOC-6775 support arbitrarily long incremental backups

---

_config_base.yml
_data/releases.yml
_includes/releases/v23.1/v23.1.0.md
_includes/releases/v23.1/v23.1.1.md
advisories/a103220.md
v23.1/known-limitations.md

This PR does the following:
- Withdraws v23.1.0 binaries
- Removes this bug from the Known Limitations (since it's now documented by a TA)
- Adds TA 103220
- Adds v23.1.1 release notes
Closes DOC-6564.

v23.1.1 release

---

_config_cockroachdb.yml

Bumping Dedicate hotfix version to v22.2.9 as v22.2.8 was withdrawn.

Bumping Dedicated hotfix number

---

v23.1/ui-cluster-overview-page.md

Addresses: DOC-6840
- Adds brief mention that unavailable nodes will show stale (last-known) values for capacity on the **Cluster Overview** page.
Staging
[ui-cluster-overview-page.md](https://deploy-preview-16442--cockroachdb-docs.netlify.app/docs/dev/ui-cluster-overview-page.html#capacity-metrics)

DOC-6840 DB Console stale capacity

---

v22.2/show-grants.md
v22.2/show-system-grants.md
v23.1/show-grants.md
v23.1/show-system-grants.md

[DOC-6649], [DOC-6650] show grants column names fix
This PR takes over and rebases #16461 to get it over the finish line.
[v22.2/show-grants.md](https://deploy-preview-17009--cockroachdb-docs.netlify.app/docs/v22.2/show-grants.html)
[v22.2/show-system-grants.md](https://deploy-preview-17009--cockroachdb-docs.netlify.app/docs/v22.2/show-system-grants.html)
[v23.1/show-grants.md](https://deploy-preview-17009--cockroachdb-docs.netlify.app/docs/v23.1/show-grants.html)
[v23.1/show-system-grants.md](https://deploy-preview-17009--cockroachdb-docs.netlify.app/docs/v23.1/show-system-grants.html)

[DOC-6649][DOC-6650] show grants column names fix

---

_includes/v23.1/cdc/pubsub-performance-setting.md
_includes/v23.1/cdc/webhook-performance-setting.md
v23.1/changefeed-examples.md
v23.1/changefeed-sinks.md
v23.1/create-changefeed.md

Fixes DOC-7349, DOC-7414
Added a note for the new webhook and Pub/Sub cluster settings that allow the performance improvements.
Note: I haven't added setting these embedded in examples because the intention is to backport these settings to be default on.

Add the webhook and pub/sub performance cluster setting to docs

---

.github/scripts/docs-prs-reviews.go
.github/workflows/pr-reviews.yml

We as an organization have a contractual/legal obligation in some situations to ensure that our documentation is accurate. We want a member of the docs team to review each PR that comes in from a non-docs team member (this includes external contributors and CRL employees alike).
- If the PR is in draft, pass the check.
- Else:
- If the author of the PR is a member of docs-prs, pass the check.
- Else, check the reviewers of the PR.
- If there is a review from at least one docs-prs member and the latest review from that member is approved, pass the check.
- Else, fail the check.
Fixes DOC-7469

DOC-7469: Improve governance around docs PRs

---

_includes/head.html
sitemap.xml

Now that v23.1 is GA, both the dev and stable paths point to v23.1. In the sitemap logic and in the page head, it would automatically force a page's canonical to point to the dev URL. This PR fixes that.

Fix issues with sitemap and canonicals

---

_includes/v23.1/cdc/show-changefeed-job-retention.md
_includes/v23.1/cdc/show-changefeed-job.md
v23.1/create-and-configure-changefeeds.md
v23.1/show-jobs.md

Fixes DOC-7207
`SHOW CHANGEFEED JOBS` will now show _all_ jobs even if they haven't completed, and it does not matter when they completed. This differs from `SHOW JOBS`, which has a default 14-day retention time. Both of these statements can have their display retention time altered with a cluster setting.
This PR updates the docs to this effect, and also adds a missing `SHOW` section to our get started create and configure page for changefeeds.

Update show jobs doc for changefeed retention time

---

cockroachcloud/create-a-serverless-cluster.md
cockroachcloud/regions.md
cockroachcloud/serverless-faqs.md

Added serverless section to regions page, removed regions from serverless faq, and removed leftover region step from create page

Add serverless to cloud regions page

---

v23.1/create-changefeed.md

This is a quick fix to remove the random PTS monitoring include from the top of `CREATE CHANGEFEED` SQL page. It has no context there and is seemingly an error leftover from the PTS work for v23.1.
Replaced with a reference to the monitoring page.

Replace PTS monitoring bullet list from SQL page

---

_config_base.yml
_data/releases.yml
_includes/releases/v22.2/v22.2.10.md

[DOC-6559] Release notes for 22.2.10
[releases/v22.2.md](https://deploy-preview-17121--cockroachdb-docs.netlify.app/docs/releases/v22.2.html)

[DOC-6559] Release notes for 22.2.10

---

_includes/releases/v23.1/v23.1.0.md

Quick fix to the 23.1 GA release notes. (It should not read two minor versions — it is major versions and not quite two.)

Correct version description in release notes

---

_includes/v22.1/cdc/metrics-labels.md
_includes/v22.2/cdc/metrics-labels.md

Fixes DOC-7042
This is to update the description for metrics label blurb to be a little clearer. Had updated this as part of 23.1 work, so pulling the v23.1 description to v22.2 and v22.1.

Update to metric label blurb

---

cockroachcloud/cmek-ops-aws.md

Reverts cockroachdb/docs#16398
See https://github.com/cockroachlabs/managed-service/pull/13158#pullrequestreview-1442620976
Preview: [cockroachcloud/cmek-ops-aws.md](https://deploy-preview-17086--cockroachdb-docs.netlify.app/docs/cockroachcloud/cmek-ops-aws.html)

Revert "[DOC-7103] Remove mention of external ID from AWS CMEK docs"

---

src/current/_includes/v22.2/start-in-docker/mac-linux-steps-single-node.md
src/current/_includes/v22.2/start-in-docker/mac-linux-steps.md
src/current/_includes/v23.1/start-in-docker/mac-linux-steps-single-node.md
src/current/_includes/v23.1/start-in-docker/mac-linux-steps.md
src/current/v22.2/start-a-local-cluster-in-docker-windows.md
src/current/v23.1/start-a-local-cluster-in-docker-windows.md

[DOC-782] Use different ports for additional Docker nodes
[v22.2/start-a-local-cluster-in-docker-linux.md](https://deploy-preview-17045--cockroachdb-docs.netlify.app/docs/v22.2/start-a-local-cluster-in-docker-linux.html)
[v22.2/start-a-local-cluster-in-docker-mac.md](https://deploy-preview-17045--cockroachdb-docs.netlify.app/docs/v22.2/start-a-local-cluster-in-docker-mac.html)
[v22.2/start-a-local-cluster-in-docker-windows.md](https://deploy-preview-17045--cockroachdb-docs.netlify.app/docs/v22.2/start-a-local-cluster-in-docker-windows.html)
[v23.1/start-a-local-cluster-in-docker-linux.md](https://deploy-preview-17045--cockroachdb-docs.netlify.app/docs/v23.1/start-a-local-cluster-in-docker-linux.html)
[v23.1/start-a-local-cluster-in-docker-mac.md](https://deploy-preview-17045--cockroachdb-d …

[DOC-782] Use different ports for additional Docker nodes

---

src/current/_includes/v23.1/cdc/recommendation-monitoring-pts.md
src/current/v23.1/changefeed-examples.md
src/current/v23.1/create-and-configure-changefeeds.md
src/current/v23.1/create-changefeed.md

Quick fix to the monitoring callout that should be at the top of pages

Correct the callout for cdc monitoring on main pages

---

v21.2/aws-dms.md
v22.1/aws-dms.md
v22.2/aws-dms.md
v22.2/qlik.md
v23.1/aws-dms.md
v23.1/qlik.md

[DOC-7471](https://cockroachlabs.atlassian.net/browse/DOC-7471)
DOC-7267
- Make correction to our schema creation guidance in Qlik and DMS docs.
- Document CRDB/PG string sorting difference as a "known limitation" in DMS doc when validating data.

DMS schema and string sorting differences

---

src/current/v22.2/changefeed-sinks.md
src/current/v23.1/changefeed-sinks.md

Fixes DOC-7841
The `webhook_sink_config` `Retry.Max` field was described incorrectly as the maximum amount of time. This provides clarification on the two retry fields and provides an example of specifying the option.

Correct webhook sink maximum number of retries

---

src/current/v23.1/show-backup.md

Addresses DOC-5751:
- Adds the 'regions' column to SHOW BACKUP which outputs a string of ALTER DATABASE commands if
the database is a multi-region database and NULL if not
This is a duplicate of https://github.com/cockroachdb/docs/pull/17079 which was on the `master` branch.

DOC-5751 added regions column for show backup

---

src/current/cockroachcloud/export-logs.md
src/current/cockroachcloud/export-metrics.md
src/current/v23.1/cockroachdb-feature-availability.md

Addresses DOC-7211
Updated export logs and export metrics pages, removed references to creation date restrictions
This PR replaces https://github.com/cockroachdb/docs/pull/16516

DOC-7211: Log export and metric export docs should remove language around older cluster limitations

---

src/current/_includes/cockroachcloud/ccloud/install-ccloud.md

Closes [DOC-8082](https://cockroachlabs.atlassian.net/browse/DOC-8082).

Bump ccloud version to 0.4.9

---

src/current/_includes/cockroachcloud/migration/sct-self-hosted.md
src/current/cockroachcloud/migrations-page.md

Clarify that you can use the SCT to export the schema for a migration to CockroachDB Self-Hosted. This point was already in the docs but was not as visible as it could be.

clarify that SCT can be used for self-hosted migrations

---

src/current/v23.1/performance-recipes.md

The use of an include embedded in an info callout is currently causing this page to render incorrectly. Removing it from the callout seems to be the only way to use this include in a bulleted list.

fix problematic formatting on SQL perf recipes page

---

src/current/_includes/v22.2/ui/insights.md
src/current/_includes/v23.1/performance/sql-trace-txn-enable-threshold.md
src/current/_includes/v23.1/ui/insights.md
src/current/_includes/v23.1/ui/transaction-details.md
src/current/v22.2/performance-recipes.md
src/current/v23.1/performance-recipes.md

Addresses: DOC-7876 
(A) Updated Performance Tuning Recipes page, (1) added references to Schema Insights tab to drop unused indexes and create missing indexes. (2) Fixed right TOC by adding hyphens to liquid delimiters. (B) Updated Insights page, (1) changed link to point to Index Recommendations section of Databases page, (2) fixed table format. (C) Updated Transactions page, fixed bullet list format.

DOC-7876: Update performance-tuning recipes for unused and missing indexes recommendations

---

src/current/v22.1/logging-overview.md
src/current/v22.1/node-shutdown.md
src/current/v22.2/logging-overview.md
src/current/v22.2/node-shutdown.md
src/current/v23.1/logging-overview.md
src/current/v23.1/node-shutdown.md

[DOC-796] Document that nodes now log their progress shutting down
[src/current/v22.1/logging-overview.md](https://deploy-preview-17319--cockroachdb-docs.netlify.app/docs/v22.1/logging-overview.html)
[src/current/v22.1/node-shutdown.md](https://deploy-preview-17319--cockroachdb-docs.netlify.app/docs/v22.1/node-shutdown.html)
[src/current/v22.2/logging-overview.md](https://deploy-preview-17319--cockroachdb-docs.netlify.app/docs/v22.2/logging-overview.html)
[src/current/v22.2/node-shutdown.md](https://deploy-preview-17319--cockroachdb-docs.netlify.app/docs/v22.2/node-shutdown.html)
[src/current/v23.1/logging-overview.md](https://deploy-preview-17319--cockroachdb-docs.netlify.app/docs/v23.1/logging-overview.html)
[src/current/v23.1/node-shutdown.md](https://deploy-preview-17319--cockroachdb-d …

[DOC-796] Document that nodes now log their progress shutting down

---

src/current/_includes/releases/v23.1/v23.1.0.md

The formatting of the final paragraph of the `Add configurable setting to adjust grant lease options` description is broken:
This PR fixes the formatting.

Fix formatting in 23.1.0 release notes

---

src/current/v23.1/crdb-internal.md

Addresses:
DOC-6168: PR #91098 - sqlstats: record idle latency for statements
DOC-6244: PR #92351 - sql, ui: add index used by statement
DOC-6906: PR #96436 - sql: add last error code to statements statistics tables
Updated crdb_internal page, added idleLat, indexes, and lastErrorCode to statement_statistics.

added idleLat, indexes, and lastErrorCode to statement_statistics

---

src/current/v22.1/gssapi_authentication.md
src/current/v22.2/gssapi_authentication.md
src/current/v23.1/gssapi_authentication.md

[DOC-7699] Remove outdated note about GSSAPI
[src/current/v22.1/gssapi_authentication.md](https://deploy-preview-17331--cockroachdb-docs.netlify.app/docs/v22.1/gssapi_authentication.html)
[src/current/v22.2/gssapi_authentication.md](https://deploy-preview-17331--cockroachdb-docs.netlify.app/docs/v22.2/gssapi_authentication.html)
[src/current/v23.1/gssapi_authentication.md](https://deploy-preview-17331--cockroachdb-docs.netlify.app/docs/v23.1/gssapi_authentication.html)

[DOC-7699] Remove outdated note about GSSAPI

---

src/current/_includes/v22.2/start-in-docker/mac-linux-steps.md
src/current/_includes/v23.1/start-in-docker/mac-linux-steps.md
src/current/v22.2/start-a-local-cluster-in-docker-windows.md
src/current/v23.1/start-a-local-cluster-in-docker-windows.md

[DOC-8207] Fix typo in Docker startup page
[src/current/v22.2/start-a-local-cluster-in-docker-mac.md](https://deploy-preview-17356--cockroachdb-docs.netlify.app/docs/v22.2/start-a-local-cluster-in-docker-mac.html)
[src/current/v22.2/start-a-local-cluster-in-docker-linux.md](https://deploy-preview-17356--cockroachdb-docs.netlify.app/docs/v22.2/start-a-local-cluster-in-docker-linux.html)
[src/current/v23.1/start-a-local-cluster-in-docker-mac.md](https://deploy-preview-17356--cockroachdb-docs.netlify.app/docs/v23.1/start-a-local-cluster-in-docker-mac.html)
[src/current/v23.1/start-a-local-cluster-in-docker-linux.md](https://deploy-preview-17356--cockroachdb-docs.netlify.app/docs/v23.1/start-a-local-cluster-in-docker-linux.html)
[src/current/v22.2/start-a-local-cluster-in-docker-windows.md](ht …

[DOC-8207] Fix typo in Docker startup page

---

src/current/_data/redirects.yml

This PR ensures that anyone accessing `docs/(dev|stable)/interleave-in-parent(.html)?` are redirected to the deprecation notice in v21.1.

Update interleave redirects

---

src/current/v23.1/connect-to-a-changefeed-kafka-sink-with-oauth-using-okta.md

Fixes DOC-8080
I’ve worked through this tutorial a number of times now for testing, and every time I forget to change into the correct directory that is noted at the start of this step here: [Connect to a Changefeed Kafka Sink with OAuth Using Okta](https://www.cockroachlabs.com/docs/v23.1/connect-to-a-changefeed-kafka-sink-with-oauth-using-okta.html#step-7-start-your-kafka-server) 
It might be easier for readers not to miss this if we just added in a `cd` directory command block for this.

Docs Fixit: Add cd command block for ease

---

src/current/v22.2/create-changefeed.md
src/current/v23.1/create-changefeed.md

Fixes DOC-8250
Very minor edit to bring the direction to the main Changefeed Sinks page up to the top of the sink URI section on the changefeed SQL page. Users can get more information on the Sinks page and so we want them to know about this if they land on the SQL page first.

Docs fixit: Better direct users to sink page from SQL page

---

src/current/_includes/common/tls-bad-cipher-warning.md
src/current/_includes/v23.1/app/java-tls-note.md
src/current/cockroachcloud/frequently-asked-questions.md
src/current/v23.1/authentication.md

[DOC-8159](https://cockroachlabs.atlassian.net/browse/DOC-8159)
Warn about insecure TLS cipher support

add warning about lack of support for insecure tls 1.2 cipher suites

---

src/current/_includes/releases/cloud/2022-09-24.md
src/current/_includes/v22.2/ui/databases.md
src/current/_includes/v23.1/ui/databases.md
src/current/cockroachcloud/cluster-management.md
src/current/cockroachcloud/databases-page.md
src/current/cockroachcloud/serverless-cluster-management.md

Addresses: DOC-8269
[A) Updated Databases page, (1) removed reference to Add Database button, (2) added hyphens to liquid tags to remove whitespace. (B) Updated Cloud Databases page, removed reference to create, edit, and delete databases. (C) Updated Serverless and Dedicated Cluster Management pages, removed Create a Database section. (D) Updated cloud release notes page for 2022-09-24, to remove link to Create a Database section.

DOC-8269: Update the docs to indicate that users cannot create or delete databases in the CC console

---

src/current/v23.1/automatic-cpu-profiler.md
src/current/v23.1/troubleshooting-overview.md

Addresses: DOC-8144
Created Automatic CPU Profiler page. Updated Troubleshooting Overview page with link to CPU Profiler page, debug zip and debug tsdump.

DOC-8144: Document new automatic CPU profiler cluster settings

---

src/current/_includes/cockroachcloud/restore-multiregion-dedicated.md
src/current/cockroachcloud/authorization.md
src/current/cockroachcloud/use-managed-service-backups.md
src/current/v23.1/backup-and-restore-monitoring.md

Discovered this change via the release notes and opened a ticket https://cockroachlabs.atlassian.net/browse/DOC-8275

Backups page now called Backup and Restore

---

src/current/v23.1/create-and-configure-changefeeds.md
src/current/v23.1/monitor-and-debug-changefeeds.md

Fixes DOC-7567
This PR adds a short new section with some high-level recommendations on running a lot of changefeeds while keeping system resources in mind. 
As part of this PR, rearranged the top of the Create and Configure Changefeeds page so that the addition of this new section could become part of the "Before you create a changefeed" guidelines/considerations.

Update changefeed docs with system resource recommendations

---

src/current/v23.1/architecture/replication-layer.md

Fixes a bug on the 'Architecture > Replication Layer' page where the value of the Raft tick interval was failing to render in the chart of important constants because the YAML variable in the docs page didn't match the YAML variable in the `_data/constants.yml` file.

Update name of Raft tick interval to match YAML

---

src/current/_includes/v22.1/misc/enterprise-features.md
src/current/_includes/v22.2/misc/enterprise-features.md
src/current/_includes/v23.1/misc/enterprise-features.md

[DOC-7213] Split up Enterprise features, strengthen calls to action, copyedit
NB: 22.1 doesn't have Cluster SSO, DB Console SSO, CDC Queries. 22.2 doesn't have CDC Queries
[src/current/v22.1/enterprise-licensing.md](https://deploy-preview-17398--cockroachdb-docs.netlify.app/docs/v22.1/enterprise-licensing.html)
[src/current/v22.1/get-started-with-enterprise-trial.md](https://deploy-preview-17398--cockroachdb-docs.netlify.app/docs/v22.1/get-started-with-enterprise-trial.html)
[src/current/v22.2/enterprise-licensing.md](https://deploy-preview-17398--cockroachdb-docs.netlify.app/docs/v22.2/enterprise-licensing.html)
[src/current/v22.2/get-started-with-enterprise-trial.md](https://deploy-preview-17398--cockroachdb-docs.netlify.app/docs/v22.2/get-started-with-enterprise-trial.html) …

[DOC-7213] Split up Enterprise features, copyedit

---

src/current/_includes/sidebar.html
src/current/_includes/sidebar.js.html
src/current/search.html

To test this PR:
- Access any page in the deploy preview. Make sure the sidebar renders and opens to the page you chose. The page should also open without any `.html` extension.
- Add `.html` to the end of the URL. The same page should appear highlighted in the sidebar.
- Search for any page in the docs. You should be brought to the stable URL with no `.html` extension.
- htmltest should pass.

Make sidebar/search use pretty URLs while preserving htmltest checks

---

src/current/_config_base.yml
src/current/_data/releases.yml
src/current/_includes/releases/v22.2/v22.2.12.md

[DOC-8377] Release notes for v22.2.12
Preview: [releases/v22.2.md](https://deploy-preview-17501--cockroachdb-docs.netlify.app/docs/releases/v22.2.html)

[DOC-8377] Release notes for v22.2.12

---

src/current/_config_base.yml
src/current/_data/releases.yml
src/current/_includes/releases/v23.1/v23.1.6.md

relates to https://github.com/cockroachdb/docs/pull/17530 and https://github.com/cockroachdb/docs/pull/17519

v23.1.6 release notes

---

src/current/cockroachcloud/export-metrics.md

Addresses: DOC-8265
Modified Export Metrics page, added note about AWS Cloudwatch spend.

DOC-8265: Document metric export to CloudWatch dimensions and cost implications

---

src/current/releases/kubernetes-operator.md

[DOC-8229] Operator 2.10 and 2.11 release notes
[src/current/releases/kubernetes-operator.md](https://deploy-preview-17366--cockroachdb-docs.netlify.app/docs/releases/kubernetes-operator.html)

[DOC-8229] Operator 2.10 and 2.11 release notes

---

src/current/_data/redirects.yml

This PR adds redirects from URLs that were resulting in 404s, discovered by looking at pages with low CSAT scores in our Looker dashboard.

Add redirects from old install URLs

---

src/current/v23.1/changefeed-sinks.md

[DOC-8357](https://cockroachlabs.atlassian.net/browse/DOC-8357) 
Two of the sasl_client_secret parameters are uppercase on the changefeed sinks page. Right now, changefeeds are not case agnostic. They must be lowercase to pass. If users copy and paste from the docs, they would run into an error.

Docs Fixit: incorrect casing for CDC sasl param

---

src/current/v23.1/metrics.md
src/current/v23.1/ui-custom-chart-debug-page.md

Addresses: DOC-8394
Updated Custom Chart and Metrics pages, removed Serverless tab.

DOC-8394: On Custom Chart Debug Page, remove Serverless tab under Available Metrics section

---

src/current/cockroachcloud/aws-privatelink.md
src/current/cockroachcloud/connect-to-a-serverless-cluster.md
src/current/cockroachcloud/connect-to-your-cluster.md

[DOC-8435] Document how to get the connection string for MR Serverless with PrivateLink
[DOC-8546] Correct VPC Peering docs to change the desired status from Active to Available
- Also improve the Dedicated doc in a similar way.
Preview: 
[src/current/cockroachcloud/connect-to-a-serverless-cluster.md](https://deploy-preview-17570--cockroachdb-docs.netlify.app/docs/cockroachcloud/connect-to-a-serverless-cluster.html)
[src/current/cockroachcloud/connect-to-your-cluster.md](https://deploy-preview-17570--cockroachdb-docs.netlify.app/docs/cockroachcloud/connect-to-your-cluster.html)

[DOC-8435][DOC-8546] Document how to get the connection string for MR Serverless with PrivateLink, correct VPC Peering error

---

src/current/netlify.toml

Netlify is sunsetting asset optimization (images, JS, CSS) in October 2023, so this PR disables it ahead of schedule.

DOC-8355: Disable asset optimization settings in docs

---

src/current/_includes/v22.2/sidebar-data/stream.json
src/current/_includes/v23.1/sidebar-data/stream-data.json

Fixes DOC-8583
This is a quick fix PR to rename one of the headings in the Stream Data side nav to better describe the pages that fall underneath and to better relate to the [heading on the CDC overview page](https://www.cockroachlabs.com/docs/stable/change-data-capture-overview#optimize-a-changefeed-for-your-workload).

Update heading in stream data sidenav

---

src/current/v22.2/cluster-setup-troubleshooting.md
src/current/v23.1/cluster-setup-troubleshooting.md

[DOC-202] Document troubleshooting info about what to do if a node's timezone changes
[v22.2/cluster-setup-troubleshooting.md](https://deploy-preview-16478--cockroachdb-docs.netlify.app/docs/v22.2/cluster-setup-troubleshooting.html)
[v23.1/cluster-setup-troubleshooting.md](https://deploy-preview-16478--cockroachdb-docs.netlify.app/docs/v23.1/cluster-setup-troubleshooting.html)

[DOC-202] Document troubleshooting info about what to do if a node's timezone changes

---

src/current/v22.2/changefeed-sinks.md
src/current/v23.1/changefeed-sinks.md

Fixes DOC-7828
Adds a short clarification for topic naming when a changefeed watching multiple tables emits to a Pub/Sub sink.
Also, includes a slight rearrange of the description to bullet format so the considerations are easier to parse.

Clarify multiple table topic naming for Pub/Sub sink

---

src/current/_includes/head.html
src/current/_layouts/default.html

We should be explicit with the protocol we use in our URLs. This adds `https:` in front of the URLs we reference in our HTML templates.

Fix protocol-relative URLs

---

src/current/v22.1/changefeed-examples.md
src/current/v22.2/changefeed-examples.md
src/current/v23.1/changefeed-examples.md

Fixes DOC-8619
This is a quick fix to update the `--whitelist` flag from Kafka examples, which is now deprecated. Kafka has replaced this flag with `--include`. Refer to https://docs.confluent.io/kafka/operations-tools/kafka-tools.html#kafka-console-consumer-sh
Also, removed unnecessary prompts from command prompts and syntax markers from output blocks.

Update Kafka flag in example to remove deprecated language

---

src/current/v23.1/set-cluster-setting.md
src/current/v23.1/show-cluster-setting.md
src/current/v23.2/set-cluster-setting.md
src/current/v23.2/show-cluster-setting.md

Addresses: DOC-7918
(1) Updated SET CLUSTER SETTING and SHOW CLUSTER SETTING pages, updated Required privileges to include MODIFYSQLCLUSTERSETTING. (2) Updated 23.2 files.

DOC-7918: PR #104542 - sql: Limit MODIFYSQLCLUSTERSETTING to only view sql.defaults

---

src/current/v22.2/set-cluster-setting.md
src/current/v22.2/show-cluster-setting.md

Addresses: DOC-7919
(1) Updated SET CLUSTER SETTING and SHOW CLUSTER SETTING pages for 22.2, updated Required privileges with call out about sql.auth.modify_cluster_setting_applies_to_all.enabled cluster setting.

DOC-7919: PR #104231 - release-22.2: sql: prevent MODIFYCLUSTERSETTING from viewing non sql.defaults

---

src/current/v22.2/build-a-csharp-app-with-cockroachdb.md
src/current/v23.1/build-a-csharp-app-with-cockroachdb.md
src/current/v23.2/build-a-csharp-app-with-cockroachdb.md

This PR comprises the doc work to fix the transactions example, and updates the instructions to use a `DATABASE_URL` environment variable to connect to the cluster.
This PR depends on https://github.com/cockroachlabs/hello-world-csharp/pull/6 being merged first.
Fixes DOC-8630.

Refactor C# example to use DATABASE_URL

---

src/current/v23.1/architecture/replication-layer.md
src/current/v23.1/cluster-setup-troubleshooting.md
src/current/v23.1/load-based-splitting.md
src/current/v23.1/node-shutdown.md
src/current/v23.2/architecture/replication-layer.md
src/current/v23.2/cluster-setup-troubleshooting.md
src/current/v23.2/load-based-splitting.md
src/current/v23.2/node-shutdown.md

Fixes:
- DOC-6917
- DOC-6989
- DOC-6999
- DOC-7746
- DOC-8564
- Architecture > Replication Layer: Update the 'Load-based splitting' section to describe how replica count & CPU usage are used to rebalance replicas (not disk usage)
- Cluster Setup Troubleshooting: Add a new section 'Disk usage is different across nodes in the cluster' to explain that this is expected behavior, and link to load-based replication architecture docs
- Load-based splitting: Add a new section 'Monitor load-based splitting' so users can know where to look in logs and metrics to see how it is working
- Node Shutdown: Update the 'Size and replication factor' to explain how replicas are rebalanced when a node is decommissioned and immediately replaced, and include a link to docs about how replica …

Add docs on CPU-based replica rebalancing

---

src/current/cockroachcloud/cockroachdb-dedicated-on-azure.md
src/current/cockroachcloud/export-metrics.md

Addresses: DOC-8232
(1) Updated Observability section of CockroachDB Dedicated on Azure page. (2) Updated Export Metrics From a CockroachDB Dedicated Cluster page, added “or Azure” to the four instances that “GCP” was mentioned.

DOC-8232: Docs for Datadog metrics integration supported for Dedicated Azure clusters

---

src/current/_includes/v22.1/orchestration/kubernetes-limitations.md
src/current/_includes/v22.1/orchestration/start-cockroachdb-operator-secure.md
src/current/_includes/v22.2/orchestration/kubernetes-limitations.md
src/current/_includes/v22.2/orchestration/start-cockroachdb-operator-secure.md
src/current/_includes/v23.1/orchestration/kubernetes-limitations.md
src/current/_includes/v23.1/orchestration/start-cockroachdb-operator-secure.md
src/current/v22.1/orchestrate-a-local-cluster-with-kubernetes.md
src/current/v22.2/orchestrate-a-local-cluster-with-kubernetes.md
src/current/v23.1/orchestrate-a-local-cluster-with-kubernetes.md

[DOC-8203] Document limitation on modifying Kubernetes labels when using the Operator
[src/current/v22.1/orchestrate-a-local-cluster-with-kubernetes.md](https://deploy-preview-17758--cockroachdb-docs.netlify.app/docs/v22.1/orchestrate-a-local-cluster-with-kubernetes.html)
[src/current/v22.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md](https://deploy-preview-17758--cockroachdb-docs.netlify.app/docs/v22.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.html)
[src/current/v22.1/deploy-cockroachdb-with-kubernetes.md](https://deploy-preview-17758--cockroachdb-docs.netlify.app/docs/v22.1/deploy-cockroachdb-with-kubernetes.html)
[src/current/v22.1/deploy-cockroachdb-with-kubernetes-insecure.md](https://deploy-preview-17758--cockroachdb-docs.netlify.app/docs/v22.1/deploy-cockroa …

[DOC-8203] Document limitation on modifying Kubernetes labels when using the Operator

---

src/current/v23.1/advanced-changefeed-configuration.md
src/current/v23.2/advanced-changefeed-configuration.md

Fixes DOC-7906
This PR adds a section to the Advanced Changefeed Configuration page around cluster settings that customers can tweak in order to improve changefeed latency.
- three cluster settings to use in combination
- some detail for each and a brief recommendation on what to change
- warnings around how adjusting these settings may affect transactions

Introduce improve changefeed latency section

---

src/current/_data/releases.yml

Linux and Docker were inadvertently marked as no longer experimental. cc/ @ianjevans who is on vacation.

Fix 23.1.10 ARM metadata

---

src/current/cockroachcloud/cloud-org-audit-logs.md
src/current/cockroachcloud/export-logs.md
src/current/v23.1/cockroachdb-feature-availability.md
src/current/v23.2/cockroachdb-feature-availability.md

[DOC-8845] Org and cluster log export are GA
[src/current/cockroachcloud/cloud-org-audit-logs.md](https://deploy-preview-17898--cockroachdb-docs.netlify.app/docs/cockroachcloud/cloud-org-audit-logs.html)
[src/current/cockroachcloud/export-logs.md](https://deploy-preview-17898--cockroachdb-docs.netlify.app/docs/cockroachcloud/export-logs.html)
[src/current/v23.1/cockroachdb-feature-availability.md](https://deploy-preview-17898--cockroachdb-docs.netlify.app/docs/v23.1/cockroachdb-feature-availability.html)
[src/current/v23.2/cockroachdb-feature-availability.md](https://deploy-preview-17898--cockroachdb-docs.netlify.app/docs/v23.2/cockroachdb-feature-availability.html)

[DOC-8845] Org and cluster log export are GA

---

.github/workflows/vale.yml

Writers can run it locally via `make vale` on a branch prior to committing, or they can run `vale <filename>`.

Turn off Vale

---

src/current/_includes/v23.1/cdc/schedule-query-example.md
src/current/_includes/v23.2/cdc/schedule-query-example.md

This removes an `AS {label}` from a CDC query example that did not show up in CSV message format.

Remove irrelevant label from cdc query example

---

src/current/_config_cockroachdb.yml
src/current/_includes/releases/current-cloud-version.md
src/current/_includes/releases/v23.1/v23.1.11.md

This release will now be available on all Serverless clusters and select Dedicated clusters.
Build preview links:
- https://deploy-preview-17922--cockroachdb-docs.netlify.app/docs/releases/cloud
- https://deploy-preview-17922--cockroachdb-docs.netlify.app/docs/releases/v23.1

Phase 2 admonition for v23.1.11

---

src/current/v23.1/monitor-cockroachdb-with-prometheus.md
src/current/v23.2/monitor-cockroachdb-with-prometheus.md

Addresses DOC-8873
(1) Updated Monitor CockroachDB with Prometheus page, (a) corrected links to Grafana dashboards and (b) fixed formatting error.

DOC-8873: Links to Grafana Dashboards are outdated

---

src/current/_includes/v23.2/cdc/pubsub-performance-setting.md
src/current/_includes/v23.2/cdc/webhook-performance-setting.md
src/current/v23.2/advanced-changefeed-configuration.md
src/current/v23.2/changefeed-examples.md
src/current/v23.2/changefeed-sinks.md
src/current/v23.2/create-changefeed.md

Fixes DOC-8670
In v23.1 we added a cluster setting that enables some performances enhancements for webhook & pub/sub. This setting was not enabled by default and customers needed to flip the switch to see the improvements. In the docs, we added notes in all the relevant sink spaces to direct customers to enable this setting. 
For v23.2, we have enabled this setting by default. Because we don't foresee any need for a customer to interact with this setting right now, we're removing mention of this from the docs.

Remove reference to webhook and pub/sub performance cluster setting

---

src/current/_data/releases.yml
src/current/_includes/releases/v23.2/v23.2.0-alpha.2.md

[DOC-7783] Release notes for v23.2.0-alpha.2
Initial commit represents the generated notes for SHA `10d282dc9045ebb8b3faaf891706a13b08177949` before edits
Latest commit updates the hash to `2111b61b2d7c789bc03b1e9392062df80c779075` with a copyedit for the new notes.
Preview: [releases/v23.2.md](https://deploy-preview-17929--cockroachdb-docs.netlify.app/docs/releases/v23.2.html)

[DOC-7783] Release notes for v23.2.0-alpha.2

---

src/current/v23.1/cdc-queries.md
src/current/v23.1/row-level-ttl.md
src/current/v23.2/cdc-queries.md
src/current/v23.2/row-level-ttl.md

Fixes DOC-8334
Adds a couple of examples using CDC queries and information around referencing rows that have expired with row-level TTL in a table.

Add guidance on filtering changefeed messages for TTL deletes

---

src/current/_includes/v22.2/misc/basic-terms.md
src/current/_includes/v22.2/misc/database-terms.md
src/current/_includes/v23.1/misc/basic-terms.md
src/current/_includes/v23.1/misc/database-terms.md
src/current/_includes/v23.2/misc/basic-terms.md
src/current/_includes/v23.2/misc/database-terms.md
src/current/v22.2/architecture/glossary.md
src/current/v22.2/architecture/overview.md
src/current/v22.2/architecture/reads-and-writes-overview.md
src/current/v23.1/architecture/glossary.md
src/current/v23.1/architecture/overview.md
src/current/v23.1/architecture/reads-and-writes-overview.md
src/current/v23.2/architecture/glossary.md
src/current/v23.2/architecture/overview.md
src/current/v23.2/architecture/reads-and-writes-overview.md

This page is our 4th-most-visited page overall, and it needed some attention.
- Add more links to terms and things that have docs now.  Most didn't have docs yet when this page was added.
- Move the giant glossaries to the bottom of the page so readers can get through the **Overview** section first (that section is kind of the whole point of this page's existence, and sticking a glossary in the middle was breaking the flow of the page).

Update Architecture Overview

---

src/current/cockroachcloud/export-logs.md

Addresses DOC-8236
(1) Updated Export Logs From a CockroachDB Dedicated Cluster page, (a) added omitted_channels parameter and (b) corrected json code samples by adding quotes.

DOC-8236: Docs for Improve reliability and error handling for log export for cloud clusters

---

src/current/_includes/v23.1/misc/enterprise-features.md
src/current/_includes/v23.1/sidebar-data/self-hosted-deployments.json
src/current/_includes/v23.2/misc/enterprise-features.md
src/current/_includes/v23.2/sidebar-data/self-hosted-deployments.json
src/current/v23.1/cockroachdb-feature-availability.md
src/current/v23.1/role-based-audit-logging.md
src/current/v23.1/sql-audit-logging.md
src/current/v23.2/cockroachdb-feature-availability.md
src/current/v23.2/role-based-audit-logging.md
src/current/v23.2/sql-audit-logging.md

Addresses: DOC-8060
(1) Added Role-based SQL Audit Logging page. (2) Updated Enterprise Features page with Role-based SQL Audit Logging link. (3) Renamed SQL Audit Logging page to Table-based SQL Audit Logging. (4) Updated Self-Hosted Deployments sidebar, added Role-based SQL Audit Logging link and renamed Table-based SQL Audit Logging link. (5) Updated 23.2 files. (6) Updated Feature Availability page, in Preview section, added Role-based SQL Audit Logging.

DOC-8060: Docs for SQL Audit Logs: Restrict SQL activity logging by user/role

---

src/current/_plugins/versions/generator.rb

Fix a change made [here](https://github.com/cockroachdb/docs/pull/17948/files#diff-961682e1b5333c244149ef538764cb6496b45fe3ae780925271e84b2f27797f0R99) where the ruby function `compact` appears to have a typo in it, which may have led to search indexing issues discussed [here](https://cockroachlabs.slack.com/archives/C03TH7EEMAA/p1696635329799879) (private to Cockroach Labs).

Fix typo in compact function

---

src/current/_plugins/versions/generator.rb

Reverting as this did not address the described problem. We now believe the problem may be related to a build timeout caused by #17948, so will revert that next.

Revert "Fix typo in compact function"

---

src/current/v23.1/change-data-capture-overview.md
src/current/v23.2/change-data-capture-overview.md

This is a quick fix to add the recently published `parquet` format to the list on the overview pages.

Add parquet format to cover pages for CDC

---

src/current/_data/releases.yml

macOS ARM download links should still be **experimental** rather than **limited access**. In [Prod](https://www.cockroachlabs.com/docs/releases/?filters=mac#testing-releases), they are currently marked as **both**.  It's intended that **both** should be a possibility, but it's not correct here.
Relates to https://github.com/cockroachdb/ed-tools/pull/50
(which fixes the logic bug, hopefully)

Fix macOS ARM download label on 23.2.0-alpha.2 and 23.2.0-alpha.3

---

src/current/_includes/v23.2/ui/ui-metrics-navigation.md
src/current/v23.2/ui-cdc-dashboard.md
src/current/v23.2/ui-distributed-dashboard.md
src/current/v23.2/ui-hardware-dashboard.md
src/current/v23.2/ui-overload-dashboard.md
src/current/v23.2/ui-overview-dashboard.md
src/current/v23.2/ui-queues-dashboard.md
src/current/v23.2/ui-replication-dashboard.md
src/current/v23.2/ui-runtime-dashboard.md
src/current/v23.2/ui-slow-requests-dashboard.md
src/current/v23.2/ui-sql-dashboard.md
src/current/v23.2/ui-storage-dashboard.md
src/current/v23.2/ui-ttl-dashboard.md

As part of work for the Physical Cluster Replication docs, there will be a monitoring page that includes information on the Physical Replication dashboard. As part of the v23.2 release, we do not want to add a fully fledged dashboard page to the UI section as only as small number of customers will be using this feature. Instead, we are keeping this dashboard info to a new monitoring page in the upcoming Disaster Recovery / Physical Cluster Replication section in the docs (for now).
This PR removes the ## Dashboard Navigation heading that was including in an include file, which provides instructions that would be good to reuse on the PCR monitoring page (without the heading). Ultimately, removing the heading makes this include a little more flexible.

Remove heading from UI include file for reuse without heading

---

src/current/v22.2/licensing-faqs.md
src/current/v23.1/licensing-faqs.md
src/current/v23.2/licensing-faqs.md

https://cockroachlabs.atlassian.net/browse/DOC-9056
Used an HTML link for the `mailto:` as the prior bullet already did this, and I'm not sure whether all our site processes  support markdown mailto links.

Replace link to trial license form with Sales email [DOC-9056]

---

src/current/v23.1/cockroach-debug-zip.md
src/current/v23.2/cockroach-debug-zip.md

Addresses DOC-8738
(1) Updated cockroach debug zip page with cluster impact warning and recommendation to filter by time range.

DOC-8738: Warn users that generating the debug zip can degrade the cluster

---

src/current/v23.2/show-statistics.md

Addresses DOC-8929:
- `SHOW STATISTICS` creation time now displays statistics in the session time zone, if it is set
Preview
https://deploy-preview-17986--cockroachdb-docs.netlify.app/docs/dev/show-statistics#output

DOC-8929 show stats created field displays timestamptz

---

src/current/_includes/v23.1/ui/admin-access-only.md
src/current/_includes/v23.1/ui/admin-access.md
src/current/_includes/v23.2/ui/admin-access-only.md
src/current/_includes/v23.2/ui/admin-access.md
src/current/v23.1/enable-node-map.md
src/current/v23.1/ui-databases-page.md
src/current/v23.1/ui-debug-pages.md
src/current/v23.1/ui-key-visualizer.md
src/current/v23.1/ui-sessions-page.md
src/current/v23.2/enable-node-map.md
src/current/v23.2/ui-databases-page.md
src/current/v23.2/ui-debug-pages.md
src/current/v23.2/ui-key-visualizer.md
src/current/v23.2/ui-sessions-page.md

Addresses DOC-9074
(1) Updated Sessions page to mention VIEWREDACTED privilege. (2) Updated admin-access include file to mention VIEWACTIVITY and VIEWREDACTED for Statements, Transactions and Insights pages. (3) Added admin-access-only include file. (4) Updated Databases, Key Visualizer, Debug, Enable NodeMap pages, to use admin-access-only include file.

DOC-9074: Fix Incorrect note on privileges needed to access DB Console pages

---

src/current/cockroachcloud/alerts-page.md
src/current/cockroachcloud/authorization.md
src/current/cockroachcloud/cluster-management.md

[DOC-8898] Document new role capabilities:
- Org Admins receive email notifications about patch upgrades
- Cluster admins and cluster operators can set maintenance windows
Also convert tabs to spaces and add some cross-references
[src/current/cockroachcloud/alerts-page.md](https://deploy-preview-18005--cockroachdb-docs.netlify.app/docs/cockroachcloud/alerts-page.html)
[src/current/cockroachcloud/authorization.md](https://deploy-preview-18005--cockroachdb-docs.netlify.app/docs/cockroachcloud/authorization.html)
[src/current/cockroachcloud/cluster-management.md](https://deploy-preview-18005--cockroachdb-docs.netlify.app/docs/cockroachcloud/cluster-management.html)

[DOC-8898] Document new role capabilities

---

src/current/_includes/v23.2/sidebar-data/reference.json
src/current/v23.2/column-level-encryption.md
src/current/v23.2/encryption.md

Fixes DOC-8057
- Add a new page, 'Column Level Encryption', to the security reference
section
- Add links to the new page from our existing Encryption at Rest docs

Add docs on column-level encryption

---

src/current/_includes/v22.2/orchestration/kubernetes-limitations.md
src/current/_includes/v22.2/orchestration/start-cockroachdb-helm-insecure.md
src/current/_includes/v22.2/orchestration/start-cockroachdb-helm-secure.md
src/current/_includes/v23.1/orchestration/kubernetes-limitations.md
src/current/_includes/v23.1/orchestration/start-cockroachdb-helm-insecure.md
src/current/_includes/v23.1/orchestration/start-cockroachdb-helm-secure.md
src/current/_includes/v23.2/orchestration/kubernetes-limitations.md
src/current/_includes/v23.2/orchestration/start-cockroachdb-helm-insecure.md
src/current/_includes/v23.2/orchestration/start-cockroachdb-helm-secure.md
src/current/v22.2/secure-cockroachdb-kubernetes.md
src/current/v23.1/secure-cockroachdb-kubernetes.md
src/current/v23.2/secure-cockroachdb-kubernetes.md

Updating documentation to include cert-manager as an option and option of choice for Certificate Management in Kubernetes using Helm, further updating the documents as this now brings support for all versions of k8s including 1.22 and later.

Cert manager changes

---

src/current/v23.1/show-sessions.md
src/current/v23.1/show-statements.md
src/current/v23.2/show-sessions.md
src/current/v23.2/show-statements.md

Addresses DOC-8509:
- `SHOW STATEMENTS` and `SHOW SESSIONS` commands now display timestamps using the session's timezone setting
Preview
https://deploy-preview-17985--cockroachdb-docs.netlify.app/docs/dev/show-sessions#response

DOC-8509 display timestamptz for the respective sessions

---

src/current/v23.2/cockroach-debug-merge-logs.md
src/current/v23.2/configure-logs.md

Addresses DOC-8104 DOC-8102 DOC-8103
(1) Updated Configure Logs page, added Set timezone section. (2) Updated cockroach debug merge-logs page, added required format option and considerations section.

DOC-8104: PR #104265 - util/log: timezone support for formats crdb-v1 and crdb-v2

---

src/current/_includes/v23.1/sidebar-data/troubleshooting.json
src/current/_includes/v23.2/sidebar-data/troubleshooting.json
src/current/cockroachcloud/export-metrics.md
src/current/v23.1/differences-in-metrics-between-third-party-monitoring-integrations-and-db-console.md
src/current/v23.1/monitor-cockroachdb-with-prometheus.md
src/current/v23.1/third-party-monitoring-tools.md
src/current/v23.1/troubleshooting-overview.md
src/current/v23.2/differences-in-metrics-between-third-party-monitoring-integrations-and-db-console.md
src/current/v23.2/monitor-cockroachdb-with-prometheus.md
src/current/v23.2/third-party-monitoring-tools.md
src/current/v23.2/troubleshooting-overview.md

Addresses DOC-9008
(1) Added Differences in Metrics between Third-Party Monitoring Integrations and DB Console page with images. (2) Updated Troubleshooting sidebar. (3) Updated troubleshooting overview page. (5) Added See Also links on Third-party Monitoring Integrations, Prometheus, and Export Metrics pages. (6) Updated 23.2 files.

DOC-9008 Differences in Metrics Between Datadog & DB Console

---

src/current/v23.1/configure-logs.md
src/current/v23.1/logging-overview.md
src/current/v23.2/configure-logs.md
src/current/v23.2/logging-overview.md

Addresses DOC-8678
(1) Updated Logging Overview page, added KV_DISTRIBUTION channel and cockroach-kv-distribution.log destination. (2) Updated Configure Logs page, added kv-distribution file-group to default configuration.

DOC-8678: Feedback: Logging Overview - Document the KV_DISTRIBUTION channel

---

src/current/v23.1/use-cloud-storage.md
src/current/v23.2/use-cloud-storage.md

We do not recommend `self` in most cases and showing it as an example gives it more exposure than we really desire.
We especially want to be sure that anyone using "self" has read and understood the footnote under "considerations". This note was previously linked after the example but that relied on one clicking it and reading it, so a user could presumably discover and start using `self` without reading the note.
After this change, the only mention of `self` is in the footnote, so only users who read the note should be aware it is an option, specifically in the configuration where it is a valid option.

remove `self` nodelocal examples

---

src/current/v22.2/alter-changefeed.md
src/current/v23.1/alter-changefeed.md
src/current/v23.2/alter-changefeed.md

Fixes DOC-9147
You cannot alter a changefeed that uses CDC queries. This limitation was listed in the general CDC limitations and on the CDC queries page. However, this was missed from the alter changefeed page. This is a quick fix to remedy.

Add alter changefeed limitation for CDC queries

---

src/current/v23.1/role-based-audit-logging.md
src/current/v23.2/role-based-audit-logging.md

Addresses DOC-7866
Updated Role-based audit logging page, added section for sql.log.user_audit.reduced_config.enabled.

DOC-7866: PR #103759 - sql: add `sql.log.user_audit.reduced_config.enabled` to support single role checks for role-based audit logs 

---

src/current/v23.1/advanced-changefeed-configuration.md
src/current/v23.2/advanced-changefeed-configuration.md

Quick fix to an incorrect setting name on the Advanced changefeed config page

Quick fix typo on cluster setting Advanced Changefeed page

---

src/current/cockroachcloud/upgrade-to-v23.1.md
src/current/v22.2/upgrade-cockroach-version.md
src/current/v23.1/upgrade-cockroach-version.md
src/current/v23.2/upgrade-cockroach-version.md

[DOC-9200] Document recommendation to reset SQL statistics before upgrading to v23.1
- Remove redundant 'Review Breaking Changes' sections from v23.1 and v23.2 upgrade topics
- Move 'Review Breaking Changes' section in v22.2 upgrade topic earlier
- Also add the advice to reset SQL statistcs in the CockroachDB Cloud  'Upgrade to v23.1' topic
**Previews**
[src/current/cockroachcloud/upgrade-to-v23.1.md](https://deploy-preview-18072--cockroachdb-docs.netlify.app/docs/cockroachcloud/upgrade-to-v23.1.html)
[src/current/v22.2/upgrade-cockroach-version.md](https://deploy-preview-18072--cockroachdb-docs.netlify.app/docs/v22.2/upgrade-cockroach-version.html)
[src/current/v23.1/upgrade-cockroach-version.md](https://deploy-preview-18072--cockroachdb-docs.netlify.app/docs/v23.1/upgrade-cockroach-versi …

[DOC-9200] Document recommendation to reset SQL statistics before upgrading to v23.1

---

src/current/v22.2/show-statistics.md
src/current/v23.1/show-statistics.md
src/current/v23.2/show-statistics.md

also see: https://github.com/cockroachdb/cockroach/pull/114166
This sentence in the docs was incorrect. In order to run this command, the user must have any privilege on the table being inspected.

Fix "required privileges" for SHOW STATISTICS

---

src/current/cockroachcloud/regions.md

Added `us-east-1` as an AWS region for Dedicated as per this [Slack comment](https://cockroachlabs.slack.com/archives/C01PHNMUFLN/p1700499556821929)

Updated AWS regions for CockroachDB Cloud

---

src/current/_includes/releases/v23.2/v23.2.0-alpha.1.md
src/current/v23.2/ui-cdc-dashboard.md

Fixes DOC-9246
Updates include:
- Adds a callout to the Changefeed Dashboard page where the name had changed on two graphs.
- Also, added to "New in v23.2" flags to graphs that are completely new for v23.2 — flags were missed in the original docs page publish
- Included an additional sentence of detail to the release note

Add a callout to the CDC dashboard graph renames

---

src/current/_data/releases.yml

Fix incorrect ARM metadata for Linux and Docker in v23.2.0-alpha.2+ releases, which erroneously indicated that ARM is GA for these platforms in these versions.
Relates to https://github.com/cockroachdb/ed-tools/pull/52, which adjusts the defaults in `release-notes.py` to hopefully prevent this from happening again.
Previews:
In the below, ARM is experimental for Linux and Docker v23.2.x, v23.1.x, and v22.2.12-. ARM is Limited Access for 22.2.13, and GA for v22.2.14+. ARM did not exist before v22.2.
https://deploy-preview-18090--cockroachdb-docs.netlify.app/docs/releases/ 
https://deploy-preview-18090--cockroachdb-docs.netlify.app/docs/releases/v23.2#v23-2-0-alpha-7
https://deploy-preview-18090--cockroachdb-docs.netlify.app/docs/releases/v23.1#v23-1-12 …

[DOC-9249] Fix ARM Linux metadata for v23.2.x

---

src/current/v23.1/export.md
src/current/v23.2/export.md

Fixes DOC-6659
This adds a paragraph to the export docs to let customers know that export will leave partially written files behind if it encounters a cancelation or failure. Also a couple of bullet points to consider alternatives.

Clarify incomplete export scenario

---

src/current/v22.2/connection-pooling.md
src/current/v23.1/connection-pooling.md
src/current/v23.2/connection-pooling.md

This page was conflating the concepts of open and active connections. They are both valuable to monitor for different reasons. With this patch, the correct metrics are described, and "active" is defined more clearly.
It also incorrectly described a metric as being "per second" when it is in fact just a count.

Fix definitions of "active" and "open" connections

---

src/current/v22.1/encryption.md
src/current/v22.2/encryption.md
src/current/v23.1/encryption.md
src/current/v23.2/encryption.md

Fixes DOC-9087
- Update the 'Encryption' page to note that because it relies on storage engine compactions, only data that is somehow touched gets encrypted. As a result, in some cases the percentage of files/bytes encrypted may not reach 100%.
- The above is applied to v22.1, v22.2, v23.1, and v23.2 docs

Explain why encryption at rest may not reach 100%

---

src/current/_includes/releases/release-downloads-docker-image.md
src/current/releases/index.md

[DOC-9251] Clarify Intel and ARM support in the Docker multi-platform image
This PR adjusts the text shown at the beginning of the Docker section and adds a "Notes" field to the Docker table to document the support level of the Intel and ARM image in each multi-platform image. Also adjusts the logic to prevent the `_limited_access` and `_experimental` fields both displaying as true.
Ref: https://cockroachlabs.slack.com/archives/CHKQGKYEM/p1700107859889549
Related change which I split off from this PR: https://github.com/cockroachdb/docs/pull/18090
Preview: 
[releases/releases.md](https://deploy-preview-18082--cockroachdb-docs.netlify.app/docs/releases/releases.html)
[src/current/releases/index.md](https://deploy-preview-18082--cockroachdb-docs.netlify.app/docs/releases/index.html)

[DOC-9251] Clarify Intel and ARM support in the Docker multi-platform image

---

src/current/releases/index.md

Ref: https://cockroachlabs.slack.com/archives/C01PHNMUFLN/p1701716727019289
macOS binaries are still experimental, but downloads should not have a popup. The popup code was inadvertently added to two areas of the index code. Code on the version-specific index is not impacted.
Preview: [src/current/releases/index.md](https://deploy-preview-18121--cockroachdb-docs.netlify.app/docs/releases/index.html)

Remove the experimental download popup from macOS links

---

src/current/_data/releases.yml
src/current/_includes/releases/v23.1/v23.1.13.md
src/current/releases/v23.1.md

Touches DOC-8127
NB. This PR is only for the Dedicated rollout targeting 2023-12-04.  Will need to make further PRs for the upcoming Serverless and, later, Self-hosted releases.

Add release notes for v23.1.13

---

src/current/_data/releases.yml

Published release notes a bit too soon. We'll bring this back shortly.

Revert v23.2.0-beta.2 by commenting out releases.yml block

---

src/current/v22.2/changefeed-messages.md
src/current/v23.1/changefeed-messages.md
src/current/v23.2/changefeed-messages.md

Fixes DOC-9221, DOC-9247
Adds a warning regarding the `__crdb__` field that is emitted in changefeed messages in Avro format.

Add warning for __crdb__ Avro schema field

---

src/current/_data/releases.yml
src/current/_includes/releases/v23.2/v23.2.0-beta.2.md

[[DOC-9307](https://cockroachlabs.atlassian.net/browse/DOC-9307)] Publish release notes for v23.2.0-beta.2
Reverts cockroachdb/docs#18126
Adds new notes in SHA `8497d5eb24d9ff057fc57346ab21c3d796ba05be`, then copyedits them.
**Preview**: [releases/v23.2.md](https://deploy-preview-18129--cockroachdb-docs.netlify.app/docs/releases/v23.2.html)

[DOC-9307] Publish v23.2.0-beta.2 release notes

---

src/current/v23.2/physical-cluster-replication-monitoring.md

Fixes DOC-9304
Replaces the `physical_replication.frontier_lag_nanos` metric for `physical_replication.replicated_time_seconds` in the physical cluster replication docs.

Replace the lag nanos metric pcr

---

src/current/v23.1/export.md
src/current/v23.2/export.md

Fixes DOC-7861
This PR adds a brief sentence to the `EXPORT` docs following a new internal implementation which results in all columns being written as nullable.

Add sentence to export docs on nullable columns

---

src/current/cockroachcloud/export-metrics.md
src/current/v23.1/differences-in-metrics-between-third-party-monitoring-integrations-and-db-console.md
src/current/v23.2/differences-in-metrics-between-third-party-monitoring-integrations-and-db-console.md

Addresses: DOC-9195
(1) Updated Export Metrics page, added step and callout to enable percentiles. (2) Updated Differences in Metrics page, added that writing queries is not supported.

DOC-9195: Differences in Metrics Between Datadog & DB Console follow-up

---

src/current/v23.1/show-cluster-setting.md
src/current/v23.2/show-cluster-setting.md

Addresses DOC-8190
Updated SHOW CLUSTER SETTING page, added `default_value` and `origin` columns.

DOC-8190: PR #104449 - sql: add default_value and is_overridden to cluster settings

---

src/current/cockroachcloud/export-logs.md

Addresses DOC-9110
(1) Updated Export Logs From a CockroachDB Dedicated Cluster page, added note that logs are not backfilled.

DOC-9110: Feedback: Export Logs From a CockroachDB Dedicated Cluster

---

src/current/v23.1/configure-logs.md
src/current/v23.2/configure-logs.md

Addresses DOC-9265
(1) Updated Configure Logs page, Redact Logs section with recommendation to use external log collector to redact logs.

DOC-9265: Feedback: Configure CockroachDB Dedicated Logs

---

src/current/_includes/v22.2/sql/unsupported-postgres-features.md
src/current/_includes/v23.1/sql/unsupported-postgres-features.md
src/current/_includes/v23.2/sql/unsupported-postgres-features.md

We defined some builtins around pg_advisory locks, but they are no-ops, and some functions are not even defined. This commit adds this limitation to unsupported postgres features.
See https://github.com/cockroachdb/cockroach/issues/13546.

Mention that we don't support Advisory Lock Functions

---

src/current/v22.2/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
src/current/v23.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
src/current/v23.2/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md

[DOC-426] Amend the note about enabling global access
Remove the note about updating the tutorial for now. The Google documentation we link to is very thorough.

[DOC-426] Amend the note about enabling global access

---

src/current/_includes/v23.1/ui/active-statement-executions.md
src/current/_includes/v23.1/ui/active-transaction-executions.md
src/current/_includes/v23.1/ui/statements-filter.md
src/current/_includes/v23.1/ui/statements-views.md
src/current/_includes/v23.1/ui/transactions-filter.md
src/current/_includes/v23.1/ui/transactions-views.md
src/current/_includes/v23.2/ui/active-statement-executions.md
src/current/_includes/v23.2/ui/active-transaction-executions.md
src/current/_includes/v23.2/ui/statements-filter.md
src/current/_includes/v23.2/ui/statements-views.md
src/current/_includes/v23.2/ui/transactions-filter.md
src/current/_includes/v23.2/ui/transactions-views.md
src/current/cockroachcloud/statements-page.md
src/current/cockroachcloud/transactions-page.md
src/current/v23.1/ui-statements-page.md
src/current/v23.1/ui-transactions-page.md
src/current/v23.2/ui-statements-page.md
src/current/v23.2/ui-transactions-page.md

Fixed DOC-9326
(1) Updated Cloud Statements/Transactions pages to show Active Executions sections similar to Self-Hosted pages, modified pages to only have calls to include files. (2) Moved views sections from Self-Hosted pages into statements/transactions-views include files, updated links to work with Cloud pages. (3) Moved setting of link_prefix variable from statements/transactions-filter include files to statements/transaction-views include files. (4) In active-statement/transaction-executions include files, updated links to work with Cloud pages.

DOC-9326 Feedback: Statements Page and Transactions Page

---

src/current/_includes/v23.1/ui/statement-details.md
src/current/_includes/v23.1/ui/statements-table.md
src/current/_includes/v23.1/ui/transaction-details.md
src/current/_includes/v23.1/ui/transactions-table.md
src/current/_includes/v23.2/ui/statement-details.md
src/current/_includes/v23.2/ui/statements-table.md
src/current/_includes/v23.2/ui/transaction-details.md
src/current/_includes/v23.2/ui/transactions-table.md

Fixes DOC-7437
For Statements and Transactions pages, updated include files to indicate that corresponding fingerprint details page reflects specified application name and database.

DOC-7437 PR #99719 - ui: use app name of selected row when fetching fingerprint details

---

src/current/_includes/v23.1/metric-names.md
src/current/_includes/v23.2/metric-names.md

Fixes DOC-9073
On Metrics page, added sql.mem.root.current and sql.mem.root.max

DOC-9073 Update our documentation to include sql.mem.root.current metric

---

src/current/v23.1/crdb-internal.md
src/current/v23.2/crdb-internal.md

Fixes DOC-8632 DOC-6259
On crdb_internal page, (1) in statistics column section, added units, (2) fixed spelling mistakes.

DOC-8632 specify the unit for metrics in the statistics column where is not clear from the name

---

src/current/_includes/v22.2/prod-deployment/topology-recommendations.md
src/current/_includes/v23.1/prod-deployment/topology-recommendations.md
src/current/_includes/v23.2/prod-deployment/topology-recommendations.md
src/current/v22.2/cockroach-start.md
src/current/v23.1/cockroach-start.md
src/current/v23.2/cockroach-start.md

- [DOC-3439] Improve the recommendation against running multiple nodes on the same hardware
- Change the recommendation against to a "Do not" recommendation
- Split out the point about multiple disks or SSDs into a separate bullet, and also add using RAID as a possibility
- Backport to all supported versions 
This change impacts many different pages that use this include. See https://github.com/cockroachdb/docs/pull/18171#issuecomment-1863629813 for links to preview the changes in context.
- [DOC-6001] Give more context about using multiple stores for a single node

[DOC-3439][DOC-6001] Improve recommendations about node per hardware and storage per node

---

src/current/v23.2/physical-cluster-replication-monitoring.md

Fixes DOC-9168
This PR adds a reference (on the physical cluster replication page) to metrics during the cutover period for the primary and standby clusters.
This came about after a customer asked what happens to metrics in the case where they fail over and then fail back to the primary cluster.

Add reference to metrics on primary and standby during cutover

---

src/current/_includes/v23.1/sidebar-data/cloud-deployments.json
src/current/_includes/v23.2/sidebar-data/cloud-deployments.json
src/current/cockroachcloud/cluster-management.md
src/current/cockroachcloud/create-your-cluster.md
src/current/cockroachcloud/frequently-asked-questions.md
src/current/cockroachcloud/upgrade-policy.md
src/current/cockroachcloud/upgrade-to-v23.1.md
src/current/cockroachcloud/upgrade-to-v23.2.md
src/current/v23.1/restoring-backups-across-versions.md
src/current/v23.2/restoring-backups-across-versions.md

[DOC-9458] Update Upgrade Policy page title
Also updates link text in other CC pages and CRDB v23.1+ pages
[src/current/cockroachcloud/cluster-management.md](https://deploy-preview-18192--cockroachdb-docs.netlify.app/docs/cockroachcloud/cluster-management.html)
[src/current/cockroachcloud/create-your-cluster.md](https://deploy-preview-18192--cockroachdb-docs.netlify.app/docs/cockroachcloud/create-your-cluster.html)
[src/current/cockroachcloud/frequently-asked-questions.md](https://deploy-preview-18192--cockroachdb-docs.netlify.app/docs/cockroachcloud/frequently-asked-questions.html)
[src/current/cockroachcloud/upgrade-policy.md](https://deploy-preview-18192--cockroachdb-docs.netlify.app/docs/cockroachcloud/upgrade-policy.html)
[src/current/cockroachcloud/upgrade-to-v23.1.md](https://deploy …

[DOC-9458] Update Upgrade Policy page title

---

src/current/_includes/releases/release-downloads-docker-image.md
src/current/releases/index.md

Previously, to suppress download links, you had to remove the release entry from `_data/releases.yml`, which means that the logic that builds the tables in `releases/index.html` can't include Cloud-only releases. Instead, a reader must either be given the direct link or must construct it by going to a different page and manually editing the URL. In addition, the writer must manually add or remove a Liquid include on one line, a  `unless` block in a separate area, and a Liquid admonition. This is all pretty prone to error and. confusing.
This PR introduces three new optional per-release fields in `_data/releases.yml`:
- `cloud_only`: If `true`, suppress download links and show explanatory messaging.
- `cloud_only_message`: If `cloud_only` is `true`, this is displayed at the top of the …

Add YAML field and Liquid logic to better support a Cloud-only release

---

src/current/_includes/v23.1/cdc/lagging-ranges.md
src/current/_includes/v23.2/cdc/lagging-ranges.md
src/current/v23.1/advanced-changefeed-configuration.md
src/current/v23.1/monitor-and-debug-changefeeds.md
src/current/v23.2/advanced-changefeed-configuration.md
src/current/v23.2/monitor-and-debug-changefeeds.md

Fixes DOC-7674
Adds a Monitor Latency section to the monitoring page for changefeeds. This includes information on:
- `admit_latency` and `commit_latency`
- `lagging_ranges`

Add monitor latency section to group recommendations on changefeed latency

---

src/current/v23.1/take-full-and-incremental-backups.md
src/current/v23.2/take-full-and-incremental-backups.md

Fixes DOC-9475
This is a quick fix to some outdated language referring to scheduled backups. "Automated backups" could cause confusion with our managed-service cloud backups, which are automatically taken for the user.

Correct the scheduled backup language automated for clarity

---

src/current/v23.2/set-up-physical-cluster-replication.md

Fixes DOC-9146
This copies the multi-region and topology limitation from the known limitation section on the PCR overview page to the tutorial page. No new content here really, just ensuring this is visible to users setting up PCR with the tutorial.

Add prereq note on multi-region limitation for physical cluster replication

---

src/current/v23.2/physical-cluster-replication-monitoring.md
src/current/v23.2/physical-cluster-replication-overview.md
src/current/v23.2/set-up-physical-cluster-replication.md

Fixes DOC-8268
This adds a short example to the PCR Monitoring page on verifying data between the primary and standby clusters.
Like the whole of the PCR feature, data verification is very much in preview. Here, we wanted to emphasize that this tool is very much in active development (hence the extended preview message in its section). 
PR includes references across the PCR docs to data verification.

Add docs for pcr data verification

---

src/current/v22.2/ui-ttl-dashboard.md
src/current/v23.1/ui-ttl-dashboard.md
src/current/v23.2/ui-ttl-dashboard.md

There can be some ambiguity interpreting what the "rows selected" metric does on the processing rate graph for the TTL dashboard metrics. This commit clarifies any ambiguity~

TTL dashboard metric clarification

---

src/current/_includes/releases/v23.1/v23.1.0-alpha.8.md

Edited a release note that referred to mux rangefeeds being "enabled", which may have caused confusion as they are no longer enabled by default. The original release note was edited "too much" and moved away from the meaning.

Edit release notes for v23.1.0-alpha.8 for clarity on mux rangefeed

---

src/current/v23.2/architecture/transaction-layer.md

In reorganizing #18098 I moved some content from the Read Committed feature doc to the architecture (Transaction Layer) doc. 
- Added some links back to the Read Committed doc.
- Tweaked one sentence about interleaved statements to be consistent with how the main doc was updated during review (i.e., removed the word "blocking").

add links, make wording consistent with feature doc

---

src/current/v22.2/alter-backup-schedule.md
src/current/v23.1/alter-backup-schedule.md
src/current/v23.2/alter-backup-schedule.md

Fixes DOC-9531
The `first_run` and `ignore_existing_backups` schedule options were included on the `ALTER BACKUP SCHEDULE` page. This is incorrect because users can only pass these options at schedule creation with `CREATE SCHEDULE FOR BACKUP`. For now, removed the "schedule options" table include from the `ALTER` page, and instead placed the table directly. This will make for easier maintenance.

Fix schedule options `first_run` + `ignore_existing_backups` for alter backup schedule

---

src/current/v22.2/row-level-ttl.md
src/current/v23.1/row-level-ttl.md
src/current/v23.2/row-level-ttl.md

Fixes [DOC-9338](https://cockroachlabs.atlassian.net/browse/DOC-9338) by updating ~all TTL examples to set the `ttl_job_cron` value to `@daily`, since the default (`@hourly`) is really too short.
Fixes [DOC-8836](https://cockroachlabs.atlassian.net/browse/DOC-8836) (for v23.2)
Touches the obvious/easy parts of [DOC-9443](https://cockroachlabs.atlassian.net/browse/DOC-9443) (TIMESTAMP -> TIMESTAMPTZ)
NB. A subset of the v23.2 changes were also ported to v22.2 and v23.1

Update Row-level TTL cron job durations, etc.

---

src/current/v21.2/timestamp.md
src/current/v22.1/timestamp.md
src/current/v22.2/timestamp.md
src/current/v23.1/timestamp.md
src/current/v23.2/timestamp.md

Starting in v21.2 our documentation incorrectly noted the minimum
supported `TIMESTAMP` value. This commit fixes the error.
defaultdb> SELECT '4714-11-24 00:00:00+00:00 BC'::TIMESTAMP;
timestamp
--------------------------
4714-11-24 00:00:00 BC
(1 row)
defaultdb> SELECT '4714-11-24 00:00:00+00:00 BC'::TIMESTAMP - '1 millisecond'::INTERVAL;
ERROR: timestamp "-4713-11-23T23:59:59Z" exceeds supported timestamp bounds
SQLSTATE: 22009

Fix minimum timestamp

---

src/current/_includes/v23.2/sidebar-data/self-hosted-deployments.json

The Backup and Restore Overview page was not showing in the nav, this was due to a typo in the sidebar data file.

Correct the sidebar data typo for back and restore overview

---

src/current/v22.2/build-a-go-app-with-cockroachdb.md
src/current/v23.1/build-a-go-app-with-cockroachdb.md
src/current/v23.2/build-a-go-app-with-cockroachdb.md

This step is no longer necessary. Due to changes in
https://github.com/cockroachlabs/example-app-go-pgx/pull/8
it results in the following error message:
go: /Users/rloveland/work/code/example-app-go-pgx/go.mod already exists
Relates to DOC-9584

Update go pgx tutorial to remove `go mod init`

---

src/current/v22.2/performance-best-practices-overview.md
src/current/v23.1/performance-best-practices-overview.md
src/current/v23.2/performance-best-practices-overview.md

Recommend `disallow_full_table_scans` session var

---

src/current/advisories/a104309.md

Technical Advisory 104309
Preview: [src/current/advisories/a104309.md](https://deploy-preview-18309--cockroachdb-docs.netlify.app/docs/advisories/a104309.html)

Technical Advisory 104309

---

src/current/_data/releases.yml

ARM on Linux and Docker is GA for 23.1.16
Relates to https://github.com/cockroachdb/ed-tools/pull/54 which updates the release-note script defaults
Ref: [DOC-8595] 
https://deploy-preview-18330--cockroachdb-docs.netlify.app/docs/releases/#v23-1
https://deploy-preview-18330--cockroachdb-docs.netlify.app/docs/releases/v23.1#v23-1-16

ARM on Linux and Docker is GA for 23.1.16

---

src/current/v23.1/create-schedule-for-changefeed.md
src/current/v23.2/create-schedule-for-changefeed.md

Fixes DOC-9702
This PR corrects a bug on `CREATE SCHEDULE FOR CHANGEFEED` page where the table name was missing from the statement.
Also, added:
- a schedule label to the CDC query example. (Not incorrect, but preferable)
- output to the first example to show that the `initial_scan = 'only'` option is added to the create statement for scheduled changefeeds without the user needing to include it.

Correct the syntax on the create schedule for changefeed page

---

src/current/v22.2/alter-table.md
src/current/v23.1/alter-table.md
src/current/v23.2/alter-table.md

Fixes DOC-9537
NB. This limitation applies to v22.2, v23.1, and v23.2

Add new limitation for ALTER COLUMN TYPE

---

src/current/cockroachcloud/use-managed-service-backups.md

Fixes DOC-9798
This is a quick fix to the Managed-service backup page that was out of date re changes to the Backup UI page. Have removed the rows and size descriptions here.
Note: The `rows` column from the UI has not yet been removed (as of March 5, 2024), however there is a bug that is showing `0` incorrectly. Therefore, we have decided it is best to remove this from docs for now.
https://deploy-preview-18336--cockroachdb-docs.netlify.app/docs/cockroachcloud/use-managed-service-backups.html?filters=dedicated

Remove reference to row column on the CC Console Backup UI page

---

src/current/advisories/a104309.md

Amend A104309 to note that CockroachDB issue #119536 is now fixed
Preview: https://deploy-preview-18347--cockroachdb-docs.netlify.app/docs/advisories/a104309

Amend A104309 to note that CockroachDB issue #119536 is now fixed

---

src/current/v23.1/show-sessions.md
src/current/v23.1/show-statements.md
src/current/v23.2/show-sessions.md
src/current/v23.2/show-statements.md

This updates the docs to align with the intended behavior, which was most recently fixed by https://github.com/cockroachdb/cockroach/pull/119820.

Fix required privileges for SHOW SESSIONS/STATEMENTS

---

src/current/v23.1/restore.md
src/current/v23.2/restore.md

Fixes DOC-9799
`RESTORE TABLE` can also restore sequences. Although we had docs on object dependencies that includes sequences, we did not mention them in the general parameters and functional details sections.

Include sequences in the list of restore targets

---

src/current/v22.2/cockroach-start-single-node.md
src/current/v23.1/cockroach-start-single-node.md
src/current/v23.2/cockroach-start-single-node.md

[DOC-9433] Document antipatterns for single-node clusters
[src/current/v22.2/cockroach-start-single-node.md](https://deploy-preview-18361--cockroachdb-docs.netlify.app/docs/v22.2/cockroach-start-single-node.html)
[src/current/v23.1/cockroach-start-single-node.md](https://deploy-preview-18361--cockroachdb-docs.netlify.app/docs/v23.1/cockroach-start-single-node.html)
[src/current/v23.2/cockroach-start-single-node.md](https://deploy-preview-18361--cockroachdb-docs.netlify.app/docs/v23.2/cockroach-start-single-node.html)

[DOC-9433] Document antipatterns for single-node clusters

---

src/current/cockroachcloud/stream-changefeed-to-snowflake-aws.md

There is duplication in step numbering on the Snowflake tutorial page. This PR corrects that.

Correct step numbers on changefeed snowflake tutorial page

---

src/current/_includes/v22.2/sql/privileges.md
src/current/_includes/v23.1/sql/privileges.md
src/current/_includes/v23.2/sql/privileges.md
src/current/_includes/v24.1/sql/privileges.md

Fixes DOC-9877
Corrects the supported privileges table on the authorization page for `RESTORE`. The `RESTORE` privilege can only be granted at the database or system level. Added link to the `RESTORE` required privileges section on the SQL page.

Correct the supported privileges table for restore privilege levels

---

.gitignore

With recent macOS and Xcode and our toolchain, you now need to run this command before `bundle install`:
```
bundle config build.cbor --with-cflags="-Wno-incompatible-function-pointer-types"
bundle config build.posix-spawn --with-cflags="-Wno-incompatible-function-pointer-types"
```
After you run that plus `bundle install`, a new file is created in the repo, `.bundle/config`. This is a local configuration file that should not make it into the repo, I guess.

Add .bundle/config to .gitignore

---

src/current/_includes/releases/v23.1/v23.1.7.md
src/current/_includes/releases/v23.2/v23.2.3.md

Fixes DOC-9805
A couple of release notes relating to changefeeds were missed from the original eng PR, adding them to the release note pages manually.

Add missing changefeed release notes to v23.1 & v23.2

---

src/current/_data/releases.yml

Fixes DOC-9904
In releases.yml, removed cloud lines from v23.2.4 to enable download of self-hosted binaries.
rendered preview: https://deploy-preview-18471--cockroachdb-docs.netlify.app/docs/releases/v23.2#v23-2-4

v23.2.4 self-hosted binary release

---

src/current/v24.1/cockroachdb-feature-availability.md
src/current/v24.1/monitor-and-debug-changefeeds.md

Fixes DOC-10016
This removes the preview label from changefeed metrics labels in v24.1.

Remove the preview label from changefeed metrics labels

---

src/current/v24.1/changefeed-sinks.md

Fixes DOC-6745
This PR adds documentation for the `ClientID` field in the `kafka_sink_config` option. This allows users to specify a client ID they have set in their Kafka server configuration with a Kafka quota and then create a changefeed with that ID reference.
[Changefeed Sinks page](https://deploy-preview-18447--cockroachdb-docs.netlify.app/docs/v24.1/changefeed-sinks.html)
Added details to the Changefeed Sinks page, more specifically the Kafka Sink Configuration section.

Add kafka_sink_config clientID field for Kafka quotas

---

src/current/v23.1/take-locality-restricted-backups.md
src/current/v23.2/take-locality-restricted-backups.md
src/current/v24.1/take-locality-restricted-backups.md

Fixes DOC-8582
The locality hierarchy for the syntax description was not 100% clear on this page. The example used `region,cloud`, which was also confusing as we describe a most inclusive to least inclusive locality hierarchy through our node startup docs. 
This PR updates that example to more descriptive and includes specific example values within the syntax for clarity.

Update the execution locality example for cloud/region locality tiers

---

src/current/v24.1/ui-sql-dashboard.md

Fixes DOC-9636
(1) In ui-sql-dashboard.md, (a) modified description of Full Table/Index Scans to specify non-negative rate, (b) added link to Statements page filter, (c) fixed typo in description for the Connection Latency.
rendered preview: [SQL Dashboard page](https://deploy-preview-18491--cockroachdb-docs.netlify.app/docs/v24.1/ui-sql-dashboard.html)

DOC-9636 PR #118787 - ui: take non-negative derivative of full scan chart

---

src/current/_includes/releases/v24.1/v24.1.0-alpha.5.md

Fixes DOC-10153
In v24.1.0-alpha.5.md, fixed formatting of 2 release notes.

DOC-10153 Fix release note formatting in v24.1.0-alpha.5

---

src/current/_data/releases.yml

- Update v23.1.13:
- Mark ARM as NOT experimental
- Update v23.1.20:
- Mark ARM as NOT experimental
- Mark this as an LTS release

Update v23.1.13 and v23.1.20 release metadata

---

src/current/_includes/releases/v23.1/v23.1.20.md

23.1.20 landed simultaneous to recent changes to the display of downloads, and missed being updated to use the new include, causing the old download buttons to look ugly instead of using the new table.

Use the new download table include for 23.1.20

---

src/current/_includes/releases/cloud/2021-12-06.md
src/current/_includes/releases/cloud/2022-11-07.md
src/current/_includes/releases/cloud/2023-09-08.md
src/current/cockroachcloud/architecture.md
src/current/cockroachcloud/create-your-cluster.md

Removed mentions of machine types from CockroachCloud docs and release notes.
Addresses [DOC-9953](https://cockroachlabs.atlassian.net/browse/DOC-9953) and [DOC-10181](https://cockroachlabs.atlassian.net/browse/DOC-10181)

Removed mentions of Cloud machine types

---

src/current/_data/releases.yml

Fixes DOC-10138
In releases.yml for v23.1.21, removed 3 cloud fields to show download links
Rendered preview [releases/v23.1.html#v23.1.21](https://deploy-preview-18546--cockroachdb-docs.netlify.app/docs/releases/v23.1.html#v23-1-21)

DOC-10138 v23.1.21 release notes SH download links

---

src/current/v24.1/cockroach-start.md

Fixes DOC-10268
Followup to #18511 with the monitoring piece

Add docs on monitoring WAL failover

---

src/current/v24.1/set-up-physical-cluster-replication.md

Quick fix to the standby cluster creation portion. The setup page noted that the sql prompt would include the word `system` on the standby cluster. This is no longer true when a user first initializes a cluster with `--virtualized-empty`, it will look more like `root@{node IP}:26257/defaultdb>`
To avoid confusion, this PR removes that line from the tutorial. (Note that this line still exists in the docs for the primary cluster started with `virtualized` as the prompt includes `system` still in v24.1

Small fix to prompt note on standby v24.1 virtualized-empty PCR

---

src/current/_includes/v24.1/physical-replication/fast-cutback-syntax.md
src/current/v24.1/cutover-replication.md
src/current/v24.1/physical-cluster-replication-overview.md
src/current/v24.1/set-up-physical-cluster-replication.md

Fixes DOC-9774
This PR adds the `encode-uri` command to the pcr documentation as an alternative to copying certificates between clusters. 
Right now, we're not including a reference page for this command as the interface might be consolidated with another command.
Refer to the Files Changed box below for rendered docs page previews of the changes.

Update pcr guides to use encode-uri cli for managing certificates

---

src/current/_includes/releases/v23.1/v23.1.0.md
src/current/_includes/releases/v24.1/v24.1.0-alpha.1.md
src/current/_includes/releases/v24.1/v24.1.0.md
src/current/v24.1/licensing-faqs.md

[DOC-10090] v24.1.0 deprecations and backward-incompatible changes
[DOC-10093] v24.1.0 licensing updates
- Also fix a display bug in v23.1.0 release notes
Relates to [DOC-10061]
Preview: [releases/v24.1.md](https://deploy-preview-18530--cockroachdb-docs.netlify.app/docs/releases/v24.1.html)

[DOC-10090][DOC-10093] v24.1.0 deprecations, backward-incompatible changes, licensing updates

---

src/current/cockroachcloud/export-metrics.md

Fixes DOC-9690
In export-metrics.md, removed Preview note for Prometheus.
Rendered preview: [Enable metrics export for Prometheus](https://deploy-preview-18585--cockroachdb-docs.netlify.app/docs/cockroachcloud/export-metrics.html?filters=prometheus-metrics-export#enable-metrics-export)

DOC-9690 Docs for General Availability: Prometheus/Grafana metrics integration for Dedicated/Advanced clusters

---

src/current/v24.1/cockroachdb-feature-availability.md

Fixes DOC-10359
Adds the pcr data verification tool to the feature availability page. This PR only adds it to the feature page for v24.1 because in v23.2 the whole pcr feature was in preview (and therefore the entire doc set there). 
No actual new content here, all borrowed from the data verification section.

Add the pcr data verification tool to feature phase page v24.1

---

src/current/_includes/cockroachcloud/cdc/tutorial-privilege-check.md
src/current/_includes/v23.2/cdc/tutorial-privilege-check.md
src/current/_includes/v24.1/cdc/tutorial-privilege-check.md
src/current/cockroachcloud/stream-changefeed-to-snowflake-aws.md
src/current/v23.2/changefeed-examples.md
src/current/v23.2/connect-to-a-changefeed-kafka-sink-with-oauth-using-okta.md
src/current/v23.2/stream-a-changefeed-to-a-confluent-cloud-kafka-cluster.md
src/current/v24.1/changefeed-examples.md
src/current/v24.1/connect-to-a-changefeed-kafka-sink-with-oauth-using-okta.md
src/current/v24.1/stream-a-changefeed-to-a-confluent-cloud-kafka-cluster.md

Fixes DOC-10247
Added a short sentence before examples and tutorials begin to remind users to check they have the `CHANGEFEED` privilege before running through the steps.

Precede changefeed tutorials and examples with changefeed privilege note

---

src/current/_includes/v24.1/cdc/azure-event-hubs-uri.md
src/current/v24.1/changefeed-examples.md

Fixes DOC-10229
Added `kafka://` as an alternative scheme for Azure Event Hub sinks.

Add kafka:// uri scheme as supported for Azure Event Hub sinks

---

src/current/v23.1/cloud-storage-authentication.md
src/current/v23.2/cloud-storage-authentication.md
src/current/v24.1/cloud-storage-authentication.md

The `ASSUME_ROLE` parameter was mistakenly changed to `IAM_ROLE` in an [earlier PR](https://github.com/cockroachdb/docs/commit/38956d177209cddf377db123ed314bbb593f7027). 
The `IAM_ROLE` param doesn't exist. This PR updates those instances back to `ASSUME_ROLE`.

Correct iam parameter for cloud storage auth

---

src/current/advisories/index.md

This works around an empty row at the end of the table where 'internal/advisories.json' looks like an advisory, but isn't. It also will prevent display of an advisory missing a summary, description, or date, which would be an error.
To test: Check that [src/current/advisories/index.md](https://deploy-preview-18641--cockroachdb-docs.netlify.app/docs/advisories/index.html) has no empty row at the end of the table, and that no advisory is missing when compared to https://www.cockroachlabs.com/docs/advisories/ (there should be 63).

Add logic to avoid treating an internal include as an advisory

---

src/current/_includes/releases/v24.1/v24.1.0-alpha.5.md
src/current/_includes/v24.1/sql/privileges.md
src/current/v24.1/set-up-physical-cluster-replication.md

Fixes DOC-10381
Add shortened guide on replicating from a non-virtualized cluster to a standby cluster that has been initialized with `--virtualized-empty`. 
Added the release note for the same.

Add PCR from non-virtualized cluster to virtualized standby docs

---

src/current/v24.1/advanced-changefeed-configuration.md

Fixes DOC-9451
The `kv.rangefeed.catchup_scan_concurrency` cluster setting has been removed. This PR removes and adjusts the Advanced Changefeed Configuration page to also remove that setting. (No new content here.)

Remove kv.rangefeed.catchup_scan_concurrency cluster setting from the changefeed docs

---

src/current/v24.1/monitor-and-debug-changefeeds.md

Fixes DOC-9335
This PR adds the `emitted_batch_size` metric to the list of metrics supported by changefeed metrics labels. 
Also, alphabetized the metric label table and added the metric type.

Add emitted batch size metric label and sort table

---

src/current/_includes/sidebar-data-v23.1.json
src/current/_includes/unsupported-version.md
src/current/_includes/v23.1/sidebar-data/latest-releases.json
src/current/_layouts/page.html

[DOC-10557] Fix LTS date logic bug and 23.1 TOC
These bugs are causing the unsupported-version admonition to show up only on Release pages and not in versioned pages for any version (including EOL).
- Also add debug capability (disabled by default)
- Also propagate the combined Releases TOC entry to 23.1
This PR takes over https://github.com/cockroachdb/docs/pull/18615 (which already had review) and implements its fixes, as well as fixing a regression I somehow introduced there and making the logic just a bit more safe. I keep missing the "In LTS maintenance or LTS assistance, just show the LTS assistance" message in the logic.
**Versioned release pages**:
GA: https://deploy-preview-18667--cockroachdb-docs.netlify.app/docs/releases/v24.1 (No admonition)
GA: …

[DOC-10557] Fix LTS date logic bug and 23.1 TOC

---

src/current/_data/releases.yml

Fixes REL-984
In releases.yml, for v23.1.23, removed cloud fields and added lts:true.
Rendered previews:
- [Releases list](https://deploy-preview-18672--cockroachdb-docs.netlify.app/docs/releases/#v23-1)
- [v23.1.23](https://deploy-preview-18672--cockroachdb-docs.netlify.app/docs/releases/v23.1#v23-1-23)

REL-984 v23.1.23: [Docs] Adjust release notes for download/SH

---

src/current/v23.1/cancel-job.md
src/current/v23.1/pause-job.md
src/current/v23.1/resume-job.md
src/current/v23.2/cancel-job.md
src/current/v23.2/pause-job.md
src/current/v23.2/resume-job.md
src/current/v24.1/cancel-job.md
src/current/v24.1/pause-job.md
src/current/v24.1/resume-job.md

Fixes DOC-5624
This adds the pause/resume/cancel all diagram and syntax to the v24.1+ docs.
Refer to the Files changed box below for a rendered preview.

Add the pause resume cancel all job syntax to diagram

---

src/current/_includes/releases/v23.1/v23.1.23.md
src/current/_includes/releases/v24.1/v24.1.0-alpha.5.md

Fixes DOC-10599
This updates v24.1 and v23.1 release notes, looks like the v23.2 release for this setting isn't out yet.

Update cluster setting for bulk oracle cdc in release notes

---

src/current/v24.1/alter-backup-schedule.md
src/current/v24.2/alter-backup-schedule.md

Fixes DOC-9055
This PR adds the `EXECUTE [FULL] IMMEDIATELY` syntax to the `ALTER BACKUP SCHEDULE` SQL statement.

Add execute immediately to alter backup schedule docs

---

src/current/_data/releases.yml

[REL-1004] Followup to add Cloud-first messages to v23.2.7
Also remove an extraneous entry in a prior version

[REL-1004] Followup to add Cloud-first messages to v23.2.7

---

src/current/_includes/releases/whats-new-intro.md
src/current/releases/v1.0.md
src/current/releases/v1.1.md
src/current/releases/v19.1.md
src/current/releases/v19.2.md
src/current/releases/v2.0.md
src/current/releases/v2.1.md
src/current/releases/v20.1.md
src/current/releases/v20.2.md
src/current/releases/v21.1.md
src/current/releases/v21.2.md
src/current/releases/v22.1.md
src/current/releases/v22.2.md
src/current/releases/v23.1.md
src/current/releases/v23.2.md
src/current/releases/v24.1.md
src/current/releases/v24.2.md

[DOC-10653] Update logic in What's New intro:
- Evaluate the page directory to see whether a major version has been branched, rather than using `static_files`, which does not include files with frontmatter. The logic is not the most efficient but it does bail early as soon as it finds a file in the directory.
- Keep track of some older versions that need different links or anchors. (The release notes Python script refers to this as "the singularity")
- Parameterize the What's New intro to require the major version, adjust all What's New pages to pass it.
- Remove duplicate content about upgrading from some What's New pages since it's in the What's New intro 
To see the problem @mikeCRL originally reported, go to the v24.1 live release notes and notice that the third bullet point in the …

[DOC-10653] Update logic in What's New intro

---

src/current/_data/redirects.yml

Using a new way to redirect all version-specific MOLT docs to the `molt` repo.
The `:version` syntax causes the following paths to redirect to `molt`:
- `vXX.X`
- `stable`
- `dev`

adjust MOLT redirect logic

---

src/current/v24.2/known-limitations.md

Fixes DOC-10705
This moves the one new v24.1 KL from the "New limitations" into the existing limitations section for v24.2 docs.

Move new PCR KL from v24.1 to existing KLs in v24.2

---

src/current/v23.2/physical-cluster-replication-overview.md
src/current/v24.1/physical-cluster-replication-overview.md
src/current/v24.2/physical-cluster-replication-overview.md

This is a quick fix to remove the "host" language from the PCR docs. This is confusing because we use this terminology for tenanted serverless clusters,

Small update to PCR upgrade language

---

src/current/_data/alerts.yml
src/current/_data/releases.yml
src/current/_includes/corestyle.scss
src/current/_includes/unsupported-version.md
src/current/_includes/version-switcher.html
src/current/releases/index.md

[DOC-10431] Further LTS improvements
1. Update the logic on the Releases index to get the LTS status from `site.data.versions` instead of `site.data.releases`
2. Update the version switcher to show LTS status both for the currently-viewed page version above the drop-down and in the list of versions in the drop-down
3. Modify the LTS Maintenance admonition from a red warning to a purple note.
4. Fix some LTS logic issues including off-by-one errors on LTS maintenance and assistance dates
5. In the Docker tab, hide the Notes column for all versions except for v23.1 and v22.2.
6. Fix a display bug each in the Source and Docker tabs
Also added some debug messages and the ability to enable or disable debug in the Releases index and the version switcher. The debug info shows in the page source …

[DOC-10431] Further LTS improvements

---

src/current/v24.2/cockroachdb-feature-availability.md

Fixes DOC-9631
Copied cockroachdb-feature-availability.md from v24.1 to v24.2.

DOC-9631 update v24.2 feature availability of Metric scrape (prometheus-compatible metric endpoint) supported for Dedicated Azure cluster

---

src/current/v23.2/physical-cluster-replication-overview.md
src/current/v24.1/physical-cluster-replication-overview.md
src/current/v24.2/physical-cluster-replication-overview.md

Fixes DOC-10835
This PR adjusts the upgrade section for PCR to provide an ordered list of the steps between the system vc and vc as well as the primary + standby.

Update the upgrades section for PCR for more detailed guidance

---

src/current/_includes/v23.1/known-limitations/show-backup-symlink.md
src/current/_includes/v23.2/known-limitations/show-backup-symlink.md
src/current/_includes/v24.1/known-limitations/show-backup-symlink.md
src/current/_includes/v24.2/known-limitations/show-backup-symlink.md
src/current/v23.1/known-limitations.md
src/current/v23.1/show-backup.md
src/current/v23.2/known-limitations.md
src/current/v23.2/show-backup.md
src/current/v24.1/known-limitations.md
src/current/v24.1/show-backup.md
src/current/v24.2/known-limitations.md
src/current/v24.2/show-backup.md

Fixes DOC-7659
This documents an existing limitation that some users had run into recently.

Add limitation for show backup and nodelocal storage with symlink

---

src/current/v23.1/cdc-queries.md
src/current/v23.2/cdc-queries.md
src/current/v24.1/cdc-queries.md
src/current/v24.2/cdc-queries.md

Fixes DOC-7419
This fixes an issue that came out of acceptance testing some time ago. The description for the `event_schema_timestamp` function (that users can specify with cdc queries) was not very clear that the schema change would need to trigger a changefeed event in order for a message to send with the timestamp of the schema change.

Update description for event_schema_timestamp function for cdc queries

---

src/current/v23.1/create-and-configure-changefeeds.md
src/current/v23.2/create-and-configure-changefeeds.md
src/current/v24.1/create-and-configure-changefeeds.md
src/current/v24.2/create-and-configure-changefeeds.md

Fixes DOC-10219
This adds a couple of sentences to the # Enable rangefeeds section to describe (briefly) why there is a 5–10% write latency cost when enabling rangefeeds.

Provide more description on latency cost with rangefeeds

---

src/current/cockroachcloud/export-logs-advanced.md
src/current/cockroachcloud/export-logs.md
src/current/cockroachcloud/export-metrics-advanced.md
src/current/cockroachcloud/export-metrics.md
src/current/v23.1/cockroachdb-feature-availability.md
src/current/v23.2/cockroachdb-feature-availability.md
src/current/v24.1/cockroachdb-feature-availability.md
src/current/v24.2/cockroachdb-feature-availability.md

Fixes DOC-10895
- In cockroachdb-feature-availability.md, (1) replaced dedicated with advanced, (2) updated links to export-*-advanced, (3) replaced AWS CloudWatch with Amazon CloudWatch.
- In export-metrics.md, (1) removed mentions of Azure Monitor.
- In export-metrics-advanced.md, (1) added mentions of Azure Monitor, (2) replaced mentions of dedicated with advanced, (3) added Prometheus preview note for Azure.
- In export-logs.md, (1) removed mentions of Azure monitor, (2) added filter-tabs include for Standard/Advanced, (3) resolved merge conflict.
- In export-logs-advanced.md, (1) added mentions of Azure monitor, (2) replaced AWS CloudWatch with Amazon CloudWatch, (3) corrected references to config step.
- In export-*.md files, (1) replaced cockroachlabs.com links with liquid links, …

DOC-10895 Cloud 2.0 update export logs and metrics for Azure Monitor

---

src/current/_includes/v23.2/cdc/filter-show-changefeed-jobs-columns.md
src/current/_includes/v24.1/cdc/filter-show-changefeed-jobs-columns.md
src/current/_includes/v24.2/cdc/filter-show-changefeed-jobs-columns.md
src/current/v23.2/create-and-configure-changefeeds.md
src/current/v23.2/show-jobs.md
src/current/v24.1/create-and-configure-changefeeds.md
src/current/v24.1/show-jobs.md
src/current/v24.2/create-and-configure-changefeeds.md
src/current/v24.2/show-jobs.md

Fixes DOC-10960
Adds a short filter column example for `SHOW CHANGEFEED JOBS` to the `SHOW JOB` page and the Create and Configure Changefeeds page.

Add an example to filter columns on show changefeed jobs

---

src/current/_data/releases.yml

Fixes REL-1334
In releases.yml, deleted cloud lines for v24.2.1 to enable download of self-hosted binaries.

REL-1334 v24.2.1: [Docs] Adjust release notes for download/SH

---

src/current/_data/releases.yml
src/current/releases/index.md

Fixes REL-1489
In releases.yml, added line for v24.2.1 to withdraw release.

REL-1489 Withdraw v24.2.1 from release notes page

---

src/current/v22.1/alter-backup.md
src/current/v22.1/alter-changefeed.md
src/current/v22.1/show-create-schedule.md
src/current/v22.2/alter-backup-schedule.md
src/current/v22.2/alter-backup.md
src/current/v22.2/alter-changefeed.md
src/current/v22.2/show-create-schedule.md
src/current/v23.1/alter-backup-schedule.md
src/current/v23.1/alter-backup.md
src/current/v23.1/alter-changefeed.md
src/current/v23.1/show-create-schedule.md
src/current/v23.2/alter-backup-schedule.md
src/current/v23.2/alter-backup.md
src/current/v23.2/alter-changefeed.md
src/current/v23.2/show-create-schedule.md
src/current/v24.1/alter-backup-schedule.md
src/current/v24.1/alter-backup.md
src/current/v24.1/alter-changefeed.md
src/current/v24.1/show-create-schedule.md
src/current/v24.2/alter-backup-schedule.md
src/current/v24.2/alter-backup.md
src/current/v24.2/alter-changefeed.md
src/current/v24.2/show-create-schedule.md

Fixes DOC-11093
Updated the instances of 
{% remote_include https://raw.githubusercontent.com/cockroachdb/generated-diagrams/master/grammar_svg/show_create_schedules.html %}
To 
{% remote_include https://raw.githubusercontent.com/cockroachdb/generated-diagrams/{{ page.release_info.crdb_branch_name }}/grammar_svg/show_create_schedules.html %}
in 4 different commands.

Fix master ref in sql diagram remote include uri

---

src/current/v23.2/performance-recipes.md
src/current/v24.1/performance-recipes.md
src/current/v24.2/performance-recipes.md

Fixes DOC-11185
In performance-recipes.md, added back markdown="1" so that liquid links are rendered properly in html table.

DOC-11185 Cloud-2.0 fix cockroachcloud links on performance-recipes.md for v23.2, v24.1, v24.2

---

src/current/_includes/v24.2/sidebar-data/cloud-deployments.json
src/current/cockroachcloud/provision-a-cluster-with-terraform.md

[DOC-9723] Update Terraform page for new plans
- Update page title (but not filename) with an eye toward covering more than cluster creation on the page in future
- Update page variables and filter tabs
- Split Serverless into Basic and Standard
- Removed the `tfvars` construct in favor of directly copying the examples from https://github.com/cockroachdb/terraform-provider-cockroach/blob/398102111d6e696a4e2c034077f812cd1917f675/examples/resources/cockroach_cluster/resource.tf with the following changes:
- Replace `machine_type` field in Advanced example with `provisioned_vcpus`, per [thread](https://cockroachlabs.slack.com/archives/C01CD39JX8E/p1726523199408789).
- Subsequently replaced `provisioned_vcpus` with `provisioned_virtual_cpus` and `num_vcpus` with `num_virtual_cpus`, per …

[DOC-9723] Update Terraform page for new plans

---

src/current/cockroachcloud/export-logs-advanced.md
src/current/cockroachcloud/export-logs.md

Fixes DOC-11204
In export-logs.md, removed incorrect mention of Azure monitor.
In export-logs-advanced.md, added sentence about Azure monitor log naming format.

DOC-11204 Cloud 2.0 remove mention of Azure monitor on export logs for Standard

---

src/current/_includes/v24.2/sidebar-data/sql.json
src/current/v24.2/create-external-connection.md
src/current/v24.2/drop-external-connection.md
src/current/v24.2/set-up-physical-cluster-replication.md
src/current/v24.2/show-create-external-connection.md
src/current/v24.2/show-external-connection.md

Fixes DOC-10317
This PR adds the `SHOW EXTERNAL CONNECTION` statement to the docs.
Also added the `postgresql` external connection support for physical cluster replication.

Add docs for show external connection

---

src/current/cockroachcloud/basic-cluster-management.md
src/current/cockroachcloud/costs.md
src/current/releases/cloud.md
src/current/v24.2/cockroachdb-feature-availability.md

- [Release notes > Oct 1](https://deploy-preview-18967--cockroachdb-docs.netlify.app/docs/releases/cloud.html)
- [Cloud Costs > Usage-based *billing* metrics in Preview](https://deploy-preview-18967--cockroachdb-docs.netlify.app/docs/cockroachcloud/costs.html#usage-based-billing-metrics-in-preview) (Same content as above)
- [Features in Preview > Usage-based billing metrics](https://deploy-preview-18967--cockroachdb-docs.netlify.app/docs/v24.2/cockroachdb-feature-availability.html#features-in-preview) (A summary)

Release note and other updates on usage-based billing preview

---

src/current/cockroachcloud/create-an-advanced-cluster.md
src/current/cockroachcloud/plan-your-cluster-advanced.md

[DOC-11236] Move and update cluster sizing details to Plan an Advanced Cluster
- Moved and edited compute and storage capacity details, linked
- Copyediting and restructuring improvements to the planning page
Previews:
[src/current/cockroachcloud/create-an-advanced-cluster.md](https://deploy-preview-18958--cockroachdb-docs.netlify.app/docs/cockroachcloud/create-an-advanced-cluster.html)
[src/current/cockroachcloud/plan-your-cluster-advanced.md](https://deploy-preview-18958--cockroachdb-docs.netlify.app/docs/cockroachcloud/plan-your-cluster-advanced.html)

[DOC-11236] Move and update cluster sizing details to Plan an Advanced Cluster

---

src/current/_data/releases.yml
src/current/_includes/releases/new-release-downloads-docker-image.md

Fixes REL-1381
In releases.yml, removed cloud attributes to show download links.
Rendered preview:
- [Downloads](https://deploy-preview-19011--cockroachdb-docs.netlify.app/docs/releases/v23.1#v23-1-28-downloads)
- [Docker image](https://deploy-preview-19011--cockroachdb-docs.netlify.app/docs/releases/v23.1#v23-1-28-docker-image)

REL-1381 v23.1.28 (was 23.1.27): [Docs] Adjust release notes for download/SH

---

src/current/_data/releases.yml

Fixes DOC-11475
In release.yml, fixed entries for v24.3.0-alpha.1 and v23.1.28.
rendered previews
- [Releases](https://deploy-preview-19013--cockroachdb-docs.netlify.app/docs/releases/#v24-3)
- [24.3](https://deploy-preview-19013--cockroachdb-docs.netlify.app/docs/releases/v24.3)
- [23.1.28](https://deploy-preview-19013--cockroachdb-docs.netlify.app/docs/releases/v23.1#v23-1-28)

DOC-11475 Remove duplicate entry for 24.3.0-alpha.2

---

src/current/_includes/releases/v23.1/v23.1.28.md

- Remove duplicate note
- Move security note to the correct part of the file
- In security note, add a link to a command a fix a link pointing to the wrong reference

Update v23.1.28 release notes

---

src/current/releases/cloud.md

[DOC-11237] Release-note deprecation of is_regex JWT API field

[DOC-11237] Release-note deprecation of is_regex JWT API field

---

src/current/cockroachcloud/troubleshooting-page.md
src/current/v23.1/cluster-setup-troubleshooting.md
src/current/v23.2/cluster-setup-troubleshooting.md
src/current/v24.1/cluster-setup-troubleshooting.md
src/current/v24.2/cluster-setup-troubleshooting.md
src/current/v24.3/cluster-setup-troubleshooting.md

Touches DOC-7401 again, a little
This came up again in today's SQL Foundations weekly (2024-10-21)
Summary: remove last lingering mentions of "connection retry" and instead point users to 'Connection Pooling' (on-prem) and 'Production Checklist' (cloud) pages instead.

Change remaining refs to 'connection retry'

---

src/current/_includes/v24.1/install-docker-steps.md
src/current/_includes/v24.2/install-docker-steps.md
src/current/_includes/v24.3/install-docker-steps.md
src/current/v24.1/install-cockroachdb-linux.md
src/current/v24.1/install-cockroachdb-mac.md
src/current/v24.1/install-cockroachdb-windows.md
src/current/v24.2/install-cockroachdb-linux.md
src/current/v24.2/install-cockroachdb-mac.md
src/current/v24.2/install-cockroachdb-windows.md
src/current/v24.3/install-cockroachdb-linux.md
src/current/v24.3/install-cockroachdb-mac.md
src/current/v24.3/install-cockroachdb-windows.md

[DOC-10949] Update Docker instructions for Cloud-first
- Also externalize Docker instructions into a version-specific include
- Also convert HTML to Markdown
This is related to #18826 but I separated it out on purpose so that I can rebase this one on that one's work.
Sending for initial review before backporting to more versions
[src/current/v24.2/install-cockroachdb-mac.md](https://deploy-preview-18839--cockroachdb-docs.netlify.app/docs/v24.2/install-cockroachdb-mac.html)
[src/current/v24.2/install-cockroachdb-windows.md](https://deploy-preview-18839--cockroachdb-docs.netlify.app/docs/v24.2/install-cockroachdb-windows.html)
[src/current/v24.2/install-cockroachdb-linux.md](https://deploy-preview-18839--cockroachdb-docs.netlify.app/docs/v24.2/install-cockroachdb-linux.html)

[DOC-10949] Update Docker instructions for Cloud-first

---

src/current/v24.3/cluster-virtualization-metric-scopes.md
src/current/v24.3/cluster-virtualization-setting-scopes.md

[DOC-11556] CV setting and metric scopes for v24.3
Previews:
[src/current/v24.3/cluster-virtualization-metric-scopes.md](https://deploy-preview-19051--cockroachdb-docs.netlify.app/docs/v24.3/cluster-virtualization-metric-scopes.html)
[src/current/v24.3/cluster-virtualization-setting-scopes.md](https://deploy-preview-19051--cockroachdb-docs.netlify.app/docs/v24.3/cluster-virtualization-setting-scopes.html)
[Instructions for generating these](https://docs.google.com/spreadsheets/d/1HIalzAhwU0CEYzSuG2m1aXSJRpiIyQPJdt8SusHpJ_U/edit?gid=1642767093#gid=1642767093)

[DOC-11556] CV setting and metric scopes for v24.3

---

src/current/v23.1/diagnostics-reporting.md
src/current/v23.2/diagnostics-reporting.md
src/current/v24.1/diagnostics-reporting.md
src/current/v24.2/diagnostics-reporting.md

Addresses DOC-11674
- Backport changes from cockroachdb/docs#19008 to v23.1, v23.2, v24.1, and v24.2

Backport changes from cockroachdb/docs#19008

---

src/current/_data/redirects.yml
src/current/cockroachcloud/upgrade-cockroach-version.md

[DOC-11682] Fix redirect to new Cloud upgrade page
This was due to my misunderstanding of the syntax.
- Also add an anchor to the new page with a link to the new section of the (current Cloud version's) release notes to help ease the transition
To test: Confirm that hitting https://deploy-preview-19111--cockroachdb-docs.netlify.app/docs/cockroachcloud/upgrade-to-v24.2 redirects to the new page

[DOC-11682] Fix redirect to new Cloud upgrade page

---

src/current/v23.2/sql-statements.md
src/current/v24.1/sql-statements.md
src/current/v24.2/sql-statements.md
src/current/v24.3/sql-statements.md

The stored procedure statements were missing from the SQL Statements page since they were introduced in 23.2.

add stored proc statements to SQL Statements list

---

src/current/_includes/v24.3/physical-replication/failover-read-virtual-cluster.md
src/current/_includes/v24.3/physical-replication/fast-failback-syntax.md
src/current/_includes/v24.3/physical-replication/show-virtual-cluster-data-state.md
src/current/v24.3/alter-virtual-cluster.md
src/current/v24.3/create-virtual-cluster.md
src/current/v24.3/failover-replication.md
src/current/v24.3/physical-cluster-replication-technical-overview.md
src/current/v24.3/set-up-physical-cluster-replication.md

Fixes DOC-8047
This PR adds the `READ VIRTUAL CLUSTER` option to the `CREATE VIRTUAL CLUSTER` statement. This allows for reads on the standby virtual cluster during a PCR stream. Updates `ALTER VIRTUAL CLUSTER` too, with the same option for the failback process.

Add docs for read on standby in PCR

---

src/current/v24.3/wal-failover.md

Fixes DOC-11749
Rendered Preview:
- [WAL Failover](https://deploy-preview-19163--cockroachdb-docs.netlify.app/docs/v24.3/wal-failover.html)

Fix broken log config snippet in WAL failover docs

---

src/current/v23.1/restore.md
src/current/v23.2/restore.md
src/current/v24.1/restore.md
src/current/v24.2/restore.md
src/current/v24.3/restore.md

Fixes DOC-11003
Currently, we only mention that restore verifies a checksum when using one of the backup validation options. A regular restore also verifies the checksums of the backup data before restoring to the cluster. This PR adds a short paragraph re this to the `RESTORE` functional detail section on the SQL page.
Versions 23.1 – 24.3

Add paragraph on checksum verification in restore jobs for compliance

---

src/current/_includes/v24.3/physical-replication/show-virtual-cluster-data-state.md
src/current/v24.3/alter-virtual-cluster.md
src/current/v24.3/cockroachdb-feature-availability.md
src/current/v24.3/create-virtual-cluster.md
src/current/v24.3/failover-replication.md
src/current/v24.3/physical-cluster-replication-technical-overview.md

Fixes DOC-11751
We've decided to move PCR read on standby to the public preview phase.
Note on the main example on the `CREATE VIRTUAL CLUSTER` page, I've added a custom "preview" note since cluster virtualization is in preview but PCR generally is GA. See files for details.

Add preview label to PCR read on standby docs

---

src/current/v24.3/follower-reads.md

Fast-follow to clarify the step in #19165, as suggested in https://github.com/cockroachdb/docs/pull/19165#discussion_r1852896741

clarify non-leaseholder node step

---

src/current/_includes/cockroachcloud/backups/cloud-api-get-put.md
src/current/_includes/cockroachcloud/backups/managed-backup-upgrade-downgrade.md
src/current/_includes/cockroachcloud/backups/review-settings.md
src/current/_includes/cockroachcloud/filter-tabs/managed-backups.md
src/current/_includes/v24.3/sidebar-data/cloud-deployments.json
src/current/cockroachcloud/managed-backups-advanced.md
src/current/cockroachcloud/managed-backups-basic.md
src/current/cockroachcloud/managed-backups.md
src/current/releases/cloud.md

Fixes DOC-17711
Refer to the rendered preview:
[Managed Backups](https://deploy-preview-19177--cockroachdb-docs.netlify.app/docs/cockroachcloud/managed-backups-basic.html)

Create include tab files for managed backup page cluster types

---

src/current/_includes/releases/v24.1/v24.1.5.md
src/current/_includes/releases/v24.2/v24.2.3.md
src/current/_includes/releases/v24.3/v24.3.0-alpha.1.md

@arjunmahishi and @smcvey because there was no release note specified for this change, would you please offer any guidance you have on making the release note I've drafted here clearer or more specific?

Add release note for bug fix for iterator over file sinks

---

src/current/_data/releases.yml

Modified the date in `releases.yml` to ensure proper functionality of Liquid logic for identifying the latest release.

Update release date in releases.yml to support Liquid logic

---

src/current/v24.3/ui-replication-dashboard.md

Fixes DOC-9550
In ui-replication-dashboard.md, added section for Range Operations graph.
- [Range Operations](https://deploy-preview-19186--cockroachdb-docs.netlify.app/docs/v24.3/ui-replication-dashboard.html#range-operations)

DOC-9550 Provide example of range operations graph

---

src/current/_includes/v24.3/backups/backup-to-deprec.md
src/current/_includes/v24.3/backups/old-syntax-removed.md
src/current/v24.3/backup.md
src/current/v24.3/restore.md
src/current/v24.3/show-backup.md
src/current/v24.3/take-full-and-incremental-backups.md

Fixes DOC-11663
Changes the deprecation notice for `BACKUP`, `RESTORE`, `SHOW BACKUP` old syntax to confirm the syntax has been removed in v24.3+.
https://deploy-preview-19192--cockroachdb-docs.netlify.app/docs/v24.3/backup.html
https://deploy-preview-19192--cockroachdb-docs.netlify.app/docs/v24.3/show-backup.html

Change deprecation warning for old backup syntax to removal note in v24.3+

---

src/current/v24.3/create-logical-replication-stream.md
src/current/v24.3/logical-data-replication-overview.md
src/current/v24.3/physical-cluster-replication-overview.md
src/current/v24.3/set-up-logical-data-replication.md

Fixes DOC-11689
This PR adds a handful more link references between LDR (and PCR) pages.

Add further link reference in LDR docs

---

src/current/v23.1/trigram-indexes.md
src/current/v23.2/trigram-indexes.md
src/current/v24.1/trigram-indexes.md
src/current/v24.2/trigram-indexes.md
src/current/v24.3/trigram-indexes.md

fix copy buttons on Trigram Indexes page

---

src/current/_data/releases.yml
src/current/_includes/releases/v24.2/v24.2.8.md

v24.2.8 release notes (cloud)

---

src/current/cockroachcloud/cloud-api.md

This is a quick fix for a typo and a couple render issues on the Cloud API page.

Fixes to typos on Cloud API page

---

src/current/releases/index.md

* Updates the [Releases](https://www.cockroachlabs.com/docs/releases/) page > Recent Releases and Upcoming Releases tables.
* Removes 'latest patch release' column from Recent Releases - we can bring this back and use liquid to automate the patch version details via [DOC-11004](https://cockroachlabs.atlassian.net/browse/DOC-11004).

Update major release dates and statuses

---

src/current/_includes/releases/v23.1/v23.1.29.md
src/current/_includes/releases/v23.2/v23.2.16.md
src/current/_includes/releases/v24.1/v24.1.6.md
src/current/_includes/releases/v24.2/v24.2.4.md
src/current/_includes/releases/v24.3/v24.3.0-alpha.1.md

Fixes DOC-12109
This PR adds a release note to versions 23.1 – 24.3 that was omitted from the original eng PR.

Add missing backup schedule bug fix release note

---

src/current/v24.3/ldap-authentication.md
src/current/v25.1/ldap-authentication.md

Quick fix to a code block that wasn't rendering

Fix the code block on LDAP page

---

src/current/_includes/v23.1/sidebar-data/sql.json
src/current/_includes/v23.2/sidebar-data/sql.json
src/current/_includes/v24.1/sidebar-data/sql.json
src/current/_includes/v24.2/sidebar-data/sql.json
src/current/_includes/v24.3/sidebar-data/sql.json
src/current/_includes/v25.1/sidebar-data/sql.json

Remove (Enterprise) from nav title for SQL statements from v23.1 onward

---

src/current/_data/releases.yml
src/current/_includes/releases/v24.2/v24.2.9.md

v24.2.9 release notes

---

src/current/_data/releases.yml
src/current/_includes/releases/v24.1/v24.1.11.md

v24.1.11 release notes

---

src/current/_data/redirects.yml

A fix to the redirects implemented in https://github.com/cockroachdb/docs/pull/19303, which did not account for the path with /stable, only with certain /<major_version> paths.

Fix redirect to Compare page

---

src/current/_data/releases.yml

Fixes REL-1952
In releases.yml, removed cloud fields for v23.2.20 to show binary download links.

REL-1952 v23.2.20: [Docs] Adjust release notes for download/SH

---

src/current/_includes/v23.1/cdc/privilege-model.md
src/current/_includes/v23.2/cdc/privilege-model.md
src/current/_includes/v24.1/cdc/privilege-model.md
src/current/_includes/v24.2/cdc/privilege-model.md
src/current/_includes/v24.3/cdc/privilege-model.md
src/current/_includes/v25.1/cdc/privilege-model.md
src/current/_includes/v25.1/sidebar-data/sql.json
src/current/v23.1/alter-changefeed.md
src/current/v23.1/create-changefeed.md
src/current/v23.1/create-schedule-for-changefeed.md
src/current/v23.2/alter-changefeed.md
src/current/v23.2/create-changefeed.md
src/current/v23.2/create-schedule-for-changefeed.md
src/current/v24.1/alter-changefeed.md
src/current/v24.1/create-changefeed.md
src/current/v24.1/create-schedule-for-changefeed.md
src/current/v24.2/alter-changefeed.md
src/current/v24.2/create-changefeed.md
src/current/v24.2/create-schedule-for-changefeed.md
src/current/v24.3/alter-changefeed.md
src/current/v24.3/create-changefeed.md
src/current/v24.3/create-schedule-for-changefeed.md
src/current/v25.1/alter-changefeed.md
src/current/v25.1/alter-job.md
src/current/v25.1/create-changefeed.md
src/current/v25.1/create-schedule-for-changefeed.md
src/current/v25.1/create-user.md

Fixes DOC-12058
This PR updates the changefeed privilege docs to deprecate the use of the `CHANGEFEED` privilege for viewing and managing changefeed jobs on tables users have the privilege on (from v25.1). Instead, documenting that users should use job ownership or global privileges to view and manage jobs.
Also, made changes to an incorrect role option listed since v20.2 (was listed as `CREATECHANGEFEED` should have been `CONTROLCHANGEFEED`). This make sense and has meant that the content for this deprecated role option is now consolidated into the Privilege model table.
Also, made adjustments to the `ALTER CHANGEFEED` privilege section as per the above changes + testing.
https://deploy-preview-19290--cockroachdb-docs.netlify.app/docs/v25.1/alter-job.html …

Update docs for changefeed privileges in v25.1

---

src/current/releases/release-support-policy.md
src/current/v24.1/restoring-backups-across-versions.md
src/current/v24.2/restoring-backups-across-versions.md
src/current/v24.3/restoring-backups-across-versions.md
src/current/v25.1/restoring-backups-across-versions.md

Fixes DOC-11980
This PR updates the Restoring Backups Across Versions page to account for innovation releases.
Innovation releases were introduced in v24.2, so the changes have been added to v24.1+ since the policy is that users can restore to the same major version, or one above — v24.1 clusters can upgrade to v24.3 (skipping the first v24.2 innovation release).

Update the restore backups across major version docs for innovation releases

---

src/current/v24.3/set-up-physical-cluster-replication.md
src/current/v25.1/set-up-physical-cluster-replication.md

Remove static versioning from PCR section in v24.3+

---

src/current/_data/releases.yml

Fixes DOC-12744
In releases.yml, modified date for v25.1.1 to not be the same as v25.1.2 as workaround for version selector.

DOC-12744 Adjust release date for version 25.1.1

---

src/current/_data/releases.yml

Fixes REL-2085
In releases.yml, removed cloud fields for v25.1.2 to enable download links for binaries.

REL-2085 v25.1.2 (was 25.1.1): [Docs] Adjust release notes for download/SH

---

src/current/cockroachcloud/provision-a-cluster-with-terraform.md

Fixes DOC-12712
Added the required provider definition to the TF examples to make it possible for users to run the example directly, if necessary.
https://deploy-preview-19454--cockroachdb-docs.netlify.app/docs/cockroachcloud/provision-a-cluster-with-terraform.html

Add the provider def to the TF docs

---

src/current/v24.3/take-and-restore-locality-aware-backups.md
src/current/v25.1/take-and-restore-locality-aware-backups.md

Fixes DOC-12344
Adjust the sentence in v24.3 + v25.1 regarding locality-aware incremental backups to clarify that the the storage URI + the `COCKROACH_LOCALITY` region must match the related full backup.

Update the description of incremental backups with locality aware

---

src/current/v23.1/cloud-storage-authentication.md
src/current/v23.2/cloud-storage-authentication.md
src/current/v24.1/cloud-storage-authentication.md
src/current/v24.2/cloud-storage-authentication.md
src/current/v24.3/cloud-storage-authentication.md
src/current/v25.1/cloud-storage-authentication.md

Fixes DOC-12366
This PR removes sections from the Cloud Storage Authentication page that refer to using the CRL role with Cloud clusters, which is not supported.

Remove the Advanced implicit auth + crl role from cloud storage auth page

---

src/current/releases/cloud.md

Fixes DOC-12824
In cloud.md, replaced Regular innovation with Innovation release.
- [CockroachDB Cloud Releases: February 18, 2025](https://deploy-preview-19464--cockroachdb-docs.netlify.app/docs/releases/cloud#february-18-2025)

DOC-12824 Correct release type for CockroachDB v25.1 to Innovation

---

src/current/css/customstyles.scss

Added CSS to make bold text in tables inherit the font size. Presently the font sizes are mismatched.
**Before:**
**After:**

make bold text in tables match font size

---

src/current/_includes/v23.1/misc/s3-compatible-warning.md
src/current/_includes/v23.2/misc/s3-compatible-warning.md
src/current/_includes/v24.1/misc/s3-compatible-warning.md
src/current/_includes/v24.3/misc/s3-compatible-warning.md
src/current/_includes/v25.1/misc/s3-compatible-warning.md

Fixes DOC-12919
In s3-compatible-warning.md, added check for cloud-storage-authentication.md page.
Rendered Preview
- [Cloud Storage Authentication](https://deploy-preview-19471--cockroachdb-docs.netlify.app/docs/v25.1/cloud-storage-authentication?filters=s3compatible)
- [RESTORE](https://deploy-preview-19471--cockroachdb-docs.netlify.app/docs/v25.1/restore#source-privileges)

Fix hyperlink issue for S3-compatible services

---

src/current/v23.1/authentication.md
src/current/v23.2/authentication.md
src/current/v24.1/authentication.md
src/current/v24.3/authentication.md
src/current/v25.1/authentication.md

Quick PR correcting some punctuation that seems wrong to me. Please feel free to close if my proposed change violates style, I just wanted to find something extremely simple to test the docs toolchain.
Addresses: DOC-13075
- Corrects an errant colon in `authentication.md`

Replace errant colon with semicolon

---

src/current/v25.2/ui-overview.md

Fixes DOC-13048 DOC-11496
In ui-overview.md, updated DB Console timezone configuration section with ui.default_timezone cluster setting.
Rendered previews:
- [DB Console timezone configuration](https://deploy-preview-19495--cockroachdb-docs.netlify.app/docs/25.2/ui-overview#db-console-timezone-configuration)

DOC-13048 Product Change- PR #143499 - ui: add support for all timezones in db console

---

src/current/_includes/releases/v25.1/v25.1.3.md

Fixes DOC-13165
In v25.1.3.md, fixed formatting by removing line with Epic: none.
Rendered previews:
- [v25.1.3 release notes](https://deploy-preview-19512--cockroachdb-docs.netlify.app/docs/releases/v25.1#v25-1-3-bug-fixes)

Fix bad formatting in v25.1.3 release notes bug fixes section 

---

src/current/_includes/v23.1/sidebar-data/self-hosted-deployments.json
src/current/_includes/v23.2/sidebar-data/self-hosted-deployments.json
src/current/_includes/v24.1/sidebar-data/self-hosted-deployments.json
src/current/_includes/v24.3/sidebar-data/self-hosted-deployments.json
src/current/_includes/v25.1/sidebar-data/self-hosted-deployments.json
src/current/_includes/v25.2/sidebar-data/self-hosted-deployments.json
src/current/v23.1/deployment-operations-skills-taxonomy.md
src/current/v23.2/deployment-operations-skills-taxonomy.md
src/current/v24.1/deployment-operations-skills-taxonomy.md
src/current/v24.3/deployment-operations-skills-taxonomy.md
src/current/v25.1/deployment-operations-skills-taxonomy.md
src/current/v25.2/deployment-operations-skills-taxonomy.md

Fixes DOC-12354
Rendered preview: 
[Deployment & ops skills taxonomy](https://deploy-preview-19400--cockroachdb-docs.netlify.app/docs/v25.1/deployment-operations-skills-taxonomy.html)

Add v1 Deployment & Ops Skills Taxonomy

---

src/current/v24.3/upgrade-cockroachdb-kubernetes.md
src/current/v25.1/upgrade-cockroachdb-kubernetes.md
src/current/v25.2/upgrade-cockroachdb-kubernetes.md

Adds an include that was missing in the 24.3 docs reorg. Rendered:

Add missing Kubernetes upgrade content

---

src/current/Gemfile

Removed ~> 4.3 until conflict with our use of ianjevins/jekyll-remote-include is resolved

Update Gemfile to specify Jekyll 4.3.4

---

src/current/releases/index.md

Update current/upcoming releases tables to account for v25.1 release and remove recent EOS releases.

Add missing updates to releases page for v25.1

---

src/current/v25.2/plpgsql.md

Updated one of the `RETURNS SETOF` examples to use `RETURNS TABLE` instead. This demonstrates that `RETURNS TABLE` is now valid PL/pgSQL syntax. cc @mikeCRL

add RETURNS TABLE example for Pl/pgSQL

---

src/current/cockroachcloud/basic-cluster-management.md
src/current/cockroachcloud/costs.md
src/current/cockroachcloud/free-trial.md
src/current/cockroachcloud/plan-your-cluster-basic.md
src/current/releases/cloud.md

Per @jaiayu , customers and support have expressed confusion over the $15 monthly resource benefit available to non-contract Basic customers. Primarily that it is distinct from the $400 free usage benefit offered to new customers, but also that it appears as a credit on the monthly invoice.
- Translate the "50 million RU/10 GiB storage" benefit into $15 to match the invoice language and distinguish from the one-time $400 benefit
- Add mentions of the benefit to other places where we discuss Basic cluster costs

Clarify the monthly Basic resource benefit

---

src/current/v24.3/physical-cluster-replication-monitoring.md
src/current/v24.3/ui-physical-cluster-replication-dashboard.md
src/current/v25.1/physical-cluster-replication-monitoring.md
src/current/v25.1/ui-physical-cluster-replication-dashboard.md
src/current/v25.2/physical-cluster-replication-monitoring.md
src/current/v25.2/ui-physical-cluster-replication-dashboard.md

Fixes DOC-13812
Removes the SST Bytes graph section from the PCR Console metrics page. Also, removes the reference to the graph on the monitoring page.

Remove the SST Bytes graph from the DB Console page for PCR

---

src/current/v24.3/create-logical-replication-stream.md
src/current/v24.3/logical-data-replication-overview.md
src/current/v24.3/manage-logical-data-replication.md
src/current/v24.3/set-up-logical-data-replication.md
src/current/v25.1/create-logical-replication-stream.md
src/current/v25.1/create-logically-replicated.md
src/current/v25.1/logical-data-replication-overview.md
src/current/v25.1/manage-logical-data-replication.md
src/current/v25.1/set-up-logical-data-replication.md
src/current/v25.2/cockroachdb-feature-availability.md
src/current/v25.2/create-logical-replication-stream.md
src/current/v25.2/create-logically-replicated.md
src/current/v25.2/logical-data-replication-monitoring.md
src/current/v25.2/logical-data-replication-overview.md
src/current/v25.2/manage-logical-data-replication.md
src/current/v25.2/set-up-logical-data-replication.md

Fixes DOC-13440
This PR:
- Removes the preview label from LDR in v25.2 to bring into GA.
- Removes `validated` mode from all versions — for now, removed the `mode` option and `immediate` value because this is the default and only option.
- Adds a description of how unique secondary indexes interact with LDR.
Navigate to pages from [v25.2 Setup tutorial](https://deploy-preview-19626--cockroachdb-docs.netlify.app/docs/v25.2/set-up-logical-data-replication.html#schema-validation).

Update LDR docs for GA & remove validated

---

src/current/_includes/releases/v25.2/v25.2.1.md

Fixes DOC-13940
In v25.2.1.md, removed duplicate release note of backported change.

DOC-13940 Remove duplicate release note of backported change

---

src/current/cockroachcloud/upgrade-policy.md

Add v24.1 to EOS table and v25.2 to currently supported table.

Update cloud upgrade policy page for latest versions

---

src/current/_includes/v24.1/wal-failover-log-config.md
src/current/_includes/v24.3/wal-failover-log-config.md
src/current/_includes/v25.1/wal-failover-log-config.md
src/current/_includes/v25.2/wal-failover-log-config.md
src/current/_includes/v25.3/wal-failover-log-config.md

WAL failover log config needs `auditable: false`

---

src/current/v23.1/diagnostics-reporting.md
src/current/v23.2/diagnostics-reporting.md
src/current/v24.1/diagnostics-reporting.md
src/current/v24.2/diagnostics-reporting.md
src/current/v24.3/diagnostics-reporting.md
src/current/v25.1/diagnostics-reporting.md
src/current/v25.2/diagnostics-reporting.md
src/current/v25.3/diagnostics-reporting.md

Fixes DOC-13703
- Replace mentions of 'anonymous' with 'obfuscated/redacted'
- Remove mention of details, and point users to the 'Telemetry Collected by CockroachDB' page, which is intended to be the comprehensive reference

Update diagnostics page re: telemetry info

---

src/current/_data/releases.yml

Fixes
REL-2651 
REL-2615
REL-2642
REL-2633
REL-2624
In releases.yml, removed cloud fields to show download links.
- [Release downloads](https://deploy-preview-19856--cockroachdb-docs.netlify.app/docs/releases/#downloads)

[Docs] Adjust release notes for download/SH v25.2.2, v25.1.8, v24.3.15, v24.1.20, v23.2.27

---

src/current/v23.2/physical-cluster-replication-overview.md
src/current/v24.1/physical-cluster-replication-overview.md
src/current/v24.2/physical-cluster-replication-overview.md
src/current/v24.3/create-virtual-cluster.md
src/current/v24.3/drop-virtual-cluster.md
src/current/v24.3/physical-cluster-replication-monitoring.md
src/current/v24.3/physical-cluster-replication-overview.md
src/current/v24.3/physical-cluster-replication-technical-overview.md
src/current/v24.3/set-up-physical-cluster-replication.md
src/current/v25.1/create-virtual-cluster.md
src/current/v25.1/drop-virtual-cluster.md
src/current/v25.1/physical-cluster-replication-monitoring.md
src/current/v25.1/physical-cluster-replication-overview.md
src/current/v25.1/physical-cluster-replication-technical-overview.md
src/current/v25.1/set-up-physical-cluster-replication.md
src/current/v25.2/create-virtual-cluster.md
src/current/v25.2/drop-virtual-cluster.md
src/current/v25.2/physical-cluster-replication-monitoring.md
src/current/v25.2/physical-cluster-replication-overview.md
src/current/v25.2/physical-cluster-replication-technical-overview.md
src/current/v25.2/set-up-physical-cluster-replication.md
src/current/v25.3/create-virtual-cluster.md
src/current/v25.3/drop-virtual-cluster.md
src/current/v25.3/physical-cluster-replication-monitoring.md
src/current/v25.3/physical-cluster-replication-overview.md
src/current/v25.3/physical-cluster-replication-technical-overview.md
src/current/v25.3/set-up-physical-cluster-replication.md

https://cockroachlabs.atlassian.net/browse/DOC-14188

Remove outdated line about PCR only being for self-hosted CRDB

---

src/current/_includes/cockroachcloud/backups/cloud-api-backup-settings.md
src/current/_includes/cockroachcloud/backups/cloud-api-backup-view.md
src/current/_includes/cockroachcloud/backups/cloud-api-managed-backup-intro.md
src/current/_includes/cockroachcloud/backups/cloud-api-restore-endpoint.md
src/current/cockroachcloud/cloud-api.md
src/current/cockroachcloud/managed-backups-advanced.md
src/current/cockroachcloud/managed-backups-basic.md
src/current/cockroachcloud/managed-backups.md
src/current/v25.3/cockroachdb-feature-availability.md

Fixes DOC-11599
Add task-oriented guidance to our docs around using the cloud API to:
- View managed backups
- Restore cluster objects
- Restore database objects
- Restore table objects
- View restore operations on a cluster
Opted to break out our existing include(s) for human readability due to different functionality between Cloud plans.
TODO:
- Update release note date to the actual release date

Add documentation for new backup and restore cloud API endpoints

---

src/current/_data/releases.yml

Fixes DOC-14576
In releases.yml, for v25.3.0 set linux_intel_fips: false.
- [Download FIPS-ready runtimes](https://deploy-preview-20109--cockroachdb-docs.netlify.app/docs/v25.3/fips.html#download-fips-ready-runtimes) (Production section is removed)

DOC-14576 v25.3.0 download URL for the latest FIPS binary getting 404 error

---

src/current/_data/releases.yml

REL-2952
Removes `cloud-only*` parameters and sets `linux_intel_fips` to `true`.

Bring v25.3.0 out of cloud-only phase

---

src/current/v23.1/datadog.md
src/current/v23.2/datadog.md
src/current/v24.1/datadog.md
src/current/v24.2/datadog.md
src/current/v24.3/datadog.md
src/current/v25.1/datadog.md
src/current/v25.2/datadog.md
src/current/v25.3/datadog.md

Fixes DOC-12287
In datadog.md, remove step 7 Disable DB Console local storage of metrics (optional).
- [Monitor CockroachDB Self-Hosted Clusters with Datadog](https://deploy-preview-20164--cockroachdb-docs.netlify.app/docs/v25.3/datadog)

DOC-12287 Feedback: Monitor CockroachDB Self-Hosted Clusters with Datadog (remove guidance on disable DB console)

---

StyleGuide.md

This PR attempts to clarify the use of "legacy" vs "deprecated" in our documentation.

Update style guide re: 'legacy' vs. 'deprecated'

---

src/current/_includes/cockroachcloud/backups/cloud-api-restore-endpoint.md
src/current/_includes/cockroachcloud/backups/managed-backup-perms.md
src/current/cockroachcloud/cloud-api.md
src/current/cockroachcloud/managed-backups-advanced.md
src/current/cockroachcloud/managed-backups-basic.md
src/current/cockroachcloud/managed-backups.md

https://cockroachlabs.atlassian.net/browse/DOC-14703
- "Restore operations" can be used to describe the broad, non-specific act of restoration to a CockroachDB cluster. Not a reference to a specific action that may be described in the product (which likely uses the "job" label anyway)
- "Restore jobs" should be used to describe instances of restore procedures taking place in CockroachDB, especially when a it may be described in the product UI or the underlying jobs subsystem/jobs table.

Change usages of restore operations to restore jobs

---

src/current/v24.1/architecture/life-of-a-distributed-transaction.md
src/current/v24.1/transaction-retry-error-reference.md
src/current/v24.3/architecture/life-of-a-distributed-transaction.md
src/current/v24.3/transaction-retry-error-reference.md
src/current/v25.1/architecture/life-of-a-distributed-transaction.md
src/current/v25.1/transaction-retry-error-reference.md
src/current/v25.2/architecture/life-of-a-distributed-transaction.md
src/current/v25.2/transaction-retry-error-reference.md
src/current/v25.3/architecture/life-of-a-distributed-transaction.md
src/current/v25.3/transaction-retry-error-reference.md

Link from retry error reference to timestamp cache

---

src/current/v24.1/cockroachdb-feature-availability.md
src/current/v24.1/common-table-expressions.md
src/current/v24.1/temporary-tables.md
src/current/v24.3/cockroachdb-feature-availability.md
src/current/v24.3/common-table-expressions.md
src/current/v24.3/temporary-tables.md
src/current/v25.1/cockroachdb-feature-availability.md
src/current/v25.1/common-table-expressions.md
src/current/v25.1/temporary-tables.md
src/current/v25.2/cockroachdb-feature-availability.md
src/current/v25.2/common-table-expressions.md
src/current/v25.2/temporary-tables.md
src/current/v25.3/cockroachdb-feature-availability.md
src/current/v25.3/common-table-expressions.md
src/current/v25.3/temporary-tables.md

Fixes DOC-13355
- Update temp tables docs with a 'perf considerations' section that warns users about possible perf impacts incl. schema change GC risk, recommends CTEs
- Update temp table docs 'examples' section to mention CTEs as an alternative
- Update CTE docs to mention that they can be used instead of temp tables
- Update the feature availability page re: temp tables to add more info
re: schema change GC risk

Update temp tables docs re: perf caveats vs CTEs

---

src/current/_data/releases.yml

Fixes REL-2964
In releases.yml, for v25.3.1, removed cloud fields to enable binary download links and set linux_intel_fips to true.
- [v25.3.1](https://deploy-preview-20270--cockroachdb-docs.netlify.app/docs/releases/v25.3.html#v25-3-1-downloads)
- [FIPS production releases](https://deploy-preview-20270--cockroachdb-docs.netlify.app/docs/v25.3/fips.html#production-releases)

REL-2964 v25.3.1: [Docs] Adjust release notes for download/SH

---

src/current/cockroachcloud/cloud-api.md

https://cockroachlabs.atlassian.net/browse/DOC-14635

Add rate limit to CCAPI doc

---

src/current/v23.2/alter-index.md
src/current/v23.2/alter-table.md
src/current/v24.1/alter-index.md
src/current/v24.1/alter-table.md
src/current/v24.3/alter-index.md
src/current/v24.3/alter-table.md
src/current/v25.2/alter-index.md
src/current/v25.2/alter-table.md
src/current/v25.3/alter-index.md
src/current/v25.3/alter-table.md
src/current/v25.4/alter-index.md
src/current/v25.4/alter-table.md

(also `ALTER INDEX ... SCATTER`)
Fixes DOC-286

Add docs for `ALTER TABLE ... SCATTER`

---

src/current/_includes/v24.1/essential-alerts.md
src/current/_includes/v24.3/essential-alerts.md
src/current/v24.1/architecture/replication-layer.md
src/current/v24.1/cluster-setup-troubleshooting.md
src/current/v24.1/monitoring-and-alerting.md
src/current/v24.1/ui-slow-requests-dashboard.md
src/current/v24.3/architecture/replication-layer.md
src/current/v24.3/cluster-setup-troubleshooting.md
src/current/v24.3/monitoring-and-alerting.md
src/current/v24.3/ui-slow-requests-dashboard.md

Fixes DOC-14774
Backports non-leader-leases changes from
https://github.com/cockroachdb/docs/pull/19755

Backport leader-leaseholder split info to v24.*
