- install-cockroachdb.md
Completed writing up install instructions for OS X, Linux, and Windows (issue #3). "Live" version of this draft can be seen here: http://cockroach-draft-docs.s3-website-us-east-1.amazonaws.com/install-cockroachdb.html
I've assigned this to Marc, but I'd love for others to review as well, ideally performing the steps to find anything I've missed or gotten wrong. cc: @mjibson, @bdarnell, @spencerkimball, @petermattis, @andreimatei.
Some notes:
- OS tabs at the top work but still need to be styled. I might try that myself but will probably ask DivisionOf to help. 
- Links for downloading os x and linux binaries are just dummies. I'll update those once we have the binaries and know where we'll host them.
- I'm pretty confident about the mac instructions, since I'm on mac, but I'm speculating …
> draft of install instructions for osx, linux, and windows

- install-cockroachdb.md
- start-a-local-cluster.md
Fixes #30 
- Removed `--init` step from **Secure Mode** instructions.
- Added step on adding nodes to both the **Dev Mode** and **Secure Mode** instructions. 
- Tweaked the intro to mention adding additional nodes.
@spencerkimball, @mberhault, please let me know what you think. Instead of adding a third section for a "multi-node local cluster", I just added a step to each of the existing procedures. Happy to try another approach, if you prefer. 
@spencerkimball: I've used `localhost` in the secure example, even though it's currently a problem: [#4118](https://github.com/cockroachdb/cockroach/issues/4118) and [#3358](https://github.com/cockroachdb/cockroach/issues/3358).
In case you'd rather review an html version: http://cockroach-draft-docs.s3-website-us-east-1.amazonaws.com/start-a-local …
> removed --init step and added step for adding new nodes

- _data/sidebar_doc.yml
- cloud-deployment.md
- deploy-a-multinode-cluster.md
- install-cockroachdb.md
- on-premise-deployment.md
- start-a-local-cluster.md
Updated start-a-local-cluster.md to account for:
- removal of `--dev` flag
- default storage location
- attribute optional when passing `--stores` flag
@petermattis, @mberhault, please let me know if I missed anything, or if you want me to cut back or expand any explanations. I'll also be sure all of this gets into the `cockroach` CLI docs. 
I'll work on this file again once @mberhault's done with his changes to certs, @BramGruneir's done with his changes to `--store`, and @tamird's done with his changes to ports.
Fixes #47
> updates to insecure and secure startup

- _config.yml
I think this change adds full urls to sitemap and doesn't break anything else. Please take a look, @mjibson, @bdarnell.
> adding url to config

- _config.yml
It's better for SEO to either always or never use "www.", and we currently use it.
> Add `www.` to URL

- _includes/sidebar.html
- css/customstyles.css
- js/customscripts.js
This adds search inline. See screenshot. We need an API key and custom search ID to make this work. I used some from my account. See fields in the JS where you fill that in.
This works by just changing the main page contents to the search results. It currently doesn't support paging. It also doesn't change the URL. That means if you reload you'll get the old page data. It also means the back button doesn't work (i.e., won't take you to how it looked before you hit search). We can add support for all of those features, they just each take time.
I did this with custom code because it looked like dealing with all the styling issues from using google's native stuff was going to cause some bad problems.
> Add CSE inline search

- _includes/head.html
Just updated `_includes/head.html` so the page title shows up correctly. @bdarnell, look right?
> changing page title

- CONTRIBUTING.md
- improve-the-docs.md
Linking to `CONTRIBUTING.md` instead of `README.md`, and fixing link to GitHub docs on creating a local clone. Also adding link to GitHub dos on pushing to a remote.
> Updates to Improve the Docs

- int.md
Removing mention of `BIT` data type. 
Issue open to implement `INT(n)` and `BIT(n)`: https://github.com/cockroachdb/cockroach/issues/5514
> removing bit

- install-cockroachdb.md
- secure-a-cluster.md
- start-a-local-cluster.md
- Using node 2 and 3 store names that match default for node 1.
- Mentioning that each node listens on a different port, in intro.
- Adding `http://<localhost>:8080` to admin UI step.
> Tweaks to cluster startup docs 

- bool.md
- bytes.md
- decimal.md
- float.md
- int.md
- string.md
Pete,
Revised based on your comments in PR #131:
- Removed mention of "unlimited" for `string` and `bytes`.
- Removed redundant language when specifying synonyms.
- Added note that we'll support declaring a decimal as a literal (rather than casting from string or float) in a future version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/160)
> Minor revisions to data types docs

- _data/strings.yml
- install-cockroachdb-in-md.md
- install-cockroachdb.md
- manual-deployment.md
- secure-a-cluster.md
- start-a-local-cluster.md
- start-a-node.md
Instead of updating the version and build strings in multiple places, I added the `version` and `build` variables to `_data/strings.yml` and used them wherever necessary as follows:
`{{site.data.strings.version}}`
`{{site.data.strings.build}}`
Going forward, when the current version and build change, we need only update these variables. 
Fixes #173
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/174)
> using variables for version and build

- _data/strings.yml
```
$ ./cockroach-beta-20160330.linux-amd64/cockroach version|head -n 5
Build Vers:  go1.6
Build Tag:   beta-20160330
Build Time:  2016/03/30 14:53:35
Build Deps:
github.com/VividCortex/ewma                c34099b489e4ac33ca8d8c5f9d29d6eeaf69f2ed
```
Can someone check the OSX binary?
https://binaries.cockroachdb.com/cockroach-beta-20160330.darwin-10.9-amd64.tgz
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/175)
> Use beta-20130330

- configure-replication-zones.md
- manual-deployment.md
Updated configure-replication-zone.md examples to show that `zone set` echos the full zone configuration. 
Also added step to `manual-deployment.md` for configuring replication. 
@petermattis, please take a look.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/193)
> Showing echo for zone set

- CONTRIBUTING.md
- README.md
- improve-the-docs.md
The `README.md` now points to our live docs and to `CONTRIBUTING.md` for details on chipping in. 
Any feedback, @spencerkimball, @petermattis, @bdarnell? Might be good for someone to install Jekyll and test out building the docs locally.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/194)
> updating docs readme.md and contributing.md

- bool.md
- bytes.md
- create-database.md
- decimal.md
- float.md
- int.md
- release-savepoint.md
- savepoint.md
- show-index.md
- sql-statements.md
- string.md
Updated docs for `SHOW INDEX`, added some placeholder files for `savepoint` and `release savepoint`, and made other minor tweaks.
@petermattis, does the scope of the show index doc look sufficient? Trying to establish the right conventions for moving forward with sql statement docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/199)
> Docs for SHOW INDEX

- decimal.md
- string.md
Update decimal docs to cover precision and scale.
Update string docs to cover length limit. 
In response to https://github.com/cockroachdb/cockroach/pull/5750
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/200)
> Decimal precision/scale and string length

- decimal.md
- string.md
Updated `strings.md` to list `STRING(n)` as the primary form for limiting length on a string column.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/211)
> Limiting length of STRING column

- decimal.md
Updated the decimal.md page to mention that when a decimal column's precision and scale are identical, the inserted value must round to less than 1. 
In response to https://github.com/cockroachdb/cockroach/pull/5994.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/219)
> note about precision = scale

- _data/sidebar_doc.yml
- build-a-test-app.md
- create-database.md
- data-definition.md
- grant.md
- index.md
- privileges.md
- rename-table.md
- show-index.md
- sql-statements.md
- use-the-built-in-sql-client.md
Adding docs for SQL privileges, starting with the `GRANT` statement. 
@mberhault, look ok? I'll add a general page on privileges next, and then add required privileges to each statement page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/215)
> draft doc for GRANT statement

- _includes/head.html
Fixing the canonical link element to point to the `/docs` directory.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/229)
> fixing canonical link

- _includes/app/basic-sample.php
- _includes/app/txn-sample.php
Some refactoring and adds the transactional example (it's not presentable until https://github.com/cockroachdb/cockroach/issues/5758 gets fixed, but that shouldn't be long).
I tested this locally by adding a `sleep(3)` between the two transactional writes and running `for i in $(seq 0 1); do php ../docs/_includes/app/txn-sample.php& done` (which is guaranteed to see a restart).
Ping #182 - all of those transactional examples need tests even more since those wrappers might actually get picked up by production code one day.
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/183)
> php: use PDO, add transactional example

- contribute-to-cockroachdb.md
Calling out ability to open Gitter from within docs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/249)
> referencing gitter sidecar

- cloud-deployment.md
- manual-deployment.md
- start-a-local-cluster.md
@uptimeDBA wrote up a guide for running CockroachDB in a VirtualBox VM. This PR links to his guide, updates our cloud deployment docs to link to our GCE instructions, and a few other minor updates.
Fixes #262
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/263)
> Link to VirtualBox VM setup guide and other minor deployment doc updates

- start-a-local-cluster.md
- use-the-built-in-sql-client.md
Updated `cockroach sql` docs to explain how to run external commands from the shell. Added to synopsis and added examples. Also covered executing sql from command line using `echo` instead of the `-e` flag.
Thanks for supplying great, examples, @knz. Assigned to Raphael, but perhaps @mberhault can review while he's out?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/270)
> Running external commands from sql shell

- _data/sidebar_doc.yml
- back-up-and-restore-data.md
- bool.md
- bytes.md
- configure-replication-zones.md
- data-types.md
- date.md
- decimal.md
- float.md
- frequently-asked-questions.md
- int.md
- interval.md
- sql-statements.md
- string.md
- timestamp.md
- use-the-built-in-sql-client.md
Updating docs to answer some questions we've received in our Gitter channel:
- Can you execute SQL from a file? (fixes #276) @tschottdorf, please take a look at the updates to `use-the-built-in-sql-client.md`.
- Does CockroachDB support cross-region communication? (fixes #273) @bdarnell, please take a look at the updates to `configure-replication-zones.md`.
- Can you use CockroachDB as a kv store? (fixes #138) @vivekmenezes, please take a look at the question added to `frequently-asked-questions.md`.  
- What are the storage sizes for different data types? (fixes #214) @knz, please take a look at the changes to `data-types.md`, `string.md`, `bytes.md`, and `decimal.md`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" …
> Docs updates from Gitter

- data-definition.md
Previously, the "Indexes" section on `data-definition.md` said "coming soon," which mislead a user into thinking that indexes aren't already available. That "coming soon" really meant "docs coming soon."
For now, replacing that with links to related SQL statements and Radu's blog post on index selection.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/293)
> Linking to related pages on indexes

- _includes/app/txn-sample.js
- _includes/app/txn-sample.php
- _includes/app/txn-sample.py
- _includes/sql/diagrams/grammar.html
- rollback-transaction.md
- transactions.md
See cockroachdb/cockroach#6797.
We changed the error code that clients should expect for retryable
serialization errors. This change reflects how clients should react to
this new error.
Any seemingly unrelated changes here are because I ran `make`.
For now I've simply replaced the expected error code in samples, but if sample authors 
know about more idiomatic ways to catch standard PG errors from their respective drivers
(i.e. specific exceptions to catch), please let me know. 
@bdarnell @andreimatei @tschottdorf @tamird @dt
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/315)
> Document SerializationFailureError for retryable errors

- css/lavish-bootstrap.css
Using `border-bottom: 1px solid #46a417` instead of `text-decoration: underline`. This adds a bit more vertical space between word and underline.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/330)
> CSS change to improve link style on hover

- secure-a-cluster.md
~~~ shell
./cockroach quit --http-port= 8081 
~~~
returns the following error:
~~~ shell
Error: unknown flag: --http-port
~~~
`cockroach quit --help` doesn't currently list `--http-port` as a flag, but does list `--port`
Suggesting to convert syntax for quit to use `--port` flag instead
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/332)
> Change quit flag to --port

- _data/sidebar_doc.yml
- beta-20160602.md
Kind of a slow week for visible changes - a lot of work has gone into preparation for future features (ui/next, distsql, column families, dump/restore) or internal improvements with no direct user impact.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/345)
> beta-20160602 release notes

- _data/strings.yml
- beta-20160602.md
- date.md
- interval.md
- timestamp.md
Added links and doc updates to release notes.
Also update `date`, `timestamp`, and `interval` docs to reflect that you can use string literals. @nvanbenschoten
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/351)
> updates to release notes

- constraints.md
These diagrams had previously been generated and added to the `CREATE TABLE` syntax. Now adding them to the Constraints page as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/361)
> Add constraint diagrams to constraints.md

- create-table.md
Adding show/hide functionality for expanded CREATE TABLE grammar diagrams.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/363)
> basic and expanded CREATE TABLE grammar diagrams

- data-types.md
- int.md
- serial.md
Adding docs for the new `SERIAL` type. Fixes #356.
HTML version: http://cockroach-draft-docs.s3-website-us-east-1.amazonaws.com/serial.html
@paperstreet, @petermattis, not sure if the last example is clear enough.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/362)
> SERIAL type

- float.md
typo in SELECT * FROM floats example, said value in column `a` was rounded when it was actually column `b`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/370)
> Small typo in float doc example

- data-types.md
- identifiers.md
- string.md
- use-the-built-in-sql-client.md
- In `identifiers.md`, updated limitations.
- In `strings.md`, documented escape strings.
- In `use-the-built-in-sql-cliend.md`, documented `--pretty` flag for executing SQL from the command line. Also restructured the examples a bit.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/373)
> Various doc updates related to character support

- serial.md
Added `BIGSERIAL` and `SMALLSERIAL` as aliases for `SERIAL`.
Based on https://github.com/cockroachdb/cockroach/pull/7187
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/378)
> SERIAL aliases

- _includes/sql/aggregates.md
- _includes/sql/functions.md
- _includes/sql/operators.md
- functions-and-operators.md
- generate/funcs.go
This also moves the headers out of the generated includes to the containing
template -- this should make it a little easier to include hand-written
prose introducing each section (e.g. how aggregates behave).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/379)
> Split out aggregates into own section of functions doc

- _includes/sql/aggregates.md
- _includes/sql/functions.md
- generate/funcs.go
use the new Category method on parser.Builtin to categorize functions rather than the return type
In practice this means that most functions are categorized by their argument type or return type
but a couple examples of manual categorization (ID Generation and System Info) show what else
is possible
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/387)
> use self-categorized functions

- int.md
- string.md
Adding hexadecimal string literal format to `STRING` type docs and hexadecimal numeric literal format to `INT` type docs.
Fixes #377
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/392)
> hexidecimal string and numeric literals

- _includes/sql/aggregates.md
- _includes/sql/functions.md
- generate/funcs.go
* eliminate subcategorization of aggregates since the majority are numeric and the
remainder aren't meaningfully categorized by types (eg count).
* pick up the changes in builtins self-categorization that wraps up the
math functions into a single category.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/397)
> more function categorization

- start-a-local-cluster-in-docker.md
There were two step 4s.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/398)
> Fixing typo in docker quickstart

- _includes/sql/diagrams/create_index.html
- generate/main.go
This is the fully expanded syntax diagram for `CREATE INDEX` with all keywords and grammar exposed. This is really what the last one should have looked like.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/400)
> Create Index diagram - fully expanded

- _includes/sql/diagrams/truncate.html
- generate/main.go
No biggie, just expanded the `opt_drop_behavior` clause to expose the `CASCADE` and `RESTRICT` keywords, ready to be documented.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/408)
> Expand Truncate diagram

- secure-a-cluster.md
Since `secure-a-cluster.md` restarts nodes created in `start-a-cluster.md`, the store names must be the same.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/424)
> Correcting store names in secure-a-cluster.md

- _data/sidebar_doc.yml
- _data/strings.yml
- beta-20160629.md
- column-families.md
- older-versions.md
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/429)
> beta-20160629 release notes

- install-cockroachdb.md
- start-a-local-cluster-in-docker.md
This PR updates our installation and cluster startup docs based on native Docker for Mac and Docker for Windows.
- `install-cockroachdb.md` recommends Docker for Mac and Docker for Windows instead of Docker Toolbox.
- `start-a-cluster-in-docker.md` now includes using volumes to persist node data (that wasn't easy using Docker Toolbox on Mac/Windows) and simplifies accessing the Admin UI from the host (no longer need to get the VM's IP.
HTML versions here: 
- http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d38dd1c9de98e16e8e833bff7340ce43ebc201f9/install-cockroachdb.html
- http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/d38dd1c9de98e16e8e833bff7340ce43ebc201f9/start-a-local-cluster-in-docker.html
Fixes #415
I've decided not to cover a Docker-specific rewrite …
> Docker updates

- configure-replication-zones.md
- troubleshoot.md
Fixes remaining issue in https://github.com/cockroachdb/cockroach/issues/4192
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/434)
> Simplify format of single-replica zone config

- css/customstyles.css
- index.md
In advance of a larger overhaul of the docs homepage by Division Of, this PR improves the styling of the critter buttons:
- Button text is now green, to indicate they are links/clickable.
- Pre-hover, the buttons are at 80% opacity.
- On hover, the buttons are at 100% opacity and lift up a bit.
HTML version here: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/1baeec53e3c6ac25014dd18cbf37220c67c07e13/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/433)
> Updating critter buttons on docs homepage

- css/customstyles.css
This change makes it easier to differentiate code-formatted text from normal text in tables. Outside of tables, this isn't a problem since code-formatted text has a grey background.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/439)
> Bolding code formatted text in tables

- manual-deployment.md
- secure-a-cluster.md
- start-a-local-cluster.md
- start-a-node.md
Accompanies the merged fix https://github.com/cockroachdb/cockroach/pull/7475
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/443)
> Document the --http-addr flag.

- manual-deployment.md
- secure-a-cluster.md
- start-a-local-cluster.md
- start-a-node.md
This PR contains revisions/clarifications around the new `--http-addr` flag. It also removes instructions about ssh tunneling, as requested by @tamird [here](https://github.com/cockroachdb/docs/pull/443/files/ff8589c12d1b01fa78d1aa9eb55acb148aa1ff87#r70448227). 
Also, this PR tries to clarify what `--host` defaults to, depending on scenario. Fixes #446 
HTTP version available here: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/b379df2ae3f552cff5fea8bbb13a0d3178206c35
@tamird, @glycerine, PTAL
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/447)
> Revisions related to http-addr

- configure-replication-zones.md
- show-columns.md
- show-databases.md
- show-grants.md
- show-index.md
- show-tables.md
- show-time-zone.md
- show-transaction.md
Meta keywords for page on replications zones:
- ttl
- time to live
- availability zones
Meta keyword for various `SHOW` statements:
- reflection
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/456)
> adding keywords for seo

- start-a-local-cluster-in-docker.md
Docker on windows doesn't like volume tags without quotes. Following is the error. Works after adding quotes.
C:\Program Files\Docker\Docker\Resources\bin\docker.exe: Error parsing reference: "/cockroach-data/roach1:/cockroach/coc
kroach-data" is not a valid repository/tag.
See 'C:\Program Files\Docker\Docker\Resources\bin\docker.exe run --help'.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/457)
> adding quote around volume option in docker command

- interval.md
This PR adds the Postgres and ISO formats to our docs on the `INTERVAL` data type. 
Once https://github.com/cockroachdb/cockroach/issues/7916 is resolved, I'll add in mention of negative intervals.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/462)
> additional interval formats

- _data/sidebar_doc.yml
- beta-20160721.md
- older-versions.md
See cockroachdb/cockroach#7950
I'll be offline tomorrow; @jseldess please merge and fix as needed assuming the beta is going out on schedule. 
@paperstreet We're not mentioning interleaved tables yet, right?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/468)
> Release notes for beta-20160721

- _includes/feedback-widget.html
- _includes/head.html
- _layouts/page.html
- back-up-and-restore-data.md
- cockroachdb-architecture.md
- cockroachdb-in-comparison.md
- css/feedback-widget.css
- css/theme-blue.css
- explore-the-admin-ui.md
- js/feedback-widget.js
This PR adds a feedback mechanism to the bottom of every page of our docs. We're using a hubspot form to collect submitted feedback.
- When a user clicks **Yes**, we send a "yes" response, along with the current page title, to hubspot via their forms api. 
- When a user clicks **No**, we open a popup (using the [magnificent popup script](http://dimsemenov.com/plugins/magnific-popup/#mfp-build-tool)) containing the embedded hubspot form. When the user then clicks **Submit**, all completed fields, along with the current page title, are sent to hubspot.
In cases where we don't want the feedback widget to show up on a page (i.e., the page is just a placeholder), `feedback: false` can be added to the page's frontmatter.
One benefit of using hubspot is that we can track known users' actions …
> Docs feedback widget

- back-up-and-restore-data.md
- cockroach-commands.md
- learn-cockroachdb-sql.md
Fixes #470
HTML version: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/e56d57b24ab1ebb55f22c655dec41c5de7d7fd41/back-up-and-restore-data.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/472)
> docs for the dump command

- build-a-test-app.md
This PR fixes a jquery bug that was causing the `build-a-test-app.md` code samples to disappear on Safari. Somehow, the bug didn't cause problems on Chrome.
Fixes #478 
Fixes #369
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/479)
> fix jquery bug

- recommended-production-settings.md
Clarifies how CockroachDB handles file descriptors, based on https://github.com/cockroachdb/cockroach/pull/7961.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/480)
> file descriptors clarification

- _data/sidebar_doc.yml
- _includes/sidebar.html
- column-families.md
- constraints.md
- css/customstyles.css
- indexes.md
- keywords-and-identifiers.md
- learn-cockroachdb-sql.md
This PR adds a third level to the docs sidenav. This is particularly useful for sql statements and other reference areas. For example, when you're on the page for a particular statement or datatype, the sidenav now both shows you where you are in the overall structure and lets you browse other statements.
HTML version: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/86084b8591acd9bc9fea8ecd7630724132090b3c/serial.html
Fixes #186
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/476)
> adding third level to sidenav

- install-cockroachdb.md
Removing mention of command to start the docker daemon, in favor of Docker's own docs.
Fixes #452.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/484)
> linux docker install

- start-a-local-cluster-in-docker.md
On `start-a-local-cluster-in-docker.md`, the instructions for joining the second and third nodes to the cluster have the closing quotes in the wrong place. This PR fixes the problem.
Fixes #523
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/524)
> fixing error in docker command

- constraints.md
- drop-index.md
Docs on removing Foreign Key constraint using `DROP INDEX...CASCADE`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/541)
> Remove FOREIGN KEY

- _data/sidebar_doc.yml
- _includes/sql/diagrams/truncate.html
- generate/main.go
- sql-statements.md
- truncate.md
Heavily redacted the diagram that displays vs. the syntax that's accepted.
- Descendent tables don't exist, so `ONLY` and `*` are vestigial
- `CASCADE` doesn't delete rows, so everything behaves like `RESTRICT`, so no need to list either as options.
Closes #498
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/542)
> TRUNCATE doc

- _includes/footer.html
Reorder **Talk to us** links in footer. Also rename **Forum** to **Community Forum**.
Fixes #530
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/543)
> update talk to us section of footer

- _data/sidebar_doc.yml
- sql-feature-support.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/550)
> adding SQL feature support matrix

- interval.md
This PR updates the `INTERVAL` type documentation to cover the SQL standard format. 
Fixes #559
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/560)
> update to INTERVAL type documentation

- _data/sidebar_doc.yml
- _includes/develop-callout.html
- _includes/develop-paragraph.md
- bytes.md
- develop-branch.md
- install-cockroachdb.md
- int.md
- interval.md
- string.md
- timestamp.md
This PR covers how to get access to features on `develop` but not yet included in any official beta binary. 
- `install-cockroachdb.md`: Updated the build from source install instructions to mention building from code on the `develop` branch.
- `_includes/develop-paragraph.md` and `_includes/develop-callout.html`: Added reusable disclaimers to be used in docs for any feature only on `develop`. 
- `develop-branch.md`: Added a page where we can list features available only on the `develop` branch. Ideally, we'll link to the docs for the feature and list the date on which the feature was merged.
@spencerkimball, @petermattis, @bdarnell, PTAL. Ben mentioned in chat that his preference would be to leave the install docs focused on the latest beta version and use `contributing.md` to focus on …
> features-on-develop-branch

- _includes/feedback-widget.html
Previously, when a user clicked the "Yes" feedback button on a page of the docs, we would send the page title to hubspot. This PR adds the page url as well. This ensures that, when we export submission data from hubspot, we get sufficient contextual information about each submission. 
Fixes #562
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/563)
> pass page url to hubspot

- _includes/feedback-widget.html
This PR adds code to get the hubspot cookie and send it along with "Yes" feedback submissions. Thanks for the help, @d4l3k!
Fixes #564
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/568)
> docs: send hubspot cookie with "Yes" feedback submissions

- secure-a-cluster.md
- start-a-local-cluster-in-docker.md
- start-a-local-cluster.md
Moved `cockroach stop` command from the beginning of `secure-a-cluster` to end of `start-a-local-cluster`.
Closes #553
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/581)
> Move stop command in getting started section

- _includes/topnav.html
To drive more traffic to the forum, and to align with the rest of the site, this PR adds **FORUM** to the desktop and mobile topnavs. 
Fixes #582
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/583)
> docs: add forum to topnav

- _data/sidebar_doc.yml
- beta-20160829.md
- older-versions.md
I'm being optimistic here and assuming that the GRPC change will make us stable enough to do a release this week. 
Counts in the "Contributors" section are based on the master branch as
of d0a4a64
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/579)
> Draft release notes for beta-20160825

- _data/sidebar_doc.yml
- orchestrate-cockroachdb-with-kubernetes.md
This PR adds a new page explaining how to test out CockroachDB on Kubernetes using `minikube` and the alpha Pet Set feature. It's based on @tschottdorf's and @a-robinson's  CockroachDB example files in the [Kubernetes repo](https://github.com/kubernetes/kubernetes/tree/master/examples/cockroachdb). 
This still needs quite a bit of work, but I want to get some initial feedback.
Fixes #506
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/584)
> docs: running cockroachdb on kubernetes locally

- beta-20160407.md
- beta-20160414.md
- beta-20160421.md
- beta-20160428.md
- beta-20160505.md
- beta-20160512.md
- beta-20160519.md
- beta-20160526.md
- beta-20160602.md
- beta-20160609.md
- beta-20160616.md
- beta-20160629.md
- beta-20160714.md
- beta-20160721.md
- beta-20160728.md
- beta-20160829.md
This PR adds mac and linux binary links to each beta release notes page.
Fixes #604 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/604)
> Add binary links to release notes

- configure-replication-zones.md
Add `--file` flag to `configure-replication-zones.md` and update examples.
I'll open a separate PR to handle the new zone config format and other related changes on `develop`.
Fixes #601
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/602)
> Add --file flag to zone config docs

- develop-branch.md
- int.md
- timestamp.md
This PR removes mention of the ability to create timestamps with nanoseconds, adds the `INT8` alias for the `INT` data type, and adds this change to the list of features/changes only on `develop`. 
Fixes #559
Fixes #597 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/603)
> Remove nanoseconds and add INT8 alias

- bytes.md
This PR clarifies that `BYTES` columns accept string literals as well as octets and hex digits.
Fixes #427
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/606)
> Clarify bytes format

- create-table.md
I'm assuming this is a typo a show columns uses the method of  unique_rowid() and not unique_row(id)
```
root@:26257> show columns from urlmap;
+--------------------+--------------+-------+------------------+
|       Field        |     Type     | Null  |     Default      |
+--------------------+--------------+-------+------------------+
| geturl_name        | STRING(50)   | false | NULL             |
| geturl_description | STRING(2048) | true  | NULL             |
| date_added         | DATE         | true  | "CURRENT_DATE"() |
| true_url           | STRING(2048) | true  | NULL             |
| rowid              | INT          | false | unique_rowid()   |
+--------------------+--------------+-------+------------------+
(5 rows)
root@:26257>
```
---
This change is [<img …
> fix typo of unique_rowid(). Was unique_row(id)

- troubleshoot.md
Troubleshooting steps to solve issue for starting a node, stopping it, and then trying to get the same machine to start a new node joining a different cluster.
Also a few misc. improvements to the troubleshooting doc.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/610)
> --join troubleshooting for existing data directory

- use-the-built-in-sql-client.md
Add note explaining that the import from sql example works only with numbers. 
Fixes #608
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/620)
> Add note: Import from sql example works only with numbers

- _includes/feedback-widget.html
Previously, we requested more detail for negative but not for positive docs feedback submissions. Now, when users click "Yes", they get a popup asking them to tell what they liked about the page and to provide an email address. Both are optional. 
If it turns out that this added step is discouraging users from submitting positive feedback, we can revert to our former approach.
Fixes #624
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/625)
> Request more details for positive feedback submissions

- _data/sidebar_doc.yml
- cloud-deployment.md
- deploy-cockroachdb-on-aws.md
- deploy-cockroachdb-on-google-cloud-platform.md
- manual-deployment.md
- Steps for manually deploying CockroachDB on GCE
- Changes structure for Cloud Deployment docs to optimize for SEO (1 page per provider) and modularity (expands TOC to include individual providers)
- Stub for AWS using existing Terraform info
- Provides general guidance for any cloud environment
Closes #509
@mberhault –– Can you review?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/574)
> GCE and general cloud deployment improvements

- manual-deployment.md
- secure-a-cluster.md
Add step for stopping nodes.
Fixes #614
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/619)
> Add quit step to Manual Deployment docs

- develop-branch.md
- start-a-node.md
In response to https://github.com/cockroachdb/cockroach/pull/9066, this PR updates the `cockroach start` docs to include additional fields printed to `stdout` on node startup and adds this to the list of changes on the `develop` branch. 
In the `cockroach start` docs, a **Beta** vs. **Develop** toggle lets users get correct details for their version, whether the latest official beta binary or a binary build from `develop`.
HTML version for review: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/a61135e8a55bba5414f54e00578e4d3feadee40f/start-a-node.html#standard-output
Fixes #627
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/642)
> Additional details in stdout on node startup

- transactions.md
Addresses the docs part of #646.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/647)
> Fix the example error message for retryable transactions.

- timestamp.md
This PR changes all timezone offsets from `H:MM` to `HH:MM` and updates the example to use the `TIMESTAMPTZ` column type.
Fixes #644
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/645)
> Fix timezone offset format and example

- start-a-local-cluster-in-docker.md
- start-a-local-cluster.md
This PR makes the following updates to our "start a local cluster" docs: 
- Clarify that running a multi-node local cluster makes sense for testing purposes only. 
- Suggest manually setting each node's cache size when running multiple nodes on a single host. 
HTML versions here: 
- http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c3b7fe6f5084c057268ff10b658a26b39668f1a8/start-a-local-cluster.html
- http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/c3b7fe6f5084c057268ff10b658a26b39668f1a8/start-a-local-cluster-in-docker.html
Fixes #651 
@mberhault, @knz, @bdarnell
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/652)
> Clarify local cluster startup docs

- _data/sidebar_doc.yml
- beta-20160915.md
- older-versions.md
Based on commit d262ae331, which is currently running on the test clusters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/654)
> Release notes for beta-20160915

- _data/strings.yml
- beta-20160915.md
- install-cockroachdb.md
This PR adds doc updates to the release notes and reverts the minimum required Git version for building from source.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/662)
> Update beta-20160915 release notes

- start-a-local-cluster-in-docker.md
Make it so that copying and pasting the command directly into a terminal works, not leaving off the last line.
@jseldess
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/664)
> Add missing backslash to fix multi-line command

- _data/sidebar_doc.yml
- _includes/sql/diagrams/set_database.html
- generate/main.go
- set-database.md
This PR completes our docs on `SET DATABASE`. 
Fixes #451 
Fixes #495
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/671)
> SET DATABASE docs

- _data/sidebar_doc.yml
- _includes/sql/diagrams/show_database.html
- generate/main.go
- show-database.md
- sql-statements.md
Adding docs for the `SHOW DATABASE` statement.
Fixes #683 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/683)
> SHOW DATABASE docs

- _includes/sql/diagrams/rename_column.html
- generate/main.go
- rename-column.md
Documents `ALTER TABLE RENAME COLUMN...`
Closes #489
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/678)
> RENAME COLUMN doc

- _includes/head.html
pages with index.html in url have incomplete urls for the canonical links
/docs/create-index.html
/docs/drop-index.html
/docs/rename-index.html
/docs/show-index.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/702)
> canonical link fix

- _config.yml
- _includes/head.html
Adding `https://www.cockroachlabs.com` to canonical URL, per [Google's advice](https://support.google.com/webmasters/answer/139066?hl=en).
@jess-edwards first step in fixing URLs. The other work items will be moved into Team City.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/725)
> Canonical URL to include domain

- _data/sidebar_doc.yml
- _data/strings.yml
- beta-20161006.md
- older-versions.md
Based on https://github.com/cockroachdb/cockroach/issues/9752
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/728)
> beta-20161006 release notes

- beta-20160929.md
To track mac and linux binary downloads from release notes pages, I created new Google Tags/Triggers. Here I'm adding the corresponding data-eventcategory attributes to the links on just one release note page so we can verify that the change works. I've also changed the binary links from text to OS buttons.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/730)
> tracking installs from release notes

- beta-20160407.md
- beta-20160414.md
- beta-20160421.md
- beta-20160428.md
- beta-20160505.md
- beta-20160512.md
- beta-20160519.md
- beta-20160526.md
- beta-20160602.md
- beta-20160609.md
- beta-20160616.md
- beta-20160629.md
- beta-20160714.md
- beta-20160721.md
- beta-20160728.md
- beta-20160829.md
- beta-20160908.md
- beta-20160915.md
- beta-20160929.md
- beta-20161006.md
This PR updates the binary links on all past release notes. The links are now OS buttons with a `data-eventcategory` attribute that lets us track left-click and right-click installs.
Fixes #731
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/733)
> update binary links on all past release notes

- recommended-production-settings.md
- start-a-local-cluster-in-docker.md
This PR updates our minimum and recommended file descriptors limits based on PR https://github.com/cockroachdb/cockroach/pull/9679.
Fixes #704
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/715)
> file descriptors update

- back-up-and-restore-data.md
- configure-replication-zones.md
- create-security-certificates.md
- generate-cli-utilities-and-example-data.md
- start-a-node.md
- stop-a-node.md
- use-the-built-in-sql-client.md
- view-node-details.md
- view-version-details.md
Based on an informal internal survey, the `cockroach <command> --help` syntax seems more standard/intuitive than what's currently in the docs: `cockroach help <command>`. This PR updates the cockroach command docs accordingly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/765)
> Recommend --help for getting cli help

- _includes/sql/diagrams/grammar.html
- _includes/sql/diagrams/set_transaction.html
`LOCAL` was marked as unimplemented in https://github.com/cockroachdb/cockroach/pull/10289. This PR removes `LOCAL` from the full grammar and from the `SET TRANSACTION` diagram. 
Fixes #802
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/803)
> Remove LOCAL from set diagrams

- sql-feature-support.md
Mark interleaved tables and views as supported, and link to the corresponding documentation.
@sploiselle, know of any other updates to make?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/804)
> Update sql feature support page

- _data/sidebar_doc.yml
- _includes/sql/diagrams/begin_transaction.html
- _includes/sql/diagrams/commit_transaction.html
- _includes/sql/diagrams/iso_level.html
- _includes/sql/diagrams/release_savepoint.html
- _includes/sql/diagrams/rollback_transaction.html
- _includes/sql/diagrams/savepoint.html
- _includes/sql/diagrams/set_transaction.html
- begin-transaction.md
- commit-transaction.md
- generate/main.go
- release-savepoint.md
- rollback-transaction.md
- savepoint.md
- set-transaction.md
- show-transaction.md
- transactions.md
Contains documents for:
- `BEGIN`
- `COMMIT`
- `SET TRANSACTION`
- `SAVEPOINT cockroach_restart`
- `RELEASE SAVEPOINT cockroach_restart`
- `ROLLBACK`
- `SHOW TRANSACTION`
And integrates these links into `transactions.html`
Closes #491, #254, #253
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/672)
> Transaction-based SQL docs

- index.md
Refreshing all blog links on the docs homepage to point to more recent posts.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/816)
> Update blog listings on docs home

- create-view.md
- show-create-view.md
- views.md
This PR updates our views overview and `CREATE VIEW` doc to mention that you can list views by querying `pg_catalog.pg_views`.
Fixes #807
Fixes #812 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/811)
> List views via pg_catalog.pg_views

- _config.yml
- _includes/google_tag_manager.html
- _layouts/default.html
While looking into why the bounce rate on docs pages is off (issue #661), DivisonOf noticed that the docs site has a GA script and Tag Manager. This is duplicative because GA is installed sitewide through Tag Manager. They think this redundancy may affect bounce rate because two pageview events are sent when a page loads.
This PR removes the GA script.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/840)
> Remove ga script

- _includes/feedback-widget.html
When you submit feedback through the **No** link in the feedback widget, the following items are pre-populated:
- **Title**: Issue on docs for *page.title*
- **Body**: Please include specific details about the section with the issue, as well as steps we can take to reproduce any problems you found.
Closes #844
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/854)
> Dynamic issue title for feedback widget

- _includes/app/basic-sample.rs
- _includes/app/txn-sample.rs
The current postgres driver for Rust has some changes that break the current Rust example.
SslMode has been replaced with TlsMode.
Transaction has been moved into the transaction module.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/863)
> Fix Rust samples with changes to postgres driver

- interval.md
Update docs on the sql standard interval format to `Y-M-D H:M:S`.
Fixes #831
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/867)
> update sql standard interval format

- drop-index.md
- drop-table.md
- rename-column.md
- rename-database.md
- rename-index.md
- rename-table.md
This PR updates docs to clarify that you can't rename database, table, column, or index reference by a view.
Will document index hints generally in a separate PR. Still need to document drop column as well.
Fixes #789 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/873)
> Additional docs on view dependencies

- cockroach-commands.md
Update "Logging Flags" intro to clarify that, when `--log-dir` is not set on a client command, CockroachDB logs to `stderr` instead. We used to log to temp directories in this case.
Fixes #884
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/885)
> Update logging flags intro

- _includes/sql/diagrams/select.html
- generate/main.go
- indexes.md
- select.md
Added detail to `SELECT` about index hints, as well as changed link in `indexes.md` from `CREATE INDEX`'s section on using an index to the new section in `SELECT`.
@RaduBerinde Can I get you to review for technical accuracy?
Closes #872
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/894)
> index hints

- deploy-cockroachdb-on-microsoft-azure-insecure.md
- deploy-cockroachdb-on-microsoft-azure.md
Removed inadvertent links to GCE docs
Closes #903
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/904)
> fixing azure doc links

- _data/sidebar_doc.yml
- _includes/sql/diagrams/create_user.html
- back-up-and-restore-data.md
- build-a-test-app.md
- cockroach-commands.md
- create-and-manage-users.md
- create-security-certificates.md
- create-user.md
- deploy-cockroachdb-on-aws-insecure.md
- deploy-cockroachdb-on-aws.md
- deploy-cockroachdb-on-digital-ocean-insecure.md
- deploy-cockroachdb-on-digital-ocean.md
- deploy-cockroachdb-on-google-cloud-platform-insecure.md
- deploy-cockroachdb-on-google-cloud-platform.md
- generate/main.go
- grant.md
- privileges.md
- sql-statements.md
- use-the-built-in-sql-client.md
Includes documentation for `cockroach user`, which creates password auth.
Supporting documentation also included.
Closes #870
Closes #741
Closes #474
Closes #336
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/838)
> cockroach user command

- CONTRIBUTING.md
- _includes/expand.html
- _includes/head.html
- _layouts/default.html
- _layouts/page.html
This PR enables docs pages to be included in Optimizely A/B testing. For now, rather than add the Optimizely JS to every page of the docs, we're using a front-matter label to manage this on a page-by-page basis; when `optimizely: true` is set in a page's front-matter, the Optimizely JS is fetched in the page's header.
This PR also updates `CONTRIBUTING.md` to cover our feedback widget and optimizely, and it simplifies the conditional logic for inclusion of asciicasts and expand/collapse functionality.
Fixes #906
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/909)
> Add optimizely script

- js/customscripts.js
Adds conditional checks for mobile nav to be rendered on page at all; prevents scrolling issue that was causing it to flicker on page as identified in #69.
Closes #69
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/910)
> fixing scroll issue with mobile nav

- _config.yml
- _data/sidebar_doc.yml
- beta-20161201.md
- choose-a-deployment-profile.md
- recommended-environments.md
- set-database.md
- sql-statements.md
This PR removes mention of `SET APPLICATION_NAME` in favor of adding it later with other such variables. It also removes a few old stub pages.
Partially addresses #918
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/919)
> Remove unnecessary pages

- .gitattributes
this prevents it from diffing or trying to merge changes in the generated map, since it should be re-generated via sass to handle merging.
`-merge` tells git not to try to merges changes to a file on its own, but rather to mark it conflicted if two commits both try to change it and let the human fix it -- since these are generated from another file, changes to them generally should not be merged, but rather the changes in the source files merged and the derivative file re-generated in its entirety. 
`binary` implies `-merge` as well as `-diff`, which prevents showing diffs by default, which makes sense for the `.map` since it isn't human readable.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> mark generated css as binary in git

- _data/sidebar_doc.yml
- _includes/sql/diagrams/add_column.html
- _includes/sql/diagrams/add_constraint.html
- _includes/sql/diagrams/alter_column.html
- _includes/sql/diagrams/alter_table.html
- _includes/sql/diagrams/drop_column.html
- _includes/sql/diagrams/drop_constraint.html
- add-column.md
- add-constraint.md
- alter-column.md
- alter-table.md
- drop-column.md
- drop-constraint.md
- generate/main.go
- sql-statements.md
Closes #874
Closes #738
Closes #737
Closes #736
Closes #735
Closes #705
Closes #252
#934 still open
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/950)
> ALTER TABLE statement as multiple pages

- install-cockroachdb.md
This PR updates the build from source prerequisites in the docs to match the prerequisites in the cockroach [`CONTRIBUTING`](https://github.com/cockroachdb/cockroach/blob/master/CONTRIBUTING.md).
Fixes #961
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/962)
> Update build from source prerequisites

- interval.md
This PR simply changes the SQL standard interval format from `INTERVAL 'Y-M-D H:M:S'` to `INTERVAL 'Y-M D H:M:S'` for postgres compatibility. 
@knz, PTAL and let me know if any additional details need to be added.
Fixes #951
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/963)
> change sql standard format for postgres compatibility

- frequently-asked-questions.md
In [this FAQ](https://www.cockroachlabs.com/docs/frequently-asked-questions.html#can-i-use-cockroachdb-as-a-key-value-store) about using a SQL table as an alternative to direct access to the key value store, we unnecessarily suggest grouping the columns into a single column family. It's unnecessary because when creating a two column table with one column as the primary key, both columns get placed in the same primary key family automatically. This PR therefore removes the unnecessary suggestion.
Fixes #966
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/968)
> Remove unnecessary column family suggestion

- cockroachdb-in-comparison.md
- frequently-asked-questions.md
- index.md
At @swatikumar16's request, this PR adds the optimizely script to `cockroachdb-in-comparison`, `frequently-asked-questions`, and `index`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/980)
> Turn on optimizely on comparison matrix, faq, and docs home

- beta-20160407.md
- beta-20160414.md
- beta-20160421.md
- beta-20160428.md
- beta-20160505.md
- beta-20160512.md
- beta-20160519.md
- beta-20160526.md
- beta-20160602.md
- beta-20160609.md
- beta-20160616.md
- beta-20160629.md
- beta-20160714.md
- beta-20160721.md
- beta-20160728.md
- beta-20160829.md
- beta-20160908.md
- beta-20160915.md
- beta-20160929.md
- beta-20161006.md
- beta-20161013.md
- beta-20161027.md
- beta-20161103.md
- beta-20161110.md
- beta-20161201.md
- beta-20161208.md
- beta-20161215.md
- beta-20170105.md
- install-cockroachdb.md
In an effort to increase email sign up for product release notes, this PR:
- Moves email sign up to the top of each release notes page.
- Revises email sign up copy on the install page.
Fixes #981
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/982)
> Email signup for product release notes

- _includes/app/TxnSample.java
- build-a-test-app.md
Add example code for transaction retry logic. Compilation and
execution instructions are in a comment in the main code file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/987)
> Test App: Add Java code for transaction retries

- timestamp.md
fixing issue from #977
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/996)
> typo in timestamp casting table

- beta-20170112.md
The change to MaxOffset requires a stop-the-world upgrade.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/997)
> Add stop-the-world warning to this week's release notes.

- beta-20160407.md
- beta-20160414.md
- beta-20160421.md
- beta-20160428.md
- beta-20160505.md
- beta-20160512.md
- beta-20160519.md
- beta-20160526.md
- beta-20160602.md
- beta-20160609.md
- beta-20160616.md
- beta-20160629.md
- beta-20160714.md
- beta-20160721.md
- beta-20160728.md
- beta-20160829.md
- beta-20160908.md
- beta-20160915.md
- beta-20160929.md
- beta-20161006.md
- beta-20161013.md
- beta-20161027.md
- beta-20161103.md
- beta-20161110.md
- beta-20161201.md
- beta-20161208.md
- beta-20161215.md
- beta-20170105.md
- beta-20170112.md
@jseldess found a bug on release note pages causing the feedback buttons to not work. Culprit was unescaped apostrophes in page titles. Fix is converting those to the HTML representation of an apostrophe (instead of the literal `'`).
Note that this has to be done for all page titles in the future, as well, or those buttons will continue to break. Can discuss another strategy for a permanent fix in person.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1001)
> Convert apostrophes in page titles to HTML rep

- _data/sidebar_doc.yml
Fixes a typo in the docs sidenav.
Fixes #1003
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1005)
> Fix typo in sidenav

- frequently-asked-questions.md
- strong-consistency.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1002)
> Improve the phrasing of the page "strong consistency"

- deploy-cockroachdb-on-microsoft-azure-insecure.md
- deploy-cockroachdb-on-microsoft-azure.md
`binaries.cockroachdb.com` is not consistently working on Microsoft Azure; @mberhault suggests changing URL to point directly to Amazing S3 where binaries are hosted.
@jseldess PTAL
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1011)
> Update binary URL for Azure

- back-up-and-restore-data.md
This PR expands the `cockroach dump` docs to cover dumping multiple tables as well as choosing whether to dump a table's schema, data, or both. 
Fixes #991
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1010)
> update cockroach dump

- _data/alerts.yml
- beta-20170112.md
- sql-grammar.md
This PR adds a note to the top of the full SQL grammar page encouraging users to checkout the statement-specific pages first. 
It also adds a link to the warning in the beta-20170112 release notes. 
Fixes #1013
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1014)
> Note on grammar page

- _data/alerts.yml
- sql-grammar.md
In https://github.com/cockroachdb/docs/pull/1017, we changed the "alerts" to allow markdown in addition to HTML, but I missed that this change has caused alerts to not close properly. Reverting to allow only HTML inside alerts to fix the problem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1020)
> Remove flag to use markdown inside alerts

- index.md
- learn-cockroachdb-sql.md
This PR update links to point to our 1.0 Roadmap issue; they used to point to the github wiki. It also links to the newest blog post from the docs homepage.
Fixes #1022 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1023)
> Link updates

- bool.md
- bytes.md
- data-types.md
- date.md
- decimal.md
- float.md
- int.md
- interval.md
- serial.md
- sql-constants.md
- sql-expressions.md
- sql-feature-support.md
- sql-statements.md
- string.md
- table-expressions.md
- timestamp.md
Fixes #992.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1008)
> New docs on expressions and constants

- _data/sidebar_doc.yml
- sql-constants.md
- sql-expressions.md
- sql-statements.md
- table-expressions.md
This PR exposes in the sidenav the new pages on expressions and constants added in https://github.com/cockroachdb/docs/pull/1008. Plus some minor cleanup.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1025)
> Expressions in sidenav

- show-columns.md
This PR updates `show-columns.md` to show `indices` in the response.
Fixes #1043
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1048)
> add indices to show columns response

- _includes/sql/aggregates.md
- _includes/sql/functions.md
Regenerate built-in function docs to add:
- `col_description()`
- `format_type()`
- `unnest()`
And a bunch of `pg_catalog` compatibility functions. Note: I'll open a cockroach PR to update some descriptions and the regenerate these before merging.
Fixes #1045 
Fixes #1044 
Fixes #1041 
Fixes #1039 
Fixes #1038
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1047)
> Regenerate func docs

- set-database.md
- sql-expressions.md
- sql-name-resolution.md
- table-expressions.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1050)
> Tell a bit more about SQL name resolution.

- _data/sidebar_doc.yml
- show-all.md
- sql-name-resolution.md
This PR adds the `MAX_INDEX_KEYS`, `SEARCH_PATH`, and `SERVER_VERSION` variables to the `SHOW ALL` statement documentation. Fixes #933. Fixes #790.
It also changes the **Develop** sidebar a bit:
- New subsection called `SQL Syntax` to better house topics like constants, keywords, expressions, and the full grammar.
- Moved SQL Feature Support from **Learn How It Works** to **Develop** for greater visibility.
@knz, the addition of `search_path` to the `show all` docs goes well with your PR on name resolution. I'll get that reviewed in the morning. If we merge that first, I can link to those docs from the `search_path` description on the `show all` page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …
> Update SHOW ALL docs and sidebar

- frequently-asked-questions.md
Adds FAQ on how CockroachDB is both highly available and strong consistent without violating CAP (using @bdarnell's language from the forum). Updates FAQs on when CockroachDB is a good fit and when not (using @dianasaur323's suggestions).
Fixes #824 
Fixes #778
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1061)
> Faq updates

- explore-the-admin-ui.md
Realized that the admin UI port wasn't listed in this doc and figured it would be somewhat useful to include it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1060)
> Adding port to admin UI doc

- _includes/app/gorm-basic-sample.go
As discussed, this is meant to mirror `basic-sample.go`.
I believe the naming convention here should also apply for ORM samples
that require multiple files, such as Hibernate. A Hibernate sample might
be ZIP'ed and be named `hibernate-basic-sample.zip`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1054)
> Basic sample for GORM

- column-families.md
- create-table.md
Updates to reflect that we now group all columns into a single family by default.
Fixes #1052 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1058)
> Update column family docs

- _includes/start_in_docker/mac-linux-steps.md
- install-cockroachdb.md
- start-a-local-cluster-in-docker.md
- start-a-local-cluster.md
This PR updates `install-cockroachdb.md` and `start-a-local-cluster-in-docker.md` to account for issues reported in https://github.com/cockroachdb/docs/issues/907. Specifically:
- In `start-a-local-cluster-in-docker.md`, we now offer different instructions per OS. Importantly, for Windows, we now provide correct instructions for mounting a host directory as a volume. Also, at the top, we now warn that running CockroachDB in Docker is not easy and not recommended for production; we suggest orchestration tools instead. 
- In `install-cockroachdb.md`, the docker install method for mac and linux now discourages all but Docker experts for running in Docker. The windows install section also starts with a warning about running CockroachDB in Docker and suggests orchestration tools instead.
Fixes …
> Improve docs for running CockroachDB in Docker

- install-cockroachdb.md
In https://github.com/cockroachdb/docs/pull/1095, forgot to mention that you need to share local drives.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1097)
> Share local drives for docker for windows

- start-a-local-cluster-in-docker.md
This PR reuses the javascript from `build-a-python-app-with-cockroachdb.md` to show/hide content based on the OS button selected, and to get the toc to pick up only visible headers.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1098)
> Add toc on start-a-local-cluster-in-docker.md

- build-a-java-app-with-cockroachdb.md
- build-an-app-with-cockroachdb.md
This PR updates the java "build an app" tutorial to cover both the jdbc driver and the Hibernate ORM.
@jordanlewis, @cuongdo, not sure if the "Run the Java code" step is as clear as it should be. Please don't hold back.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1100)
> Update java "build an app" tutorial

- sql-feature-support.md
User gave negative docs feedback on search results for `sequence`. That keyword shows up in the `SERIAL` docs, but on our SQL Feature Support list, we don't reference `SERIAL` in the `Sequences` entry. This PR fixes that.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1102)
> reference serial from sequences

- _includes/start_in_docker/mac-linux-steps.md
- start-a-local-cluster-in-docker.md
In https://github.com/cockroachdb/docs/pull/1095#pullrequestreview-22682485, @a-robinson pointed out that we don't need to map container ports to the host for nodes 2 and 3 since we already do so for node 1. This PR therefore removes the `-P` flag from the `docker run` commands for container/node 2 and container/node 3.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1121)
> Remove container/host port mapping for nodes 2 and 3

- int.md
- sql-constants.md
This PR adds a `Length` section to our `INT` type docs. That section covers using `BIT(n)` to limit decimal integer values based on the length of their corresponding binary integer values. 
@knz, @bdarnell, did I miss or get anything wrong? Also, @knz, do we need to update the `Supported Casting & Conversion` section?
Fixes #580
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1116)
> Add BIT(n) to INT docs

- deploy-cockroachdb-on-digital-ocean.md
Secure deployment instructions for DigitalOcean mistakenly say that they're for an insecure deployment. Fixing typo.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1128)
> fixing typo for secure DO deployment

- create-table.md
- frequently-asked-questions.md
- serial.md
This PR adds an FAQ on auto-generating unique row IDs, and it adds an example to the `CREATE TABLE` doc.
Fixes #188
Fixes #376 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1126)
> More docs on auto-generating ids

- install-cockroachdb.md
Fixes #1046
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1130)
> Document command to build open source binary

- create-table.md
- frequently-asked-questions.md
Updated FAQ and added an example to `CREATE TABLE` page.
Fixes #1109
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1122)
> Improve guidance on using a SQL table as an alternative to direct key-value access

- deploy-cockroachdb-on-aws-insecure.md
- deploy-cockroachdb-on-aws.md
- deploy-cockroachdb-on-digital-ocean-insecure.md
- deploy-cockroachdb-on-digital-ocean.md
- deploy-cockroachdb-on-google-cloud-platform-insecure.md
- deploy-cockroachdb-on-google-cloud-platform.md
- deploy-cockroachdb-on-microsoft-azure-insecure.md
- deploy-cockroachdb-on-microsoft-azure.md
- Remove extra word in aws deployment tutorials.
- Fix `SHOW DATABASES` output in all cloud deployment tutorials.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1134)
> Minor fixes to cloud deployment tutorials

- start-a-node.md
Additional fields added to `stdout`, and details written to the `INFO` log as well.
Fixes #1144
Fixes #1143 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1149)
> stdout for cockroach start

- install-cockroachdb.md
If cockroachdb/cockroach#14082 lands, this will update the docs with the new,
shorter URL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1177)
> shorten Homebrew link by using our new tap

- create-and-manage-users.md
- create-security-certificates.md
Improvements for client certificate documentation including:
- Mention that client certificates must be created for users
- Easier-to-read synopsis and examples for creating certs
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1186)
> client certificate doc improvements

- install-cockroachdb.md
- Add command to move cockroach binary into `PATH`.
- Add note to homebrew and build from source install methods that building can take 10+ minutes.
Fixes #1175 
Fixes #1193
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1196)
> Minor improvements to install instructions

- _includes/newsletter-popout.html
Loading multiple Hubspot forms on the same page without specifying targets can cause rendering issues. This adds a target property to the two popup forms in the footer, which should fix the bug where some users don't see a form field in the modal.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1204)
> add targets to newsletter hubspot forms

- install-cockroachdb.md
In install from binary instructions,
suggest using `sudo` only if permissions require it.
Fixes #1175
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1205)
> No sudo in command to move binary into PATH

- _includes/app/basic-sample.go
- _includes/app/txn-sample.go
- insert.md
I notice that there's a little inconsistency in the use of `log.Fatal` vs. `log.Fatalf`, not a big deal but might be something worth standardizing in the docs on a larger scale at some point?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1272)
> Fix typo: connection -> connecting

- _includes/sql/diagrams/rollback_transaction.html
- generate/main.go
- rollback-transaction.md
- savepoint.md
- transactions.md
- fix SQL diagram for ROLLBACK
- consistently use ROLLBACK TO SAVEPOINT cockroach_restart
instead of ROLLBACK TO cockroach_restart
Fixes #1294
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1296)
> Updates to ROLLBACK docs

- _data/sidebar_doc.yml
- _includes/faq/auto-generate-unique-ids.html
- _includes/faq/simulate-key-value-store.html
- _includes/faq/when-to-interleave-tables.html
- beta-20170309.md
- create-table.md
- frequently-asked-questions.md
- interleave-in-parent.md
- sql-faqs.md
As we identify more and more FAQs, we need a good way
to make answers to these questions easily accessible/searchable
in the docs. This PR offers one possible approach: Adding
an FAQs section to the sidenav, with categories of FAQs broken
into distinct pages. For example, in addition to the general
FAQ we've had for some time, I've added a page on SQL-specific
FAQs.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1315)
> Answer more FAQs in the docs

- create-security-certificates.md
As of https://github.com/cockroachdb/cockroach/pull/15306, the default
certificate lifetime is 10 years for all certificate types.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1330)
> Update certificate lifetime defaults.

- _data/sidebar_doc.yml
- porting-postgres.md
Fixes #1327
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1328)
> add porting postgres page

- _includes/app/basic-sample.clj
- _includes/app/txn-sample.clj
- _includes/app/util.clj
* It's customary in Clojure to group parentheses at the end of a line
* Predicates in Clojure are named with a `?` suffix, rather than a `p`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1339)
> Adjust formatting in Clojure example

- _includes/app/basic-sample.js
There's no functional difference here, but it's a bit more consistent
with all the other uses to change these ones, especially because the
styling on the page highlights double-quoted strings a different colour
than single-quoted strings.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1341)
> Use single quotes throughout JS example

- _includes/app/activerecord-basic-sample.rb
- _includes/app/basic-sample.rb
There isn't really a standard style for this in Ruby as far as I'm
aware, so I arbitrarily chose standardizing on single quotes because I
like the colour they highlight to on the docs page better. There's one
use of double quotes left because it uses string interpolation (which
single quotes disallow).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1343)
> Use single quotes throughout ruby example

- _data/sidebar_doc.yml
- cluster-settings.md
- diagnostics-reporting.md
- show-all.md
- sql-statements.md
- start-a-node.md
- Add page on diagnostic metrics sent to Cockroach Labs and how to opt out.
- Add page on how to view and change cluster-wide settings.
- Add note about cluster-wide settings to `cockroach start` docs.
- Update SQL reference docs concerning cluster-wide settings.
- Add new pages to the sidenav.
Partly address #1277.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1336)
> Diagnostics reporting and global settings

- diagnostics-reporting.md
Fixes #1362 
In a later PR, will add more detailed documentation on the built-in table that clients can use to get these stats for themselves.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1367)
> Add SQL query stats to diagnostics page

- _data/releases.yml
This was an oversight when landing the new releases page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1374)
> mark beta-20170406 as withdrawn on releases page

- install-cockroachdb.md
Link directly to the archive instead of using latest. 
Latest is not working. See https://github.com/cockroachdb/cockroach/issues/15727.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1376)
> Update Windows archive link

- _data/sidebar_doc.yml
- upgrade-cockroach-version.md
Work toward #1182 (not closing because this is only the manual process without any kind of ops-minded automation)
@mberhault or @bdarnell Do either of you have any guidance on improving this process or additional guidance we should include? e.g., if more than 5 minutes passes before rejoining the node to the cluster, wait for 5 more minutes to ensure you don't freeze the cluster.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1338)
> manual rolling upgrade docs

- index.md
@jess-edwards, @sploiselle, @kuanluo, I added a very basic 1.0 callout to the docs homepage. Due to ongoing conversations about whether or not to have detailed 1.0 release notes, I'm not yet sure where the link will take users, perhaps to Spencer's blog post. 
In any case, thoughts about the callout working and styling? 
You'll notice that I also updated the product summary to match our main homepage. Happy to change that back if you all prefer the older text here.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1382)
> Add 1.0 callout to docs home

- sql-feature-support.md
Fix #1395 by stating that window functions are a standard feature.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1396)
> Window Functions are SQL standard

- install-cockroachdb.md
Document the new build-from-source dependencies: CMake and XZ Utils. See
cockroachdb/cockroach#14840 and cockroachdb/cockroach#15060 for details.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1397)
> update build-from-source instructions with cmake and xz

- install-cockroachdb.md
A bare `make` tries to run linters that fail in a source tarball. This will be fixed upstream eventually, but point users at the `make build` command for now, which actually does what it should.
See cockroachdb/cockroach#15909 and cockroachdb/cockroach#15923.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1413)
> build from source should use `make build`, not `make`

- null-handling.md
one ascii table on this page wasn't escaped properly, causing the layout to break.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1419)
> fixed broken layout (ascii table)

- known-limitations.md
Gave it a twice-over. Doesn't look like I introduced many new typos.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1400)
> copy edits of known limitations page

- install-cockroachdb.md
The build from source instructions refer to an outdated location for the built cockroach binary. Update them to suggest the new `make install` command, which was added to simplify exactly this step. Also add a note with the correct path to the built binary, for users who have a moral objection to installing it into `/usr/local`.
Shout out to @couchand for reporting this issue.
Fixes #1416.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1418)
> update build-from-source instructions with new `make install` command

- install-cockroachdb.md
As of homebrew/homebrew-core#13431, CockroachDB is now in Homebrew
proper! Point the install instructions at the core cockroach formula
(`cockroach`) instead of our tap's cockroach formula
(`cockroachdb/cockroach/cockroach`).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1420)
> update homebrew install to use core formula instead of tap

- _data/sidebar_doc.yml
- frequently-asked-questions.md
- known-limitations.md
- operational-faqs.md
- sql-faqs.md
Continuing off of https://github.com/cockroachdb/docs/pull/1431 from @a-robinson's fork.
Fixes #957
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1450)
> Explain background disk and memory usage growth

- _includes/contribute-options.html
- _includes/feedback-widget.html
- "No" feedback at bottom of page: 
- Remove "Thank you!" to shorten the distance to the CTA (open a GitHub issue).
- Update the issue template to match the template for **Contribute** > **Report Doc Issue**.
- "Contribute" options at top of page:
- Remove "Priority" from issue templates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1453)
> Tweak feedback mechanisms

- demo-data-replication.md
It's misleading to tell the user to open the sql shell
"on any node" because there's only one node at that point.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1454)
> Minor fix to Data Replication tutorial

- operational-faqs.md
This gets asked about a lot (most recently in https://github.com/cockroachdb/cockroach/issues/16162). It's almost arguable that we should change the behavior of the `--background` flag to accommodate users' expectations, or at the very least to print a warning if it's taking a long time. What do you think?
cc #406 and #1403
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1475)
> Add operational FAQ entry about --background flag causing hangs

- _data/releases.yml
- v1.1-alpha.20170601.md
An early start on the next testing/unstable release, covering the post-1.0 work so far.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1423)
> Release notes for v1.1 alpha.20170601

- generate/main.go
Mark the `update_stmt` as `nosplit`; the update statement is now too complicated for the railroad diagram generator to condense the split form of the grammar.
This commit holds off on actually updating the update railroad digram, because I'm not sure whether it's the same in 1.0 and 1.1.
(CC'ing @knz, just in case he wasn't aware of this neat trick.)
> fix UPDATE railroad diagram generation

- CONTRIBUTING.md
- _includes/contribute-options.html
- asciicasts/build-a-python-app-with-driver.json
- beta-20160602.md
- build-a-c++-app-with-cockroachdb.md
- build-a-clojure-app-with-cockroachdb.md
- build-a-go-app-with-cockroachdb-gorm.md
- build-a-go-app-with-cockroachdb.md
- build-a-java-app-with-cockroachdb-hibernate.md
- build-a-java-app-with-cockroachdb.md
- build-a-nodejs-app-with-cockroachdb-sequelize.md
- build-a-nodejs-app-with-cockroachdb.md
- build-a-php-app-with-cockroachdb.md
- build-a-python-app-with-cockroachdb-sqlalchemy.md
- build-a-python-app-with-cockroachdb.md
- build-a-ruby-app-with-cockroachdb-activerecord.md
- build-a-ruby-app-with-cockroachdb.md
- build-a-rust-app-with-cockroachdb.md
- improve-the-docs.md
We no longer use GitHub pages directly; we run Jekyll ourselves and push
the built site to another repository. Stop using the `gh-pages` branch
so that GitHub stops trying to build this repository as a GitHub pages
site (and warning about how the redcarpet gem is no longer supported).
This completes the transition by replacing all references to `gh-pages`
with `master`.
---
@sploiselle @jseldess if this PR successfully builds, we're good to go!
> replace all references to `gh-pages` with `master`

- Gemfile
- _config.yml
- ci/Dockerfile
- ci/README.md
- ci/builder
- ci/pull-request
Move the configuration for CI, which used to leave in the TeamCity build
configuration, and the configuration for Docker, which used to live in
cockroachdb/docs-docker, into the repository. This allows us to
scope CI/Docker configuration changes to one branch and atomically
update the configurations when the branch merges.
> move ci and docker configuration into repository

- deploy-cockroachdb-on-aws-insecure.md
- deploy-cockroachdb-on-aws.md
- deploy-cockroachdb-on-digital-ocean-insecure.md
- deploy-cockroachdb-on-digital-ocean.md
- deploy-cockroachdb-on-google-cloud-platform.md
- deploy-cockroachdb-on-microsoft-azure-insecure.md
- deploy-cockroachdb-on-microsoft-azure.md
- install-cockroachdb.md
- manual-deployment-insecure.md
- manual-deployment.md
The `cockroach-latest*.tgz` tarballs have the unfortunate downside of not
including the version in either the filename or the extracted folder.
This was a convenient way to avoid updating the install instructions to
reflect the new filenames for every release. Now, though, we track the
latest release's name in _data/releases.yml, so we can use that to
automatically derive release filenames.
This is an important step in resolving cockroachdb/cockroach#14731.
Closes #1368.
/cc @mberhault @tamird @bdarnell if we land this change, will there be anything else that depends on the these tarballs?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1375)
> use versioned tarball in install instructions

- .gitignore
- CONTRIBUTING.md
- Makefile
I have a go tool named bundle installed via macports which gets in the
way of using ruby bundle in the usual way.
This is pretty much just cargo-culting, so feedback is welcome.
> Install ruby tools into ./vendor and add scripting in Makefile

- restore.md
- view-version-details.md
There's no way to make a headerless table render in Redcarpet (using Markdown; could convert to HTML). To alleviate the issue, I converted the table to a list.
Closes #1533
> convert headerless tables to lists

- demo-automatic-rebalancing.md
`CockorachDB` -> `CockroachDB`
cc @jseldess
> Fix typo in Automatic Rebalancing docs page

- _includes/sql/operators.md
- functions-and-operators.md
- generate/funcs.go
Due to vmg/redcarpet#477, it's not possible to use pipe characters (`|`)
in tables. This currently breaks several table rows on our "Functions
and Operators" page. Since these tables are auto-generated, fix this by
just directly outputting HTML tables, where pipe characters have no
special meaning.
Fixes #1536.
> generate raw HTML tables on "Functions and Operators" page

- add-column.md
- add-constraint.md
- foreign-key.md
- Document need to add index before adding FK constraint to an existing column,
- Update `ADD COLUMN` page:
-  State that it's not possible to add a column with a FK constraint.
- Provide workaround: add column without the constraint, index the column, and then add the constraint.
Fixes #1519
> Update docs on adding the Foreign Key constraint

- orchestrate-cockroachdb-with-kubernetes.md
The `minikube.sh` script no longer exists as of
https://github.com/cockroachdb/cockroach/pull/16536
This is because it's no longer needed.
> Fix minikube instructions.

- _includes/app/txn-sample.js
Adjust the node.js transaction sample code to perform a SELECT as
part of the transaction and return the results through the txn
wrapper.
Addresses node component of issue #1606
> Update node txn sample to pass results back from the transaction

- manual-deployment.md
Add --host when connecting to prevent the following when following the doc.
$ cockroach sql \
> --certs-dir=certs
Error: unable to connect or connection lost.
Please check the address and credentials such as certificates (if attempting to
communicate with a secure cluster).
dial tcp 127.0.0.1:26257: getsockopt: connection refused
Failed running "sql"
The change below with host works shown
$ cockroach sql --certs-dir=certs --host=10.0.3.98
root@10.0.3.98:26257/>
> Use --host to connect sql client

- _includes/app/basic-sample.js
- _includes/app/txn-sample.js
Running the samples as they exist now gives this warning:
(node:74958) DeprecationWarning: PG.connect is deprecated - please see the upgrade guide at https://node-postgres.com/guides/upgrading
That page explains that the pattern we're currently using for these
examples will be removed in the next major release of the pg package, so
we might as well update to the new way of using it now.
> Update usage of pg package for node examples

- js/customscripts.js
Looks like the copy-to-clipboard sanitizing regex was sourced from a StackOverflow question titled "Regex for removing leading and trailing carriage returns and line feeds from a sentence" (https://stackoverflow.com/a/2550845/1122351), but the question text sneakily also asked for the solution to combine this with "removing periods from within the string."
We want to keep these dots when copying to the clipboard, so remove the part of the regex that strips these dots.
> preserve dots when copying to clipboard

- _includes/sidebar.html
I broke this in #1477. Guess it wasn't "dead code." 🤦‍♂️
> fix mobile breadcrumbs

- v1.0/back-up-data.md
Just noticed this while I was reading through these docs.
> Spelling fix on backup / restore page

- v1.1/demo-data-replication.md
Follow-up to https://github.com/cockroachdb/docs/pull/1658.
> Spelling fix in 1.1 data replication tutorial

- _includes/sidebar.html
On mobile, properly render "Docs Menu" in the collapsed header on pages without a sidebar entry, like the homepage and search bar. This addresses additional breakage from #1477 that was not addressed by #1652.
Also address review feedback from #1652 by adding some documenting comments.
> fix mobile breadcrumbs, round two

- Rakefile
- _data/blog_posts.xml
- _plugins/rss_data.rb
- v1.0/index.md
- v1.1/index.md
This should make it easier to keep them up to date via a new shortcut,
`rake blog_posts`.
@jseldess thought this might make your life a little easier.
> parse recent blog posts from RSS feed

- _data/blog_posts.xml
Followed this new automated process: https://github.com/cockroachdb/docs/wiki/Common-Docs-Tasks#update-links-to-recent-blog-posts. Thanks to @benesch!
> Update links to recent blog posts

- v1.0/orchestrate-cockroachdb-with-docker-swarm-insecure.md
- v1.0/orchestrate-cockroachdb-with-docker-swarm.md
- v1.1/orchestrate-cockroachdb-with-docker-swarm-insecure.md
- v1.1/orchestrate-cockroachdb-with-docker-swarm.md
In the process, get rid of the advertise-host flag, since it's pointless
to set it to the same value as the container's hostname.
Also, for future reference, is there an easier way to update both the 1.0 and 1.1 docs for something than to just manually edit both versions?
Fixes #1664
> Specify hostname on swarm services so that UI can work

- v1.1/install-cockroachdb.md
cockroachdb/cockroach#16859 added a build dependency on the autotools suite. Update the v1.1 build from source instructions to match CockroachDB's CONTRIBUTING.md.
> update v1.1 build from source instructions for autotools build dep

- css/customstyles.css
- css/customstyles.scss
Hi @deronjohnson please check this PR out. This change is only for the docs, but the blog is affected as well. Can you ensure that the `pre` and `code` classes have fall-backs beyond Monaco please? Right now all our width-sensitive code samples are broken on non-OSX systems (Monaco is a proprietary Apple font)
> Ensure font fall-backs for code samples

- _includes/sql/v1.1/diagrams/set_var.html
- v1.1/diagnostics-reporting.md
- v1.1/set-vars.md
Both SHOW and SET are really single statements which act on the
session (and they are also handled using a single code path in
CockroachDB!), with the exception of SET TRANSACTION which acts on the
current transaction. This patch acknowledges the commonality and
merges the various documentation pages into two more general pages.
Extends #1107, off `release-1.1`.
Fixes #1502.
Fixes #1503.
Also covers the change implemented in cockroachdb/cockroach#16459.
> Refactor the SHOW/SET documentation; include USE and SET NAMES.

- v1.0/create-security-certificates.md
- v1.0/deploy-cockroachdb-on-aws.md
- v1.0/deploy-cockroachdb-on-digital-ocean.md
- v1.0/deploy-cockroachdb-on-google-cloud-platform.md
- v1.0/deploy-cockroachdb-on-microsoft-azure.md
- v1.0/manual-deployment.md
- v1.1/create-security-certificates.md
- v1.1/deploy-cockroachdb-on-aws.md
- v1.1/deploy-cockroachdb-on-digital-ocean.md
- v1.1/deploy-cockroachdb-on-google-cloud-platform.md
- v1.1/deploy-cockroachdb-on-microsoft-azure.md
- v1.1/manual-deployment.md
After generating and uploading certs to a node, remove
the node cert and key before generating those for the next
node. This is instead of using our custom `--overwrite` flag,
though I still mention the flag as an alternative.
Fixes #1678
> Rework node cert workflow in cert and deployment docs

- CONTRIBUTING.md
- _plugins/redirect_from_relative.rb
- _plugins/versions/generator.rb
- _plugins/versions/versioned_page.rb
- v1.0/set-vars.md
- v1.0/show-vars.md
- v1.1/set-vars.md
- v1.1/show-vars.md
These pages were removed in #1107, but Google still knows about them.
Teach Jekyll about them too.
> add redirects for old show and set pages

- _includes/sql/v1.0/diagrams/update.html
- generate/main.go
- v1.0/update.md
- v1.1/update.md
Closes #499 
Need to self-review the content, but fixed formatting issues.
> Completed Update statement documentation

- _includes/app/basic-sample.rs
- _includes/app/txn-sample.rs
This includes a few changes:
- Use the `?` operator in place of the `try!` macro. This new operator
stabilized a few versions ago and is now the [preferred](https://doc.rust-lang.org/std/macro.try.html) syntax.
- Use `loop break value` functionality, which stabilized in [Rust
1.19](https://blog.rust-lang.org/2017/07/20/Rust-1.19.html).
- Reformat using `rustfmt`, which seems to have changed since it was last
run on this code.
> example apps: Update Rust example for Rust 1.19

- v1.0/set-vars.md
- v1.0/timestamp.md
- v1.1/set-vars.md
- v1.1/timestamp.md
closes #685
Chose not to link to docs for setting session time zone because it is apparently not a best practice.
> clarify timestamp time zone details

- releases/v1.1-alpha.20170803.md
Covers
https://github.com/cockroachdb/cockroach/compare/64be211fa...1e88c32588fd3d7cad826437c18b349fd70e4762
Only adding the highlights since the release is already done.
> Add some late additions to 20170803 release notes

- _includes/app/txn-sample.go
The cockroach-go `ExecuteTxn` signature was changed in a backward-incompatible way in https://github.com/cockroachdb/cockroach-go/pull/41, breaking the transaction example.
This change updates the sample transaction code to use the new signature.
> Change go txn sample to use updated crdb.ExecuteTx signature

- v1.0/frequently-asked-questions.md
- v1.1/frequently-asked-questions.md
> Add FAQ about decision to use Postgres protocol

- _includes/sidebar-data-v1.1.json
- _includes/sql/v1.1/diagrams/cancel_query.html
- _includes/sql/v1.1/diagrams/show_jobs.html
- _includes/sql/v1.1/diagrams/show_queries.html
- _includes/sql/v1.1/diagrams/show_sessions.html
- generate/main.go
- v1.1/cancel-query.md
- v1.1/debug-and-error-logs.md
- v1.1/manage-long-running-queries.md
- v1.1/query-behavior-troubleshooting.md
- v1.1/show-jobs.md
- v1.1/show-queries.md
- v1.1/show-sessions.md
- v1.1/sql-statements.md
- Add 1.1 page for `SHOW SESSIONS`
- Add 1.1 page for `SHOW QUERIES`
- Add 1.1 page for `CANCEL QUERY`
- Add 1.1 page for Managing Long-Running Queries
- Generate sql diagrams
- Add statements to 1.1 sidenav
- Add statements to 1.1 sql statements overview
- Update Query Behavior Troubleshooting page
Fixes #1562 
Fixes #1572 
Fixes #1571
> Managing sessions and queries

- v1.0/known-limitations.md
- v1.1/known-limitations.md
> Add known limitation around dropping interleaved indexes

- v1.0/build-a-go-app-with-cockroachdb.md
- v1.1/build-a-go-app-with-cockroachdb.md
src should be included in the source code directories of go projects.
> fix wrong directories

- v1.0/use-the-built-in-sql-client.md
- v1.1/use-the-built-in-sql-client.md
Using html codes for `\|` surrounded by code tags seems to work. 
Fixes #1878
> Fix `|` rendering problem

- v1.0/frequently-asked-questions.md
- v1.0/high-availability.md
- v1.0/recommended-production-settings.md
- v1.1/frequently-asked-questions.md
- v1.1/high-availability.md
- v1.1/recommended-production-settings.md
It's safe to do so, we just want to make sure users are aware of the
performance penalty involved.
> Soften the warning about running cross-continent clusters

- v1.0/functions-and-operators.md
- v1.1/functions-and-operators.md
Use html codes for `|` surrounded by code tags.
Fixes #1911
> Fix `|` rendering in operators list

- v1.0/sql-feature-support.md
- v1.1/sql-feature-support.md
Also add a toc for improved navigation.
In a subsequent PR:
- We should mark 1.1 features as "new" or "changed" on the 1.1 page. We might also want to add a section calling out the new/changed features.
- Any features planned for 1.2 should be marked as "planned", with links to the relevant GitHub issues.
> Include cockroach version in sql feature support pages

- v1.0/known-limitations.md
- v1.0/sql-dump.md
- v1.1/sql-dump.md
Fixes #1842 
@mjibson, was this ported back to a 1.0 patch release? If not, should we add a 1.0 known limitation about this?
> Clarify that table and view schema are now dumped in the right order

- search.html
> Add message if no search results returned

- v1.0/orchestrate-cockroachdb-with-docker-swarm-insecure.md
- v1.0/orchestrate-cockroachdb-with-docker-swarm.md
- v1.1/orchestrate-cockroachdb-with-docker-swarm-insecure.md
- v1.1/orchestrate-cockroachdb-with-docker-swarm.md
Also switch to using an `attachable` network which makes running one-off
containers easier and simplify/fix the docs as applicable.
We could also go a little further with the secure guide and remove the
client keys from each container now that we can connect to the cluster
with one-off containers, but it'll probably still come in handy in
debugging situations to have the keys in all the containers.
Fixes part of https://github.com/cockroachdb/docs/issues/1288. I'm not yet making the change suggested in https://github.com/cockroachdb/cockroach/issues/17133 because it would make our insecure and secure setups diverge quite a bit, and I'm not thrilled about that.
> Update v1.1 Docker Swarm instructions to use the init command

- _includes/sidebar-data-v1.0.json
- _includes/sidebar-data-v1.1.json
- v1.0/sql-feature-support.md
- v1.0/window-functions.md
- v1.1/sql-feature-support.md
- v1.1/window-functions.md
- Add 1.0 and 1.1 stub pages
- Add to 1.0 and 1.1 sidenavs
- Update 1.0 and 1.1 sql feature support pages
Although docs are incomplete, these changes will help make users at least aware that CockroachDB supports window functions.
> Add stubs for Window Functions documentation

- v1.0/sql-faqs.md
- v1.1/sql-faqs.md
Addresses https://github.com/cockroachdb/cockroach/issues/15721
> Add FAQ on how ints are returned as strings in JavaScript

- v1.0/install-cockroachdb.html
- v1.1/install-cockroachdb.html
Fixes #1939 
Exception: Didn't remove from the Windows binary installation instructions because the step is unfortunately the only example of running a cockroach command in a Windows environment (powershell).
> Remove `cockroach version` step from install docs

- v1.1/manage-long-running-queries.md
- v1.1/show-queries.md
- v1.1/show-sessions.md
- v1.1/show-vars.md
Fixes #1874 
- Update `show-queries.md` and `show-sessions.md`:
- Update `application_name` response field description to state that sessions/queries from the sql shell show `cockroach`.
- Update examples to show `cockroach` as `application_name` where relevant.
- Add copy-to-clipboard button to sql code blocks.
- Update `manage-long-running-queries.md`: 
- Update examples to show `cockroach` as `application_name` where relevant.
- Add copy-to-clipboard button to sql code blocks.
- Update `show-vars.md` to explain that `cockroach` is the initial value for sessions from the sql shell.
> Updates based on default application_name for sql shell

- v1.1/keywords-and-identifiers.md
Fixes #1737 
Hint that you can use double-quotes to preserve case-sensitivity
in database, table, view, and column names.
@knz, is this sufficient, or should we also add notes to `CREATE DATABASE`, `CREATE TABLE`, etc.?
> Update identifier rules

- v1.0/upgrade-cockroach-version.md
- v1.1/upgrade-cockroach-version.md
Fixes #1964 
- Use callout at top to make the upgrade path clearer.
- Fix prepare step: Encouraging users to check that all nodes are on the same version before upgrading. Also add note about using `--ranges` flag when upgrading within 1.1 series.
- Fix the node upgrade sequence: Previously, we were telling users to download the new binary
and move it onto the path before stoping and renaming the old binary. Now, we tell users to stop the process, download the new binary, and then rename the old binary and move the new binary onto the `PATH`.
- Improve usability: Use max/linux toggles.
> Fix 1.1 upgrade doc

- v1.1/use-the-built-in-sql-client.md
Fixes #1437  
- Add `raw` option for `--format` flag.
- Add example using `raw` to make `SHOW` output selectable.
> Document how to make SHOW output selectable

- _includes/custom/schema-change-view-job.md
- v1.1/alter-table.md
- Remove extra tag to get page to render.
- Also remove callout from schema-change-view-job include, now that the header already calls out new in 1.1.
> Fixe ALTER TABLE page

- v1.1/cockroach-commands.md
- v1.1/data-types.md
- v1.1/sql-dump.md
- v1.1/sql-statements.md
Fixes #1968 
Add `New in v1.1` callout to cockroach command, sql statement, and data type overview pages so users can see newness at-a-glance. 
`Changed in v1.1` callouts are too numerous and so are only embedded directly with the features changed.
> Mark as new in 1.1

- v1.1/create-a-file-server.md
[Fixing typos from last PR](https://github.com/cockroachdb/docs/pull/1914#pullrequestreview-68288879).
> Typos in create-a-file-server

- v1.1/index.md
Change "Monitor" link on docs home to point to admin ui docs instead of prometheus.
> Change monitoring link on docs home

- _includes/sidebar-data-v1.1.json
- _plugins/versions.rb
- _plugins/versions/generator.rb
- _plugins/versions/version.rb
- _plugins/versions/versioned_page.rb
- v1.0/cockroachdb-architecture.md
- v1.1/architecture/overview.md
- v1.1/cockroachdb-architecture.md
General nav cleanup given where the architecture docs landed.
- Until we decide to backport the v1.1 architecture docs to v1.0, leaving stub in place with link to 1.1. Hardcoding 1.1 link because it will always be the closest approximation.
- Adding redirects to `architecture/overview.html`––first attempt is experimental. @benesch, would love some help here to ensure I get this right.
- Removing vestigial `cockroachdb-architecture.html` page
> Fixing nav for architecture-related content

- _config.yml
This can be switched back to pointing to v1.2 once we have a v1.2
release to point at.
Temporary band-aid on top of f3eb4a30ca59e0be2b56495627300405175df79b to fix the main repo's build, which expects the dev docs to be functional. Other URLs out there on the web may also refer to the dev docs. I'm not sure whether this will work, but teamcity should make it apparent soon.
> Un-break links to the dev docs

- v1.1/drop-database.md
Clarify that `CASCADE` is the default `DROP DATABASE` behavior for all clients except the built-in SQL client. And add note that, in an upcoming patch release, `CASCADE` will be made the default behavior for the SQL client as well.
> Clarify DROP DATABASE CASCADE/RESTRICT

- _includes/sidebar-data-v1.1.json
It was incorrectly pointing to the Transaction Layer page.
> Fix link to Replication Layer page

- v1.1/orchestrate-cockroachdb-with-docker-swarm-insecure.md
Only insecure docker swarm doc is affected.
> ./cockroach no longer needed with docker

- v1.0/sql-feature-support.md
- v1.1/sql-feature-support.md
- Mention that they're also known as CTEs and WITH clauses.
- Link to GitHub tracking issue.
Fixes #2081
> Update common table expressions on SQL Feature Support page

- v1.1/orchestrate-cockroachdb-with-docker-swarm-insecure.md
- v1.1/orchestrate-cockroachdb-with-docker-swarm.md
Using the copy-to-clipboard functionality was copying the dollar signs
along with everything else, breaking the ability to paste the commands
directly into my terminal. The 1.0 docs were already correct.
It's still a little awkward that this copies the comments along with the
command, but that doesn't break anything (most of the time, at least).
> Fix copying of a few commands in 1.1 swarm docs

- css/components/_filtertabs.scss
- css/customstyles.css
* re: [#2079](https://github.com/cockroachdb/docs/issues/2079) 
* reduce OS tab height
* rearrange OS tab content into inline layout 
* update similar filter-button tabs to render same pixel height as OS tabs
> Reduce OS tab height

- v1.1/select.md
- v1.2/select.md
Closes #1497 
As discussed, added information about FETCH FIRST and FETCH NEXT in same row as LIMIT, so as not to call attention, yet inform that we do support the parameters now. Also added examples.
> Added content for FETCH FIRST and FETCH NEXT

- v1.1/architecture/overview.md
- v1.2/architecture/overview.md
- add "s" on "detail" -- "This guide details how..."
- change "do" to "does" -- "but does not explain..."
> typos in the first note "data.alerts.callout"

- v1.1/recommended-production-settings.md
- v1.1/set-transaction.md
- v1.2/recommended-production-settings.md
- v1.2/set-transaction.md
- Add tip about space-separated transaction options
- ~~Note no diff in perf or storage between `string(n)` and `string`~~
- Mention system-wide file descriptors limit
> Various 1.1 updates

- v1.0/learn-cockroachdb-sql.md
- v1.1/learn-cockroachdb-sql.md
- v1.2/learn-cockroachdb-sql.md
Bug called out in Gitter:
> INSERT INTO accounts (id, balance) VALUES (5);
> Sql should be INSERT INTO accounts (id) VALUES (5);;
> Fix default insert in learn-cockroachdb-sql.md

- _config.yml
- _data/releases.yml
- releases/v1.2-alpha.20171113.md
- v1.2/set-transaction.md
- Add release notes file
- Update `_config.yml`
- Update `_data/releases.yml`
- Add product and doc changes
> Release notes for v1.2-alpha.20171113

- v1.1/create-a-file-server.md
- v1.2/create-a-file-server.md
This allows deletion of BACKUP-CHECKPOINT.
Found this while testing with a real nginx server.
> Add DELETE directive to nginx DAV docs

- v1.2/install-cockroachdb.html
Fixes #2150
Fixes #2166  
Note that the 1.2 build from source instructions are hidden for now, though. See https://github.com/cockroachdb/docs/issues/2155. #
> Update requirements for building v1.2 from source

- _includes/app/TxnSample.java
- v1.0/transactions.md
- v1.1/transactions.md
- v1.2/transactions.md
Fixes #2121. While the previous version was correct, some JDBC drivers
do not implicitly release the savepoint on transaction commit as the
comment indicated, so this is a better example.
> Test App: Add explicit release savepoint

- v1.1/demo-follow-the-workload.md
- v1.2/demo-follow-the-workload.md
Run kv the second time for 7min instead of 5.
This should be long enough in almost all cases to get the
range lease to move.
See https://github.com/cockroachdb/cockroach/issues/20213.
> Update follow-the-workload tutorial

- v1.2/admin-ui-overview-dashboard.md
- v1.2/operational-faqs.md
> Document how to truncate timeseries data sooner

- v1.0/known-limitations.md
- v1.0/truncate.md
- v1.1/known-limitations.md
- v1.1/truncate.md
- v1.2/known-limitations.md
- v1.2/truncate.md
> Clarify that truncate is equivalent to dropping and recreating a table

- releases/v1.2-alpha.20171211.md
> releases: Correct reference to timestamp cache

- _includes/orchestration/start-cluster.md
- _includes/orchestration/start-kubernetes.md
- v1.1/orchestrate-cockroachdb-with-kubernetes.md
- v1.2/orchestrate-cockroachdb-with-kubernetes.md
This enables them to work on more clusters (including non-GKE clusters)
by default.
This PR replaces https://github.com/cockroachdb/docs/pull/2271.
> Update secure Kubernetes instructions with RBAC support

- _includes/sidebar-data-v1.1.json
- _includes/sidebar-data-v2.0.json
- v1.0/orchestrate-cockroachdb-with-mesosphere-insecure.md
- v1.1/orchestrate-cockroachdb-with-mesosphere-insecure.md
- v2.0/orchestrate-cockroachdb-with-mesosphere-insecure.md
I don't know whether to include the doc in v2.0 or not - you can't
actually run unstable releases using the DC/OS package we provide, but
is it weird if we don't have the doc for it? Will we forget to add it
later? Let me know what you'd like.
The first commit is just https://github.com/cockroachdb/docs/pull/2319.
> Update Mesosphere docs to reflect support for newer cockroach versions

- v1.0/collate.md
- v1.0/deploy-a-test-cluster.md
- v1.1/collate.md
- v1.1/deploy-a-test-cluster.md
- v2.0/collate.md
- v2.0/deploy-a-test-cluster.md
The auto-generated functions docs expect a page called
`collatedstring.html`. The existing page is called `collate.html`. This
client-side redirect should suffice.
Fixes https://github.com/cockroachdb/cockroach/issues/21394
> Add redirect for collation page

- _includes/faq/clock-synchronization.html
- _includes/prod_deployment/synchronize-clocks.md
- v1.0/operational-faqs.md
- v1.0/recommended-production-settings.md
- v1.1/common-errors.md
- v1.1/deploy-cockroachdb-on-aws-insecure.md
- v1.1/deploy-cockroachdb-on-aws.md
- v1.1/deploy-cockroachdb-on-digital-ocean-insecure.md
- v1.1/deploy-cockroachdb-on-digital-ocean.md
- v1.1/deploy-cockroachdb-on-google-cloud-platform-insecure.md
- v1.1/deploy-cockroachdb-on-google-cloud-platform.md
- v1.1/deploy-cockroachdb-on-microsoft-azure-insecure.md
- v1.1/deploy-cockroachdb-on-microsoft-azure.md
- v1.1/manual-deployment-insecure.md
- v1.1/manual-deployment.md
- v2.0/common-errors.md
- v2.0/deploy-cockroachdb-on-aws-insecure.md
- v2.0/deploy-cockroachdb-on-aws.md
- v2.0/deploy-cockroachdb-on-digital-ocean-insecure.md
- v2.0/deploy-cockroachdb-on-digital-ocean.md
- v2.0/deploy-cockroachdb-on-google-cloud-platform-insecure.md
- v2.0/deploy-cockroachdb-on-google-cloud-platform.md
- v2.0/deploy-cockroachdb-on-microsoft-azure-insecure.md
- v2.0/deploy-cockroachdb-on-microsoft-azure.md
- v2.0/manual-deployment-insecure.md
- v2.0/manual-deployment.md
Fixes #960
Fixes #1867
Fixes #2129
Fixes #1799 
Fixes #1690 
@bdarnell, @mberhault, I've added clock sync instructions for digital ocean, gce, aws, azure, and for manual deployment. However, I haven't yet touched on centOS or Redhat, both of which @robert-s-lee has suggested would be helpful. I'm hesitant to document those distros until we've done more testing on them. Please let me know what you think.
> More detailed docs on clock sync

- _config.yml
- _data/releases.yml
- releases/v2.0-alpha.20180116.md
On the release notes page, I commented out the updates so we can easily build on them for the next alpha release.
> Withdraw v2.0-alpha.20180116 release

- v1.1/deploy-cockroachdb-on-aws-insecure.md
- v1.1/deploy-cockroachdb-on-aws.md
- v1.1/deploy-cockroachdb-on-digital-ocean-insecure.md
- v1.1/deploy-cockroachdb-on-digital-ocean.md
- v1.1/deploy-cockroachdb-on-google-cloud-platform-insecure.md
- v1.1/deploy-cockroachdb-on-google-cloud-platform.md
- v1.1/deploy-cockroachdb-on-microsoft-azure-insecure.md
- v1.1/deploy-cockroachdb-on-microsoft-azure.md
- v1.1/recommended-production-settings.md
- v2.0/deploy-cockroachdb-on-aws-insecure.md
- v2.0/deploy-cockroachdb-on-aws.md
- v2.0/deploy-cockroachdb-on-digital-ocean-insecure.md
- v2.0/deploy-cockroachdb-on-digital-ocean.md
- v2.0/deploy-cockroachdb-on-google-cloud-platform-insecure.md
- v2.0/deploy-cockroachdb-on-google-cloud-platform.md
- v2.0/deploy-cockroachdb-on-microsoft-azure-insecure.md
- v2.0/deploy-cockroachdb-on-microsoft-azure.md
- v2.0/recommended-production-settings.md
Fixes #2181
Fixes #1132
Fixes #1356
> Revise basic hardware recs and add cloud-specific recs

- _includes/sidebar-data-v2.0.json
- v2.0/data-types.md
- v2.0/inet.md
- v2.0/sql-constants.md
- v2.0/string.md
- v2.0/uuid.md
> INET data type

- _includes/sidebar-releases.json
Include two releases per branch: The most recent, and the original
x.y.0 (which is larger and discusses the new features of the release).
All others are in the "all releases" page (the two parts of which have
been bumped up in the tree to save a click).
What do you think of this idea? @jess-edwards and I noticed today that 1.0.7 was kind of buried in the middle of the list and easy to miss.
> Thin out the release sidebar

- _includes/footer.html
- _includes/head.html
- Really, this time. I didn't do this right in #2443.
- Also, do not show footer email signup on training pages. This has also been in place for some time but not working.
> Exclude training from search results

- v2.0/functions-and-operators.md
- v2.0/sql-statements.md
- v2.0/use-the-built-in-sql-client.md
- Change ? shell help command to ??.
- Remove mention of client-side execution for check_syntax.
- Remove "new/changed in 1.1" callouts from headers.
Fixes #2402
> Update built-in sql client docs

- v1.0/install-cockroachdb.html
- v1.1/install-cockroachdb.html
- v2.0/install-cockroachdb.html
We had some inconsistent `dava-eventcategory` tags on the install page, which caused conflicts/tracking failures in Google Tag manager. This PR aligns them.
Bundled in here is also a formatting fix for the `docker version` commands, which weren't formatted in HTML and didn't prevent the user from selecting the terminal marker.
> Fix Google Tag Manager tags

- _data/releases.yml
- releases/v2.0-alpha.20180122.md
Fixes https://github.com/cockroachdb/cockroach/issues/22947
I chose not to comment out the release notes as was done in #2366 because I didn't want to have to roll them all forward into the next alpha's release notes, but let me know if you think we should do that instead.
Also, is this all that we do to withdraw a release?
> Withdraw the v2.0-alpha.20180122 release

- v1.1/array.md
- v2.0/array.md
- Add details about supported casting; fixes #2517.
- Reformat examples to use copy-to-clipboard.
> Updates to 2.0 array docs

- _data/releases.yml
- releases/v2.0-alpha.20180212.md
See https://github.com/cockroachdb/cockroach/pull/23034.
> Withdraw the v2.0-alpha.20180212 release

- v1.0/demo-automatic-cloud-migration.md
- v1.1/demo-automatic-cloud-migration.md
- v1.1/training/fault-tolerance-and-automated-repair.md
- v2.0/demo-automatic-cloud-migration.md
This was changed in the ycsb binary in
https://github.com/cockroachdb/loadgen/pull/120, and I even mostly
updated the training docs in #2536 but forgot to actually change the
flag used.
> Fix ycsb rate limit flag in training

- _includes/orchestration/monitor-cluster.md
- _includes/orchestration/start-kubernetes.md
This can be confusing for users because the port-forward method of
viewing the admin UI only works if you're port-forwarding from your
local machine.
> Recommend against running Kubernetes instructions from a cloud shell

- _includes/orchestration/start-kubernetes.md
- _includes/orchestration/stop-kubernetes.md
- v1.0/orchestrate-cockroachdb-with-kubernetes.md
- v1.1/orchestrate-a-local-cluster-with-kubernetes-insecure.md
- v2.0/orchestrate-a-local-cluster-with-kubernetes-insecure.md
Also add a couple of missing `kubectl get pods` commands and clean up
the formatting of the commands to be entered into the SQL shell.
> Add missing COPY buttons to Kubernetes docs

- _includes/prod_deployment/synchronize-clocks.md
In https://github.com/cockroachdb/docs/pull/2564, I renamed
Manual Deployment to On-Premises Deployment but neglected
to update the clock synch include, which was targeting content
based on page title.
> Fix clock synch instructions in on-premises tutorials

- v1.1/architecture/distribution-layer.md
- v2.0/architecture/distribution-layer.md
s/an sorted map/a sorted map/g
> Fix a typo on the 'Distribution Layer' page

- v1.1/architecture/storage-layer.md
- v2.0/architecture/storage-layer.md
The last link on the page ends with `.html/`.  The link works when
testing on a locally running Jekyll site, but fails on the live site:
```
curl -v
https://www.cockroachlabs.com/docs/stable/build-an-app-with-cockroachdb.html/
*   Trying 104.27.131.83...
* TCP_NODELAY set
* Connected to www.cockroachlabs.com (104.27.131.83) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
* Server certificate: sni212570.cloudflaressl.com
* Server certificate: COMODO ECC Domain Validation Secure Server CA 2
* Server certificate: COMODO ECC Certification Authority
> GET /docs/stable/build-an-app-with-cockroachdb.html/ HTTP/1.1
> Host: www.cockroachlabs.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 404 Not Found
```
Note: I searched for other links ending with …
> Fix broken link on 'Storage Layer' page

- _includes/faq/planned-maintenance.md
- v1.1/remove-nodes.md
- v2.0/operational-faqs.md
- v2.0/remove-nodes.md
- v2.0/sql-faqs.md
- v2.0/stop-a-node.md
- v2.0/upgrade-cockroach-version.md
- Add FAQ on handling planned node maintenance
- Add guidance on using server.time_until_store_dead for rolling upgrades
- Minor improvements to cockroach quit doc
- Retitle Remove Nodes to Decommission Nodes
Fixes #2038
> Doc updates for planned maintenance events

- v1.0/demo-automatic-cloud-migration.md
- v1.1/demo-automatic-cloud-migration.md
- v1.1/demo-follow-the-workload.md
- v2.0/demo-automatic-cloud-migration.md
- v2.0/demo-follow-the-workload.md
Also link to the actual Go installation instructions, not just the
tarball download page.
Fixes #2332
> Clarify go version requirement for our load generators

- v1.1/training/index.md
> Add client-side redirect from /training/overview.html to current training home

- v1.1/show-trace.md
- v2.0/show-trace.md
SHOW KV FOR SESSION returns an invalid syntax error. I changed it to
SHOW KV TRACE FOR SESSION.
Fixes #2667
> Fix incorrect SHOW KV TRACE syntax.

- v2.0/information-schema.md
Update all information schema tables to match implementations, including
updating the meanings of `_CATALOG` and `_SCHEMA` columns.
From my review, other incomplete items in information_schema that
require fixes:
- CHARACTER_SET_* and GENERATION_EXPRESSION in `columns` table.
- administrable_role_authorizations
- applicable_roles
- column_privileges
- enabled_roles
- role_table_grants
- sequences
- `statistics` table needs `IMPLICIT` defined.
See #2017
Fixes #2508
> Add the referential_constraints view to information schema

- v1.0/view-node-details.md
- v1.1/view-node-details.md
- v2.0/view-node-details.md
Fixes #2249 
Also add the appropriate descriptions/field names for the v1.0 docs while I'm here.
I'm not sure this is really the best explanation, but I'm also skeptical that it's worth going into great detail here since it could easily confuse people in the common case that there's nothing weird about the values. It'd probably help if we had a good definition of what it means to be "live" that we could link to from here. Do we?
>  Attempt to clarify the node status command's updated_at field

- v1.0/deploy-cockroachdb-on-microsoft-azure-insecure.md
- v1.0/deploy-cockroachdb-on-microsoft-azure.md
- v1.1/deploy-cockroachdb-on-microsoft-azure-insecure.md
- v1.1/deploy-cockroachdb-on-microsoft-azure.md
- v2.0/deploy-cockroachdb-on-microsoft-azure-insecure.md
- v2.0/deploy-cockroachdb-on-microsoft-azure.md
Azure has slightly modified the interface for its network security group
rules, and our cloud deployment docs no longer matched.
+ Explicitly specify that the required rules are "Inbound" rules.
+ Add Destination and Destination port fields.
+ Sort fields to match current Azure interface.
Fixes #2418 
Current Azure Interface for reference:
> Update guide for Azure Network Security Rules

- v1.0/check.md
- v1.1/check.md
- v2.0/check.md
- v2.0/drop-column.md
> drop CHECK when column is dropped

- v1.0/deploy-cockroachdb-on-google-cloud-platform-insecure.md
- v1.0/deploy-cockroachdb-on-google-cloud-platform.md
- v1.1/deploy-cockroachdb-on-google-cloud-platform-insecure.md
- v1.1/deploy-cockroachdb-on-google-cloud-platform.md
- v2.0/deploy-cockroachdb-on-google-cloud-platform-insecure.md
- v2.0/deploy-cockroachdb-on-google-cloud-platform.md
Unfortunately the best GCE documentation I could find on the topic was
in a forum rather than their docs, but it does a decent job explaining
things:
https://groups.google.com/d/topic/gce-discussion/MKKRv03d5i4/discussion
Fixes #2554 
cc @sibblegp in case you have suggestions to better clarify the pitfall.
> Call out the backend timeout setting of GCE's TCP Proxy load balancers

- v2.0/cluster-setup-troubleshooting.md
- v2.0/known-limitations.md
- v2.0/recommended-production-settings.md
- v2.0/start-a-node.md
These flags were also updated in 2.0 so it makes sense to report the
most recent change.
> Bump version number in version flag

- Rakefile
- Use all of gce-agent's available cpus (8).
- Do not disable external link checking.
- Do not disable image or script checking.
> Try to speed up htmlproofer

- v1.0/deploy-a-test-cluster.md
- v1.1/deploy-a-test-cluster.md
- v2.0/deploy-a-test-cluster.md
Also remove the instructions to set up a local load generator as this
new workflow replaces that.
Closes #2460
> update cloudformation docs with load generator selection instructions

- v1.1/deploy-a-test-cluster.md
As written this actually doesn't work properly. The new nodes in the autoscaling group are not automatically added to the underlying k8s cluster so scaling the database just puts multiple pods on the same node. Deleting this until we can provide the proper instructions here. I believe it will involve: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-updating-stacks.html
> Remove K8s scaling instructions for CF template

- v1.1/initialize-a-cluster.md
- v2.0/initialize-a-cluster.md
Explained that the target of the `cockroach init` command must be one of
the nodes which appear in the `--join` flag of the `cockroach start`
command.
Fixes #2589
> Specify restrictions on the target of `init`

- v1.1/architecture/distribution-layer.md
- v2.0/architecture/distribution-layer.md
There was a missing blank line between the text describing the list, and
the first list item.  Adding the blank line caused the renderer to build
the list correctly.
It wasn't clear why from reading the below (unless I missed it):
https://daringfireball.net/projects/markdown/syntax#list
¯\_(ツ)_/¯
> Fix Markdown error in unsorted list

- v1.0/explain.md
- v1.1/explain.md
- v2.0/explain.md
> identify all statements that can be EXPLAINed

- _includes/sidebar.html
- _plugins/versions/versioned_page.rb
Version switcher URLs should have a trailing slash iff they are a
directory. Jekyll already handles this logic for us, so we just need to
teach the version injector not to strip the trailing slash if it exists.
> Fix version switcher URLs

- _data/releases.yml
But leave the release note pages in place so as
not to break incoming links.
> Remove withdrawn releases from full release list

- v1.0/build-a-python-app-with-cockroachdb-sqlalchemy.md
- v1.1/build-a-python-app-with-cockroachdb-sqlalchemy.md
- v2.0/build-a-python-app-with-cockroachdb-sqlalchemy.md
If you are skimming the docs, and trying to connect to a cluster that you've already made you may miss the warning to switch to using cockroach:// instead of postgres://
> improve connection instructions for sqlalchemy

- v1.1/architecture/transaction-layer.md
- v2.0/architecture/transaction-layer.md
Specifically:
- Use less charged language to describe node shutdown during max clock
offset situations
- Add a link to 'Remove Nodes' to provide more detail about what happens
during the node shutdown process
> Update clock offset shutdown language

- CONTRIBUTING.md
- _includes/sidebar-data-v2.0.json
- _includes/sql/v2.0/diagrams/split_index_at.html
- _includes/sql/v2.0/diagrams/split_table_at.html
- v1.1/rename-index.md
- v2.0/alter-index.md
- v2.0/alter-table.md
- v2.0/split-at.md
- v2.0/sql-statements.md
Fixes #616.
This change documents the `ALTER [TABLE|INDEX] .. SPLIT AT ..`
statement. It describes how to use the statement and then provides
justification for why an operator might want to use it.
Depends on https://github.com/cockroachdb/cockroach/pull/23721.
> sql: document SPLIT AT statement

- _includes/start_in_docker/mac-linux-steps.md
- v1.0/start-a-local-cluster-in-docker.md
- v1.1/start-a-local-cluster-in-docker.md
- v2.0/start-a-local-cluster-in-docker.md
This PR replaces https://github.com/cockroachdb/docs/pull/2462.
> Clarify where to find docker install guidance

- _includes/footer.html
In our nightly docs test, GitHub is throttling us with a 429 status.
> Exclude GitHub link in footer from link checking

- _includes/sidebar-data-v2.0.json
- v2.0/sql-feature-support.md
- Mark JSON and inverted indexes as supported in 2.0
- Add inverted indexes to 2.0 sidenav
> Mark JSON as supported in 2.0

- releases/v2.0-beta.20180319.md
Pgweb compatibility wasn't introduced until https://github.com/cockroachdb/cockroach/pull/23839,
which did not make it into this release. This should be added to the next set of release notes.
Discovered in https://github.com/cockroachdb/cockroach/pull/23518.
> Remove pgweb mention in v2.0-beta.20180319 release notes

- _includes/sidebar-data-v1.1.json
- _includes/sidebar-data-v2.0.json
- v1.1/sql-statements.md
- v2.0/cancel-job.md
- v2.0/import.md
- v2.0/pause-job.md
- v2.0/resume-job.md
- v2.0/sql-statements.md
Closes #2045 
A couple of questions for @mjibson:
- Can schema changes be paused/resumed in 2.0?
- Pause/resume/cancel jobs are enterprise features..so if a user wants to pause an `IMPORT` job, would they need an enterprise license, even though `IMPORT` is not an enterprise feature?
Update: Matt's answers:
- No
- Pause/cancel/resume jobs are not enterprise features (they are wrongly labeled so in the Docs).
> Pause/Cancel/Resume IMPORT jobs

- _config.yml
cockroachdb/cockroach has been bumped to link to
https://cockroachlabs.com/docs/v2.1. Temporarily alias the 2.0 docs as
the 2.1 docs; they are, after all, nearly identical.
When we're ready to start documenting 2.1, we can remove this alias and
copy the 2.0 folder to a 2.1 folder.
> Introduce 2.1 docs alias

- _config.yml
- _includes/sidebar-data-v2.0.json
- _plugins/sidebar_htmltest.rb
htmltest doesn't understand JavaScript, so it can't proof the links in
the sidebar. Work around the issue by generating stub pages with all the
links in each version's sidebar.
Fix #2809.
> Run htmltest on links in the sidebar

- v1.1/known-limitations.md
I'd guess this got dropped from the known limitations because the --join
flags in our examples changed to include more than just the first node,
but the underlying issue still exists in clusters large enough that it
isn't guaranteed that a copy of the first range will be on nodes
included in the join flags.
It's been fixed for 2.0, but we should still include this in our 1.1
docs. I've tweaked the wording a bit to make more sense than the v1.0
wording verbatim would have.
> Copy v1.0 known join flag limitation over to v1.1 known limitations

- v1.0/recommended-production-settings.md
- v1.1/recommended-production-settings.md
- v2.0/recommended-production-settings.md
We mixed in the word "nodes" when we're really talking about the number
of replicas. This was incorrect as written because the number of nodes
isn't particularly relevant for fault tolerance -- the number of
replicas is what really matters.
> Correct statement about running with even number of replicas

- v2.0/known-limitations.md
Reflect improvements and remove references to the retired kv.transaction.max_intents cluster setting.
> Update known limitation about txn size.

- v1.0/views.md
- v1.1/views.md
- v2.0/views.md
From v1.0, 1.1, and 2.0.
Fixes #2555.
> Remove 'Simplify supporting legacy code' section

- v1.1/performance-best-practices-overview.md
- v2.0/performance-best-practices-overview.md
Just noticed a duplicate sentence in the SQL best practices doc.
> Remove duplicate sentence on column families

- _includes/azure-locations.md
- scripts/azure-locations.py
- v2.0/enable-node-map.md
We should follow-up with coordinates for the GCE and Azure regions, but
these are not correct for anything other than AWS - for example, AWS's
us-east-1 is in Northern Virginia, while GCE's us-east1 is in South Carolina.
> Clarify provided geo-coordinates are AWS-only, make example match them

- v2.0/set-vars.md
- v2.0/show-vars.md
Fixes #2288 
On `set-vars.md`, also removed the column indicating whether or not a variable could be returned with `show` because the answer for all variables seems to be `Yes` now.
> Document intervalstyle session variable

- v1.1/connection-parameters.md
- v2.0/connection-parameters.md
sslmode has nothing to do with whether the server checks that client
certificates are signed by a known CA.
Removed "client-side", this is redundant.
> Fix ssl connection parameters.

- v2.0/query-order.md
Noticed by @rytaft.
Fixes #2922.
@rytaft if you can think of a way where a scalar subquery can provide a tuple (I couldn't find one in the end, although I was initially confident that was possible), we could add it here.
> Fix an order presentation example.

- _includes/sidebar-data-v2.0.json
- _includes/sidebar-data-v2.1.json
- _includes/sql/v2.0/diagrams/show_ranges.html
- _includes/sql/v2.0/diagrams/stmt_block.html
- _includes/sql/v2.1/diagrams/show_ranges.html
- _includes/sql/v2.1/diagrams/stmt_block.html
- v2.0/demo-follow-the-workload.md
- v2.0/partitioning.md
- v2.0/show-experimental-ranges.md
- v2.0/split-at.md
- v2.0/training/data-unavailability-troubleshooting.md
- v2.0/training/locality-and-replication-zones.md
- v2.1/demo-follow-the-workload.md
- v2.1/partitioning.md
- v2.1/show-experimental-ranges.md
- v2.1/split-at.md
- v2.1/training/data-unavailability-troubleshooting.md
- v2.1/training/locality-and-replication-zones.md
Fixes #2282 
Related:
- https://github.com/cockroachdb/cockroach/pull/14390
- https://github.com/cockroachdb/cockroach/pull/24696
Specific changes:
- Add a statement page for `SHOW EXPERIMENTAL_RANGES`
- `s/TESTING_RANGES/EXPERIMENTAL_RANGES/g` wherever it was previously
mentioned, such as in `SPLIT AT`, partitioning docs, and some of the
trainings
- Add `SHOW EXPERIMENTAL_RANGES` page(s) to sidebar nav
- Had to update full SQL diagram so the link to the `show_stmt_ranges`
nonterminal would work properly
- Finally, replicated all changes into v2.1 folder
> Add docs for SHOW EXPERIMENTAL_RANGES

- v2.0/information-schema.md
- v2.1/information-schema.md
> Add information_schema examples

- _includes/sidebar-data-v2.0.json
- _includes/sidebar-data-v2.1.json
- _includes/sql/v2.0/diagrams/show_ranges.html
- _includes/sql/v2.1/diagrams/show_ranges.html
- v2.0/demo-follow-the-workload.md
- v2.0/partitioning.md
- v2.0/show-testing-ranges.md
- v2.0/split-at.md
- v2.0/sql-statements.md
- v2.0/training/data-unavailability-troubleshooting.md
- v2.0/training/locality-and-replication-zones.md
- v2.1/demo-follow-the-workload.md
- v2.1/partitioning.md
- v2.1/show-testing-ranges.md
- v2.1/split-at.md
- v2.1/sql-statements.md
- v2.1/training/data-unavailability-troubleshooting.md
- v2.1/training/locality-and-replication-zones.md
Fixes #2954
- `SHOW EXPERIMENTAL_RANGES` is not supported in current releases of 2.0
or 2.1, so we update all uses back to `SHOW TESTING_RANGES`, which
does work on both versions.
- Rename files to `show-testing-ranges.html`
- Add `SHOW TESTING_RANGES` to 'SQL Statements' page.
- Add `EXPERIMENTAL_AUDIT` to 'SQL Statements' page while we're in here.
> Update 2.0, 2.1 docs to use `SHOW TESTING_RANGES`

- v2.0/known-limitations.md
- v2.1/known-limitations.md
> Remove info about TRUNCATE

- v2.0/start-a-node.md
- v2.1/start-a-node.md
> --temp-dir flag

- v2.0/known-limitations.md
Follow-up to https://github.com/cockroachdb/docs/pull/3013
> Mark limitation resolved as of 2.1

- v2.0/enable-node-map.md
- v2.0/orchestrate-cockroachdb-with-docker-swarm-insecure.md
- v2.0/orchestrate-cockroachdb-with-docker-swarm.md
- v2.0/recommended-production-settings.md
- v2.0/start-a-node.md
- v2.1/enable-node-map.md
- v2.1/orchestrate-cockroachdb-with-docker-swarm-insecure.md
- v2.1/orchestrate-cockroachdb-with-docker-swarm.md
- v2.1/recommended-production-settings.md
- v2.1/start-a-node.md
Also update examples across 2.0 and 2.1 docs.
Fixes #https://github.com/cockroachdb/cockroach/issues/24950
> Recommend decimal notation for flags that accept percentage

- v2.0/secure-a-cluster.md
Link: https://www.cockroachlabs.com/docs/stable/secure-a-cluster.html
I added {% include copy-clipboard.html %} before code blocks to allow for the Copy to Clipboard function.
> #3038 - Add copy-to-clipboard function to Getting Started

- v2.0/use-the-built-in-sql-client.md
Link: https://www.cockroachlabs.com/docs/stable/use-the-built-in-sql-client.html
A couple of things I did here:
* I added {% include copy-clipboard.html %} before code blocks to allow for the Copy to Clipboard function.
* Where needed, I broke code blocks into multiple parts.
* I fixed an incorrect SQL statement (thanks, Amruta).
* I fixed a typo.
> 3038 - Add copy-to-clipboard function to Getting Started docs

- v2.1/stop-a-node.md
We recently added copy-to-clipboard functionality to the code
blocks on the page. There were some nested in divs for secure/
insecure toggling. That nesting doesn't work
(see https://github.com/cockroachdb/docs/issues/2146). As a
workaround, I changed the div tags to section tags.
> Fixed 2.1 version of stop-a-node.md

- v2.0/sql-feature-support.md
- v2.0/time.md
- v2.1/data-types.md
- v2.1/sql-feature-support.md
- v2.1/time.md
- v2.1/timestamp.md
Also minor tweaks to the TIMEZONE type docs.
Fixes #2982
> Document the TIMETZ type

- v1.1/training/network-partition-troubleshooting.md
- v1.1/training/resources/docker-compose.yaml
- v2.0/training/network-partition-troubleshooting.md
- v2.0/training/resources/docker-compose.yaml
- v2.1/training/network-partition-troubleshooting.md
- v2.1/training/resources/docker-compose.yaml
As reported on Slack, Docker Compose changed the way that it names
networks when there's a hyphen in your current directory's name.
To avoid this version-dependent confusion, use a new-ish Docker Compose
feature to assign the full name of the network using the `name` field
and bump the version of the compose file appropriately to use the
feature: https://docs.docker.com/compose/compose-file/#name-1
Thanks @tim-o!
> Fix docker network names in partition troubleshooting exercise

- search.html
* implement regex to strip `+` signs from search query strings
> Strip + signs from search query strings

- v2.0/operational-faqs.md
- v2.0/sql-faqs.md
- v2.0/transactions.md
- v2.1/operational-faqs.md
- v2.1/sql-faqs.md
- v2.1/transactions.md
Also link to new transaction contention content from transactions page.
> Move FAQ from sql to operational FAQs page

- .vale.ini
- ci/Dockerfile
- ci/builder
- ci/pull-request
- ci/vale/CockroachDB/Contractions.yml
- ci/vale/CockroachDB/HeadingsCase.yml
- ci/vale/CockroachDB/HeadingsPunctuation.yml
- ci/vale/CockroachDB/OxfordComma.yml
This is a WIP PR to test [valelint](https://valelint.github.io/docs/) as a possible solution for auto-checking docs against at least some of our style conventions. 
For now, I've added 4 rules to check against:
- `Abbreviations.yml`: Checks for incorrect instances of `e.g.,` and `i.e.,`.
- `Contractions.yml`: Checks for `don't`, `can't`, `won't`, and `shouldn't`.
- `Headings.yml`: Checks that all headings use title case. This rule needs work since "step" headings in tutorials are more sentence case. A topic for further discussion.
- `OxfordComma.yml`: Checks for this non-contentious convention :).
To try this out, first install vale:
```
brew tap ValeLint/vale
brew install vale
```
Then clone this PR and at the root of the docs repo, run:
```
vale v2.1
```
That'll run the checks against …
> Add prose linter and basic rules

- _config.yml
- _includes/sidebar-data-v2.1.json
As requested by @mberhault and @nstewart, due to encryption bug that won't be resolved until after the v2.1.0-alpha.20180604 release.
> Temporarily revert encryption docs

- v2.1/data-types.md
- v2.1/time.md
> TIMETZ is not recommended for use in current state

- css/theme-blue.css
We currently wrap monospaced tabular output which makes it unreadable. This patch turns on scrolling in such cases.
Our highlighted code samples appear to already have the scrolling turned on, so this change brings the non-highlighted output in line.
> Scroll monospaced output instead of wrapping

- _includes/prod_deployment/insecurecockroachdb.service
- _includes/prod_deployment/securecockroachdb.service
This PR needs to be merged to ensure the TC builds for the main systemd PR (https://github.com/cockroachdb/docs/pull/3163) succeeds.
> Added systemd config files

- _includes/sidebar.html
- css/customstyles.css
- css/layouts/_sidebar.scss
- js/customscripts.js
- Expand first level by default.
- Remove the "accordian" behavior.
Conditional logic ensures that these changes affect only 2.1 docs.
> Update 2.1 sidenav

- _includes/orchestration/initialize-cluster-insecure.md
- _includes/orchestration/start-cluster.md
- v2.0/orchestrate-cockroachdb-with-kubernetes.md
- v2.1/orchestrate-cockroachdb-with-kubernetes.md
This is true as of the updates that we made to the Kubernetes config for
v2.0.
> Update Kubernetes docs to reflect that pods aren't "Ready" before init

- _includes/sidebar-data-v2.1.json
- v2.1/admin-ui-statements-page.md
To-Do (for future sprints):
- Edit the doc as required (change navigation guidance after the page is made accessible from the navigation bar, edit limitations as they are resolved, add screenshots after page design is finalized).
- Identify and update related documents (Troubleshooting guidance, production docs, etc.)
> Admin UI Statements page - Reference doc

- v2.0/upgrade-cockroach-version.md
Added references to 2.0.3 for consistency's sake - Comcast got a bit confused earlier, and though the instructions were for 2.0.
> s/2.0/2.0.3 on "Upgrade to Cockraoch DB 2.0" page

- v2.1/serial.md
This change is taken from
https://github.com/cockroachdb/docs/pull/3172
by dchenk.
> Mention sequence from serial type docs

- _config.yml
- _data/releases.yml
- _includes/sidebar-data-v2.1.json
- releases/v2.1.0-alpha.20180702.md
For https://github.com/cockroachdb/cockroach/issues/26951.
The output when using the tag for the last release (or its corresponding SHA) was huge and included a lot of old stuff, even from last year. But when I use the SHA initially picked for the [last alpha release](https://github.com/cockroachdb/cockroach/issues/25351#issuecomment-393646225), I get the current output, which seems correct.
```
python3 scripts/release-notes.py --from=83e98d996b3ba3537afd7bc67e439eb5d3ea1659 --until=3106615e752628fca3d446028ead653c82b6468a --hide-unambiguous-shas --hide-per-contributor-section > draft-release-notes2.md
```
> Release notes for v2.1.0-alpha.20180702

- v2.0/demo-automatic-cloud-migration.md
"--join=localhost:26257 \ "
is already exist  in the last line you don't have to add twice
> unnecessary line"--join=localhost:26257 \"

- v1.1/demo-automatic-cloud-migration.md
- v2.1/demo-automatic-cloud-migration.md
Follow-up to https://github.com/cockroachdb/docs/pull/3357.
> Remove extra --join flag from cloud migration tutorial

- _redirects
This is needed because netlify serves /foo.html if a users hits /foo/,
even if /foo/index.html exists. Releases is the only page we could find
that had both a foo.html and /foo/index.html, so everything else should
be fine.
> proxy the releases page correctly

- v1.1/create-security-certificates-openssl.md
- v2.0/create-security-certificates-openssl.md
- v2.1/create-security-certificates-openssl.md
We create node certificates with subject `/O=Cockroach/CN=node`. By default,
openssl doesn't allow multiple certificates with the same subject to be
signed (is knows this by checking the local database files).
There are multiple ways of getting around this (delete/truncate the
database files, add more fields to the subject that vary for each node),
but this one is by far the easiest.
> openssl docs: allow multiple certificates for the same subject.

- _includes/sidebar.html
* re: #3431 
* handle active sidebar highlighting for URLs without .html explicitly appended
> Highlight sidebar links for URLs without explicitly-appended `.html` 

- _config.yml
- _data/releases.yml
- releases/v2.1.0-alpha.20180730.md
Raw notes. Still need to be edited.
> Update docs site for v2.1.0-alpha.20180730 release

- v2.1/interval.md
@ivan, can you review this edit to docs? It's related to https://github.com/cockroachdb/cockroach/pull/27393.
CockroachDB now supports PostgreSQL abbreviated time units.
Closes #3458.
> Add abbreviated time units

- v2.1/explain.md
Level and Type columns don't display in EXPLAIN(VERBOSE). To view, use `SELECT "Level", "Type" FROM [EXPLAIN...];`
Closes #3209.
> Remove Level / Type columns from EXPLAIN(VERBOSE)

- _includes/v2.1/computed-columns/add-computed-column.md
- _includes/v2.1/computed-columns/jsonb.md
- _includes/v2.1/computed-columns/partitioning.md
- _includes/v2.1/computed-columns/secondary-index.md
- _includes/v2.1/computed-columns/simple.md
- v2.1/computed-columns.md
Computed columns can now be added to an existing table, using the `ALTER TABLE...ADD COLUMN` statement.
Closes #3067.
> Add computed column to existing table

- v2.1/functions-and-operators.md
- v2.1/known-limitations.md
- v2.1/sql-statements.md
- v2.1/use-the-built-in-sql-client.md
- Document the --set flag.
- Document \set option=value` as alias for \set option value.
- Document boolean aliases for client-side options.
- Reorder and rename some sections for clarity.
- Correct/improve the section on session and output types.
Fixes #3343.
> Update cockroach sql docs

- v2.1/drop-database.md
- v2.1/rename-database.md
You cannot rename / drop a database if it is set as the current database.
Closes #3090.
> RENAME / DROP DATABASE update

- v2.0/known-limitations.md
Docs currently suggest this is fixed, but per https://github.com/cockroachdb/cockroach/issues/25828 it still applies to INSERT INTO... SELECT FROM and CREATE TABLE AS SELECT statements.
> Adding Known Limitation about write and update limits

- v2.1/known-limitations.md
This is still an issue in 2.1, per https://github.com/cockroachdb/cockroach/issues/25828
> Re-adding write and update limits for a single statement

- CONTRIBUTING.md
- _includes/footer.html
- v1.0/sql-feature-support.md
- v1.0/sql-grammar.md
- v1.1/sql-feature-support.md
- v1.1/sql-grammar.md
- v2.0/sql-feature-support.md
- v2.0/sql-grammar.md
- v2.1/sql-feature-support.md
- v2.1/sql-grammar.md
Now that the page toc is always in the right margin, and users
can use the toc to jump around the page, the back-to-top button
is only helpful in cases where a page is long and does not have
a toc. In these cases, writers can explicitly set
back_to_top: true in the pages front-matter.
This PR also adds a toc to sql feature support pages.
> Make back-to-top button an explicit front-matter setting

- _includes/sidebar-data-v2.1.json
- _includes/v2.1/misc/schema-changes-between-prepared-statements.md
- _includes/v2.1/misc/schema-changes-within-transactions.md
- v2.1/alter-table.md
- v2.1/known-limitations.md
- v2.1/online-schema-changes.md
- v2.1/truncate.md
Partially addresses #2940 and #1340.
Fixes #3430.
- Add a page 'Online Schema Changes', which describes how online schema
changes work at a high level, including their limitations.
- Update `TRUNCATE` documentation to note that it is technically a
schema change, and is thus not purely transactional.
- Add links from various schema change statement reference pages to the
new schema changes overview page.
> Document online schema changes

- v2.1/connection-parameters.md
- v2.1/learn-cockroachdb-sql.md
- v2.1/show-databases.md
Fixes #3206.
- Update [Client connection parameters][1] to note that `database` param
defaults to `defaultdb` as of 2.1
- Update [Learn SQL][2] and [SHOW DATABASES][3] to describe `defaultdb`
and `postgres`
[1]: https://www.cockroachlabs.com/docs/dev/connection-parameters.html
[2]: https://www.cockroachlabs.com/docs/dev/learn-cockroachdb-sql
[3]: https://www.cockroachlabs.com/docs/dev/show-databases
> Add docs to describe new default database(s)

- v2.1/encryption.md
As pointed out during
[QA](https://github.com/cockroachdb/cockroach/issues/21880)
* add links to AES and counter mode wiki pages
* be consistent in capitalization of Encryption At Rest
* mention default value of `rotation-period` in parameter table
> Encryption At Rest: tweak docs.

- v2.0/performance-benchmarking-with-tpc-c.md
- v2.1/performance-benchmarking-with-tpc-c.md
The --warehouses argument for loading TPCC fixtures was off by a factor
of 10.
> Fix --warehouses argument in TPCC instructions

- v1.1/architecture/distribution-layer.md
- v2.1/architecture/distribution-layer.md
Follow-up to https://github.com/cockroachdb/docs/pull/3565.
> Make units consistent with text

- _includes/v1.1/orchestration/kubernetes-scale-cluster.md
- _includes/v2.0/orchestration/kubernetes-scale-cluster.md
- _includes/v2.1/orchestration/kubernetes-scale-cluster.md
As called out in #3558.
-----------
**Simplify explanation of the number of nodes in a Kubernetes cluster**
----------
**Provide link to instructions for resizing GKE cluster.**
There's also a single command that we could simply show the user:
gcloud container clusters resize cockroachdb --size=4
...but I'm not sure how to fit it in next to the links for GCE and AWS
without it looking out of place. Suggestions appreciated.
> Make a couple simplifications to the Kubernetes scaling docs

- _includes/v1.1/orchestration/kubernetes-limitations.md
- _includes/v2.0/orchestration/kubernetes-limitations.md
- _includes/v2.1/orchestration/kubernetes-limitations.md
Rather than the less-specific upstream Kubernetes docs.
> When referencing DaemonSets, link to our docs on the topic

- v2.1/int.md
Fixes #3593.
When we re-add BIT via https://github.com/cockroachdb/cockroach/pull/28807 it will be a completely different type.
> Remove BIT from the INT page.

- .vale.ini
Hi,
I'm the author of [Vale](https://github.com/errata-ai/vale), the natural language linter that you've recently included in your CI suite. 
I noticed that you mentioned having some trouble with code blocks (be9af9075f6072080bec461ee319d52096aa0d28). After looking through v2.1 of your documentation, it appears the issue is that non-standard markup syntax supported by Jekyll (e.g., [`includes`](https://jekyllrb.com/docs/includes/)) is causing some parsing confusion.
This isn't an uncommon issue (most static site generators introduce their own syntax) and Vale addresses it by including [customizable support for non-standard markup](https://errata.ai/vale/markup/#non-standard-markup).
I've updated your `.vale.ini` file to include 4 scoping rules (3 block-level and 1 inline-level) that seem …
> Add scoping rules to Vale's configuration

- _includes/head.html
- js/license-on-page.js
- v2.0/enterprise-licensing.md
- v2.0/get-started-with-enterprise-trial.md
- v2.1/enterprise-licensing.md
- v2.1/get-started-with-enterprise-trial.md
Closes #3667
This PR also includes JavaScript so you can link to it with parameters to include a user's actual license information on the page, e.g. `.../docs/stable/get-started-with-enterprise-trial.html?license=1234&organization=Not%20CRL`
In the case the page doesn't have any parameters passed to it, it loads just like the [Enterprise Licensing page](https://www.cockroachlabs.com/docs/stable/enterprise-licensing.html).
@jseldess I don't think this necessarily needs a link in the side nav since it's really only designed to be linked to from an email, but if you or anyone on your team has any suggestions for where to place it, I'm glad to oblige.
> add Enterprise Trial - Get Started doc

- v2.1/detailed-sql-support.md
- v2.1/sql-feature-support.md
- v2.1/subqueries.md
This PR only updates what currently exists in our docs about correlated subqueries. Follow up PRs will be made by @knz or myself for the following:
1. Expanding the [Subqueries](https://www.cockroachlabs.com/docs/dev/subqueries.html) page to include information about what subqueries are not supported
2. Adding examples of correlated subqueries where necessary 
Related to #2976.
> Update existing content about correlated subqueries

- v2.1/diagnostics-reporting.md
Replace detailed description of each section of diagnostics reporting
with a summary and details about the endnpoint to use to view
details yourself.
Fixes #3695.
Fixes #3080.
Fixes #3062.
Fixes #3597.
> Update 2.1 diagnostics reporting page

- v2.1/debug-and-error-logs.md
> Remove --log-backtrace-at and --verbosity from docs

- _includes/sidebar-data-v2.1.json
Change top-level Tutorials section to Guides > Explore Features.
Second "Guide" (after Get Started) feels more meaningful in terms of user flow than an entirely separate "Tutorials" sidenav section.
Plan is to look at analytics over next few weeks to see if the changed placement (compared to original placement nested inside Guides > Get Started) increases traffic to these tutorials through the sidenav.
> 2.1 sidenav tweak

- CONTRIBUTING.md
- _includes/footer.html
- v2.0/deploy-cockroachdb-on-aws-insecure.md
- v2.0/deploy-cockroachdb-on-aws.md
- v2.0/deploy-cockroachdb-on-digital-ocean-insecure.md
- v2.0/deploy-cockroachdb-on-digital-ocean.md
- v2.0/deploy-cockroachdb-on-google-cloud-platform-insecure.md
- v2.0/deploy-cockroachdb-on-google-cloud-platform.md
- v2.0/deploy-cockroachdb-on-microsoft-azure-insecure.md
- v2.0/deploy-cockroachdb-on-microsoft-azure.md
- v2.0/deploy-cockroachdb-on-premises-insecure.md
- v2.0/deploy-cockroachdb-on-premises.md
- v2.0/manual-deployment.md
- v2.0/monitoring-and-alerting.md
- v2.0/orchestrate-cockroachdb-with-docker-swarm-insecure.md
- v2.0/orchestrate-cockroachdb-with-docker-swarm.md
- v2.0/orchestrate-cockroachdb-with-kubernetes-insecure.md
- v2.0/orchestrate-cockroachdb-with-kubernetes.md
- v2.0/orchestrate-cockroachdb-with-mesosphere-insecure.md
- v2.0/orchestration.md
- v2.0/performance-benchmarking-with-tpc-c.md
- v2.0/performance-tuning.md
- v2.0/recommended-production-settings.md
Only 2-3% of traffic to Gitter and the Forum come
from the docs. For at least a while, we're therefore
turning off the help widget to allow us to expose
a docs satisfaction survey via Drift, which would
otherwise overlap and conflict with the help widget.
> Remove help widget from the docs

- v2.1/array.md
Arrays can now be cast to strings (Postgres compatibility).
Closes #3621.
> Cast arrays to strings

- _includes/v2.1/sql/diagrams/explain.html
- v2.1/explain.md
Fixes #3071
Summary of changes (all to the `EXPLAIN` page):
- Remove `METADATA`, `QUALIFY`, and `EXPR` options.  Required rewriting
a few bits slightly to remove references to those flags.
- Updated railroad diagram
> Remove options from EXPLAIN docs

- v2.1/debug-zip.md
Closes #3642 
The original issue (#3642 ) was for adding Problem Ranges to the list of things in the debug zip. In addition to that, I also added other things that appear in the debug zip (like cluster settings, etc.) that were missing from the doc.
Also deleted one instance of a warning that appeared twice.
> `cockroach debuz zip` doc updates

- _includes/v2.0/orchestration/start-cluster.md
- _includes/v2.1/orchestration/start-cluster.md
- v2.0/kubernetes-performance.md
- v2.1/kubernetes-performance.md
> Call out performance-optimized k8s config

- v2.1/string.md
CockroachDB now distinguishes `CHAR` and `VARCHAR`, as mandated by the SQL standard and PostgreSQL compatibility. 
Closes #3693.
> String aliases are preserved

- v2.1/table-expressions.md
> Add docs for SRF column accessors

- v2.1/architecture/transaction-layer.md
- v2.1/parallel-statement-execution.md
- v2.1/performance-best-practices-overview.md
Fixes #3485.
- Update *Writes* section of the 'Transaction Layer' doc:
- note that as of v2.1 transactional writes are pipelined
- Explain the effects / how it works at a high level
- Update 'Cluster Settings' page with the new flags (via the
autogenerated docs from the CockroachDB build):
- kv.transaction.write_pipelining_enabled
- kv.transaction.write_pipelining_max_batch_size
> Document pipelining of transactional writes

- v2.1/jsonb.md
Extend the JSONB field access example to include accessing an array element.
> Extend the JSONB field access example

- v2.0/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
- v2.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
Fixes part of #3591 
Relies on https://github.com/cockroachdb/cockroach/pull/31196 getting in first, since it's what automates the creation of the cockroachdb-public service in each cluster's default namespace.
> Explain the unconventional namespace usage in multi-cluster k8s setup

- v2.1/recommended-production-settings.md
- v2.1/start-a-node.md
- Add `--locality-advertise-addr` flag to `cockroach start` docs
- Feature the flag in the Networking section of the Production Checklist
Fixes #3256.
> Document how to prefer local networks

- _includes/v2.1/sql/settings/settings.md
Relates to #2964.
For v2.1.0, range merges will be disabled, and the cluster setting will not be available to users.
> Remove range merge cluster setting from 2.1.0 docs

- _includes/sidebar-data-v2.1.json
- v2.1/experimental-features.md
Fixes #2914.
- Add a new page **SQL Syntax > Experimental Features** which lists the experimental features available in CockroachDB 2.1.
- For each experimental feature, either link to documentation (if available), or write a brief description and example using comments and statements adapted from source code in the cockroachdb/cockroach repo.
> Add page listing experimental features

- v2.1/architecture/replication-layer.md
Fixes #2051.
- Add a paragraph to *Architecture > Replication Layer* describing that
as of v2.1, in addition to the rebalancing that occurs when nodes are
added or removed, we also rebalance leases and replicas based on load.
Also added links to relevant cluster setting and zone config docs for
those who want more info.
> Replication layer docs: add load-based rebalancing

- v2.1/managed-connect-to-your-cluster.md
- v2.1/managed-sign-up-for-a-cluster.md
- v2.1/managed-user-management.md
- Fix path to `ca.crt` in example connection strings.
- Emphasize that admin password must be changed right away.
- Tweak other user/password-related content.
> Managed fixes

- v2.1/build-a-python-app-with-cockroachdb-sqlalchemy.md
- v2.1/known-limitations.md
Create known limitations page for 2.1, as well as perform _very_ minor cleanup on old issues. Descriptions provided by engineering in all cases except for the `DISTINCT` issue with JSON, which I worked with Justin on.
Once merged, the following issues should have the `docs-done` label added
- cockroachdb/cockroach#16392
- cockroachdb/cockroach#18029
- cockroachdb/cockroach#19464
- cockroachdb/cockroach#20136
- cockroachdb/cockroach#22418
- cockroachdb/cockroach#23719
- cockroachdb/cockroach#24436
- cockroachdb/cockroach#24919
- cockroachdb/cockroach#25809
- cockroachdb/cockroach#26709
- cockroachdb/cockroach#27953
- cockroachdb/cockroach#28059
- cockroachdb/cockroach#28724
- cockroachdb/cockroach#28772
- cockroachdb/cockroach#30192
- cockroachdb/cockroach#30381
- …
> Add 2.1 known limitations

- _includes/head.html
- _layouts/page.html
- v2.1/index.md
This fix causes the page title to be unique in browser tabs
and also helps us differentiate between standard docs home
and managed docs home in analytics data.
> Correct managed home page title

- _includes/v2.1/known-limitations/cdc.md
- v2.1/change-data-capture.md
- v2.1/create-changefeed.md
- v2.1/known-limitations.md
Updates in this PR:
- Renamed/ moved the CDC known limitations include to a new directory
- Added Avro as supported
- Added duration to the `RESOLVED` option
- Removed `RENAME TABLE` known limitation
Closes #3725.
> Update CDC docs with new 2.1 changes

- v2.1/create-security-certificates-openssl.md
Reinstate the warning about not changing the certificate key usage for
2.1 and make it "danger" category. Also emphasize that you can't remove
any of the key usages either.
Ironically, Go started enforcing key usages to be what we have in the
docs.
Starting with 2.1, nodes and clients will not be able to communicate if
those settings are changed.
> openssl instructions: re-instate warning about key usages.

- v2.1/install-cockroachdb-mac.html
- v2.1/install-cockroachdb.html
> Add note about using homebrew after other install methods

- v2.1/kubernetes-performance.md
Also restructure the content into steps.
Fixes #3318.
> Add secure DaemonSet instructions

- _includes/v2.1/misc/external-urls.md
Currently the doc specifies that the Host should be the container name - this isn't correct. This URL:
`'azure://foo.blob.core.windows.net/employees.sql?AZURE_ACCOUNT_KEY=12345&AZURE_ACCOUNT_NAME=foo';` will throw an error from Azure since we attempt to conect to `foo.blob.core.windows.net/foo.blob.core.windows.net`. There should not be a host at all in the `azure://` string.
> Updated Azure Backup URL

- v2.0/transactions.md
- v2.1/transactions.md
... explaining that not all implicit transactions are automatically
retried.
Fixes #3748
> Improve docs around automatic retries

- v2.1/delete.md
- v2.1/truncate.md
- v2.2/delete.md
- v2.2/truncate.md
Fixes #4088.
- Update `DELETE` page to remove unnecessary `TRUNCATE` example, and add
a note saying to prefer `TRUNCATE` for tables >= 1000 rows.
- Update `TRUNCATE` page to expand the initial description of its
behavior slightly, and to add a note saying to prefer `DELETE` for
tables with < 1000 rows.
- Various small copy edits: typo fix; link update; whitespace.
> Clarify when to use DELETE vs. TRUNCATE

- v2.1/demo-automatic-rebalancing.md
- v2.2/demo-automatic-rebalancing.md
Follow-up fix to https://github.com/cockroachdb/docs/pull/4111/files.
> Remove now-irrelevant mention of splitting

- v2.1/change-data-capture.md
- v2.1/create-changefeed.md
In 2.1, the avro format option is `'experimental-avro'`, whereas in 2.2, it's `experimental_avro` without quotes. 
Fixes #4115.
> Correct avro format in 2.1 cdc docs

- css/customstyles.css
- css/customstyles.scss
#4084 left a bug that caused a large amount of spacing above a header if you jumped to it using the right-hand nav. This PR fixes it.
> fix bug that caused strange formatting with on-page jumps

- _includes/sidebar-data-v2.1.json
- v2.1/postgres-ddl-support.md
Fixes #3803.
- Add a new page, 'SQL > SQL Feature Support > Postgres DDL support',
which compares Postgres DDL support to CockroachDB, and describes
various extensions and workarounds (where relevant).
- The above is based on a (23-page!) internal document generated by
@knz.  The modifications are mostly edits related to Markdown
conversion, copy edits, added links for additional context, and so
on. All credit to knz, all errors were introduced in the subsequent
conversion and editing. :-}
> Add page listing PostgreSQL DDL support

- v2.1/computed-columns.md
- v2.2/computed-columns.md
Fixes #4137.
Related to #3501.
- Remove erroneous claim that computed columns can only be added at
table creation time.
> Computed columns: not just at table creation

- _includes/head.html
For the initial release, we didn't want search engines indexing our managed docs. Now that we're up and running, it makes sense to have them indexed.
> Tell search engines to start indexing managed docs

- v2.1/build-a-go-app-with-cockroachdb-gorm.md
- v2.2/build-a-go-app-with-cockroachdb-gorm.md
Fixes #4140.
- Delete an extra header and include that had snuck into the "insecure"
example section.  Looks like good old-fashioned human error.
> Remove duplicate paras from GORM insecure example

- _includes/v2.2/misc/customizing-the-savepoint-name.md
- _includes/v2.2/misc/savepoint-limitations.md
- _includes/v2.2/misc/session-vars.html
- v2.2/commit-transaction.md
- v2.2/release-savepoint.md
- v2.2/rollback-transaction.md
- v2.2/savepoint.md
- v2.2/set-vars.md
- v2.2/show-vars.md
- v2.2/sql-statements.md
- v2.2/transactions.md
Fixes #4008.
- Added a new section *Customizing the savepoint name* to several
pages (via include), which describes the new `force_savepoint_restart`
session variable and makes clear that SAVEPOINT is still only used for
transaction retries, and that we don't support nested
transactions (yet!).
- Made the "this is not a generalized SAVEPOINT, it's only for retries"
warning that lives on several pages an include.
- Removed all inline mentions of `cockroach_restart` *except* in actual
code samples, since it's not part of the statement name.  E.g.,
everywhere `SAVEPOINT cockroach_restart` is used in prose, it's been
changed to just `SAVEPOINT`.
- Added the `force_savepoint_restart` session variable to the list of
session vars.  While there, I discovered some broken table …
> Document customizable savepoint names

- v2.1/insert.md
- v2.1/upsert.md
- v2.2/insert.md
- v2.2/upsert.md
As was discussed with @andy-kimball.
> Update the documentation for UPSERT and INSERT

- _includes/v2.1/app/basic-sample.cs
- _includes/v2.1/app/insecure/basic-sample.cs
- _includes/v2.1/app/insecure/txn-sample.cs
- _includes/v2.2/app/basic-sample.cs
- _includes/v2.2/app/insecure/basic-sample.cs
- _includes/v2.2/app/insecure/txn-sample.cs
- _includes/v2.2/app/txn-sample.cs
- v2.1/build-a-csharp-app-with-cockroachdb.md
- v2.2/build-a-csharp-app-with-cockroachdb.md
Addresses part of #3700.
- Update C# code samples to show how to connect to secure clusters (this
is using code from @BramGruneir and @rolandcrosby - thanks guys!).
- Update the instructions in the docs to show how to create the
PKCS#12-formatted certificates which are required by C# (thanks for
the magic openssl incantation @mberhault).
- Various updates and copy edits to make the page work like our other
updated "Build an app" examples, i.e., using the new includes,
providing secure and insecure examples, etc.
- Note: all of the changes to both docs and code were replicated across
both v2.1 and v2.2.
> Update C# code samples to use secure connections

- v2.1/performance-best-practices-overview.md
- v2.2/performance-best-practices-overview.md
> Update perf best practices with interleave caveats

- CONTRIBUTING.md
- v2.1/cockroach-workload.md
- v2.1/demo-automatic-rebalancing.md
- v2.1/start-a-local-cluster.md
- v2.2/cockroach-workload.md
- v2.2/demo-automatic-rebalancing.md
- v2.2/start-a-local-cluster.md
some spelling mistakes
one command in restart cluster did not work for a local cluster until port was removed.
tpcc workload was pointing to bank command
> minor fixes

- _includes/v2.2/misc/session-vars.html
- v2.2/int.md
Fixes #4183, #4254.
Lays some groundwork for future work on #4298.
- Update `INT` page to include examples of actual min/max integers
supported by each type for easier reference.
- Update `INT` data type page with additions to the **Size**
section, specifically:
- A description of possible compatibility issues caused by 64-bit
integers vs. e.g. JavaScript runtimes, including when using
frameworks that autogenerate frontend code.
- Mention and link to `default_int_size` session var and cluster
setting.
- Add `default_int_size` to session vars page
> Update INT docs re: INT8, default_int_size setting

- _includes/sidebar-data-v2.1.json
- _includes/sidebar-data-v2.2.json
- _includes/v2.2/known-limitations/cdc.md
- v2.2/change-data-capture.md
- v2.2/create-changefeed.md
CDC updates, including:
- New cluster settings
- Updated default envelope format,
- List of unsupported SQL types/values in avro
Other changes: Rearranged the sidebar
Addresses some of the changes laid out in #3992. Note: core changefeed and cloud storages updates coming next.
> CDC cluster settings, envelope format, unsupported values in avro

- _includes/sidebar-data-v2.2.json
- _includes/v2.2/misc/automatic-statistics.md
- _includes/v2.2/misc/delete-statistics.md
- _includes/v2.2/sql/diagrams/create_stats.html
- _includes/v2.2/sql/settings/settings.md
- v2.2/cost-based-optimizer.md
- v2.2/create-statistics.md
- v2.2/show-statistics.md
Fixes #4241, #4253, #4180.
- Update CREATE STATISTICS doc with the following variants:
- CREATE STATISTICS foo FROM bar
- CREATE STATISTICS __auto__ FROM bar
- CREATE STATISTICS foo FROM bar AS OF SYSTEM TIME '-4h'
- Added information about automatic stats collection to the CREATE
STATISTICS page (via an include)
- Updated instructions for deleting statistics, added to both CREATE
STATISTICS and SHOW STATISTICS pages (via include)
- Updated railroad diagram and parameter descriptions for CREATE
STATISTICS v2.2
- Updated sidebar and page titles to remove extraneous "experimental"
text, since it's already clearly marked in the various documents via
an include.
- Used a proper emdash (!) in a few places.
> Update CREATE STATISTICS doc with missing variants

- _includes/v2.2/misc/session-vars.html
- v2.2/cost-based-optimizer.md
Fixes #4330.
- Update 'Cost-based optimizer' page with a new section 'Join
reordering', which discusses the new functionality, as well as
tradeoffs involved in its operation.  The new
`experimental_reorder_joins_limit` setting is described, along with
some warnings to the user about not setting it too high, since that
may lead to performance degradation.
- Update the session variables page to include the
`experimental_reorder_joins_limit` variable.
> Document join reordering by the optimizer

- _includes/v2.2/sql/settings/settings.md
- v2.2/cost-based-optimizer.md
A bit more work to address #3998.
- Edit the 'Supported statements' section of the ['Cost-based
Optimizer'][1] page as follows:
- Add `FILTER` per cockroachdb/cockroach#34077
- Add `DELETE` per cockroachdb/cockroach#34522
- Add `INSERT .. ON CONFLICT` variants per cockroachdb/cockroach#33339
- Remove `experimental_optimizer_updates` cluster setting (can't find
a commit for this, but I don't see it in `SHOW ALL` output on my
local build of yesterday's `master`, version number is
`v2.2.0-alpha.20181217-1096-gd104dcee69-dirty`.
[1]: http://www.cockroachlabs.com/docs/v2.2/cost-based-optimizer.html
> Update CBO docs to list more supported statements

- v2.1/constraints.md
Fixed a small typo in the markdown for constraints.md
> Fix typo in constraints docs

- _includes/sidebar-data-v2.2.json
- v2.2/range-merges.md
@benesch Here's a rough draft of the range merges doc. Can I get any edits content-wise from you? Will work on improving the doc's IA and moving it over to 2.2, etc. but wanted to make sure I have the technical side basically right.
I thought I'd talk more about the impact of range merges w/r/t talking to more nodes, as opposed to the cost incurred by the DistSender waiting for acks from each range in the query because a lot of that is supposed to be improved by a combo of Txn pipelining and parallel commits. You have a take on that? Or should we do the more obvious thing for 2.1 and see how 2.2 ends up looking?
Closes #2964
> [WIP] Range merges

- _includes/unsupported-version-soon.md
- _includes/unsupported-version.md
- _layouts/page.html
- v19.1/install-cockroachdb-linux.html
- v19.1/install-cockroachdb-mac.html
- v19.1/install-cockroachdb-windows.html
- v2.1/install-cockroachdb-linux.html
- v2.1/install-cockroachdb-mac.html
- v2.1/install-cockroachdb-windows.html
> Mark 1.0 as unsupported and 1.1 as soon-unsupported in docs

- _includes/sidebar-data-v19.1.json
- v19.1/dbeaver.md
- v19.1/intellij-idea.md
- v19.1/third-party-database-tools.md
Duplicating docs from v2.1 into v19.1, including a string change to an actual version of CockroachDB I tested with Intellij.
> include third-party database tools, including intellij docs, in 19.1

- v2.1/common-errors.md
Fixes #4401.
- Update 'Common Errors' page with a new 'read within uncertainty
interval' section, which describes the error and how to avoid it
- Link from the above to other relevant docs (e.g., architecture docs on
txn conflicts, AOST, etc.)
> Add read in uncertainty interval to common errors

- v19.1/interval.md
Fixes #4375.
- Update `INTERVAL` docs with a new section on 'Precision', where we
note that as of 19.1, nanoseconds are going away in favor of
microseconds only
- Remove description of Golang-ish interval syntax which mentioned
nanoseconds
- s/nano/micro/g (which may not have made sense in all cases, pending
engineering review).
- Add new 'aliases' section to match other data types, where we note
that you can specify intervals with string literals in some contexts.
- Move information about internal representation to the 'Size' section.
- Update Examples to use new output format.
> Remove nanoseconds from INTERVAL docs

- _includes/v19.1/misc/automatic-statistics.md
- v19.1/cost-based-optimizer.md
- v19.1/create-statistics.md
- v19.1/show-jobs.md
Fixes #4374, #4379.
- Update automatic statistics mentions to note that it's on by default,
and remove instructions for turning it on (since it's already on).
- Update CREATE STATS mentions to note that it creates jobs, and can be
viewed by SHOW JOBS.
- Update SHOW JOBS page to mention automatic stats.
> Docs: auto-stats on by default, CREATE STATS jobs

- v19.1/performance-benchmarking-with-tpc-c.md
- v19.1/recommended-production-settings.md
- v2.1/performance-benchmarking-with-tpc-c.md
- v2.1/recommended-production-settings.md
- Clarify that we are talking about vCPU instead of CPU.
- Fix connection string info in the workload instructions of benchmarking a large cluster.
Closes #4301, #4304, #4287.
> Update Production Checklist

- _redirects
This PR replaces https://github.com/cockroachdb/docs/pull/4451,
which used client-side redirects.
Fixes #4450.
> Server-side redirect of v2.2 urls to v19.1 via netlify

- _includes/v19.1/misc/session-vars.html
- v19.1/bytes.md
- v19.1/sql-constants.md
- v19.1/string.md
- v2.0/bytes.md
- v2.0/import.md
- v2.0/sql-constants.md
- v2.0/string.md
- v2.1/bytes.md
- v2.1/show-vars.md
- v2.1/sql-constants.md
- v2.1/string.md
Fixes #3324.
Also fixes an incorrectness introduced by mistake in #2134.
@rmloveland would appreciate if you could take this over and add the finishing touches.
> Fix the documentation on bytes/string conversions, explain bytea_output.

- _includes/topnav.html
When you click "Docs" in the topnav, it sense you to `/docs/stable`, without the final forward slash, ad this seems to mess of the versioning of links on the page. This PR fixes that.
> Fix links on doc landing page

- _includes/sidebar-data-v19.1.json
- v19.1/bit.md
- v19.1/data-types.md
- v19.1/int.md
- v19.1/sql-constants.md
- v19.1/string.md
Fixes #4070.
First commit from #4452.
@rmloveland feel free to take this over.
> Document BIT/VARBIT. 

- _includes/v19.1/known-limitations/import-interleaved-table.md
- _includes/v2.1/known-limitations/import-interleaved-table.md
- v19.1/known-limitations.md
- v19.1/sql-dump.md
- v2.1/known-limitations.md
- v2.1/sql-dump.md
Documenting that dump won't work without manual edits when interleaved tables are present.
I'm hoping this will avoid some consternation for someone trying to restore down the road. Better to inform them if basic functionality won't work as expected, especially if the fix is easy. This could free up the bulk IO team to work on things without a workaround.
@jseldess AFAIK we haven't actually referred to issues in the docs before, so let me know if this is alright with you.
> SQL Dump Known Issue

- _includes/v19.1/zone-configs/view-the-replication-zone-for-a-partition.md
- _includes/v2.1/zone-configs/view-the-replication-zone-for-a-partition.md
- v19.1/partitioning.md
- v2.1/partitioning.md
- v2.1/show-zone-configurations.md
There were numerous problems in the partition by list example:
- It used only 2 datacenters, a bad pattern for CockroachDB.
- In each datacenter, there was only 1 node. This made partitioning
non-functional because CockroachDB won't place more than one replica
of a range on a single node.
- There were some bugs in the zone config settings.
This PR expands the example to 3 datacenters with 3 nodes in each. It also
converts the example to be runnable as a local cluster and adds
an example of how to view the zone config for a partition.
Fixes #4499.
Separately, we'll need to re-test and refresh the partition by range example and the sub-partition example.
> Fix table partitioning docs

- v19.1/cost-based-optimizer.md
- v19.1/joins.md
Fixes #2012.
- Added a section to the CBO page, 'Join hints', which describes:
- Join hint syntax
- Supported join algorithms, and how they work
> Add docs for optimizer join hints

- v19.1/known-limitations.md
- v19.1/rename-database.md
- v19.1/rename-table.md
- v2.0/known-limitations.md
- v2.0/rename-database.md
- v2.0/rename-table.md
- v2.1/known-limitations.md
- v2.1/rename-database.md
- v2.1/rename-table.md
Fixes #4393.
- Update `ALTER TABLE .. RENAME DATABASE` to say that db renames are not
transactional, explain why, and offer a workaround.
- Update 'Known limitations' page to note that db renames are not
transactional, with a link to the above page for more information.
> Database renames are not transactional

- _includes/sidebar-data-v19.1.json
- _includes/sidebar-data-v2.1.json
- v19.1/index.md
- v2.1/index.md
After refreshing the docs landing page, release note sign-ups
dropped noticably. In the previous version, the link to the
Install page was top-left, which is the position that tends to
get the most clicks.
This PR bumps the Install link to the top-left again in the hope
that more users once again go to the install page and, from there,
sign up for release notes.
This PR also adds a link to our training curriculum under
Learn More. It also renames "Explore Features" to "Explore 
Capabilities" in the sidenav. "Features" always felt too narrow.
> Landing page tweak

- _includes/sidebar-data-v19.1.json
- _includes/sidebar-data-v2.1.json
- v19.1/diagnostics-reporting.md
It's not sustainable to keep the list of details that get reported
up-to-date, so this PR summarizes the types of details and more explicitly
points users to the endpoint for viewing the real details.
This PR also moves the diagnostics reporting page into the Reference 
section.
Fixes #4526.
Fixes #4525.
Fixes #4259.
> Update diagnostics reporting page for v19.1

- v19.1/architecture/life-of-a-distributed-transaction.md
- v19.1/architecture/transaction-layer.md
@nvanbenschoten Can I get you to take a look at this for a tech edit? Still need to polish the language a bit, but want to make sure I have the technical details lined up correctly. Oh––and one open question: does the `DistSender` or the `TxnCoordSender` actually write the transaction record?
Closes #4397
> Lazy transaction record docs

- v19.1/cost-based-optimizer.md
Fixes #4502, #4549.
Addresses part of #4509.
Summary:
- Add `CROSS <x> JOIN` to list of supported hints
- Remove line saying cross join was not supported
> Add CROSS JOIN to list of hints supported by CBO

- _includes/v19.1/misc/linux-binary-prereqs.md
- _includes/v2.1/misc/linux-binary-prereqs.md
- v19.1/common-errors.md
- v19.1/recommended-production-settings.md
- v2.1/common-errors.md
- v2.1/recommended-production-settings.md
> Document tzdata dependency

- _includes/v19.1/zone-configs/create-a-replication-zone-for-a-secondary-index.md
- v19.1/configure-replication-zones.md
- v19.1/cost-based-optimizer.md
Fixes #4198.
- Add a section to the CBO page, 'Preferring the nearest index', which
describes the feature and provides a short tutorial using a local
cluster
- Update references to the `--locality` flag to link to the docs for
that flag
- Add link from replication zones doc for secondary indexes to the new
CBO section so there is cross-linkage
> CBO prefers index from zone nearest gateway

- _includes/v19.1/misc/force-index-selection.md
- v19.1/indexes.md
- v19.1/select-clause.md
- v19.1/table-expressions.md
Fixes #4363.
- Write a new set of instructions for forcing index selection, including
the `FORCE_INDEX` and new `ASC`/`DESC` scan direction keywords.
- Use the above as an include so it can be used to:
- Replace the existing content in 'Table Expressions'
- Add a new section to the `SELECT` page
- Finally, made some small updates to the 'Indexes' page to link more
things together.
> Document specifying scan direction in index hint

- _includes/v19.1/known-limitations/homebrew.md
- v19.1/install-cockroachdb-mac.html
- v19.1/known-limitations.md
Add a warning to the 19.1 mac install page that homebrew install
won't be available until the release of Go 1.12.2. Hide
install steps in the meantime. These changes will be visible as 
soon as the "stable" alias applies to v19.1
Add this as a known limitation as well.
Fixes #4575.
> Install via homebrew not available for v19.1

- ci/pull-request
This change to the `pull-request` CI script attempts to determine
which Markdown files have changed using `git diff`, and adds deep
links to the generated HTML output when commenting on Github.
I'm not sure exactly where this script runs, so this may not work in production, but I've verified that the parts that I changed produce the expected output in isolation.
> ci: Deeplink to changed files in PR comments.

- _includes/v19.1/misc/automatic-statistics.md
- v19.1/cost-based-optimizer.md
- v19.1/install-cockroachdb-linux.html
- v19.1/install-cockroachdb-mac.html
- Remove "experimental" from name of auto stats cluster settings 
- Rename experimental_reorder_joins_limit session variable
- Increase required Go version for building from source
> 19.1 updates

- ci/pull-request
Minor changes to the `pull-request` script to fix the following issues with deeplinks:
- All changed files between the PR branch and the latest `origin/master` branch were
being linked. Now, we compare the PR branch to the best common ancestor branch it has with
`origin/master`, as determined by `git merge-base`.
- Only Markdown files were being linked. Now, we also link changes to HTML files. Includes
(and any other files with paths beginning with `_`) are still ignored.
> ci: Compare with merge-base, and link to changed .html pages

- v19.1/install-cockroachdb-windows.html
- v2.1/install-cockroachdb-windows.html
This "Install CockroachDB on Windows" page has a warning box but the
bolded text is "Native CockroachDB on Windows requires Windows 8 or
higher" and the experimental status is a bit hidden in the rest of the
box. This binary is almost entirely untested, so I'd suggest we swap the
bolded text to be about the experimental status of the binary.
Otherwise, I worry that users may form a bad initial impression of our
performance/stability/maturity (and perhaps don't bother contacting us
as a result).
> Be louder about experimental status of windows build

- _includes/v19.1/app/BasicSample.java
- _includes/v19.1/app/TxnSample.java
- _includes/v2.1/app/BasicSample.java
- _includes/v2.1/app/TxnSample.java
- v19.1/connection-parameters.md
- v2.1/connection-parameters.md
- Searched for mentions of `application_name` for JDBC and didn't find anything to clean up.
- Added a note to Connection Parameters to call out `ApplicationName` for JDBC.
Closes #4294.
> Edit ApplicationName param for JDBC

- _includes/sidebar-data-v19.1.json
- _includes/v19.1/sql/diagrams/comment.html
- _includes/v19.1/sql/diagrams/show_tables.html
- v19.1/comment-on.md
- v19.1/show-tables.md
- v19.1/sql-statements.md
- Add `COMMENT ON` statement
- Update `SHOW TABLES ... WITH COMMENT`
Closes #4261, #4182, #4262.
> Add COMMENT ON / Update SHOW TABLES

- _includes/v19.1/sql/diagrams/import_csv.html
- _includes/v19.1/sql/diagrams/import_dump.html
- _includes/v2.1/sql/diagrams/import_csv.html
- _includes/v2.1/sql/diagrams/import_dump.html
- v19.1/import.md
- v2.1/import.md
- Generate simplified, distinct diagrams for CSV and dump
- Update paramaters and examples accordingly
- Remove parentheses around instances of file_location
Fixes #4065.
> Improve UX of IMPORT docs

- v1.0/window-functions.md
- v1.1/window-functions.md
- v19.1/window-functions.md
- v2.0/window-functions.md
- v2.1/window-functions.md
For some reason, the title of the "Window Functions" page was in ALL CAPS
across all CockroachDB versions. Since "window functions" refers to the
general concept as opposed to a SQL keyword, this should be title case
throughout.
> Change "Window Functions" page title to title case

- v19.1/add-constraint.md
- v19.1/foreign-key.md
Fixes #4134, #4177.
- Update ADD CONSTRAINT doc's section on adding foreign key constraints
to remove the "you must create an index" language and add some
"indexes are created for you" language
- Update tables in ADD CONSTRAINT to use new style
- A few small link and copy edits
> Automatically index fk columns on an empty table

- v19.1/cost-based-optimizer.md
- v19.1/explain.md
Fixes #4348.
- Remove explicit use of `EXPLAIN(OPT)` from CBO page; all usage should
be on `EXPLAIN` page
- Add quick explanations of the `OPT, *` options, with direct links to
each example on the `EXPLAIN` page
> Update CBO page `EXPLAIN(OPT)` info

- _includes/v19.1/misc/schema-change-view-job.md
- v19.1/add-column.md
- v19.1/add-constraint.md
- v19.1/alter-column.md
- v19.1/alter-index.md
- v19.1/alter-table.md
- v19.1/alter-type.md
- v19.1/configure-zone.md
- v19.1/create-index.md
- v19.1/drop-column.md
- v19.1/drop-constraint.md
- v19.1/drop-database.md
- v19.1/drop-index.md
- v19.1/drop-table.md
- v19.1/experimental-audit.md
- v19.1/partition-by.md
- v19.1/rename-column.md
- v19.1/rename-index.md
- v19.1/rename-table.md
- v19.1/split-at.md
- v19.1/truncate.md
- v19.1/validate-constraint.md
Fixes #4015.
- Revise generic "schema change = SHOW JOBS" to make narrower claim
about which of them will appear in SHOW JOBS, since it isn't all of
them yet.
- Update various statement and sub-statement pages that will show up in
the jobs table to say (roughly) that "this statement is a job, and
will show up when you run SHOW JOBS".
> Update (some) schema change docs with `SHOW JOBS`

- v19.1/cost-based-optimizer.md
- v19.1/sql-faqs.md
- v19.1/sql-feature-support.md
- v19.1/subqueries.md
- Update various docs to note that we now support most correlated
subqueries, specifically:
- Correlated subquery section of 'Subqueries' page
- 'Cost-based Optimizer' page
- 'SQL FAQ' and 'SQL Feature Support' pages
Fixes #4000.
> Update correlated subquery docs

- _includes/v19.1/misc/sorting-delete-output.md
- v19.1/delete.md
- v19.1/query-order.md
Fixes #4378.
- Add new section 'Sorting the output of deletes' to both the `DELETE`
and 'Ordering Query Results' pages.
- Add example section 'Sort an return deleted rows' to the `DELETE` page
- Update all examples on `DELETE` page to use new SQL CLI output table
formatting
- Add SQL code needed for `DELETE` examples in a comment at the bottom
of the page
> `LIMIT` is required on a `DELETE ... ORDER BY`

- v19.1/add-constraint.md
- v19.1/check.md
Fixes #4362.
- Update `CHECK` constraint page to note that validation is now
asynchronous.
- Update 'Add Constraint' page to note that validation is now
asynchronous, and to give an example of adding a CHECK constraint to a
column added earlier in the same transaction.
> Document asynchronous CHECK constraint validation

- v19.1/demo-serializable.md
- v19.1/release-savepoint.md
- v19.1/show-trace.md
- v19.1/sql-statements.md
- v19.1/transactions.md
In transaction retry docs, call out ways to change the results buffer size beyond which automatic retries are no longer possible.
Fixes #4144.
> Results buffer

- v19.1/common-errors.md
Fixes #4552.
- Update 'Common Errors' page with this retry error message, and
recommend that the user add retries to their app.
- Also spruced up the txn restart section intro with some links to
reference docs on how txns work in CockroachDB for the curious.
> Add docs for "transaction deadline exceeded" error

- v19.1/common-errors.md
(Still) fixes #4552.
Original discussion in #4667 .  This change fixes a technical error I introduced while copy-editing some text of that PR.
Summary of changes (is still):
- Update 'Common Errors' page with:
- the retry error message
- a recommendation that the user add retries to their app
- a description of the state that leads to such errors (kindly
contributed by Andrei Matei)
- also spruced up the txn restart section intro with some links to
reference docs on how txns work in CockroachDB for the curious.
> Add docs for "transaction deadline exceeded" error, again

- v19.1/build-a-go-app-with-cockroachdb-gorm.md
- v19.1/build-a-python-app-with-cockroachdb-sqlalchemy.md
- v19.1/build-a-ruby-app-with-cockroachdb-activerecord.md
Fixes #4669.
- Note that these ORMs rely on foreign keys to generate joins.  If you
disable FKs, they won't build the joins for you.  For each ORM, also
link to the likely API for emitting raw SQL.
> Update ORM docs with foreign key note

- _config_base.yml
- _data/releases.yml
- releases/v19.1.0-rc.4.md
See https://github.com/cockroachdb/cockroach/issues/37010.
> Release notes for v19.1.0-rc.4

- v19.1/cockroachdb-in-comparison.md
SQL support was "Read-only", is now "Yes".
See also: https://cloud.google.com/spanner/docs/dml-syntax.
Fixes #4678.
> Update comparison chart for Spanner's SQL support

- _includes/sidebar-data-v19.1.managed.json
- v19.1/managed-authentication.md
- v19.1/managed-authorization.md
- v19.1/managed-cluster-management.md
- v19.1/managed-connect-to-your-cluster.md
- v19.1/managed-monitoring-page.md
- v19.1/managed-security-overview.md
- v19.1/managed-sql-audit-logging.md
- v19.1/managed-sql-users-page.md
Closes #4039
**Summary:**
- Created MSO security docs
- Deleted the user management doc and merged the content with the new managed-authorization doc
- Updated the sidebar nav
**Note for all reviewers:**
I have left out the 'how certs work' section and other conceptual info because I don't think MSO users need to worry about those details. However, I am open to including the details as well - let me know what you think. 
@jseldess After the IA discussion in our last 1:1, I thought it was better to make new documents for the managed security docs since I didn't find much content overlap with the CRDB docs. However, I am open to reuse the CRDB docs and use MSO-specific tags instead. Let me know what you prefer.
> Added MSO security docs

- .gitignore
- v19.1/indexes.md
- v2.1/indexes.md
* Suggest that users look to `EXPLAIN` plans to determine when an index is being used
* Modified the language around when indexes will slow down a write operation; it's a little more ambiguous than was implied.
> Clarifying some statements about indexes

- v2.1/upsert.md
The first sentence appears to contradict info in the following section. They both accomplish the same thing in declarative terms, but they can have quite different performance.
> Clarify UPSERT vs INSERT ON CONFLICT performance

- _config_base.yml
- _data/releases.yml
- _includes/sidebar-releases.json
- releases/v2.1.7.md
> Add v2.1.7 release notes

- _includes/v19.1/orchestration/kubernetes-remove-nodes-insecure.md
- _includes/v19.1/orchestration/kubernetes-remove-nodes-secure.md
In the "remove node" instructions of our secure k8s tutorial, we still reference a `kubectl` command. This PR removes that.
> Remove kubectl reference in helm step

- Makefile
- _config_base.yml
- _config_standard_local.yml
This PR adds `_config_standard_local.yml` and adjusts the Makefile to call this config as part of `make standard`. The config excludes the markdown files for all versions earlier than 2.1 and 19.1, dramatically cutting the number of files that get built.
Once we have 19.2 docs, we'll need to update this, and then again when 19.2 becomes the stable version. There's probably a less fragile way to do this, but this is a good first step.
Builds for our live site aren't affected, as they use the `standard-build` and `managed-build` make targets. Local builds of the managed docs also are not affected.
**Performance comparison**
On `master`, a fresh build (`rm -rf _site` and then `make standard`) takes ~42s and incremental changes take ~25s. Subsequent full builds, without clearing `_site`, take …
> Faster local builds

- v19.2/transactions.md
- v2.0/transactions.md
- v2.1/transactions.md
Apply https://github.com/cockroachdb/docs/pull/4913 to other doc version.
> Fix transactions doc typo

- v19.1/cost-based-optimizer.md
- v19.2/cost-based-optimizer.md
The documentation for the cost-based query optimizer uses `&emdash;`
instead of `&mdash;`, which isn't correct. Luckily, the fix is simple :)
> Fix em-dashes in cost-based query optimizer docs

- _includes/v19.1/misc/delete-statistics.md
- _includes/v19.2/misc/delete-statistics.md
- v19.1/cost-based-optimizer.md
- v19.2/cost-based-optimizer.md
... and node restarts after stats deletion to clear caches.
- Add a new subsection to CBO page, 'Controlling statistics refresh
rate', where we describe the cases when stats are refreshed in more
detail.
- To match the structure of the above, we break the instructions for
deleting stats into a new section 'Turning off statistics'
- Finally, tweak stats deletion instructions on CBO page and CREATE
STATS page so both say that nodes must be restarted
post-stats-deletion to clear caches.
Fixes #4809, #4872.
> Update docs on automatic stats refresh rate

- v19.1/partitioning.md
- v19.2/partitioning.md
- v2.0/partitioning.md
- v2.1/partitioning.md
A few of the intra-page links in partitioning.md were pointing to the
wrong section (the one they were already in rather than the relevant
example.)
> Fix anchor links in partitioning docs

- _includes/sidebar-data-v19.1.json
- _includes/sidebar-data-v19.2.json
- _includes/v19.1/misc/debug-subcommands.md
- _includes/v19.2/misc/debug-subcommands.md
- v19.1/cockroach-commands.md
- v19.1/debug-ballast.md
- v19.1/debug-encryption-active-key.md
- v19.1/debug-merge-logs.md
- v19.1/debug-zip.md
- v19.1/operational-faqs.md
- v19.1/recommended-production-settings.md
- v19.2/cockroach-commands.md
- v19.2/debug-ballast.md
- v19.2/debug-encryption-active-key.md
- v19.2/debug-merge-logs.md
- v19.2/debug-zip.md
- v19.2/operational-faqs.md
- v19.2/recommended-production-settings.md
> Document ballast file as production best practice

- _includes/v19.1/app/insecure/basic-sample.clj
- _includes/v19.1/app/insecure/basic-sample.cpp
- _includes/v19.1/app/insecure/txn-sample.clj
- _includes/v19.1/app/insecure/txn-sample.cpp
- _includes/v19.2/app/basic-sample.clj
- _includes/v19.2/app/basic-sample.cpp
- _includes/v19.2/app/insecure/basic-sample.clj
- _includes/v19.2/app/insecure/basic-sample.cpp
- _includes/v19.2/app/insecure/txn-sample.clj
- _includes/v19.2/app/insecure/txn-sample.cpp
- _includes/v19.2/app/txn-sample.clj
- _includes/v19.2/app/txn-sample.cpp
- v19.1/build-a-c++-app-with-cockroachdb.md
- v19.1/build-a-clojure-app-with-cockroachdb.md
- v19.2/build-a-c++-app-with-cockroachdb.md
- v19.2/build-a-clojure-app-with-cockroachdb.md
Added the following to the "Build an App with CockroachDB" examples:
- C++ secure application example
- Clojure secure application example
> Secure app examples

- _includes/v19.1/orchestration/kubernetes-scale-cluster.md
- _includes/v19.1/orchestration/start-cockroachdb-helm-insecure.md
- _includes/v19.1/orchestration/start-kubernetes.md
- _includes/v19.2/orchestration/kubernetes-scale-cluster.md
- _includes/v19.2/orchestration/start-cockroachdb-helm-insecure.md
- _includes/v19.2/orchestration/start-kubernetes.md
- v19.1/orchestrate-cockroachdb-with-kubernetes-insecure.md
- v19.2/orchestrate-cockroachdb-with-kubernetes-insecure.md
How to run insecure on EKS using configs and helm.
Running secure will be handled in a separate PR. 
- Secure with standard configs doesn't work due to some issue with Kubernetes-created CSRs on EKS. Will need to use different configs to use certs generated outside of Kubernetes. 
- Secure with helm won't work because it uses standard configs. We will probably need distinct helm charts to GKE and EKS. Opened this issue: cockroachdb/cockroach#38847. Secure with helm on EKS is therefore out-of-scope for now.
Addresses #5042.
> Single-region insecure cluster on EKS tutorial

- _includes/v19.1/orchestration/start-cockroachdb-secure.md
- _includes/v19.2/orchestration/start-cockroachdb-secure.md
- v19.1/orchestrate-cockroachdb-with-kubernetes.md
- v19.2/orchestrate-cockroachdb-with-kubernetes.md
This PR adds a note about using custom config for secure EKS deployment and calls out that secure EKS via Helm is not supported.
It is a continuation of https://github.com/cockroachdb/docs/pull/5047. 
Fixes #5042.
> Single-region secure cluster on EKS

- _includes/sidebar-data-v19.1.json
- _includes/sidebar-data-v19.2.json
- v19.1/advanced-client-side-transaction-retries.md
- v19.1/commit-transaction.md
- v19.1/common-errors.md
- v19.1/demo-serializable.md
- v19.1/performance-best-practices-overview.md
- v19.1/release-savepoint.md
- v19.1/rollback-transaction.md
- v19.1/transactions.md
- v19.2/advanced-client-side-transaction-retries.md
- v19.2/commit-transaction.md
- v19.2/common-errors.md
- v19.2/demo-serializable.md
- v19.2/performance-best-practices-overview.md
- v19.2/release-savepoint.md
- v19.2/rollback-transaction.md
- v19.2/transactions.md
- Split discussion of client-side retries roughly in two:
- Application developers should use an application-level retry loop
with exponential backoff
- Library authors should use SAVEPOINT and friends
- For application developers, update 'Transactions' page with example in
pseudocode showing how to implement an application-level retry loop
with exponential backoff.
- For library authors, break out discussion of client-side txn retries
using the SAVEPOINT protocol into a separate page, "Advanced
Client-side Transaction Retries".
Addresses the non-code-sample-update parts of #4810.
> Deemphasize SAVEPOINT retries (1/n)

- v19.1/backup.md
- v19.1/restore.md
- v19.2/backup.md
- v19.2/restore.md
> Edit BACKUP/RESTORE system.users

- v19.1/change-data-capture.md
In the first section in which the document describes connecting to Kafka it uses 2181 but then in the example using Kafka with Avro it says 8081 which is the schema registry, not zookeeper.
> Changed the port for zookeeper from 8081 to 2181

- _includes/v19.1/app/insecure/basic-sample.py
- v19.1/build-a-python-app-with-cockroachdb.md
... and update the surrounding descriptive text to match the new code.
Addresses #5035.
> Update Python psycopg2 example with app retry loop

- _includes/v19.1/app/insecure/gorm-sample.go
- v19.1/build-a-go-app-with-cockroachdb-gorm.md
... and update the surrounding descriptive text to match the new code.
Includes updates based on review comments in https://github.com/cockroachdb/docs/pull/5049, which for some reason stopped accepting updates.
Addresses #5035.
> Update GORM insecure example with app retry loop

- _includes/v1.1/prod-deployment/insecure-test-load-balancing.md
- _includes/v1.1/prod-deployment/secure-test-load-balancing.md
- _includes/v19.1/prod-deployment/insecure-test-load-balancing.md
- _includes/v19.1/prod-deployment/secure-test-load-balancing.md
- _includes/v19.2/prod-deployment/insecure-test-load-balancing.md
- _includes/v19.2/prod-deployment/secure-test-load-balancing.md
- _includes/v2.0/prod-deployment/insecure-test-load-balancing.md
- _includes/v2.0/prod-deployment/secure-test-load-balancing.md
- _includes/v2.1/prod-deployment/insecure-test-load-balancing.md
- _includes/v2.1/prod-deployment/secure-test-load-balancing.md
- v19.1/performance-benchmarking-with-tpc-c.md
- v19.2/performance-benchmarking-with-tpc-c.md
- v2.0/performance-benchmarking-with-tpc-c.md
- v2.1/performance-benchmarking-with-tpc-c.md
Changing the '|' to a ';' as the pipe does not change the permission of the workload file.
> Piping to chmod for workload doesn't work

- v19.1/known-limitations.md
- v19.2/known-limitations.md
- v2.1/known-limitations.md
see: 
https://github.com/cockroachdb/cockroach/issues/39117
https://cockroachdb.zendesk.com/agent/tickets/3517
Users can encounter this any time they have a large # of ranges (>500GiB per node), and cold start. I think it's worth documenting given that it can make an entire cluster unavailable until these steps are taken.
@bdarnell please ensure I didn't say anything inaccurate and @jseldess let me know if you think there's a better place for these :)
> Added new known limitation

- _includes/sidebar-data-v19.2.json
- v19.2/sql-tuning-with-explain.md
Closes #4692 
Note: The TC build's failing because of a link that points to a file in Eric's open PR. (https://github.com/cockroachdb/docs/pull/5075/files)
> Using EXPLAIN to troubleshoot SQL Performance

- v19.2/learn-cockroachdb-sql.md
#5040
This PR includes the "Learn CockroachDB SQL" MovR update, originally a part of the #5075 PR. I broke it out into a different feature branch because of the conflicts with MSO...
> Learn CRDB SQL MovR update

- _includes/sidebar-data-v19.2.json
- _includes/sidebar-data-v19.2.managed.json
- v19.2/migrate-from-oracle.md
- v19.2/migration-overview.md
> Oracle Migration Guide

- _includes/v19.2/sql/movr-start.md
- v19.2/migrate-from-oracle.md
- v19.2/movr.md
Pretty small PR
- Corrected syntax on cockroach workload in start instructions (cockroach workload needs a connection string - you can't use --host or --insecure or --cert-dir like you can for other cockroach commands)
- Added copy + paste instructions to MovR overview page
> Corrected syntax; expanded overview instructions

- v19.2/show-locality.md
Not just for single-node clusters, but any time a node is started
without `--locality` specified.
> Clarify when locality is NULL for SHOW LOCALITY

- Makefile
Bundler shouldn't be reinstalled just because the vendor directory is
out of date. (Directories appear out of date whenever a direntry is
changed; i.e., whenever a file is added or removed.) This was causing CI
to fail whenever vendor got an earlier mtime than bootstrap, because it
looked like bootstrap was out of date and thus dependencies were being
reinstalled.
> Makefile: mark vendor as an order-only dependency

- _includes/v19.2/performance/partition-by-city.md
- _includes/v19.2/sql/movr-statements-partitioning.md
- _includes/v19.2/zone-configs/create-a-replication-zone-for-a-table-partition.md
- v19.2/demo-geo-partitioning.md
- v19.2/partitioning.md
- v19.2/topology-geo-partitioned-leaseholders.md
- v19.2/topology-geo-partitioned-replicas.md
Updated partition examples with secondary indexes to:
- Use the same partition names for primary and secondary index partitions on the same table
- Use `ALTER PARTITION ... OF INDEX` when configuring zone constraints on secondary-index partitions
Fixes #5245. 
Added Solon and Andy to the review as well.
> Partition names reused across primary and secondary indexes

- _includes/v19.2/sql/aggregates.md
- v19.2/functions-and-operators.md
- v19.2/select-clause.md
Added note and examples about ordering non-commutative aggregate function inputs.
Fixes #4801. 
See accompanying cockroach PR: https://github.com/cockroachdb/cockroach/pull/40316
> Non-commutative aggregate functions

- js/customscripts.js
The terminal prompt was using the same class as double-quoted SQL
strings in the new version of the syntax highlighter, which was causing
the prompt detection code to inadvertently remove double-quoted SQL
strings.
Teach the prompt detection code to double-check that the prompt it's
removing is actually at the beginning of the code block and only
contains the prompt character ($) or (<) to avoid accidentally removing
strings.
> Tweak syntax highlighting prompt detection

- _includes/v19.1/orchestration/start-cockroachdb-helm-secure.md
- _includes/v19.1/orchestration/start-cockroachdb-secure.md
- _includes/v19.1/orchestration/test-cluster-secure.md
- _includes/v19.2/orchestration/start-cockroachdb-helm-secure.md
- _includes/v19.2/orchestration/start-cockroachdb-secure.md
- _includes/v19.2/orchestration/test-cluster-secure.md
- v19.1/orchestrate-cockroachdb-with-kubernetes.md
- v19.2/orchestrate-cockroachdb-with-kubernetes.md
Callout naming requirements for StatefulSet and Helm chart names
and for SQL usernames.
Fixes #5365.
> Document CSR naming limitation

- _includes/v19.2/app/basic-sample.py
- _includes/v19.2/app/insecure/basic-sample.py
- v19.2/build-a-python-app-with-cockroachdb.md
Also, delete the comments in the Python code that state that
`crdb_internal.force_retry()` must be run as root.  This restriction was
lifted in https://github.com/cockroachdb/cockroach/pull/39246.
The 19.1 Python code samples were updated in #5085 and #5173.  We then
forgot to port those changes to 19.2.  This commit remedies that
oversight.
Addresses part of #5176.
> Update 19.2 Python code with app retry loop

- v19.2/cockroach-workload.md
Fixes #5309.
Note: There are several other issues for documenting other new flags and `workload` abilities. This PR is restricted to the new `--display-every` and `--display-format` flags.
> Document workload flags for stats frequency and format

- v19.2/frequently-asked-questions.md
- v19.2/sql-dump.md
- v19.2/sql-faqs.md
- v19.2/use-the-built-in-sql-client.md
Also link to corresponding `SHOW` statements for client-side
commands, where relevant, and remove "as of xxx" references 
to older versions.
Fixes #5376.
> Document \d client-side command with no argument

- _includes/v19.2/sql/diagrams/table_ref.html
- v19.2/table-expressions.md
Fixes #4886.
- Updated table expression diagram.
- Updated parameters on table expression page.
- Updated "Using the output of other statements" section on table expression page.
I'm not really finding any examples in doc where we use newly-invalid row sources in selection clauses. The only area of prose/syntax doc that I'd be concerned about is [table expressions](https://www.cockroachlabs.com/docs/v19.2/table-expressions.html). The [selection queries](https://www.cockroachlabs.com/docs/v19.2/selection-queries.html#using-any-table-expression-as-selection-clause) page reads:
> Any table expression can be used as a selection clause (and thus also a selection query) by prefixing it with TABLE or by using it as an operand to SELECT * FROM.
@RaduBerinde 
In …
> Updated table expression diagram and page for row sources

- v19.1/install-cockroachdb-mac.html
- v19.2/install-cockroachdb-mac.html
- Change from core brew to our tap.
- Remove notes about exclusion of CCL features.
At the moment, this change is only visible for 19.1,
our current stable version, but the copy is in place
for 19.2 as well.
Fixes #5443.
> Update homebrew instructions

- _includes/v19.2/sql/diagrams/show_backup.html
- v19.2/show-backup.md
> SHOW BACKUP SCHEMAS

- _data/releases.yml
- _includes/sidebar-releases.json
- releases/v2.1.9.md
> v2.1.9 release notes

- v19.2/joins.md
Fixes #4443.
Wording clarified on merge joins to reflect nuance of join choice algorithm.
> Merge join doc clarification

- v19.1/deploy-cockroachdb-on-aws-insecure.md
- v19.1/deploy-cockroachdb-on-aws.md
- v19.1/deploy-cockroachdb-on-google-cloud-platform-insecure.md
- v19.1/deploy-cockroachdb-on-google-cloud-platform.md
- v19.1/recommended-production-settings.md
- v19.2/deploy-cockroachdb-on-aws-insecure.md
- v19.2/deploy-cockroachdb-on-aws.md
- v19.2/deploy-cockroachdb-on-google-cloud-platform-insecure.md
- v19.2/deploy-cockroachdb-on-google-cloud-platform.md
- v19.2/recommended-production-settings.md
Increase optimal vCPUs to 32.
Update GCP and AWS recs as well. Holding off on Azure until
the upcoming cloud report, at which point we should revisit
our hardware recs more broadly.
Fixes #4711.
> Clarify hardware recs for throughput

- _includes/unsupported-version-soon.md
- _includes/unsupported-version.md
- _layouts/page.html
- Mark everything before 2.0 as unsupported.
- Mark 2.0 as soon to be unsupported.
Our policy is that we support stable plus the two versions
prior.
We'll have to adjust this again with the 19.2 release.
Fixes #5477.
> Update unsupported warning on older doc versions

- js/customscripts.js
Previously we would mark something as a prompt if it matched the
character and was preceeded by nothing or a string of only whitespace
characters. However with strings like `id > 0` the space before the `>`
would be seen as empty since the `id` was a non-text DOM node.
To fix this, require that the `>` be after a newline.
Fixes #5480
> fix prompt marker detection

- _includes/sidebar-data-v19.2.json
- _includes/v19.2/sql/diagrams/split_index_at.html
- _includes/v19.2/sql/diagrams/split_table_at.html
- _includes/v19.2/sql/diagrams/unsplit_index_at.html
- _includes/v19.2/sql/diagrams/unsplit_table_at.html
- _includes/v19.2/sql/movr-start-nodes.md
- _includes/v19.2/sql/movr-statements-nodes.md
- _includes/v19.2/sql/movr-statements-partitioning.md
- v19.2/alter-index.md
- v19.2/alter-table.md
- v19.2/split-at.md
- v19.2/sql-statements.md
- v19.2/unsplit-at.md
- Added new page for `UNSPLIT AT` statement.
- Added new diagrams for `UNSPLIT AT` statement.
- Added new diagrams/parameter for `SPLIT AT` statement for WITH EXPIRATION.
- Changed all `UNSPLIT AT` examples to use `movr` database.
Fixes #4895.
Fixes #5008.
Fixes #5007.
> UNSPLIT AT statement page and diagrams

- _includes/v19.1/prod-deployment/secure-generate-certificates.md
- _includes/v19.2/prod-deployment/secure-generate-certificates.md
- v19.1/configure-replication-zones.md
- v19.1/create-security-certificates-openssl.md
- v19.1/monitor-cockroachdb-with-prometheus.md
- v19.2/configure-replication-zones.md
- v19.2/create-security-certificates-openssl.md
- v19.2/monitor-cockroachdb-with-prometheus.md
- v2.1/create-security-certificates-openssl.md
`$` prompt gets auto-added to the first line. We should remove
that behavior at some point, but this is a fix for now.
> Adjust shell samples to not start with comments

- v19.2/information-schema.md
Fixes #5184. 
This PR contains the following changes:
- `check_constraints` table added to `information_schema` doc
- `information_schema` doc examples now use MovR database
> check_constraints table added to information_schema doc

- _includes/v19.2/sql/movr-start-nodes.md
- _includes/v19.2/sql/movr-statements-nodes.md
- _includes/v19.2/sql/movr-statements-partitioning.md
- v19.2/cockroach-demo.md
Fixes #5380.
- Added note to `cockroach demo` page about telemetry.
- Fixed "Flags" section headings.
> Telemetry enabled by default in cockroach demo

- v19.2/configure-replication-zones.md
- v19.2/show-create.md
- v19.2/show-partitions.md
- v19.2/show-zone-configurations.md
Fixes #5407.
- Added notes on zone configuration warning message in SHOW CREATE TABLE
- Changed all SHOW CREATE examples to use MovR dataset
> Warning message in SHOW CREATE TABLE about zone configurations

- _includes/v19.2/app/gorm-sample.go
- _includes/v19.2/app/insecure/gorm-sample.go
> GORM: `force_retry()` does not need root in 19.2

- v19.2/timestamp.md
Fixes #5005.
- Added doc about specifying precision for timestamp objects
- Updated timestamp example output
> Timestamp precision doc

- v19.2/show-partitions.md
Fixes #5533. 
(Reverts https://github.com/cockroachdb/docs/pull/5364).
I just removed the note that says that `SHOW PARTITIONS` doesn't show inherited zone configurations.
> Display inherited constraints in SHOW PARTITIONS

- v19.2/show-locality.md
- v19.2/start-a-node.md
Fixes #5536.
Fixes #4890. 
Added examples for `crdb_internal.locality_value` to `show-locality.md` and `start-a-node.md`.
Built-in function reference already generated in https://www.cockroachlabs.com/docs/dev/functions-and-operators.html#system-info-functions.
> crdb_internal.locality_value

- _config_base.yml
We forgot this in https://github.com/cockroachdb/docs/pull/5498.
> Make site recognize 19.1.5 as latest stable version

- v19.1/use-the-built-in-sql-client.md
Current render doesn't lint shell code (screencap)
Suggested edit fixes this (screencap)
> Add line feed preceding code fence

- v19.2/build-a-java-app-with-cockroachdb.md
> Document JDBC driver cursor support

- _includes/v19.2/sql/movr-statements-geo-partitioned-replicas.md
- v19.2/experimental-features.md
- v19.2/generate-cockroachdb-resources.md
- v19.2/performance-tuning-insecure.md
- v19.2/performance-tuning.md
- v19.2/show-ranges.md
- v19.2/training/data-unavailability-troubleshooting.md
- v19.2/training/geo-partitioning.md
- v19.2/training/locality-and-replication-zones.md
Fixes #5406.
Fixes #5374. 
Fixes #5375. 
- Updated SHOW RANGES examples on SHOW RANGES page
- Added Response section to SHOW RANGES doc page
- Updated SHOW RANGES output on performance tuning pages
- Updated SHOW RANGES output on several training pages
- Removed SHOW RANGES from experimental features
*Note*: @jseldess We should update the [Define Table Partitions](https://www.cockroachlabs.com/docs/dev/partitioning.html) page in a separate PR, as a part of a separate issue. I had a very hard time following the examples on the page. I will open a separate issue.
> SHOW RANGES updates

- v19.1/training/fault-tolerance-and-automated-repair.md
- v19.2/training/fault-tolerance-and-automated-repair.md
Updated the Fault Tolerance and Automated Repair training doc in 19.1 and 19.2. This step isn't in previous docs versions.
The analogous 19.2 Fault Tolerance article in Tutorials already has the correct syntax.
> Fix write syntax in fault tolerance training

- v19.2/cockroach-demo.md
Fixes #5519.
- New flag entry
- New example
> --geo-partitioned-replicas flag

- _includes/sidebar-data-v19.2.cockroachcloud.json
Closes https://github.com/cockroachdb/docs/issues/5598
The tutorial was already ported but wasn't added to the sidebar nav. Adding it in this PR.
> Added app tutorial to sidebar nav

- v19.2/configure-replication-zones.md
Fixes #5278.
Added a bullet to the general guidance on defining *required* and *prohibited* zone constraints.
> Conflicting zone constraints

- _includes/v19.2/sql/function-special-forms.md
- v19.2/timestamp.md
Fixes #5286.
- Added `AT TIME ZONE` to special syntax table
- Added note to `TIMESTAMP` page about converting between `TIMESTAMP` and `TIMESTAMPTZ`
> timezone() and AT TIME ZONE

- v19.2/delete.md
- v19.2/indexes.md
- v19.2/table-expressions.md
- v19.2/update.md
Fixes #5547.
Changes include:
- New sections in DELETE and UPDATE statement pages
- New examples in DELETE and UPDATE statement pages
- Callout on Indexes and Table Expressions pages
> Force index selection for DELETE and UPDATE statements

- v19.1/index.md
- v19.2/index.md
- v2.1/index.md
This uses the homepage_title field from the relevant
config as the index.html h1. CockroachCloud Docs for
CockroachCloud, and CockroachDB Docs for CockroachDB.
Fixes #5651.
> Add homepage front-matter field

- v1.0/add-constraint.md
- v1.0/column-families.md
- v1.0/create-table-as.md
- v1.0/create-table.md
- v1.0/show-create-table.md
- v1.1/add-constraint.md
- v1.1/column-families.md
- v1.1/create-table-as.md
- v1.1/create-table.md
- v1.1/show-create-table.md
- v1.1/show-trace.md
- v19.1/column-families.md
- v19.1/create-table-as.md
- v19.1/show-trace.md
- v19.2/column-families.md
- v19.2/show-trace.md
- v2.0/add-constraint.md
- v2.0/column-families.md
- v2.0/create-table-as.md
- v2.0/create-table.md
- v2.0/show-create-table.md
- v2.0/show-trace.md
- v2.1/add-constraint.md
- v2.1/column-families.md
- v2.1/create-table-as.md
- v2.1/show-trace.md
I noticed that a few of our example CLI outputs had ␤ characters at the
end of each line. I think this is a just display artifact from an older
version of the Cockroach CLI, so I removed them.
> Remove ␤ characters from example outputs
