cockroachdb/docs

- v2.0/backup.md
- v2.0/experimental-audit.md
This PR takes over changes from https://github.com/cockroachdb/docs/pull/3297 and https://github.com/cockroachdb/docs/pull/3295.
Thanks for @Princesso for initiating the changes.
> Copy to clipboard updates

- _includes/footer.html
* update 'Pricing' copy to 'Subscriptions'
> Update footer to match Marketing website

- _includes/sidebar-data-v2.0.json
- _includes/sidebar-data-v2.1.json
Addresses https://github.com/cockroachdb/docs/issues/3377#issuecomment-404653014.
> Shorten performance benchmarking in sidenav

- v2.0/known-limitations.md
- v2.1/known-limitations.md
> Resolve known limitation with CHECK constraints on upsert

- v1.1/training/index.md
- v2.0/training/index.md
- v2.1/training/index.md
> Remove feedback widget from training landing page

- v1.0/build-a-go-app-with-cockroachdb-gorm.md
- v1.0/build-a-go-app-with-cockroachdb.md
- v1.1/build-a-go-app-with-cockroachdb-gorm.md
- v1.1/build-a-go-app-with-cockroachdb.md
- v2.0/build-a-go-app-with-cockroachdb-gorm.md
- v2.0/build-a-go-app-with-cockroachdb.md
- v2.1/build-a-go-app-with-cockroachdb-gorm.md
- v2.1/build-a-go-app-with-cockroachdb.md
Follow-up to https://github.com/cockroachdb/docs/pull/3403.
> Update GORM link

- _includes/v2.0/prod-deployment/insecure-start-nodes.md
- _includes/v2.0/prod-deployment/insecurecockroachdb.service
- _includes/v2.0/prod-deployment/secure-start-nodes.md
- _includes/v2.0/prod-deployment/securecockroachdb.service
- _includes/v2.1/prod-deployment/insecure-start-nodes.md
- _includes/v2.1/prod-deployment/insecurecockroachdb.service
- _includes/v2.1/prod-deployment/secure-start-nodes.md
- _includes/v2.1/prod-deployment/securecockroachdb.service
- v2.0/upgrade-cockroach-version.md
- v2.1/upgrade-cockroach-version.md
- Added the `advertise-host` flag to systemd configuration files and parameters table
- Updated the rolling upgrades process for systemd
Tested on Digital Ocean.
> Using Systemd (Config changes + rolling upgrades)

- v2.1/change-data-capture.md
Updates to alpha docs based on user feedback.
> CDC Updates

- _includes/v2.1/sql/functions.md
- _includes/v2.1/sql/window_functions.md
- v2.1/functions-and-operators.md
- Add `chr`, `convert_to`, and `convert_from`.
- Add auto-generated docs on window functions.
> Update 2.1 functions

- _includes/v2.1/sql/diagrams/simple_select_clause.html
- _includes/v2.1/sql/diagrams/stmt_block.html
> Regenerate full 2.1 sql grammar

- _redirects
> Redirect for /docs

- v2.0/partition-by.md
- v2.1/partition-by.md
> Remove mention of future ability to alter primary key

- _includes/sidebar-data-v2.1.json
- v2.1/cockroach-commands.md
- v2.1/cockroach-demo.md
- v2.1/learn-cockroachdb-sql.md
- v2.1/use-the-built-in-sql-client.md
> Document the cockroach demo command

- v2.1/encryption.md
Also mentioned key information written to log files.
Both changes occured recently.
> Describe runtime key rotation in encryption page.

- v2.0/information-schema.md
- v2.1/information-schema.md
- v2.1/query-order.md
Closes #3441. (add SHOW ROLES)
Closes #3440. (add sequences / name resolution)
Closes #3325. (add routines / parameters tables note)
Cloes #3224. (add constaint_column_usage)
> information_schema updates

- v2.0/performance-benchmarking-with-tpc-c.md
- v2.1/performance-benchmarking-with-tpc-c.md
> Performance Benchmarking TPC-C 10K

- _config.yml
- _data/releases.yml
- _includes/sidebar-releases.json
- releases/v2.0.5.md
- releases/v2.1.0-alpha.20180730.md
See https://github.com/cockroachdb/cockroach/issues/28310.
> Add v2.0.5 release notes

- v2.0/backup.md
- v2.0/import.md
- v2.0/restore.md
- v2.1/backup.md
- v2.1/import.md
- v2.1/restore.md
> Updated backup/restore/import job creation

- _includes/heap_analytics.html
- _layouts/default.html
Just what it says on the tin: Adding Heap analytics to docs site
> add Heap Analytics to docs

- _includes/v2.1/computed-columns/convert-computed-column.md
- _includes/v2.1/sql/diagrams/alter_column.html
- v2.1/alter-column.md
- v2.1/computed-columns.md
Remove the "computed-ness" from a column. Follow up work to be done on #2992.
Closes #3220.
> Convert computed column to regular column

- v2.1/import.md
@bobvawter Commit 1 addresses #3093 
@dt Commit 2 addresses #3337
> Import doc updates: Skip n lines + support decompressing input files

- v2.1/show-columns.md
> Fix show columns example

- v2.0/performance-best-practices-overview.md
- v2.0/performance-tuning.md
- Fix typo on perf tuning tutorial.
- Cross-reference the perf tuning tutorial from the SQL best practices page.
> Tuning fix

- v2.1/admin-ui-statements-page.md
> Updated content for Statements page

- _includes/sidebar-data-v2.1.json
- _includes/v2.1/orchestration/kubernetes-limitations.md
- _includes/v2.1/orchestration/start-kubernetes.md
- v2.1/orchestrate-cockroachdb-with-kubernetes-insecure.md
- v2.1/orchestrate-cockroachdb-with-kubernetes-multi-region.md
- v2.1/orchestrate-cockroachdb-with-kubernetes.md
Fixes #2933.
Follow-up work: https://github.com/cockroachdb/docs/issues/3591.
> Document multi-region Kubernetes deployment

- scripts/issues-from-release-notes.py
Thanks to @knz for the guidance.
> Update issues-from-release-notes.py script to handle nested bullets

- _includes/sidebar-data-v2.1.json
- releases/v2.1.0-beta.20180827.md
- v2.1/orchestrate-cockroachdb-with-kubernetes-insecure.md
- v2.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
- v2.1/orchestrate-cockroachdb-with-kubernetes.md
- Fix filename and links
- Add redirect from previous url
> Tweaks to multi-cluster k8s deployment

- v2.0/partitioning.md
earlier version had inconsistent localities between steps 2 and 5.
> Corrected localities on partitioning doc

- v2.1/scalar-expressions.md
> Explain ARRAY(a,b,c).

- _includes/v2.1/sql/aggregates.md
- _includes/v2.1/sql/diagrams/stmt_block.html
- _includes/v2.1/sql/diagrams/table_ref.html
- _includes/v2.1/sql/functions.md
- _includes/v2.1/sql/operators.md
- _includes/v2.1/sql/settings/settings.md
- _includes/v2.1/sql/window_functions.md
- Updates v2.1 functions and operators.
- Updates v2.1 full grammar.
Fixes #3627.
Fixes #3626.
Partially addresses #2982.
> Update 2.1 functions and grammar

- _config.yml
- _data/releases.yml
- releases/v2.1.0-beta.20180904.md
For https://github.com/cockroachdb/cockroach/issues/29164.
> Release notes for v2.1.0-beta.20180904 

- v2.0/get-started-with-enterprise-trial.md
Didn't realize I missed the file save on fixing the format in the callout on this page.
> fix formatting for v2.0/get-started-with-enterprise-trial.md

- v2.0/training/data-import.md
- v2.0/training/sql-basics.md
> Add SQL Basics to 2.0 training

- v2.0/training/sql-basics.md
- v2.1/training/sql-basics.md
> Fix SQL Basics training

- v2.0/training/sql-basics.md
- v2.1/training/sql-basics.md
> Remove OPEN> from transaction example

- _includes/sidebar-data-v2.1.json
- _includes/v2.1/sql/diagrams/alter_type.html
- v2.1/alter-table.md
- v2.1/alter-type.md
- v2.1/sql-statements.md
> Document `Alter type` subcommand

- v2.1/create-and-manage-users.md
- v2.1/create-user.md
- v2.1/grant.md
- v2.1/roles.md
All users belong to the role `public`.
Closes #2984.
> Add public role

- _includes/v2.1/sql/connection-parameters-with-url.md
- _includes/v2.1/sql/connection-parameters.md
- v2.1/configure-replication-zones.md
- v2.1/connection-parameters.md
- v2.1/create-and-manage-users.md
- v2.1/sql-dump.md
- v2.1/use-the-built-in-sql-client.md
- v2.1/view-node-details.md
Update from https://github.com/cockroachdb/cockroach/pull/29467
> Update the description of client parameters

- v1.1/architecture/sql-layer.md
- v2.0/architecture/sql-layer.md
- v2.1/architecture/sql-layer.md
This came up on Gitter today - a user was surprised at the discrepancy.
> Improve the description of SQL planning.

- v2.1/orchestrate-cockroachdb-with-kubernetes.md
Follow-up to https://github.com/cockroachdb/docs/pull/3749.
> Fix link in 2.1 k8s tutorial

- v2.1/backup.md
- v2.1/cancel-job.md
- v2.1/cancel-query.md
- v2.1/cancel-session.md
- v2.1/cluster-settings.md
- v2.1/configure-replication-zones.md
- v2.1/create-and-manage-users.md
- v2.1/create-database.md
- v2.1/create-user.md
- v2.1/experimental-audit.md
- v2.1/export.md
- v2.1/import.md
- v2.1/rename-database.md
- v2.1/reset-cluster-setting.md
- v2.1/restore.md
- v2.1/set-cluster-setting.md
- v2.1/show-backup.md
- v2.1/show-cluster-setting.md
> Replace mentions of root with admin role

- _includes/sidebar-data-v2.1.json
- releases/v2.1.0-alpha.20180702.md
- v2.1/admin-ui-access-and-navigate.md
- v2.1/admin-ui-cluster-overview-page.md
> Remove cluster variable content for user auth + restructure UI docs

- _includes/v2.1/sql/diagrams/cancel_job.html
- _includes/v2.1/sql/diagrams/pause_job.html
- _includes/v2.1/sql/diagrams/resume_job.html
- v2.1/cancel-job.md
- v2.1/pause-job.md
- v2.1/resume-job.md
> Add CANCEL/PAUSE/RESUME JOBS variants

- v2.0/known-limitations.md
- v2.0/upgrade-cockroach-version.md
- v2.1/known-limitations.md
- v2.1/upgrade-cockroach-version.md
- Use release_version front-matter value
- Update formatting of some callouts
> Keep cockroach version up-to-date in upgrade and limitations pages

- v2.1/training/cluster-upgrade.md
> Correct versions in 2.1 cluster upgrade training

- v2.0/build-a-go-app-with-cockroachdb-gorm.md
- v2.0/build-a-go-app-with-cockroachdb.md
- v2.1/build-a-go-app-with-cockroachdb-gorm.md
- v2.1/build-a-go-app-with-cockroachdb.md
> Use go get in Go tutorial

- _config.yml
- _data/releases.yml
- _includes/v2.1/sql/settings/settings.md
- releases/v2.1.0-beta.20180924.md
For https://github.com/cockroachdb/cockroach/issues/30340.
> Release notes for v2.1.0-beta.20180924

- _config.yml
- _data/releases.yml
- _includes/sidebar-releases.json
- releases/v1.1.9.md
- releases/v2.0.6.md
- releases/v2.1.0-beta.20181001.md
See https://github.com/cockroachdb/cockroach/issues/30569, https://github.com/cockroachdb/cockroach/issues/30573, https://github.com/cockroachdb/cockroach/issues/30602. 
Fixes #3785.
> Release notes

- v2.1/debug-zip.md
- v2.1/generate-cockroachdb-resources.md
- v2.1/stop-a-node.md
Add `--url` where missing & minor updates
Closes #3757.
> CLI updates

- v2.1/recommended-production-settings.md
> Memory warning

- v2.1/show-columns.md
> Show hidden columns

- v2.0/get-started-with-enterprise-trial.md
- v2.1/get-started-with-enterprise-trial.md
Marketing requested we add links to a few more features to the intro of this page.
> add links to enterprise features in intro graf

- _includes/v2.1/misc/haproxy.md
- _includes/v2.1/sql/connection-parameters.md
- v2.1/demo-automatic-cloud-migration.md
- v2.1/deploy-cockroachdb-on-premises-insecure.md
- v2.1/deploy-cockroachdb-on-premises.md
- v2.1/generate-cockroachdb-resources.md
> Document locality filter for cockroach gen haproxy

- _includes/v2.1/misc/schema-changes-within-transactions.md
> Update known limitation: schema changes in txns

- v2.0/install-cockroachdb.html
- v2.1/install-cockroachdb.html
> Correct docker release reference

- v2.1/detailed-sql-support.md
- Removed bolding
- Replaced < and > so they can render correctly
Closes #3801.
> Sql comparison

- v2.1/set-vars.md
> Document `SET SCHEMA` syntax

- _includes/v2.0/orchestration/start-cluster.md
- _includes/v2.1/orchestration/start-cluster.md
- v2.0/kubernetes-performance.md
- v2.1/kubernetes-performance.md
See https://github.com/cockroachdb/cockroach/pull/31015.
> Call out performance config for insecure k8s deployments

- _includes/v2.1/faq/auto-generate-unique-ids.html
- _includes/v2.1/sql/functions.md
- v2.1/serial.md
> Add better examples / language around monotonicity

- _config.yml
- _data/releases.yml
- releases/v1.1.9.md
- releases/v2.0.6.md
- releases/v2.1.0-beta.20180924.md
- releases/v2.1.0-beta.20181001.md
- releases/v2.1.0-beta.20181008.md
For https://github.com/cockroachdb/cockroach/issues/30831.
> Release notes for v2.1.0-beta.20181008

- v2.1/information-schema.md
> Add numeric_precision_radix to information_schema.columns

- _includes/sidebar.html
To understand users' queries, I need to add a class to track submissions to this form.
> add class to search form for query tracking

- _includes/v2.1/misc/external-urls.md
> Updated content for AWS_REGION parameter

- v2.1/sql-name-resolution.md
> Add docs on index name resolution

- _includes/head.html
- _includes/vwo.html
* add VWO pixel for A/B site testing
> Add VWO pixel

- _config.yml
- _data/releases.yml
- releases/v2.1.0-beta.20181015.md
See https://github.com/cockroachdb/cockroach/issues/31085.
> Add v2.1.0-beta.20181015 release notes

- _includes/topnav.html
* update CTA link in header to point to new 'Start Trial' page
> Update header CTA link

- releases/v2.1.0-beta.20181015.md
- scripts/issues-from-release-notes.py
- Change label that script applies to docs issues
- Remove comments
> Issue script update

- v2.0/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
- v2.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
I'm not convinced this is the best place to put it. Let me know if you
think it deserves its own section rather than just being a "if the above
didn't work" step.
Fixes #3591
This solves the problem I rambled about in https://github.com/cockroachdb/docs/issues/3591#issuecomment-428686994
> Document need for a firewall rule in multi-cluster kubernetes guide

- v2.1/encryption.md
In particular, make it more explicit and scarier.
Fixes #3877.
> Update Encryption at Rest experimental warning

- _config_base.yml
- _data/releases.yml
- releases/v2.1.0-rc.1.md
See https://github.com/cockroachdb/cockroach/issues/31359.
> Add release notes for v2.1.0-rc.1

- v2.1/inverted-indexes.md
Documenting Ben's knowledge bomb from [the forum](https://forum.cockroachlabs.com/t/jsonb-filtering-on-numbers/2094/2).
This isn't super intuitive and it's probably going to come up again.
> Inverted Index Comparisons

- v2.0/inverted-indexes.md
Same as https://github.com/cockroachdb/docs/pull/3904
> Following PR 3904, making same change for v2.0

- v2.0/frequently-asked-questions.md
- v2.1/frequently-asked-questions.md
Also mark "cloud dbaas" as coming soon.
> Update when cockroach is not suitable

- _config_base.yml
- _data/releases.yml
- releases/v2.1.0-rc.2.md
See https://github.com/cockroachdb/cockroach/issues/31767.
> Add release notes for v2.1.0-rc.2

- v2.1/subqueries.md
> Document support for correlated subqueries

- v2.1/show-jobs.md
> Update SHOW JOBS with sort

- v2.1/known-limitations.md
> Remove the ON CONFLICT CHECK known limitation

- _includes/sidebar-data-v2.1.json
- _includes/v2.1/sql/diagrams/create_stats.html
- _includes/v2.1/sql/diagrams/show_stats.html
- v2.1/cost-based-optimizer.md
- v2.1/create-statistics.md
- v2.1/show-statistics.md
- v2.1/sql-statements.md
> CREATE / SHOW STATISTICS 

- _includes/v2.1/orchestration/monitor-cluster.md
- _includes/v2.1/prod-deployment/secure-test-load-balancing.md
- v2.1/admin-ui-access-and-navigate.md
- v2.1/known-limitations.md
- v2.1/monitoring-and-alerting.md
- v2.1/orchestrate-cockroachdb-with-docker-swarm.md
- v2.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
- v2.1/orchestrate-cockroachdb-with-kubernetes.md
- v2.1/secure-a-cluster.md
- v2.1/training/security.md
- v2.1/upgrade-cockroach-version.md
Closes #3765 
- Added a UI user auth known issue
- Updated deployment, orchestration, and training docs with content for UI user auth
> UI user auth follow-up work

- v2.1/cockroach-commands.md
- v2.1/common-errors.md
- v2.1/demo-automatic-cloud-migration.md
- v2.1/demo-automatic-rebalancing.md
- v2.1/demo-data-replication.md
- v2.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
- v2.1/orchestrate-cockroachdb-with-kubernetes.md
- v2.1/partitioning.md
- v2.1/performance-tuning.md
- v2.1/training/data-unavailability-troubleshooting.md
- v2.1/training/fault-tolerance-and-automated-repair.md
- v2.1/training/locality-and-replication-zones.md
> Remove misc references to `cockroach zone`

- v2.1/explain.md
> Update EXPLAIN examples to show filter and join conditions

- _config_base.yml
- releases/v2.1.0-rc.1.md
- releases/v2.1.0-rc.2.md
- releases/v2.1.0.md
- v2.0/install-cockroachdb.html
- v2.1/install-cockroachdb.html
> Make it easier to get docker image for specific versions

- _includes/sidebar-data-v2.0.json
- _includes/sidebar-data-v2.1.json
- v2.0/alter-table.md
- v2.0/sql-statements.md
- v2.1/alter-table.md
- v2.1/alter-type.md
- v2.1/sql-statements.md
> Add VALIDATE CONSTRAINT to sidenav and sql statement overview

- v2.1/upgrade-cockroach-version.md
> Update rolling upgrade doc to leverage admin UI in preparation phase

- _includes/head.html
- _layouts/page.html
- v2.1/index.md
> Revert "Correct managed home page title"

- CONTRIBUTING.md
This is not synchronized with Makefile content.
> Update CONTRIBUTION.md test run section

- _includes/v2.0/app/basic-sample.go
- _includes/v2.0/app/txn-sample.go
- _includes/v2.1/app/basic-sample.go
- _includes/v2.1/app/txn-sample.go
> Add db.Close() to go samples

- v2.1/insert.md
> Remove extra div tag from INSERT doc

- v2.1/change-data-capture.md
- v2.1/create-changefeed.md
> Add link to CDC use case

- v2.1/import.md
- v2.1/sql-dump.md
> Support cockroach dump in IMPORT PGDUMP

- _includes/v2.0/app/TxnSample.java
Follow-up to https://github.com/cockroachdb/docs/pull/4047.
> Backport Java code sample fix to 2.0

- v2.1/cockroach-demo.md
- v2.1/use-the-built-in-sql-client.md
- v2.2/cockroach-demo.md
- v2.2/use-the-built-in-sql-client.md
> Add quit and exit commands for exiting the sql shell

- v2.1/diagnostics-reporting.md
- v2.2/diagnostics-reporting.md
Fixes #4079.
Fixes #4064.
Fixes #4063.
> Add new details to diagnostics reporting doc

- css/customstyles.css
- css/customstyles.scss
> fix anchor jump on page load

- _includes/v2.2/sql/settings/settings.md
> Update 2.2 cluster settings doc

- _includes/sidebar-data-v2.1.json
- _includes/sidebar-data-v2.2.json
- v2.1/cockroach-commands.md
- v2.1/use-the-query-formatter.md
- v2.2/cockroach-commands.md
- v2.2/use-the-query-formatter.md
> 20181026 sqlfmt

- v2.1/create-index.md
- v2.2/create-index.md
> PK columns cannot be included in STORING

- v2.1/show-jobs.md
- v2.2/show-jobs.md
> DROP TABLE does not show up in SHOW JOBS

- v2.1/start-a-node.md
- v2.2/start-a-node.md
> Adding missing --join flags to cross-network example

- _config_base.yml
- _data/releases.yml
- _includes/sidebar-releases.json
- releases/v2.0.7.md
- releases/v2.1.2.md
- releases/v2.2.0-alpha.20181119.md
For https://github.com/cockroachdb/cockroach/issues/32847 and https://github.com/cockroachdb/cockroach/issues/32890.
> Release notes for v2.0.7 and v2.1.2

- v2.0/architecture/transaction-layer.md
- v2.1/architecture/transaction-layer.md
- v2.2/architecture/transaction-layer.md
> Remove duplicated 'Timestamp cache' entries

- _includes/v2.1/prod-deployment/secure-generate-certificates.md
- _includes/v2.2/prod-deployment/secure-generate-certificates.md
- v2.1/admin-ui-access-and-navigate.md
- v2.1/create-security-certificates-custom-ca.md
- v2.1/create-security-certificates-openssl.md
- v2.1/create-security-certificates.md
- v2.1/performance-tuning.md
- v2.2/admin-ui-access-and-navigate.md
- v2.2/create-security-certificates-custom-ca.md
- v2.2/create-security-certificates-openssl.md
- v2.2/create-security-certificates.md
- v2.2/performance-tuning.md
> Improve certs documentation

- _includes/v1.0/app/basic-sample.cs
- _includes/v1.0/app/txn-sample.cs
- _includes/v1.1/app/basic-sample.cs
- _includes/v1.1/app/txn-sample.cs
- _includes/v2.0/app/basic-sample.cs
- _includes/v2.0/app/txn-sample.cs
- _includes/v2.1/app/basic-sample.cs
- _includes/v2.1/app/txn-sample.cs
- _includes/v2.2/app/basic-sample.cs
- _includes/v2.2/app/txn-sample.cs
Fixes #4139.
@rmloveland, ahead of your security work for c#, I'm pushing this little fix suggested by a user.
> Use correct C# method

- v2.1/cockroach-workload.md
- v2.2/cockroach-workload.md
> Add kv to cockroach workload docs

- _config_base.yml
- _data/releases.yml
- _includes/sidebar-releases.json
- releases/v2.1.3.md
- releases/v2.2.0-alpha.20181217.md
See https://github.com/cockroachdb/cockroach/issues/33029.
> Add release notes for v2.2.0-alpha.20181217

- _includes/v2.1/sql/settings/settings.md
> Update cluster settings doc

- v2.1/install-cockroachdb-linux.html
- v2.2/install-cockroachdb-linux.html
> Remove libncurses dependency for linux build from source

- v2.2/query-order.md
Follow-up to https://github.com/cockroachdb/docs/pull/4154.
> Apply query order change to 2.2 docs

- _includes/sidebar-data-v2.1.managed.json
- _includes/sidebar-data-v2.2.managed.json
- v2.1/managed-frequently-asked-questions.md
- v2.2/managed-frequently-asked-questions.md
> Add Managed FAQ

- v2.1/recommended-production-settings.md
- v2.2/recommended-production-settings.md
Summary of changes: Update the basic and cloud specific hardware recommendations.
Note: Will add the updates to the 2.1 version once the 2.2 is ready to go.
Closes #3936 (main tracking issue).
Closes #4112.
Closes #46.
Closes #3962.
Closes #3276.
> Update the Production Checklist

- v2.1/architecture/replication-layer.md
- v2.2/architecture/replication-layer.md
Completes doc of #2568 (not closing issue because still want to incorporate setting into demo)
@a-robinson @benesch PTAL for tech edits, will clean up copy once it looks good
> document leaseholder rebalancing in architecture docs

- v2.1/managed-sign-up-for-a-cluster.md
> Managed: Remove extra apostrophe in connection string

- v2.2/admin-ui-statements-page.md
> Added content for Logical plans

- _includes/sidebar-data-v2.1.json
- _includes/sidebar-data-v2.2.json
- v2.2/load-based-splitting.md
@nvanbenschoten Could I get you to do a tech edit of this page? And what is Ridwan's GitHub handle so I can grab his review, as well?
> Load-based splitting

- _config_base.yml
- _data/releases.yml
- _includes/v2.2/sql/aggregates.md
- _includes/v2.2/sql/functions.md
- _includes/v2.2/sql/operators.md
- _includes/v2.2/sql/settings/settings.md
- _includes/v2.2/sql/window_functions.md
- releases/v2.2.0-alpha.20181119.md
- releases/v2.2.0-alpha.20181217.md
- releases/v2.2.0-alpha.20190114.md
For https://github.com/cockroachdb/cockroach/issues/33565.
> [WIP] Add release notes for v2.2.0-alpha.20190114 release

- v2.1/frequently-asked-questions.md
- v2.2/frequently-asked-questions.md
We should leverage the new security overview docs that @Amruta-Ranade wrote.
> Link to security overview from product faq

- v2.0/sql-audit-logging.md
- v2.1/sql-audit-logging.md
- v2.2/sql-audit-logging.md
> Update 'SQL Audit Logging' to use `cockroach sql`

- v2.1/constraints.md
- v2.2/constraints.md
> Update info about removing unique constraints

- _includes/sidebar-data-v2.2.json
- v2.2/architecture/life-of-a-distributed-transaction.md
@nvanbenschoten Could I get you to take a look at this for technical accuracy? Still need to polish some of the writing, but any other copy edits are certainly welcome.
> Life of dist txn

- v2.0/array.md
- v2.1/array.md
- v2.2/array.md
> Improve ARRAY docs with a link to array functions

- v2.1/functions-and-operators.md
- v2.2/functions-and-operators.md
> Add link to examples in 'Aggregate Functions' area

- _data/releases.yml
> Add v2.1.4 to releases page

- v2.0/split-at.md
- v2.1/split-at.md
- v2.2/split-at.md
> Note that truncated tables must be pre-split again

- v2.2/admin-ui-statements-page.md
@celiala @piyush-singh Updated the Logical Plans section in the Statements Page doc. The cluster settings doc is auto-generated for every release. Will check if it's updated after the alpha.
> Added cluster setting info

- _includes/v2.1/prod-deployment/advertise-addr-join.md
- _includes/v2.2/prod-deployment/advertise-addr-join.md
> Fix table in systemd instructions

- v2.2/admin-ui-debug-pages.md
> Added content for debug page updates

- v2.1/upgrade-cockroach-version.md
> Require upgrade to 2.0.5 before upgrading to 2.1

- v2.1/insert.md
- v2.2/insert.md
> Clarify INSERT best practices and remove RETURNING NOTHING suggestion

- v2.2/follower-reads.md
> Follower reads

- _config_base.yml
- _data/releases.yml
- _includes/v2.2/sql/functions.md
- _includes/v2.2/sql/settings/settings.md
- releases/v2.2.0-alpha.20190211.md
Add release notes and update changed auto-generated functions and cluster settings docs.
> Release notes for v2.2.0-alpha.20190211

- v2.2/change-data-capture.md
Reworded CDC section on the new cluster settings.
Related to #4323.
> CDC: Update cluster settings description

- v2.1/architecture/transaction-layer.md
- v2.2/architecture/transaction-layer.md
> remove extraneous link to MVCC explanation from txn arch docs

- v2.1/null-handling.md
- v2.2/null-handling.md
The markdown table formatting was broken.
> Fix table in null-handling.md

- _includes/v2.0/sql/function-special-forms.md
- _includes/v2.1/sql/function-special-forms.md
- _includes/v2.2/sql/function-special-forms.md
> Remove redundant listing of current_timestamp()

- v2.2/architecture/transaction-layer.md
@nvanbenschoten Can I get you to take a quick look at this description of the latch manager? And can it be backported verbatim from this version into 2.1? (You can also ignore the bit where I moved around some of the content related to MVCC)
closes #4307
> describe latch manager in 2.2 architecture

- _includes/footer.html
* update copyright year to current year instead of hardcoded value
> update copyright year

- v19.1/cluster-setup-troubleshooting.md
- v19.1/common-errors.md
- v19.1/debug-and-error-logs.md
- v19.1/kubernetes-performance.md
- v19.1/query-behavior-troubleshooting.md
Addresses #3889 
I have added content to the troubleshooting guides based on my self-study as well as in-person discussions over the last few months. The docs need to be edited extensively, but wanted to get initial feedback to ensure I am on the right track.
Update: Ready for peer review
> Update the troubleshooting guides

- v19.1/enterprise-licensing.md
Add a features section toward the top that lists features with descriptions and links.
Closes #4339.
> Update Enterprise Licensing page

- v19.1/remove-nodes.md
- v2.1/remove-nodes.md
closes #3885
@awoods187 PTAL
@bdarnell The original issue had an ask from you for any additional input, so I'll just echo that here. If you don't have any feedback, A-OK.
> expand considerations for decommissioning nodes

- _config_base.yml
- _data/releases.yml
- releases/v19.1.0-beta.20190304.md
For https://github.com/cockroachdb/cockroach/issues/35216.
> Add release notes for v19.1.0-beta.20190304

- _includes/sidebar-data-v19.1.json
- _includes/v19.1/sql/diagrams/show_sequences.html
- v19.1/alter-sequence.md
- v19.1/create-sequence.md
- v19.1/drop-sequence.md
- v19.1/rename-sequence.md
- v19.1/show-sequences.md
- v19.1/sql-statements.md
To go along with https://github.com/cockroachdb/cockroach/pull/35215.
Would welcome suggestion as to how to generate the SVG diagram (the bnf file is created by the other PR).
> Document SHOW SEQUENCES.

- v19.1/common-errors.md
Follow-up to #4402.
Finishes off #4401.
> Add read within uncertainty interval to 19.1 docs

- v19.1/foreign-key.md
Fixes #4012.
- Update Foreign Keys page with:
- Revised introduction to add just a bit more context around what FKs
are and how they work.
- New section 'Composite foreign key matching' that describes how the
key matching algorithms work conceptually, in prose.
- New example 'Match composite foreign keys with `MATCH SIMPLE` and
`MATCH FULL`' that shows how the matching algorithms work by listing
examples.
> Document composite foreign key matching

- releases/v19.1.0-beta.20190304.md
If this part is autogenerated, the script may need to be fixed too.
> Fix docker link in release notes

- v19.1/detailed-sql-support.md
- v2.1/detailed-sql-support.md
> Update detailed SQL Standard Comparison page

- _config_base.yml
- _data/releases.yml
- _includes/sidebar-releases.json
- releases/v2.1.6.md
For https://github.com/cockroachdb/cockroach/issues/35365.
> Add v2.1.6 release notes

- v19.1/information-schema.md
- v2.1/information-schema.md
> information_schema.tables.version is experimental

- v19.1/default-value.md
- v2.1/default-value.md
> fix typos in default-value.md

- _includes/sidebar-data-v19.1.json
- v19.1/authentication.md
- v19.1/gssapi_authentication.md
Will iterate on the content/info arch after Monday's beta.
> Beta release draft for GSSAPI auth

- v19.1/show-jobs.md
- v2.1/show-jobs.md
As mentioned in the table above, the column is named `job_type`.
> Fix column name when selecting job by type.

- _includes/sidebar-data-v19.1.json
- v19.1/cockroach-commands.md
- v19.1/debug-merge-logs.md
- v19.1/debug-zip.md
- v2.2/debug-merge-logs.md
> Added doc for debug merge-logs command

- v19.1/admin-ui-statements-page.md
> Minor update to the Statements page

- v19.1/bytes.md
- v19.1/string.md
- v2.1/bytes.md
- v2.1/string.md
closes #609
@knz Can you take a quick look at this? Hope I didn't butcher your explanation!
> describe differences between bytes and strings

- _includes/v19.1/misc/gce-locations.md
- _includes/v2.1/misc/gce-locations.md
> Add coordinates for europe-west6 region

- v19.1/operational-faqs.md
> Update name of timeseries storage duration cluster setting

- v19.1/show-jobs.md
- Document `statement` column in `SHOW JOBS` response.
- `SHOW JOBS` only goes back 12 hours.
> Updates to SHOW JOBS

- v19.1/show-jobs.md
Fixes #4059.
The content was already correct. Just tweaked, and added a possible value to one response column.
> Tweak docs on SHOW JOBS output

- _includes/v19.1/orchestration/start-cockroachdb-secure.md
- _includes/v2.1/orchestration/start-cockroachdb-secure.md
> Link to secure k8s config that can use externally created certs

- v19.1/configure-replication-zones.md
- v2.1/configure-replication-zones.md
> Correct documented syntax for per-replica constraints

- _includes/v19.1/performance/overview.md
- _includes/v2.1/performance/overview.md
- v19.1/experimental-features.md
- v19.1/window-functions.md
- v2.1/experimental-features.md
- v2.1/window-functions.md
> Link to MovR repo where relevant

- _includes/v19.1/misc/session-vars.html
> Document results_buffer_size session variable

- v19.1/information-schema.md
> Add columns to information_schema.columns

- _includes/sidebar-data-v19.1.json
- v19.1/admin-ui-cdc-dashboard.md
- v19.1/admin-ui-overview.md
Closes #4384 
Note to self: Need to add screenshots
> Added content for CDC dashboard

- v19.1/explain.md
Fix `join` in example outputs and add docs and examples on new `OPT` options.
Fixes #4550.
Fixes #4551.
Fixes #4366.
> Update EXPLAIN output and OPT options

- v19.1/debug-zip.md
> Debug zip doc updates

- _includes/v19.1/misc/external-urls.md
> Updated S3 URL parameters

- _includes/sidebar-data-v19.1.json
- v19.1/upgrade-cockroach-version.md
This list in not exhaustive. Instead, it focuses on key
user-facing features that aren't enabled until finalization.
Fixes #4486.
> Document features that require upgrade finalization

- _includes/v19.1/misc/external-urls.md
> Support for cloud storage HTTP(S) proxy

- v19.1/cockroach-workload.md
- v2.1/cockroach-workload.md
> Clarify accepted values for cockroach workload --duration flag

- _config_base.yml
- _data/releases.yml
- releases/v19.1.0-rc.1.md
- scripts/issues-from-release-notes.py
> Add release notes for v19.1.0-rc.1

- v1.1/show-trace.md
- v19.1/explain-analyze.md
- v19.1/show-trace.md
- v2.0/show-trace.md
- v2.1/explain-analyze.md
- v2.1/show-trace.md
I think this is a typo, but English is my second language, so maybe not.
> Fix a typo and add a minor clarification

- v19.1/common-errors.md
- v19.1/known-limitations.md
- v19.1/recommended-production-settings.md
- v2.1/common-errors.md
- v2.1/known-limitations.md
- v2.1/recommended-production-settings.md
> 19.1 known limitations

- v19.1/backup.md
- v2.0/backup.md
- v2.1/backup.md
a couple people have thought we sent secrets over plaintext.
Lauren, feel free to pass review to others if I've chosen the wrong owner.
> Added clarification that we construct API calls from backup URLs

- v19.1/change-data-capture.md
- v19.1/monitoring-and-alerting.md
- Added a section to the Monitoring and Alerting page
- Added a bullet to CDC > Monitor a Changefeed section
Closes #3791.
> CDC monitoring / alerting

- _config_base.yml
- _data/releases.yml
- _includes/v19.1/sql/settings/settings.md
- releases/v19.1.0-rc.2.md
> Add release notes for v19.1.0-rc.2

- v19.1/cost-based-optimizer.md
> Remove beta from CBO; add join hint consideration

- _config_base.yml
- v19.1/training/backup-and-restore.md
- v19.1/training/geo-partitioning.md
- v2.1/training/backup-and-restore.md
- v2.1/training/geo-partitioning.md
> Update geo-partitioning training to be multi-region

- v19.1/intellij-idea.md
- v2.1/intellij-idea.md
> Updated pgerror code

- _includes/v19.1/sql/diagrams/show_jobs.html
- v19.1/admin-ui-jobs-page.md
- v19.1/cancel-job.md
- v19.1/pause-job.md
- v19.1/show-jobs.md
Closes #4585 
Still working on the SQL diagram but wanted to open the PR to get the content reviewed.
> Created doc for Show automatic jobs statement and updated relevant docs

- v1.0/install-cockroachdb.html
- v1.1/install-cockroachdb.html
- v19.1/install-cockroachdb-linux.html
- v19.1/install-cockroachdb-mac.html
- v19.1/install-cockroachdb-windows.html
- v2.0/install-cockroachdb.html
- v2.1/install-cockroachdb-linux.html
- v2.1/install-cockroachdb-mac.html
- v2.1/install-cockroachdb-windows.html
Google Tag Manager is currently instrumented to fire on specific on-page actions to help us understand when users download Cockroach; this is done through `data-eventcategory` and `data-eventaction` tags. However, the current analytics tool we use, Heap, doesn't support these tags and instead relies on being able to uniquely identify elements on the page via CSS.
This PR replicates most of the Google Analytics tags into CSS selectors, which will make these page elements uniquely selectable (i.e. usable) by Heap, which allows both the marketing and docs teams to have meaningful telemetry on customer interactions with the install pages through Heap.
These changes largely consist of moving either the `data-eventaction` (preferred) or `data-eventcategory` into the element's class, which will …
> replicate Google Tag Manager install hooks into CSS for Heap

- _includes/v19.1/sql/begin-transaction-as-of-system-time-example.md
- _includes/v19.1/sql/diagrams/begin_transaction.html
- _includes/v19.1/sql/diagrams/set_transaction.html
- _includes/v19.1/sql/set-transaction-as-of-system-time-example.md
- v19.1/as-of-system-time.md
- v19.1/begin-transaction.md
- v19.1/set-transaction.md
> Add support for AS OF SYSTEM TIME clause in BEGIN and SET TRANSACTION

- _config_base.yml
- _data/releases.yml
- releases/v19.1.0-rc.3.md
> Add release notes for v19.1.0-rc.3

- v19.1/cost-based-optimizer.md
> Mark CBO index prefs as enterprise

- _includes/v2.1/misc/external-urls.md
- v19.1/import.md
> Add S3 / GCE examples

- _includes/v19.1/known-limitations/cdc.md
- _includes/v2.1/known-limitations/cdc.md
> Clarify CDC known limitation

- v19.1/demo-geo-partitioning.md
> Wrap SQL commands to be completely visible

- _includes/v19.1/known-limitations/cdc.md
> Add cloud storage sink known limitation

- v19.1/create-user.md
- v2.1/create-user.md
> Fix typo in CREATE USER docs

- .bash_profile
- _includes/v1.0/app/basic-sample.php
- _includes/v1.1/app/basic-sample.php
- _includes/v19.1/app/basic-sample.php
- _includes/v19.1/app/insecure/basic-sample.php
- _includes/v2.0/app/basic-sample.php
- _includes/v2.0/app/insecure/basic-sample.php
- _includes/v2.1/app/basic-sample.php
- _includes/v2.1/app/insecure/basic-sample.php
Without this we'll cycle connections each query. See https://forum.cockroachlabs.com/t/throughput-not-increasing-when-doubling-nodes-3-to-6/2725/5
> Added PERSISTENT => true to php examples. 

- _includes/v19.1/orchestration/start-kubernetes.md
- _includes/v2.1/orchestration/start-kubernetes.md
> Specify reasonable instance type for k8s deployments

- _includes/v19.1/orchestration/kubernetes-remove-nodes-secure.md
- v19.1/orchestrate-a-local-cluster-with-kubernetes.md
- v19.1/training/orchestration-with-kubernetes.md
- v2.1/training/orchestration-with-kubernetes.md
- Add step for approving CSR for added node
- Change decommission command to use secure flag
Fixes #4803.
> Kubernetes training updates

- v19.1/bytes.md
- v19.1/dbeaver.md
- v2.1/bytes.md
- v2.1/dbeaver.md
> Make DBeaver edits

- v19.1/common-errors.md
- v2.1/common-errors.md
> can't to cannot

- v19.1/architecture/life-of-a-distributed-transaction.md
- v2.1/architecture/life-of-a-distributed-transaction.md
edited the life of a transaction page
> minor copy edits

- v19.1/training/geo-partitioning.md
- v2.1/training/geo-partitioning.md
> copy edited

- v19.1/create-index.md
- v2.1/create-index.md
changed two instances of don't to do in v19.1 and v2.1
closes #4779
> Minor edits: Create Index #4779

- v19.1/training/backup-and-restore.md
> changed Core to core 

- v19.1/contribute-to-cockroachdb.md
- v2.1/contribute-to-cockroachdb.md
> fix contractions

- _config_base.yml
- _data/releases.yml
- _includes/sidebar-releases.json
- releases/v19.1.1.md
> v19.1.1 release notes

- _includes/sidebar-data-v19.1.managed.json
@jseldess Based on our discussion last week, I took a stab at reorganizing the MSO docs' sidebar nav. Let me know what you think :)
> Reorganizing MSO sidebar nav

- releases/v19.1.0.md
- v19.1/index.md
- v2.1/index.md
Also reword cta on 19.1 release notes
> Remove 19.1 cta from docs home

- v19.1/insert.md
Also update respose formatting.
Fixes #4844.
> Fix create table for INSERT examples

- _includes/head.html
- _layouts/default.html
- _layouts/page.html
- v19.1/bit.md
- v19.1/debug-merge-logs.md
Add divs for top-of-page and toc CTAs
Remove front-matter fields
> Add convert flow JS to docs site

- _includes/sidebar-data-v19.1.json
- v19.1/licensing-faqs.md
To-Do: Update licensing terminology in the rest of the docs
> Added Licensing FAQs

- _config_base.yml
- _data/releases.yml
- _includes/sidebar-releases.json
- releases/v19.1.2.md
> Add v19.1.2 release notes

- v19.1/migrate-from-mysql.md
- v19.1/migrate-from-postgres.md
- v19.2/migrate-from-mysql.md
- v19.2/migrate-from-postgres.md
> Remove Beta tags from Migrate from Postgres / MySQL

- v19.1/online-schema-changes.md
- v19.2/online-schema-changes.md
> Add note about online schema changes

- releases/v1.0-rc.1.md
- v19.1/enable-node-map.md
- v19.2/enable-node-map.md
- v2.0/enable-node-map.md
- v2.1/enable-node-map.md
> Fix broken link

- v19.1/cost-based-optimizer.md
- v19.2/cost-based-optimizer.md
> Describe schema caching vs. locality-aware indexes

- v19.1/authentication.md
- v19.1/create-security-certificates.md
- v19.2/authentication.md
- v19.2/create-security-certificates.md
> Added content for wildcard hostnames

- v19.1/training/locality-and-replication-zones.md
- v19.1/training/planned-maintenance.md
- v19.1/training/under-replication-troubleshooting.md
- v19.2/training/locality-and-replication-zones.md
- v19.2/training/planned-maintenance.md
- v19.2/training/under-replication-troubleshooting.md
- v2.1/training/planned-maintenance.md
> Fix various typos in some training docs

- v19.2/import-into.md
- v19.2/import.md
- v19.2/sql-statements.md
> Incremental import

- _config_base.yml
- _data/releases.yml
- releases/v19.2.0-alpha.20190701.md
> Add release notes for 19.2.0-alpha.20190701

- v19.1/follower-reads.md
- v19.2/follower-reads.md
> Fix follower reads cluster setting default

- _includes/v19.2/sql/settings/settings.md
> Update 19.2 cluster settings

- v19.2/install-cockroachdb-linux.html
- v19.2/install-cockroachdb-mac.html
> Bump required Go version for building from source

- _includes/v19.1/misc/external-urls.md
- _includes/v19.2/misc/external-urls.md
> Add warning that nodelocal doesn't work in multi-node clusters

- v19.1/common-errors.md
- v19.2/common-errors.md
- v2.1/common-errors.md
Fixes #4331 (along with #4402 that already did most of the work).
> Add `ReadWithinUncertainty...` to Common Errors

- v19.1/known-limitations.md
- v19.2/known-limitations.md
Requests to a restarted node in need of snapshots can hang.
Fixes #4957.
> Known limitation: Requests to a restarted node in need of snapshots can hang

- _config_base.yml
- _data/releases.yml
- _includes/sidebar-releases.json
- releases/v19.1.3.md
- releases/v2.1.8.md
> Release notes for v2.1.8 and v19.1.3

- v1.0/interleave-in-parent.md
- v1.1/interleave-in-parent.md
- v19.1/interleave-in-parent.md
- v19.2/interleave-in-parent.md
- v2.0/interleave-in-parent.md
- v2.1/interleave-in-parent.md
> Fix kv storage examples on all interleaving pages

- v19.2/experimental-features.md
... along with some context about what the feature is, how it works (by
linking to George's blog post), and a list of current limitations.
Fixes #4953.
> Add vectorization to experimental features list

- _includes/v19.2/known-limitations/cdc.md
- v19.1/change-data-capture.md
- v19.2/change-data-capture.md
- v19.2/create-changefeed.md
> Add warning about CDC cloud sink bug

- v19.2/create-database.md
- v2.1/create-database.md
> fixed nits on create database page

- _includes/v19.1/app/insecure/BasicExample.java
- v19.1/build-a-java-app-with-cockroachdb.md
As well as a small tweak to the docs to link to the newer client-side
transaction retry recommendations.
Addresses #5035.
> Update Java JDBC example to use app retry loop

- _includes/footer.html
- _includes/topnav.html
Updates to match marketing site. 
Fixes #5057.
> Topnav and footer updates

- v19.2/change-data-capture.md
- v2.1/change-data-capture.md
Changed the port for zookeeper from 8081 to 2181
> Apply https://github.com/cockroachdb/docs/pull/5086 to 2.1 and 19.2 docs

- v19.2/use-the-built-in-sql-client.md
> sql client reference: Updates welcome message and add docs for new shell metacommands

- v19.1/architecture/replication-layer.md
Just fixed a broken link on this page...
> Fixed broken link

- v19.2/architecture/storage-layer.md
> Small typo fix

- v19.1/learn-cockroachdb-sql.md
> Removed hedge note from Learn CockroachDB SQL page

- v19.1/architecture/replication-layer.md
- v19.1/architecture/storage-layer.md
- v19.1/training/locality-and-replication-zones.md
- v19.2/architecture/replication-layer.md
- v19.2/architecture/storage-layer.md
- v19.2/training/locality-and-replication-zones.md
This includes the changes made in #5128 and #5129, but to all versions.
> small corrections applied to all versions

- v19.2/debug-ballast.md
> Document default ballast file size

- v19.1/common-errors.md
Providing copy feature for commands
> Providing copy feature for commands

- v19.1/build-a-c++-app-with-cockroachdb.md
Providing Copy feature for the commands
> Providing Copy feature for the commands

- v19.1/sql-faqs.md
Copy feature to copy SQL/Java scripts
> Copy feature to copy SQL/Java scripts

- v19.1/sql-faqs.md
Copy feature for copying queries on click of copy link
> Copy feature for copying queries

- v19.1/sql-faqs.md
Copy feature for copying the queries
> Copy feature for copying the queries

- _includes/v19.1/faq/auto-generate-unique-ids.html
- v19.1/performance-best-practices-overview.md
- v19.1/query-behavior-troubleshooting.md
- v2.1/performance-best-practices-overview.md
- v2.1/query-behavior-troubleshooting.md
* Added a new approach describing how to mitigate the issue with good
schema design
* Expanded our description of how these can be caused by monotonically
increasing index keys or table Primary Keys.
> Expanded content around hot ranges.

- _config_base.yml
- _data/releases.yml
- _includes/sidebar-releases.json
- releases/v19.1.4.md
> Update docs site for v19.1.4 release

- _data/releases.yml
- releases/v19.1.4.md
> Correct date of v19.1.4 release

- _includes/v19.2/sql/movr-start.md
- _includes/v19.2/sql/movr-statements.md
- Leverage previous page for starting cluster.
- Add secure/insecure toggle so as to provide complete copy/paste commands
> Refactor movr start instructions

- v19.1/cockroach-workload.md
> Removed pprof flag from 19.1 cockroach workload docs

- _includes/v19.2/sql/movr-start-nodes.md
- _includes/v19.2/sql/movr-statements-nodes.md
- v19.2/cockroach-demo.md
> --nodes and --locality flags and MovR examples added to cockroach demo page

- _includes/sidebar-data-v19.2.json
- _includes/v19.2/sql/diagrams/show_locality.html
- _includes/v19.2/sql/movr-statements-nodes.md
- v19.2/show-locality.md
- v19.2/sql-statements.md
- New SHOW LOCALITY page
- New SHOW LOCALITY entry in SQL Statements Overview
- New SHOW LOCALITY diagram
> SHOW LOCALITY statement

- _includes/v19.2/sql/diagrams/comment.html
- _includes/v19.2/sql/diagrams/show_columns.html
- _includes/v19.2/sql/diagrams/show_databases.html
- v19.2/comment-on.md
- v19.2/show-columns.md
- v19.2/show-databases.md
- v19.2/show-tables.md
- Added diagrams and examples for SHOW COLUMNS WITH COMMENTS and SHOW DATABASES WITH COMMENTS
- Updated SHOW TABLES and COMMENT ON pages to use MovR
Fixes #4892 and #4893
> SHOW COLUMNS WITH COMMENTS and SHOW DATABASES WITH COMMENTS

- v19.1/migrate-from-oracle.md
> Remove New in 19.2 flag

- v19.1/create-changefeed.md
> Edit link to Authorization from CREATE CHANGEFEED

- v19.2/show-partitions.md
> Added note about inherited constraints

- v19.2/cockroach-workload.md
> Mark --init flag as deprecated for workload run

- v19.2/licensing-faqs.md
> Licensing update 

- _includes/topnav.html
> Update topnav to link to pricing page

- v19.2/learn-cockroachdb-sql.md
- v19.2/show-columns.md
- v19.2/show-databases.md
- v19.2/show-tables.md
- v19.2/show-users.md
- v19.2/use-the-built-in-sql-client.md
> Expand docs on new SQL shell commands

- v19.1/install-cockroachdb-windows.html
- v19.2/install-cockroachdb-windows.html
Problem identified in https://github.com/cockroachdb/docs/pull/5388.
> Add missing copy-to-clipboard on windows install page

- _includes/v19.2/app/gorm-sample.go
- _includes/v19.2/app/insecure/gorm-sample.go
- v19.2/build-a-go-app-with-cockroachdb-gorm.md
This work was done for 19.1 in #5084 and #5163.  We forgot to also port
it to 19.2.  Hence this commit.
> Update 19.2 Go/GORM code to use app retry loop

- _includes/v19.2/app/BasicExample.java
- _includes/v19.2/app/insecure/BasicExample.java
> Delete Java comment re: force_retry() needing root

- v19.2/sql-tuning-with-explain.md
> Added info on span and index to SQL tuning with EXPLAIN

- v19.2/restore.md
> Add skip_missing_views option to RESTORE

- _includes/v19.2/sql/diagrams/show_jobs.html
- v19.2/show-jobs.md
Add docs for SHOW JOBS WHEN COMPLETED
Closes #5291, #5249.
[ON HOLD until 19.2.0-beta20190909 goes out]
> Add SHOW JOBS WHEN COMPLETED

- v19.1/cockroach-demo.md
- v19.1/cockroach-workload.md
- v19.1/create-and-manage-users.md
- v19.1/create-security-certificates.md
- v19.1/debug-ballast.md
- v19.1/debug-zip.md
- v19.1/sql-dump.md
- v19.1/start-a-node.md
- v19.1/stop-a-node.md
- v19.1/use-the-built-in-sql-client.md
- v19.1/use-the-query-formatter.md
- v19.1/view-node-details.md
- v19.2/cockroach-demo.md
- v19.2/cockroach-workload.md
- v19.2/create-security-certificates.md
- v19.2/debug-ballast.md
- v19.2/debug-zip.md
- v19.2/generate-cockroachdb-resources.md
- v19.2/sql-dump.md
- v19.2/stop-a-node.md
- v19.2/use-the-built-in-sql-client.md
- v19.2/use-the-query-formatter.md
- v19.2/view-node-details.md
Necessary following https://github.com/cockroachdb/docs/pull/5386.
> Reformat cli command synopses

- v19.2/performance-best-practices-overview.md
> Truncate sql

- _includes/v19.2/sql/diagrams/alter_column.html
- v19.2/add-constraint.md
- v19.2/alter-column.md
- v19.2/alter-table.md
- v19.2/not-null.md
- v19.2/sql-statements.md
> ALTER TABLE ALTER COLUMN SET NOT NULL

- v19.1/frequently-asked-questions.md
> Remove 19.1 beta warning for migrate from postgres

- _includes/v19.1/topology-patterns/fundamentals.md
- _includes/v19.2/topology-patterns/fundamentals.md
- v19.1/demo-geo-partitioning.md
- v19.1/topology-duplicate-indexes.md
- v19.1/topology-follow-the-workload.md
- v19.1/topology-follower-reads.md
- v19.1/topology-geo-partitioned-leaseholders.md
- v19.1/topology-geo-partitioned-replicas.md
- v19.2/demo-geo-partitioning.md
- v19.2/topology-duplicate-indexes.md
- v19.2/topology-follow-the-workload.md
- v19.2/topology-follower-reads.md
- v19.2/topology-geo-partitioned-leaseholders.md
- v19.2/topology-geo-partitioned-replicas.md
> Reference case studies from topology docs

- v19.2/import.md
> IMPORT Performance Improvements

- _redirects
> Tell Netlify to redirect to our custom 404 page

- _redirects
> Revert "Tell Netlify to redirect to our custom 404 page"

- _data/releases.yml
- _includes/sidebar-releases.json
- releases/v19.1.5.md
> v19.1.5 release notes

- v1.0/start-a-local-cluster-in-docker.md
- v1.1/start-a-local-cluster-in-docker.md
- v19.1/start-a-local-cluster-in-docker.md
- v19.2/start-a-local-cluster-in-docker-windows.md
- v2.0/start-a-local-cluster-in-docker.md
- v2.1/start-a-local-cluster-in-docker.md
> Fix command to remove data dir on Windows

- _includes/v19.2/sql/functions.md
- _includes/v19.2/sql/settings/settings.md
> Update 19.2 auto-gen setting and function docs

- _includes/topnav.html
- Add Events to Resources menu.
- Revert Get CockroachDB button to get-cockroachdb page.
Fixes #5509.
> Update topnav to match marketing site

- v19.1/recommended-production-settings.md
- v19.2/recommended-production-settings.md
- v2.1/recommended-production-settings.md
> Remove syntax highlighting from prod checklist example

- v19.1/create-changefeed.md
- v19.2/create-changefeed.md
- v2.1/create-changefeed.md
> Changefeed cursors must be in quotes

- v19.1/architecture/storage-layer.md
- v19.2/architecture/storage-layer.md
> There are 2 RocksDB instances per store, not 3

- CONTRIBUTING.md
> minor nit in CONTRIBUTING

- v19.2/use-the-built-in-sql-client.md
Fixes #5520. 
Added `--watch` flag description and example.
> cockroach sql --watch flag

- _includes/v19.2/sql/diagrams/explain_analyze.html
- v19.2/explain-analyze.md
Fixes #5518.
- Added "Aliases" section to `EXPLAIN ANALYZE` doc page
- Updated `EXPLAIN ANALYZE` diagram
> EXPLAIN ANALYSE

- _includes/v19.2/sql/diagrams/stmt_block.html
- _includes/v19.2/sql/function-special-forms.md
- v19.2/collate.md
Fixes #5285.
- Entry for COLLATION FOR added to functions and operators doc page
- New example for pg_collation_for and COLLATION FOR added to COLLATE page
> pg_collation_for and COLLATION FOR

- v19.1/architecture/replication-layer.md
- v19.2/architecture/replication-layer.md
> Update docs on epoch- vs. expiration-based leases

- _config_base.yml
- _data/releases.yml
- releases/v19.2.0-beta.20191014.md
Fixes #5588.
Need to add more doc updates.
> Add v19.2.0-beta.20191014 release notes

- _includes/sidebar-data-v19.2.json
- _includes/v19.2/sql/diagrams/show_range_for_row.html
- _includes/v19.2/sql/movr-statements-geo-partitioned-replicas.md
- v19.2/experimental-features.md
- v19.2/show-range-for-row.md
- v19.2/show-ranges.md
Fixes #5534.
- New diagram for SHOW RANGE FOR ROW
- New doc page for SHOW RANGE FOR ROW
- ToC and SHOW RANGES references to SHOW RANGE FOR ROW page
> SHOW RANGE FOR ROW

- v19.2/set-vars.md
> Added note about utc as alias for UTC

- _includes/sidebar-data-v19.2.json
- v19.1/upgrade-cockroach-version.md
- v19.2/upgrade-cockroach-version.md
> Clarify upgrade path

- _includes/head.html
> Remove cockroachcloud canonical reference to cockroachdb docs

- _includes/footer.html
- _includes/topnav.html
- v19.1/index.md
- v19.2/index.md
- v2.1/index.md
> Remove references to older training pages

- _includes/v19.1/known-limitations/dump-table-with-no-columns.md
- _includes/v19.2/known-limitations/dump-table-with-no-columns.md
- v19.1/known-limitations.md
- v19.1/sql-dump.md
- v19.2/known-limitations.md
- v19.2/sql-dump.md
> Document cockroach dump limitation

- _includes/v19.1/orchestration/kubernetes-remove-nodes-secure.md
- _includes/v19.1/orchestration/monitor-cluster.md
- _includes/v19.2/orchestration/kubernetes-remove-nodes-secure.md
- _includes/v19.2/orchestration/monitor-cluster.md
- v19.1/orchestrate-a-local-cluster-with-kubernetes.md
- v19.2/orchestrate-a-local-cluster-with-kubernetes.md
Corrected some things I encountered when testing.
> corrections to k8s deployment docs

- v19.2/cockroach-workload.md
> Rename --initial-rows to --initial-count

- v19.1/experimental-features.md
- v19.2/experimental-features.md
> Clarify fingerprint experimental feature

- _includes/sidebar-data-v19.2.json
- _includes/v19.2/misc/session-vars.html
- _includes/v19.2/sql/diagrams/explain.html
- _includes/v19.2/sql/disk-spilling-ops.md
- v19.2/architecture/sql-layer.md
- v19.2/experimental-features.md
- v19.2/explain.md
- v19.2/set-vars.md
- v19.2/show-vars.md
- v19.2/vectorized-execution.md
Fixes #4790.
Fixes #5141.
Fixes #5287.
Fixes #5288.
Fixes #5513.
This PR includes the following initial changes:
- Vectorized Query Execution page added
- Vectorized execution section removed from experimental features
- Vectorized execution section added to SQL Layer page
> Vectorized Execution

- v19.2/information-schema.md
- v19.2/show-tables.md
> Document comments and doc links for virtual tables

- _includes/v19.2/sql/diagrams/stmt_block.html
- _includes/v19.2/sql/functions.md
- _includes/v19.2/sql/settings/settings.md
- Full sql grammar
- Functions
- Settings
> Update v19.2 auto-gen docs

- v19.2/vectorized-execution.md
> Vectorized typo

- _config_base.yml
- _data/releases.yml
- releases/v19.2.0-rc.2.md
> Add release notes for v19.2.0-rc.2

- v19.2/create-table-as.md
- v19.2/drop-table.md
Small PR, just updated some output for formatting while I was working on a separate issue.
> Small formatting fixes (mainly updated output)

- _includes/v19.2/sql/diagrams/opt_frame_clause.html
- _includes/v19.2/sql/diagrams/window_definition.html
- v19.2/select-clause.md
- v19.2/window-functions.md
Fixes #5295.
Informs #4655.
- Added window definition section
- Added window_definition diagram and parameters
- Added extended opt_frame_clause diagram and parameters
- Updated all output for Window Functions doc page
- Updated description of window functions to include OVER and WINDOW clause description
@mjibson I just saw #4655, but I agree that we need to update this page ASAP.
> Window frame docs

- _includes/v19.1/sql/diagrams/create_index.html
- _includes/v19.2/sql/diagrams/create_index.html
- v19.1/create-index.md
- v19.2/create-index.md
Also fill in description for opt_partition_by.
Fixes #5707.
> Document CREATE INDEX ... USING

- _includes/v19.2/misc/sorting-delete-output.md
- v19.2/delete.md
- v19.2/insert.md
- v19.2/query-order.md
- v19.2/update.md
- v19.2/upsert.md
> Better explain ordering in mutations

- _config_base.yml
- _data/releases.yml
- releases/v19.2.0-rc.3.md
- v19.2/install-cockroachdb-linux.html
- v19.2/install-cockroachdb-mac.html
> Add v19.2.0-rc.3 release notes

- v19.2/backup-and-restore.md
- v19.2/backup.md
- v19.2/restore.md
> Document locality-aware backups

- v19.2/backup-and-restore.md
- v19.2/upgrade-cockroach-version.md
> Document features that required 19.2 upgrade finalization

- _includes/v19.2/performance/partition-by-city.md
- _includes/v19.2/sql/diagrams/alter_zone_partition.html
- _includes/v19.2/sql/diagrams/alter_zone_table.html
- _includes/v19.2/zone-configs/create-a-replication-zone-for-a-database.md
- _includes/v19.2/zone-configs/create-a-replication-zone-for-a-secondary-index.md
- _includes/v19.2/zone-configs/create-a-replication-zone-for-a-system-range.md
- _includes/v19.2/zone-configs/create-a-replication-zone-for-a-table-partition.md
- _includes/v19.2/zone-configs/create-a-replication-zone-for-a-table.md
- v19.2/configure-replication-zones.md
- v19.2/configure-zone.md
- v19.2/create-table.md
- v19.2/recommended-production-settings.md
- v19.2/show-zone-configurations.md
- v19.2/training/geo-partitioning.md
> Update docs on creating and showing zone configs for partitions

- v19.2/detailed-sql-support.md
- v19.2/sql-faqs.md
- v19.2/subqueries.md
> Remove `LATERAL` in `FROM` limitation from docs

- v19.2/delete.md
I think Michael Brown was a bit inappropriate, particularly given that we were deleting him.
> delete: change fictional name

- _config_base.yml
- _data/releases.yml
- releases/v19.2.0-rc.4.md
> Add v19.2.0-rc.4 release notes

- v19.2/cockroachcloud-cluster-management.md
> CC: Added "delete cluster" section

- _includes/sidebar-data-v19.2.cockroachcloud.json
- netlify/serve
- v19.2/cockroachcloud-troubleshooting-page.md
> Added CC troubleshooting page

- netlify/serve
- v19.1/cockroachcloud-connect-to-your-cluster.md
- v19.1/deploy-a-python-to-do-app-with-flask-kubernetes-and-cockroachcloud.md
- v19.2/cockroachcloud-connect-to-your-cluster.md
- v19.2/cockroachcloud-frequently-asked-questions.md
- v19.2/deploy-a-python-to-do-app-with-flask-kubernetes-and-cockroachcloud.md
> CC assorted updates (FAQs, IP whitelist)

- v19.2/cockroachcloud-frequently-asked-questions.md
> Fixed formatting error

- v19.2/begin-transaction.md
- v19.2/follower-reads.md
- v19.2/topology-follower-reads.md
... to make the feature easier to access from drivers and ORMs.
Fixes #5613.
> Update follower reads docs to use SET TRANSACTION

- v19.1/experimental-audit.md
- v19.2/experimental-audit.md
> Update audit log docs with auto-retry counter

- v19.1/cost-based-optimizer.md
- v19.2/cost-based-optimizer.md
Fixes #4605.
Should be followed up ASAP with #5800.
> Clarify requirements for CBO using "nearest" index

- v19.2/cost-based-optimizer.md
> Note that stats are collected on table creation

- v1.0/data-types.md
- v1.0/timestamp.md
- v1.1/data-types.md
- v1.1/timestamp.md
- v19.1/data-types.md
- v19.1/timestamp.md
- v19.2/data-types.md
- v19.2/timestamp.md
- v2.0/data-types.md
- v2.0/timestamp.md
- v2.1/data-types.md
- v2.1/timestamp.md
Follow up to https://github.com/cockroachdb/docs/pull/5762.
> TIMESTAMP / TIMESTAMPTZ clarifications

- _includes/v19.2/misc/external-urls.md
> Support implicit credentials for S3

- _includes/v19.2/sql/querying-partitions.md
- v19.2/partition-by.md
- v19.2/partitioning.md
Fixes #4796. 
- Added "Querying partitions" include file.
- Included this file as a section in [Define Table Partitions](https://www.cockroachlabs.com/docs/dev/partitioning.html) and [PARTITION BY](https://www.cockroachlabs.com/docs/dev/partition-by.html) pages.
Still a WIP - please provide feedback.
> Querying partitioned data

- v19.2/performance-benchmarking-with-tpc-c-100k-warehouses.md
- v19.2/performance-benchmarking-with-tpc-c-10k-warehouses.md
- v19.2/performance-benchmarking-with-tpc-c-1k-warehouses.md
Thanks for finding this, @Amruta-Ranade!
> Link to AWS instance creation docs, not GCP

- v19.2/cockroachcloud-cluster-management.md
- v19.2/cockroachcloud-frequently-asked-questions.md
> CC: Added backup restore section

- _includes/sidebar-data-v19.2.cockroachcloud.json
- netlify/serve
- v19.2/cockroachcloud-console-access-management.md
- v19.2/cockroachcloud-create-your-cluster.md
Closes #4944 #5643 #5474 #5737
> CC create cluster workflow

- v19.2/cockroachcloud-connect-to-your-cluster.md
- v19.2/cockroachcloud-console-access-management.md
- v19.2/cockroachcloud-sign-up-for-a-cluster.md
Disclaimer: This is a placeholder draft for the create account workflow until billing and organization structure is implemented.
Update: Added info about orgs. Handling billing in the "create cluster workflow" PR.
> CC: create account workflow

- _includes/sidebar-data-v19.2.cockroachcloud.json
- v19.2/cockroachcloud-production-checklist.md
> CC production checklist

- _config_base.yml
- _includes/version-nav.html
> Correct reference to jekyll-sitemap plugin in base config

- v19.2/known-limitations.md
Fixes: https://github.com/cockroachdb/docs/issues/5853
> Removed resolved issue

- v19.2/import.md
> Add DELIMITED DATA format to IMPORT

- v19.2/import.md
- v20.1/import.md
Also edited the markdown layout for the table.
Closes #5701
> Add nullif, skip to DELIMITED DATA options

- v19.1/recommended-production-settings.md
- v19.2/recommended-production-settings.md
- v20.1/recommended-production-settings.md
> Document the importance of an appropriate idle connection limit

- v19.2/cockroachcloud-frequently-asked-questions.md
> CC: Added FAQ for load balancers

- _includes/sidebar-data-v19.2.cockroachcloud.json
> CC: Reorganizing sidebar nav

- v19.1/backup-and-restore.md
- v19.1/restore.md
- v19.2/backup-and-restore.md
- v19.2/restore.md
- v20.1/backup-and-restore.md
- v20.1/restore.md
> Clarify backups that must be specified for incremental backups and restores

- v19.2/install-cockroachdb-mac.html
> Clarify version upgrade via homebrew

- _includes/v19.2/prod-deployment/insecure-requirements.md
- _includes/v19.2/prod-deployment/secure-requirements.md
- _includes/v19.2/prod-deployment/topology-recommendations.md
- _includes/v20.1/prod-deployment/insecure-requirements.md
- _includes/v20.1/prod-deployment/secure-requirements.md
- _includes/v20.1/prod-deployment/topology-recommendations.md
- v19.2/recommended-production-settings.md
- v20.1/recommended-production-settings.md
> add verbiage against using 2 nodes

- _includes/v19.1/known-limitations/schema-change-ddl-inside-multi-statement-transactions.md
- _includes/v19.1/known-limitations/schema-changes-within-transactions.md
- _includes/v19.2/known-limitations/schema-change-ddl-inside-multi-statement-transactions.md
- _includes/v19.2/known-limitations/schema-changes-within-transactions.md
- _includes/v20.1/known-limitations/schema-change-ddl-inside-multi-statement-transactions.md
- _includes/v20.1/known-limitations/schema-changes-within-transactions.md
- v19.1/known-limitations.md
- v19.1/online-schema-changes.md
- v19.2/known-limitations.md
- v19.2/online-schema-changes.md
- v20.1/known-limitations.md
- v20.1/online-schema-changes.md
> Document schema change DDL "partial commit" error

- scripts/issues-from-roadmap.py
Next step is to refactor the script to keep the github issues
in sync with airtable, ideally on a schedule.
Fixes #5930.
> Script to generate docs issues from 20.1 airtable epics

- scripts/issues-from-release-notes.py
- scripts/issues-from-roadmap.py
- Get 5 airtable records at a time
- More efficient querystring parameters
> Minor tweaks to roadmap script

- _includes/v19.2/cdc/print-key.md
- _includes/v20.1/cdc/print-key.md
- v19.1/change-data-capture.md
- v19.2/change-data-capture.md
- v20.1/change-data-capture.md
> Add note about property print.key flag

- v19.1/backup.md
- v19.2/backup.md
- v20.1/backup.md
> Remove out-dated incremental backup limitation

- _includes/v19.1/known-limitations/adding-stores-to-node.md
- _includes/v19.2/known-limitations/adding-stores-to-node.md
- _includes/v2.1/known-limitations/adding-stores-to-node.md
- _includes/v20.1/known-limitations/adding-stores-to-node.md
- v19.1/known-limitations.md
- v19.1/start-a-node.md
- v19.2/known-limitations.md
- v19.2/start-a-node.md
- v2.1/known-limitations.md
- v2.1/start-a-node.md
- v20.1/known-limitations.md
- v20.1/start-a-node.md
> Document limitation with adding stores to nodes

- v19.2/vectorized-execution.md
- v20.1/vectorized-execution.md
> vectorized execution now supports TIMESTAMP and UUID data types

- v19.1/build-a-rust-app-with-cockroachdb.md
- v19.1/jsonb.sublime-workspace
- v2.1/build-a-rust-app-with-cockroachdb.md
references https://github.com/cockroachdb/docs/issues/6125
> updated rust docs to reflect correct startup flags in 19.1 and 2.1

- v19.2/show-locality.md
references https://github.com/cockroachdb/docs/issues/6143
> updated show locality to have an example for pre 19.2

- _includes/v19.1/known-limitations/schema-changes-within-transactions.md
- _includes/v19.2/known-limitations/schema-changes-within-transactions.md
- _includes/v2.1/misc/schema-changes-within-transactions.md
- _includes/v20.1/known-limitations/schema-changes-within-transactions.md
- v1.0/known-limitations.md
- v1.1/known-limitations.md
- v2.0/known-limitations.md
> Clarify known limitation on schema changes within transactions

- v1.0/indexes.md
- v1.1/indexes.md
- v19.1/indexes.md
- v19.2/indexes.md
- v2.0/indexes.md
- v2.1/indexes.md
- v20.1/indexes.md
I clarified the description and example of stored columns on indexes.
Fixes #3912
> Improve STORING description

- v19.2/vectorized-execution.md
- v20.1/vectorized-execution.md
> Vectorized support for IS NULL and IS NOT NULL

- _includes/v19.2/sql/aggregates.md
- _includes/v19.2/sql/functions.md
- _includes/v19.2/sql/settings/settings.md
> Correct 19.2 auto-gen docs

- _includes/sidebar-data-v19.2.json
- _includes/sidebar-data-v20.1.json
- v19.1/frequently-asked-questions.md
- v19.1/index.md
- v19.2/frequently-asked-questions.md
- v19.2/index.md
- v20.1/frequently-asked-questions.md
- v20.1/index.md
> Better expose licensing FAQs

- v1.0/upgrade-cockroach-version.md
- v1.1/upgrade-cockroach-version.md
- v19.1/upgrade-cockroach-version.md
- v19.2/upgrade-cockroach-version.md
- v2.0/upgrade-cockroach-version.md
- v2.1/upgrade-cockroach-version.md
- v20.1/upgrade-cockroach-version.md
> Fix code block formatting issues

- _includes/v20.1/sql/aggregates.md
- _includes/v20.1/sql/functions.md
- _includes/v20.1/sql/operators.md
- _includes/v20.1/sql/settings/settings.md
- _includes/v20.1/sql/window_functions.md
Fixes #6196.
Fixes #6192.
Fixes #6190.
> Update 20.1 auto-gen func and setting docs

- _includes/v19.2/orchestration/start-cockroachdb-helm-insecure.md
- _includes/v19.2/orchestration/start-cockroachdb-helm-secure.md
- _includes/v20.1/orchestration/start-cockroachdb-helm-insecure.md
- _includes/v20.1/orchestration/start-cockroachdb-helm-secure.md
Fixes #6091 
Addresses the Helm portion of #5922
> Update Helm install steps

- v19.2/training/cluster-startup-and-scaling.md
> Correct Step 3 --store grammar error.

- v19.1/training/cluster-startup-and-scaling.md
- v19.1/training/fault-tolerance-and-automated-repair.md
- v19.2/training/cluster-startup-and-scaling.md
- v19.2/training/fault-tolerance-and-automated-repair.md
- v19.2/training/locality-and-replication-zones.md
- v2.1/training/cluster-startup-and-scaling.md
- v2.1/training/fault-tolerance-and-automated-repair.md
- v20.1/training/cluster-startup-and-scaling.md
- v20.1/training/fault-tolerance-and-automated-repair.md
reviewed with Rich
fixes #6231
> issue 6231

- v19.2/import.md
- v20.1/import.md
> Enable saving bad csv rows to a side file

- scripts/issues-from-roadmap.py
Copy of https://github.com/cockroachdb/docs/pull/6156 with with some small fixes so we can get this merged. @otan, we can iterate on this more in follow-up PRs, if necessary.
> scripts: add ability to update issues, add Github Tracking Issue

- v19.2/create-user.md
- v20.1/create-user.md
> Allow usernames to start with numbers

- v19.2/gssapi_authentication.md
- v20.1/gssapi_authentication.md
This format is all wrong but it has the additional info required to get started
> Kerberos / GSSAPI docs initial update based on customer engagement

- _config_base.yml
- _data/releases.yml
- releases/v20.1.0-alpha.20200113.md
> Add v20.1.0-alpha20200113 release notes

- _includes/v19.2/orchestration/kubernetes-limitations.md
- _includes/v19.2/orchestration/kubernetes-prometheus-alertmanager.md
- _includes/v19.2/orchestration/kubernetes-remove-nodes-insecure.md
- _includes/v19.2/orchestration/kubernetes-remove-nodes-secure.md
- _includes/v19.2/orchestration/kubernetes-scale-cluster.md
- _includes/v19.2/orchestration/kubernetes-upgrade-cluster.md
- _includes/v19.2/orchestration/start-cockroachdb-helm-insecure.md
- _includes/v19.2/orchestration/start-cockroachdb-helm-secure.md
- _includes/v19.2/orchestration/start-cockroachdb-local-helm-insecure.md
- _includes/v19.2/orchestration/start-cockroachdb-local-helm-secure.md
- _includes/v20.1/orchestration/kubernetes-limitations.md
- _includes/v20.1/orchestration/kubernetes-prometheus-alertmanager.md
- _includes/v20.1/orchestration/kubernetes-remove-nodes-insecure.md
- _includes/v20.1/orchestration/kubernetes-remove-nodes-secure.md
- _includes/v20.1/orchestration/kubernetes-scale-cluster.md
- _includes/v20.1/orchestration/kubernetes-upgrade-cluster.md
- _includes/v20.1/orchestration/start-cockroachdb-helm-insecure.md
- _includes/v20.1/orchestration/start-cockroachdb-helm-secure.md
- _includes/v20.1/orchestration/start-cockroachdb-local-helm-insecure.md
- _includes/v20.1/orchestration/start-cockroachdb-local-helm-secure.md
- v19.2/orchestrate-a-local-cluster-with-kubernetes-insecure.md
- v19.2/orchestrate-a-local-cluster-with-kubernetes.md
- v19.2/orchestrate-cockroachdb-with-kubernetes-insecure.md
- v19.2/orchestrate-cockroachdb-with-kubernetes.md
- v20.1/orchestrate-a-local-cluster-with-kubernetes-insecure.md
- v20.1/orchestrate-a-local-cluster-with-kubernetes.md
- v20.1/orchestrate-cockroachdb-with-kubernetes-insecure.md
- v20.1/orchestrate-cockroachdb-with-kubernetes.md
Fixes #6118 #5931
Based on #6103 submitted by @tyranron
> update Helm steps for Helm 3.0

- v19.2/authentication.md
- v20.1/authentication.md
Opening a new PR to address the changes suggested in #4537 
(The original PR was opened for 2.1 and is now outdated.)
> Update external contributor's PR

- v19.2/cockroachcloud-frequently-asked-questions.md
- v19.2/cockroachcloud-security-overview.md
- v20.1/cockroachcloud-frequently-asked-questions.md
- v20.1/cockroachcloud-security-overview.md
> Added info for CC backup encryption

- _includes/v20.1/misc/external-urls.md
- v19.2/import.md
- v20.1/import.md
- Edit note about nodelocal usage (Closes #5905)
- Add nodelocal IMPORT example (Closes #6083)
- Allow wildcards in IMPORT URLs (Closes #5904)
> Nodelocal updates and CSV wildcard

- _config_base.yml
- _data/releases.yml
- _includes/sidebar-releases.json
- releases/v19.1.7.md
> Add v19.1.7 release notes and related doc updates

- _config_base.yml
- _data/releases.yml
- _includes/sidebar-releases.json
- releases/v2.1.11.md
> Add v2.1.11 release notes and related doc updates

- _includes/v19.2/sql/use-import-into.md
- _includes/v20.1/sql/use-import-into.md
- v19.2/migrate-from-csv.md
- v19.2/migrate-from-mysql.md
- v19.2/migrate-from-oracle.md
- v19.2/migrate-from-postgres.md
- v20.1/migrate-from-csv.md
- v20.1/migrate-from-mysql.md
- v20.1/migrate-from-oracle.md
- v20.1/migrate-from-postgres.md
> Add notes about using IMPORT INTO to import into existing tables

- v19.2/cockroachcloud-connect-to-your-cluster.md
- v20.1/cockroachcloud-connect-to-your-cluster.md
Update the Node/pg code sample to add:
- missing comma
- couple of library imports
- connection pool object
- main function skeleton
- link to the node-postgres module documentation
Fixes #6392.
> Update JS code on CockroachCloud connection page

- _includes/sidebar-releases.json
- releases/v19.2.2.md
- releases/v19.2.3.md
Also only show latest 19.2 patch in sidebar.
> Link to stable docker image

- _includes/v20.1/sql/functions.md
- _includes/v20.1/sql/settings/settings.md
> Refresh 20.1 functions and cluster settings docs

- v20.1/install-cockroachdb-linux.html
- v20.1/install-cockroachdb-mac.html
> Bump Go version for building from source

- _includes/v20.1/app/django-basic-sample/views.py
- _includes/v20.1/app/insecure/django-basic-sample/views.py
see https://github.com/cockroachdb/django-cockroachdb/issues/121
> Fix up retry code in django

- releases/v19.2.3.md
- releases/v20.1.0-alpha.20200123.md
> Correct release note about cross joins

- _includes/v20.1/admin-ui/admin-ui-metrics-navigation.md
- v20.1/admin-ui-cdc-dashboard.md
- v20.1/admin-ui-hardware-dashboard.md
- v20.1/admin-ui-overview-dashboard.md
- v20.1/admin-ui-replication-dashboard.md
- v20.1/admin-ui-runtime-dashboard.md
- v20.1/admin-ui-sql-dashboard.md
- v20.1/admin-ui-storage-dashboard.md
> document Admin UI range selector

- _includes/sidebar-data-v19.2.cockroachcloud.json
- _includes/sidebar-data-v20.1.cockroachcloud.json
- _includes/v20.1/known-limitations/cdc.md
- v19.2/change-data-capture.md
- v19.2/known-limitations.md
- v19.2/stream-changefeed-to-snowflake-aws.md
- v20.1/change-data-capture.md
- v20.1/known-limitations.md
- v20.1/stream-changefeed-to-snowflake-aws.md
Use a CockroachCloud cluster stream an enterprise changefeed through AWS S3 to Snowflake.
Closes #5874.
> Tutorial: Enterprise CDC + Snowflake

- v19.1/architecture/storage-layer.md
- v19.2/architecture/storage-layer.md
- v20.1/architecture/storage-layer.md
> Update GC TTL info in Storage Layer docs

- v19.1/topology-follower-reads.md
- v19.2/topology-follower-reads.md
- v20.1/topology-follower-reads.md
> Fix SQL errors in Follower Reads topology page

- _config_base.yml
- _data/releases.yml
- _includes/sidebar-releases.json
- releases/v19.1.8.md
- releases/v19.2.4.md
> Release notes for 19.2.4 and 19.1.8

- _includes/v19.1/cdc/correctness-warning.md
- _includes/v19.1/known-limitations/cdc.md
- _includes/v19.2/known-limitations/cdc.md
- v19.1/change-data-capture.md
- v19.1/create-changefeed.md
- v19.2/change-data-capture.md
- v19.2/create-changefeed.md
- v20.1/change-data-capture.md
> Fix docs about CDC correctness issue

- v20.1/performance-best-practices-overview.md
Added a copy functionality for copying the source code.
> Added a copy functionality for the code.

- _config_base.yml
- _data/releases.yml
- releases/v20.1.0-beta.1.md
> Release notes for v20.1.0-beta.1

- v19.2/cockroachcloud-create-your-cluster.md
- v20.1/cockroachcloud-create-your-cluster.md
> Updated CC pricing

- v20.1/create-changefeed.md
Changes:
- Added note to `CREATE CHANGEFEED` > Options section
Closes #6182.
> CDC: experimental_avro + envelope=key_only + updated is now rejected

- _includes/topnav.html
This updates the nav to link to the new pages and new page names
> update nav paths

- _includes/v19.2/app/django-basic-sample/views.py
- _includes/v19.2/app/insecure/django-basic-sample/views.py
Using a global in_retry variable causes a race condition. This was
already fixed in the v20.1 docs, so the v19.2 docs need the same fix.
> Fix transaction retry function for v19.2 Django docs

- v20.1/cockroach-commands.md
> Remove reference to cockroach user command

- v19.2/cockroachcloud-frequently-asked-questions.md
- v20.1/cockroachcloud-frequently-asked-questions.md
> CC: Fixed broken links

- _includes/head.html
- _includes/unsupported-version-soon.md
> Tell search engines to ignore docs prior to 19.1

- _config_base.yml
- _data/releases.yml
- _includes/v20.1/sql/settings/settings.md
- releases/v20.1.0-beta.2.md
> Add release notes for v20.1.0-beta.2

- jekyll-algolia-dev/lib/jekyll/algolia/hooks.rb
Add dev documents to the index only if the stable version does not have the doc
> Index only dev version documents if no stable version exists

- _includes/v19.2/sql/diagrams/on_conflict.html
- _includes/v20.1/sql/diagrams/on_conflict.html
> Remove where clause from INSERT .. ON CONFLICT diagrams

- v20.1/show-queries.md
Fixes #6189.  
(with #6647)
- Updated results list on SHOW QUERIES page.
- Updated output and examples on SHOW QUERIES page.
Adding you to review, @rohany, since Solon is out and the original PR was opened by an outside contributor (https://github.com/cockroachdb/cockroach/pull/41622).
> Updated SHOW QUERIES results and examples

- _includes/v20.1/sql/diagrams/select.html
@rmloveland caught a mistake in the SELECT diagram (#6767). This PR fixes that mistake.
> Regenerated SELECT diagram

- _includes/sidebar-data-v20.1.cockroachcloud.json
- _includes/sidebar-data-v20.1.json
- _includes/v20.1/sql/diagrams/import_csv.html
- _includes/v20.1/sql/diagrams/import_into.html
- v20.1/import-into.md
- v20.1/import.md
- v20.1/migrate-from-avro.md
- Added new page `migrate-from-avro.md`
- Added avro options and examples to `import.md`
- Added avro to `import-into.md`
TO DO:
Closes #5961.
> Migrate from Avro

- _includes/v20.1/sql/aggregates.md
- _includes/v20.1/sql/functions.md
- _includes/v20.1/sql/window_functions.md
> Updated functions tables for 20.1

- v19.2/cockroachcloud-create-your-cluster.md
- v20.1/cockroachcloud-create-your-cluster.md
> Updated names of node sizes

- _includes/v20.1/sql/diagrams/alter_sequence_options.html
- _includes/v20.1/sql/diagrams/create_sequence.html
- v20.1/alter-sequence.md
- v20.1/create-sequence.md
Fixes #6198.
- Updated `alter_sequence_options.html` and `create_sequence.html` diagrams to include `OWNED BY` parameter.
- Updated `ALTER SEQUENCE` and `CREATE SEQUENCE` pages with `OWNED BY` parameter description.
> ALTER/CREATE SEQUENCE column ownership docs

- v19.1/topology-duplicate-indexes.md
- v19.2/topology-duplicate-indexes.md
- v20.1/topology-duplicate-indexes.md
> Embed youtube video on duplicate indexes doc

- _includes/sidebar-data-v19.2.cockroachcloud.json
- _includes/sidebar-data-v20.1.cockroachcloud.json
- v19.2/build-a-python-app-with-cockroachdb-django.md
- v20.1/build-a-python-app-with-cockroachdb-django.md
Closes #6809 
- Added conditional text for CRDB-Django app doc to make it work for CC
- Updated CC sidebar nav
- Verified that the code works for CC
- Added tag to build the doc for CC
@jseldess Can you verify if I used the conditional tags properly?
> Adapt Django sample app for CC

- v19.2/admin-ui-sql-dashboard.md
- v19.2/admin-ui-storage-dashboard.md
- v20.1/admin-ui-sql-dashboard.md
- v20.1/admin-ui-storage-dashboard.md
> minor Admin UI updates

- v20.1/time.md
- v20.1/timestamp.md
> Added precision sections for TIME and TIMESTAMP data types

- v19.2/cockroachcloud-console-access-management.md
- v19.2/cockroachcloud-create-your-cluster.md
- v20.1/cockroachcloud-console-access-management.md
- v20.1/cockroachcloud-create-your-cluster.md
Closes #6358 
cc @davidmargolin for review (GH won't let me assign the PR to you for review)
> Trial codes content

- v19.1/bytes.md
- v19.1/string.md
- v19.2/bytes.md
- v19.2/string.md
- v2.1/bytes.md
- v2.1/string.md
- v20.1/bytes.md
- v20.1/string.md
- Changed "specificially" to "specifically".
> Fixed typo

- _includes/footer.html
- _includes/topnav.html
Updates the nav pointing to new compare and pricing page
> new pricing page

- _redirects
Force redirects in case any break when Netlify updates how redirects are handled
> force redirects

- v20.1/cockroach-nodelocal-upload.md
Added a link to the cockroach start flag descriptions.
> Minor copy edit on cockroach nodelocal upload

- v19.1/build-a-go-app-with-cockroachdb-gorm.md
- v19.1/build-a-go-app-with-cockroachdb.md
- v19.1/build-a-java-app-with-cockroachdb-hibernate.md
- v19.1/build-a-java-app-with-cockroachdb.md
- v19.1/build-a-python-app-with-cockroachdb-sqlalchemy.md
- v19.1/build-a-python-app-with-cockroachdb.md
- v19.2/build-a-go-app-with-cockroachdb-gorm.md
- v19.2/build-a-go-app-with-cockroachdb.md
- v19.2/build-a-java-app-with-cockroachdb-hibernate.md
- v19.2/build-a-java-app-with-cockroachdb.md
- v19.2/build-a-python-app-with-cockroachdb-sqlalchemy.md
- v19.2/build-a-python-app-with-cockroachdb.md
- v20.1/build-a-go-app-with-cockroachdb-gorm.md
- v20.1/build-a-go-app-with-cockroachdb.md
- v20.1/build-a-java-app-with-cockroachdb-hibernate.md
- v20.1/build-a-java-app-with-cockroachdb.md
- v20.1/build-a-python-app-with-cockroachdb-sqlalchemy.md
- v20.1/build-a-python-app-with-cockroachdb.md
Addresses #5885.
- Add links to git repos for 'Hello World' apps for Go, Java, and Python
- Because the git repos show "insecure" connections, the doc updates
only cover the insecure examples.  The secure examples get a note
letting the user know about the git repo.
- Propagate the above changes to versions: 19.1, 19.2, 20.1
> Add links to git repos for 'Hello World' apps

- v19.1/deploy-cockroachdb-on-microsoft-azure-insecure.md
- v19.1/deploy-cockroachdb-on-microsoft-azure.md
- v19.1/recommended-production-settings.md
- v19.2/deploy-cockroachdb-on-microsoft-azure-insecure.md
- v19.2/deploy-cockroachdb-on-microsoft-azure.md
- v19.2/recommended-production-settings.md
- v20.1/deploy-cockroachdb-on-microsoft-azure-insecure.md
- v20.1/deploy-cockroachdb-on-microsoft-azure.md
- v20.1/recommended-production-settings.md
Recommend the compute-optimized F-series in the prod
checklist and Azure-specific deployment tutorials.
Fixes #4561.
> Update Azure hardware recs

- v20.1/information-schema.md
Fixes #6594. 
- Updated description of table_constraints table.
- Updated example output.
> Update to information_schema.table_constraints table

- v20.1/interval.md
Fixes #6612. 
Fixes #6448.
Fixes #6450. 
- Updated "Syntax" section of `INTERVAL` page.
- Updated "Precision" section of `INTERVAL` page.
- Added "Duration fields" section to `INTERVAL` page.
> INTERVAL updates

- _includes/v20.1/misc/session-vars.html
> Fixed typo in description of session variable 'enable_zigzag_join'

- _includes/sidebar-data-v19.2.cockroachcloud.json
- _includes/sidebar-data-v20.1.cockroachcloud.json
- releases/cockroachcloud-04062020.md
- v20.1/build-a-python-app-with-cockroachdb-django.md
Closes #7014 
@celiala @joshimhoff @kannanlakshmi Please check if I missed any updates that should have been called out. TIA!
> CC release notes for April

- _includes/v20.1/sql/aggregates.md
- _includes/v20.1/sql/functions.md
- _includes/v20.1/sql/operators.md
Fixes #6980.
Fixes #6974.
Fixes #7028.
> Updated built-in functions and operators include files

- _includes/v20.1/sql/diagrams/show_backup.html
- v20.1/backup.md
- v20.1/show-backup.md
Changes to `backup.md`:
- Reorganized the info in the "Viewing and controlling backups jobs" section
- Added note about `CHECKPOINT` file. Closes #6831.
Changes to `show-backup.md`:
- Updated SQL diagram
- Added `WITH privileges` parameter
- Added `is_full_cluster` column to the response
- Added "Show a backup with privileges" example
> Misc. BACKUP v20.1 Updates

- v20.1/architecture/storage-layer.md
Fixes #6003.
- Add new section 'Storage Layer > GC > Protected Timestamps', which
describes what they are and how they work at a high level.
> Add docs on the protected timestamp subsystem

- _includes/sidebar-data-v19.2.cockroachcloud.json
- _includes/sidebar-data-v20.1.cockroachcloud.json
- releases/cockroachcloud-03022020.md
- releases/cockroachcloud-04062020.md
Fixes #7006.
Footer signup was already in place.
> Add release note signup to CC release pages

- _config_base.yml
- _data/releases.yml
- _includes/sidebar-releases.json
- releases/v19.2.6.md
> Add v19.2.6 release notes

- v20.1/data-types.md
- v20.1/time.md
Fixes #7116.
- Added "New in v20.1" element to Data Types page for `TIMETZ`.
- Added "New in v20.1" element to `TIME` page for `TIMETZ`.
> Marked TIMETZ as new in 20.1

- _config_base.yml
- _data/releases.yml
- releases/v20.1.0-beta.4.md
- releases/v20.1.0-rc.1.md
> v20.1.0-rc.1 release notes and related updates

- releases/v19.2.6.md
- v19.2/monitoring-and-alerting.md
- v20.1/monitoring-and-alerting.md
- Release notes v19.2.6
- Monitoring and Alerting (dev and stable)
> Correcting Typos

- v20.1/admin-ui-cluster-overview-page.md
> Admin UI email signup

- v20.1/experimental-features.md
- v20.1/indexes.md
- Added New in v20.1 tag to hash-sharded indexes section
- Added experimental warning to hash-sharded indexes section
- Added hash-sharded indexes to experimental features
> Hash-sharded indexes updates

- _config_base.yml
- _data/releases.yml
- releases/v20.1.0-rc.2.md
> Add v20.1.0-rc.2 release notes

- v20.1/cockroach-debug-zip.md
Fixes #6744.
Fixes #6940.
Fixes #6931.
Fixes #6739.
- This change covers `cockroach debug zip`.
- The identical change in UI - Advanced Debug is reflected in #7010.
> update cockroach debug zip

- _includes/v20.1/sql/diagrams/create_index.html
- _includes/v20.1/sql/diagrams/create_inverted_index.html
- _includes/v20.1/sql/diagrams/drop_index.html
- v20.1/create-index.md
- v20.1/drop-index.md
Fixes #7140. 
- Updated diagrams that include `CONCURRENTLY` keyword.
- Added `CONCURRENTLY` parameter description.
> No-op CONCURRENTLY syntax added

- v20.1/cost-based-optimizer.md
- v20.1/delete.md
- v20.1/explain.md
- v20.1/indexes.md
- v20.1/make-queries-fast.md
- v20.1/performance-best-practices-overview.md
- v20.1/performance-tuning-insecure.md
- v20.1/performance-tuning.md
- v20.1/selection-queries.md
- v20.1/sql-tuning-with-explain.md
- v20.1/update.md
Fixes #7142.
- Updated some wording around output of `EXPLAIN`.
- Updated all example output for `EXPLAIN`.
> Updated EXPLAIN output for 20.1

- v20.1/alter-primary-key.md
Fixes #7076.
- Added two new bullets to details of `ALTER PRIMARY KEY` about partitioning secondary indexes.
- Extended geo-partitioning example in `ALTER PRIMARY KEY` to include secondary index partitioning.
> Partitioning and ALTER PRIMARY KEY

- v19.2/gssapi_authentication.md
- v20.1/gssapi_authentication.md
> GSSAPI Authentication (Enterprise) Doc Update

- v19.1/rename-column.md
- v19.2/rename-column.md
- v20.1/rename-column.md
> Corrected IF EXISTS description for RENAME COLUMN

- v19.1/create-table.md
- v19.2/create-table.md
- v20.1/create-table.md
> Added note about automatic FK index creation

- _data/releases.yml
- _includes/sidebar-releases.json
- _includes/unsupported-version-soon.md
- _includes/unsupported-version.md
- releases/index.md
- releases/release-support-policy.md
- v19.1/support-resources.md
- v19.2/support-resources.md
- v2.0/support-resources.md
- v2.1/support-resources.md
- v20.1/support-resources.md
- Explain phases of support (maintenance, assistance, EOL).
- Update references through docs.
- Explain versioning scheme.
Addresses part of #6993.
> Release support policy

- v20.1/cockroach-gen.md
> update cockroach gen haproxy

- _includes/sidebar-data-v19.2.cockroachcloud.json
- _includes/sidebar-data-v20.1.cockroachcloud.json
- releases/cockroachcloud-05042020.md
> CC: May Release Notes

- v20.1/create-view.md
Fixes #6729. 
- Added `IF NOT EXISTS` parameter description to `CREATE VIEW` page. 
(Diagram already up-to-date from #6862.)
- Updated example output on `CREATE VIEW` page.
> CREATE VIEW IF NOT EXISTS

- v19.2/authorization.md
- v19.2/show-ranges.md
- v20.1/authorization.md
- v20.1/show-ranges.md
Also show how to add a user to the admin role.
Fixes #7297
> Correct privileges required for show ranges

- _config_base.yml
> Fix docker image for 20.1

- releases/v20.1.0.md
> CC trial code update

- _config_base.yml
- _data/releases.yml
- _includes/sidebar-releases.json
- releases/v19.1.9.md
> Add v19.1.9 release notes

- v19.1/known-limitations.md
- v19.1/migrate-from-oracle.md
- v19.2/known-limitations.md
- v19.2/migrate-from-oracle.md
- v20.1/known-limitations.md
- v20.1/migrate-from-oracle.md
Resolves https://github.com/cockroachdb/docs/issues/7318.
> remove "Silent validation error with DECIMAL values" limitation

- _includes/v20.1/known-limitations/dump-table-with-collations.md
- v19.1/known-limitations.md
- v19.2/known-limitations.md
- v20.1/cockroach-dump.md
- v20.1/known-limitations.md
> Document remaining 20.1 known limitations

- jekyll-algolia-dev/lib/jekyll/algolia/configurator.rb
See https://github.com/cockroachdb/docs/issues/7351 for context.
> Add list items to search indexing (Fixes 7351)

- v19.1/cockroachdb-in-comparison.md
- v19.2/cockroachdb-in-comparison.md
- v20.1/cockroachdb-in-comparison.md
> typo Transations fixed

- v19.2/postgresql-compatibility.md
- v20.1/postgresql-compatibility.md
Addresses https://github.com/cockroachdb/docs/issues/7362
> Change Postgres compatibility to version 9.5

- _includes/sidebar-data-v20.1.json
Also create tutorial categories:
- Database Capabilities
- Third-Party Tools
- Multi-Region App Development
> Move third-party pages to tutorials

- v20.1/backup-and-restore-advanced-options.md
- Clarify UX for locality-aware incremental backup / restore. Closes #7335.
- Add information about full cluster restore and zone configs. Closes #7112.
> Misc. BACKUP edits

- v19.2/multi-region-deployment.md
- v20.1/multi-region-deployment.md
Following a direct customer request, I made some minor improvements to the Multi-region application deployment (GKE) section of our multi-region tutorial.
> Improvements to Multi-region application deployment (GKE) instructions

- _includes/sidebar-data-v20.1.json
- v20.1/developer-guide-overview.md
With Hello World and Multi-Region sub-sections.
> Create Sample Apps section under Tutorials

- _includes/v20.1/known-limitations/dropping-renaming-during-upgrade.md
- v20.1/known-limitations.md
- v20.1/upgrade-cockroach-version.md
> Document limitation when upgrading to v20.1.0

- _includes/v20.1/misc/tooling.md
- v20.1/third-party-database-tools.md
Fixes #7279
* Removed comprehensive/partial support classification in favor of full/beta everywhere
> Add appdev tooling one page summary

- _includes/v20.1/faq/sql-query-logging.md
- v20.1/query-behavior-troubleshooting.md
> mention slow query log overhead

- v20.1/cockroach-debug-ballast.md
Fixes #7394 
@Amruta-Ranade, not sure if I fixed this correctly (it works on local build). It looked like the doc had been set to redirect to itself. Let me know if we need to get another opinion on this!
> fix broken redirect

- jekyll-algolia-dev/lib/jekyll/algolia/hooks.rb
- jekyll-algolia-dev/lib/jekyll/algolia/indexer.rb
> Revert "Add temporary Algolia logging to better understand indexing by versions"

- v19.1/string.md
- v19.2/string.md
- v20.1/string.md
> Update STRING docs to use same size limit as BYTES

- _includes/sidebar-data-v20.1.cockroachcloud.json
- v20.1/cockroachcloud-connect-to-your-cluster.md
- v20.1/cockroachcloud-create-your-account.md
- v20.1/cockroachcloud-create-your-cluster.md
- v20.1/cockroachcloud-quickstart.md
Summary:
- Added a quickstart guide that leverages the generic free trial code
- Updated the sidebar nav
- Cleaned up other docs to match the current UI
> CC trial codes

- v19.2/import.md
- v20.1/import.md
- v20.2/import.md
Commenting out the IMPORT option for now. Closes #7494.
> Remove experimental_save_rejected option

- v20.2/show-sessions.md
> Port #7485 to v20.2

- css/components/_toc.scss
- css/customstyles.css
- css/customstyles.scss
Makes scrollbar visible on Chrome
Fixes issue #5029
> Fix scrollbar on Chrome

- v20.1/recommended-production-settings.md
- v20.2/recommended-production-settings.md
> Update node density docs

- _config_base.yml
- _data/releases.yml
- _includes/sidebar-releases.json
- releases/v20.1.2.md
- releases/v20.2.0-alpha.1.md
> Release notes v20.2.0 alpha.1 and v20.1.2

- _includes/v20.2/sql/aggregates.md
- _includes/v20.2/sql/functions.md
- _includes/v20.2/sql/operators.md
- _includes/v20.2/sql/window_functions.md
... as well as whatever else was available on the main branch of
CockroachDB as of 6589106751d844bb6f01300c06d2872086de2632.
> Add docs for geospatial built-in functions

- v19.1/cockroachdb-in-comparison.md
- v19.2/cockroachdb-in-comparison.md
- v20.1/cockroachdb-in-comparison.md
- v20.2/cockroachdb-in-comparison.md
> Fix typo on comparison page

- v20.1/cockroachcloud-upgrade-to-v20.1.md
> Embed 20.1 CC upgrade video

- _includes/v19.1/misc/force-index-selection.md
- _includes/v19.2/misc/force-index-selection.md
- _includes/v20.1/misc/force-index-selection.md
- _includes/v20.2/misc/force-index-selection.md
> Fixed a typo on Table Expressions page

- _includes/v19.2/orchestration/start-cockroachdb-helm-insecure.md
- _includes/v19.2/orchestration/start-cockroachdb-helm-secure.md
- _includes/v19.2/orchestration/start-cockroachdb-local-helm-insecure.md
- _includes/v19.2/orchestration/start-cockroachdb-local-helm-secure.md
- _includes/v20.1/orchestration/start-cockroachdb-helm-insecure.md
- _includes/v20.1/orchestration/start-cockroachdb-helm-secure.md
- _includes/v20.1/orchestration/start-cockroachdb-local-helm-insecure.md
- _includes/v20.1/orchestration/start-cockroachdb-local-helm-secure.md
- _includes/v20.2/orchestration/start-cockroachdb-helm-insecure.md
- _includes/v20.2/orchestration/start-cockroachdb-helm-secure.md
- _includes/v20.2/orchestration/start-cockroachdb-local-helm-insecure.md
- _includes/v20.2/orchestration/start-cockroachdb-local-helm-secure.md
Relates to https://github.com/cockroachdb/dev-inf/issues/82
> update Helm chart links

- v19.2/build-a-go-app-with-cockroachdb-gorm.md
- v19.2/build-a-go-app-with-cockroachdb.md
- v20.1/build-a-go-app-with-cockroachdb-gorm.md
- v20.1/build-a-go-app-with-cockroachdb.md
- v20.2/build-a-go-app-with-cockroachdb-gorm.md
- v20.2/build-a-go-app-with-cockroachdb.md
- Corrected some typos/grammar errors.
- Removed erroneous "Beta support" notes.
- Made `crdb` library install consistent across examples.
> Misc updates to Go Hello World tutorials

- _data/advisories.yml
- advisories/a50587.md
> Technical advisory 50587

- _config_base.yml
- _data/releases.yml
- _includes/sidebar-releases.json
- releases/v19.1.11.md
> v19.1.11 Release Notes

- v19.2/authentication.md
- v19.2/show-queries.md
- v19.2/show-sessions.md
- v20.1/authentication.md
- v20.1/show-queries.md
- v20.1/show-sessions.md
- v20.2/authentication.md
- v20.2/show-queries.md
- v20.2/show-sessions.md
> Authorization Doc updates

- _includes/v19.2/misc/movr-live-demo.md
- _includes/v20.1/misc/movr-live-demo.md
- _includes/v20.2/misc/movr-live-demo.md
- v19.2/movr.md
- v19.2/multi-region-application.md
- v19.2/multi-region-deployment.md
- v19.2/multi-region-overview.md
- v20.1/movr.md
- v20.1/multi-region-application.md
- v20.1/multi-region-deployment.md
- v20.1/multi-region-overview.md
- v20.2/movr.md
- v20.2/multi-region-application.md
- v20.2/multi-region-deployment.md
- v20.2/multi-region-overview.md
> Added links to live movr demo

- _includes/v19.2/app/django-basic-sample/settings.py
- _includes/v20.1/app/django-basic-sample/settings.py
- _includes/v20.2/app/django-basic-sample/settings.py
- v19.2/build-a-python-app-with-cockroachdb-django.md
- v20.1/build-a-python-app-with-cockroachdb-django.md
- v20.2/build-a-python-app-with-cockroachdb-django.md
Fixes #7523.
Updated settings files and code snippets to use SSL instead of password authentication.
> Fixed secure Django sample app settings to use SSL

- v19.2/build-a-python-app-with-cockroachdb-django.md
- v19.2/build-a-python-app-with-cockroachdb-pony.md
- v19.2/build-a-python-app-with-cockroachdb-sqlalchemy.md
- v19.2/install-client-drivers.md
- v19.2/multi-region-setup.md
- v20.1/build-a-python-app-with-cockroachdb-django.md
- v20.1/build-a-python-app-with-cockroachdb-pony.md
- v20.1/build-a-python-app-with-cockroachdb-sqlalchemy.md
- v20.1/install-client-drivers.md
- v20.1/multi-region-setup.md
- v20.2/build-a-python-app-with-cockroachdb-django.md
- v20.2/build-a-python-app-with-cockroachdb-pony.md
- v20.2/build-a-python-app-with-cockroachdb-sqlalchemy.md
- v20.2/install-client-drivers.md
- v20.2/multi-region-setup.md
Fixes #7333
- Added prerequisite notes to django-cockroachdb install instructions
- Changed occurences of python3 to python
> Django install note added + misc update

- _includes/newsletter-popout.html
Added a condition around the js to check if on the advisories page to always show the email popup 
prettier formatted the page
> open email popup on advisories page

- _includes/v20.1/misc/tooling.md
- _includes/v20.2/misc/tooling.md
Fixes https://github.com/cockroachdb/docs/issues/6865
> Add Flowable full support and link to Flowable's tutorial

- _data/releases.yml
- releases/v20.2.0-alpha.2.md
> Release date fixed

- v20.2/cockroach-dump.md
> Add --dump-all flag to cockroach dump

- _config_base.yml
- _data/releases.yml
- _includes/sidebar-releases.json
- releases/v20.1.4.md
> Release notes for v20.1.4

- _includes/v20.2/sql/diagrams/create_view.html
- v20.2/create-view.md
- v20.2/views.md
Fixes #7746. 
Fixes #7606. 
- Updated SQL diagram for `CREATE VIEW` page.
- Updated parameters on `CREATE VIEW` page.
- Updated examples on `CREATE VIEW` and Views pages.
> Support for CREATE OR REPLACE VIEW

- _includes/sidebar-data-v20.1.json
- _includes/sidebar-data-v20.2.json
- v20.1/disaster-recovery.md
- v20.2/disaster-recovery.md
Add Disaster Recovery doc
Main made from Chris' draft:
- General grammatical / style changes
- Re-arranged content to be broken up by single-region vs. multi-region
- Added links
> Disaster Recovery

- css/customstyles.css
Fixes https://github.com/cockroachdb/docs/issues/7806
Previously fixed with https://github.com/cockroachdb/docs/pull/7189
> Repush fix to prevent Contribute dropdown cutoff

- _includes/v20.2/misc/session-vars.html
> typo fixed

- _includes/v20.2/sql/aggregates.md
- _includes/v20.2/sql/functions.md
- _includes/v20.2/sql/operators.md
Generated functions (built-ins, aggregates, operators) update as of https://github.com/cockroachdb/cockroach/releases/tag/provisional_202008031850_v20.2.0-alpha.3.
@rmloveland FYI, as some of these might touch geospatial.
> Generated functions (built-ins, aggregates, operators) doc update for v20.2 (alpha 3)

- v20.1/known-limitations.md
> Document issue where 20.1 upgrade breaks Data Distribution page

- _redirects
> Redirect "releases"  to "releases/"

- jekyll-algolia-dev/lib/jekyll/algolia/indexer.rb
> Test search synonyms

- _includes/sidebar-data-v20.2.json
- _includes/v20.2/misc/tooling.md
- v20.2/liquibase.md
Fixes #5989.
- Added new tutorial on using Liquibase with CRDB.
- Updated tooling tutorials ToC.
> Liquibase tutorial

- v20.1/show-backup.md
- v20.2/show-backup.md
> Fix SHOW BACKUP examples

- _includes/unsupported-version-soon.md
- _layouts/page.html
Chanced upon this and thought I would quickly update.
Not sure who should review but I think @taroface worked on the release support policy page recently so I added you!
> Update unsupported versions

- releases/v20.1.0.md
- v20.1/alter-primary-key.md
- v20.1/backup-and-restore.md
- v20.1/flyway.md
- v20.1/follower-reads.md
- v20.2/alter-primary-key.md
- v20.2/backup-and-restore.md
- v20.2/flyway.md
- v20.2/follower-reads.md
Fixes #7804. 
FYI @dankellycockroach @jseldess
> Embedded some new videos

- releases/v20.1.0.md
- v20.1/alter-primary-key.md
- v20.1/backup-and-restore.md
- v20.1/flyway.md
- v20.1/follower-reads.md
- v20.2/alter-primary-key.md
- v20.2/backup-and-restore.md
- v20.2/flyway.md
- v20.2/follower-reads.md
Reverts cockroachdb/docs#7944
Embedded videos are broken...
> Revert "Embedded some new videos"

- v20.1/alter-primary-key.md
- v20.1/backup-and-restore.md
- v20.1/flyway.md
- v20.1/follower-reads.md
- v20.2/alter-primary-key.md
- v20.2/backup-and-restore.md
- v20.2/flyway.md
- v20.2/follower-reads.md
> Embed videos

- _config_base.yml
- _data/releases.yml
- _includes/sidebar-releases.json
- releases/v19.2.10.md
> Add v19.2.10 release notes

- releases/v20.2.0-alpha.3.md
> Add release notes for v20.2.0-alpha.3

- _config_base.yml
- _data/releases.yml
- _includes/sidebar-releases.json
- releases/v20.2.0-alpha.3.md
Forgot to do the "edit config files" portion during the original PR to address #7976.
> Update site configs for v20.2.0-alpha.3

- v20.2/cockroach-sql.md
> Removed smart_prompt from docs

- v20.2/alter-role.md
- v20.2/alter-user.md
- v20.2/create-role.md
- v20.2/create-user.md
- v20.2/drop-role.md
> Removed output from CREATE/ALTER/DROP role and aliases examples

- v20.1/cockroachcloud-upgrade-policy.md
> Updated CC upgrade doc

- _includes/v20.1/cockroachcloud-pricing.md
- v20.1/cockroachcloud-connect-to-your-cluster.md
- v20.1/cockroachcloud-create-your-cluster.md
> CC pricing updates

- _includes/sidebar-data-v20.1.cockroachcloud.json
- _includes/sidebar-data-v20.1.json
- _includes/sidebar-data-v20.2.json
- _includes/v20.1/misc/import-perf.md
- _includes/v20.2/misc/import-perf.md
- v20.1/import-performance-best-practices.md
- v20.1/migrate-from-avro.md
- v20.1/migrate-from-csv.md
- v20.1/migrate-from-mysql.md
- v20.1/migrate-from-oracle.md
- v20.1/migrate-from-postgres.md
- v20.1/migration-overview.md
- v20.2/import-performance-best-practices.md
- v20.2/migrate-from-avro.md
- v20.2/migrate-from-csv.md
- v20.2/migrate-from-mysql.md
- v20.2/migrate-from-oracle.md
- v20.2/migrate-from-postgres.md
- v20.2/migration-overview.md
> Add Import Performance Best Practices

- _config_base.yml
- _data/releases.yml
- _includes/sidebar-releases.json
- releases/v20.1.5.md
> v20.1.5 release notes

- _includes/sidebar-data-v20.2.json
- _includes/v20.2/sql/diagrams/alter_type.html
- _includes/v20.2/sql/diagrams/create_type.html
- _includes/v20.2/sql/diagrams/drop_type.html
- _includes/v20.2/sql/diagrams/show_enums.html
- v20.2/alter-type.md
- v20.2/create-type.md
- v20.2/data-types.md
- v20.2/drop-type.md
- v20.2/enum.md
- v20.2/migration-overview.md
- v20.2/postgresql-compatibility.md
- v20.2/restore.md
- v20.2/show-enums.md
- v20.2/sql-audit-logging.md
- v20.2/sql-feature-support.md
- v20.2/sql-statements.md
Fixes #7751. 
Fixes #7626. 
Fixes #8154.
Fixes #8136.
> Support for ENUM types

- _includes/sidebar-data-cockroachcloud.json
- _includes/sidebar-data-v20.1.json
- _includes/sidebar-data-v20.2.json
Update sidebar to match 20.1 sections and add back links that were dropped
cc @yingzhuchin
> Update 20.2 sidebar

- _includes/v20.1/misc/tooling.md
- _includes/v20.2/misc/tooling.md
- v19.2/third-party-database-tools.md
You guys added CockroachDB support to Beekeeper a few months ago, so figured I'd call it out!
> Add beekeeper studio to your docs

- v20.2/install-cockroachdb-spatial.md
s/alpha.3/beta.1/g
Fixes #8405.
> Update download locations for spatial install

- v20.2/cockroach-quit.md
> remove --decommission from cockroach quit

- v20.1/topology-duplicate-indexes.md
- v20.2/topology-duplicate-indexes.md
... in both 20.1 and 20.2 docs.
Fixes #8262.
> Fix incorrect Follower Reads interval

- v19.1/string.md
- v19.2/string.md
- v2.0/string.md
- v2.1/string.md
- v20.1/string.md
- v20.2/string.md
> Remove STRING collation warning

- _includes/v20.2/misc/session-vars.html
- v20.2/cost-based-optimizer.md
- v20.2/joins.md
Fixes #8351. 
- Added note to Cost-based Optimizer and Joins pages.
- Added new prefer_lookup_joins_for_fk to list of session variables.
> prefer_lookup_joins_for_fk setting

- _config_base.yml
- _data/advisories.yml
- _data/releases.yml
- _includes/sidebar-releases.json
- advisories/a54418.md
- advisories/index.md
- releases/v20.1.4.md
- releases/v20.1.5.md
- releases/v20.1.6.md
> v20.1.6 release notes

- _includes/v20.1/topology-patterns/fundamentals.md
- v19.2/roles.md
- v20.1/topology-basic-production.md
Made the 3 proposed changes in #8407 . I wasn't sure what to do with the sub-item for item 3 in the "Provision hardware" section, so I combined the two and added parentheses.
> Minor grammar/format edits on Basic Production Topology Doc

- v20.2/spatial-data.md
> Update Docker links on 'Working with Spatial Data'

- v20.2/known-limitations.md
> Removed now() filtering limitation

- _includes/v19.2/sql/aggregates.md
> Correct aggregate functions in 19.2 docs

- v19.2/delete.md
- v20.1/delete.md
- v20.2/delete.md
- Added note on batch deleting from tables with explicit foreign key actions
> Batch deleting from tables with explicit foreign key actions

- _includes/v20.2/prod-deployment/insecure-flag.md
- v20.2/deploy-cockroachdb-on-aws-insecure.md
- v20.2/deploy-cockroachdb-on-digital-ocean-insecure.md
- v20.2/deploy-cockroachdb-on-google-cloud-platform-insecure.md
- v20.2/deploy-cockroachdb-on-microsoft-azure-insecure.md
- v20.2/deploy-cockroachdb-on-premises-insecure.md
- v20.2/deploy-cockroachdb-on-premises.md
- v20.2/orchestrate-a-local-cluster-with-kubernetes-insecure.md
- v20.2/orchestrate-cockroachdb-with-docker-swarm-insecure.md
- v20.2/orchestrate-cockroachdb-with-kubernetes-insecure.md
- v20.2/start-a-local-cluster-in-docker-mac.md
- v20.2/start-a-local-cluster.md
> Revert insecure deprecation callout

- v20.1/performance-benchmarking-with-tpc-c-100k-warehouses.md
- v20.1/performance-benchmarking-with-tpc-c-10k-warehouses.md
- v20.1/performance-benchmarking-with-tpc-c-1k-warehouses.md
- v20.1/performance.md
- v20.2/performance-benchmarking-with-tpc-c-100k-warehouses.md
- v20.2/performance-benchmarking-with-tpc-c-10k-warehouses.md
- v20.2/performance-benchmarking-with-tpc-c-1k-warehouses.md
- v20.2/performance.md
> Update 20.{1,2} docs to mention 2020 Cloud Report

- _includes/sidebar-data-v20.2.json
- v20.2/cockroach-sql.md
- v20.2/create-type.md
- v20.2/show-types.md
- v20.2/sql-statements.md
Fixes #8398.
- Added `SHOW TYPES` page.
- Added `\dT` command to `cockroach sql` page.
- Made some corrections/clarifications on a couple pages.
> SHOW TYPES and \dT

- _config_base.yml
- _data/releases.yml
- _includes/sidebar-releases.json
- releases/v20.2.0-beta.3.md
> Add release notes for v20.2.0-beta.3

- _includes/sidebar-data-v20.2.json
- v20.2/alter-database.md
- v20.2/convert-to-schema.md
- v20.2/create-schema.md
- v20.2/sql-statements.md
Fixes #8348. 
Fixes #8318. 
- Added `CONVERT TO SCHEMA` docs page, with example.
- Added misc links to `CONVERT TO SCHEMA` page.
> CONVERT TO SCHEMA docs

- _includes/v20.1/misc/movr-workflow.md
- _includes/v20.2/misc/movr-workflow.md
For each step, I added executable SQL example(s) that work with the MovR database.
> Add executable SQL examples to the MovR workflow doc

- releases/v20.1.0-beta.4.md
Tasks undertaken:
- Added link to issue 46414 in release notes for v.20.1.0-beta.4
Screenshot of fix within local build:
> Issue #7040 - What's New in v20.1.0-beta.4 Doc Update

- v19.1/migrate-from-mysql.md
- v19.2/migrate-from-mysql.md
- v2.1/migrate-from-mysql.md
- v20.1/migrate-from-mysql.md
- v20.2/migrate-from-mysql.md
This P.R fixes issue number #8449
> Updated migrate-from-mysql.md file

- v19.1/not-null.md
- v19.2/not-null.md
- v20.1/not-null.md
- v20.2/not-null.md
- added null handling hyperlink for the first NULL occurrence only, as per issue description
- added null handling hyperlink in See Also section
- minor formatting changes for the un-uniformed text
> doc: add new hyperlink (#5331)

- _includes/v20.1/topology-patterns/fundamentals.md
- v19.2/roles.md
- v20.1/topology-basic-production.md
Changed ports from 8888 to 8080 on encryption.md for version 19.2 20.1 and 20.2 (Issue #6869 )
> Port edits on encryption.md

- v19.2/start-a-local-cluster-in-docker-windows.md
- v20.1/start-a-local-cluster-in-docker-windows.md
- v20.2/start-a-local-cluster-in-docker-windows.md
@Amruta-Ranade I think I did it right this time. 🙏🏻
> Update PS command line per issue #7207

- v20.2/alter-type.md
- v20.2/create-type.md
- v20.2/drop-type.md
- v20.2/enum.md
- v20.2/show-types.md
> Added note about cross-database user-defined type references

- _includes/sidebar-data-v20.2.json
- _includes/v20.2/sql/diagrams/alter_sequence.html
- v20.2/alter-sequence.md
- v20.2/alter-table.md
- v20.2/alter-view.md
- v20.2/create-schema.md
- v20.2/set-schema.md
- v20.2/sql-statements.md
> SET SCHEMA docs

- v20.1/recommended-production-settings.md
- v20.2/recommended-production-settings.md
> correct capacity recommendations

- _config_base.yml
- _data/releases.yml
- releases/v20.2.0-beta.4.md
> v20.2.0 beta.4 release notes

- _includes/sidebar-releases.json
> Add v20.2.4 to sidebar.

- v19.1/partitioning.md
- v2.0/partitioning.md
- v2.1/partitioning.md
Re-open PR from https://github.com/cockroachdb/docs/pull/8535
Fixes https://github.com/cockroachdb/docs/issues/4964
> Add PARTITION prefix in sample query (re-open)

- v19.2/start-a-local-cluster-in-docker-windows.md
- v20.1/start-a-local-cluster-in-docker-windows.md
- v20.2/start-a-local-cluster-in-docker-windows.md
@Amruta-Ranade Changes made for the 2nd and 3rd docker port arguments per issue #7199. If these changes are correct, I will make them for 20.1 and 20.2, if needed.
> Remove 2nd & 3rd port argument.

- v20.2/explain.md
Fixes #8313.
See #8548 for updates to the session variables docs.
> Disallow full table scans

- v20.1/temporary-tables.md
- v20.2/alter-schema.md
- v20.2/cockroach-demo.md
- v20.2/cockroach-gen.md
- v20.2/convert-to-schema.md
- v20.2/create-schema.md
- v20.2/create-view.md
- v20.2/drop-database.md
- v20.2/drop-schema.md
- v20.2/drop-table.md
- v20.2/learn-cockroachdb-sql.md
- v20.2/make-queries-fast.md
- v20.2/partial-indexes.md
- v20.2/rename-table.md
- v20.2/set-schema.md
- v20.2/show-schemas.md
- v20.2/show-tables.md
- v20.2/temporary-tables.md
- v20.2/views.md
Fixes #7603. 
Fixes #8158.
- Updated syntax pages for `SHOW SCHEMAS` and `SHOW TABLES` to include latest output.
- Updated other affected pages, including `SHOW SCHEMAS` pages that queried internal tables for ownership.
> Updated output of SHOW TABLES and SHOW SCHEMAS

- v20.2/show-create.md
> Updated SHOW CREATE page output

- v19.1/follower-reads.md
- v19.2/follower-reads.md
This fixes issue #5038
Added clarifying paragraph to explain follower reads without suggesting that it can 'future-proof' the feature in users' code. 
Adding @jseldess to review following contributing.md
> Follower reads wording fix

- _includes/v20.1/app/sqlalchemy-basic-sample.py
- _includes/v20.2/app/sqlalchemy-basic-sample.py
updated _includes/v20.1/app/sqlalchemy-basic-sample.py and _includes/v20.2/app/sqlalchemy-basic-sample.py
updates include:
1. Include code smell fix that was fixed in Commit 17fc080
2. Added docstrings
3. updated variable names and other syntax as suggested by pylon
> Updated sqlalchemy-basic-sample.py to fix code smell and a few other syntax issues

- v20.2/install-cockroachdb-linux.html
- v20.2/install-cockroachdb-mac.html
> Update build from source requirements

- v20.2/enum.md
> Alpha upgrade warning for ENUM users
