cockroachdb/docs

_config.yml
_includes/head.html
basic-sql-statements.md
css/syntax.css
install-cockroachdb.md
sql-statements.md
start-a-local-cluster.md

Move to kramdown/rouge

---

cockroachdb-in-comparison.md
css/customstyles.css
css/theme-blue.css
js/customscripts.js

@bdarnell, @mrtracy, @spencerkimball, @petermattis, anyone else who wants to help:
I'm aiming to have a quick yes/no feature comparison in the beta docs. At this stage, I'd appreciate help identifying the right "features" for such a quick comparison.
- Did I list the right features? 
- Should any be rephrased?
- Are any missing?
- Any other thoughts?
Here's an html version (still needs styling), in case it's easier to read: http://cockroach-draft-docs.s3-website-us-east-1.amazonaws.com/cockroachdb-in-comparison.html
I'll find a way to provide a bit more detail (sentence or two) on hover over a yes/no answer. Hopefully we can link to standalone pages (or page sections) in our docs for each feature.

cockroachdb in comparison

---

_includes/sidebar.html
css/customstyles.css
css/customstyles.scss

Styled the search form to more closely resemble search on blog, and removed unused css.
@mjibson, @jess-edwards: Thoughts?

re-styling search form

---

start-a-local-cluster.md

I replaced `--stores` with `--store` in start-a-local-cluster.md.

changing stores to store

---

css/sql.css

Color nonterminals

---

_includes/sql/diagrams/begin_transaction.html
_includes/sql/diagrams/commit_transaction.html
_includes/sql/diagrams/drop_database.html
_includes/sql/diagrams/drop_index.html
_includes/sql/diagrams/drop_table.html
_includes/sql/diagrams/rename_column.html
_includes/sql/diagrams/rename_database.html
_includes/sql/diagrams/rename_index.html
_includes/sql/diagrams/rename_table.html
_includes/sql/diagrams/rollback_transaction.html
_includes/sql/diagrams/select.html
_includes/sql/diagrams/set_database.html
_includes/sql/diagrams/set_timezone.html
_includes/sql/diagrams/set_transaction.html
_includes/sql/diagrams/show_columns.html
_includes/sql/diagrams/show_databases.html
_includes/sql/diagrams/show_grants.html
_includes/sql/diagrams/show_index.html
_includes/sql/diagrams/show_tables.html
_includes/sql/diagrams/show_timezone.html
_includes/sql/diagrams/show_transaction_isolation_level.html
_includes/sql/diagrams/show_transaction_priority.html
_includes/sql/diagrams/values.html
generate/extract/extract.go
generate/main.go
show-transaction-isolation-level.md

A few complicated ones are missing or terse.

SQL diagrams for pretty much everything else

---

_layouts/page.html
cockroach-commands.md
start-a-node.md
stop-a-node.md

Added logging flags to docs. Does this looks correct and the right level of details? @bdarnell, @BramGruneir, @petermattis ?
HTML version here: http://cockroach-draft-docs.s3-website-us-east-1.amazonaws.com/cockroach-commands.html#logging-flags

logging flags

---

start-a-local-cluster.md

Very minor fixes to start-a-local-cluster.md

minor fixes

---

build-a-test-app.md
css/syntax.css

My intention for the **Build a Test App** page is to show a simple scenario (import driver, connect, create table, insert rows, update rows) from each language for which we've tested a driver. 
Matt Jibson was going to help with these, but since he's got his hands full, I just drafted up and tested a python example. I'd like opinions about:
1. Is the scenario sufficient for getting started docs? If not, how should we change/expand it?
2. Is it ok to show `user="root"` in the connection, or should I fake a specific user? 
3. Is it ok to show this as a single code block, or should I make it more of a narrative using the language's shell (like [rethink](https://www.rethinkdb.com/docs/guide/python/) does)? 
@spencerkimball, @tschottdorf, @bdarnell, @petermattis

python example

---

frequently-asked-questions.md

vivek's tweak to consistency explanation

---

install-cockroachdb.md

fix for multiple instances of the same hubspot form embedded on the same page

formInstanceId attribute added

---

_includes/app/basic-sample.js

Also @mrtracy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/141)

Create node.js code sample

---

_includes/app/basic-sample.clj
_includes/app/basic-sample.js
_includes/app/basic-sample.py
_includes/app/basic-sample.rb

Updating python and ruby samples to exclude the transfer transaction. That'll be in separate samples demonstrating how to retry. 
I test both samples, and they work fine. But I had to comment out the `conn.exec('SET AUTOCOMMIT = ON')` in the ruby file. @tamird, do we not need something like that to make each statement immediately commit?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/149)

Basic python and ruby samples

---

_includes/app/basic-sample.rb
_includes/app/txn-sample.clj

Accidentally left this out of last PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/150)

adding clj txn sample

---

_includes/app/BasicSample.java
build-a-test-app.md

note java requires that the class name and file name match, thus the renamed file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/142)

add java example

---

_includes/app/txn-sample.go

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/147)

go txn sample

---

_includes/app/basic-sample.py
_includes/app/txn-sample.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/152)

Expand the Python example with automatic txn retries.

---

build-a-test-app.md

I revised build-a-test-app.md to be more of a tutorial. Lists prerequisites, shows creating db and table and grant privileges from the sql client, shows connecting and executing basic statements, and finally shows the transaction scenario.
Plenty missing still, but I'd like feedback on this new format.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/153)

new approach for build-a-test-app

---

_includes/app/basic-sample.clj
_includes/app/txn-sample.clj

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/155)

Extend/improve the Clojure examples.

---

_includes/app/basic-sample.cpp
_includes/app/txn-sample.cpp

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/146)

adding c++ txn sample

---

_includes/app/txn-sample.cpp
_includes/app/txn-sample.go

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/163)

Go and c++ txn sample improvements - no more inserts

---

_includes/app/BasicSample.java
_includes/app/basic-sample.js
_includes/app/basic-sample.rb
_includes/app/txn-sample.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/162)

Improve app examples

---

build-a-test-app.md

This was messing up copy and paste. The change on line 115 is a trailing new line.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/166)

Fix single quote instead of accent

---

transactions.md

https://www.cockroachlabs.com/docs/transactions.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/148)

 initial content for the transaction's page

---

_includes/app/basic-sample.js
_includes/app/txn-sample.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/167)

Polish node.js example

---

_includes/app/basic-sample.go
_includes/app/txn-sample.go

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/169)

go basic sample

---

build-a-test-app.md

Is this the right language, @andreimatei, @spencerkimball?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/168)

details about go library for retries

---

frequently-asked-questions.md
index.md
manual-deployment.md
secure-a-cluster.md
start-a-local-cluster.md
start-a-node.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/171)

Update version references

---

install-cockroachdb-in-md.md
install-cockroachdb.md

Set the links for the beta binaries.
I'll merge once they've been built and pushed, then we'll need to rebuild and push the docs.
A few other things that we should look into later:
* can we have a parameter somewhere and reuse it? that would be easier and less error-prone
* lots of trailing whitespaces in those files. we tend to avoid those.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/172)

Link to beta binaries

---

transactions.md

Fixing typos and minor tweak to transactions.md.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/181)

fixing typos and other tweaks

---

_includes/app/basic-sample.php

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/154)

Add basic PHP sample

---

_includes/app/basic-sample.js
_includes/app/txn-sample.js
_includes/app/txn-sample.py

Also, @andreimatei would you mind double checking the txn retry logic?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/179)

Re-work Node.js transaction model to support retries

---

build-a-test-app.md
css/components/_filtertabs.scss
css/customstyles.css

New filter tabs for the build test app page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/178)

Build test app filters

---

_includes/app/txn-sample.js

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/187)

Pull commit closure into anonymous function

---

_includes/sql/diagrams/grammar.html
_includes/sql/diagrams/rollback_transaction.html

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/191)

Sync current grammar

---

_includes/sql/functions.md
_includes/sql/operators.md
functions-and-operators.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/196)

Add operator and func docs

---

install-cockroachdb.md

more granular tracking events based on copy events
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/202)

docs: install page | tracking events updates

---

_data/sidebar_doc.yml
release-notes.md

Not sure how to upload this to staging but here's what it looks like.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/203)

Add release notes page

---

start-a-local-cluster.md
troubleshoot.md

Adding troubleshooting recommendations for "replicas failing" errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/204)

troubleshooting content

---

install-cockroachdb-in-md.md
install-cockroachdb.md

Updated build from source and docker instructions to point to latest version.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/208)

build from source and docker install methods for latest beta version

---

_includes/toc.html
_layouts/page.html
css/customstyles.css
css/customstyles.scss

scrolling with some easing
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/212)

anchor link scroll position fix

---

_data/sidebar_doc.yml
beta-20160414.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/218)

Release notes for beta-20160414

---

_data/sidebar_doc.yml
_data/strings.yml
beta-20160414.md
cockroach-commands.md
install-cockroachdb-in-md.md
install-cockroachdb.md
start-a-local-cluster.md
timestamp.md
troubleshoot.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/221)

updates for beta-20160414 release notes

---

_includes/sql/diagrams/alter_table.html
_includes/sql/diagrams/drop.html
_includes/sql/diagrams/drop_index.html
_includes/sql/diagrams/grammar.html
_includes/sql/diagrams/truncate.html
generate/main.go

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/220)

Regenerate grammar diagrams

---

_includes/sql/functions.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/222)

Regenerate function docs

---

cockroach-commands.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/223)

Documenting severity used when --alsologtostderr is set without a value

---

_includes/sql/diagrams/set_transaction.html
generate/main.go

Done with a simple post-production replacement.
See #226
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/228)

Improved SET TRANSACTION display

---

_data/sidebar_doc.yml
beta-20160421.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/234)

Add release notes for beta-20160421

---

Makefile
_includes/sql/diagrams/grammar.html

This week's additions aren't mentioned anywhere but the full grammar.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/236)

Regenerate SQL diagrams

---

_data/strings.yml
beta-20160421.md

Added links and doc updates to beta-20160421 release notes. Also few minor revisions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/238)

rn updates

---

beta-20160421.md

Fixing wrong date in release notes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/239)

fixing wrong date in rn heading

---

_data/sidebar_doc.yml
_data/strings.yml
_includes/sql/operators.md
beta-20160428.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/242)

Release notes for beta 20160428

---

build-a-test-app.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/243)

Fixing invalid link

---

_data/sidebar_doc.yml
beta-20160505.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/265)

Release notes for beta-20160505

---

_includes/hubspot_analytics.html
_layouts/default.html

Fixes #272
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/274)

Adding hubspot analytics code

---

_data/sidebar_doc.yml
beta-20160512.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/289)

Release notes for beta-20160512

---

_includes/sidebar.html
js/customscripts.js
search.html

Fixes #232 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/292)

Track search queries

---

_data/sidebar_doc.yml
beta-20160519.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/303)

Release notes for beta-20160519

---

beta-20160519.md
cockroach-commands.md
timestamp.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/305)

beta-20160519 release note edits

---

_includes/sql/diagrams/grammar.html
_includes/sql/diagrams/insert.html
_includes/sql/diagrams/upsert.html
_includes/sql/operators.md
generate/funcs.go

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/304)

Regenerate grammar diagram

---

timestamp.md

Fixes #309
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/310)

More accurate docs about nanosecond timestamps.

---

_data/sidebar_doc.yml
beta-20160526.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/321)

Beta 20160526 release notes

---

_data/strings.yml
beta-20160526.md
timestamp.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/323)

Adding links and doc updates to release notes

---

_includes/app/txn-sample.py

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/319)

Improve style of python txn example

---

configure-replication-zones.md

Making sure `--join` is used correctly. Also improving the intros for examples. 
Fixes #298
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/327)

Improving zone config examples

---

_includes/app/basic-sample.rs

This sample uses the newly supported Rust driver.
My gift to @tamird and @tschottdorf.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/294)

Add basic Rust sample

---

generate/extract/extract.go

Being done here instead of in sql.y because of test reasons. Hacky, but
will remove later.
Fixes #328
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/340)

Remove joined_table from grammar

---

null-handling.md

@jseldess As requested I've "de-blogged" the narrative of my NULL handling post and created a null-handling page. 
I haven't added this page to the menu as I wasn't sure if you wanted a separate page or the content added to somewhere like the data-definition page.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/333)

Added null-handling page

---

CONTRIBUTING.md

Adding @sploiselle's new **Keep Contributing** section, which helps contributors stay in sync with updates to `cockroachdb/docs`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/344)

Expanding docs CONTRIBUTING.md

---

_includes/google_remarketing.html
_layouts/default.html

Fixes #349
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/350)

remarketing tag in docs footer

---

_includes/sql/diagrams/grammar.html
_includes/sql/operators.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/352)

adding // to operator docs

---

index.md

Fixes #341
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/353)

links to sqlalchemy and consistency checker posts

---

_includes/app/txn-sample.rs

This sample uses the newly supported Rust driver, that now also
supports savepoints.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/326)

Add transaction Rust sample

---

_data/sidebar_doc.yml
beta-20160609.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/365)

beta-20160609 release notes

---

_data/strings.yml

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/366)

updating version and build_time strings in docs

---

_includes/sql/diagrams/create_database.html
create-database.md
generate/main.go

As discussed in #360
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/367)

Add encoding clause to Create Database diagram

---

create-database.md

Required Privileges before Synopsis.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/368)

Reordering sections in CREATE TABLE doc

---

install-cockroachdb.md

Fixes https://github.com/cockroachdb/cockroach/issues/7206
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/381)

Updating required Go version for build from source

---

_includes/sql/diagrams/create_index.html
generate/main.go

In-lined the opt_storing clause.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/382)

Create Index diagram changes

---

_includes/sql/aggregates.md
_includes/sql/functions.md
generate/funcs.go

this makes the generated TOC at the top include quick links to e.g. all the functions that return strings
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/386)

add subheadings for each group of functions

---

.gitignore

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/388)

ignore 'generate' binary written by 'go build'

---

_data/sidebar_doc.yml
beta-20160616.md
older-versions.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/391)

Release notes for beta-20160616

---

_data/strings.yml
beta-20160616.md

Adding links and doc updates.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/393)

Release note edits

---

_data/strings.yml
_includes/sql/diagrams/explain.html
_includes/sql/diagrams/grammar.html
configure-replication-zones.md

- Updated build time in `strings.yml`. 
- Regenerated grammar diagrams.
- Added `ttlseconds` to `configure-replication-zones.md`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/395)

Build time update

---

beta-20160616.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/396)

Fixing broken link in release notes and other tweaks

---

frequently-asked-questions.md

Listing Rust as supported language, and adding link to page on transactions.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/399)

Minor FAQ updates

---

_includes/check_warning.html
constraints.md
null-handling.md

cockroachdb/cockroach#7311 fixed the issue with renames
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/402)

remove warning about renaming cols in CHECK

---

rename-column.md

We neglected to do this in PR #402

Remove check warning include from rename-column.md

---

learn-cockroachdb-sql.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/412)

Fix link to identifiers

---

CONTRIBUTING.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/419)

Adding CircleCI details to docs CONTRIBUTING.md

---

index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/420)

Adding new blog posts to docs home

---

_includes/sql/diagrams/begin_transaction.html
_includes/sql/diagrams/iso_level.html
begin-transaction.md
generate/main.go

My first PR following the new [CONTRIBUTING](https://github.com/cockroachdb/docs/blob/gh-pages/CONTRIBUTING.md) guidelines. (`html-proofer` took a while on my system but completed successfully.)
This one may require some discussion as I've included the **iso_level** production which, I my mind, doesn't match the documentation/blogs around transaction isolation levels in CockroachDB. 
Parts of it might need some `unimplemented()` or `SKIP_DOC` or something in the grammar file.
I haven't done the Basic/Expanded thing with the iso_level diagram because it was only the one diagram. Let me know if you want it and I'll add the JavaScript.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" …

Expand Begin Transaction diagram

---

install-cockroachdb.md

Fixes #421
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/428)

RAM requirement for building from source

---

install-cockroachdb.md

Fixes docs-part of https://github.com/cockroachdb/cockroach/issues/7698
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/442)

add bash as install requirement

---

_includes/sql/diagrams/create_database.html
_includes/sql/diagrams/create_index.html
generate/main.go

Fixes #375
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/440)

Unlink some things

---

_includes/sql/diagrams/commit_transaction.html
generate/main.go

Added the 'END' keyword to the diagram. Hopefully that's the full syntax ready to be documented.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/445)

Added END keyword to COMMIT syntax diagram

---

_data/sidebar_doc.yml
beta-20160714.md
older-versions.md

cockroachdb/cockroach#7804
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/453)

Release notes for beta-20160714

---

_data/sidebar_doc.yml
manual-deployment.md
recommended-production-settings.md

This PR adds a page with cluster topology, clock synchronization, and file descriptor limit recommendations for production deployments. 
This aims to fix #53 and is a start for #436.
HTTP version available here: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/7ccfa14b230bce596d6aaa73ccc78761ea1e015c/recommended-production-settings.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/449)

Recommended production settings

---

_data/sidebar_doc.yml
_data/strings.yml
_includes/sql/diagrams/grammar.html
_includes/sql/diagrams/update.html
beta-20160714.md
cockroach-commands.md
column-families.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/455)

Release note updates

---

_includes/footer.html

Fixes #458 
@jess-edwards
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/460)

update footer to match rest of site

---

recommended-production-settings.md

Adding steps to increase the open files limit on various versions of Mac and Linux. 
HTML version: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/68be398a1c4cb808f6bba4678c4ca678b37e5923/recommended-production-settings.html
Fixes #436
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/459)

steps to increase the open files limit

---

explore-the-admin-ui.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/477)

coming soon message on admin ui docs

---

recommended-production-settings.md

Updating recommendation about clock synchronization based on comments here: https://github.com/cockroachdb/cockroach/issues/4884#issuecomment-235058307
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/483)

update recommendation about clock syncing

---

install-cockroachdb.md

A best practice after installing a piece of software is running `software version` to make sure it's actually there. Adding that command (`cockroach version`) to `install-cockroachdb.md` for each version of the installation.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/485)

Verify Installation

---

back-up-and-restore-data.md

Fixes #511
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/512)

dump checks that user has select privilege

---

install-cockroachdb.md

Updating CockroachDB install verification step for Docker.
@sploiselle, PTAL. We seem to have missed this update in your PR: https://reviewable.io/reviews/cockroachdb/docs/485#-KNbVD8tNX0R_BKk0whW
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/515)

verify install step for docker

---

_data/sidebar_doc.yml
beta-20160728.md
older-versions.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/514)

Release notes for beta-20160728

---

_includes/footer.html
css/_footer.scss
css/_variables.scss
css/components/_filtertabs.scss
css/customstyles.css
css/customstyles.scss
css/lavish-bootstrap.css
js/customscripts.js

new footer w/updated sass files
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/517)

New footer

---

_data/strings.yml
_includes/sql/diagrams/grammar.html
_includes/sql/diagrams/table_constraint.html
_includes/sql/operators.md
beta-20160728.md

Added links and doc updates to release notes, and regenerated SQL diagrams and functions docs.
@bdarnell, PTAL.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/519)

update release notes

---

install-cockroachdb.md

Fixes #516
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/522)

add missing p tag

---

Gemfile
create-index.md
create-table.md
indexes.md
learn-cockroachdb-sql.md

This PR contains:
- First draft of `CREATE INDEX` statement
- Additions to Indexes doc, including information on how indexes work and best practices.
- Links to the other documents from `CREATE TABLE`
- We agreed in the related issue to include a section about __How do indexes work?__ However, after multiple rewrites I had a nigh impossible time gracefully ending it without leading into some kind of __Best Practices__, so they're in there. Originally some of this guidance was in `CREATE INDEX`, but I think this is a better place for it so it can get repurposed in `CREATE TABLE`.
- __Best Practices__ could use some kind of vouch from a DBA/dev. I did a healthy amount of research to come up with these but you never know. For instance – the limit of number of columns to use in an index is …

Create Index, Indexes docs

---

frequently-asked-questions.md

added JSON, JOIN, and bulk insert FAQ
@knz – Could I get you to take a quick look at the mentions I made of `JOIN` here? I wasn't sure if we could remove it as a limitation or not.
@paperstreet – Could I get you to review the JSON/bulk insert mentions? Feel free to loop in anyone else who ought to review.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/533)

adding FAQ

---

_includes/sql/diagrams/drop_index.html
generate/main.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/538)

updating DROP INDEX diagram

---

constraints.md
create-table.md

Adding foreign key constraint info to relevant docs. Will follow up with additional documentation on removing foreign keys using `DROP INDEX`.
@dt – Could I get you to check this out for me?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/528)

Foreign Key docs

---

drop-index.md

Closes #536 
Closes #258
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/540)

DROP INDEX doc

---

_data/sidebar_doc.yml
_includes/sql/diagrams/show_constraints.html
constraints.md
generate/main.go
show-constraints.md
sql-statements.md

This PR adds docs on the `SHOW CONSTRAINT` statement. Fixes #521.
HTML version here: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/ac93df39a27eed858da4f66cb1379724cd98ff2d/show-constraints.html
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/520)

docs on show constraints statement

---

recommended-production-settings.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/554)

Increasing number of max open FD's through Systemd

---

recommended-production-settings.md

Minor edits to language added in https://github.com/cockroachdb/docs/pull/554
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/565)

minor edit to docs on file descriptor limits

---

start-a-local-cluster-in-docker.md

Fixes #566
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/567)

Fix errors in docker commands

---

index.md

Fixes #555
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/569)

docs: add link to new blog post

---

build-a-test-app.md
secure-a-cluster.md
start-a-local-cluster-in-docker.md
start-a-local-cluster.md

This PR corrects the step numbers in `start-a-local-cluster`, adds a TOC to a few pages, moves some JS to the bottom of files, and makes a few other minor text changes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/586)

docs: numbering and other minor fixes

---

build-a-test-app.md

This PR adds the php transaction sample to `build-a-test-app.md` (finally).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/588)

docs: add php txn sample

---

css/customstyles.css
css/layouts/_header.scss

tablet layout fix
line height adjustments
sass code refactoring
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/592)

nav updates

---

_data/strings.yml
beta-20160829.md
install-cockroachdb.md

Add links and doc updates to beta-20160829 release notes
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/594)

docs: update beta release notes

---

start-a-local-cluster-in-docker.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/595)

fixing broken table in start-a-local-cluster-in-docker.md

---

manual-deployment.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/615)

fix typo of username. see https://github.com/cockroachdb/docs/issues/613

---

_data/sidebar_doc.yml
beta-20160908.md
older-versions.md

cockroachdb/cockroach#9198
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/633)

Release notes for beta-20160908

---

_data/sidebar_doc.yml
_data/strings.yml
beta-20160908.md
cockroach-commands.md
install-cockroachdb.md

Adding links and doc updates. 
@jordanlewis, please let me know when the binaries are ready and I'll publish.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/635)

beta-20160908 release note updates

---

beta-20160908.md

Adding one more doc update to beta-20160908 release notes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/636)

Add doc update to beta-20160908 release notes

---

deploy-cockroachdb-on-aws.md
deploy-cockroachdb-on-google-cloud-platform.md

Deploy CockroachDB on AWS.
@mberhault – Could I get you to review for me?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/640)

AWS manual deploy

---

_includes/footer.html

Fixes #658
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/659)

Change Email to Contact Us in footer

---

beta-20160407.md
beta-20160414.md
beta-20160421.md
beta-20160428.md
beta-20160505.md
beta-20160512.md
beta-20160519.md
beta-20160526.md
beta-20160602.md
beta-20160609.md
beta-20160616.md
beta-20160629.md
beta-20160714.md
beta-20160721.md
beta-20160728.md
beta-20160829.md
beta-20160908.md
deploy-cockroachdb-on-google-cloud-platform.md
install-cockroachdb.md

broken binary links, emergency fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/663)

temporary URL for binaries at HTN

---

_includes/google_remarketing.html
_layouts/default.html
css/customstyles.css
css/layouts/_footer.scss

- fixes white space on bottom of page caused by conflict between gitter plugin and the google remarketing tag
- adds bottom padding to footer so that gitter button doesn’t land on footer newsletter form
- include footer in content div in order to push everything to side when opening mobile nav
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/673)

Visual bugs

---

install-cockroachdb.md

Fixes #665
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/684)

Update required go version for building from source

---

generate/extract/extract.go
generate/extract/extract_test.go
generate/main.go

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/695)

Refactor extract to optionally split productions

---

_includes/sql/diagrams/rename_index.html
generate/main.go
rename-index.md

Documents `RENAME INDEX`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/679)

RENAME INDEX doc

---

_data/sidebar_doc.yml
automated-scaling-and-repair.md
distributed-transactions.md
go-implementation.md
high-availability.md
open-source.md
simplified-deployment.md
sql.md
strong-consistency.md

Fixes #697 
HTML here: http://cockroach-docs-review.s3-website-us-east-1.amazonaws.com/df9a869f1fd5db0f829182656b2bc86c238daab0/high-availability.html
@jess-edwards, PTAL
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/699)

Distinct page for each feature

---

_data/sidebar_doc.yml
beta-20160929.md
older-versions.md

As of cockroachdb/cockroach@980c6fe. See cockroachdb/cockroach#9583
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/693)

Draft release notes for beta-20160929

---

_data/strings.yml
beta-20160407.md
beta-20160414.md
beta-20160421.md
beta-20160428.md
beta-20160505.md
beta-20160512.md
beta-20160519.md
beta-20160526.md
beta-20160602.md
beta-20160609.md
beta-20160616.md
beta-20160629.md
beta-20160714.md
beta-20160721.md
beta-20160728.md
beta-20160829.md
beta-20160908.md
beta-20160929.md
deploy-cockroachdb-on-aws.md
deploy-cockroachdb-on-google-cloud-platform.md
install-cockroachdb.md
manual-deployment.md
secure-a-cluster.md
start-a-local-cluster.md
start-a-node.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/701)

beta-20160929 release note updates

---

generate/main.go

Fixes #700
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/706)

Allow relinking

---

orchestrate-cockroachdb-with-kubernetes.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/709)

Develop -> master links

---

_data/strings.yml
_includes/sidebar.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/707)

Remove unused strings

---

css/customstyles.css
css/layouts/_header.scss

spacing updates
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/711)

nav spacing

---

_includes/back-to-top.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/717)

Only show top scroll button on long pages after scroll up

---

start-a-local-cluster-in-docker.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/721)

Fix links to docker

---

beta-20160929.md

Part of #731
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/732)

fixing install tracking on release notes

---

css/customstyles.css
css/customstyles.scss

Fixes #719
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/742)

Restore pre overflow

---

CONTRIBUTING.md

Adding greater description for using notes, warnings, and tips.
@jseldess Pretty minor; take a quick look? Also think it closes an old issue.
Closes #48
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/744)

added paragraph highlighting (e.g., notes) details

---

_data/sidebar_doc.yml
_includes/sql/diagrams/alter_table.html
_includes/sql/diagrams/create_index.html
_includes/sql/diagrams/create_table.html
_includes/sql/diagrams/delete.html
_includes/sql/diagrams/grammar.html
_includes/sql/diagrams/index_def.html
_includes/sql/diagrams/interleave.html
_includes/sql/diagrams/opt_interleave.html
_includes/sql/diagrams/table_constraint.html
constraints.md
create-table.md
data-definition.md
generate/main.go
interleave-in-parent.md

Document for `CREATE TABLE... INTERLEAVE IN PARENT...`
Includes updates to SQL Grammar for supporting `INTERLEAVE`
@paperstreet Can you review to make sure this is in the right direction?
Closes #465
- Need to expand document to include interleaving secondary indexes.
- Change nav structure related to #622
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/632)

Interleave tables

---

_data/sidebar_doc.yml
_includes/sql/diagrams/create_table_as.html
create-table-as.md
generate/main.go
sql-statements.md

Documents `CREATE TABLE AS` in SQL.
Closes #598
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/752)

CREATE TABLE AS SQL statement

---

_data/sidebar_doc.yml
cockroach-commands.md
generate-cli-utilities-and-example-data.md

Documents `cockroach gen`.
Closes #98
Closes #648
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/755)

cockroach gen docs

---

_data/sidebar_doc.yml
manual-deployment.md
orchestrate-cockroachdb-with-docker-swarm.md
orchestrate-cockroachdb-with-kubernetes.md
orchestration.md

This PR adds documentation on orchestrating CockroachDB with Docker Swarm. It also adds an overview page on Orchestration listing Swarm and Kubernetes.
Fixes #185
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/676)

Running CockroachDB with Docker Swarm

---

beta-20161013.md

Add empty line so bulleted list renders properly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/759)

Fix list of contributors in beta-20161013 release notes

---

orchestrate-cockroachdb-with-docker-swarm.md
orchestrate-cockroachdb-with-kubernetes.md

This PR updates our Kubernetes-specific docs to focus on cloud deployments. 
Fixes #677
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/727)

cockroachdb and kubernetes in the cloud

---

configure-replication-zones.md

Fixes #762
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/763)

Fix typos in replication zone examples

---

_includes/sql/diagrams/select.html
generate/main.go
select.md

Covers `SELECT`. I'd like to add more examples to the document, but this is sufficient to get started.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/726)

SELECT SQL statement

---

_data/sidebar_doc.yml
cloud-deployment.md
deploy-cockroachdb-on-aws.md
deploy-cockroachdb-on-digital-ocean.md
deploy-cockroachdb-on-google-cloud-platform.md

Does exactly what it says on the tin.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/758)

Digital Ocean insecure deployment

---

distributed-transactions.md
frequently-asked-questions.md
strong-consistency.md

Remove mention of two-phases commit from `distributed-transactions.md`, and clarify language around strong consistency in `strong-consistency.md` and in `frequently-asked-questions.md`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/786)

Minor edits to features pages and FAQ

---

_data/sidebar_doc.yml
beta-20161027.md
older-versions.md

As of cockroachdb/cockroach@7b94b9a.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/784)

Draft release notes for beta-20161027

---

show-create-view.md

To reflect https://github.com/cockroachdb/cockroach/issues/10245 getting fixed.
Shouldn't be merged until after https://github.com/cockroachdb/cockroach/pull/10270.
@jseldess
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/797)

Update SHOW CREATE VIEW privileges section

---

insert.md

This PR adds Go- and python-specific examples for `INSERT ... RETURNING`.
Fixes #805 
Fixes #766 
@knz, @spencerkimball
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/813)

RETURNING example in python and go

---

_data/sidebar_doc.yml
beta-20161103.md
older-versions.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/820)

Release notes for beta-20161103

---

_includes/footer.html

Under **Company**, remove **Events** and add **Security**.
Fixes #825
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/826)

Link to security page from footer

---

cloud-deployment.md
deploy-cockroachdb-on-aws-insecure.md
deploy-cockroachdb-on-digital-ocean-insecure.md
deploy-cockroachdb-on-google-cloud-platform-insecure.md
deploy-cockroachdb-on-google-cloud-platform.md
manual-deployment.md

Includes 
- GCE secure deployment
- AWS secure deployment
- Digital Ocean secure deployment
- Updated overview 
- Change to site's information architecture to favor secure deployments
Closes #775, #776, #777
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/821)

Secure cloud deployments

---

install-client-drivers.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/833)

htmlproofer ignores link to crates.io

---

_data/sidebar_doc.yml
beta-20161110.md
older-versions.md

As of commit cockroachdb/cockroach@954063f7
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/835)

Draft release notes for beta-20161110

---

_data/sidebar_doc.yml
information-schema.md
show-columns.md
show-constraints.md
show-create-table.md
show-create-view.md
show-database.md
show-databases.md
show-grants.md
show-index.md
show-tables.md
sql-feature-support.md

Documents `information_schema` table
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/859)

Information Schema

---

index.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/879)

recent-posts: fix typo.

---

index.md

Add links to recent blog posts, and make "Recent Blog Post" a link to cockroachlabs.com/blog.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/881)

Update blog links on docs home

---

demo-data-replication.md
demo-fault-tolerance-and-recovery.md

demonstration not demonstratation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/886)

Fix spelling error

---

demo-data-replication.md

Previously, the roach was elongated. Added the relevant where clause to correct the issue.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/889)

Fix mytable roach in data replication demo

---

constraints.md

Documents that creating a table with a foreign key now automatically creates an index for you.
Also removes reference about foreign key dependency on index, which is no longer true.
@dt Can I get you to review for technical accuracy?
Closes #832
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/895)

Foreign Key auto index creation

---

_data/sidebar_doc.yml
deploy-cockroachdb-on-aws-insecure.md
deploy-cockroachdb-on-digital-ocean-insecure.md
deploy-cockroachdb-on-digital-ocean.md
deploy-cockroachdb-on-google-cloud-platform.md
deploy-cockroachdb-on-microsoft-azure-insecure.md
deploy-cockroachdb-on-microsoft-azure.md

Covers both secure and insecure deployments, as well as adding necessary links.
Closes #510
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/893)

Azure deployments

---

configure-replication-zones.md
interleave-in-parent.md
troubleshoot.md

This PR updates zone config and troubleshooting docs to use the new zone config format. 
These docs will be updated more extensively once expressive zone config changes have been finalized.
Fixes #649
Fixes #897
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/902)

Zone config format

---

_data/sidebar_doc.yml
beta-20161201.md
older-versions.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/905)

Release notes for beta-20161201

---

_data/sidebar_doc.yml
beta-20161207.md

As of cockroachdb/cockroach@b4d3d7054
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/911)

Release notes for beta-20161207

---

_includes/sql/aggregates.md
_includes/sql/functions.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/915)

_includes: regen function docs

---

_data/sidebar_doc.yml
beta-20161208.md
beta-20161215.md
older-versions.md

As of cockroachdb/cockroach@5596982
@knz, were any of your join changes user-facing or is it all in preparation for distsql?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/923)

Draft release notes for beta-20161215

---

index.md

Add links to new blog posts on docs homepage.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/929)

Update links to blog

---

_data/sidebar_doc.yml
_includes/prometheus-callout.html
cloud-deployment.md
deploy-cockroachdb-on-aws-insecure.md
deploy-cockroachdb-on-aws.md
deploy-cockroachdb-on-digital-ocean-insecure.md
deploy-cockroachdb-on-digital-ocean.md
deploy-cockroachdb-on-google-cloud-platform-insecure.md
deploy-cockroachdb-on-google-cloud-platform.md
deploy-cockroachdb-on-microsoft-azure-insecure.md
deploy-cockroachdb-on-microsoft-azure.md
manual-deployment.md
monitor-cockroachdb-with-prometheus.md
orchestration.md
start-a-local-cluster.md

This PR adds docs on monitoring CockroachDB with Prometheus. It also covers connecting Grafana and Alertmanager to Prometheus for visualizations and notifications.
Fixes #469
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/928)

Prometheus

---

build-a-test-app.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/931)

correct command is cockroach user not cockroach users

---

create-and-manage-users.md
create-user.md

Closes #930
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/938)

Clarify root user cannot use password authentication

---

orchestrate-cockroachdb-with-kubernetes.md

Fixes #932 
Merge needs to wait on https://github.com/cockroachdb/cockroach/pull/12536
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/940)

Update Kuberentes doc to 1.5 (StatefulSets)

---

orchestrate-cockroachdb-with-kubernetes.md

Fixes #946
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/947)

Add poddisruptionbudget to kubectl delete command

---

_includes/sql/aggregates.md
_includes/sql/functions.md
_includes/sql/operators.md
generate/funcs.go

Closes #19
Need to have the descriptions copy edited before merging cockroachdb/cockroach#12533
Also:
Closes #945
Closes #944 
Closes #943 
Closes #942 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/948)

Descriptions for Functions & Operators

---

orchestrate-cockroachdb-with-kubernetes.md

Another feature that's been improved since this example was created
https://github.com/cockroachdb/cockroach/pull/12584
@jseldess

kubernetes: Use scale command instead of patch

---

constraints.md
create-index.md
foreign-key.md
information-schema.md
primary-key.md
show-transaction.md

Fixes #954
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/956)

Shorten meta descriptions to under 156 characters

---

_data/sidebar_doc.yml
beta-20170105.md
older-versions.md

As of cockroachdb/cockroach@5b28afe7d
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/958)

Release notes for beta-20170105

---

select.md

Closes #953 
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/967)

`FILTER` clause in `SELECT`'s `target_elem`

---

beta-20170105.md

Capitalize Raft in beta-20170105 release notes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/973)

Capitalize Raft in beta-20170105 release notes

---

bytes.md
decimal.md
string.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/975)

Fixed typo "degredation"

---

_data/sidebar_doc.yml
beta-20170112.md
older-versions.md

cockroachdb/cockroach#12849
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/986)

Release notes for beta-20170112

---

bool.md
bytes.md
data-types.md
date.md
decimal.md
float.md
int.md
interval.md
serial.md
string.md
timestamp.md

Closes #51
Closes #282
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/977)

SQL type conversion details

---

information-schema.md

Closes #1006
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1007)

typo: "implementation" 

---

back-up-and-restore-data.md
create-and-manage-users.md
use-the-built-in-sql-client.md
view-node-details.md

Fix #998.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1000)

Clarify handling of --pretty

---

beta-20170112.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1012)

Add a warning to beta-20170112

---

_data/sidebar_doc.yml
collate.md
data-types.md
sql-feature-support.md
string.md

closes #847
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/974)

support for collated strings

---

_data/sidebar_doc.yml
beta-20170112.md
beta-20170126.md
older-versions.md

Still TODO: the rule solver.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1029)

Release notes for beta-20170126

---

configure-replication-zones.md

Fix bullets and spelling errors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1031)

Zone doc fixes

---

collate.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1033)

Grammar fix in collate.md

---

deploy-cockroachdb-on-aws-insecure.md
deploy-cockroachdb-on-aws.md
deploy-cockroachdb-on-digital-ocean-insecure.md
deploy-cockroachdb-on-digital-ocean.md
deploy-cockroachdb-on-google-cloud-platform-insecure.md
deploy-cockroachdb-on-google-cloud-platform.md
deploy-cockroachdb-on-microsoft-azure-insecure.md
deploy-cockroachdb-on-microsoft-azure.md
orchestrate-cockroachdb-with-docker-swarm.md

Link fixes in cloud deployment and docker swarm tutorials. Grammar fix in swarm tutorial as well.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1035)

Link fixes

---

_includes/sql/diagrams/create_database.html
_includes/sql/diagrams/grammar.html
_includes/sql/diagrams/truncate.html
generate/main.go

It just got renamed to targets. Also regen diagrams.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1032)

fix for privilege_target

---

sql-expressions.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1036)

Add missing doc for searched CASE expressions.

---

delete.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1051)

update link to DROP COLUMN doc

---

_includes/newsletter-popout.html

Moved email sign up form to pop up at 75% of page height instead of at very bottom
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1024)

move footer email pop up

---

sql-feature-support.md

Fixes #1015
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1055)

Update SQL feature support page to link to ALTER TABLE substatements

---

_includes/footer.html

Closes #1064
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1065)

Add pricing page link to footer

---

_includes/app/basic-sample.rb
_includes/app/txn-sample.rb
build-a-test-app.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1068)

ruby: add txn-sample

---

_includes/app/sqlalchemy-basic-sample.py

As much as possible, this mirrors the structure of
`gorm-basic-sample.go`. Tested with Python 2.7.x & Python 3.5.x.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1071)

Basic sample for SQLAlchemy

---

_includes/footer.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1075)

updating footer copyright date to 2017

---

build-a-go-app-with-cockroachdb.md

Currently doesn't persist on TOC clicks, but it's a start.
Fixes #1074
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1077)

add ability to link to the orm page with `#orm` in the URL

---

_data/sidebar_doc.yml
beta-20170209.md
older-versions.md

See cockroachdb/cockroach#13480
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1080)

beta-20170209 release notes

---

_includes/sql/diagrams/explain.html
explain.md
generate/main.go

Closes #430
Also includes some work from #794
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1073)

EXPLAIN SQL doc

---

build-a-go-app-with-cockroachdb.md
build-a-python-app-with-cockroachdb.md

This is so we can properly track clicks on driver and orm buttons on "build an app" tutorials.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1099)

Add data-tool class to strong tags

---

recommended-production-settings.md

Fixes #1083
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1084)

Update minimum file descriptors limit

---

show-all.md
sql-name-resolution.md

Fixes #1092 
Fixes #1093
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1104)

SET SEARCH_PATH and return current user for SHOW ALL

---

_data/sidebar_doc.yml
_includes/sql/aggregates.md
_includes/sql/diagrams/grammar.html
_includes/sql/diagrams/select.html
_includes/sql/diagrams/truncate.html
_includes/sql/functions.md
beta-20170216.md
generate/funcs.go
older-versions.md
recommended-production-settings.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1103)

Release notes for beta-20170216

---

generate/extract/extract.go

My laptop is much more pleasant to use when it's not trying to start
dozens of JVMs at the same time. Total running time of `make generate`
is roughly unchanged.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1105)

generate: Limit the number of concurrent java processes

---

build-a-python-app-with-cockroachdb.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1106)

Fixed a typo in the python docs

---

_data/sidebar_doc.yml
beta-20170223.md
older-versions.md

cockroachdb/cockroach#13717
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1111)

Release notes for beta-20170223

---

index.md

Should be *Kuan Luo*.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1113)

typo: Kuan Lo

---

beta-20170209.md
frequently-asked-questions.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1112)

typo: highly availability

---

orchestrate-cockroachdb-with-docker-swarm.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1137)

Grammar fix in Docker Swarm tutorial

---

_data/sidebar_doc.yml
_includes/sidebar.html
build-a-go-app-with-cockroachdb-gorm.md
build-a-go-app-with-cockroachdb.md
build-a-java-app-with-cockroachdb-hibernate.md
build-a-java-app-with-cockroachdb.md
build-a-python-app-with-cockroachdb-sqlalchemy.md
build-a-python-app-with-cockroachdb.md
cloud-deployment.md
deploy-cockroachdb-on-aws-insecure.md
deploy-cockroachdb-on-aws.md
deploy-cockroachdb-on-digital-ocean-insecure.md
deploy-cockroachdb-on-digital-ocean.md
deploy-cockroachdb-on-google-cloud-platform-insecure.md
deploy-cockroachdb-on-google-cloud-platform.md
deploy-cockroachdb-on-microsoft-azure-insecure.md
deploy-cockroachdb-on-microsoft-azure.md
manual-deployment-insecure.md
manual-deployment.md

- Split driver/orm instructions into separate pages
- Split secure and insecure manual deployment into two pages
- Make sidebar recognize alternate URLs at second level
- Add alternate urls to sidebar
- Reformat intro of cloud deployment tutorials
Fixes #1133
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1135)

Use distinct pages, not JS, for page variations

---

serial.md

Fixes #1140
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1146)

Remove "experimental" disclaimer from SERIAL docs

---

back-up-and-restore-data.md

This PR updates the `cockroach dump` docs to cover the new `--as-of` flag:
- Intro revised slightly
- Flag added
- Example added
Fixes #1138
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1145)

Update cockroach dump docs to cover --as-of flag

---

orchestrate-cockroachdb-with-docker-swarm.md

@jseldess
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1156)

Fix minor typo

---

_data/sidebar_doc.yml
beta-20170309.md
older-versions.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1158)

beta-20170309 release notes

---

back-up-and-restore-data.md

Fixes #1155
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1159)

Add disclaimer to cockroach dump docs

---

install-cockroachdb.md

Fixes #1163
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1167)

Docker for Windows requirements and links

---

CONTRIBUTING.md
_layouts/default.html
install-cockroachdb.md
start-a-local-cluster-in-docker.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1178)

fix HTML proofer for internal link to os toggle

---

import-data.md

Remove extra "from" in first sentence of `import-data.md`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1188)

Remove repeated word

---

_data/sidebar_doc.yml
deploy-cockroachdb-on-aws.md
deploy-cockroachdb-on-digital-ocean.md
deploy-cockroachdb-on-google-cloud-platform.md
deploy-cockroachdb-on-microsoft-azure.md
manual-deployment.md
orchestrate-cockroachdb-with-docker-swarm-insecure.md
orchestrate-cockroachdb-with-docker-swarm.md

This PR breaks the swarm tutorial into two pages, one for secure orchestration and the other for insecure orchestration. For secure orchestration, the main difference is the creation and use of certs and Docker secrets.
Fixes #876
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1184)

Secure orchestration with Docker Swarm

---

learn-cockroachdb-sql.md
show-databases.md

Fixes #1169
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1202)

Update SQL statement responses

---

_data/sidebar_doc.yml
beta-20170323.md
older-versions.md

See cockroachdb/cockroach#14320. Replaces #1198.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1214)

Release notes for beta-20170323

---

_includes/app/sequelize-basic-sample.js

Mirrors other ORM sample code.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1221)

Sequelize sample for "Build an App"

---

_data/sidebar_doc.yml
build-a-nodejs-app-with-cockroachdb-sequelize.md
build-a-nodejs-app-with-cockroachdb.md
build-a-python-app-with-cockroachdb-sqlalchemy.md
build-an-app-with-cockroachdb.md

This PR splits the node.js "build a test" app tutorial into 2, one featuring the pq driver, one featuring Sequelize.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1225)

Add Sequelize tutorial

---

_includes/app/activerecord-basic-sample.rb

This can be run via `ruby activerecord-basic-sample.rb` once
the ActiveRecord, pg and activerecord-cockroachdb-adapter gems are
installed. That can be done via
`gem install activerecord pg activerecord-cockroachdb-adapter`.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1232)

Add ActiveRecord basic sample.

---

_data/sidebar_doc.yml
build-a-go-app-with-cockroachdb-gorm.md
build-a-java-app-with-cockroachdb-hibernate.md
build-a-nodejs-app-with-cockroachdb-sequelize.md
build-a-python-app-with-cockroachdb-sqlalchemy.md
build-a-ruby-app-with-cockroachdb-activerecord.md
build-a-ruby-app-with-cockroachdb.md
build-an-app-with-cockroachdb.md

Expand Ruby "build an app" tutorial to offer usage of pg driver or Active Record ORM.
Fixes #547 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1234)

Active Record tutorial

---

_includes/twitter_analytics.html
_layouts/default.html
build-a-c++-app-with-cockroachdb.md
build-a-clojure-app-with-cockroachdb.md
build-a-go-app-with-cockroachdb-gorm.md
build-a-go-app-with-cockroachdb.md
build-a-java-app-with-cockroachdb-hibernate.md
build-a-java-app-with-cockroachdb.md
build-a-nodejs-app-with-cockroachdb-sequelize.md
build-a-nodejs-app-with-cockroachdb.md
build-a-php-app-with-cockroachdb.md
build-a-python-app-with-cockroachdb-sqlalchemy.md
build-a-python-app-with-cockroachdb.md
build-a-ruby-app-with-cockroachdb-activerecord.md
build-a-ruby-app-with-cockroachdb.md
build-a-rust-app-with-cockroachdb.md
build-an-app-with-cockroachdb.md
index.md

- to docs home
- to "build an app" tutorials
Fixes #1238
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1240)

Add Twitter pixel

---

set-transaction.md
show-transaction.md

Fixes #1237
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1242)

SHOW TRANSACTION only possible within a transaction

---

install-cockroachdb.md

Fixes #1209
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1244)

Update build from source instructions

---

_includes/app/basic-sample.js
build-a-nodejs-app-with-cockroachdb.md

From nwHacks feedback; add steps to install `async` to get app working.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1212)

adding async install to nodejs app

---

build-a-c++-app-with-cockroachdb.md
build-a-clojure-app-with-cockroachdb.md
build-a-go-app-with-cockroachdb.md
build-a-java-app-with-cockroachdb.md
build-a-nodejs-app-with-cockroachdb.md
build-a-php-app-with-cockroachdb.md
build-a-python-app-with-cockroachdb.md
build-a-ruby-app-with-cockroachdb.md
build-a-rust-app-with-cockroachdb.md
build-an-app-with-cockroachdb.md

Make sequence explicit in "run code" step.
Fixes #1215
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1246)

Clarify driver-specific build an app tutorials

---

build-a-go-app-with-cockroachdb.md

Fixes #1250
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1251)

Fix broken include in build a go app tutorial

---

_includes/sql/functions.md
generate/funcs.go

regenerate funcs
Fixes #1258
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1259)

ignore pg compat functions

---

set-transaction.md
show-transaction.md

This reverts commit d2bfa92354a37d636aaf4ae6d18ad383c6ea32ba.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1262)

Revert "SHOW TRANSACTION only possible within a transaction"

---

_includes/app/basic-sample.clj
_includes/app/project.clj
_includes/app/txn-sample.clj
_includes/app/util.clj
build-a-clojure-app-with-cockroachdb.md

Fixes https://github.com/cockroachdb/cockroach/issues/7912.
Fixes #646.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1263)

Update the Clojure examples.

---

create-and-manage-users.md
create-user.md

Fixes #1236
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1270)

Add rules for SQL usernames

---

upsert.md

Fixes #1268
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1269)

Note case when UPSERT is faster than INSERT ON CONFLICT

---

_includes/app/basic-sample.go
_includes/app/txn-sample.go
insert.md

Fixing issue mentioned in #1272
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1286)

making log.Fatal references consistent

---

begin-transaction.md
build-a-c++-app-with-cockroachdb.md
build-a-clojure-app-with-cockroachdb.md
build-a-go-app-with-cockroachdb.md
build-a-java-app-with-cockroachdb.md
build-a-nodejs-app-with-cockroachdb.md
build-a-php-app-with-cockroachdb.md
build-a-python-app-with-cockroachdb.md
build-a-ruby-app-with-cockroachdb.md
build-a-rust-app-with-cockroachdb.md
cockroachdb-in-comparison.md
distributed-transactions.md
frequently-asked-questions.md
transactions.md

Fixes #1117
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1139)

Fix language in documentation referring to txn retries

---

CONTRIBUTING.md
create-index.md
create-table.md
drop-index.md
rename-index.md
select.md
show-index.md

- Add Implicit column to all examples
- Other minor fixes
Fixes #1201
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1271)

Update SHOW INDEX docs

---

orchestrate-cockroachdb-with-kubernetes.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1298)

Remove links to non-existent minikube docs

---

demo-fault-tolerance-and-recovery.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1299)

Fix nodes referenced in `quit` step

---

truncate.md

Fixes #655 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1297)

Add CASCADE to TRUNCATE docs

---

beta-20170420.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1313)

Edit to try and force a cache refresh

---

_includes/newsletter-popout.html

Fixes #1308
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1320)

Prevent popup from opening on mobile

---

porting-postgres.md

Should've caught these fixes when reviewing https://github.com/cockroachdb/docs/pull/1328
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1332)

Minor formatting fixes in Porting from PostgreSQL

---

functions-and-operators.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1322)

Document operator operation and precedence

---

start-a-local-cluster-in-docker.md
start-a-local-cluster.md

Fixes #1345
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1346)

Fix link text

---

_data/sidebar_doc.yml
_data/strings.yml
v1.0-rc.1.md

- Change url and page name to match actual version name
- Change version string to match actual version name
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1355)

Fix version name in docs

---

sql-faqs.md

Fixes #1066
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1359)

Add FAQ on logging SQL queries

---

transactions.md

Just made a small grammar fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1378)

small fix to transactions.md

---

v1.0-rc.2.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1380)

Fix bullet in release notes

---

install-cockroachdb.md

Fixes #1377
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1379)

Minimum Windows version for Windows binary

---

install-cockroachdb.md

Follow-up from #1379.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1384)

Install: clarify language of Windows version requirement

---

upgrade-cockroach-version.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1388)

typo on rolling upgrade page

---

known-limitations.md

Follow up from #1381 to document https://github.com/cockroachdb/cockroach/issues/13027
@jseldess
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1390)

Improve known limitation about restoring a backup onto new machines

---

_includes/diagnostics-callout.html
install-cockroachdb.md

Fixes #1386
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1389)

Disclose diagnostics reporting on install page

---

install-cockroachdb.md

In response to https://github.com/cockroachdb/cockroach/issues/15887#issuecomment-301103361.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1404)

Draw more attention to Windows 8 requirement

---

foreign-key.md

Fixes #1401
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1407)

Remove confusion around adding fk constraints

---

CONTRIBUTING.md

@tamird pointed out that we do not explicitly state our expectations of voice/tense for the docs. Adding the recommendations to our style guide to prevent future confusion from contributors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1399)

adding  style guide specifics

---

start-a-local-cluster-in-docker.md

CockroachDB 1.0 has been released 😄
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1410)

Update Docker version in docs

---

sql-feature-support.md

Fixes #1394
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1415)

Link to latest join blog post

---

_data/releases.yml
releases.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1422)

Unstable releases

---

build-a-java-app-with-cockroachdb.md

Fixes #1442
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1443)

Fix link to Java transaction code sample

---

_includes/contribute-options.html
_layouts/page.html

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1452)

Add ids for tracking and move html to separate file

---

_includes/contribute-options.html

Fixes #1457
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1458)

adding data-proofer-ignore to 'Edit This Page' link

---

_data/sidebar_doc.yml
_includes/custom/logging-flags.md
beta-20160414.md
cluster-setup-troubleshooting.md
cockroach-commands.md
configure-replication-zones.md
create-and-manage-users.md
create-security-certificates.md
debug-and-error-logs.md
file-an-issue.md
general-troubleshooting.md
generate-cockroachdb-resources.md
query-behavior-troubleshooting.md
sql-dump.md
start-a-node.md
stop-a-node.md
support-resources.md
troubleshooting-overview.md
use-the-built-in-sql-client.md
view-node-details.md

Troubleshooting documentation based on early experiences.
Note that this documentation is not meant to be exhaustive and can still be iterated on. Trying to lay groundwork here ahead of the 1.0 release to help customers who stumble over things we've seen.
Closes #891
Closes #892
Closes #971
Closes #1219
Closes #1230
Closes #1283 
Closes #1300
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1370)

Troubleshooting docs

---

constraints.md

Capitalization fix
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1463)

Minor grammar edit

---

v1.0.1.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1466)

fix typo in v1.0.1 release notes

---

demo-data-replication.md

Missing backslash causes command to not background correctly.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1465)

Update commands to work as designed.

---

v1.0.1.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1468)

Call out new troubleshooting docs in v1.0.1 release notes

---

create-table.md

- Add tip at top
- Add CREATE TABLE AS example
Fixes #1464
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1470)

Callout CREATE TABLE AS in CREATE TABLE docs

---

_includes/app/activerecord-basic-sample.rb
build-a-ruby-app-with-cockroachdb-activerecord.md

Fixes #1461
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1473)

Update activerecord sample to actually set the primary key

---

debug-and-error-logs.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1478)

Fix cluster var for query logging

---

diagnostics-reporting.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1481)

fix misformatted header on diagnostics reporting page

---

debug-and-error-logs.md

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1480)

Fix the other instance of sql.trace.txn.threshold.

---

_data/sidebar_doc.yml
cockroach-commands.md
debug-and-error-logs.md
debug-zip.md
file-an-issue.md
general-troubleshooting.md

Closes #1372
Closes #1179
@knz Can I get you to review for technical accuracy? If this isn't close to being right, let me know and I'd love to grab some time to discuss in greater detail. Thanks!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1469)

debug zip command

---

create-table-as.md

Fixes #1467
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1486)

Improve the doc for CREATE TABLE ... AS

---

add-column.md

Fixes #934 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1483)

ADD COLUMN documentation

---

check.md

Correct to relative url for `ADD CONSTRAINT` link.

Fix link in CHECK constraint

---

install-cockroachdb.md

Add analytics attributes to links on install page

---

information-schema.md

Document the information_schema.user_privileges view

---

beta-20161215.md
build-a-clojure-app-with-cockroachdb.md
cloud-deployment.md
cluster-settings.md
cluster-setup-troubleshooting.md
configure-replication-zones.md
create-security-certificates.md
demo-automatic-rebalancing.md
deploy-cockroachdb-on-aws-insecure.md
deploy-cockroachdb-on-aws.md
deploy-cockroachdb-on-digital-ocean-insecure.md
deploy-cockroachdb-on-digital-ocean.md
deploy-cockroachdb-on-google-cloud-platform-insecure.md
deploy-cockroachdb-on-google-cloud-platform.md
deploy-cockroachdb-on-microsoft-azure-insecure.md
deploy-cockroachdb-on-microsoft-azure.md
file-an-issue.md
import-data.md
manual-deployment-insecure.md
manual-deployment.md
monitor-cockroachdb-with-prometheus.md
orchestrate-cockroachdb-with-docker-swarm-insecure.md
orchestrate-cockroachdb-with-docker-swarm.md
orchestrate-cockroachdb-with-kubernetes.md
upgrade-cockroach-version.md

Implements the style mentioned in #1492

fixes spacing for redcartpet

---

select.md
sql-faqs.md

Clarify docs for ORDER BY

---

_includes/app/TxnSample.java

Fixes #1528. Thanks to @dimsmol for the find!

Test App: Fix Java retry bug

---

generate/yacc/parse.go
generate/yacc/parse_test.go

fixes current DEFAULT production problem

sync parser.go

---

_includes/sql/diagrams/rename_table.html
generate/main.go
rename-table.md

Added Parameters section and converted Usage to Examples

---

recommended-production-settings.md

Starts to address #1132, though not yet per-cloud.

Basic hardware recs

---

diagnostics-reporting.md

- Make two opt out options more explicit
- Explain how to verify opt out
Fixes #1547

Update diagnostics reporting page

---

drop-database.md

Clean up DROP DATABASE documentation

---

known-limitations.md

Add known limitation about schema changes between executions of prepared statements

---

configure-replication-zones.md

Fixes #1280
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/cockroachdb/docs/1441)

Add info on setting zone configs for system ranges

---

recommended-production-settings.md

@robert-s-lee, based on some feedback in the docs meeting, I've updated our hardware recs to clarify that decisions depend on scenario and workload. PTAL.

Clarify that hardware decisions depend on scenario and workload

---

_includes/app/txn-sample.js

Modifies the callback behavior of the node.js transaction wrapper
code to propogate up all arguments to the callback in the user
defined operation.
Current implementation would only propogate the errors up, and not
any data that the user wishes to have returned.

Propagate operation results through node.js txnWrapper example

---

backup.md

https://github.com/cockroachdb/cockroach/issues/16424

Don't use unsupported non-const expr in AS OF SYSTEM TIME

---

_includes/sql/diagrams/revoke.html
generate/main.go
revoke.md

Revoke statement document: Added Parameters section, converted Usage to Examples, updated SQL diagram

---

_includes/app/common-steps.md
_includes/app/txn-sample.js
build-a-c++-app-with-cockroachdb.md
build-a-go-app-with-cockroachdb.md
build-a-java-app-with-cockroachdb.md
build-a-nodejs-app-with-cockroachdb.md
build-a-php-app-with-cockroachdb.md
build-a-python-app-with-cockroachdb.md
build-a-ruby-app-with-cockroachdb.md
build-a-rust-app-with-cockroachdb.md

- Comment edit in node txn wrapper
- Minor updates to flow of node txn step

Tweaks to Node.js build an app tutorial

---

index.md

Update recent blog posts

---

_includes/app/common-steps.md
build-a-c++-app-with-cockroachdb.md
build-a-clojure-app-with-cockroachdb.md
build-a-go-app-with-cockroachdb-gorm.md
build-a-go-app-with-cockroachdb.md
build-a-java-app-with-cockroachdb-hibernate.md
build-a-java-app-with-cockroachdb.md
build-a-nodejs-app-with-cockroachdb-sequelize.md
build-a-nodejs-app-with-cockroachdb.md
build-a-php-app-with-cockroachdb.md
build-a-python-app-with-cockroachdb-sqlalchemy.md
build-a-python-app-with-cockroachdb.md
build-a-ruby-app-with-cockroachdb-activerecord.md
build-a-ruby-app-with-cockroachdb.md
build-a-rust-app-with-cockroachdb.md
demo-automatic-rebalancing.md
demo-data-replication.md
demo-fault-tolerance-and-recovery.md
learn-cockroachdb-sql.md
start-a-local-cluster.md

Add "copy to clipboard" throughout getting started docs

---

_includes/footer.html

Change them to point to `/docs/stable` instead of `/docs`.

Update docs links in footer

---

v1.0/monitor-cockroachdb-with-prometheus.md
v1.1/monitor-cockroachdb-with-prometheus.md

Update flag prefix in prometheus docs

---

v1.1/back-up-data.md

Partner to https://github.com/cockroachdb/docs/pull/1655/

Fix on v1.1 backup page

---

v1.0/deploy-cockroachdb-on-google-cloud-platform-insecure.md
v1.0/deploy-cockroachdb-on-google-cloud-platform.md
v1.1/deploy-cockroachdb-on-google-cloud-platform-insecure.md
v1.1/deploy-cockroachdb-on-google-cloud-platform.md

Update GCE load balancing guidance

---

v1.0/index.md
v1.1/index.md

@kuanluo, @jess-edwards, @swatikumar16, PTAL.

Add usability interview callout

---

_includes/sidebar-data-v1.0.json
_includes/sidebar-data-v1.1.json
v1.0/demo-automatic-cloud-migration.md
v1.1/demo-automatic-cloud-migration.md

I recorded a live demo of deploying across Digital Ocean and GCE and then migrating from DO to GCE, as a complement to the tutorial on this topic. 
This PR embeds the recording (on Youtub) in the tutorial and renames the broadens the name of the tutorial from "Automatic Cloud Migration" to "Cross-Cloud Deployment & Migration".

Cross-cloud deployment & migration screencast

---

_config.yml
v1.1/deploy-cockroachdb-on-aws-insecure.md
v1.1/deploy-cockroachdb-on-aws.md
v1.1/deploy-cockroachdb-on-digital-ocean-insecure.md
v1.1/deploy-cockroachdb-on-digital-ocean.md
v1.1/deploy-cockroachdb-on-google-cloud-platform-insecure.md
v1.1/deploy-cockroachdb-on-google-cloud-platform.md
v1.1/deploy-cockroachdb-on-microsoft-azure-insecure.md
v1.1/deploy-cockroachdb-on-microsoft-azure.md
v1.1/manual-deployment-insecure.md
v1.1/manual-deployment.md
v1.1/set-vars.md
v1.1/show-vars.md
v1.1/use-the-built-in-sql-client.md

- Add SQL shell welcome details, calling out version and cluster ID details
- Add `node_id` session variable to `show-vars.md` and deployment tutorials
Fixes #1633

v1.1 SQL shell updates

---

_includes/head.html
v1.0/build-an-app-with-cockroachdb.md
v1.0/cockroachdb-in-comparison.md
v1.0/frequently-asked-questions.md
v1.0/index.md
v1.0/install-cockroachdb.md
v1.1/build-an-app-with-cockroachdb.md
v1.1/cockroachdb-in-comparison.md
v1.1/frequently-asked-questions.md
v1.1/index.md
v1.1/install-cockroachdb.md

As requested by @swatikumar16.

Update meta descriptions and keywords

---

_data/blog_posts.xml
v1.0/index.md
v1.1/index.md

- Remove 1.0 callout
- Refresh links to recent blog posts
- Update docs homepage messaging to match main homepage

Updates to Docs home

---

v1.0/orchestrate-cockroachdb-with-docker-swarm-insecure.md
v1.0/orchestrate-cockroachdb-with-docker-swarm.md
v1.1/orchestrate-cockroachdb-with-docker-swarm-insecure.md
v1.1/orchestrate-cockroachdb-with-docker-swarm.md

- Secure: Add steps for generating client (root) cert/key and secrets
- Secure & Insecure: Add copy-to-clipboard feature
- Secure & Insecure: Add guidance on accessing the Admin UI from outside the swarm
Fixes #1617
Fixes #1640
Fixes #1736

Update docker swarm tutorials

---

CONTRIBUTING.md
releases/v1.1-alpha.20170720.md
v1.1/show-vars.md
v1.1/use-the-built-in-sql-client.md

- Add guidance on version tags to CONTRIBUTING.md
- Add version tag to node_id variable
- Add version tag to SQL Shell Welcome section
Fixes #1639

Add 1.1 callouts

---

v1.0/configure-replication-zones.md
v1.1/configure-replication-zones.md

According to Bram, they were never really finished and are something
that we'd prefer to fully think through before committing to supporting
them. See https://github.com/cockroachdb/cockroach/issues/14163 for more detail.

Remove documentation of positive constraints.

---

_includes/sidebar-releases.json

Closes #1750
@benesch Any chance I could get you to take a quick peek at this?

Add links to alpha/beta releases

---

v1.0/restore.md
v1.1/restore.md

typo in restore docs

---

v1.0/upgrade-cockroach-version.md
v1.1/upgrade-cockroach-version.md

Add node shutdown verification step to rolling upgrade instructions

---

v1.0/deploy-cockroachdb-on-aws-insecure.md
v1.0/deploy-cockroachdb-on-aws.md
v1.0/deploy-cockroachdb-on-google-cloud-platform-insecure.md
v1.0/deploy-cockroachdb-on-google-cloud-platform.md
v1.1/deploy-cockroachdb-on-aws-insecure.md
v1.1/deploy-cockroachdb-on-aws.md
v1.1/deploy-cockroachdb-on-google-cloud-platform-insecure.md
v1.1/deploy-cockroachdb-on-google-cloud-platform.md

Remove links to terraform configs

---

v1.0/view-version-details.md
v1.1/view-version-details.md

Add response field descriptions and remove --deps flag

---

v1.0/monitor-cockroachdb-with-prometheus.md
v1.1/monitor-cockroachdb-with-prometheus.md

Fix --alertmanager.url flag

---

v1.0/deploy-cockroachdb-on-google-cloud-platform-insecure.md
v1.0/deploy-cockroachdb-on-google-cloud-platform.md
v1.1/deploy-cockroachdb-on-google-cloud-platform-insecure.md
v1.1/deploy-cockroachdb-on-google-cloud-platform.md

Fix incorrect port in GCE deployment tutorials

---

v1.0/set-vars.md
v1.1/set-vars.md

Fix formatting error in SET doc

---

_includes/sidebar-data-v1.1.json
_includes/sql/v1.1/functions.md
v1.1/array.md
v1.1/bytes.md

Closes #1561 
- Created document for Array data type
- Updated sidebar navigation to include Array in Data Types category
- Updated Bytes document as per discussion on Slack about increasing size to 1 MB.
- Updated Functions and Operators document with array functions.

Created document for Array data type, updated related files

---

_includes/sidebar-data-v1.1.json
_includes/sql/v1.1/diagrams/show_backup.html
generate/main.go
v1.1/alter-database.md
v1.1/alter-index.md
v1.1/show-backup.md
v1.1/sql-statements.md

Docs-side fix for #1822.
Also fixes #1504.

Add missing pages and document SHOW BACKUP

---

_includes/footer.html
_includes/topnav.html

In response to https://github.com/cockroachlabs/hugo-website/pull/173

Update footer to align with hugo site

---

v1.0/contribute-to-cockroachdb.md
v1.1/contribute-to-cockroachdb.md

Update contributor policy

---

v1.0/install-cockroachdb.html
v1.1/install-cockroachdb.html

Add analytics tags to install page copy buttons

---

_includes/sidebar-data-v1.1.json

Reorganized navigation sidebar

---

v1.1/sql-feature-support.md

- Mark ARRAY as supported
- Add UUID
- Update link to auto-increment docs
- Add parallel statement execution

Update 1.1 sql feature support page

---

_includes/sql/v1.1/diagrams/drop_database.html
generate/main.go
v1.1/drop-database.md

Add CASCADE/RESTRICT to DROP DATABASE docs

---

CONTRIBUTING.md
_layouts/default.html
css/customstyles.css
css/layouts/_content.scss
hackathons.md

Wanted to put together a resource for Hackathon students to get them started with using CockroachDB in Node.js (by far the most popular framework for hacks). This will be the content we point students to when they come up and talk to us.
My experience at two hackathons last year leads me to believe we need this because a lot of students struggle with parsing through the documentation and finding all of the bits and pieces they need. All of this content exists elsewhere, but by aggregating everything into a single place, we're table to ensure they don't fall off the "happy path," and if they do, we have many points that we can put them back on.
Sending this up to see what @jseldess and @jess-edwards think. A few questions for y'all:
- Does this work on the docs site, or should it be a blog …

Hackathon Guide

---

hackathons.md

Fixing @jseldess's comments from #1840
- Changed button colors to match "INSTALL" button in nav
- Changed version number to use Liquid template
- Fixed typo for macOS/Linux download link

Hacktathon guide fast-follow fixes

---

v1.0/deploy-cockroachdb-on-google-cloud-platform-insecure.md
v1.1/deploy-cockroachdb-on-google-cloud-platform-insecure.md

Update command to show correct SQL query for testing correct GCE deployment.

Update testing SQL commands for deploying to GCE

---

v1.0/known-limitations.md
v1.1/known-limitations.md

Also update the 1.0 page intro to mention that, when a limitation is resolved, we update the page to identify the release including the change.

Add version to known limitations page title

---

_includes/sql/v1.1/diagrams/add_constraint.html
_includes/sql/v1.1/diagrams/validate_constraint.html
generate/main.go
v1.1/validate-constraint.md

Validate constraint stub

---

v1.1/show-create-table.md

Update SHOW CREATE TABLE example

---

_includes/custom/remove-user-callout.html
_includes/sidebar-data-v1.1.json
_includes/sql/v1.1/diagrams/create_user.html
_includes/sql/v1.1/diagrams/drop_user.html
generate/main.go
v1.0/create-and-manage-users.md
v1.1/create-and-manage-users.md
v1.1/create-user.md
v1.1/drop-user.md
v1.1/revoke.md
v1.1/sql-statements.md

- Add docs on `DROP USER`
- Add `DROP USER` to sidenav and sql statements overview
- Update `CREATE USER` diagram
- Update related docs with guidance on removing users
Fixes #1591

DROP USER statement and related updates

---

v1.0/use-the-built-in-sql-client.md
v1.1/functions-and-operators.md
v1.1/sql-statements.md
v1.1/use-the-built-in-sql-client.md

Document SQL shell help options

---

v1.1/create-and-manage-users.md
v1.1/create-user.md

Clarify that root user must user cert-based authentication

---

_includes/sidebar-data-v1.1.json
_includes/sql/v1.1/diagrams/reset_csetting.html
_includes/sql/v1.1/diagrams/reset_session.html
_includes/sql/v1.1/diagrams/set_cluster_setting.html
_includes/sql/v1.1/diagrams/set_var.html
generate/main.go
v1.1/reset-cluster-setting.md
v1.1/reset-vars.md
v1.1/set-cluster-setting.md
v1.1/set-vars.md
v1.1/show-cluster-setting.md
v1.1/sql-statements.md

Document RESET and SET TO DEFAULT

---

_includes/sidebar-data-v1.1.json
v1.1/architecture/distribution-layer.md
v1.1/architecture/overview.md
v1.1/architecture/replication-layer.md
v1.1/architecture/sql-layer.md
v1.1/architecture/storage-layer.md
v1.1/architecture/transaction-layer.md

Fixes #49 
Sending up a mostly sensible view of where these are at so far. Start with `overview.md` and then basically progresses through the layers identified there.
@jseldess Given how rough all of this is, structural feedback is most impactful, but if there are details you know are missing, I'd be glad for any additional technical information you have.
@bdarnell Thank you so much for the outline for the layers. It really helped provide a structure to these documents. Because I used the structured you recommended, can I get you to review it to see if I was in the right ballpark for the topic as you expected to have it covered? Also, any technical corrections are greatly appreciated. Apologies for the unpolished language.

Architecture docs v1

---

_includes/sidebar-data-v1.1.json

Remove extra command and empty line.

Fix json for 1.1 sidenav

---

_includes/sql/v1.1/aggregates.md
_includes/sql/v1.1/functions.md
_includes/sql/v1.1/operators.md
generate/funcs.go

Fix the SQL function docs.

---

_includes/sidebar-data-v1.1.json
v1.1/create-security-certificates.md
v1.1/rotate-certificates.md

Created certificate rotation document

---

v1.0/known-limitations.md
v1.1/known-limitations.md

Document v1.1 known limitations

---

v1.1/data-types.md
v1.1/float.md
v1.1/int.md

INT and FLOAT aliases

---

v1.1/cockroachdb-architecture.md

adding redirect from old architecture docs

---

v1.0/create-user.md
v1.1/create-user.md

Adding insecure flag for connecting to insecure cluster as specific user

Improve connecting to insecure cluster example

---

v1.1/sql-feature-support.md

Mark sequences as planned and link to related GitHub issue

---

v1.1/install-cockroachdb.html

- Fix a link
- Remove extra language to shorten page
- Remove h2 headers
- Make homebrew the default for mac
Fixes #1999

Minor improvements to Install CockroachDB page

---

v1.0/install-cockroachdb.html
v1.1/install-cockroachdb.html
v1.2/install-cockroachdb.html

Add missing analytics event tags

---

_config.yml
rfc/training-content-delivery.md

RFC: Training Content

---

_includes/prod_deployment/insecure-start-nodes.md
_includes/prod_deployment/secure-start-nodes.md

Fix --host description in cloud tutorials

---

v1.1/admin-ui-overview.md
v1.2/admin-ui-overview.md

Redirected Explore the Admin UI page to Overview page

---

_includes/topnav.html
css/components/_buttons.scss
css/customstyles.css
v1.0/build-a-nodejs-app-with-cockroachdb-sequelize.md
v1.1/build-a-nodejs-app-with-cockroachdb-sequelize.md
v1.2/build-a-nodejs-app-with-cockroachdb-sequelize.md

* Update site-wide CTA button copy to indicate "Download" instead of "Install"
* Update header button style to vertically center copy

Update download button copy

---

releases/v1.1.2.md

Fix dump in 1.1.2 release notes

---

_includes/topnav.html

* Add 'Pricing' to 'Product' dropdown in header.

Add Pricing option to Product dropdown in header

---

v1.0/monitor-cockroachdb-with-prometheus.md
v1.1/frequently-asked-questions.md
v1.1/import-data.md
v1.1/monitor-cockroachdb-with-prometheus.md
v1.2/frequently-asked-questions.md
v1.2/import-data.md
v1.2/monitor-cockroachdb-with-prometheus.md

Update FAQ about migrating from PostgreSQL or MySQL

---

_includes/footer.html
_includes/topnav.html
v1.1/backup.md
v1.1/restore.md
v1.1/sql-statements.md
v1.2/backup.md
v1.2/install-cockroachdb.html
v1.2/restore.md
v1.2/sql-statements.md

* change 'Products' dropdown label to 'Product'; remove 'Core' from dropdown
* change 'CockroachDB Enterprise' to 'CockroachDB' in dropdown options
* remove 'CockroachDB Core' from dropdown options

Update topnav to reflect changes to Product page

---

_includes/footer.html

Reorder Docs links in footer and add Architecture

---

v1.1/import-data.md
v1.1/porting-postgres.md
v1.2/import-data.md
v1.2/porting-postgres.md

Remove mention of arrays as unsupported

---

CONTRIBUTING.md
_includes/head.html
v1.0/cockroachdb-in-comparison.md
v1.0/frequently-asked-questions.md
v1.0/index.md
v1.1/cockroachdb-in-comparison.md
v1.1/frequently-asked-questions.md
v1.1/index.md
v1.2/cockroachdb-in-comparison.md
v1.2/frequently-asked-questions.md
v1.2/index.md

Remove Optimizely from docs

---

_includes/linkedin_analytics.html
_layouts/default.html

Add LinkedIn tag to docs pages

---

_config.yml
_data/releases.yml
_includes/sidebar-releases.json
releases/v1.1.3.md
v1.1/cancel-job.md
v1.1/restore.md
v1.2/cancel-job.md
v1.2/restore.md

raw changelog for [1.1.3](https://github.com/cockroachdb/cockroach/issues/20176).

v1.1.3 release notes

---

releases/v1.1.3.md
v1.0/build-a-c++-app-with-cockroachdb.md
v1.0/install-client-drivers.md
v1.1/build-a-c++-app-with-cockroachdb.md
v1.1/install-client-drivers.md
v1.1/orchestrate-cockroachdb-with-kubernetes.md
v1.2/build-a-c++-app-with-cockroachdb.md
v1.2/install-client-drivers.md
v1.2/orchestrate-cockroachdb-with-kubernetes.md

Fixes https://github.com/cockroachdb/cockroach/issues/20320

Fix k8 cert approval command

---

css/components/_buttons.scss
css/customstyles.css
css/global/_type.scss
css/layouts/_header.scss

__[desc]:__
* increase font size on header links
* update font family on header button

Sync styles between docs and main site

---

v1.1/null-handling.md
v1.1/select.md
v1.2/null-handling.md
v1.2/select.md

Clarify treatment of NULLs in SELECTs with ORDER BY clause

---

_config.yml
_data/releases.yml
releases/v1.2-alpha.20171204.md

See https://github.com/cockroachdb/cockroach/issues/20272.

Release notes for v1.2-alpha.20171204

---

v1.0/contribute-to-cockroachdb.md
v1.1/contribute-to-cockroachdb.md
v1.2/contribute-to-cockroachdb.md

Broken by https://github.com/cockroachdb/cockroach/pull/20581

Fix link to style.md in the main repo to reflect recent changes

---

_config.yml
_data/releases.yml
releases/v1.2-alpha.20171211.md
v1.2/install-cockroachdb.html

For https://github.com/cockroachdb/cockroach/issues/20457.

Release notes v1.2 alpha.20171211

---

.gitignore
_includes/sidebar.html
css/components/_buttons.scss
css/customstyles.css
css/layouts/_header.scss
css/layouts/_sidebar.scss
js/customscripts.js

* fix layout flickering at responsive breakpoints (@ 768px & 992px)
* fix vertical alignment of header links
* fix positioning of version-switcher (to prevent bottom edge from rendering as double border)
* code cleanup

UI Updates

---

v1.2/stop-a-node.md

Follow-up to https://github.com/cockroachdb/docs/pull/2275.

Fix stop a node

---

v1.2/view-node-details.md

@jseldess does this need a review from eng?

removed status required flags and updated examples - fixes #2259

---

_includes/prod_deployment/secure-generate-certificates.md
_includes/sidebar-data-v1.1.json
_includes/sidebar-data-v2.0.json
v1.1/create-security-certificates-openssl.md
v1.1/create-security-certificates.md
v1.1/secure-a-cluster.md
v2.0/create-security-certificates-openssl.md
v2.0/create-security-certificates.md
v2.0/secure-a-cluster.md

Created openssl document

---

v1.0/backup.md
v1.1/backup.md
v2.0/backup.md

Fixed incremental backup example

---

_config.yml
_data/releases.yml
_includes/sidebar-releases.json
releases/v1.1.4.md
v1.1/common-errors.md
v2.0/common-errors.md

Release notes for v1.1.4 release. See https://github.com/cockroachdb/cockroach/issues/21144.

Release notes for v1.1.4

---

_includes/sql/v2.0/aggregates.md
_includes/sql/v2.0/functions.md
_includes/sql/v2.0/operators.md

Refresh 2.0 functions and operators doc

---

_includes/sql/v2.0/diagrams/alter_sequence_options.html
_includes/sql/v2.0/diagrams/create_sequence.html
_includes/sql/v2.0/diagrams/drop_sequence.html
_includes/sql/v2.0/diagrams/stmt_block.html
v2.0/alter-sequence.md
v2.0/create-sequence.md
v2.0/drop-sequence.md
v2.0/sql-grammar.md

Also regenerate full SQL grammar page.

Add sequence diagrams

---

v2.0/admin-ui-access-and-navigate.md
v2.0/operational-faqs.md

Document how to reduce or disable timeseries data

---

_config.yml
_data/releases.yml
releases/v2.0-alpha.20180116.md

See https://github.com/cockroachdb/cockroach/issues/21321

v2.0-alpha.20180116 release notes

---

css/components/_toc.scss
css/customstyles.css

Reduce font size and line height for toc items

---

_plugins/versions/version.rb
v1.0/install-cockroachdb.html
v1.1/install-cockroachdb.html
v2.0/install-cockroachdb.html

Our homebrew recipe is currently only for the latest stable release.
Fixes #2153

Remove homebrew install option for non-stable releases

---

_data/releases.yml
v2.0/demo-fault-tolerance-and-recovery.md

- Fix spelling fix in 2.0 fault tolerance tutorial; follow-up to https://github.com/cockroachdb/docs/pull/2380.
- Fix incorrect data on release page.

Minor language fixes

---

_includes/sidebar-data-v1.1.json
_includes/sidebar-data-v2.0.json
_includes/sql/v1.0/diagrams/grammar.html
_includes/sql/v1.1/diagrams/grammar.html
_includes/sql/v2.0/aggregates.md
_includes/sql/v2.0/diagrams/grammar.html
_includes/sql/v2.0/diagrams/stmt_block.html
_includes/sql/v2.0/functions.md
_includes/sql/v2.0/operators.md
v1.1/upgrade-cockroach-version.md
v2.0/upgrade-cockroach-version.md

Fixes #2073 
Fixes #2315 
Fixes #2174 
Fixes #2173 
Fixes #2383 
Fixes #2384
Fixes #2385
Fixes #2213 
Fixes #2394

Update 2.0 functions and operators

---

v2.0/install-cockroachdb.html

Change Go requirement in 2.0 install docs

---

releases/v2.0-alpha.20180122.md

- Correct enterprise links
- Add a missing period

Minor edits to v2.0-alpha.20180122 release notes

---

_includes/head.html

Exclude training pages from search results

---

_config.yml
_data/releases.yml
_includes/sidebar-releases.json
releases/v1.1.5.md

For https://github.com/cockroachdb/cockroach/issues/21890.

Update docs site and add release notes for v1.1.5

---

_includes/sidebar-data-v1.0.json
_includes/sidebar-data-v1.1.json
_includes/sidebar-data-v2.0.json
releases/v1.0-rc.1.md
v1.0/multi-active-availability.md
v1.1/enterprise-licensing.md
v1.1/frequently-asked-questions.md
v1.1/multi-active-availability.md
v2.0/enterprise-licensing.md
v2.0/frequently-asked-questions.md
v2.0/multi-active-availability.md

Adding content that describes what MAA is/does, as well as a light treatment of some of the technologies we use to enable the features for customers.
@bdarnell Can I get you to review from a technical standpoint? The intended audience is not as highly technical as the architecture docs, so I think we can speak mostly to larger strokes of the software's functionality (e.g. Raft).

[WIP] Multi-Active Availability Feature Description

---

_includes/sidebar-data-v2.0.json
_includes/sql/v2.0/diagrams/create_sequence.html
_includes/sql/v2.0/diagrams/rename_sequence.html
_includes/sql/v2.0/diagrams/show_create_sequence.html
v2.0/alter-sequence.md
v2.0/create-sequence.md
v2.0/drop-sequence.md
v2.0/rename-sequence.md
v2.0/show-create-sequence.md
v2.0/show-create-table.md
v2.0/show-create-view.md
v2.0/sql-statements.md

SHOW CREATE SEQUENCE doc + general updates

---

v1.1/training/cluster-upgrade.md
v1.1/training/node-decommissioning.md

There's also the fact that the next module doesn't actually have the steps to create a cluster from scratch, but I don't want to tweak any of @petermattis's content without his confirmation at this point.

training: Fix node cleanup text, remove final What's Next section

---

_includes/sidebar-data-training.json
v1.1/training/index.md
v1.1/training/software-panic-troubleshooting.md

- Add client-side redirect from /training/index.html to /v1.1/training/index.html
- Fix what's next link in panic module
- Fix network partition in sidenav

Training fixes

---

_config.yml
v1.1/training/backup-and-restore.md

@petermattis and @a-robinson, I have to get the license to work in the morning, but this should be good to go otherwise. To test it yourself, you can get an internal license from the #backup channel.  
Sorry for the late addition. If it's too late to include in the training, no problem. I can hide the content/slides.

Update backup and restore training

---

_includes/sidebar-data-training.json
_includes/sidebar.html

- Edit sidebar JS to allow external links
- Add feedback survey and docs link to sidenav

Training feedback survey

---

v1.1/frequently-asked-questions.md
v2.0/frequently-asked-questions.md

Update answers to: 
When is CockroachDB a good choice? 
Adds: `Multi-region deployments, Cloud migrations`
Question: When is CockroachDB not a good choice? 
Removes: `Complex SQL Joins`
cc @awoods187 @petermattis @nstewart

Update answers to When is CockroachDB a good / not good choice

---

_includes/sql/v2.0/diagrams/delete.html
v2.0/delete.md
v2.0/select.md

Closes #2258.
`UPDATE` edits moved to #2514.

Update DELETE SQL Diagram

---

v2.0/foreign-key.md

Add SET NULL / SET DEFAULT examples to FK doc

---

_includes/sql/v2.0/functions.md
_includes/sql/v2.0/operators.md

Update 2.0 functions and operators doc

---

v1.1/sql-feature-support.md
v2.0/sql-feature-support.md

- Mark Sequences as supported in 2.0
- Add INET for 2.0
- Change UUID for sql standard to postgres extension for 1.1 and 2.0

Various updates to sql feature support page

---

v2.0/show-cluster-setting.md

Update required privileges for show cluster settings

---

v1.1/cancel-query.md
v2.0/cancel-query.md

Clarify that CANCEL QUERY accepts a single ID

---

v2.0/functions-and-operators.md
v2.0/sql-expressions.md

For https://github.com/cockroachdb/cockroach/pull/20747.
Fixes #2423.

 Document BETEWEEN SYMMETRIC operator

---

_config.yml
v1.1/training/cluster-upgrade.md
v2.0/install-cockroachdb.html

Replaces https://github.com/cockroachdb/docs/pull/2557.

Point v2.0-alpha at non-yanked release

---

v1.0/contribute-to-cockroachdb.md
v1.1/contribute-to-cockroachdb.md
v2.0/contribute-to-cockroachdb.md

Follow up to https://github.com/cockroachdb/docs/pull/2562.

Fix link to "help wanted" issues

---

v2.0/create-and-manage-users.md
v2.0/create-user.md

Remove password creation from insecure mode

---

v1.1/orchestrate-a-local-cluster-with-kubernetes-insecure.md
v1.1/orchestration.md
v2.0/orchestrate-a-local-cluster-with-kubernetes-insecure.md
v2.0/orchestration.md

Also list mesosphere on orchestration overview.

Link from local orchestration to real orchestration overview

---

_includes/sidebar-data-v2.0.json
v2.0/data-types.md
v2.0/inet.md
v2.0/jsonb.md

Closes #2011.
This PR only covers the JSONB data type. A separate PR will be opened for inverted indexes.

JSONB data type

---

_includes/sidebar-data-training.json

Link to company-agnostic training survey

---

v1.1/training/architecture-overview.md
v1.1/training/why-cockroachdb.md

Replace intro training slides with videos

---

v1.0/use-the-built-in-sql-client.md
v1.1/use-the-built-in-sql-client.md
v2.0/use-the-built-in-sql-client.md

Fixes cockroachdb/cockroach#23507.

Fix root cert param name in SQL shell example

---

v1.1/admin-ui-replication-dashboard.md
v2.0/admin-ui-replication-dashboard.md

Fix explanation of unavailable ranges in admin ui docs

---

v1.1/architecture/overview.md
v2.0/architecture/overview.md

Add Range Lease definition to architecture overview

---

v2.0/information-schema.md

Change references to information schema columns from boolean true/false to yes/no.

---

v2.0/drop-index.md

Closes #2395.
added description that you must use cascade to drop a unique index

update DROP INDEX doc

---

v1.0/start-a-node.md
v1.1/start-a-node.md
v2.0/start-a-node.md

start a node: add clarification on specifying flags every time

---

v2.0/explain.md

Updating the documentation for EXPLAIN with the v2.0 format. Including
more information on the contents of the ordering column.
Fixes #2393.
Fixes #2515.

Update documentation for EXPLAIN

---

v2.0/table-expressions.md

Fix the position of some semicolons.

---

v2.0/information-schema.md

sql: Add missing columns in information_schema.columns view

---

v2.0/information-schema.md

sql: Add missing columns to information_schema.statistics table

---

v2.0/information-schema.md

sql: Add information_schema.administrable_role_authorizations view

---

v2.0/information-schema.md

sql: Add information_schema.column_privileges view

---

v2.0/configure-replication-zones.md

Document changes to the built-in replication zones

---

v1.0/grant.md
v1.1/grant.md
v2.0/grant.md

Clarify ON DATABASE vs ON TABLE.* grants

---

_includes/orchestration/kubernetes-upgrade-cluster.md
v1.1/orchestrate-cockroachdb-with-kubernetes-insecure.md
v1.1/orchestrate-cockroachdb-with-kubernetes.md
v2.0/orchestrate-cockroachdb-with-kubernetes-insecure.md
v2.0/orchestrate-cockroachdb-with-kubernetes.md

Document how to upgrade a cluster on Kubernetes

---

v1.0/configure-replication-zones.md
v1.1/configure-replication-zones.md
v2.0/configure-replication-zones.md

Ignore the first commit, it's just #2677

Add copy-clipboard to commands on the Configure Replication Zones page

---

v2.0/transactions.md

... supported by our txn auto-retry mechanism to include "extended
protocol" batches.

expand the definition of "batches" of statements

---

v2.0/information-schema.md

sql: add information_schema.(applicable_roles|enabled_roles) views

---

v2.0/architecture/sql-layer.md

Follow-up to https://github.com/cockroachdb/docs/pull/2695

Correct spelling mistake in v2.0 sql-layer.md

---

v2.0/known-limitations.md

known-limitations: remove incremental-after-schema-change warning

---

v1.0/deploy-a-test-cluster.md
v2.0/deploy-a-test-cluster.md

Follow-up to https://github.com/cockroachdb/docs/pull/2697

Remove scaling step for test clustet tutorial

---

v1.0/delete.md
v1.1/delete.md
v2.0/delete.md

delete: note that deletes dont free disk space immediately

---

v1.1/insert.md
v2.0/insert.md

add example to insert on conflict

---

v2.0/backup.md
v2.0/performance-best-practices-overview.md
v2.0/select.md
v2.0/transactions.md

add descriptions of as of system time's benefits/drawbacks

---

scripts/find-unused-images.py

Previously, we were looking through some files multiple times.

Speed up unused image finding script

---

_includes/head.html

- noindex
- nofollow
- noarchive
- nocache
Fixes #2724

Add more robots tags to training page headers

---

releases/v1.2-alpha.20171204.md
releases/v2.0-alpha.20180129.md
v2.0/import.md
v2.0/insert.md
v2.0/performance-best-practices-overview.md

Replicated Matt J's PR so I could copy-edit it. 
Closes #2115, #2445, #2055, #2172, #2115

Improve IMPORT 2.0 Docs

---

_includes/sql/v2.0/diagrams/show_trace.html
v2.0/show-trace.md

Fixes #2425
Fixes #2553
Fixes #2289

updates to the SHOW TRACE FOR docs

---

_includes/sidebar-data-v2.0.json
v2.0/import.md

FYI, @Amruta-Ranade, this is something @dianasaur323 to do.

Remove "beta" label from IMPORT

---

v1.0/upgrade-cockroach-version.md
v1.1/upgrade-cockroach-version.md
v2.0/upgrade-cockroach-version.md

Updated for v1.1 and v2.0, not applicable to v1.0.
Fixes #2367

upgrade cockroach version: add version compatibility information

---

v2.0/add-column.md
v2.0/add-constraint.md
v2.0/alter-column.md
v2.0/alter-table.md
v2.0/backup.md
v2.0/cockroach-commands.md
v2.0/data-types.md
v2.0/drop-column.md
v2.0/drop-constraint.md
v2.0/information-schema.md
v2.0/manage-long-running-queries.md
v2.0/rename-column.md
v2.0/rename-table.md
v2.0/restore.md
v2.0/sql-dump.md
v2.0/sql-statements.md

Fixes #2735 
@bdarnell, please let me know if you disagree with any of the removals. There might be more that I left that you might've removed, too...

Remove new/changed in 1.1 callouts from prominent places

---

v2.0/jsonb.md

JSONB functions and operators

---

v1.1/validate-constraint.md
v2.0/validate-constraint.md

Fixes https://github.com/cockroachdb/docs/issues/990

Add params and examples to `VALIDATE CONSTRAINT`

---

CONTRIBUTING.md

Related: https://github.com/cockroachdb/docs/pull/2700

Note changed HTML test program

---

_includes/json/json-sample.go
_includes/sidebar-data-v2.0.json
v2.0/demo-json-support.md

add json tutorial

---

v1.1/demo-automatic-cloud-migration.md
v1.1/demo-automatic-rebalancing.md
v1.1/demo-data-replication.md
v1.1/demo-fault-tolerance-and-recovery.md
v1.1/demo-follow-the-workload.md
v1.1/orchestrate-a-local-cluster-with-kubernetes-insecure.md
v2.0/demo-automatic-cloud-migration.md
v2.0/demo-automatic-rebalancing.md
v2.0/demo-data-replication.md
v2.0/demo-fault-tolerance-and-recovery.md
v2.0/demo-follow-the-workload.md
v2.0/demo-json-support.md
v2.0/inverted-indexes.md
v2.0/jsonb.md
v2.0/orchestrate-a-local-cluster-with-kubernetes-insecure.md

- Use line braks in some JSON sql examples.
- Cross-reference the JSON tutorial.
- Update the See Also list in core benefit tutorials.

Various JSON and core benefit updates

---

v1.0/upsert.md
v2.0/upsert.md

Follow-up to https://github.com/cockroachdb/docs/pull/2758.

Spelling fix in upsert.md

---

search.html

* update property reference in search handler to fix snippet truncation

fix broken snippet truncating

---

search.html

* provide fallback if cookies disabled
* check results array length to detect if no results

Provide fallback for docs version if cookies disabled

---

_config.yml
_data/releases.yml
_includes/sidebar-releases.json
releases/v1.1.7.md
releases/v2.0-beta.20180326.md

Release notes draft for March 26, 2018

Release notes draft

---

v2.0/backup.md
v2.0/import.md
v2.0/restore.md

Disallow bulkio statements within transactions

---

v2.0/backup.md
v2.0/restore.md

Added content for with revision_history and point-in-time restore

---

v2.0/configure-replication-zones.md

Fixes #2296 
This may not be enough explanation, so please let me know what you think!

Document per-replica zone configs

---

_includes/sidebar-data-v2.0.json
v2.0/partitioning.md

I am dividing the partitioning documentation task in two phases:
1. Add the stand-alone partitioning doc.
2. Update the related individual docs.
This PR is for phase 1. 
@danhhz @benesch Please review the doc for technical accuracy and completeness
@awoods187 Please review the doc for positioning and terminology
@jseldess @lhirata  Please review the doc for structure and completeness
I will copy-edit the doc extensively after the first round of reviews.

Added partitioning doc and updated sidebar nav

---

v2.0/backup.md
v2.0/create-sequence.md
v2.0/drop-sequence.md
v2.0/rename-sequence.md
v2.0/restore.md
v2.0/sql-dump.md

Closes #2718, #2510, #2516, #2522.

Sequence Updates

---

v2.0/computed-columns.md
v2.0/partitioning.md

Will work with Amruta later to add computed column example to partitioning

Partitioning Links

---

_includes/json/json-sample.py
v2.0/demo-json-support.md

- Add python code.
- Update tutorial to let user choose go or python.

Add python to json tutorial

---

v1.1/debug-and-error-logs.md
v2.0/debug-and-error-logs.md

Add callouts to Debug Logs pages re: UTC usage

---

_includes/sql/v2.0/functions.md
_includes/sql/v2.0/operators.md
v2.0/debug-zip.md
v2.0/deploy-a-test-cluster.md
v2.0/install-cockroachdb.md
v2.0/training/cluster-startup-and-scaling.md
v2.0/training/node-startup-troubleshooting.md

- Update Go version for build from source instructions 
- Update 2.0 functions and operators
- Remove application_name from sql field of cockroach start output
- Add heap profiles to debug zip docs

Misc 2.0 updates

---

v2.0/known-limitations.md
v2.0/use-the-built-in-sql-client.md

Reflect some v2.0 changes to the SQL CLI

---

v1.0/known-limitations.md
v1.1/known-limitations.md

Follow-up to https://github.com/cockroachdb/docs/pull/2790.

Indicate that limitation is resolved as of 2.0

---

v2.0/architecture/transaction-layer.md

Change PushTxnQueue to TxnWaitQueue in 2.0 architecture docs

---

_includes/sql/v2.0/diagrams/experimental_audit.html
v2.0/experimental-audit.md

Remove git merge conflict markers

---

_config.yml
_data/releases.yml
releases/v2.0-rc.1.md

tweak: v2.0-rc1 => v2.0-rc.1

---

v2.0/show-jobs.md

Added note to SHOW JOBS doc

---

_includes/sql/v2.0/diagrams/create_sequence.html
_includes/sql/v2.0/diagrams/show_create_sequence.html
v2.0/create-sequence.md

Closes #2793.
@nvanbenschoten, I think `CACHE <seq_value>` need to be added to the `create_sequence` SQL diagram.

Add CACHE / NO CYCLE to CREATE SEQUENCE

---

v2.0/query-behavior-troubleshooting.md
v2.0/sql-faqs.md

Update FAQ with SQL audit log info

---

releases/v2.0.0.md

@knz, I added a row to the documentation updates section about your work around selection queries. Does the language look ok?

Add a few more topics to documentation updates

---

_includes/linux-binary-prereqs.md
v2.0/install-cockroachdb.md

Add 2.0 linux binary requirements

---

v2.0/demo-json-support.md

edits based on feedback from andy's run-through

JSON demo edits

---

v2.0/sql-dump.md
v2.0/use-the-built-in-sql-client.md

Add note about --user flag

---

v1.1/connection-parameters.md
v2.0/connection-parameters.md

Requested by @mberhault  in https://github.com/cockroachdb/docs/pull/2853#issuecomment-379309528

Clarify support for sslmode=allow,prefer

---

v2.0/grant.md

Fix broken Copy button

---

v2.0/install-cockroachdb.md

Reflects https://github.com/cockroachdb/cockroach/pull/24513
Reflects https://github.com/cockroachdb/cockroach/pull/24531
Informs https://github.com/cockroachdb/cockroach/issues/24625#issuecomment-380010285

Update the install dependency list

---

v1.1/known-limitations.md

1.1 known limitations: call out deletes in large txn limitation

---

v2.0/jsonb.md

JSON Operators edits

---

_includes/orchestration/kubernetes-limitations.md

To match https://github.com/cockroachdb/cockroach/pull/24601

Update statement on compatibility with old Kubernetes versions

---

v2.0/experimental-audit.md

the row count is also valid for mutation statements.
Requested by @dianasaur323

Clarify the audit log format

---

_includes/sql/v2.0/diagrams/experimental_audit.html
_includes/sql/v2.1/diagrams/experimental_audit.html
v2.0/experimental-audit.md
v2.1/experimental-audit.md

Changes:
- Update EXPERIMENTAL_AUDIT pages to use @mjibson's nicer diagrams from
https://github.com/cockroachdb/cockroach/pull/24295
- Update the v2.1 page to use the v2.1 included diagram

Update EXPERIMENTAL_AUDIT diagrams

---

_includes/aws-locations.md
_includes/gce-locations.md
v2.0/enable-node-map.md
v2.1/enable-node-map.md

Added GC locations to Enable Node Map doc

---

_includes/sql/v2.0/functions.md

Addresses #https://github.com/cockroachdb/cockroach/issues/24917

Correct 2.0 functions doc

---

v2.0/admin-ui-jobs-page.md
v2.1/admin-ui-jobs-page.md

Documented expandable job descriptions

---

v2.0/architecture/storage-layer.md

👋 
Just something that jumped out at me while reading your already amazing documentation.

Minor spelling correction in docs

---

v1.1/architecture/distribution-layer.md
v1.1/architecture/replication-layer.md
v1.1/architecture/storage-layer.md
v1.1/architecture/transaction-layer.md
v2.0/architecture/distribution-layer.md
v2.0/architecture/replication-layer.md
v2.0/architecture/transaction-layer.md
v2.1/architecture/distribution-layer.md
v2.1/architecture/replication-layer.md
v2.1/architecture/storage-layer.md
v2.1/architecture/transaction-layer.md

Follow-up to https://github.com/cockroachdb/docs/pull/3002

Spelling fixes

---

v1.0/recommended-production-settings.md
v1.1/recommended-production-settings.md
v2.0/recommended-production-settings.md
v2.1/recommended-production-settings.md

As brought up in the review of #2896.

Note that higher replication factors are recommended for local disks

---

_includes/orchestration/kubernetes-performance.md
_includes/sidebar-data-v1.1.json
_includes/sidebar-data-v2.0.json
_includes/sidebar-data-v2.1.json
v1.1/kubernetes-performance.md
v1.1/orchestrate-cockroachdb-with-kubernetes-insecure.md
v1.1/orchestrate-cockroachdb-with-kubernetes.md
v1.1/orchestration.md
v1.1/recommended-production-settings.md
v2.0/kubernetes-performance.md
v2.0/orchestrate-cockroachdb-with-kubernetes-insecure.md
v2.0/orchestrate-cockroachdb-with-kubernetes.md
v2.0/orchestration.md
v2.0/recommended-production-settings.md
v2.1/kubernetes-performance.md
v2.1/orchestrate-cockroachdb-with-kubernetes-insecure.md
v2.1/orchestrate-cockroachdb-with-kubernetes.md
v2.1/orchestration.md
v2.1/recommended-production-settings.md

I'm sure it could be better written or easier to understand, so feedback or suggestions would be great.
Other questions:
* Should we provide more numbers about how much each change helps on a basic workload like `kv`?
* Should we be more prescriptive about which set of changes are most recommended?
* Should we provide any more material, such as a preconstructed YAML file with easy-to-replace template parameters showing where a user's customized numbers should go?
Fixes #2265

Performance tuning guide for running on Kubernetes

---

v2.0/backup.md
v2.1/backup.md

sqlccl: ensure interleave hierarchy in BACKUP

---

v2.1/known-limitations.md

Requested by @andreimatei in https://github.com/cockroachdb/cockroach/pull/23373#issuecomment-383617998.

Remove a known limitation.

---

_includes/external-urls-v1.0.md
_includes/external-urls-v2.0.md
v1.0/backup.md
v1.0/restore.md
v1.1/backup.md
v1.1/import.md
v1.1/restore.md
v2.0/backup.md
v2.0/import.md
v2.0/restore.md
v2.1/backup.md
v2.1/import.md
v2.1/restore.md

Also update with GCS and custom CA settings/params.
Fixes #2170
Fixes #2400

consolidate external URL docs

---

_includes/faq/planned-maintenance.md
v2.0/monitoring-and-alerting.md
v2.1/monitoring-and-alerting.md

Document server.shutdown.drain_wait setting

---

_includes/sql/v2.0/diagrams/add_column.html
_includes/sql/v2.0/diagrams/add_constraint.html
_includes/sql/v2.0/diagrams/alter_column.html
_includes/sql/v2.0/diagrams/drop_column.html
_includes/sql/v2.0/diagrams/drop_constraint.html
_includes/sql/v2.0/diagrams/drop_index.html
_includes/sql/v2.1/diagrams/add_column.html
_includes/sql/v2.1/diagrams/add_constraint.html
_includes/sql/v2.1/diagrams/alter_column.html
_includes/sql/v2.1/diagrams/drop_column.html
_includes/sql/v2.1/diagrams/drop_constraint.html
_includes/sql/v2.1/diagrams/drop_index.html
v2.0/add-column.md
v2.0/add-constraint.md
v2.0/alter-column.md
v2.1/add-column.md
v2.1/add-constraint.md
v2.1/alter-column.md

Regenerate diagrams

---

v2.0/import.md
v2.1/import.md

document IMPORT CSV and BYTES format

---

scripts/issues-from-release-notes.py

@knz and/or @benesch, this is ready for a review.

Script to auto-generate docs issues from release notes file

---

_includes/sidebar-data-v2.1.json
_includes/sql/v2.1/diagrams/export.html
v2.1/export.md

EXPORT CSV doc

---

CONTRIBUTING.md
STYLE.md

We strive for clear, correct, and concise documentation! Here's our style guide.

Style Guide

---

v2.1/cluster-setup-troubleshooting.md
v2.1/debug-zip.md
v2.1/file-an-issue.md

added copy to clipboard to troubleshooting page

---

v2.1/initialize-a-cluster.md
v2.1/privileges.md
v2.1/recommended-production-settings.md
v2.1/start-a-node.md

Added clipboard functionality to deployment topics

---

_includes/sql/v2.0/diagrams/restore.html
_includes/sql/v2.1/diagrams/restore.html
v2.0/restore.md
v2.1/restore.md

Modified database restore example

---

v2.0/sql-faqs.md
v2.1/sql-faqs.md

Clarify the join FAQ.

---

v2.0/insert.md
v2.1/insert.md

Formatting cleanup on insert.md

---

_includes/faq/sql-query-logging.md
v2.0/query-behavior-troubleshooting.md
v2.0/sql-faqs.md
v2.1/query-behavior-troubleshooting.md
v2.1/sql-faqs.md

Add query logging faq content to query troubleshooting page

---

v2.0/import.md
v2.0/training/data-corruption-troubleshooting.md
v2.1/export.md
v2.1/import.md
v2.1/training/data-corruption-troubleshooting.md

Fix incorrect uses of import in 2.0/2.1 docs/training

---

_includes/sidebar.html

Make it possible to use external urls in sidenav again

---

STYLE.md

Updates based on Rich's feedback

Style Guide Updates

---

_includes/sql/v2.0/functions.md

Fixes https://github.com/cockroachdb/cockroach/issues/25833

Update 2.0 function descriptions

---

v2.0/demo-json-support.md
v2.1/demo-json-support.md

Text says YouTube, code says Github.

Fix error on 'JSON Support'

---

_includes/external-urls-v2.0.md
v2.1/export.md

Also  fix documentation of EXPORT's nullas option.
As called out in https://github.com/cockroachdb/cockroach/issues/25223#issuecomment-392212300

 Fix documentation of GCS AUTH for import/export docs

---

_includes/sidebar-data-v2.1.json
v2.1/admin-ui-access-and-navigate.md
v2.1/admin-ui-user-authentication.md

Closes #1582 
Initial draft for the Admin UI user auth changes. I have not tested the procedure yet, but opening the PR for structural review. @jseldess

Initial draft for Admin UI user auth changes

---

v2.1/cancel-job.md

Allow cancel job on schema changes

---

v2.0/create-view.md
v2.0/performance-best-practices-overview.md
v2.0/views.md
v2.1/create-view.md
v2.1/joins.md
v2.1/performance-best-practices-overview.md
v2.1/views.md

- Added info about lookup joins + consolidated info about join algorithms on the Join Expression page.
- Cleaned up style on headings and mentions of joins.
Closes #3153.

Lookup Joins

---

_includes/orchestration/kubernetes-upgrade-cluster.md
_includes/orchestration/kubernetes-upgrade-cluster_v2.1.md
v2.1/orchestrate-cockroachdb-with-kubernetes-insecure.md
v2.1/orchestrate-cockroachdb-with-kubernetes.md
v2.1/upgrade-cockroach-version.md

Document 2.1 rolling upgrade auto-finalization

---

_config.yml
_data/releases.yml
releases/v2.1.0-alpha.20180604.md
scripts/issues-from-release-notes.py

See https://github.com/cockroachdb/cockroach/issues/25351.

Release notes for v2.1.0-alpha.20180604

---

v2.1/cancel-query.md
v2.1/manage-long-running-queries.md

Cancel schema change update

---

STYLE.md
ci/vale/CockroachDB/Terminology.yml

Updates to the Style Guide + linter based on Fixit Day conversations

Updates to the Style Guide + linter

---

_config.yml
_data/releases.yml
_includes/sidebar-releases.json
releases/v2.0.3.md
v2.1/upgrade-cockroach-version.md

For https://github.com/cockroachdb/cockroach/issues/26696.

v2.0.3 release notes

---

v2.0/add-column.md

Building on changes in https://github.com/cockroachdb/docs/pull/3277 by @Princesso. Thank you!

Add copy-to-clipboard to 2.0 ADD COLUMN doc

---

v2.0/add-constraint.md

Taking over changes from https://github.com/cockroachdb/docs/pull/3278. Thanks to @Kolokodess!

Add copy-to-clipboard to add-constrain

---

_includes/prod_deployment/insecure-scale-cluster.md
_includes/prod_deployment/insecure-start-nodes.md
_includes/prod_deployment/insecurecockroachdb.service
_includes/prod_deployment/secure-scale-cluster.md
_includes/prod_deployment/secure-start-nodes.md
_includes/prod_deployment/securecockroachdb.service
v2.1/deploy-cockroachdb-on-digital-ocean-insecure.md
v2.1/deploy-cockroachdb-on-digital-ocean.md

Closes #1772 
@jseldess @mberhault This is an initial draft of the systemd process. For now, I have updated only the Digital Ocean deployment guide. Once the content is finalized, I will port the changes to the other deployment guides.
To-Do:
- Figure out where to place the sample configuration templates
- Edit the "Scale the cluster" sections
- Port content to other deployment guides
(Update: All To-Dos completed)
Future to-dos:
- Figure out how backup/restore and upgrades work with systemd

Initial draft for systemd process

---

v2.0/orchestrate-cockroachdb-with-kubernetes.md
v2.1/orchestrate-cockroachdb-with-kubernetes.md

Follow-up to https://github.com/cockroachdb/docs/pull/2795

Correct response for csr approval

---

_includes/sidebar-data-v2.1.json
v2.1/backup.md
v2.1/change-data-capture.md
v2.1/create-changefeed.md
v2.1/pause-job.md

Change Data Capture

---

v2.0/demo-automatic-rebalancing.md

in step 1
there is '--host=localhost'
need back slash at the end to continue command

back slash needed

---

v1.1/demo-automatic-rebalancing.md
v1.1/demo-fault-tolerance-and-recovery.md
v2.1/demo-automatic-rebalancing.md
v2.1/demo-fault-tolerance-and-recovery.md

Follow-up to https://github.com/cockroachdb/docs/pull/3347
and https://github.com/cockroachdb/docs/pull/3348.

Add missing backslashes

---

v2.1/create-changefeed.md

Add pause, resume, cancel info to CREATE CHANGEFEED

---

_includes/sidebar-data-v2.0.json
_includes/sidebar-data-v2.1.json
v2.0/performance-benchmarking-with-tpc-c.md
v2.1/performance-benchmarking-with-tpc-c.md
v2.1/performance-benchmarking.md

Performance Benchmarking

---

_includes/settings/v2.1/settings.md
_includes/sql/v2.1/aggregates.md
_includes/sql/v2.1/functions.md
_includes/sql/v2.1/operators.md

Fixes #3331 
Fixes #3217 
Fixes #3211 
Fixes #3339 
Fixes #3320 
Fixes #3332

Update 2.1 functions, operators, and settings
