_includes/v19.1/orchestration/start-cockroachdb-helm-insecure.md
_includes/v19.1/orchestration/start-cockroachdb-helm-secure.md
_includes/v19.2/orchestration/start-cockroachdb-helm-insecure.md
_includes/v19.2/orchestration/start-cockroachdb-helm-secure.md

Fixes #5654 
Also, slightly clarified the Helm install step. Originally the link to the install steps came before the RBAC steps, which I found misleading. In my run-through, I clicked that link first and tried `helm init` before creating the service account, which failed install and forced me to backtrack. Here, I repositioned that link after the RBAC steps.

update Helm instructions for k8s 1.16.0

---

v19.2/configure-zone.md

Updated permissions doc for CONFIGURE ZONE

---

v19.1/sql-statements.md
v19.2/sql-statements.md

@lhirata, in addition to this, I think we need to make sure it's clear on the CDC overview and other related docs how the enterprise and core versions differ. 
Fixes #5718

Clarify changefeeds on sql statement list

---

_includes/v19.2/misc/session-vars.html
v19.2/cost-based-optimizer.md

Fixes #5693. 
The `optimizer` setting is deprecated (i.e. you literally can't change this setting in 19.2, and if you try you get an error).
- Removed "Turn the optimizer off" section.
- Removed "optimizer" session variable.

Removed optimizer setting documentation

---

v19.2/date.md
v19.2/known-limitations.md
v19.2/migrate-from-oracle.md

Fixes #4887.
- Removed known limitation "Conversion of integers to date/time values". The tracking issue (cockroachdb/cockroach/issues/20136) has been resolved.
- Updated size of supported `DATE` column values from 8 bytes to 16 bytes.
- Added note about PG-compatible dates.
Please review for technical accuracy, and please advise if we need to update the documentation in other places to reflect this change.

PG-compatible dates

---

_includes/v19.2/known-limitations/import-high-disk-contention.md
v19.2/import.md
v19.2/known-limitations.md
v19.2/upgrade-cockroach-version.md

- Call out that it's not allowed in import docs.
- Mention that imports should've be in progress when starting
a rolling upgrade.
Fixes #5703.

No import rolling upgrade

---

_includes/v19.2/sql/crdb-internal-partitions-example.md
_includes/v19.2/sql/crdb-internal-partitions.md
v19.2/configure-replication-zones.md
v19.2/demo-low-latency-multi-region-deployment.md
v19.2/partitioning.md
v19.2/show-partitions.md
v19.2/topology-geo-partitioned-leaseholders.md
v19.2/topology-geo-partitioned-replicas.md

Fixes #4796.
Include files created:
- Tip
- Details and examples
Tip include added to:
- SHOW PARTITIONS page
- Define Table Partitions page
- Geo-partitioning Demo
Details and examples include added to:
- SHOW PARTITIONS page
**Note**: This table, and others, will be documented in more detail in a forthcoming `crdb_internal` PR (see #2957).

crdb_internal.partitions tip

---

v19.2/explain.md
v19.2/joins.md

Document new EXPLAIN flag for lookup joins

---

v19.2/upgrade-cockroach-version.md

Fixes #5672. 
Changes include:
- Upgrade "checklist" added as post-upgrade section. 
- Range merge queue cluster setting added as first item in checklist.
- "Troubleshooting" section no longer a step.
Feel free to suggest more settings for the checklist. We can always add more after merging this change, as they come up.
FYI:
I checked [v19.1 Known Limitations](https://www.cockroachlabs.com/docs/v19.1/known-limitations.html), and I found that only a few of the tracking issues listed there have been resolved. AFAICT, none required changing cluster settings for workarounds that might need checking after an upgrade.

Post-upgrade checklist

---

v19.1/delete.md
v19.2/cost-based-optimizer.md
v19.2/delete.md
v19.2/update.md

Since almost everything is planned by the CBO in 19.2, maintaining an explicit list was getting unwieldy and is probably no longer necessary.
Fixes #5284.

Remove list of supported SQL from CBO docs

---

_includes/sidebar-data-v19.2.json
_includes/v19.2/sql/diagrams/import_into.html
v19.2/import-into.md
v19.2/insert.md
v19.2/performance-best-practices-overview.md
v19.2/performance-tuning-insecure.md
v19.2/performance-tuning.md
v19.2/sql-faqs.md
v19.2/sql-statements.md

Add references to IMPORT INTO in relevant docs

---

v19.2/interval.md

Fixes #5634. 
- Added `INTERVAL(6)` as a no-op alias for `INTERVAL`.

INTERVAL(6) alias

---

v1.0/timestamp.md
v1.1/timestamp.md
v19.1/timestamp.md
v19.2/timestamp.md
v2.0/timestamp.md
v2.1/timestamp.md

The timestamp docs specified that our TIMESTAMPTZ datatype stores a time
zone offset. This is not true. It always stores the timestamp in UTC.
This is explicitly stated further down on the same page: "However, it is
conceptually important to note that TIMESTAMPTZ does not store any time
zone data."
For some reason this was correct in the v2.0 docs and earlier but
incorrect in later docs.

Fix inaccurate TIMESTAMPTZ description

---

v19.2/timestamp.md

This reverts commit 4d287bdc7e354c3879ccede62211de51d0ad45e6 (PR #5535).
See https://github.com/cockroachdb/cockroach/pull/42285#issuecomment-551292412

Revert "- Add doc about specifying precision for timestamp objects"

---

_includes/v19.2/faq/auto-generate-unique-ids.html
v19.2/performance-best-practices-overview.md
v19.2/query-behavior-troubleshooting.md

Specifically:
- Updated 'Unique ID Best Practices' section with a table showing pros/cons of each approach for generating PKs / unique IDs: multi-column, UUID, serial ints
- Added a new approach describing how to get good performance with composite PKs
- Expanded our description of how hotspots can be caused by monotonically increasing index keys or table primary keys
Related to #4863

Update unique ID section of perf best practices

---

_config_cockroachcloud.yml
_config_cockroachdb.yml

As soon as we have 20.1 docs, `/dev` will point to them instead.
Fixes #5844.

Temporarily direct `/dev` urls to 19.2

---

v19.1/backup.md
v19.1/import.md
v19.1/restore.md
v19.2/backup.md
v19.2/import-into.md
v19.2/import.md
v19.2/restore.md

Add note to BACKUP, RESTORE, IMPORT, IMPORT INTO that the statement returns when the job is finished or if it encounters an error.
Closes #5240.

Add note about when BACKUP, etc. commands return

---

v19.1/recommended-production-settings.md
v19.2/recommended-production-settings.md

Add transaction retry info to production checklist

---

_includes/version-nav.html
_plugins/flavor_selector.rb
_plugins/versions/generator.rb

The FlavorSelector plugin needs to run before the JekyllVersions plugin.
We were getting lucky previously with the right order, but For some
reason enabling the sitemap plugin caused us to get unlucky.
Use more granular plugin priorities to enforce exactly the right
ordering.

Fix Jekyll plugin ordering

---

_includes/sidebar-data-v19.2.json
_includes/v19.2/sql/diagrams/alter_index_partition_by.html
v19.2/alter-database.md
v19.2/alter-index.md
v19.2/alter-partition.md
v19.2/alter-range.md
v19.2/alter-table.md
v19.2/configure-zone.md
v19.2/online-schema-changes.md
v19.2/partition-by.md
v19.2/show-partitions.md
v19.2/sql-statements.md

- Add landing page for ALTER PARTITION that references the only
relevant subcommand, CONFIGURE ZONE.
- Update PARTITION BY to cover by tables and indexes. Also add
this statement to the SQL statements list and cross-reference
it more.
- Update other ALTER landing pages for usability and consistency.
Fixes #5869.
Fixes #5868.

Improve SQL reference on partitioning

---

_includes/head.html
v19.1/index.md
v19.2/index.md
v2.1/index.md
v20.1/index.md

Previously, the title and description tags on CC docs pages
were referencing CockroachDB, which we think was negatively
effective SEO. This PR adds logic to replace "CockroachDB"
with "CockroachCloud" in the meta title and desciption fields
on pages with the site.cockroachcloud variable, which gets
added to pages built with _config_cockroachcloud.yml. It
also adds customer, and more descriptive, meta descriptions
for CC and CRDB docs landing pages.
Fixes #5876.

CC SEO fix

---

_includes/v19.1/orchestration/kubernetes-expand-disk-size.md
_includes/v19.1/orchestration/start-cockroachdb-helm-insecure.md
_includes/v19.1/orchestration/start-cockroachdb-helm-secure.md
_includes/v19.1/orchestration/start-cockroachdb-insecure.md
_includes/v19.1/orchestration/start-cockroachdb-secure.md
_includes/v19.2/orchestration/kubernetes-expand-disk-size.md
_includes/v19.2/orchestration/start-cockroachdb-helm-insecure.md
_includes/v19.2/orchestration/start-cockroachdb-helm-secure.md
_includes/v19.2/orchestration/start-cockroachdb-insecure.md
_includes/v19.2/orchestration/start-cockroachdb-secure.md
_includes/v20.1/orchestration/kubernetes-expand-disk-size.md
_includes/v20.1/orchestration/start-cockroachdb-helm-insecure.md
_includes/v20.1/orchestration/start-cockroachdb-helm-secure.md
_includes/v20.1/orchestration/start-cockroachdb-insecure.md
_includes/v20.1/orchestration/start-cockroachdb-secure.md
v19.1/orchestrate-cockroachdb-with-kubernetes.md
v19.2/orchestrate-cockroachdb-with-kubernetes.md
v20.1/orchestrate-cockroachdb-with-kubernetes.md

Fixes #5459
- For the memory adjustments, I documented the second workaround that was listed in the issue. I was able to execute the steps for both Helm and config, but wasn't sure how to verify that the new cache and SQL memory size values were actually in effect (the Admin UI doesn't appear to reflect these limits). Will possibly need a technical review. If we also want to describe the first workaround, I will need some more technical context on this.
- For expanding the persistent volume claims, I was able to increase the disk sizes in production (GKE) even after manually setting `allowVolumeExpansion` to `false`. I documented the requirement to set this to `true` anyway, but could use clarity from an engineer on why that might have happened. Also, because I wasn't able to test this by …

K8s prod requirements

---

v19.2/index.md
v20.1/index.md

Add Performance page. Also add link to Cockroach U and SQL Tuning tutorial,
to keep first row symmetrical.
This is just a stop-gap. it doesn't bring the docs landing page in line
with the sidenav. The Docs team is planning an offsite to more
broadly rethink the docs info architecture, so we should wait until that
outcome is clear before more dramatically revamping the landing page.
Fixes #5839.

Tweak docs landing page

---

v19.1/upgrade-cockroach-version.md
v19.2/upgrade-cockroach-version.md
v20.1/upgrade-cockroach-version.md

Made the Kubernetes instructions easier to discover & access in our upgrade docs.
Relates to #5780.

link upgrades doc to Kubernetes instructions

---

v19.2/constraints.md
v19.2/drop-index.md
v20.1/constraints.md
v20.1/drop-index.md

Fixes #5916. 
No diagram changes needed.

CASCADE no longer needed to drop UNIQUE INDEX

---

v19.1/constraints.md
v19.2/constraints.md
v20.1/constraints.md

The y of "Foreign key" was not included in the code-formatted text.

Fix typo in constraints page

---

Makefile

htmltest assumes the _site directory has a working site layout. When building with just jekyll (i.e., not using netlify/build or netlify/local), the cloud directory is not in the expected place, so things break.
Add this make target so people can just type "make htmltest" which uses the docker builder to simulate exactly what happens on netlify, which htmltest can then check since things are in the expected locations.
Fixes #4093
Closes #6157

teach make test to build

---

.htmltest.yml

Resolves #3833.
The current default of 128 has a tendency to reach "too many files at
once" when attempting to `os.Stat` on local setups. I don't think the
speedup is too important, so setting to a lower setting of 16.

change htmltest DocumentConcurrencyLimit to 16

---

_includes/v19.1/sql/diagrams/drop_index.html
_includes/v19.1/sql/diagrams/rename_index.html
_includes/v19.1/sql/diagrams/split_index_at.html
_includes/v19.2/sql/diagrams/alter_index_partition_by.html
_includes/v19.2/sql/diagrams/drop_index.html
_includes/v19.2/sql/diagrams/rename_index.html
_includes/v19.2/sql/diagrams/split_index_at.html
_includes/v19.2/sql/diagrams/unsplit_index_at.html
_includes/v2.0/sql/diagrams/drop_index.html
_includes/v2.0/sql/diagrams/rename_index.html
_includes/v2.0/sql/diagrams/split_index_at.html
_includes/v2.1/sql/diagrams/drop_index.html
_includes/v2.1/sql/diagrams/rename_index.html
_includes/v2.1/sql/diagrams/split_index_at.html
_includes/v20.1/sql/diagrams/alter_index_partition_by.html
_includes/v20.1/sql/diagrams/drop_index.html
_includes/v20.1/sql/diagrams/rename_index.html
_includes/v20.1/sql/diagrams/split_index_at.html
_includes/v20.1/sql/diagrams/unsplit_index_at.html

Previously, some of the syntax diagrams would indicate that table_name
was required, and index_name was optional. However, the opposite is true.
fixes #5948

Fix diagrams for 'table_name @ index_name' syntax

---

v19.1/install-cockroachdb-linux.html
v19.1/install-cockroachdb-mac.html
v19.2/install-cockroachdb-linux.html
v19.2/install-cockroachdb-mac.html
v2.0/install-cockroachdb.html
v2.1/install-cockroachdb-linux.html
v2.1/install-cockroachdb-mac.html
v20.1/install-cockroachdb-linux.html
v20.1/install-cockroachdb-mac.html

Clarify go compiler version requirements for all releases.

---

v19.2/secure-a-cluster.md

Noticed this link wasn't rendering properly in the "secure a cluster" section:
Single missing `[` to fix it up. 😄

fix link to geo-partitioning

---

v19.2/create-table-as.md
v19.2/secure-a-cluster.md
v19.2/show-locality.md
v19.2/show-partitions.md
v19.2/start-a-local-cluster-in-docker-linux.md
v19.2/start-a-local-cluster-in-docker-mac.md
v19.2/start-a-local-cluster-in-docker-windows.md
v19.2/start-a-local-cluster.md
v20.1/create-table-as.md
v20.1/secure-a-cluster.md
v20.1/show-locality.md
v20.1/show-partitions.md
v20.1/start-a-local-cluster-in-docker-linux.md
v20.1/start-a-local-cluster-in-docker-mac.md
v20.1/start-a-local-cluster-in-docker-windows.md
v20.1/start-a-local-cluster.md

Follow-up to https://github.com/cockroachdb/docs/pull/6239.

Fix links to geo-partitioning tutorial

---

v19.1/install-cockroachdb-linux.html
v19.1/install-cockroachdb-mac.html
v19.2/install-cockroachdb-linux.html
v19.2/install-cockroachdb-mac.html
v2.0/install-cockroachdb.html
v2.1/install-cockroachdb-linux.html
v2.1/install-cockroachdb-mac.html
v20.1/install-cockroachdb-linux.html
v20.1/install-cockroachdb-mac.html

Follow-up edits for https://github.com/cockroachdb/docs/pull/6132

---

v19.1/limit-offset.md
v19.1/selection-queries.md
v19.2/limit-offset.md
v19.2/selection-queries.md
v20.1/limit-offset.md
v20.1/selection-queries.md

- Explain difference between keyset pagination and LIMIT/OFFSET
- Show examples of the former being fast and the latter being slow
- Show how to use EXPLAIN to check why the difference exists
- Add warning to LIMIT/OFFSET docs recommending keyset pagination
- ... all of the above for 19.1, 19.2, 20.1 docs
Fixes #3743

Update pagination docs to use keyset / seek method

---

_includes/v19.2/orchestration/kubernetes-prometheus-alertmanager.md
_includes/v19.2/orchestration/kubernetes-scale-cluster.md
_includes/v19.2/orchestration/start-cockroachdb-local-insecure.md
_includes/v19.2/orchestration/start-cockroachdb-local-secure.md
_includes/v19.2/orchestration/start-cockroachdb-secure.md
_includes/v19.2/orchestration/test-cluster-secure.md
_includes/v20.1/orchestration/kubernetes-prometheus-alertmanager.md
_includes/v20.1/orchestration/kubernetes-scale-cluster.md
_includes/v20.1/orchestration/kubernetes-upgrade-cluster.md
_includes/v20.1/orchestration/start-cockroachdb-local-insecure.md
_includes/v20.1/orchestration/start-cockroachdb-local-secure.md
_includes/v20.1/orchestration/start-cockroachdb-secure.md
_includes/v20.1/orchestration/test-cluster-secure.md
v19.2/orchestrate-a-local-cluster-with-kubernetes-insecure.md
v19.2/orchestrate-a-local-cluster-with-kubernetes.md
v19.2/orchestrate-cockroachdb-with-kubernetes.md
v20.1/orchestrate-a-local-cluster-with-kubernetes-insecure.md
v20.1/orchestrate-a-local-cluster-with-kubernetes.md
v20.1/orchestrate-cockroachdb-with-kubernetes.md

Advances #4696. Arguably blocked by #42173. 
Custom CA steps are working for authenticating and initializing the CRDB cluster and running SQL shell (steps 1-5) in the K8s deployment guide. 
The Monitor step (6) still isn't compatible: Our current Prometheus and Alertmanager YAMLs only request certs from K8s. 
I also ran into an `ImagePullBackOff` error with the Upgrade step (7), which may be unrelated.

draft custom CA steps for K8s deployment

---

v19.2/training/orchestration-with-kubernetes.md
v20.1/training/orchestration-with-kubernetes.md

Instructions mention an option to delete client pod but if one chooses to skip the step, there's an additional pod lingering in the clean up step. This adds an explicit step to delete the pod.

cmd to delete cockroachdb-client-secure is missing

---

_includes/v19.2/sql/vectorized-support.md
_includes/v20.1/sql/vectorized-support.md
v19.2/array.md
v19.2/bit.md
v19.2/collate.md
v19.2/data-types.md
v19.2/date.md
v19.2/decimal.md
v19.2/inet.md
v19.2/interval.md
v19.2/jsonb.md
v19.2/serial.md
v19.2/time.md
v19.2/timestamp.md
v19.2/vectorized-execution.md
v20.1/array.md
v20.1/bit.md
v20.1/collate.md
v20.1/data-types.md
v20.1/date.md
v20.1/decimal.md
v20.1/inet.md
v20.1/interval.md
v20.1/jsonb.md
v20.1/serial.md
v20.1/time.md
v20.1/vectorized-execution.md

Fixes #5947.
- Added column to data type landing page for vectorized support
- Added note to page for each data type not supported by vectorized execution

Improved vectorized support docs

---

v19.2/gssapi_authentication.md

Docs were mistakenly telling the user to get a ticket for the postgres user on the client rather than the db user.

update to get ticket for db user on client

---

v19.2/gssapi_authentication.md
v20.1/gssapi_authentication.md

Clarified instructions on how and where to use keytab files, and added directions on how to create a merged keytab for multiple cluster endpoints

Fix keytab directions

---

_config_base.yml
_data/releases.yml
releases/v20.1.0-alpha.20200123.md

We released on 1/30, so the docs look for binaries, etc.,
using that date. However, the release is tagged with 1/23.
Thus, broken links. This PR corrects that. However, this
results in a somewhat confusing descrepancy between the
release date and the release name.
Fixes #6405.

Correct name of latest alpha release

---

_includes/v19.1/misc/session-vars.html
_includes/v19.2/misc/session-vars.html
_includes/v20.1/misc/session-vars.html

In CockroachDB 19.1+ , the variable `experimental_reorder_joins_limit`
is now known as `reorder_joins_limit`.
Fixes #6174.

Clean up outdated join limit variable usages

---

_includes/v19.2/app/django-basic-sample/urls.py
_includes/v19.2/app/insecure/django-basic-sample/urls.py
_includes/v20.1/app/django-basic-sample/urls.py
_includes/v20.1/app/insecure/django-basic-sample/urls.py

django.conf.urls.url is deprecated and works differently from
django.urls.path. The current example is broken.

Fix Django urlpatterns

---

v19.2/remove-nodes.md
v20.1/remove-nodes.md

Fixes #4915.
I took a small leap and added similar guidance for the "5-node cluster with 5-way replication for a specific table" example.
I did not create the new section heading (4-node cluster with 3-way replication) suggested in the issue, as I felt it would send a mixed signal in terms of how that section is conceptually organized.

improve decommission node guidance

---

v19.2/timestamp.md
v20.1/data-types.md
v20.1/set-vars.md
v20.1/time.md
v20.1/timestamp.md

Fixes #5964.
- Added `TIMETZ` to v20.1 docs (`time.md` and `data-types.md`).
- Updated example output for `TIME` data type.
@otan for technical review.

TIMETZ docs

---

v20.1/joins.md
v20.1/subqueries.md

Fixes #5990.
@chrisseto Adding you for technical review
- Added a section on `LATERAL` subqueries to the "Subqueries" documentation page.
- Added a section on `LATERAL` subqueries to the "Join Expressions" documentation page. This section really only links to the main section, on the "Subqueries" page.

LATERAL subquery docs

---

v19.2/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
v20.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md

Fixes #6389. 
In the interest of expediency, I added 1) a link to the new GCP global access instructions and 2) a note that the tutorial will be revised to utilize global access (which I plan to split into a separate issue).

update GCP load balancer restrictions

---

_includes/v20.1/sql/diagrams/delete.html
_includes/v20.1/sql/diagrams/insert.html
_includes/v20.1/sql/diagrams/select.html
_includes/v20.1/sql/diagrams/update.html
_includes/v20.1/sql/diagrams/upsert.html
_includes/v20.1/sql/diagrams/with_clause.html
v20.1/common-table-expressions.md

Recursive CTE docs...
Fixes #5956.
- Updated 20.1 `delete`, `insert`, `select`, `update`, `upsert`, and `with_clause` diagrams.
- Added new section and examples to 20.1 "Common Table Expressions" doc page.
**Note** 
I did not update the `stmt_block` diagram (the primary SQL grammar chart), due to an issue with the [Railroad Diagram Generator](https://bottlecaps.de/rr/ui) API. This will block this PR from being merged, as other diagrams reference this chart. See #6472 for more details.

Recursive CTE docs

---

_config_cockroachcloud.yml
netlify/build

Previously, we would build the CC pages to _site/cockroachcloud
and then have Netlify move the pages to _site/docs/cockroachcloud.
Instead, we now use the latter as the destination directly in the
_config_cockroachcloud.yml.

Simplify destination for CC pages

---

_includes/v19.2/known-limitations/cdc.md
_includes/v20.1/known-limitations/cdc.md
v19.2/change-data-capture.md
v19.2/create-changefeed.md
v20.1/change-data-capture.md
v20.1/create-changefeed.md

Edit CDC examples to show more than one table in a changefeed

---

_data/advisories.yml
_includes/sidebar-releases.json
_redirects
advisories/a30821.md
advisories/a42567.md
advisories/a43870.md
advisories/a44166.md
advisories/a44299.md
advisories/a44348.md
advisories/index.md

New section advisories with per-advisory pages

---

v19.2/authorization.md
v19.2/create-role.md
v19.2/grant.md
v20.1/authorization.md
v20.1/create-role.md
v20.1/grant.md

Closes #5925
To-Do: Backport to 19.2

CRDB authorization overview doc overhaul

---

v19.2/build-a-python-app-with-cockroachdb-django.md
v20.1/build-a-python-app-with-cockroachdb-django.md

Fixes #6375.
Added note to 19.2 and 20.1 Django-ORM "Build an App" tutorial about versioning.

Django ORM installation instructions updated for versioning

---

v19.2/cluster-setup-troubleshooting.md
v20.1/cluster-setup-troubleshooting.md

Fixes #4475.
- Add new 'Node liveness' section to the 'Troubleshoot cluster setup'
page, including:
- What it is
- How the system checks for it
- Causes of common problems with node liveness (overloaded disk /
busted network connectivity)

Update cluster troubleshooting with node liveness

---

v1.0/column-families.md
v1.1/column-families.md
v19.1/column-families.md
v19.2/column-families.md
v2.0/column-families.md
v2.1/column-families.md
v20.1/column-families.md

Fixes #5994. 
- Updated output on 20.1 column families page.
- Added paragraph to 20.1 column families page stating that secondary indexes support column families.
- Added note to versions prior to 20.1 about secondary indexes *not* supporting column families.

Secondary indexes support column families in 20.1

---

v20.1/vectorized-execution.md

Fixes #6452.
Added `TIMESTAMPTZ` to list of supported data types for vectorized execution.
Follow-up to https://github.com/cockroachdb/docs/pull/6327.

TIMESTAMPTZ vectorized support.

---

v20.1/cockroach-demo.md

Fixes #6070.
Added syntax table and examples for `cockroach demo` cluster SQL `\demo_node` commands.

\demo_node docs

---

_includes/sidebar-data-v19.2.json
_includes/sidebar-data-v20.1.json
v19.2/install-client-drivers.md
v20.1/install-client-drivers.md

Upleveled Driver/ORM support overview in "Develop" section.
I also removed this from the SQL Reference section, as this isn't reference material.

Uplevel Driver/ORM support in Developer Guide

---

_includes/v19.2/misc/session-vars.html
_includes/v20.1/misc/session-vars.html
v19.2/show-vars.md
v20.1/show-vars.md

Touches #5819 and #6189.  
- Updated output for `SHOW ALL` in `SHOW <var>` doc pages for 19.2 and 20.1.
- Updated `session-vars.html` table for 19.2 and 20.1
@nvanbenschoten Adding you for brief tech review, as you made https://github.com/cockroachdb/cockroach/pull/26433.

Updated session vars for 19.2 and 20.1

---

v20.1/interval.md

Fixes #6599 
Fixes #6600 
Fixes #6601 
Fixes #6602 
Changes to 20.1 `INTERVAL` docs:
- Updated example output.
- Removed 19.1 upgrade note.
@otan It looks like https://github.com/cockroachdb/cockroach/pull/43379 fixes some bugs with CRDB's `INTERVAL`. Any reason we should call these changes out in the docs?

Interval docs refresh

---

_includes/v20.1/sql/diagrams/create_index.html
_includes/v20.1/sql/diagrams/sort_clause.html
v20.1/query-order.md

Fixes #5911. 
- Updated `create_index` and `sort_clause` diagrams. `create_index` and `sort_clause` BNF files were updated in https://github.com/cockroachdb/cockroach/pull/41544/files. Due to the exclusion of `opt_nulls_order` in `diagrams.go`, the generated diagram for `create_index` did not really change. Adding latest diagrams generated for each of the BNF files, for completeness.
- Added note about CRDB support for `NULLS FIRST|LAST` being for compatibility with PostgreSQL.
Adding you, @yuzefovich, since you were first reviewer on https://github.com/cockroachdb/cockroach/pull/41544.

NULLS FIRST|LAST doc

---

v19.2/cockroachcloud-upgrade-policy.md
v20.1/cockroachcloud-upgrade-policy.md

When mentioning minor versions in the CC upgrade policy,
we were linking to testing releases (alpha/beta), which is
something different. We don't have distinct links for major
and minor versions of stable releases, so for now,
we're just linking to the list of "production" releases
in both cases.

Don't link to testing releases for minor versions

---

v20.1/cockroach-start.md

Fixes #5915 and #6019.
- Add docs for `--storage-engine` flag on node start, which can
be `pebble`, `rocksdb`, or `default`, which makes the
`--storage-engine` flag sticky for future runs when no engine
is specified

Document storage engine flag

---

v19.1/support-resources.md
v19.2/support-resources.md
v20.1/support-resources.md

Fixes #6686.
- Update 'Support Resources' page with links to Slack and the Support
Portal.  Remove old Gitter link.
- Apply changes to versions: 19.1, 19.2, 20.1.

Update support information

---

v20.1/manage-long-running-queries.md

I missed this page when updating `SHOW QUERIES` example output in #6764, for #6189.

Updated example output in Manage Long-Running Queries

---

Makefile
netlify/build

This gives us greater insight into errors building the site.
For example, where there's a JSON syntax error in a sidenav
file, without this flag, there's no clear indication.

Add --trace flag to docs build commands

---

v20.1/comment-on.md
v20.1/show-create.md
v20.1/show-tables.md

Fixes #6609.
Added examples of `COMMENT ON TABLE` in `SHOW CREATE TABLE` output to:
- `COMMENT ON` page
- `SHOW TABLES` page
- `SHOW CREATE` page

Added examples of COMMENT ON TABLE in SHOW CREATE TABLE output

---

v20.1/cockroach-demo.md

- Document the --empty flag.
- Document the kv and ycsb datasets.
- Document the --cache and --max-sql-memory flags.
Fixes #6623.

Various updates to cockroach demo docs

---

v20.1/alter-primary-key.md

Fixes #6736.
Fixes #6728. 
- Added details section to ALTER PRIMARY KEY page
- Removed gating from primary key changes (https://github.com/cockroachdb/cockroach/pull/45753)

Updates to ALTER PRIMARY KEY documentation

---

v1.0/build-a-python-app-with-cockroachdb-sqlalchemy.md
v1.1/build-a-python-app-with-cockroachdb-sqlalchemy.md
v19.1/build-a-python-app-with-cockroachdb-sqlalchemy.md
v19.2/build-a-python-app-with-cockroachdb-sqlalchemy.md
v19.2/install-client-drivers.md
v2.0/build-a-python-app-with-cockroachdb-sqlalchemy.md
v2.1/build-a-python-app-with-cockroachdb-sqlalchemy.md
v20.1/build-a-python-app-with-cockroachdb-sqlalchemy.md
v20.1/install-client-drivers.md

See https://github.com/cockroachdb/cockroachdb-python/pull/88 and
https://github.com/cockroachdb/cockroachdb-python/issues/87.
CRDB's SQLAlchemy dialect requires the use of psycopg2. Currently,
it is not included in our default install instructions. This PR adds
text to do so, as well as an information prompt in case the user does
not require psycopg2.

Fix sqlalchemy install in docs to include psycopg2 by default

---

v19.1/remove-nodes.md
v19.2/remove-nodes.md
v20.1/monitoring-and-alerting.md
v20.1/remove-nodes.md

Update health endpoint doc to clarify that a node is considered
unready when it can no longer accept new SQL connectsions, for
example, when shutting down. This excludes decomissioning since
a decommissioned node, although absent of data, can still serve
as a SQL gateway.
Fixes #6589.

Decommissioned nodes are considered ready

---

_includes/v19.1/misc/chrome-localhost.md
_includes/v19.1/orchestration/monitor-cluster.md
_includes/v19.1/orchestration/test-cluster-secure.md
_includes/v19.2/misc/chrome-localhost.md
_includes/v19.2/orchestration/monitor-cluster.md
_includes/v19.2/orchestration/test-cluster-secure.md
_includes/v20.1/misc/chrome-localhost.md
_includes/v20.1/orchestration/monitor-cluster.md
_includes/v20.1/orchestration/test-cluster-secure.md
v19.1/admin-ui-overview.md
v19.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
v19.1/secure-a-cluster.md
v19.2/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
v19.2/secure-a-cluster.md
v20.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
v20.1/secure-a-cluster.md

- Add a callout about enabling a required Chrome setting.
Made this an per-version include and included across
all relevant pages.
- Add missing semicolon to SQL statement.
Fixes #6946.
Incorporates https://github.com/cockroachdb/docs/pull/6868.

Document how to access secure Admin UI from Chrome

---

v19.2/cockroach-commands.md
v20.1/cockroach-commands.md
v20.1/cockroach-demo.md

- New `--insecure=false` option starts a secure demo cluster.
- In a multi-node demo cluster, `--with-load` now balances load across nodes.
Fixes #6930.
Fixes #6627.

Cockroach demo updates

---

_includes/sidebar-data-v20.1.json
_includes/v20.1/misc/external-urls.md
v20.1/cockroach-commands.md
v20.1/cockroach-nodelocal-upload.md
v20.1/import-into.md
v20.1/import.md
v20.1/show-backup.md

Changes:
- Added `cockroach-nodelocal-upload.md`, which explains the new command
- Added `cockroach nodelocal upload` to the sidebar nav
- Added `cockroach nodelocal upload` to `cockroach-commands.md`
- Updated existing nodelocal URI examples / notes to include a `nodeID`, which is now required
Closes #6010, #6788.

Add cockroach nodelocal upload docs

---

_includes/v19.2/sql/disk-spilling-ops.md
v19.1/experimental-features.md
v19.2/experimental-features.md
v19.2/vectorized-execution.md
v20.1/data-types.md
v20.1/experimental-features.md
v20.1/vectorized-execution.md

Fixes #6464. 
Fixes #6441.  
Fixes #6921.
Also, removes documentation about the private cluster settings for vectorized execution.
- Removed references to `vectorize` cluster setting (this cluster setting is not public), in favor of the `vectorize` session variable.
- Added unordered aggregations to list of experimental disk-spilling operations in 19.2 (this has been resolved for 20.1, which will be documented in a forthcoming PR on 20.1 vectorized updates to disk-spilling operations).
- Fixed some typos.
- Added note about the vectorized engine skipping unused columns of unsupported data (#6464 and #6441).
- Added `INTERVAL` to list of supported data types in 20.1.

Updates to vectorized execution documentation

---

_includes/v20.1/prod-deployment/backup.sh
_includes/v20.1/sql/diagrams/backup.html
_includes/v20.1/sql/diagrams/restore.html
v20.1/backup-and-restore.md
v20.1/backup.md
v20.1/restore.md

backup-and-restore.md
- Changed examples to focus on full cluster backup / restore
- Edited script to be for a full cluster example
- Finish editing script to account for new incremental backup syntax 
backup.md
- Updated SQL diagram 
- Added information about full cluster backup
- Added new/easier incremental backup syntax (where you just backup to the same destination as the full backup)
- Changed backup examples to be focused primarily on how to do a full cluster backup
- Minor format / language cleanup
restore.md
- Updated SQL diagram
- Added information about full cluster restore
- Added new/easier restore from incremental backup syntax (where you just restore from the one destination)
- Changed restore examples to be focused primarily on how to do a full cluster restore (if …

Full cluster BACKUP / RESTORE + incremental backups

---

v20.1/time.md

Fixes #6619. 
- Added paragraph to `TIME/TIMETZ` page that calls out support for `timezone()` for converting between `TIME` and `TIMETZ`. 
Support for `TIME/TIMETZ` in `timezone()` is documented at https://www.cockroachlabs.com/docs/dev/functions-and-operators.html#date-and-time-functions.

timezone() now works for time/timetz

---

v20.1/add-constraint.md
v20.1/alter-primary-key.md
v20.1/constraints.md
v20.1/create-table.md
v20.1/drop-constraint.md
v20.1/indexes.md
v20.1/online-schema-changes.md
v20.1/primary-key.md

Fixes #6914 
Fixes #6912 
Fixes #6911 
Fixes #6904 
Fixes #6975.
This PR covers a few things:
- Updated examples in `ADD CONSTRAINT` docs.
- Updated examples in `DROP CONSTRAINT` docs.
- Added note to `ADD CONSTRAINT` docs about adding primary key in case of `DROP CONSTRAINT` or default primary key on `rowid`. Note that we want to discourage users from not explicitly defining a PK, so the second stipulation isn't explored in detail or with examples.
- Added note about no concurrent PK/schema changes to both `ALTER PRIMARY KEY` and online schema changes docs.
- Added `ADD PRIMARY KEY` to `ALTER TABLE` subcommands table as an alias for `ADD CONSTRAINT ... PRIMARY KEY`.
- Added note to `ADD CONSTRAINT` page about `ADD PRIMARY KEY` being alias.

PK changes doc update #2

---

releases/v20.1.0-beta.3.md

Changed a link to a page that was removed for the 20.1 RBAC change.

fix 20.1 roles link

---

_includes/v19.1/orchestration/test-cluster-secure.md
_includes/v19.2/orchestration/test-cluster-secure.md
_includes/v20.1/orchestration/test-cluster-secure.md
v19.1/admin-ui-overview.md
v19.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
v19.1/secure-a-cluster.md
v19.2/admin-ui-overview.md
v19.2/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
v19.2/secure-a-cluster.md
v20.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
v20.1/secure-a-cluster.md

Updates the documented access workaround to use `GRANT role` rather than `INSERT INTO`.
Fixes #6649

update Admin UI security 'workaround'

---

scripts/docs_csat.py

apiclient was the original name of the library.
At some point, it was switched over to be googleapiclient.

Update google api client for docs_csat script

---

v20.1/restore.md

`AS OF SYSTEM TIME` can now be used for any restore, not just of backups with revision history
Closes #6897.

RESTORE ... AS OF SYSTEM TIME 

---

v19.1/online-schema-changes.md
v19.2/online-schema-changes.md
v2.1/online-schema-changes.md
v20.1/online-schema-changes.md

Fixes #7070.
- Update example on 'Online Schema Changes' page that was not using the
correct syntax for running a selection query against a specific
index.
- (Funnily enough, the error message produced was the same either way,
which is probably why this slipped in.  That, and lack of #7067.)

Use correct `foo@foo_idx` syntax in examples

---

_includes/v20.1/known-limitations/schema-change-ddl-inside-multi-statement-transactions.md
_includes/v20.1/known-limitations/schema-changes-within-transactions.md
v20.1/cancel-job.md
v20.1/online-schema-changes.md
v20.1/pause-job.md
v20.1/resume-job.md
v20.1/show-jobs.md

- All schema changes are now run as jobs and can be paused, resumed, and 
canceled (Closes #6894, #6017)
- Clarify what happens if a schema change fails (Closes #5044)

Schema change jobs

---

_includes/v20.1/backups/encrypted-backup-description.md
v20.1/backup.md
v20.1/encryption.md
v20.1/restore.md

General change:
- Added the `encrypted_backups_description.md` include, which is used in `backups.md` and `encryption.md`
Changes to `backups.md`:
- Added **Encrypted backups** section 
- Added a **Backup options** section 
- Added **Create encrypted backups** example
- Added missing colons to New in v20.1 tags
Changes to `restore.md`:
- Added a **Restore from an encrypted backup** example
- Added missing colons to New in v20.1 tags
Changes to `encryption.md`:
- Removed **Encryption cavaets > Unencrypted backups** subsection
- Added a **Encrypted backups (Enterprise)** section
Closes #6011

Encrypted BACKUP

---

v19.1/explain.md
v19.2/explain.md
v20.1/explain.md
v20.1/joins.md

Fixes #6462. 
Fixes #6445. 
- Updated 20.1 `EXPLAIN` example output.
- Updated default `EXPLAIN` docs for 20.1, 19.2, and 19.1 for clarity.
- Added hash join and cross join `EXPLAIN` output to 20.1, 19.2 docs.

EXPLAIN doc updates

---

v19.1/foreign-key.md
v19.2/foreign-key.md
v20.1/foreign-key.md

Fixes #6615.
- Updated 19.1, 19.2, and 20.1 foreign key docs to be easier to read.
- Updated 19.1, 19.2, and 20.1 foreign key docs to include referenced column index requirement.
- Added note to 20.1 foreign key docs stating that an index on FK column(s), or an index on referenced column(s), can be dropped if there is another suitable index.

Updates to Foreign Key docs

---

_includes/v20.1/performance/overview.md
v20.1/foreign-key.md

Fixes #6607.  
- Added notes and example to Foreign Key docs page.
- Removed single-column requirement from Foreign Key docs page.
- Removed note from Performance docs.
https://github.com/cockroachdb/cockroach/pull/43417 affects more than just docs about foreign keys... In specific, we need to update the MovR schema to take advantage of this lifted restriction. That schema needs to be updated for a number of other things as well, so I consider updating the schema out of the scope of this docs issue.

Multiple foreign key constraints can exist on the same column

---

v20.1/time.md
v20.1/timestamp.md

Fixes #6901.  
- Added paragraph, examples about changing precision levels to `TIME` and `TIMESTAMP` docs.

Changing precision level of TIME and TIMESTAMP columns

---

v20.1/set-vars.md

Fixes #6207.
- Edited `SET TIME ZONE` section for readability.
- Added `UTC+/-` and `GMT+/-` to `SET TIME ZONE` section.

SET TIME ZONE supports UTC+- and GMT+- for PG compatibility

---

v20.1/architecture/transaction-layer.md

Fixes #6571.
Summary of changes (all to 'Transaction Layer' page):
- Update 'Writes and reads' section to note that there are now *two*
types of locks: write intents, and unreplicated locks managed by the
concurrency manager in a per-node lock table (about which more below).
- Update 'Write intents' section with information about new concurrency
control mechanism using unreplicated lock table.
- Add new 'Concurrency control' section describing concurrency manager
and lock table at a high level, with links to `SELECT FOR UPDATE`
docs.  This is followed by more detailed subsections that are mostly
adapted from the in-code comments in
`pkg/kv/kvserver/concurrency/concurrency_control.go`.

Document new approach to locking in KV layer

---

_includes/sidebar-data-v20.1.json
v20.1/upgrade-cockroach-version.md

Update the 20.1 upgrade documentation to:
- Mention that in progress schema changes will be paused
and resumed post-finalization.
- Call out that new schema changes will be blocked entirely.
- Document features requiring upgrade finalization.
- Make preparation steps more pronounced.
Fixes #6971.
Fixes #6836.

Update 20.1 rolling upgrade docs

---

v19.1/known-limitations.md
v19.2/known-limitations.md
v19.2/migrate-from-oracle.md
v2.0/known-limitations.md
v2.1/known-limitations.md
v20.1/known-limitations.md
v20.1/migrate-from-oracle.md

Add new limitations and remove resolved limitations.

20.1 known limitations

---

v20.1/monitoring-and-alerting.md

Fixes #6968.
- Updated the documented `/health` response.
- Added a note to reflect the guidance in the corresponding release note.

update health endpoint

---

css/customstyles.css

Trade-off of this approach: "Contribute" button is not flush against right border on short titles. If we do still want it flush against right, then on long titles the "Contribute" button will not be flush against left border.
@jseldess, let me know what you think? Thanks!

Prevent Contribute dropdown from getting cut off on long titles

---

_includes/v20.1/known-limitations/correlated-ctes.md
v20.1/common-table-expressions.md
v20.1/known-limitations.md

Fixes #6195. 
- Added notes, example about limitation on `WITH` clauses containing mutations
- Added "Known limitations" subsection and subsubsection on correlated CTE limitation, with example.

No correlated CTEs; Only top-level WITH clauses containing mutations

---

_includes/v20.1/misc/session-vars.html
v20.1/explain.md

Fixes #6699, #6903, #6920.
- Add a new section to EXPLAIN docs called 'Find out if a statement is
using SELECT FOR UPDATE locking', with an example showing how to
check.
- List out the SQL statements that have support enabled by default for
SFU locking.

Document viewing locking strength with EXPLAIN

---

_includes/v19.2/sql/disk-spilling-ops.md
_includes/v20.1/misc/session-vars.html
_includes/v20.1/sql/disk-spilling-ops.md
v19.2/experimental-features.md
v19.2/explain.md
v19.2/known-limitations.md
v19.2/vectorized-execution.md
v20.1/experimental-features.md
v20.1/vectorized-execution.md

Fixes #5968.
Fixes #6203. 
Fixes #6922. 
Fixes #6924.
Fixes #6905.
Fixes #6618.
Fixes #6621.
Fixes #6979.
Fixes #7141.
- Updated `vectorize` settings on 20.1 Vectorized Execution doc page and Session Variables table.
- Added notes to Window Functions and Selection Queries pages about experimental support in vectorized.
- Updated 20.1 Vectorized Execution page for clarity, accuracy around disk-spilling support.
- Updated 19.2 Vectorized Execution page for clarity.

Vectorized execution support for disk-spilling operators

---

_includes/sidebar-data-v20.1.json
_includes/v20.1/misc/customizing-the-savepoint-name.md
_includes/v20.1/misc/savepoint-limitations.md
_includes/v20.1/sql/diagrams/rollback_transaction.html
_includes/v20.1/sql/diagrams/show_savepoint_status.html
_includes/v20.1/sql/retry-savepoints.md
_includes/v20.1/sql/savepoint-ddl-rollbacks.md
_includes/v20.1/sql/savepoints-and-row-locks.md
_includes/v20.1/sql/unsupported-postgres-features.md
v19.1/rollback-transaction.md
v19.2/rollback-transaction.md
v20.1/advanced-client-side-transaction-retries.md
v20.1/commit-transaction.md
v20.1/detailed-sql-support.md
v20.1/release-savepoint.md
v20.1/rollback-transaction.md
v20.1/savepoint.md
v20.1/show-savepoint-status.md
v20.1/sql-feature-support.md
v20.1/sql-statements.md
v20.1/transactions.md

Fixes #5953.
- Update SAVEPOINT page with more examples of "general" savepoints, in addition to the existing "retry" savepoints
- Add a new SHOW SAVEPOINT STATUS statement page, and add it to the sidebar
- Update RELEASE SAVEPOINT docs to clarify "retry" savepoints vs. "general", and update the example

Document nested SAVEPOINTs

---

v1.1/architecture/transaction-layer.md
v19.1/architecture/transaction-layer.md
v19.2/architecture/transaction-layer.md
v2.0/architecture/transaction-layer.md
v2.1/architecture/transaction-layer.md
v20.1/architecture/transaction-layer.md

Addresses a small part of #7057.
- Edit a sentence that had multiple internal dashes that was confusing
readers.  Now it's several sentences, each with one job.

Simplify sentence about write intent creation

---

_includes/v20.1/faq/sql-query-logging.md
v20.1/admin-ui-debug-pages.md
v20.1/query-behavior-troubleshooting.md
v20.1/sql-audit-logging.md

Fixes #6881.
Fixes #5976.
- Added authentication logs to "Troubleshoot Query Behavior" doc.
- Used examples provided in the [PR](https://github.com/cockroachdb/cockroach/pull/45193).
- I am assuming `cockroach-auth.log` is a symlink consistent with how short file naming is used with the other logs, but let me know if that is incorrect.
- Made some tweaks to slow query log to add consistency with the new documented logs.

document authentication logs

---

netlify/build

I happened to notice that we are forcing reindexing on all builds, including for PR branches: 
https://github.com/cockroachdb/docs/commit/28298fa67b8013633dfd1705bb5ae085e17b82a3#diff-fc7ff7079492ad92dcee358fffdfb6db
There was probably a reason for this at some point, but I think it's safe to restore to default settings now.

Revert commit that forces reindexing on all builds

---

jekyll-algolia-dev/lib/jekyll-algolia.rb
jekyll-algolia-dev/lib/jekyll/algolia/configurator.rb
jekyll-algolia-dev/lib/jekyll/algolia/hooks.rb

This change does a few things:
- Ask Algolia to start indexing text between \<td\> tags (doing this instead of \<table\> to avoid exceeding Algolia's record size restrictions)
- Bump our Algolia max record size from 10KB to 20KB, since we upgraded to a paid plan
- Clean up some existing code comments for better clarity

Index table column text; bump Algolia max record size; clean up comments (Fixes 7107)

---

_includes/sidebar-data-v20.1.json
v20.1/cluster-setup-troubleshooting.md
v20.1/configure-replication-zones.md
v20.1/query-replication-reports.md

Fixes #6604, fixes #6857, fixes #6323.
- Update replication reports docs to note that nodes are considered dead
or unavailable much more quickly than before.
- Rename from 'Query Replication Reports' to 'Replication Reports' to
mitigate some reported confusion about the name of the feature.
- Move 'Replication Reports' into the 'Troubleshooting' section of the
docs, as that's more in line with their use.
- Add more links from 'Configure Replication Zones' to 'Replication
Reports' page, so users know how to verify their constraints are being
respected.
- Update 'Troubleshooting Cluster Setup' docs with links to replication
reports for various cases.

Various replication report docs improvements

---

v20.1/cockroach-sql.md

Fixes #6211.
- Add a new section 'Error messages and SQLSTATE codes' to the
`cockroach sql` docs, with an example showing an error message and
SQLSTATE code.
- Also, describe how the error messages and codes are generated, and the
benefits of relying on SQLSTATE rather than error messages for
automation purposes.

Document CLI's use of SQLSTATE error codes

---

_includes/sidebar-data-v20.1.json
_includes/v20.1/backups/advanced-examples-list.md
_includes/v20.1/backups/encrypted-backup-description.md
releases/v20.1.0-rc.1.md
v20.1/backup-and-restore-advanced-options.md
v20.1/backup-and-restore.md
v20.1/backup.md
v20.1/restore.md

Summary of Changes:
`backup-and-restore.md`
This doc describes the basic / common usage that most users will need. If a user only reads one doc to understand BACKUP / RESTORE, it should be this one. 
- Simplified the main Enterprise backup / restore example to be of a full cluster and with the new "append" incremental backup syntax
- Added a list of "advanced option examples" that links to the new `Back up and Restore Data - Advanced Options` doc
`BACKUP.md`
- Reorganized the information that was already on the page (removed excess headings but reorganized the information)
- Moved the "advanced usage" examples to the new `Back up and Restore - Advanced Options` doc and added a list of the examples on this doc (to help with CTRL+F)
`RESTORE.md`
- Reorganized the information that was …

Re-organize BACKUP / RESTORE docs

---

v20.1/release-savepoint.md
v20.1/rollback-transaction.md
v20.1/savepoint.md
v20.1/sql-statements.md

Addresses  #5953.
- Add 'new in v20.1' tags and appropriate verbiage to the following
parts of the docs that were missed in some previous work in this area:
- RELEASE SAVEPOINT
- ROLLBACK
- SAVEPOINT
- 'SQL Statements'

Mark savepoints as 'New in v20.1' in more places

---

v20.1/upgrade-cockroach-version.md

This change:
- Brings the language on the 'Upgrade CockroachDB' page in line with how
we are talking about nested transactions elsewhere
- Corrects an erroneous reference to changing retry savepoint names for
ORM usage, which was first made available in 19.1.

Tweak savepoint language on upgrade finalization

---

_includes/v19.1/app/basic-sample.rs
_includes/v19.1/app/insecure/basic-sample.rs
_includes/v19.1/app/insecure/txn-sample.rs
_includes/v19.1/app/txn-sample.rs
_includes/v19.2/app/basic-sample.rs
_includes/v19.2/app/insecure/basic-sample.rs
_includes/v19.2/app/insecure/txn-sample.rs
_includes/v19.2/app/txn-sample.rs
_includes/v2.1/app/basic-sample.rs
_includes/v2.1/app/insecure/basic-sample.rs
_includes/v2.1/app/insecure/txn-sample.rs
_includes/v2.1/app/txn-sample.rs
_includes/v20.1/app/basic-sample.rs
_includes/v20.1/app/insecure/basic-sample.rs
_includes/v20.1/app/insecure/txn-sample.rs
_includes/v20.1/app/txn-sample.rs
v19.2/build-a-rust-app-with-cockroachdb.md
v19.2/install-client-drivers.md
v20.1/build-a-rust-app-with-cockroachdb.md
v20.1/install-client-drivers.md

Fixes #5560.
- Update secure driver instructions to point to https://crates.io/crates/postgres-openssl/.
- Update secure basic samples for latest version of driver for v2.1-v20.1.
- Update secure txn samples for latest version of driver for v2.1-v20.1.
- Update insecure basic samples for latest version of driver for v2.1-v20.1.
- Update insecure txn samples for latest version of driver for v2.1-v20.1.
- Add Rust driver to Postgres Client listing page

Fix Rust driver examples and documentation, add to drivers list

---

v20.1/array.md
v20.1/data-types.md
v20.1/decimal.md
v20.1/int.md
v20.1/string.md

Fixes #6206. 
- Added note to "Data Types" page about implicit casting to `INT` and `DECIMAL` `ARRAY`s.
- Added "Implicit casting" subsection, with example, to `ARRAY` page.

Implicit casting to INT and DECIMAL ARRAY

---

v20.1/create-sequence.md
v20.1/rename-database.md

Fixes #6908.
- Added additional bullet to Considerations on `CREATE SEQUENCE` page.
- Reworked limitations on, added limitation and example to Rename Database page.
- Updated examples on Rename Database page.

Databases cannot be renamed if in explicit sequence reference

---

v20.1/temporary-tables.md

Fixes #7139.
- Added bullet to Details on Temporary Tables page about `ON COMMIT PRESERVE ROWS` support for PG compatibility.

ON COMMIT PRESERVE ROWS for PG compatibility

---

v20.1/partitioning.md

Fixes #7031.
- Update 'Define table partitions' to note that CockroachDB 20.1 sends a
notice to the client warning about possible perf degradation when you
create a non-partitioned index on a partitioned table.

Docs for non- vs. partitioned indexes and tables

---

v20.1/sql-constants.md
v20.1/string.md

Fixes #6906.
- Add new section on dollar-quoted strings to 'SQL Constants' page
- Add more linkage from `STRING` data type page to the string literal
syntax info

Document dollar-quoted string literal syntax

---

v19.1/load-based-splitting.md
v19.2/load-based-splitting.md
v20.1/load-based-splitting.md

Corrects the default mentioned on the load-base splitting doc. However, this setting is excluded from the 20.1 auto-generated cluster settings docs (it's there in 19.2). I think this is due to the recent public/private setting distinction, but I'm not sure. I'll follow-up on that separately. I believe the setting should be included in the auto-generated doc if we're referencing it explicitly on a page like this.
Fixes #7108.

Correct kv.range_split.load_qps_threshold default

---

_includes/v20.1/sql/operators.md
v20.1/array.md
v20.1/inverted-indexes.md

Fixes #6919.
- Update the 'Inverted indexes' page to mention support for SQL `ARRAY`
type.  Add links to array docs.
- Update the `ARRAY` data type reference to mention this as well.
- Update the 'Functions and operators' page to use anchors so we can
link directly to the containment operators `>@` and `@>` being
mentioned.

Document that inverted indexes work on arrays

---

_includes/footer.html

The slack URL under "Support Channels" is in https://www.cockroachlabs.com/contact/
but is not in any of the docs pages. This adds it in there for
consistency.

make docs footer consistent with wordpress

---

v20.1/select-clause.md

Fixes #7134.
Fixes #5913.
- Added notes to Select Clause page on GROUP BY requirement for aggregate functions.
This doc *could* benefit from an example, but I'm having difficulty coming up with an example that makes sense to me without being confusing. IIUC, this behavior update is for PG compatibility, so it's not super important that we have an example.

Added notes on GROUP BY requirement for aggregate functions

---

STYLE.md

- Updated guidance to use `1.` for each item in a numbered list.

update style guidelines for numbered lists

---

v20.1/select-clause.md

Fixes #6193.
- Added note and example about grouping by aliases to the Select Clause page.

GROUP BY supports grouping by aliases

---

v19.2/build-a-python-app-with-cockroachdb-django.md
v19.2/install-client-drivers.md
v20.1/build-a-python-app-with-cockroachdb-django.md
v20.1/install-client-drivers.md

Corrected version numbers for Django support, as suggested in https://github.com/cockroachdb/docs/pull/6521#issuecomment-624269747.

Corrected version numbering for Django support

---

v1.0/install-cockroachdb.html
v1.1/install-cockroachdb.html
v19.1/install-cockroachdb-linux.html
v19.1/install-cockroachdb-mac.html
v19.2/install-cockroachdb-linux.html
v19.2/install-cockroachdb-mac.html
v2.0/install-cockroachdb.html
v2.1/install-cockroachdb-linux.html
v2.1/install-cockroachdb-mac.html
v20.1/install-cockroachdb-linux.html
v20.1/install-cockroachdb-mac.html

Previously, it referenced 3.81+, but the latest release
is just 3.17.2. This was a typo. Change to 3.8+.
Fixes #7342.

Correct min cmake version required for building from source

---

jekyll-algolia-dev/lib/jekyll/algolia/configurator.rb

Reverts cockroachdb/docs#7352
Unfortunately adding list items to search indexing pushes certain pages over our Algolia size limit.
```
3:55:52 PM: [✗ Error] Record is too big                                                      
3:55:52 PM:                                                                                  
3:55:52 PM: The jekyll-algolia plugin detected that one of your records exceeds the 20.00 Kb 
3:55:52 PM: record size limit.                                                               
3:55:52 PM:                                                                                  
3:55:52 PM: title:    Low Latency Reads and Writes in a Multi-Region Cluster                 
3:55:52 PM: url:      https://www.cockroachlabs.com/docs/v20.1/demo-low-latency-multi-region-deployme …
```

Revert "Add list items to search indexing (Fixes 7351)"

---

_includes/sidebar-data-v20.1.json
v20.1/flyway.md
v20.1/third-party-database-tools.md

Fixes #5356. 
- Added a new page on using Flyway with CRDB. This page includes a simple tutorial, and some notes on transaction boundaries and retries.

Flyway docs

---

_config_base.yml
_data/releases.yml
_includes/sidebar-releases.json
releases/v19.2.7.md

Fixes #7288. 
Release notes based on https://github.com/cockroachdb/cockroach/commit/2e19ff0576ff21e243f00f2e2acdaeea57aee6f3.

Release notes for v19.2.7

---

jekyll-algolia-dev/lib/jekyll/algolia/configurator.rb
jekyll-algolia-dev/lib/jekyll/algolia/extractor.rb
jekyll-algolia-dev/lib/jekyll/algolia/shrinker.rb

Attempt #2 to add list items to search indexing (previous attempt had to be rolled back because we generated files over Algolia's max record size).
This change adds list items to search indexing, and works around the max record size issue by:
- Shrinking records via removing html attributes
- Excluding \<svg\> diagrams and \<pre\> code blocks from search indexing
Exclusion of code blocks is based on previous discussion with @jseldess, where we agreed they can be excluded because they are not the "meat" of documents.
This change has been tested to make sure we now successfully come under Algolia's max record limit.

Add list items to search indexing + changes to meet Algolia max record size (Fixes #7351)

---

v20.1/build-a-go-app-with-cockroachdb.md

Go users can mistake "pg" to mean `go-pg` which is an ORM for Postgres. However, this article is about using "pq" which refers to the `lib/pq` SQL driver. To prevent ambiguity, this PR updates the article to use "pq" instead of "pg" throughout.

Change pg -> pq in Go example

---

scripts/bump_major_version.py

With each new major release of CockroachDB, there are a number of
administrative tasks that need to be accomplished on the docs website.
This includes, but is not limited to:
- Create a new `vXY.Z` folder, and copy content to it
- Copy includes to a new `_includes/vXY.Z` folder
- Copy images to a new versioned folder, and edit image link text in the
referencing documents as needed to point to the right places
- Update the YAML config files with the new version info
- Create a new sidebar JSON file
- In the newly created XY.Z folder, remove the various "new in vXY.Z-1"
callouts from the copied files.
Note: this list may not be exhaustive, see the code for details.
This script attempts to automate these tasks as much as possible.  In
addition to copying files around, editing files, etc., it …

Add script to handle admin tasks re: version bumps

---

v19.1/change-data-capture.md
v19.1/create-changefeed.md
v19.1/gssapi_authentication.md
v19.2/change-data-capture.md
v19.2/create-changefeed.md
v19.2/gssapi_authentication.md
v2.1/change-data-capture.md
v2.1/create-changefeed.md
v20.1/change-data-capture.md
v20.1/cockroachcloud-authorization.md
v20.1/cockroachcloud-connect-to-your-cluster.md
v20.1/cockroachcloud-frequently-asked-questions.md
v20.1/create-changefeed.md
v20.1/deploy-a-python-to-do-app-with-flask-kubernetes-and-cockroachcloud.md
v20.1/gssapi_authentication.md

Changed instances of `whitelist` to `allowlist` everywhere in the docs except for instances that refer to UI elements (CloudFormation UI, Kafka, and Jekyll builds)

Changed terminology from whitelist to allowlist

---

_includes/sidebar-data-v20.2.json
_includes/v20.2/misc/tooling.md
v20.2/third-party-database-tools.md

Port changes from #7393 and #7444 to v20.2

Port changes from #7393 and #7444 to v20.2

---

v20.1/cockroachcloud-connect-to-your-cluster.md
v20.1/cockroachcloud-quickstart.md
v20.1/deploy-a-python-to-do-app-with-flask-kubernetes-and-cockroachcloud.md

- Removed recommended username/password combinations from the Quickstart guide and sample app tutorial
- Cleaned up the sample app tutorial to match the current UI
- Added a "before you move into production section" to the Quickstart guide

Updated CC Quickstart guide and sample app tutorial

---

v19.2/import-into.md
v20.1/import-into.md
v20.2/import-into.md

- Clarify that IMPORT INTO can't be used to insert data into existing row. Closes #7270
- Add note that IMPORT INTO invalidates foreign keys. Closes #7278.

IMPORT INTO edits

---

_includes/sidebar-releases.json

- Create prod and testing sections.
- Expose latest release under each. Last 3 for prod. Only one
for testing.
- Add intro to all prod patch release notes linking users
to GA release notes for full feature summaries and upgrade
instructions. With this, we can remove GA release notes
from sidenav.
Fixes #7547.
Fixes #7506.

Update sidebar to better expose latest prod and testing releases

---

releases/v19.1.1.md
releases/v19.1.2.md
releases/v19.1.3.md
releases/v19.1.4.md
releases/v19.1.5.md
releases/v19.1.6.md
releases/v19.1.7.md
releases/v19.1.8.md
releases/v19.1.9.md
releases/v19.2.1.md
releases/v19.2.2.md
releases/v19.2.3.md
releases/v19.2.4.md
releases/v19.2.5.md
releases/v19.2.6.md
releases/v19.2.7.md
releases/v20.1.1.md
releases/v20.1.2.md

Forgot to include this part in 7550:
Add intro to all prod patch release notes linking users
to GA release notes for full feature summaries and upgrade
instructions. With this, we can remove GA release notes
from sidenav.

Follow-up to https://github.com/cockroachdb/docs/pull/7550

---

v20.1/show-create.md
v20.2/show-create.md

Previously, the SHOW CREATE examples only showed the default
result of 2 columns, starting with the object name. This PR
adds additional examples showing how to return only the
CREATE STATEMENT for easier copy/paste reuse.

Add examples for getting copyable create statements

---

v20.1/build-a-java-app-with-cockroachdb.md
v20.1/developer-guide-overview.md
v20.2/build-a-java-app-with-cockroachdb.md
v20.2/developer-guide-overview.md

This PR adds links to the Spring tutorial in two places:
- The overview of the Develop guide
- The JDBC Java docs
As we add more Spring tutorials, I'll add links to the tutorials in the corresponding ORM tutorial.

Improve visibility of Spring tutorial

---

v19.1/build-a-java-app-with-cockroachdb-hibernate.md
v19.2/build-a-java-app-with-cockroachdb-hibernate.md
v20.1/build-a-java-app-with-cockroachdb-hibernate.md
v20.2/build-a-java-app-with-cockroachdb-hibernate.md

Following discussion offline with @rafiss, I'm removing the batch size recommendation from the Hibernate docs, as the recommendation does not really apply to the Hibernate ORM.

Removed batch size constraint from Hibernate best practices

---

v20.2/add-column.md

Fixes #7619. 
Fixes #7745.
- Removed limitation in `col_qualification` parameter description.
- Changed example to use `cockroach demo bank`.
- Added `ADD COLUMN ... REFERENCES` example.
Note that `ADD COLUMN ... REFERENCES` syntax support does not change SQL diagram generated for `ALTER TABLE ... ADD COLUMN`, nor does it affect the existing help text.

ADD COLUMN ... REFERENCES syntax

---

v19.2/recommended-production-settings.md
v20.1/recommended-production-settings.md
v20.2/recommended-production-settings.md

Fixes #7096.
Fixes #6702.
- As Raphael noted, selecting the number of nodes for fault tolerance comes before selecting the number of CPUs per node. We don't currently have a docs reference specifically about determining node count for a production deployment, but this is in progress. I'm discussing with @jseldess how best to add this to our deployment guidance.
- On the storage capacity issue (60 GB -> 250 GB), I was unclear on whether this capacity equates to the max `store` size and whether that in turn equates to the total disk capacity. Since we advise operators to always leave a certain amount (listed in this update as 40%) free, should they account for this 40% when provisioning volumes so that they can benefit from the full supported 60/250 GB?
- For now I've conflated the …

upgrade Production Checklist with "rules of thumb"

---

v20.1/build-a-spring-app-with-cockroachdb-jpa.md
v20.2/build-a-spring-app-with-cockroachdb-jpa.md

Fixed some formatting on the Spring JPA tutorial - the live version isn't generating HTML correctly. This PR fixes that.
@vy-ton Thanks for pointing this out!

Fixed formatting errors on Spring JPA tutorial

---

v19.1/known-limitations.md
v19.2/known-limitations.md
v2.1/known-limitations.md
v20.1/known-limitations.md
v20.2/known-limitations.md

Fixes #7719. Covers v2.1 - 20.2.
Questions:
- Should this known limitation also apply to memory limits (based on [this comment](https://github.com/cockroachdb/cockroach/issues/34988#issuecomment-648283843))? 
- Should CPU technically be called vCPU?

add known limitation: Admin UI CPU metric

---

v20.1/transaction-retry-error-reference.md
v20.2/transaction-retry-error-reference.md

- In the section on `RETRY_WRITE_TOO_OLD`, we are talking about the
ordering of two transactions A and B.  I had erroneously said that if
B comes after A, then B has a lower timestamp than A.  In fact, if B
comes after A, then B has a *higher* timestamp than A.  This PR fixes
that error.

Fix logic error in timestamp ordering remark

---

_includes/v20.1/json/json-sample.go
_includes/v20.1/json/json-sample.py
_includes/v20.2/json/json-sample.go
_includes/v20.2/json/json-sample.py
v20.1/demo-json-support.md
v20.2/demo-json-support.md

Query the reddit API 40 times instead of until there
are no more results. This quickens the tutorial and
inserts enough rows to show the speed up with an inverted
index. It also helps speed up a related Katacoda tutorial.

Update json tutorial and code

---

v20.2/array.md

Fixes #7744. 
Fixes #7621. 
- Updated example output of examples on `ARRAY` docs page.
- Added new ordering by array example to `ARRAY` docs page.
- Removed note on limitation on ordering by arrays.

Ordering by arrays

---

_includes/v20.1/known-limitations/cdc.md
_includes/v20.2/known-limitations/cdc.md
v20.1/create-changefeed.md
v20.2/create-changefeed.md

The "open correctness issue with changefeeds connected to cloud storage 
sinks where new row information will display with a lower timestamp than 
what has already been emitted, which violates our ordering guarantees" 
was fixed in v20.1

Remove CDC correctness warning

---

v19.1/build-a-python-app-with-cockroachdb-sqlalchemy.md
v19.2/build-a-python-app-with-cockroachdb-sqlalchemy.md
v2.1/build-a-python-app-with-cockroachdb-sqlalchemy.md
v20.1/build-a-python-app-with-cockroachdb-sqlalchemy.md
v20.2/build-a-python-app-with-cockroachdb-sqlalchemy.md

Removed paragraph about SAVEPOINTs from run_transaction() recommendation

---

_includes/v20.2/sql/diagrams/stmt_block.html

Updated stmt_block. This update is required for new diagrams to not break the build with broken links (e.g., #7964).

Updated stmt_block diagram

---

_redirects

Instead of adding a manual redirect, use Netlify's built-in "Pretty URLs" feature. See https://docs.netlify.com/routing/redirects/redirect-options/#trailing-slash

Better redirects for releases

---

_includes/v19.2/app/BasicExample.java
_includes/v19.2/app/java-tls-note.md
_includes/v19.2/app/java-version-note.md
_includes/v20.1/app/BasicExample.java
_includes/v20.1/app/java-tls-note.md
_includes/v20.1/app/java-version-note.md
_includes/v20.2/app/BasicExample.java
_includes/v20.2/app/java-tls-note.md
_includes/v20.2/app/java-version-note.md
v19.2/build-a-java-app-with-cockroachdb-hibernate.md
v19.2/build-a-java-app-with-cockroachdb-jooq.md
v19.2/build-a-java-app-with-cockroachdb.md
v19.2/install-client-drivers.md
v20.1/build-a-java-app-with-cockroachdb-hibernate.md
v20.1/build-a-java-app-with-cockroachdb-jooq.md
v20.1/build-a-java-app-with-cockroachdb.md
v20.1/install-client-drivers.md
v20.2/build-a-java-app-with-cockroachdb-hibernate.md
v20.2/build-a-java-app-with-cockroachdb-jooq.md
v20.2/build-a-java-app-with-cockroachdb.md
v20.2/install-client-drivers.md

Fixes #7937. 
I tested all samples against Java versions 8-14, with JDBC driver version 42.2.14.
Touches #7820.

Updated version guidance on Java docs

---

_includes/sidebar-data-v20.2.json
v20.2/spatial-features.md
v20.2/spatial-glossary.md

Fixes #7910.
- Add a new page, 'Glossary of Spatial and GIS Terms', designed to help
users get oriented to the rather confusing, TLA-laden GIS space.
- To orient the above page "in space" and give it somewhere to live, we
add a new 'Spatial Features' section, with a semi-placeholder page to
be filled in more later, called 'Spatial Features', where we will
provide users with a reference of what, er, spatial features we
support.

Add a spatial and GIS glossary

---

_includes/v20.1/app/spring-data-jpa/application.yml
_includes/v20.2/app/spring-data-jpa/application.yml
v20.1/build-a-spring-app-with-cockroachdb-jpa.md
v20.2/build-a-spring-app-with-cockroachdb-jpa.md

Fixes #5992.
- Updated properties file to specify v20.1 CRDB Hibernate dialect.
- Added latest Hibernate version to pom.xml file (Spring Data JPA uses older version that doesn't support CRDB dialect.
- Updated app output.
Before merging this, I need to merge the change to the roach-data repo: https://github.com/cockroachlabs/roach-data/pull/4.

Updated v20.1 Spring-JPA tutorial to use CRDB Hibernate dialect

---

_includes/v19.2/app/java-tls-note.md
_includes/v20.1/app/java-tls-note.md
v19.2/install-client-drivers.md
v20.1/install-client-drivers.md

https://github.com/cockroachdb/docs/issues/7820#issuecomment-675037589

Removed TLS guidance for v20.1 and v19.2

---

v19.1/change-data-capture.md
v19.2/change-data-capture.md
v20.1/change-data-capture.md
v20.1/stream-changefeed-to-snowflake-aws.md
v20.2/change-data-capture.md

Updated Enable Rangefeeds section:
- Removed outdated info about changefeeds that collect changes by 
periodically sending a request for any recent changes. Rangefeeds have 
been the only type of changefeed available since at least v19.2 
- Moved the Enable Rangefeeds section to be higher on the page since 
it's required for changefeeds to work
Closes #8003

Update info about enabling rangefeeds

---

v20.2/restore.md

Add info about restoring tables with UDTs

---

_includes/v19.2/misc/delete-statistics.md
_includes/v20.1/misc/delete-statistics.md
_includes/v20.2/misc/delete-statistics.md
v19.2/create-statistics.md
v19.2/show-statistics.md
v20.1/create-statistics.md
v20.1/show-statistics.md
v20.2/cost-based-optimizer.md
v20.2/create-statistics.md
v20.2/show-statistics.md

Fixes #4798. 
Fixes #7611. 
- Documented multi-column statistics support in v20.2
- Updated STATISTICS statement examples and notes in v19.2, v20.1, and v20.2

Multi-column statistics

---

_includes/sidebar-data-v20.1.cockroachcloud.json
v20.1/cockroachcloud-backups-page.md
v20.1/cockroachcloud-cluster-management.md

Add doc for the Backups page in the CockroachCloud console:
- Describes the new Backups page (and the cluster/database/tables views)
- Provides steps on how to restore a cluster, database, or table
- Provides steps on how to back up and restore from a self-hosted CRDB cluster
- Provides steps on how to back up and restore your CC data manually
Closes #7248, #6818.
Note: This is for v1 of the UI. Docs will be updated as functionality is added.

CockroachCloud Backups

---

_includes/v19.2/misc/client-side-intervention-example.md
_includes/v20.1/misc/client-side-intervention-example.md
_includes/v20.2/misc/client-side-intervention-example.md

Fixes #8211.
- Added a `break` statement to the pseudocode based on reader feedback
that the `while` loop in question would never exit.  Turned out they
were right; after reviewing our actual Python code, we had a `break`
tucked in there after the db `COMMIT`.

Update logic in retry pseudocode to match real code

---

_includes/sidebar-data-v20.2.json
v20.2/install-cockroachdb-linux.html
v20.2/install-cockroachdb-mac.html
v20.2/install-cockroachdb-spatial.md

Fixes #7916.
- Add a new 'Install CockroachDB Spatial' page that lives alongside the
regular installation instructions, but separately.  The reasoning is
that there are many more fiddly steps that non-spatial users should
ideally not have to mess with until this is in a more polished state.
- Update the 'Install CockroachDB' pages for Linux and Mac to add
pointers to the spatial page.
- Add the new spatial install page to the sidebar (it is not an
additional entry in the sidebar; instead it is yet another page that
"hides" under 'Install CockroachDB').

Add docs for CockroachDB Spatial install

---

_includes/v20.1/orchestration/start-cockroachdb-insecure.md
_includes/v20.1/orchestration/start-cockroachdb-secure.md
_includes/v20.1/orchestration/start-kubernetes.md
_includes/v20.1/prod-deployment/aws-inbound-rules.md
_includes/v20.1/prod-deployment/insecure-test-load-balancing.md
_includes/v20.1/prod-deployment/secure-test-load-balancing.md
_includes/v20.2/orchestration/start-cockroachdb-insecure.md
_includes/v20.2/orchestration/start-cockroachdb-secure.md
_includes/v20.2/orchestration/start-kubernetes.md
_includes/v20.2/prod-deployment/aws-inbound-rules.md
_includes/v20.2/prod-deployment/insecure-test-load-balancing.md
_includes/v20.2/prod-deployment/secure-test-load-balancing.md
v20.1/deploy-cockroachdb-on-aws-insecure.md
v20.1/deploy-cockroachdb-on-aws.md
v20.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
v20.2/deploy-cockroachdb-on-aws-insecure.md
v20.2/deploy-cockroachdb-on-aws.md
v20.2/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md

Fixes #4314.
Relates to https://github.com/cockroachdb/cockroach/pull/51775, which adds `cockroachdb-statefulset-secure-eks.yaml`, `dnb-lb-eks.yaml`, and `configmap.yaml` to the `multiregion` repo.
Also addresses https://github.com/cockroachdb/cockroach/pull/51471.
- Draft EKS multi-region deployment (manual steps; no script)
- Under **Create inbound rules**, I'm not sure if the "Inter-node and load balancer-node communication" still fits for this rule on multi-region. It seems the load balancer points at CoreDNS on port 53, and CoreDNS provides the load balancer-node communication. Is this right?
- Since #5922 appears to still be unresolved, there is no guidance here on setting a CPU request and/or limit.
- Bob's [PR](https://github.com/cockroachdb/cockroach/pull/51471) implied (to me) …

K8s multiregion eks

---

_includes/v20.2/sql/diagrams/create_table.html
_includes/v20.2/sql/diagrams/create_table_as.html
_includes/v20.2/sql/diagrams/opt_persistence_temp_table.html
_includes/v20.2/sql/diagrams/stmt_block.html
v20.2/create-table-as.md
v20.2/create-table.md
v20.2/temporary-tables.md

This PR will fix the broken links in #8222 and #7964, and future PRs with SQL syntax diagram links.
- Updated stmt_block diagram (full SQL grammar diagram).
- Updated some links to grammar entities that no longer exist in the current.
- Updated temp table diagram to match existing grammar.

Updating stmt_block diagram for v20.2-alpha.3

---

_includes/version-nav.html

Fixes #8063.
@lnhsingh, @Amruta-Ranade, @jseldess: This PR removes the version switcher from the Docs homepage, which I believe was requested by Amruta.
While making this change, I noticed that there are CRDB pages linked from the CC part of the sidenav, namely the pages under "Use Your Cluster" > "Migrate Data." Those will have the version switcher displayed, since they are actually CRDB pages and not CC pages. Is that fine? Note that this is similar to the issue affecting breadcrumbs. When the same pages are linked from multiple sidenav locations, breadcrumbs will not work as expected.

Remove version switcher from docs homepage

---

_includes/sidebar-data-v20.2.json
_includes/v20.2/sql/diagrams/create_index.html
_includes/v20.2/sql/diagrams/index_def.html
v20.2/create-index.md
v20.2/create-table.md
v20.2/indexes.md
v20.2/partial-indexes.md
v20.2/sql-feature-support.md

Fixes #7747. 
- Added a new page for Partial Indexes.
- Updated `CREATE INDEX` syntax diagram and parameters. 
This PR will likely fix some future "opt" release note issues.

Partial indexes

---

_includes/sidebar-data-v20.2.json
v20.2/migrate-from-geojson.md
v20.2/migrate-from-geopackage.md
v20.2/migrate-from-openstreetmap.md
v20.2/migrate-from-shapefiles.md
v20.2/migration-overview.md
v20.2/spatial-data.md
v20.2/spatial-features.md
v20.2/spatial-glossary.md

Fixes #7933.
- Add 'Migrate to *' pages for each of:
- Shapefile (.shp)
- GeoJSON (.json)
- OpenStreetmap (.pbf)
- GeoPackage (.gpkg)
- For each of the above new pages, we document:
- How to get the data from original format X to format Y (usually
format Y is something we can slurp in with `IMPORT PGDUMP`)
- Which tool(s) are used for the process
- Finally, we try to link everything amongst each other and the various
already existing Spatial pages (glossary, etc.), in addition to
whatever work is needed to weave these changes into the larger docs
site in general (links, TOC updates, etc.)

Document spatial file type conversion tools

---

v19.2/recommended-production-settings.md
v20.1/recommended-production-settings.md
v20.2/recommended-production-settings.md

Updates numbers first added in #7739.
Thread: https://cockroachlabs.slack.com/archives/C013VDTRA30/p1600109555012800
- @a-entin You mentioned that versions prior to 20.1 have a 1 TB/node storage capacity limit, per conversations with Raphael. We previously had 2 TB documented. Just wanted to note that I've adjusted that number down for 19.2.
- Added back wording on 32 vCPUs as an OLTP "sweet spot" and clarified that this is not a hard limit.

update Production Checklist numbers

---

v19.2/delete-data.md
v19.2/delete.md
v19.2/learn-cockroachdb-sql.md
v19.2/performance-best-practices-overview.md
v19.2/sql-faqs.md
v19.2/truncate.md
v20.1/delete-data.md
v20.1/delete.md
v20.1/performance-best-practices-overview.md
v20.1/sql-faqs.md
v20.1/truncate.md
v20.2/delete-data.md
v20.2/delete.md
v20.2/performance-best-practices-overview.md
v20.2/sql-faqs.md
v20.2/truncate.md

Fixes #5592.
Fixes #4818. 
Fixes #5647. 
Fixes #8137.
Adding examples in other languages will likely be part of the larger [Dev Guide v2 initiative](https://github.com/cockroachdb/docs/issues/6667).

Large deletes guidance and TTL workarounds

---

_includes/v20.2/sql/diagrams/with_clause.html
v20.2/common-table-expressions.md

Fixes #7616.
- Updated WITH clause diagram
- Added `MATERIALIZED`/`NON MATERIALIZED` to WITH clause syntax parameters.
Note: I figured we don't want to encourage users to change what the optimizer decides to do, so I didn't add an example.

MATERIALIZED/NON MATERIALIZED syntax for CTE WITH clause

---

_config_base.yml
_data/releases.yml
_includes/sidebar-releases.json
releases/v20.2.0-beta.2.md

Fixes #7980. 
[v20.2.0-beta.2](https://github.com/cockroachdb/cockroach/issues/54369) is currently qualifying and scheduled for release Sept 24, 2020.

draft v20.2.0-beta.2 release notes

---

css/customstyles.css
css/customstyles.scss
netlify/build
v20.1/404.md

Fixes #4908 and #8076.
The custom 404 image is a stretch goal so I haven't attempted it with this PR.
Please preview the new 404 page here: https://deploy-preview-8415--cockroachdb-docs.netlify.app/docs/stable/404.html
You will not be able to see the page above by going to a broken link via preview site, because the way Netlify redirects, it will send you from a preview broken link to the 404 page in production. But you **can** use the Netlify preview site to verify that broken links are being redirected to the 404 page in production, which is an improvement over current behavior (see #4908).
I think this is one PR that we should make live immediately instead of waiting for all style updates. This is because the current 404 functionality is broken (see #4908), so we are essentially fixing …

Fix docs custom 404 page and reword messaging

---

_includes/sidebar-data-v20.2.json
v19.2/sql-feature-support.md
v19.2/sql-name-resolution.md
v20.1/sql-feature-support.md
v20.1/sql-name-resolution.md
v20.2/alter-schema.md
v20.2/create-schema.md
v20.2/detailed-sql-support.md
v20.2/drop-schema.md
v20.2/show-schemas.md
v20.2/sql-feature-support.md
v20.2/sql-name-resolution.md
v20.2/sql-statements.md

Fixes #8164.
Fixes #5993.
Fixes #8322.
Fixes #8346.
Fixes #8344.
Fixes #8305.
Fixes #8327.
- Added new pages for `CREATE SCHEMA`, `ALTER SCHEMA`, and `DROP SCHEMA`.
- Updated `SHOW SCHEMAS` page, and other references to user-defined schema support.
Note that this PR pilots using CLI help text instead of SQL diagrams for statement syntax documentation.

User-defined schemas

---

v20.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
v20.2/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md

Added missing code copy option for step `python teardown.py`.
Closes #8533

add missing copy option to doc

---

v19.1/cockroachdb-in-comparison.md
v19.2/cockroachdb-in-comparison.md
v20.1/cockroachdb-in-comparison.md
v20.2/cockroachdb-in-comparison.md

- PR for discarding non-essential capitalization from `cockroachdb-in-comparison.md` file from `v19.1`, `v19.2`, `v20.1` and `v20.2.`
- I have applied the v19.1 test commit solution which was a review for all other versions after check & comparison
- For this, I have compared the `cockroachdb-in-comparison.md` file from my forked branch with the file on the master branch for any un-accounted discrepancies. (there were none)
- I have used the [online difference checker tool](https://www.diffchecker.com/diff) to check the difference in content to avoid any mistakes.

remove non-essential capitalization (#6864)

---

_data/releases.yml
advisories/a54418.md

In #8435, I removed the v20.1.4 and v20.1.5 release notes from the releases index. This PR adds them back, with the `withdrawn` attribute set to `true`. This replaces the download link with a "Withdrawn" element in the page.

Added v20.1.4 and v20.1.5 release notes back to the releases index

---

v20.2/add-constraint.md
v20.2/create-view.md
v20.2/foreign-key.md
v20.2/views.md

Fixes #8503. 
Added notes to Views, `CREATE VIEW`, Foreign Keys, `ADD CONSTRAINT` docs.

Cross-database foreign key and view references disallowed by default.

---

_includes/v20.1/misc/session-vars.html
_includes/v20.2/misc/session-vars.html
v20.2/cost-based-optimizer.md
v20.2/joins.md

Fixes #8148.
Fixes #8319. 
Fixes #7614.
This PR adds the new v20.2 session variables to the list of exposed session variables in the v20.2 docs. 
The PR also includes the following fixes:
- Updates to the session variables in v20.1 and v20.2 that were added in previous CRDB versions, but were not previously documented (https://github.com/cockroachdb/cockroach/pull/37333, https://github.com/cockroachdb/cockroach/pull/35116, https://github.com/cockroachdb/cockroach/pull/42914, https://github.com/cockroachdb/cockroach/pull/48333)
- Changed `prefer_lookup_joins_for_fk` to `prefer_lookup_joins_for_fks`, to reflect the true name of the variable.
Adding @otan as primary engineering reviewer, but feel free to add anyone else.

v20.2 session variables update

---

_includes/v19.2/sql/movr-statements-geo-partitioned-replicas.md
_includes/v20.1/sql/movr-statements-geo-partitioned-replicas.md
_includes/v20.2/sql/movr-statements-geo-partitioned-replicas.md
_includes/v20.2/sql/shell-commands.md
_includes/v20.2/sql/shell-help.md
_includes/v20.2/sql/shell-options.md
_includes/v20.2/sql/shell-shortcuts.md
releases/v19.2.0-rc.1.md
v19.2/cockroach-demo.md
v19.2/query-replication-reports.md
v20.1/cockroach-demo.md
v20.1/query-replication-reports.md
v20.2/cockroach-demo.md
v20.2/cockroach-gen.md
v20.2/cockroach-sql.md
v20.2/query-replication-reports.md

- Use includes for SQL shell reference across both pages.
- Supplement the demo SQL shell reference with connection parameters
and additional commands.
- Refactor the demo examples, including a new example for connecting
additional SQL clients to a demo cluster.
Fixes #7638
Fixes #5414
Fixes #7643

Tweak sql and demo docs

---

CODE_OF_CONDUCT.md
README.md

- added a new initial Code of Conduct file for CockroachDB Docs.
Closes #8604

doc: add new initial code-of-conduct file (#5653)

---

v19.2/collate.md
v20.1/collate.md
v20.2/collate.md

Fixes #1471. 
- Added docs on collation subtags.
- Added note on deterministic and non-deterministic support.

Special collations

---

v20.1/timestamp.md
v20.2/timestamp.md

Fixes #7711.
Fixes #7858. 
Fixes #7613.

Timestamp infinity casts evaluted as max/min values + New max/min bounds on TIMESTAMP values

---

v20.2/views.md

Added example about dropping columns on which views are not dependent

---

v19.2/alter-table.md
v19.2/rename-table.md
v20.1/alter-table.md
v20.1/rename-table.md
v20.2/alter-table.md
v20.2/rename-table.md

Fixes #8129. 
- Updated the `RENAME TABLE` pages for 19.2, 20.1, and 20.2 to correctly refer to the statement as `ALTER TABLE ... RENAME TO` (`RENAME TABLE` is not a statement). 
- Made some minor formatting changes to 19.2, 20.1, and 20.2 `RENAME TABLE` pages.
- Added a note about the limitation on changing schemas with a table rename statement.
In the future, we should avoid mislabeling statements. Another instance of this is with `RENAME DATABASE`, which is not a statement (it should be `ALTER TABLE ... RENAME TO`).

Updates to RENAME TABLE page

---

_includes/enterprise-feature.md
_includes/v20.1/zone-configs/create-a-replication-zone-for-a-secondary-index.md
_includes/v20.1/zone-configs/create-a-replication-zone-for-a-table-partition.md
_includes/v20.2/zone-configs/create-a-replication-zone-for-a-secondary-index.md
_includes/v20.2/zone-configs/create-a-replication-zone-for-a-table-partition.md
v20.1/alter-partition.md
v20.1/enable-node-map.md
v20.1/gssapi_authentication.md
v20.1/show-partitions.md
v20.2/alter-partition.md
v20.2/enable-node-map.md
v20.2/gssapi_authentication.md
v20.2/show-partitions.md

Also confirmed that these callouts are not longer red warnings.
Fixes #7095.

Use include for enterprise feature callout, where possible

---

v20.1/cost-based-optimizer.md

Fixes #7415. 
This PR is identical to #8609, but in v20.1 docs.

Added note about histograms on ARRAY-typed columns (20.1 backport)

---

releases/v20.2.0-alpha.2.md

Moved release note on #50254 (sql: remove constant folding visitor) to Backward-incompatible section

---

_includes/sidebar-data-v20.2.json
v20.2/alter-database.md
v20.2/alter-schema.md
v20.2/alter-table.md
v20.2/create-schema.md
v20.2/owner-to.md

Fixes #8300.  
Fixes #8316. 
- Added `OWNER TO` page.
In the future, we should look into knocking subcommands down a level in the ToC. For example, placing a page like `OWNER TO` beneath `ALTER TABLE`.

ALTER TABLE ... OWNER TO and ALTER DATABASE ... OWNER TO

---

CONTRIBUTING.md

- `/usr/bin/ruby` has been deprecated sometime back in favor of `/bin/bash` (Got a warning for it, when I used it)
- Got a permission error when installing through `gem`, hence the need to retry with sudo
- Needed ruby-dev package for building some native packages (Got an error)
This would all go down to help reduce friction for future contributors.

Update setup instructions for more distributions

---

_includes/v19.2/sql/diagrams/update.html
_includes/v20.1/sql/diagrams/update.html
_includes/v20.2/sql/diagrams/update.html
v19.2/update.md
v20.1/update.md
v20.2/update.md

Fixes #8219. 
Documents https://github.com/cockroachdb/cockroach/pull/39202.
Note that this PR will conflict with the updates to `UPDATE` documentation in #8656.

UPDATE FROM syntax

---

v20.2/alter-schema.md
v20.2/convert-to-schema.md
v20.2/owner-to.md
v20.2/sql-name-resolution.md

Fixes #7623.
`pg_extension` is already documented in the context of our spatial features (see #7946).
- Added `pg_extension` to general list of virtual schemas on SQL namespace page.
- Removed erroneous links to "Special database names" section. (This section just warns about naming tables after virtual schemas, and says nothing about the virtual schemas).
We have a gap in our docs re: virtual schemas. See https://github.com/cockroachdb/docs/issues/8706.

pg_extension links and updates to virtual schema links

---

_includes/sidebar-data-v20.2.json
_includes/v20.2/sql/diagrams/alter_view.html
_includes/v20.2/sql/diagrams/create_view.html
_includes/v20.2/sql/diagrams/drop_view.html
v20.2/alter-view.md
v20.2/create-view.md
v20.2/drop-view.md
v20.2/migrate-from-oracle.md
v20.2/refresh.md
v20.2/sql-statements.md
v20.2/views.md

Fixes #8254. 
Fixes #8121. 
Fixes #8334. 
Fixes #8358. 
- Updated `CREATE VIEW`, `ALTER VIEW`, and `DROP VIEW` diagrams.
- Updated Views page examples.
- Added new "Materialized views" section to Views page, with examples.
- Added new `REFRESH` syntax page, with examples. 
*Note that this page pilots the new approach to using help text for SQL syntax!*

Materialized views

---

v20.1/interval.md
v20.1/time.md
v20.1/timestamp.md
v20.2/interval.md
v20.2/time.md
v20.2/timestamp.md

Fixes  #7607.
Removed note about precision on downgrades from `INTERVAL`, `TIME`, and `TIMESTAMP` pages.

Removed note on downgrading with precision types

---

releases/v19.1.7.md
releases/v2.1.11.md
releases/v20.1.7.md
releases/v20.1.8.md

In a few places, we were using `cockroach/cockroach-stable:<version>`.
`cockroach-stable` isn't valid. It should just be
`cockroach/cockroach:<version>`.
Fixes #8730.

Fix docker pull command for stable releases

---

_includes/v19.2/sql/disk-spilling-ops.md
v19.2/query-order.md
v20.1/query-order.md
v20.1/vectorized-execution.md
v20.2/query-order.md
v20.2/vectorized-execution.md

Removed paragraph pointing to limitation (https://github.com/cockroachdb/cockroach/issues/23620) that was lifted in 19.2 (https://github.com/cockroachdb/cockroach/pull/38014).

Removed limitation on ordered aggregations

---

v20.1/indexes.md
v20.2/indexes.md

- Added short paragraph linking to `ALTER PRIMARY KEY` for changing bucket size of hash-sharded index.

Link to ALTER PRIMARY KEY to change bucket size of hash-sharded index

---

_includes/v20.2/sql/functions.md

Fixes #5538.
Regenerated functions.md file, on https://github.com/cockroachdb/cockroach/releases/tag/v20.2.0-rc.3 + https://github.com/cockroachdb/cockroach/pull/55996/commits/ae19006f70604b9dc95f726498b5075dd44078ee
See https://github.com/cockroachdb/cockroach/pull/55996.

Regenerated builtin file, with updated crdb_interal.force_retry text

---

v19.2/create-table.md
v19.2/primary-key.md
v20.1/create-table.md
v20.1/primary-key.md
v20.2/create-table.md
v20.2/primary-key.md

Fixes https://github.com/cockroachdb/docs/issues/3420.
Fixes https://github.com/cockroachdb/docs/issues/4911.
- Added new "Performance considerations" section to the Primary Key Constraint page.
- Linked to the "Performance considerations" section to the Primary Key Constraint page and the SQL Performance Best Practices page from the CREATE TABLE page.
- Some other misc updates.
Additional suggestions are welcome.
I'll propagate these changes to 20.2 when they are approved for 20.1.
@ajwerner Adding you for engineering review. If you think someone else should review this instead, please tag the appropriate engineer.

Updated primary key performance guidance

---

v20.2/admin-ui-statements-page.md

Fixes #8205.
BTW @jordanlewis @dhartunian, this table was mostly empty  (only the header row appeared) on `cockroach demo`. The Rows Read and Disk Bytes Read only appear, for me, on `ALTER TABLE` statements, but the values are 0. Is this expected when running demo?

add execution statistics to statements page

---

_includes/v20.1/orchestration/kubernetes-upgrade-cluster.md
_includes/v20.2/orchestration/kubernetes-upgrade-cluster.md
v20.1/admin-ui-overview.md
v20.1/upgrade-cockroach-version.md
v20.2/admin-ui-overview.md
v20.2/upgrade-cockroach-version.md

Fixes #6319.
- For non-orchestrated deployments, this uses guidance from @knz on determining that a node is ready to accept SQL and the next node can be stopped.
- For K8s deployments, uses the guidance from @DuskEagle in the linked issue.
@DuskEagle for the Kubernetes section, it seems the partition would have to be removed from the StatefulSet after the upgrade? Otherwise wouldn't any updates to the STS only affect a single pod? Can you advise on how this would be done?
Also, I am not 100% certain the Helm command is correct. Will need to test.

update rolling upgrades guidance

---

_includes/sidebar-data-v20.2.json
v20.2/geometrycollection.md
v20.2/linestring.md
v20.2/multilinestring.md
v20.2/multipoint.md
v20.2/multipolygon.md
v20.2/point.md
v20.2/polygon.md
v20.2/spatial-features.md
v20.2/spatial-indexes.md

Specifically, this change adds basic reference docs for the following
spatial objects:
- POINT
- LINESTRING
- POLYGON
- MULTIPOINT
- MULTILINESTRING
- MULTIPOLYGON
- GEOMETRYCOLLECTION
Fixes #8567, #8568, #8569, #8570.

Add docs for POINT, LINE, POLYGON, and collections

---

v20.2/cockroach-debug-merge-logs.md
v20.2/cockroach-debug-zip.md
v20.2/debug-and-error-logs.md

Closes #7490 and #8395
Documented the `--redact-logs` flag for `debug-zip` and `debug-merge-logs` commands. Did not document the `redactable-logs` flag for `cockroach start`, `cockroach start-single-node`, and `cockroach demo` because the flag is now enabled by default and no longer needs user input.
Added an example to redact logs and the sample output. Not sure if we need to elaborate on the logging format - IMO, it needs to be a follow-up docs project that's bigger than just redacted logs.

Documented `--redact-logs` flag

---

_includes/v20.2/known-limitations/kms-scheduled-backup.md
v20.2/create-schedule-for-backup.md
v20.2/take-and-restore-encrypted-backups.md

Closes #8778.
Note that this can be removed in 20.2.1 when https://github.com/cockroachdb/cockroach/pull/56099 is merged

Add known limitation for schedule backup + KMS

---

v19.2/import-into.md
v20.1/import-into.md
v20.2/import-into.md
v20.2/import.md

Closes #8585.
Closes #8291.
Closes #8105.
Closes #8289.
Closes #8106.
Closes #7863.
Closes #8419.

IMPORT INTO with default expressions and computed columns

---

v20.2/as-of-system-time.md
v20.2/follower-reads.md
v20.2/topology-follower-reads.md

Removed "experimental" from experimental_follower_read_timestamp

---

_includes/v20.1/app/create-a-database.md
_includes/v20.1/app/python/psycopg2/example.py
_includes/v20.1/app/python/sqlalchemy/example.py
_includes/v20.1/app/python/sqlalchemy/sqlalchemy-large-txns.py
_includes/v20.1/app/start-cockroachdb.md
_includes/v20.2/app/create-a-database.md
_includes/v20.2/app/python/psycopg2/example.py
_includes/v20.2/app/python/sqlalchemy/example.py
_includes/v20.2/app/python/sqlalchemy/sqlalchemy-large-txns.py
_includes/v20.2/app/start-cockroachdb.md
v20.1/build-a-python-app-with-cockroachdb-sqlalchemy.md
v20.1/build-a-python-app-with-cockroachdb.md
v20.2/build-a-python-app-with-cockroachdb-sqlalchemy.md
v20.2/build-a-python-app-with-cockroachdb.md

Per discussion with Andy, Vy, and Eric, we are removing CRC instructions until CRC Free Tier is available and just going with secure demo clusters. I'm leaving the updates Jesse made to the Python tutorials in, but commenting them out so we can revise it later.

Comment out CRC content in Python tutorials as part of #7816

---

v20.2/admin-ui-debug-pages.md
v20.2/architecture/life-of-a-distributed-transaction.md
v20.2/architecture/replication-layer.md
v20.2/architecture/storage-layer.md
v20.2/cluster-setup-troubleshooting.md
v20.2/cockroach-debug-zip.md
v20.2/cockroach-start.md
v20.2/encryption.md
v20.2/known-limitations.md

Fixes #7562 #8392 #8595
- Update almost all mentions of "RocksDB" across the 20.2 docs to say
"the storage engine" as often as possible, and "Pebble" where we must
because it is relevant.
- In particular, update the architecture's storage layer docs to mention
Pebble and link to the Github repo and announcement blog post.

Update docs to note Pebble is the default for 20.2

---

.htmltest_nightly.yml
ci/nightly

Fixes #8094.
See example of successful nightly build run here: https://teamcity.cockroachdb.com/buildConfiguration/Internal_Docs_Nightly/2428145?showLog=2428145_7378__expandAll
"Successful" as in `htmltest` checks return valid results. There is a known issue with 429 errors to GitHub (too many requests): https://github.com/wjdp/htmltest/issues/152. For a quick fix, we could opt out GitHub links from being checked for now to cut down on noise.
Meanwhile, there are a bunch of 404 errors that are valid for fixing. Examples:
Non-OK status: 404 --- docs/v1.0/deploy-cockroachdb-on-microsoft-azure.html --> https://docs.microsoft.com/en-us/azure/virtual-machines/virtual-machines-linux-mac-create-ssh-keys
11:17:33
Non-OK status: 404 --- docs/v1.0/deploy-cockroachdb-on-microsoft-azure.html --> …

Restore nightly CI builds

---

v20.2/performance-benchmarking-with-tpcc-large.md

- Fix 140k results formatting
- Fix a mismatch between the GC TTL setting and its prose description

Fix nits on TPC-C Large page

---

v20.2/install-cockroachdb-mac.html

Fixes #8858.
- Uncomment homebrew install instructions
- Update instructions to mention that this is now v20.2 (not 19.2)
- Note that I manually tested the `brew install`-ed CockroachDB and
verified that spatial features work.

Add back homebrew install instructions for 20.2

---

cockroachcloud/backups-page.md

Note: Will merge once I get the go-ahead from SRE
Closes #8671.

Remove GCP note from CC Backup page

---

v19.1/cockroachdb-in-comparison.md
v19.2/cockroachdb-in-comparison.md
v20.1/cockroachdb-in-comparison.md
v20.2/cockroachdb-in-comparison.md

On [this page](https://www.cockroachlabs.com/docs/dev/cockroachdb-in-comparison.html), Spanner values are mistakenly shown for Yugabyte. 
Not sure who should review, but GitHub recommended Rich =)

Fix error on CockroachDB in Comparison page

---

v20.2/404.md

We were using the updated 404 page on v20.1. We now need to use it in v20.2 since Netlify always redirects 404s to "stable" version.
Related to #8082

Use updated 404 page on v20.2

---

_includes/v20.2/orchestration/start-cockroachdb-operator-secure.md

Update documented CPU/memory requests & limits to address https://github.com/cockroachdb/cockroach-operator/issues/234. Verified that these settings work with `n1-standard-4`.

update default resources

---

_includes/sidebar-data-v20.2.json
_includes/v20.2/spatial/ogr2ogr-supported-version.md
v20.2/export-spatial-data.md
v20.2/known-limitations.md
v20.2/migrate-from-geojson.md
v20.2/migrate-from-geopackage.md
v20.2/migrate-from-openstreetmap.md
v20.2/migrate-from-shapefiles.md
v20.2/spatial-features.md

Fixes #8682, #8822.
- Add an 'Export Spatial Data' page that shows how to get spatial data
out of CRDB.
- Also, note that CRDB requires `ogr2ogr` to be version 3.1.0 or greater
to work properly.

Add docs for exporting spatial data

---

tutorials/katacoda/build-python-app/step3.md

We recently remove our psycopg2 code sample in favor of using a plugin to include the sample from an external repository. The katacoda tutorial needs to download from that external repository.

Correct python file location for download

---

_includes/v20.1/orchestration/kubernetes-upgrade-cluster.md
_includes/v20.2/orchestration/kubernetes-upgrade-cluster.md

Updates in #8615 (specifically for partitions) were lost in v20.2 when adding K8s Operator steps. This commit brings them back, but at the slight expense of imposing a less efficient structure on the doc. This was necessary in order to maintain distinct instructions for Operator/Helm/configs without losing enumeration.

port K8s rolling upgrade guidance back to v20.2

---

_includes/sidebar-data-v20.2.json

Follow-up to #8212.
When I added redirects from the old pages to the new, I forgot to add
the new pages to the TOC sidebar.

Add new TPC-C pages to 20.2 sidebar

---

_includes/v20.2/orchestration/kubernetes-remove-nodes-secure.md
_includes/v20.2/orchestration/kubernetes-scale-cluster.md

Temporarily changed a step in the K8s Operator docs that referenced the secure client pod used to run SQL in the Helm and manual docs, as it was blocking users from completing the tutorial.

quick fix to remove client pod from Operator doc

---

v20.2/install-cockroachdb-linux.html

We got this wrong previously: https://github.com/cockroachdb/docs/pull/8853/files#diff-88796865ae3f0f1e24effa082b938f1525d9f464239cd716d263d84f4fc5a460L37
Fixes #8948.

Fix tar command for linux binary

---

_data/releases.yml
releases/v19.2.11.md
releases/v20.1.4.md
releases/v20.1.5.md
releases/v20.1.6.md
releases/v20.1.7.md
releases/v20.1.8.md
releases/v20.2.1.md
releases/v20.2.2.md

Also link back to GA release notes from patch releases.
Reverts https://github.com/cockroachdb/docs/pull/8965/files#diff-9c8e76d0395d5fcaeb5d07b307307be91d18e8c2be502e74db81407b2c59a13dL5.

Make 20.2.0 notes more visible

---

releases/v20.2.2.md

Remove duplicate release note from v20.2.2 notes

---

_includes/v20.1/misc/tooling.md
_includes/v20.2/misc/tooling.md

Fixes #5260.
I've added a few more IDEs/GUIs to the list of supported developer tools, based on the issues linked in https://github.com/cockroachdb/docs/issues/5260 and the list provided in https://github.com/cockroachdb/cockroach/issues/25467.
Note that I've left out a few of the tools listed, based on available usage data. If you see a tool not listed that you would like listed, please let me know.

Added more developer tools to supported list

---

_includes/v20.2/app/start-cockroachdb.md

Add clarification text to the start instructions per Diana's feedback.

---

_includes/v20.2/backups/advanced-examples-list.md
v20.2/restore.md
v20.2/take-full-and-incremental-backups.md

Driven by a question from @Mattcrdb. into_db only applies to tables restores, not database restores, but this was hard to infer from the existing text.

Improve clarity on database restore naming

---

CONTRIBUTING.md

Changed the ruby installation instructions for contributors. Resolves #9069.

Fix install ruby instructions

---

releases/v20.1.9.md
releases/v20.2.3.md

- Add intro linking back to GA release notes.
- Remove "unstable" from docker image.

Fix latest 20.1 and 20.2 release notes

---

Gemfile.lock
v20.2/alter-table.md
v21.1/alter-table.md

First PR during fixit @lnhsingh for https://github.com/cockroachdb/docs/issues/9184
> Under [Subcommands](https://www.cockroachlabs.com/docs/v20.2/alter-table#subcommands), the third column for ALTER PRIMARY KEY says Yesnes.html) for a table. and seems to have an extra column in the markdown. I think this should just say Yes. 
Changes applied to v20.2 and v21.1
Assigning to you for review

address typo on #9184

---

v20.1/foreign-key.md
v20.2/foreign-key.md
v21.1/foreign-key.md

Add a warning that `import into` will invalidate foreign keys without a `validate constraint` statement. Resolves issue #8651.

Add warning about IMPORT INTO statement

---

v20.2/show-databases.md
v21.1/show-databases.md

This addresses #8852
> The documentation for show databases states currently that no privileges are required
https://www.cockroachlabs.com/docs/stable/show-databases.html#required-privileges
> However this is wrong, for a user to be able list the database with this command they must have been granted `select` privilege on the database
Both v20.2 and v21.1 have been updated.

Add required privileges for SHOW DATABASE 

---

v20.2/frequently-asked-questions.md

Typo added in [`e01e614`](https://github.com/cockroachdb/docs/commit/e01e614d4002eaf4ab750194e8bc8a523844532a#diff-888ecd01f5d9e28c61a8aed0ac5e8196bccfb73795f2ebe7319d459b924536adR31)

Fix typo in FAQ

---

v20.1/operational-faqs.md
v20.1/show-grants.md
v20.2/operational-faqs.md
v20.2/show-grants.md
v21.1/operational-faqs.md
v21.1/show-grants.md

Closes #6328 
The default value for `timeseries.storage.resolution_10s.ttl` is 240h (10 days), not 720h (30 days) as mentioned in docs.
Updated for v21.1, v20.2, and v20.1

Update timeseries storage defaults mentioned in operational FAQs

---

v20.1/show-grants.md
v20.2/show-databases.md
v20.2/show-grants.md
v21.1/show-databases.md
v21.1/show-grants.md

Address feedback noted in #8452 to clarify that `SHOW GRANTS` will list grants for all users and roles on the _current_ database and its tables, _not_ all databases and tables as was previously documented.
Updated for v21.1, v20.2, and v20.1

Clarify description for SHOW GRANTS

---

v20.1/demo-low-latency-multi-region-deployment.md
v20.2/demo-low-latency-multi-region-deployment.md
v21.1/demo-low-latency-multi-region-deployment.md

Pertains to documentation about Low Latency Reads and Writes in a Multi-Region Cluster
Fixes: #8647

Updated --city-pair flag to --city flag for affected docker commands

---

v20.1/cockroach-workload.md
v20.2/cockroach-workload.md
v21.1/cockroach-workload.md

Corrected the `--insert-count` flag on `cockroach workload init ycsb` (was `--initial-count`) and added `--data-loader` to both the tpcc and ycsb workloads.
```
j4-crl:docs$ cockroach workload init ycsb --help
...
...
--data-loader string                How to load initial table data. Options are INSERT and IMPORT (default "INSERT")
...
--insert-count int                  Number of rows to sequentially insert before beginning workload. (default 10000)
```
```
j4-crl:docs$ cockroach workload init tpcc --help
...
...
--data-loader string                     How to load initial table data. Options are INSERT and IMPORT (default "INSERT")
```
Closes #9215

correct ycsb workload flag and add data-loader flags

---

_includes/v19.1/orchestration/kubernetes-limitations.md
_includes/v19.2/orchestration/kubernetes-limitations.md
_includes/v20.1/orchestration/kubernetes-limitations.md
_includes/v20.2/orchestration/kubernetes-limitations.md
_includes/v21.1/orchestration/kubernetes-limitations.md
v19.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
v19.2/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md

Changed minimum Kubernetes version in K8s tutorial from 1.8 to 1.15

---

v20.2/error-handling-and-troubleshooting.md
v21.1/error-handling-and-troubleshooting.md

Fixes #9212.
- Add link from the Developer Guide's errors/troubleshooting page to the
transaction retry error reference page so developers can look up
specific retry error codes when debugging.

Add link to retry error reference from dev docs

---

_includes/v21.1/computed-columns/jsonb.md
v21.1/show-ranges.md

This is a small fix to update an explanation for SHOW RANGES when null start and end keys return.  The jsonb.md change here can be discarded as it's part of another pull request.  I tried rebasing and couldn't get it out of my branch.
Closes https://github.com/cockroachdb/docs/issues/7800

Doc edit for Show Ranges with null start and end keys #7800

---

_includes/v21.1/computed-columns/jsonb.md

This is an example of how to do the issue found in #8847
Looking at the computed column doc again, there's a similar example in the "Add a computed column to an existing table" section of the doc.  That probably should suffice.  If you want to reject this, no worries.  The problem with #8847 is that the user needed an extra set of () and STORED in the example.
root@:26257/defaultdb> ALTER TABLE json_data
ADD COLUMN amount2 DECIMAL
AS ( (json_info->>'amount')::DECIMAL) STORED;
ALTER TABLE
Time: 1.250s total (execution 0.165s / network 1.085s)

Doc for issue 8847

---

_includes/v19.2/start-in-docker/mac-linux-steps.md
_includes/v20.1/start-in-docker/mac-linux-steps.md
_includes/v20.2/start-in-docker/mac-linux-steps.md

update Docker startup steps

---

_includes/v20.1/misc/csv-import-callout.md
_includes/v20.2/misc/csv-import-callout.md
_includes/v21.1/misc/csv-import-callout.md
v20.1/import-into.md
v20.1/import.md
v20.1/migrate-from-csv.md
v20.2/import-into.md
v20.2/import.md
v20.2/migrate-from-csv.md
v21.1/import-into.md
v21.1/import.md
v21.1/migrate-from-csv.md

Resolves issue #4838. Added a note that column order must be the same in user's SQL statement and file being imported to the Migrate from CSV and IMPORT statement docs.

Add column order callout

---

cockroachcloud/free-closed-beta.md

Using the [copy from the email](https://docs.google.com/document/d/1OHRaKknfBifj1bMOzlyg7reUZ4rtkwK4iUUZ7UZdhUk/edit#) that goes out to closed beta users, create a temporary, unlinked doc that explains what CC Free (closed beta) is.
This page will be removed once Free (beta) is released at the end of the month.
Closes #9169.

Add a temp unlinked doc for the CC Free closed beta

---

_data/releases.yml

Order by release rather than date, with the latest to
oldest patch per release.

Fix release list ordering

---

v1.1/architecture/overview.md
v19.1/architecture/overview.md
v19.2/architecture/overview.md
v2.0/architecture/overview.md
v2.1/architecture/overview.md
v20.1/architecture/overview.md
v20.2/architecture/overview.md
v21.1/architecture/overview.md

s/each of these needs/each of these nodes/
Fixes #9244.

Fix incorrect word usage in Architecture Overview

---

_includes/v20.2/orchestration/start-kubernetes.md
v20.2/orchestrate-cockroachdb-with-kubernetes.md

Repurpose the Kubernetes Operator note about
Red Hat to capture docs searches for Open Shift,
IBM, and Cloud Pak. ibm and cloud pak are two
of the more commonly searched terms that currently
return no results. This small change should
improve that.

Mention Open Shift and IBM Cloud Pak

---

v20.2/create-schedule-for-backup.md
v21.1/create-schedule-for-backup.md

As discussed on #8482
I can imagine wanting to not mention anything about an "internal polling mechanism", but without that a reader seems very likely to not be clear about why a backup doesn't start right away, or roughly how long of a delay to expect (although that latter concern isn't addressed super well here either).
@dt @lnhsingh

Attempt to clarify statement on AS OF SYSTEM TIME in scheduled backups

---

_includes/cockroachcloud/connect_to_crc.md

This is a fragment file with begin/end tokens for referring to the commands to start a SQL shell for the dedicated and free-tier of CRC.

New fragment include file for CRC sql commands.

---

_includes/cockroachcloud/use-cockroachcloud-instead.md
cockroachcloud/quickstart-trial-cluster.md
cockroachcloud/quickstart.md
v20.2/orchestrate-a-local-cluster-with-kubernetes-insecure.md
v20.2/orchestrate-a-local-cluster-with-kubernetes.md

Some users do not have access to CC Free (beta) yet.
- Added a note to the Quickstart
- Re-added the old instructions on how to start a cluster using the 
30-day free trial
- Updated notes on other pages that point users to use CC
Closes #9358.

Add note / quickstart for 30-day trial

---

_includes/sidebar-data-v20.2.json
_includes/sidebar-data-v21.1.json
_includes/v20.2/known-limitations/copy-from-clients.md
_includes/v20.2/known-limitations/copy-syntax.md
_includes/v21.1/known-limitations/copy-from-clients.md
_includes/v21.1/known-limitations/copy-syntax.md
v20.2/copy-from.md
v20.2/known-limitations.md
v20.2/sql-statements.md
v21.1/copy-from.md
v21.1/known-limitations.md
v21.1/sql-statements.md

Fixes #9022.
Please review this PR carefully for accuracy.
This statement was fairly difficult to document, for the following reasons:
- We don't support `COPY FROM` in the CockroachDB SQL shell. As a result, I had to use a different client (`psql`) to create a simple example. And I'm not sure how useful this example is...
- We don't support most of the PostgreSQL [`COPY FROM` syntax](https://www.postgresql.org/docs/current/sql-copy.html) (e.g., `WHERE`, `PROGRAM`, etc.). We have several different issues tracking some of the individual, unsupported options and clauses (e.g., https://github.com/cockroachdb/cockroach/issues/54580), but we don't have all of them, so it's a little hard to point to tracking issues or to create "known limitations" for syntax that we might not intend to support. …

COPY FROM docs

---

releases/v21.1.0-alpha.1.md

Follow up on conversation with @arulajmani. 
@jseldess 
FYI, the `cockroach` binary returns links in error and warning messages to the deprecations section of our GA release notes page for major releases. In 20.2, these messages link to https://www.cockroachlabs.com/docs/releases/v20.2.0.html#deprecations. In 21.1, they link to a page that we have yet to create. 
https://github.com/cockroachdb/docs/commit/33ee770b699aead65fc7c1912160236d13f9c281#diff-06124389d47e81e9751a3deb6af80c1c39185669536a72773a5b4064bc9f4b2d was pretty to the v20.2 release date, so I'm guessing we won't make the 21.1 GA page for a while. When we do, we need to remove this redirect.

Adding redirect from 21.1.0 GA URL for links from binary messages

---

_includes/cockroachcloud/quickstart/create-a-free-cluster.md
cockroachcloud/create-your-cluster.md
cockroachcloud/quickstart.md

- Removed the Before You Begin section on the Quickstart
- Added the sign up referral link for CC Free to step 1 of the Create a 
Free Cluster section
Closes #9651

Add referral link to creating a CC Free cluster to Sample Apps

---

tutorials/katacoda/learn-cockroachdb-sql/foreground.sh

To prevent users from getting to the shell prompt by
exiting the sql shell. Testing this in one tutorial
before applying it to others.

Add exec to cockroach demo in learn sql tutorial

---

tutorials/katacoda/playground-20.2/foreground.sh
tutorials/katacoda/playground-20.2/index.json
tutorials/katacoda/playground-21.1/foreground.sh
tutorials/katacoda/playground-21.1/index.json
v20.2/sql-playground.md
v21.1/sql-playground.md

Start cockroach to listen on all IPs. Katacoda requires this
to be able to access the UI.
Also create user for dbconsole access as part of startup
script.

Expose dbconsole in 20.2 and 21.1 sql playgrounds

---

v20.2/sql-playground.md
v21.1/sql-playground.md

Previously, we asked users to look in the terminal
output to find the DB Console user credentials. Now,
we just provide that info in the page intro.

Simplify dbconsole access from sql playgrounds

---

v20.2/remove-nodes.md
v21.1/remove-nodes.md

Addresses [this](https://github.com/cockroachdb/docs/pull/7304#discussion_r568754657) comment.
Our docs state that the new recommissioning behavior begins as of v20.2, so I applied this change to v20.2 and v21.1.

remove incorrect/outdated callout

---

_data/advisories.yml
advisories/a58932.md

Adding Technical Advisory 58932: "HTTP requests can cause full-cluster denial of service (DoS)".
Minor edits of an original [draft](https://docs.google.com/document/d/1piMHNdZ9pPBleI2avPcNmC827dN5hM04ffJAmDH0YFY/) by @knz.
Further comms plans to be discussed [here](https://cockroachlabs.slack.com/archives/CSPK16V51/p1612222917012500?thread_ts=1612216017.010400&cid=CSPK16V51).

Technical Advisory 58932

---

v21.1/connect-to-the-database.md
v21.1/developer-guide-overview.md
v21.1/install-client-drivers.md
v21.1/schema-design-database.md
v21.1/schema-design-overview.md
v21.1/schema-design-schema.md
v21.1/schema-design-table.md
v21.1/secure-a-cluster.md
v21.1/start-a-local-cluster.md

Opening this PR in response to the need for updated best-practice guidance around user-defined schemas.
See https://github.com/cockroachdb/docs/pull/9487/files/0dc7f87c6dd97fa04017c2e0687d08f0dc22d099#r565570489.
Changes include:
- Updated best-practice guidance for databases, user-defined schemas, and tables.
- A new user, schema, and table in the examples in the "Create a Database", "Create a User-defined Schema" and "Create a Table" pages.
The PR also includes:
- Minor updates to the end of pages (`See also`-> `What's next?`).
- Minor updates to formatting and wording on a few pages.

Schema best practice and examples update

---

_includes/v20.2/sql/privileges.md
_includes/v21.1/sql/privileges.md

`SHOW DATABASES` requires `SELECT` privileges on the databases. (https://www.cockroachlabs.com/docs/stable/show-databases.html#required-privileges)
This PR adds databases to the list of objects that support `SELECT` privileges.

Added databases to list of objects with SELECT privileges

---

v20.1/alter-primary-key.md
v20.1/partition-by.md
v20.2/alter-primary-key.md
v20.2/partition-by.md
v21.1/alter-primary-key.md
v21.1/partition-by.md

-  Added note on `NOT NULL` requirement for new PK columns to `ALTER PRIMARY KEY` page. 
Without this constraint, the statement will return the following error:
```
ERROR: cannot use nullable column "valid" in primary key
SQLSTATE: 42P15
```
- Removed outdated requirement note in PARTITION BY docs. 
This fixes https://github.com/cockroachdb/docs/issues/9507.

ALTER PRIMARY KEY doc updates

---

v20.2/export.md
v21.1/export.md

Per a support issue, EXPORT file naming changes in 20.2 can lead to unexpected outcomes.

export: clarify file naming

---

releases/index-cockroachcloud.md

Custom CSS was breaking the Latest badge. Differences didn't show up in the local build but the TeamCity online preview seems accurate.

fix CC All Releases Latest badge css

---

_config_base.yml
_data/releases.yml
_includes/sidebar-releases.json
releases/v20.2.5.md

Fixes https://github.com/cockroachdb/docs/issues/8928.

v20.2.5 release notes

---

v20.1/monitoring-and-alerting.md
v20.2/monitoring-and-alerting.md
v21.1/monitoring-and-alerting.md

- Provided (hopefully) clearer descriptions of how the health check's "unready" status relates to the decommissioning process. The adjustments slightly differ across 20.1, 20.2, and 21.1. 
- In particular, based on our [19.2 decommissioning docs](https://www.cockroachlabs.com/docs/v19.2/remove-nodes#overview), the "unready" behavior was fixed in 20.1 rather than 20.2. I updated the callouts to reflect this.
Thread: https://cockroachlabs.slack.com/archives/C013VDTRA30/p1612475598012800

clarify & update health check's relationship to decommissioning

---

v20.1/authorization.md
v20.2/authorization.md
v21.1/authorization.md

Addresses part of https://github.com/cockroachdb/docs/issues/7968 by adding clarifications on role vs. user on authorization.md.

Clarify user vs. role on Authorization page

---

v20.1/migrate-from-oracle.md
v20.2/migrate-from-oracle.md
v21.1/migrate-from-oracle.md

Change to `WITH delimiter = e'\t'`
Closes #9293

Update delimiter for migrate from oracle example

---

v21.1/cockroach-import.md

Missed @adityamaru's last comment before merging https://github.com/cockroachdb/docs/pull/9788. 
Change privileges from `admin` to `CREATE` on default database.

CLI Import privileges fix

---

cockroachcloud/cluster-management.md
cockroachcloud/console-access-management.md

Admin Tasks on Console Access Management Page
-add delete your organization instructions
-add remove an email address instructions
-add remove a credit card instructions
Cluster Management Page
-add warning that free tier clusters may be deleted after 6 months of no activity
User Authorization Page
-instructions to delete a SQL user were already present. no changes needed.
Closes #9277 and #9767

Data deletion details for CockroachCloud

---

_includes/head.html

This was removed at some point. It leverages the summary front-matter
field as the meta description.

Add meta description into head.html

---

_includes/cockroachcloud/cc-no-user-certs.md
_includes/v21.1/app/pkcs8-gen.md
v21.1/build-a-java-app-with-cockroachdb-hibernate.md
v21.1/build-a-java-app-with-cockroachdb.md
v21.1/connect-to-the-database-cockroachcloud.md
v21.1/connect-to-the-database.md

This PR addresses a couple things:
- Added a note on client authentication. (Follow up on https://github.com/cockroachdb/docs/issues/9858.)
- Added a note on generating PKCS8 keys to the java docs (we removed this information as a result of our demo and Free Tier workflows)
After review, I'll propagate to relevant versions.

Added some notes on user authentication

---

_includes/v20.2/prod-deployment/insecure-test-load-balancing.md
_includes/v20.2/prod-deployment/secure-test-load-balancing.md
_includes/v21.1/prod-deployment/insecure-test-load-balancing.md
_includes/v21.1/prod-deployment/secure-test-load-balancing.md

Instead of the distinct workload binary.
Fixes #5359.

Use cockroach workload in deployment tutorials

---

_includes/v20.2/orchestration/kubernetes-stop-cluster.md
_includes/v21.1/orchestration/kubernetes-stop-cluster.md
v20.2/orchestrate-cockroachdb-with-kubernetes-insecure.md
v21.1/orchestrate-cockroachdb-with-kubernetes-insecure.md

Fixes #9719.
- As discussed with @keith-mcclellan, this removes the command to specifically delete PVCs and PVs (on Operator and Manual deployment docs), and links instead to K8s documentation.
- Also does the above for secret deletion.
- There is a red callout with an explicit warning about deleting PVs.
- This updates 21.1 and 20.2 docs (secure and insecure).

update PVC and PV deletion step

---

v20.2/build-a-spring-app-with-cockroachdb-jdbc.md
v20.2/build-a-spring-app-with-cockroachdb-jpa.md
v21.1/build-a-spring-app-with-cockroachdb-jdbc.md
v21.1/build-a-spring-app-with-cockroachdb-jpa.md

Related to https://github.com/cockroachdb/docs/issues/9858 and https://github.com/cockroachdb/docs/issues/9793.
This PR adds a CC workflow to the JDBC and JPA Spring tutorials.
I chose to retain the secure steps for the local cluster, as I think it will be more helpful for the enterprise customers reading this fairly advanced tutorial.
@lnhsingh

Added CC steps to Spring tutorials

---

v20.1/disaster-recovery.md
v20.2/disaster-recovery.md
v21.1/disaster-recovery.md

Simple typo on the docs that I figured I could just go in and fix in a jiffy.
CockroachBD->CockroachDB

Fix typo on DR docs

---

v20.2/demo-serializable.md
v21.1/demo-serializable.md

Previously, there were duplicate headings on the page, for
Postgres and CockroachDB, and the TOC was linking
just to the first instance of a heading.
Fixes #9349.

Restructure serializable tutorial

---

v21.1/use-cloud-storage-for-bulk-operations.md

- Add deprecation notice for GCS (see Authentication - GCS section). Closes #9822.
- General edits to the page for readability:
- Added a header for the URL format table
- Moved Example URLs to be a subsection under URL Format
- Added Authentication section and moved relevant info for each cloud storage into subsections.  This info used to be provided in footnotes under the URL format table

GCS authentication

---

v20.2/performance-benchmarking-with-tpc-c-10-warehouses.md
v20.2/performance-benchmarking-with-tpc-c-100k-warehouses.md
v20.2/performance-benchmarking-with-tpc-c-10k-warehouses.md
v20.2/performance-benchmarking-with-tpc-c-1k-warehouses.md
v20.2/performance-benchmarking-with-tpcc-large.md
v20.2/performance-benchmarking-with-tpcc-local.md
v20.2/performance-benchmarking-with-tpcc-medium.md
v20.2/performance-benchmarking-with-tpcc-small.md
v21.1/performance-benchmarking-with-tpc-c-10-warehouses.md
v21.1/performance-benchmarking-with-tpc-c-100k-warehouses.md
v21.1/performance-benchmarking-with-tpc-c-10k-warehouses.md
v21.1/performance-benchmarking-with-tpc-c-1k-warehouses.md
v21.1/performance-benchmarking-with-tpcc-large.md
v21.1/performance-benchmarking-with-tpcc-local.md
v21.1/performance-benchmarking-with-tpcc-medium.md
v21.1/performance-benchmarking-with-tpcc-small.md

Previously, we were using the external `workload` binary.
Unfortunately, `cockroach workload fixtures import`, which
we use to more quickly get tpcc data into a cluster,
is undocumented. We'll handle that separately.
Fixes #5067
Fixes #9774
Fixes #6325

Update benchmarking docs to use built-in workload

---

_includes/sidebar-data-v21.1.json
v21.1/choosing-a-multi-region-configuration.md
v21.1/multiregion-overview.md
v21.1/when-to-use-regional-vs-global-tables.md
v21.1/when-to-use-zone-vs-region-survival-goals.md

... with the goal of increasing ease of understanding and findability
from searches.
- Break out 'Choosing a multi-region configuration' from the bottom of
the original overview page; also, add a "locality vs. survival"
feature matrix-y table to make it easier (?) to understand
- Add a "When to use ZONE vs REGION" page for easier searching etc.
- Add a "When to use REGIONAL vs GLOBAL" page, also for easier searching
etc.
Addresses #8958, #9708, #9709, #9884, #9886.

Break out smaller topics from multiregion overview

---

v21.1/cluster-settings.md
v21.1/functions-and-operators.md

Previously, these docs were including from
master.

Include auto-gen docs from release-21.1 branch

---

v19.2/index.md
v20.1/index.md
v20.2/index.md
v21.1/index.md

Fix typo on crdb docs landing page

---

v21.1/show-tables.md

Fixes #9763.
(cluster setting documented by https://github.com/cockroachdb/docs/pull/9904)

Added tip on disabling row count estimation for SHOW TABLES

---

_includes/sidebar-data-cockroachcloud.json
_includes/sidebar-releases.json

Previously, when looking at many of our  specific release note pages,
the sidenav would collapse. Now:
- When looking at any supported production release of CRDB,
the sidenav stays open to:
CockroachDB > Releases > Production Releases > All Production Releases
- When looking at any testing release for the upcoming version,
the sidenav stays open to:
CockroachDB > Releases > Testing Releases
- When looking at any but the latest CockroachCloud release,
the sidenav stays open to:
CockroachCloud > Release Notes > All Release Notes
For CRDB, pages for earlier production releases continue and pages
for earlier testing releases are not reflected in the sidenav.
We could cover those, too, but I'm not sure it's worth the effort.
Fixes #9957
Fixes #8454
One open issue: The "All Production Releases" …

Highlight sidenav for more release note pages

---

_includes/contribute-options.html

Previously, selecting this option on a doc page would
create a docs issue starting with an incorrectly formatted
link to the relevant doc page. Specifically, the page url
would include 2 forward slashes, e.g., docs//v20.2/secure...
Now, the generated link is correct.
Finishes up #8454.

Fix Contribute > Report Doc Issue

---

v20.2/migrate-from-shapefiles.md
v21.1/migrate-from-shapefiles.md

Fixes #9320.
Fixes #9812.
- Updated old broken link to NWS website with a new link to a copy of
the same 1950-2018 data set which was saved by the nice people at
http://archive.org.  This means that the docs can use the same exact
schema names, etc. as before without breaking anything.
Remember kids: COOL URLs DON'T CHANGE!
https://www.w3.org/Provider/Style/URI.html

Fix busted tornadoes spatial data link

---

v20.1/changefeed-for.md
v20.2/changefeed-for.md
v20.2/create-changefeed.md
v20.2/use-cloud-storage-for-bulk-operations.md
v21.1/changefeed-for.md
v21.1/create-changefeed.md
v21.1/use-cloud-storage-for-bulk-operations.md

Closes #6151, #9718, #5806
-add limitation that Avro is only available with Kafka
-add callout that cloud storage sink urls must be prepended with `experimental-` for changefeeds
-mention that core changefeeds can watch multiple tables

CDC batch of changes

---

v20.2/bulk-delete-data.md
v20.2/insert-data.md
v20.2/performance-best-practices-overview.md
v20.2/query-behavior-troubleshooting.md
v21.1/bulk-delete-data.md
v21.1/insert-data.md
v21.1/performance-best-practices-overview.md
v21.1/query-behavior-troubleshooting.md

Fixes https://github.com/cockroachdb/docs/issues/9865.
Note that the second commit includes some refactoring of the SQL performance best practices page.

Dev guide v2 Bulk Delete Data updates

---

v20.2/delete-data.md
v21.1/delete-data.md

Fixes https://github.com/cockroachdb/docs/issues/9864

Dev guide v2 Delete Data updates

---

netlify/build

Fixes #7050.
This enables migration of PR builds away from TeamCity and onto Netlify. Note that this does not yet disable TeamCity PR builds. That should happen in a separate PR once/if people are happy with Netlify build output. This means we might be briefly running vale and htmltest on both TeamCity and Netlify.
New Netlify output: https://app.netlify.com/teams/cockroach-labs/builds/605b333c041fe700089c1f99
Observation from one push:
Netlify: Build time: 3m 45s. Total deploy time: 4m 14s
TeamCity: 4m:18s

Run vale and htmltest on Netlify

---

_includes/sidebar-data-v21.1.json
_includes/v21.1/sql/generated/diagrams/alter_database_add_region.html
_includes/v21.1/sql/generated/diagrams/alter_database_survival_goal.html
_includes/v21.1/sql/generated/diagrams/alter_table_locality.html
v21.1/add-region.md
v21.1/alter-database.md
v21.1/alter-table.md
v21.1/multiregion-overview.md
v21.1/set-locality.md
v21.1/survive-failure.md

- Add docs for ALTER TABLE .. SET LOCALITY {REGIONAL,GLOBAL}
- Add docs for ALTER DATABASE .. ADD REGION (also PRIMARY REGION)
- Add docs for ALTER DATABASE .. SURVIVE {REGION,ZONE} FAILURE
- Edit the 'Multi-region Overview' page to point users to the SQL
reference pages above for syntax examples
Fixes #9096
Fixes #9115
Fixes #9298
Fixes #9301
Fixes #9598
Fixes #9610
Fixes #9617
Addresses #9341
Addresses #9708
Addresses #9709
Addresses #9884
Addresses #9886

Add SQL docs for survival, region, table locality

---

netlify/build

Fixes #10178 
External link check output can be seen at https://app.netlify.com/sites/cockroachdb-docs/deploys/6061ed3dd819900007e49012 or by clicking on "deploy/netlify" below.

Check external links on nightly runs

---

.github/workflows/nightly.yml

Trigger nightly htmltest checks for external links on Netlify, every day at 10 pm UTC.

GitHub Actions to trigger nightly htmltest run

---

_data/releases.yml

v20.2.6 was mistakenly dropped from the release list, so it's back now.

add missing release

---

v21.1/architecture/distribution-layer.md
v21.1/range-merges.md

Fixes #5846.
- Update the 'Distribution Layer' docs with a new section, *Range
Merges*, to hold (most of) the contents of the formerly separate
'Range Merges' page.
- In addition to a light copy edit of the content, we discard the
instructions for turning off range merges, since (AFAICT) that isn't
really a thing most users should be doing in the v21.1+
timeline.  (In fact, based on a quick check it's apparently no
longer a public cluster setting.)
- Update the former standalone 'Range Merges' page to redirect to the
new section of the distribution layer docs mentioned above.

Merge range merges info into architecture docs

---

v20.2/show-tables.md

Follow-up on https://github.com/cockroachdb/docs/pull/9944.
Documents https://github.com/cockroachdb/docs/issues/9763.

(backport) Added tip on disabling row count estimation for SHOW TABLES

---

Gemfile
Gemfile.lock
ci/builder

https://www.ruby-lang.org/en/news/2020/12/25/ruby-3-0-0-released/
> The following libraries are no longer bundled gems or standard libraries. Install the corresponding gems to use these features.
sdbm
webrick
net-telnet
xmlrpc
As people start to use the latest Ruby for local builds, they might run into issues with our current Gemfile. Per above, Ruby 3 no longer bundles certain gems, including `webrick`, which is needed by Jekyll (https://jekyllrb.com/docs/configuration/webrick/).
Therefore install `webrick` explicitly for now. This will not affect users or CI running older Ruby versions. Our TeamCity Docker image and Netlify are both using older Ruby versions.
We will also explicitly install `rss` for now because @jseldess (who is running Ruby 3) saw dependency issues for that. In Ruby 3 …

Modify Gemfile for Ruby 3.0.0 users

---

v20.2/recommended-production-settings.md
v20.2/schema-design-overview.md
v21.1/recommended-production-settings.md
v21.1/schema-design-overview.md

Initial PR to publish this information per https://github.com/cockroachdb/docs/issues/1830, https://github.com/cockroachdb/docs/issues/10031, and the internal SSOT sheet https://docs.google.com/spreadsheets/d/1JWqggZ1tZ_wDI_lrvWdEBtge4hQFvXEZYczQtMhkRjI/.
Going forward, efforts to gather further information for discovering limits or sizing best practices can be addressed separately in the respective issues (or otherwise as separate topics).

Add database object sizing considerations and limits info

---

v20.1/information-schema.md
v20.2/information-schema.md
v21.1/information-schema.md

Fixes https://github.com/cockroachdb/docs/issues/9592.
Fixes https://github.com/cockroachdb/docs/issues/9566.
Fixes https://github.com/cockroachdb/docs/issues/9565.
Fixes https://github.com/cockroachdb/docs/issues/9125.
Fixes https://github.com/cockroachdb/docs/issues/10121.
Fixes https://github.com/cockroachdb/docs/issues/4843.

21.1, 20.2, 20.1 information_schema tables

---

_includes/v20.1/misc/session-vars.html
_includes/v20.2/misc/session-vars.html
_includes/v21.1/misc/session-vars.html

This PR adds the following session variables:
- `locality` (added to 21.1, 20.2, and 20.1; not sure why this was left out in previous releases)
- `default_transaction_use_follower_reads` (related to https://github.com/cockroachdb/docs/issues/9584; will introduce follow-up PR)
- `enable_drop_enum_value` (related to https://github.com/cockroachdb/docs/issues/10137)
Note the following session variables, which exist in v21.1.0-beta.2, but remain undocumented:
- `disable_partially_distributed_plans` (for internal testing - no docs need; https://github.com/cockroachdb/cockroach/pull/50903)
- `override_multi_region_zone_config` (not sure if we need docs for this @rmloveland; https://github.com/cockroachdb/cockroach/pull/62119, https://github.com/cockroachdb/docs/issues/10131)
- …

Updates to 21.1 session variables

---

v20.2/as-of-system-time.md
v20.2/follower-reads.md
v20.2/topology-follower-reads.md
v21.1/as-of-system-time.md
v21.1/follower-reads.md
v21.1/topology-follower-reads.md

Fixes https://github.com/cockroachdb/docs/issues/9089.
Fixes https://github.com/cockroachdb/docs/issues/5210.
@rmloveland I think this fixes https://github.com/cockroachdb/docs/issues/5210, but please let me know if you disagree.

Clarified that follower_read_timestamp returns timestamp

---

_includes/v21.1/app/start-cockroachdb.md
v21.1/build-a-python-app-with-cockroachdb-django.md
v21.1/cockroach-demo.md
v21.1/cockroach-gen.md
v21.1/copy-from.md

Fixes https://github.com/cockroachdb/docs/issues/9634.
Fixes https://github.com/cockroachdb/docs/issues/9541.
Fixes https://github.com/cockroachdb/docs/issues/9635.
@ianjevans This might also fix https://github.com/cockroachdb/docs/issues/9898... only thing is that we still have a "port" placeholder in like half of the hello world samples (e.g., https://github.com/cockroachlabs/hello-world-go-pgx/blob/master/main.go#L37).

Updated cockroach demo connection parameters

---

v21.1/show-tables.md

Fixes https://github.com/cockroachdb/docs/issues/10135.

Added Performance section to SHOW TABLES page

---

_includes/v21.1/sql/generated/diagrams/stmt_block.html

This PR includes the full SQL grammar diagram for 21.1 (built on https://github.com/cockroachdb/cockroach/pull/63168/commits/56fc9e44fc57ccbd95e1e2bc87028dbfb33a389f).
This PR needs to be merged into master in order to merge PRs with SQL diagrams containing updated 21.1 SQL syntax https://github.com/cockroachdb/cockroach/pull/63168.

Updated stmt_block for 21.1

---

_includes/v20.2/sql/diagrams/alter_schema.html
_includes/v20.2/sql/diagrams/create_schema.html
_includes/v20.2/sql/diagrams/drop_schema.html
_includes/v21.1/sql/generated/diagrams/alter_schema.html
_includes/v21.1/sql/generated/diagrams/create_schema.html
_includes/v21.1/sql/generated/diagrams/drop_schema.html
v20.2/alter-schema.md
v20.2/create-schema.md
v20.2/drop-schema.md
v21.1/alter-schema.md
v21.1/create-schema.md
v21.1/drop-schema.md
v21.1/schema-design-schema.md

Fixes https://github.com/cockroachdb/docs/issues/9100.
Related to https://github.com/cockroachdb/cockroach/pull/63168.
This PR adds syntax diagrams for the following statements to 21.1 and 20.2 docs:
- `CREATE SCHEMA`
- `ALTER SCHEMA`
- `DROP SCHEMA`
Each version's docs are based on the version-specific branch of `sql.y`.
The PR also updates the schema name qualification.

Added diagrams for CREATE SCHEMA, ALTER SCHEMA, DROP SCHEMA; updated parameters

---

_includes/v20.2/orchestration/start-cockroachdb-helm-insecure.md
_includes/v20.2/orchestration/start-cockroachdb-helm-secure.md
_includes/v21.1/orchestration/start-cockroachdb-helm-insecure.md
_includes/v21.1/orchestration/start-cockroachdb-helm-secure.md

Added a callout to our Helm docs that addresses current functionality issues.
This will appear at the following docs in v20.2 and v21.1 (can also backport to previous docs versions if desired):
https://www.cockroachlabs.com/docs/stable/orchestrate-cockroachdb-with-kubernetes.html?filters=helm
https://www.cockroachlabs.com/docs/v20.2/orchestrate-cockroachdb-with-kubernetes-insecure#step-2-start-cockroachdb
https://www.cockroachlabs.com/docs/stable/orchestrate-a-local-cluster-with-kubernetes.html?filters=helm
https://www.cockroachlabs.com/docs/v20.2/orchestrate-a-local-cluster-with-kubernetes-insecure#step-2-start-cockroachdb

draft Helm messaging

---

v21.1/as-of-system-time.md
v21.1/follower-reads.md

Fixes https://github.com/cockroachdb/docs/issues/9584.
Goes with https://github.com/cockroachdb/docs/pull/10237.

default_transaction_use_follower_reads

---

v21.1/create-index.md
v21.1/create-table.md

Fixes https://github.com/cockroachdb/docs/issues/9604.
AFAICT, there are no examples of implicit columns in auto-generated index names. But I could be overlooking something.

Updated example hash-sharded index names

---

_config_base.yml
_data/releases.yml
_includes/sidebar-releases.json
releases/v21.1.0-beta.3.md

Fixes https://github.com/cockroachdb/docs/issues/8936.
Not sure what to do about https://github.com/cockroachdb/docs/pull/10241... I think we should just wait for the merge.

v21.1-beta.3 release notes

---

cockroachcloud/create-an-account.md

Hold until Console changes are live.
Add instructions to switch between GitHub and email login methods.
Closes https://cockroachlabs.atlassian.net/browse/CC-3651

CC GitHub Auth

---

_includes/v21.1/known-limitations/cdc.md

Updated cdc known limitations list to remove primary key changes from the "additional target options to be added" bullet. 
Closes #10050

Updated cdc known limitations for primary key changes

---

v21.1/set-locality.md

Fixes #10200.
Explain that when you move a table from `REGIONAL BY TABLE` to `REGIONAL
BY ROW` but have not yet set a new value for the `crdb_region` column,
it is given the value of the primary region by default.

Update docs to note default value of crdb_region

---

v20.2/alter-column.md
v20.2/experimental-features.md
v21.1/alter-column.md

Fixes https://github.com/cockroachdb/docs/issues/9163.
IIUC https://github.com/cockroachdb/cockroach/pull/56629 just reverts `SET TYPE` to 20.1 behavior, correct?

prohibit ALTER TABLE SET DATA TYPE requiring conversion/validation

---

v21.1/jsonb.md

Fixes https://github.com/cockroachdb/docs/issues/10086.
@chrisseto 
I added some very basic examples - happy to edit/remove those if they don't make sense.

Numeric JSON values can be casted to numeric types

---

_includes/sidebar-data-v21.1.json
v21.1/cockroach-demo.md
v21.1/frequently-asked-questions.md
v21.1/simulate-a-multi-region-cluster-on-localhost.md

Fixes #10007.
- Add a new page 'Simulate a multi-region cluster on localhost', with
instructions for using `cockroach demo --global ...` This will be part
of the infrastructure for creating/updating multi-region demos in our
docs that highlight the new features coming for v21.1.

Document simulating a multi-region cluster locally

---

v21.1/demo-low-latency-multi-region-deployment.md

A temporary enterprise license comes built-in with `cockroach demo`.

Remove unnecessary enterprise license prereq

---

releases/v20.1.14.md

The Source button name was missing, for some reason. Added it back.

add missing button name

---

_includes/v20.2/known-limitations/unordered-operations.md
_includes/v21.1/known-limitations/unordered-distinct-operations.md
v20.2/known-limitations.md
v20.2/vectorized-execution.md
v21.1/known-limitations.md
v21.1/vectorized-execution.md

Fixes #9609
Fixes #9922
Also clarifies the lack of support for disk spilling for hash aggregations in 20.2 docs.

Disk spilling support for hash aggregations

---

v20.2/orchestrate-cockroachdb-with-docker-swarm-insecure.md

There is no container named cockroachdb-0, but there is a container named cockroachdb-3.

Fix containers names when cluster stopping

---

v20.2/build-a-go-app-with-cockroachdb.md
v21.1/build-a-go-app-with-cockroachdb.md

The PGX hello world tutorial won't run for CockroachCloud with the following line of code:
```
config.TLSConfig.ServerName = "localhost"
```
I believe this line is required to run the app against the demo cluster, which uses the `require` SSL mode.
Thanks @kathancox for finding this bug!

Added missing info to PGX tutorial

---

_includes/sidebar-data-v21.1.json
v21.1/demo-low-latency-multi-region-deployment.md

- Minor language tweaks.
- Added explicit commands for applying REGIONAL BY ROW
to all relevant tables. This was a burden to do manualy
when I was testing the tutorial.
- Renamed tutorial in sidenav.

Tweak multi-region tutorial

---

_includes/head.html

On current site, non-versioned docs pages have incorrect canonical url resulting in 404s.

Correct canonical url for non-versioned docs pages

---

v20.2/cockroachdb-in-comparison.md
v21.1/cockroachdb-in-comparison.md

@jseldess issue is done! if anything needs to be edited, let me know :) 
issue: #10243

removed text that says "and click CockroachDB answers to view related documentation." in v20.2 & v21.1

---

v21.1/restore.md

Closes #10374 
Added note to `RESTORE` page to confirm that it doesn't support restoring backups made by newer versions.

Added note to confirm RESTORE does not support newer version backups

---

v21.1/install-cockroachdb-linux.html
v21.1/install-cockroachdb-mac.html

Technically, the minimum required is 1.15.3:
https://github.com/cockroachdb/cockroach/blob/release-21.1/build/go-version-check.sh#L10
However, 1.15.11 avoids these Go bugs:
https://github.com/golang/go/issues/45076
https://github.com/golang/go/issues/45187
https://github.com/golang/go/issues/42884
So to prevent users from running into those, we listing
1.15.11 as the minimum required version, followed by
a note that you can use IGNORE_GOVERS=1 to try building
with older versions.
Fixes #10468
Fixes #9081

Update Go version requirement for building 21.1 from source

---

v21.1/install-cockroachdb-windows.html
v21.1/known-limitations.md
v21.1/recommended-production-settings.md

- Remove zoneinfo step from Windows install doc.
- Remove tzdata known limitation.
- Update tzdata dependency in product checklist.
Fixes #9082

Timezone db now built into cockroach

---

cockroachcloud/network-authorization.md

VPC actually chosen in Step 4, and CIDR range found in Step 5. Thanks for the catch, Joe!

PrivateLink fix typos referencing step numbers

---

_config_base.yml
_data/releases.yml
_includes/sidebar-releases.json
releases/v21.1.0-rc.1.md

Fixes https://github.com/cockroachdb/docs/issues/8937.

v21.1.0-rc.1 release notes

---

releases/release-support-policy.md
v20.2/licensing-faqs.md
v21.1/licensing-faqs.md

Closes #10351
- Updated timelines for 20.2 and 21.1 Licensing FAQs
- Updated release support policy/EOL timeline
- No feature licensing needs to be changed as far as I can tell

Update Licensing Timelines for 21.1

---

_includes/v20.2/cdc/create-core-changefeed.md
_includes/v21.1/cdc/create-core-changefeed.md

Corrected the missing `start-single-node` to the core changefeed example
Closes #9805

Corrected mistake in core changefeed example

---

v20.2/sql-feature-support.md
v21.1/postgresql-compatibility.md
v21.1/sql-feature-support.md

See commits for details.
Fixes https://github.com/cockroachdb/docs/issues/10524.
Fixes https://github.com/cockroachdb/docs/issues/10361.
Fixes https://github.com/cockroachdb/docs/issues/10349.
TBH, there weren't that many SQL feature updates to add this release. Feel free to request additions - happy to make any revisions.

21.1 SQL Support Updates

---

_includes/v21.1/sql/import-into-regional-by-row-table.md
v21.1/import-into.md
v21.1/import.md
v21.1/known-limitations.md

Fixes #10226
- Add to Known Limitations that we can't currently IMPORT seamlessly
into REGIONAL BY ROW tables.  Document a workaround from the CRDB
tests.
- Add a side limitation that we can't ALTER COLUMN to make something
hidden (yet).
- Add notes and links to the above from the IMPORT and IMPORT INTO
pages.

Document workaround for IMPORT into RBR limitation

---

v21.1/choosing-a-multi-region-configuration.md
v21.1/multiregion-overview.md
v21.1/partitioning.md
v21.1/when-to-use-regional-vs-global-tables.md
v21.1/when-to-use-zone-vs-region-survival-goals.md

This is the analogue to #10052 (ALTER DATABASE ... ADD REGION) where we
mark various high-level pages describing multi-region capabilities with
the "enterprise feature" tag so users know about it up front.

Multiregion things require an enterprise license

---

v21.1/indexes.md
v21.1/inverted-indexes.md
v21.1/multiregion-overview.md

Fixes #10066
- Update 'Multi-Region Overview' and 'Indexes' pages to note that the
auto-partitioning of indexes on REGIONAL BY ROW tables also applies to
inverted indexes
- Update 'Inverted Indexes' page with a new section noting the above
behavior

Inverted index on RBR table is auto-partitioned

---

_redirects

This redirect was redirecting from /docs/cockroachcloud
to /docs/cockroachcloud/stable. It dates from when CC
docs were versioned. They are no longer versioned.

Remove old cockroachcloud redirect

---

_includes/sidebar-data-v21.1.json
v21.1/cluster-api.md
v21.1/monitoring-and-alerting.md

This is an enhanced version of the doc originally reviewed by @piyush-singh and @itsbilal. It still needs a thorough review for technical accuracy as it has had many updates.
Preview:  
https://deploy-preview-10532--cockroachdb-docs.netlify.app/docs/v21.1/cluster-api  
https://deploy-preview-10532--cockroachdb-docs.netlify.app/docs/v21.1/monitoring-and-alerting
Please also see the linked [API reference](https://cockroachlabs.com/docs/api/cluster/v2.html). Further enhancements to that page will come in separate PRs, but recommendations are welcome. Intended improvements include the following, though not all may be completed prior to the CRDB v21.1 release:
* Template/Redoc settings
- Limit request sample languages: perhaps just to shell+curl, maybe a couple others in addition.
- Remove the …

Add Cluster API v2 doc to complement its reference page

---

_includes/v21.1/spatial/zmcoords.md
v21.1/geometrycollection.md
v21.1/linestring.md
v21.1/multilinestring.md
v21.1/multipoint.md
v21.1/multipolygon.md
v21.1/point.md
v21.1/polygon.md
v21.1/spatial-glossary.md

Fixes #9706.
- Update the following pages to describe that we also support Z and M
coords:
- POINT
- LINESTRING
- POLYGON
- MULTIPOINT
- MULTILINESTRING
- MULTIPOLYGON
- GEOMETRYCOLLECTION
- For the GEOMETRY data type, we update its entry in the 'Spatial
Glossary' to point to the above docs, which give specifics

Add docs for spatial storage of Z/M coordinates

---

_includes/cockroachcloud/cockroachcloud-pricing.md
cockroachcloud/create-your-cluster.md

Specified machine types, storage types, and AWS IOPS per node in Step 5 of **Create Your Cluster** page.
Closes: https://cockroachlabs.atlassian.net/browse/CC-3698?atlOrigin=eyJpIjoiNjAwMWVlYWI3Y2U4NDlkMzg2ODUxOTkyY2FjN2U4Y2YiLCJwIjoiaiJ9
Question: Do we want to include IOPS for GCP cluster?

CC machine type, storage, and IOPS info

---

v20.2/take-full-and-incremental-backups.md
v21.1/take-full-and-incremental-backups.md

Added the link to the end of this paragraph in its own sentence. Avoiding a long link out in the middle of the current sentence and making it clearer to the reader what page they're heading to re cloud storage.
Closes #10573

Added link text to cloud storage bulk operations

---

v20.2/common-errors.md
v20.2/import-into.md
v21.1/common-errors.md
v21.1/import-into.md

Added more detail in the considerations section of `IMPORT INTO` that it's insert only. Also added the key collision warning to the common errors doc.
Closes #10028

Added key collision warning w IMPORT INTO to common errors and sql docs

---

_includes/sidebar-data-cockroachcloud.json
cockroachcloud/upgrade-policy.md
cockroachcloud/upgrade-to-v21.1.md
releases/v21.1.0.md

Follow-up to https://github.com/cockroachdb/docs/pull/10500. 
Fixes #10502

Update CC docs for 21.1

---

v21.1/configure-logs.md
v21.1/logging-use-cases.md

- Fixed some YAML alignment and link formatting.
- Clarified how the YAML defaults are overriden.
- Moved `DEV` channel section to a more intuitive location on the page.

logging corrections and minor improvements

---

v20.2/cockroach-version.md

Fixes #9955
Fixes #9954
Backport of https://github.com/cockroachdb/docs/pull/10490.

Update cockroach version docs for v20.2

---

v20.2/postgresql-compatibility.md
v21.1/postgresql-compatibility.md

Background: https://cockroachlabs.slack.com/archives/C01PHNMUFLN/p1621525420022500

Removed pgwire version from PostgreSQL Compatibility page

---

.github/workflows/changed_files.yml
_includes/v21.1/demo_movr.md
v21.1/make-queries-fast.md

Modifies the GitHub action to link changed documentation topics to the Netlify preview site for the PR.
We can anticipate the preview site URL using the PR number and the changed file. Non-Markdown files and Markdown files that are in directories that begin with an underscore (e.g. `_includes/v21.1/file.md`) are not linked.
I also added a step to update any existing changed file comment so the action doesn't create multiple comments.

Linking changed doc content to the preview build.

---

v20.2/export.md
v21.1/export.md

Added the two new `EXPORT` options for CSV files. With this change adapted the option layout to match the `IMPORT` page. 
Included `compression` option in the examples with output to extend that section.
Closes #10493

Adapted export kv option table & added two new options

---

v20.2/backup.md
v21.1/backup.md

Included more definition to "other backups" for db + tables and UDT + UDS. 
I *think* external storage and cluster backups are covered here already.
Closes #10400

Added detail to other backups in privileges section

---

_includes/head.html
_redirects

Restores /stable and /dev as canonical links instead of using versioned URLs.

Restore /stable and /dev as canonical links

---

v21.1/multiregion-overview.md

Looks like whenever this was moved into an include, they used copy instead of cut.

Remove duplicated text in multiregion-overview.md

---

_includes/sidebar.html
_includes/sidebar.js.html
_includes/version-switcher.html
_layouts/default.html
js/initSidebar.js

Make scripts defer and async where appropriate. Tweak version menu to avoid layout shift.
Motivated by Lighthouse recommendation.
Addresses https://github.com/cockroachdb/docs/issues/10697

Move sidebar JS later in the page to avoid blocking rendering

---

_includes/v21.1/sql/unsupported-postgres-features.md
jekyll-algolia-dev/lib/jekyll/algolia/indexer.rb

Searching for IBM currently returns no results. It's a somewhat
recurring search query, so this change should at least return
something, which is better than nothing.

Add OpenShift and IBM reference to 21.1 Kubernetes tutorial

---

v20.2/stream-data-out-of-cockroachdb-using-changefeeds.md
v21.1/stream-data-out-of-cockroachdb-using-changefeeds.md

Closes #10698 
Corrected the syntax on the code block that was preventing the `SET CLUSTER` setting from showing up in the rendered page. Also corrected a incorrect table name that would create an error in the example.

Correction org setting cdc

---

releases/v21.1.2.md

The lines replaced here are functions, not cluster settings. Reword as
appropriate.

releases/v21.1.2: fix typo mentioning functions as cluster settings

---

v20.2/connection-pooling.md
v21.1/connection-pooling.md

This helps address _some_ questions about pool sizing in deployments
where a large cluster is shared by many applications.
I don't want to try to address every possible use case, so I also added
a recommendation to perform experimentation.

Add guidance for connection pools in microservice architectures

---

_includes/v20.1/orchestration/start-kubernetes.md
_includes/v20.2/orchestration/start-kubernetes.md
_includes/v21.1/orchestration/start-kubernetes.md
v20.1/orchestrate-cockroachdb-with-kubernetes-insecure.md
v20.1/orchestrate-cockroachdb-with-kubernetes.md
v20.2/orchestrate-cockroachdb-with-kubernetes-insecure.md
v20.2/orchestrate-cockroachdb-with-kubernetes.md
v21.1/deploy-cockroachdb-with-kubernetes.md

Addresses #10479 for single-region deployments.
Also removed the callout about defining a default `gcloud` region/zone, since a regional cluster requires an explicit `--region` flag and it would send a mixed message to also define an unrelated default region.
The multi-region GKE doc needs a deeper overhaul. I didn't update it because parts of the Python script used in that doc appear to reference zone values, and I'm not sure whether they would be broken by specifying a regional cluster.

specify regional clusters in single-region GKE deployments

---

v19.1/build-a-python-app-with-cockroachdb-sqlalchemy.md
v19.2/build-a-python-app-with-cockroachdb-sqlalchemy.md
v20.1/build-a-python-app-with-cockroachdb-sqlalchemy.md
v20.2/build-a-python-app-with-cockroachdb-sqlalchemy.md
v21.1/build-a-python-app-with-cockroachdb-sqlalchemy.md

Updating the external links to the https://github.com/cockroachlabs/simple-crud-python-sqlalchemy repo (the original repo has been renamed).
I'll add remote-includes and the relevant docs updates in a forthcoming PR.

Updated URLs for simple-crud-python-sqlalchemy repo

---

_includes/v20.2/backups/bulk-auth-options.md
_includes/v21.1/backups/bulk-auth-options.md
v21.1/backup.md
v21.1/manage-a-backup-schedule.md
v21.1/restore.md
v21.1/take-and-restore-encrypted-backups.md
v21.1/take-and-restore-locality-aware-backups.md
v21.1/take-backups-with-revision-history-and-restore-from-a-point-in-time.md
v21.1/take-full-and-incremental-backups.md

Closes #10285 
Relates to #10544
Added a toggle to the example sections of `BACKUP` and `RESTORE` (v21.1) for s3, gcs, and azure. This covers some issues and questions around specific URLs for the cloud options. 
Possibility to add further storage options to toggle in future. And gives the opportunity to provide more detail on some of the examples when cloud specific.
This toggle setup will be replicated across all the bulk operations, `IMPORT`, `EXPORT` etc.

Added cloud toggle examples to BACKUP & RESTORE pages v21.1

---

_includes/v21.1/app/start-cockroachdb.md
_includes/v21.1/sql/connection-parameters.md
_includes/v21.1/sql/multiregion-example-setup.md
_includes/v21.1/sql/shell-commands.md
_includes/v21.1/sql/shell-help.md
_includes/v21.1/sql/shell-options.md
_includes/v21.1/sql/start-a-multi-region-demo-cluster.md
v21.1/build-a-go-app-with-cockroachdb-gorm.md
v21.1/build-a-go-app-with-cockroachdb-pq.md
v21.1/build-a-go-app-with-cockroachdb.md
v21.1/build-a-python-app-with-cockroachdb-django.md
v21.1/build-a-python-app-with-cockroachdb-sqlalchemy.md
v21.1/build-a-python-app-with-cockroachdb.md
v21.1/cockroach-demo.md
v21.1/cockroach-dump.md
v21.1/cockroach-sql.md
v21.1/copy-from.md
v21.1/create-database.md
v21.1/demo-low-latency-multi-region-deployment.md
v21.1/movr-flask-deployment.md
v21.1/movr-flask-setup.md
v21.1/schema-design-database.md
v21.1/schema-design-indexes.md
v21.1/schema-design-schema.md
v21.1/schema-design-table.md
v21.1/schema-design-update.md

Fixes https://github.com/cockroachdb/docs/issues/10661.
Fixes https://github.com/cockroachdb/docs/issues/10660.
Fixes https://github.com/cockroachdb/docs/issues/10659.
Fixes https://github.com/cockroachdb/docs/issues/10658.
Fixes https://github.com/cockroachdb/docs/issues/9142.
Fixes https://github.com/cockroachdb/docs/issues/9143.
Fixes https://github.com/cockroachdb/docs/issues/9131.
This PR includes changes to the CLI reference docs for `cockroach sql` and `cockroach demo`, and updates to examples affected by the changes linked in the `cockroach` PRs above.

Misc 21.1.1 CLI updates

---

v21.1/known-limitations.md

As discussed in https://github.com/cockroachdb/docs/pull/10549#pullrequestreview-658845119
Limitation appears to have been removed in https://github.com/cockroachdb/cockroach/pull/63881

Remove `crdb_region` hidden column limitation

---

v21.1/deploy-cockroachdb-with-kubernetes.md
v21.1/monitor-cockroachdb-kubernetes.md
v21.1/operate-cockroachdb-kubernetes.md

Removing 'beta' messaging for Operator GA release tomorrow.
Also added missing filter goggles on the Monitoring K8s page.

remove 'beta' messaging; add missing filter toggles

---

v21.1/configure-logs.md
v21.1/logging-use-cases.md

Enhanced the network logging docs. (Couldn't find an issue on this, though the task was outstanding.)
This was originally planned to be a tutorial on sending logs to a Fluentd server and collecting them with an external tool. After discussion with @thtruo, it seems that adding a section to the Logging Use Cases doc should be sufficient to cover the CRDB functionality. Instructing the user on their Fluentd configuration is beyond the scope of our docs.
Also fixes #10898.

document network logging use case

---

v20.2/architecture/replication-layer.md
v21.1/architecture/replication-layer.md

Fixes #10913.
- Update 'Replication Layer' docs with a new section 'How leases are
transferred from a dead node', which explains the process step by step
at a high level.
- Note: the steps vary slightly between the v20.* and v21.* series due
to some recent changes in the CRDB PR linked from the fixed issue.

Docs on how leases are transferred from dead nodes

---

v19.2/build-a-go-app-with-cockroachdb.md
v20.1/build-a-go-app-with-cockroachdb.md
v20.2/build-a-go-app-with-cockroachdb.md
v21.1/build-a-go-app-with-cockroachdb.md

This PR updates the URLs to the simple crud golang pgx app repo (formerly named `hello-world-go-pgx`)

Updated go-pgx GH repo URLs for repo rename

---

v20.2/stream-data-out-of-cockroachdb-using-changefeeds.md
v21.1/stream-data-out-of-cockroachdb-using-changefeeds.md

Closes #10793 
Added a comparison table to the top of the 20.2, 21.1 pages re enterprise & core changefeeds — replacing the bullet points

Table addition for differences between core/enterprise

---

_includes/sidebar-data-v21.1.json
v21.1/multiregion-scale-application.md

Fixes https://github.com/cockroachdb/docs/issues/10455.
This PR introduces a new page with guidance on scaling from single-region to multi-region. 
The page includes some general guidance on representing `crdb_region` columns in an ORM, for DML statements, with an example for SQLAlchemy. We can add other examples (notably, in Hibernate) after publishing this page.

Added guidance for scaling applications to multiple regions

---

cockroachcloud/run-bulk-operations.md

Adjustments to make clear that only `userfile` storage is available on CC Free tier

Small language changes for clarification

---

v20.2/known-limitations.md
v21.1/known-limitations.md

Fixes #10966
Related to cockroachdb/cockroach#55318 
Adds a known-issue to v21.1 and v20.2 for statements that use inverted indexes and filters with both JSON fetch values and containment operators.

Adding known limitation for inverted index scans.

---

_includes/sidebar-data-v20.2.json
_includes/sidebar-data-v21.1.json
v20.2/export.md
v21.1/export.md

Closes #10971 
The main sidebar on the docs page still included `EXPORT (enterprise)`. As of 20.2 `EXPORT` doesn't require an enterprise license. This caused confusion for a customer recently. Also updated a sentence at the top of the page to avoid enterprise-related language while still pointing to the non-distributed examples. 
Made these adjustments to 21.1 & 20.2

Adjustments to make export/enterprise language clearer

---

cockroachcloud/frequently-asked-questions.md

https://cockroachlabs.atlassian.net/browse/CC-4683
Clarify in the FAQ that you can still use vpc peering if not set up at cluster creation, but you will be locked into the default IP range .

Add VPC peering FAQ

---

v21.1/configure-logs.md

Clarified that the `stderr` log message format can't be changed.

clarify stderr log format

---

v21.1/community-tooling.md

DbUp supports crdb vis-a-vis its support of postgres databases using dotnet's `npgsql` driver.

Adding DbUp

---

v20.1/build-a-nodejs-app-with-cockroachdb.md
v20.2/build-a-nodejs-app-with-cockroachdb.md
v21.1/build-a-nodejs-app-with-cockroachdb.md

Updated remote include URLs following the node-postgres sample app repo rename.
See https://github.com/cockroachlabs/example-app-node-postgres.

Updated remote include links for node-postgres sample app

---

v20.1/architecture/sql-layer.md
v20.2/architecture/sql-layer.md
v21.1/architecture/sql-layer.md

Addresses #10794
- Update page overview with more detail
- Update parsing, physical planning, and logical planning sections
- Add a section on schema changes
- Various small copy edits throughout
Much of the language in these changes is taken from the SIGMOD paper
[1].  All credit goes to the paper's authors, any errors were introduced by me.
[1] https://www.cockroachlabs.com/blog/cockroachdb-sigmod-2020/

Update 'SQL Layer' with SIGMOD paper info

---

v21.1/known-limitations.md

Follow-up on https://cockroachlabs.slack.com/archives/CC5CX8EKE/p1629155750071600.
Please let me know if there is a better tracking issue to reference, as this limitation calls out our lack of support for HTTP(S) connections in general (and not just our incompatibility with PostgREST).

Added HTTP(S) connections to known limitations

---

v20.1/known-limitations.md
v20.2/known-limitations.md
v21.2/known-limitations.md

Follow-up of https://github.com/cockroachdb/docs/pull/11083

Duplicated HTTP(s) connection limitation to 20.1, 20.2, and 21.2 docsets

---

releases/v20.2.14.md

Based on Slack convo, explicitly call out that the Overview page and Hardware dashboard will no longer show all details for non-admin users.
Fixes #11084.

Add clarification message to v20.2.14 RNs per customer feedback.

---

v21.1/movr-flask-deployment.md
v21.2/movr-flask-deployment.md

Related to https://github.com/cockroachdb/docs/pull/11063 and https://github.com/cockroachdb/docs/issues/11020.
I tested this tutorial by applying all of these changes to the live deployment at https://movr.cloud. Internally, you can see these changes in the "movr-test" GCP project.

Added VPC peering to CC/GCR deployment

---

v20.2/deploy-app-gcr.md
v21.1/deploy-app-gcr.md
v21.2/deploy-app-gcr.md

The include used in step 1.1 expects a page-level variable for the referral ID. This variable was missing.

Fix CC referral ID on GCR tutorials

---

.github/workflows/changed_files.yml

This is a test to see if changing the event type to `pull_request_target` will trigger the changed files workflows from forked repositories.
See the note under "Action inputs" here: https://github.com/peter-evans/create-or-update-comment

Changing the event type to maybe enable changed files from forks.

---

.github/workflows/changed_files.yml

Reverts cockroachdb/docs#11238
Using `pull_request_target` resulted in an error.

Revert "Changing the event type to maybe enable changed files from forks."

---

v20.2/build-a-python-app-with-cockroachdb-django.md
v20.2/install-client-drivers.md
v21.1/build-a-python-app-with-cockroachdb-django.md
v21.1/install-client-drivers.md
v21.2/build-a-python-app-with-cockroachdb-django.md
v21.2/install-client-drivers.md

This PR updates the existing Django tutorial to match the refactored sample app now located at https://github.com/cockroachlabs/example-app-python-django. There will be no Django "hello-world".
I'll propagate all changes to v20.2, v21.1 docsets after these changes are approved.
Fixes https://github.com/cockroachdb/docs/issues/9285.
Related to https://github.com/cockroachdb/docs/pull/11063.

Django app refactor

---

cockroachcloud/quickstart.md

In `Quickstart with CockroachCloud Free` tab `Download the CA certificate` and `Use the built-in SQL client` both the steps has same step number. This pull request changes the step number for `Use the built-in SQL client` to 5.

Fix step number

---

.github/workflows/changed_files.yml

Although we'd like to list the changed files in PRs from forked repos, GitHub can't use security tokens across forks when posting the comment with the changed file output. Until we can find a solution to this, we should just turn off this workflow in PRs from forked repos.

Adding a condition to not run list-changed-file workflow for PRs from forks.

---

v20.2/upgrade-cockroach-version.md
v21.1/upgrade-cockroach-version.md
v21.2/upgrade-cockroach-version.md

Fixes #11228.
Our upgrade docs are instructing the user to download the binary using two separate commands, which now causes an error/warning on the command-line. This PR combines the 2 commands into one for both Mac and Linux.

fix binary download commands

---

_includes/cockroachcloud/userfile-examples/backup-userfile.md
_includes/v21.1/userfile-examples/backup-userfile.md
v21.1/cockroach-userfile-upload.md

Closes #10978 
Added a **potential** example to the `cockroach userfile upload` page to provide an easier method to upload recursively in 21.1 and 20.2 where the `--recursive` flag is not going to be present. 
Bash script or piped command ideas included in this commit, not sure which would be preferable.

Options for recursive upload example

---

_includes/v20.2/sql/role-considerations.md
v20.2/alter-role.md
v20.2/create-role.md
v21.1/alter-role.md
v21.1/auto-tls.md
v21.1/create-role.md
v21.2/alter-role.md
v21.2/auto-tls.md
v21.2/create-role.md

fixes https://github.com/cockroachdb/docs/issues/8686
This also includes a rewording to use the term "role option" instead of
"parameter" to describe these properties.
Also, I removed a bullet point that said that roles cannot login. That's
no longer true, and there's an example at the bottom of the page that
shows how to create a role that can login.

sql: clarify that role options are not inherited

---

v21.2/cockroach-debug-zip.md

Documented the 48-hour timeframe implemented in https://github.com/cockroachdb/cockroach/pull/64128.
Also clarified this section of the `debug zip` doc.

clarify 48-hour debug zip collection

---

v21.2/cluster-settings.md
v21.2/functions-and-operators.md

Updated the branch versions on the 21.2 remove-includes for built-in functions and cluster settings.
Fixes https://github.com/cockroachdb/docs/issues/11439.

Updated version on remote functions and settings includes

---

_config_base.yml
_includes/v20.2/orchestration/start-cockroachdb-operator-secure.md
_includes/v21.1/orchestration/start-cockroachdb-operator-secure.md
_includes/v21.2/orchestration/start-cockroachdb-operator-secure.md

We're going to be making some changes on the master branch of the operator including some of the manifest files referenced here in the docs. Before we do, I wanted to make sure that it wouldn't break anything that we're recommending people do to use the operator.
I've added `operator_version` to the main site config and referenced that in all of the _start-cockroachdb-operator-secure.md_ files. This changes the links from `https://.../master/...` to `https://.../<version>/...`. Now when we change something on master, we don't need to worry about it breaking our documentation.
The one downside here is that we'll need to change this value after we cut a new release. I think this is worth the tradeoff and can easily be added to our deployment steps.

Ensure we reference a tagged release of the operator

---

v21.1/install-cockroachdb-mac.html
v21.2/install-cockroachdb-mac.html

The CTA to provide an email address is missing because the uid value was duplicated in the first two installation methods.

Fix missing CTA.

---

v21.1/computed-columns.md

Stored computed columns can be a foreign key reference. Virtual columns cannot. Neither can reference a foreign key.

Correct foreign key restriction for computed columns

---

v21.1/demo-low-latency-multi-region-deployment.md
v21.2/demo-low-latency-multi-region-deployment.md

Fixes #11786
- Instead of referring to "regional tables" generally, we update to say
`REGIONAL BY ROW` (which is what we meant, and what the doc already
links to).

Update contradictory recommendation re: localities

---

_config_base.yml
_data/releases.yml
_includes/sidebar-releases.json
releases/v21.2.0-beta.1.md
releases/v21.2.0-beta.2.md

Closes #10715, #10716
Release notes for v21.2.0-beta.1 and beta.2
For review: Note that this includes **already edited** notes from the alpha that were never released. Markdown comments show the items that do not need review

Release notes v21.2.0 beta.1 and v21.2.0-beta.2

---

v20.2/pg-catalog.md
v21.1/pg-catalog.md
v21.2/pg-catalog.md

Updated pg_catalog docs to reflect 21.2 updates done by @mnovelodou.
Fixes https://github.com/cockroachdb/docs/issues/11803.
Fixes https://github.com/cockroachdb/docs/issues/11404.
Fixes https://github.com/cockroachdb/docs/issues/11389.
Fixes https://github.com/cockroachdb/docs/issues/11372.
Fixes https://github.com/cockroachdb/docs/issues/11333.
Fixes https://github.com/cockroachdb/docs/issues/11318.
Fixes https://github.com/cockroachdb/docs/issues/11444.

21.2 pg_catalog table updates

---

v20.1/known-limitations.md
v20.2/known-limitations.md
v21.1/known-limitations.md
v21.2/known-limitations.md

After some discussion, we decided that this limitation was too broad to
be helpful for developers who may be looking for different things.

Revert HTTP(s) known limitation

---

v21.2/migrate-from-csv.md

Update to v21.2 docs to add link to userfile docs on migrate CSV (per contributor PR #11671)

Userfile link to v21.2 migrate doc

---

v1.0/rename-index.md
v1.1/rename-index.md
v19.1/rename-index.md
v19.2/rename-index.md
v2.0/rename-index.md
v2.1/rename-index.md
v20.1/rename-index.md
v20.2/rename-index.md
v21.1/rename-index.md
v21.2/rename-index.md

IF EXISTS mistakenly referred to columns instead of indexes.

Fix typo in rename-index.md files

---

v21.2/create-changefeed.md
v21.2/stream-data-out-of-cockroachdb-using-changefeeds.md
v21.2/use-cloud-storage-for-bulk-operations.md

Closes #11068 
Removed the experimental tag and warning from cloud storage URIs and examples in the 21.2 cdc docs. Updated the information on the Cloud storage bulk operations page.

21.2 cdc docs remove experimental from cloud

---

_includes/v21.2/misc/session-vars.html

- Make the header row look like a header.
- Use HTML code markup instead of MD code markup.

Fix markup in session var table.

---

_config_base.yml
_includes/v20.2/orchestration/kubernetes-stop-cluster.md
_includes/v20.2/orchestration/start-cockroachdb-operator-secure.md
_includes/v21.1/orchestration/kubernetes-stop-cluster.md
_includes/v21.1/orchestration/start-cockroachdb-operator-secure.md
_includes/v21.2/orchestration/kubernetes-stop-cluster.md
_includes/v21.2/orchestration/start-cockroachdb-operator-secure.md

> **NOTE**: This should _**NOT**_ be merged until _after_ we cut the new release. If you'd like to test out the steps, you can swap `v2.2.0` for `v2.2.0-beta.2` which is currently on master.
We've made a few changes for the v2.2.0 release of the public operator including the location of the pre-generated manifests. Both the CRD and the operator yaml files now live in the _install_ directory on master.
This PR updates the version to v2.2.0 and updates the docs to point to the new locations.

Update references for operator v2.2.0

---

v21.1/take-full-and-incremental-backups.md
v21.2/take-full-and-incremental-backups.md

Closes #11997 
Corrected the sentence prior to the incremental backup to specific destination example (v21.1 & 21.2) that referred to the old syntax (present in 20.2 and earlier). 
Also added a sentence to clarify that incr backup statement to subdir will create a full backup in the main destination if there is not one already.

Corrected sentence before incremental backup to specified destination

---

v21.2/backup.md

Closes #11391 
Added an example and details on usage of the `schema.*` syntax using a wildcard to back up all tables in a schema.

Add example section on schema.* syntax to back up all tables in schema

---

v21.1/configure-logs.md
v21.2/configure-logs.md

Fixed an open anchor link that was causing parameter names to render incorrectly.

fix anchor link

---

v21.2/bulk-delete-data.md

Fixes https://github.com/cockroachdb/docs/issues/11028.
Will add reference to `ON UPDATE` expression docs after https://github.com/cockroachdb/docs/pull/12035 is merged.

Added example ON UPDATE TTL script

---

_includes/v21.2/backups/no-multiregion-table-backups.md
_includes/v21.2/known-limitations/rbr-restore-no-support.md
_includes/v21.2/known-limitations/restore-multiregion-match.md
_includes/v21.2/known-limitations/restore-tables-non-multi-reg.md
v21.2/import-into.md
v21.2/import.md
v21.2/known-limitations.md
v21.2/restore.md
v21.2/set-locality.md

Closes #10937 Draft of features for `RESTORE` & `IMPORT INTO` 21.2 multi-region features: 
`RESTORE` doc changes:
- Added section to the `RESTORE` page on restoring with the different table localities and their nuances. The RBT & RBR ordering/matching limitations are outlined here and on the known limitations page for 21.2. (Closes #11283)
- Added a bullet on the default primary region setting (Closes #11373 )
- Note on `SET LOCALITY` page
- Added the `skip-localities-check` option to the option table and this section (Closes #11278)
`IMPORT INTO` doc changes:
- Removed the section on this from the known limitation page (Closes #11919 )
- Removed the consideration bullet and added that RBR in import into is now available
- Added a bullet that import into now supports in computed columns …

`RESTORE` and `IMPORT INTO` multi-region functionality docs

---

v21.1/explain-analyze.md
v21.2/explain-analyze.md

Fixes #10828
- Update EXPLAIN ANALYZE page with new 'regions' row in the output,
which lists the regions where the nodes that participated in the query
live.

Update EXPLAIN ANALYZE with moar multiregion info

---

_includes/v21.2/misc/debug-subcommands.md
_includes/v21.2/sidebar-data-reference.json
v21.2/cockroach-commands.md
v21.2/cockroach-debug-job-trace.md

Closes #10943 
Added docs for the cockroach debug job-trace command:
- cli reference page (check on flags)
- added to cockroach commands page

Docs for cockroach debug job-trace

---

v20.2/show-backup.md
v21.1/show-backup.md
v21.2/show-backup.md

Closes #11277 #11287 #11619 #11464 
Added to 21.2 docs:
- `backup_type` column to each of the outputs in the example & in the response table
- `debug_ids` option to the table and an example to show the response format
- Moved around the `SHOW BACKUP` and `SHOW BACKUPS IN` examples + added sentence to clarify how the user should treat top-level backup collection directories.
- Added the `as_json` option to the options table.

New column and option added to SHOW BACKUP docs

---

_includes/sidebar-releases.json

Made a tweak that ensures v20.2.18 loads as the "latest" v20.2 version in the side nav.

make v20.2.18 the latest v20.2 release (new branch)

---

_includes/v21.2/misc/session-vars.html

Fixes https://github.com/cockroachdb/docs/issues/11363.
Fixes https://github.com/cockroachdb/docs/issues/11416.

lock_timeout, backslash_quote session variables

---

_includes/v21.2/sidebar-data-reference.json
_includes/v21.2/sql/generated/diagrams/alter_default_privileges.html
_includes/v21.2/sql/generated/diagrams/show_default_privileges.html
v21.2/alter-default-privileges.md
v21.2/authorization.md
v21.2/show-default-privileges.md
v21.2/sql-statements.md

Fixes https://github.com/cockroachdb/docs/issues/11420.
Fixes https://github.com/cockroachdb/docs/issues/11419.
Fixes https://github.com/cockroachdb/docs/issues/11442.
Fixes https://github.com/cockroachdb/docs/issues/11421.
Fixes https://github.com/cockroachdb/docs/issues/11449.
Fixes https://github.com/cockroachdb/docs/issues/11378.
Fixes https://github.com/cockroachdb/docs/issues/11397.
Fixes https://github.com/cockroachdb/docs/issues/11403.

SHOW DEFAULT PRIVILEGES/ALTER DEFAULT PRIVILEGES

---

v21.2/alter-role.md
v21.2/authentication.md
v21.2/authorization.md
v21.2/create-role.md
v21.2/drop-role.md
v21.2/performance-best-practices-overview.md

Fixes https://github.com/cockroachdb/docs/issues/11470.
This PR documents some performance best practices for `ROLE` operations, following the addition of hashed password caching for authentication.
(IMO, we don't need to document the specifics of hashed password caching, but LMK if you disagree.)

Added performance best practices for ROLE operations

---

cockroachcloud/cloud-api.md

Do we need a link for a location to file bugs?
Do we need a link to request an invite?

Add alert to Cloud API quickstart about it being experimental

---

v20.1/upgrade-cockroach-version.md
v20.2/upgrade-cockroach-version.md
v21.1/upgrade-cockroach-version.md
v21.2/upgrade-cockroach-version.md

Fixes #12138.
- Updated the v21.2 self-hosted upgrade doc:
- Added (tentative) list of features that require upgrade finalization
- Tried to clarify the wording of the version requirements in Step 1.
- Also corrected some earlier upgrade docs that were naming incorrect versions.

update v21.2 self-hosted upgrade doc; fix earlier upgrade docs

---

v21.1/operate-cockroachdb-kubernetes.md
v21.2/scale-cockroachdb-kubernetes.md

Updated two instances of the K8s operator.yaml manifest link to the correct path.
The paths in `start-cockroachdb-operator-secure.md` (v21.1 and v21.2) are also incorrect, but should be fixed in #12198.

fix operator.yaml links

---

_config_base.yml
_includes/v21.1/orchestration/start-cockroachdb-operator-secure.md
_includes/v21.2/orchestration/start-cockroachdb-operator-secure.md

With the next release of the public operator, we've moved away from using the `default` namespace. This has been a requested feature and is generally a best practice.
The new version (yet to be released) will use `cockroach-operator-system` and support reconciliation of resources in
all namespaces. Namespaces can be limited by setting the `WATCH_NAMESPACES` environment variable for the manager deployment.

Document the change in the default namespace

---

_includes/v20.2/known-limitations/old-multi-col-stats.md
_includes/v20.2/known-limitations/single-col-stats-deletion.md
_includes/v21.1/known-limitations/old-multi-col-stats.md
_includes/v21.1/known-limitations/single-col-stats-deletion.md
_includes/v21.2/known-limitations/old-multi-col-stats.md
_includes/v21.2/known-limitations/single-col-stats-deletion.md
v20.2/cost-based-optimizer.md
v20.2/known-limitations.md
v21.1/cost-based-optimizer.md
v21.1/known-limitations.md
v21.2/cost-based-optimizer.md
v21.2/known-limitations.md

Closes #12173 
Added known limitation to main limitation page and optimizer page: 
* old multi-column statistics not being deleted on column deletion from multi-col index
* single-column statistics not being deleted causing performance issues

Known limitation for optimizer deletion of multi-col/single col stale stats

---

_includes/v20.2/orchestration/start-cockroachdb-operator-secure.md

Replaced the liquid tag with a hardcoded version path to the Operate CockroachDB on Kubernetes doc.
cc @lnhsingh - This is unfortunately pointing to v21.1 from v20.2, for reasons that have to do with the Kubernetes Operator updates leading to changes in docs content + structure that became version-specific. I'm going to investigate the possibility of decoupling the K8s docs from CRDB versioning. In the meantime, this should be the only instance of the docs versions mismatching. Let me know if you think I should handle this differently.

hardcode link to Operate CockroachDB on K8s in v20.2

---

_includes/v21.2/sql/expression-indexes-cannot-reference-computed-columns.md
v21.2/expression-indexes.md
v21.2/known-limitations.md

Expression indexes can't reference computed cols

---

v21.1/create-changefeed.md
v21.2/create-changefeed.md

Closes #12248 
As a result of new anchor links in the Kafka Sink Config the bullet points are messed up. This PR fixes that with the correct spacing between the links.

Anchor link spacing in Kafka Config section

---

v21.1/build-a-nodejs-app-with-cockroachdb-sequelize.md

The first part of the value for "database" actually needs to be the cluster's tenant name (which is the cluster name plus a short ID) instead of just the cluster name. The user can easily get all of the relevant values from the "Connection parameters" tab.

Fix database value in Sequelize Serverless

---

_includes/sidebar-data-v21.1.json
_includes/sidebar-data-v21.2.json
_includes/v21.1/misc/mitigate-contention-note.md
_includes/v21.2/misc/mitigate-contention-note.md
v21.1/transactions.md
v21.2/transactions.md

Also removed excessive callout markup.
TOC title matches page title.

Remove dup notes and add headings.

---

v21.1/import-into.md
v21.2/import-into.md

Closes #12021 
Added docs for the `detached` option on the `IMPORT INTO` pages, this was missed originally. Included in 21.1 + 21.2.

Added the detached option info to `IMPORT INTO` pages

---

v21.2/sql-feature-support.md

Fixes https://github.com/cockroachdb/docs/issues/12148.
I've gone through [PostgreSQL Compatibility](https://www.cockroachlabs.com/docs/v21.2/postgresql-compatibility.html) and [SQL Feature Support](https://www.cockroachlabs.com/docs/v21.2/sql-feature-support.html), and I believe this PR finishes updating our SQL Feature Support for 21.2, following https://github.com/cockroachdb/docs/pull/12211. 
LMK if you disagree though. Happy to make edits/additions!

21.2 SQL Feature Support (SQL XP)

---

v21.2/upgrade-cockroach-version.md

Updating 1) backward-incompatible changes and 2) upgrade finalization features to reflect the v21.2 release note verbiage in https://github.com/cockroachdb/docs/pull/12225

Upgrade docs v21.2 enhancements

---

_includes/sidebar-data-cockroachcloud.json
cockroachcloud/frequently-asked-questions.md
cockroachcloud/upgrade-policy.md
cockroachcloud/upgrade-to-v21.1.md
cockroachcloud/upgrade-to-v21.2.md
v21.2/connection-pooling.md

Fixes #12140.
- Added v21.2 upgrade doc for CockroachDB Cloud, with a tentative list of "Respect temporary limitations" features
- Verified the upgrade flow matches the steps listed [here](https://cockroachlabs.atlassian.net/browse/CC-5082)
- Added clearer "major releases are opt-in" verbiage at the top
- Did some cleanup and reorganization of the steps from previous upgrade docs (in particular, moved "roll back" up to the section about monitoring the upgrade, since this occurs prior to upgrade finalization)
- Also fixed an incorrect version number in the v21.1 upgrade doc
Also updated the Upgrade Policy and FAQ docs as part of this PR.
cc @jseldess

add v21.2 upgrade doc for cloud

---

cockroachcloud/frequently-asked-questions.md

Added an entry defining CockroachDB Dedicated to the FAQ, and changed ## Cluster basics --> ## General to align with the Serverless FAQs.
Closes https://cockroachlabs.atlassian.net/browse/CC-5130

CC FAQ Dedicated definition

---

cockroachcloud/authentication.md

Following our style guidance on inclusive language: https://github.com/cockroachdb/docs/wiki/Style-Guide#avoid-unnecessarily-gendered-language.
Fixes #10546

Change man in the middle to machine in the middle

---

_data/advisories.yml
advisories/a72839.md
releases/v21.2.0.md

Technical advisory notes relating to [#72839](https://github.com/cockroachdb/cockroach/issues/72839).
Backups fail during upgrade process v21.2 / v21.1

Tech advisory notes: Backups fail during upgrade process a72839

---

_data/advisories.yml

Quick fix to the versions in the advisories table to make it clearer that v21.2.0 is the affected version

Update to version on table to make clearer

---

v21.2/cockroach-debug-job-trace.md

Closes #12329 
Clarified that `cockroach debug job-trace` works for imports and backups only — traceable jobs.

Clarified that job-trace is for b/u & import only

---

v21.2/follower-reads.md

Specifically, this change notes that:
- You can use `ALTER ROLE` to set the variable for all users in a role
- You can also use the alternate SQL syntax `SET SESSION CHARACTERISTICS`
Fixes cockroachdb/docs#10418
See also:
- cockroachdb/docs#11888

Add docs on FR session var wrt ALTER ROLE etc

---

_includes/v21.1/orchestration/operator-check-namespace.md
_includes/v21.1/orchestration/start-cockroachdb-operator-secure.md
_includes/v21.2/orchestration/operator-check-namespace.md
_includes/v21.2/orchestration/start-cockroachdb-operator-secure.md
v21.1/create-security-certificates-openssl.md
v21.1/operate-cockroachdb-kubernetes.md
v21.2/configure-cockroachdb-kubernetes.md
v21.2/create-security-certificates-openssl.md
v21.2/monitor-cockroachdb-kubernetes.md
v21.2/scale-cockroachdb-kubernetes.md
v21.2/schedule-cockroachdb-kubernetes.md
v21.2/secure-cockroachdb-kubernetes.md
v21.2/upgrade-cockroachdb-kubernetes.md

This supersedes #11939.
- Add steps for securing K8s Operator webhooks (adapted from @muto)
- Small formatting correction on our existing OpenSSL doc

K8s Operator webhooks docs

---

_includes/cockroachcloud/sql-connection-string-free.md
_includes/cockroachcloud/sql-connection-string.md

Connection docs were not previously using cluster name, tenant IDs, and cluster IDs correctly. This PR updates the language temporarily,[ until tenant IDs get added to cluster names and simplify this process.](https://cockroachlabs.atlassian.net/browse/CC-5285)
Examples to illustrate correct meanings:
`cluster-name`=`funny-skunk`
`cluster-id`=`12a3bcde-4fa5-6789-1234-56bc7890d123`
(Serverless) `tenant-id`=`123`
(Dedicated) `short-id`=`6mc`
To download the CA cert, you need the cluster ID. To use the SQL connection string, you need the cluster name and tenant or short ID. Dedicated certs are saved using cluster names and Serverless certs are just saved as `root.crt`.
Closes https://cockroachlabs.atlassian.net/browse/CC-5363

Clarify cluster name, tenant id, and cluster id

---

_includes/sidebar-releases.json

"Technical Advisories" in the sidenav isn’t highlighted when viewing some more recent TAs. This PR fixes that.

DOC-1859: Highlight sidenav for newer TAs

---

v21.1/show-backup.md
v21.2/show-backup.md

Closes #12278 
Expanded documentation on the `as_json` option, also added this to v21.1 docs on the SHOW BACKUP page

Example on `as_json` added to `SHOW BACKUP` docs & 21.1

---

_includes/v21.1/known-limitations/cdc.md
_includes/v21.2/known-limitations/cdc.md
v21.1/stream-data-out-of-cockroachdb-using-changefeeds.md
v21.2/stream-data-out-of-cockroachdb-using-changefeeds.md

Closes [DOC-1112](https://cockroachlabs.atlassian.net/browse/DOC-1112)
Before, cdc known limitations did not have tracking GH issues for the limitations — with the help of @amruss we have updated these with relevant issues. Also moved items that are general considerations into their own section, which helps to define the difference between limitation & more general considerations/guidelines when using changefeeds.

Updates to known limitations for cdc

---

cockroachcloud/serverless-faqs.md

Fixes DOC-2092 
Added a note to the Serverless FAQ page that mentions the error that users will receive if they attempt to run a bulk operation to cloud storage without having entered billing info first. This had come up as a question multiple times — hope is that this will add a little more discoverability while changing the actual error message currently has a few more complexities around it.

Note added to Serverless FAQs re the error on cloud storage/free tier

---

v20.2/restore.md
v21.1/restore.md
v21.2/restore.md

Closes #11865 
Remnant left from maybe the synopsis diagram, but update `kv_options` to `restore_options_list` as per the diagram. Also updated the sentence that introduces the options to avoid any confusion.

Update to restore options sentence

---

cockroachcloud/backups-page.md

Fixes DOC-1875
The CockroachCloud Restore data page currently notes that the **Restore to** field will create a new table, but it's actually a database, which makes sense from the text above the note.

DOC-1875: Corrected typo on restore cc page

---

_includes/sidebar-data-v21.1.json
_includes/sidebar-data-v21.2.json
v21.1/local-testing.md
v21.2/local-testing.md

Fixes https://github.com/cockroachdb/docs/issues/10991.
This doc is just the first iteration of an app-testing docs page for developer users. This first iteration can just focus on local unit testing. We can further break this page up into sections for unit testing, integration testing, and automation (see https://github.com/cockroachdb/docs/issues/12077 and https://github.com/cockroachdb/docs/issues/10800).
I initially started working on this to resolve https://github.com/cockroachdb/docs/issues/10991, as it relates to https://cockroachlabs.atlassian.net/browse/CRDB-2459. We don't have full TestContainer support yet (AFAIK), so I just added some extra tips that may/may not be relevant to people reading this page (happy to remove those).
Some open questions:
- Do we really want to …

Local testing best practices

---

v20.2/use-a-local-file-server-for-bulk-operations.md
v21.1/use-a-local-file-server-for-bulk-operations.md
v21.2/use-a-local-file-server-for-bulk-operations.md

Closes #10621
As per the issue and discussion with Michael some time ago, removing the Caddy section from the local file server section.

Removed Caddy section from local file server docs

---

v21.1/backup.md
v21.1/take-full-and-incremental-backups.md
v21.2/backup.md
v21.2/take-full-and-incremental-backups.md

Fixes [DOC-2153](https://cockroachlabs.atlassian.net/browse/DOC-2153) 
Added a couple of sentence to the `BACKUP` and Take Full and Incremental Backups pages around Enterprise license keys being exported through a backup. 
Rearranged the top of both pages to avoid a long stack of notes losing emphasis — these are now in a Considerations section. 
Included the `BACKUP TO` deprecation notice also next to the examples to make this more obvious

Added detail on Enterprise license export through a backup

---

v21.1/schema-design-indexes.md
v21.2/schema-design-indexes.md

Added recommendation to limit secondary index operations during off-peak hours

DOC-1511: Added off-peak recommendation for secondary indexes

---

_data/releases.yml

On the full release list, only the latest stable release
should have the "latest" tag.

Remove "latest" tag from 21.1.12

---

cockroachcloud/connect-to-your-cluster.md
cockroachcloud/create-your-cluster.md
cockroachcloud/network-authorization.md
cockroachcloud/security-overview.md

https://cockroachlabs.atlassian.net/browse/DOC-1947
On **Create a Cluster** page: mentioned that you have to actually establish the connection after enabling it during the cluster creation project, linked to instructions
On **Network Authorization** page: replaced the summarized instructions with links to detailed create & connection doc steps, added note about gke custom routes
On **Security Overview** page: linked to detailed instructions

Clarify VPC peering instructions

---

_includes/v21.1/sidebar-data-reference.json
_includes/v21.2/sidebar-data/reference.json
cockroachcloud/quickstart-trial-cluster.md
cockroachcloud/quickstart.md

- Link to local cluster option from serverless quickstart
- Combine before you begin with step 1 in dedicated quickstart

Align beginning of quickstarts

---

_includes/v21.2/sidebar-data/deploy.json

Previously, Deploy > Choose a Deployment Strategy > CockroachDB Cloud
> CockroachDB Dedicated > Create a CockroachDB Dedicated
Cluster opened the Serverless cluster creation page. Now it opens
the correct page.

Fix create dedicated cluster link in Deploy sidenav

---

_includes/cockroachcloud/restore-examples.md
_includes/cockroachcloud/userfile-examples/backup-userfile.md
cockroachcloud/backups-page.md
v21.1/backup.md
v21.1/restore.md
v21.1/take-and-restore-encrypted-backups.md
v21.1/take-backups-with-revision-history-and-restore-from-a-point-in-time.md
v21.1/take-full-and-incremental-backups.md
v21.2/backup.md
v21.2/restore.md
v21.2/take-and-restore-encrypted-backups.md
v21.2/take-backups-with-revision-history-and-restore-from-a-point-in-time.md
v21.2/take-full-and-incremental-backups.md

Fixes [DOC-2116](https://cockroachlabs.atlassian.net/browse/DOC-2116)
Syntax for RESTORE across the bulk docs needed updating to the `RESTORE FROM 'x' in 'y'` rather than the older `RESTORE FROM 'y/x'` syntax.
Plus a couple of other opportunistic edits (BACKUP syntax in places was not up-to-date, removed stacked notes at top of RESTORE doc into considerations, typo fix)

Update to RESTORE syntax in 21.1 / 21.2

---

_includes/v21.2/known-limitations/rbr-restore-no-support.md
_includes/v21.2/known-limitations/restore-multiregion-match.md
v21.2/backup.md
v21.2/known-limitations.md
v21.2/restore.md
v21.2/set-locality.md

Fixes [DOC-1872](https://cockroachlabs.atlassian.net/browse/DOC-1872), [DOC-1709](https://cockroachlabs.atlassian.net/browse/DOC-1709), [DOC-1158](https://cockroachlabs.atlassian.net/browse/DOC-1158), [DOC-723](https://cockroachlabs.atlassian.net/browse/DOC-723)
Removes limitations from 21.2: 
* backup can now backup up tables
* can now restore RBR
Also made adjustments to the Restore multi-region section to reflect these changes.

Updates to Multi-region RESTORE/BACKUP with updates in 21.2.3

---

releases/cockroachcloud-01102022.md

The notes are dated based on the date on which email
communication goes out. But since cloud isn't versioned,
the date isn't meaningful beyond that. Since the
"Latest Release Notes" page is the only place where
users can find out what version of crdb the cloud offerings
are running, it makes sense to keep the versions up to date.
I know there's broader work happening around the cloud release
not process that might resolve this issue. As part of that,
we should think of a way to communicate the current crdb
version for cloud that's release note date-agnostic.

Update the crdb version on the "latest" cloud release notes

---

v21.1/import-into.md
v21.1/import-performance-best-practices.md
v21.1/import.md
v21.2/import-into.md
v21.2/import-performance-best-practices.md
v21.2/import.md

Fixes [DOC-1301](https://cockroachlabs.atlassian.net/browse/DOC-1301)
Added a section describing the trade-off between imports into schema with secondary indexes. 
Also added links from the main import pages to the best practices page. Fixes [DOC-1013](https://cockroachlabs.atlassian.net/browse/DOC-1013)

Added guidance on trade-off between index & import

---

_includes/cockroachcloud/experimental-warning.md
_includes/common/experimental-warning.md
_includes/sidebar-data-cockroachcloud.json
_includes/v21.2/misc/experimental-warning.md
_includes/v21.2/sidebar-data/manage.json
_includes/v21.2/sidebar-data/reference.json
cockroachcloud/cloud-api.md
cockroachcloud/console-access-management.md
v21.2/changefeed-for.md
v21.2/cockroach-demo.md
v21.2/cockroach-sqlfmt.md
v21.2/experimental-audit.md
v21.2/hash-sharded-indexes.md
v21.2/logging-use-cases.md
v21.2/set-locality.md
v21.2/show-range-for-row.md
v21.2/sql-audit-logging.md

Fixes CC-5426.
This PR:
- Breaks out the service account and API key creation docs into the main managing accounts doc.
- Adds the Cloud API reference and quickstart to the sidebar navigation.
- Adds a general purpose warning that can be used across the docs for experimental features.

Refactor Cloud API docs with warnings.

---

v21.2/connect-to-the-database.md

Fixes https://github.com/cockroachdb/docs/issues/12723.
This PR adds a "Self-Hosted" tab to the [Connect to a CockroachDB Cluster](https://www.cockroachlabs.com/docs/stable/connect-to-the-database.html) page.

Added Self-Hosted to connection reference

---

v21.1/migrate-to-multiregion-sql.md
v21.2/migrate-to-multiregion-sql.md

Fixes DOC-2357
Geo-partitioned leaseholders were incorrectly mapped to Regional By
Table tables with Region survival goals in our 'Migrate to Multi-region
SQL' docs.
They are now mapped to Regional By Row tables w/ Region survival goals.
Applied to both v21.1 and v21.2 docs.

Update multiregion migration instructions

---

_includes/v21.1/sql/replication-zone-patterns-to-multiregion-sql-mapping.md
_includes/v21.2/sql/replication-zone-patterns-to-multiregion-sql-mapping.md
v21.1/migrate-to-multiregion-sql.md
v21.2/migrate-to-multiregion-sql.md

Fixes DOC-2357 (all the way this time)
- Update to use the correct mapping from zone configs to multiregion SQL
statements (again)
- Except this time, move the mapping into an include file, and use the
include file in both places the mapping is referenced

Update mapping from zcfgs to multiregion SQL

---

_config_base.yml
_data/releases.yml
_includes/sidebar-releases.json
releases/v22.1.0-alpha.1.md

Fixes [DOC-1904](https://cockroachlabs.atlassian.net/browse/DOC-1904)
Release notes for v22.1.0-alpha.1
Note added links with "stable" since there isn't a v22.1 doc set yet. We will want to update that when the dev version of the docs is live.

Release notes for v22.1.0-alpha.1

---

v21.1/set-locality.md

I've testing the UPDATE query and when using double quotes, the command returns the following error:
```sql
ERROR: column "eu-west" does not exist
```
Just changing double quotes by single does the fix.

Syntax typo in UPDATE query example

---

v21.2/connect-to-the-database.md

Our current connection docs contain a "set literal," which is not
supported in JavaScript and causes a syntax error. A solution is
to pass the connection string directly into the client without
wrapping it in a JavaScript object.

Fix syntax error for node-postgres connection docs

---

v21.1/migrate-to-multiregion-sql.md
v21.2/migrate-to-multiregion-sql.md

Fixes DOC-2357
- Fixed the (hopefully) last incorrect mapping from the old skool
geo-partitioned leaseholder pattern to the new REGIONAL BY ROW table
locality + ZONE survival goal on the 'Migrate to Multi-region SQL'
page.
- Previously, we were incorrectly referring to a mapping from
geo-partitioned leaseholders to REGIONAL BY TABLE locality + ZONE
survival.

Add (last?) correct mapping of geo* pattern to RBR

---

_redirects

Added a redirect from the now removed stream data out of cockroachdb using changefeeds page for v21.2.

Added redirect from removed changefeed file

---

v21.2/cockroach-start.md

The statement should say that the nodes can reach each other on public addresses across cloud providers.

MInor correction for multi-region documentation

---

v21.2/install-cockroachdb-linux.md
v21.2/install-cockroachdb-mac.md

Building from source archives has been broken since v21.2.0, and from
v22.1.0 onward with the Bazel migration there won't be source archives
at all. Cloning the upstream repo and building from the clone is the
most correct and future-proof way to build from source.

Don't reference source archives for building v21.2

---

v21.1/backup.md
v21.2/backup.md

Fixes [DOC-2386](https://cockroachlabs.atlassian.net/browse/DOC-2386)
This is a small clarification to the current note on the backup page that specifies that the presence of the `BACKUP CHECKPOINT` file in the backup destination means that the job was not successful. That is not actually the case, as this file is not necessarily cleared up. 
Adjusted this note to the `BACKUP MANIFEST` file's presence indicating that the job was successful.

Correction to BACKUP CHECKPOINT note on BACKUP

---

v20.2/sql-name-resolution.md
v21.1/sql-name-resolution.md
v21.2/sql-name-resolution.md

Fixes DOC-547
- Named resolution by search path will try to resolve `pg_extension` prior to `public` schema.

DOC-547: Added note about name resolution by search path

---

cockroachcloud/stream-changefeed-to-snowflake-aws.md

Fixes [DOC-2129](https://cockroachlabs.atlassian.net/browse/DOC-2129)
Updates to tutorial:
- Relevant additions to Snowflake doc links
- GCS is now covered in auto-ingest by snowflake (updated note)
- Removed `resolved` option from the create changefeed statement to avoid creation of too many objects in the bucket.
- (the experimental was removed from the s3 URI in another PR, which is mentioned in this ticket)

Minor updates to Snowflake changefeed tutorial

---

_redirects

Fixes https://cockroachlabs.atlassian.net/browse/DOC-2310. 
(*Marketing page is linking to the now-removed Hello World Example Apps overview on stable*)
Follow-up on https://github.com/cockroachdb/docs/pull/12981#issuecomment-1033778576.

Added redirect from removed Hello World Example Apps page

---

releases/v22.1.0-alpha.1.md

Link to GH tag instead of downloading a source archive.
Source archives aren't being provided as of 22.1.

Change 22.1 alpha source download link

---

v21.2/import.md

Fixes [DOC-1870](https://cockroachlabs.atlassian.net/browse/DOC-1870)
"Release note (enterprise change): Fixed a limitation of IMPORT for tables using user-defined types whereby any change to the set of tables or views which reference the type or any changes to privileges on the type during the IMPORT would lead to failure. Now new references to the type or GRANT or REVOKE operations performed while the IMPORT is ongoing will not cause failure."

Removed line from `IMPORT` page on UDT limitation

---

v21.2/changefeed-examples.md

Fixes [DOC-2503](https://cockroachlabs.atlassian.net/browse/DOC-2503)
Customer found the new layout of the changefeed examples page confusing. There was a feeling that the Cloud storage examples were hard to find. 
Adjusted the layout to make Enterprise changefeeds more prominent in the filter placements. Added a sink breakdown to start with links to the respective sections and added link out to the Changefeed Sinks page to make clear that information on forming sink URIs can be found there.

Clarify examples for enterprise/core changefeeds on new Changefeed Example page

---

v21.2/deploy-cockroachdb-on-aws-insecure.md
v21.2/deploy-cockroachdb-on-aws.md
v21.2/recommended-production-settings.md

Changing our instance type recs from c5 to m5 based
on what Cloud uses and internal consensus.

DOC-30: Update AWS instance type recommendations

---

_redirects
v21.2/node-shutdown.md

- Minor corrections and wording tweaks to Node Shutdown doc.
- Adjusted the server-side redirect to use stable and not v21.2.

(retrying) minor tweaks and corrections to node shutdown doc

---

_includes/cockroachcloud/prefer-sso.md
cockroachcloud/authentication.md
cockroachcloud/console-access-management.md
cockroachcloud/create-a-serverless-cluster.md
cockroachcloud/create-your-cluster.md

Add a note that we support GitHub SSO and will support other options soon, and that SSO is to be preferred for security.

DOC-2793: Add SSO note for Cloud Console login

---

_includes/cockroachcloud/prefer-sso.md
cockroachcloud/authentication.md
cockroachcloud/console-access-management.md
cockroachcloud/create-a-serverless-cluster.md
cockroachcloud/create-your-cluster.md

This reverts commit fb03219b41600155d0f66e42b4d182177bb96be8.

Add back "DOC-2793: Add SSO note for Cloud Console login"

---

.github/workflows/changed_files.yml

When a new release note file is pushed in the _includes/releases/vXX.Y/vXX.Y.Z.md, this PR should now display the changes in the associated major version file.

Added logic to render main release note pages in PRs

---

.github/workflows/changed_files.yml

Fixes DOC-2868:
- First-level references to includes will display a link to the pages on which that modified include is referenced

DOC-2868: Add first-level references to modified includes in Changed Files bot

---

_config_base.yml
v21.1/deploy-cockroachdb-with-kubernetes-openshift.md
v21.2/deploy-cockroachdb-with-kubernetes-openshift.md
v22.1/deploy-cockroachdb-with-kubernetes-openshift.md

Updating the operator version to v2.5.1 (for all the links to the
manifests, etc.).
I've also updated a dead link for the OpenShift instructions.
Fixes https://github.com/cockroachdb/cockroach-operator/issues/823

[operator]: Bump referenced version to v2.5.1

---

cockroachcloud/frequently-asked-questions.md

Users often want to know what regions CockroachDB is available in. Add an FAQ telling them how to find this information. This commit intentionally does not list out the specific clouds and regions because we don't want to worry about updating the docs each time a new region is added.

Cloud and region availability FAQ

---

_includes/v21.1/misc/tooling.md
_includes/v21.2/misc/tooling.md
_includes/v22.1/misc/tooling.md
v21.1/build-a-rust-app-with-cockroachdb.md
v21.1/community-tooling.md
v21.1/example-apps.md
v21.1/install-client-drivers.md
v21.2/build-a-rust-app-with-cockroachdb.md
v21.2/community-tooling.md
v21.2/example-apps.md
v21.2/install-client-drivers.md
v22.1/build-a-rust-app-with-cockroachdb.md
v22.1/community-tooling.md
v22.1/example-apps.md
v22.1/install-client-drivers.md

Fixes https://cockroachlabs.atlassian.net/browse/DOC-2894.
See https://github.com/cockroachdb/example-app-rust-postgres.
After this is merged, I'll remove the `rust` directory from [`community-tooling-samples`](https://github.com/cockroachdb/community-tooling-samples).

Moved Rust into beta support

---

v21.1/drop-region.md
v21.1/when-to-use-zone-vs-region-survival-goals.md
v21.2/drop-region.md
v21.2/when-to-use-zone-vs-region-survival-goals.md
v22.1/drop-region.md
v22.1/when-to-use-zone-vs-region-survival-goals.md

Fixes DOC-1088
- `REGION` survival plans requires at least 3 regions configured on the DB

DOC-1088: Highlight information about `REGION` survival plans

---

cockroachcloud/serverless-faqs.md

The CockroachDB Cloud console no longer consumes request units, so users should no longer see request units consumed if they're not using their DB.

Remove FAQ about RUs being consumed in background

---

v22.1/export.md

Fixes [DOC-1146](https://cockroachlabs.atlassian.net/browse/DOC-1146) [DOC-2138](https://cockroachlabs.atlassian.net/browse/DOC-2138) [DOC-2276](https://cockroachlabs.atlassian.net/browse/DOC-2276)
Parquet added as an format to the `EXPORT` sql page. Edited page to move from only CSV to more agnostically cover both formats. Format added to option table.

Updates to export page parquet format added

---

_includes/v20.2/orchestration/start-cockroachdb-operator-secure.md
_includes/v21.1/orchestration/start-cockroachdb-operator-secure.md
_includes/v21.2/orchestration/start-cockroachdb-operator-secure.md
_includes/v22.1/orchestration/start-cockroachdb-operator-secure.md
v21.1/deploy-cockroachdb-with-kubernetes-openshift.md
v21.2/deploy-cockroachdb-with-kubernetes-openshift.md
v22.1/deploy-cockroachdb-with-kubernetes-openshift.md

Removed a callout describing a known issue with the version checker job during CRDB installation by the Operator. The known issue has been fixed.

remove version checker job callout

---

_includes/releases/v22.1/v22.1.0-alpha.1.md

I'm documenting this feature and the release note omits the information about the gist that's generated.

Add info about generated gist.

---

v21.1/take-and-restore-encrypted-backups.md
v21.1/take-and-restore-locality-aware-backups.md
v21.1/take-backups-with-revision-history-and-restore-from-a-point-in-time.md
v21.2/take-and-restore-encrypted-backups.md
v21.2/take-and-restore-locality-aware-backups.md
v21.2/take-backups-with-revision-history-and-restore-from-a-point-in-time.md
v22.1/take-and-restore-encrypted-backups.md
v22.1/take-and-restore-locality-aware-backups.md
v22.1/take-backups-with-revision-history-and-restore-from-a-point-in-time.md

Fixes [DOC-3062](https://cockroachlabs.atlassian.net/browse/DOC-3062)
Fix to remove irrelevant sentences from the top of the Manage backup/restore docs that was probably applicable some versions ago.

Removed irrelevant sentences from top of backup/restore docs

---

v21.1/cockroach-debug-zip.md
v21.2/cockroach-debug-zip.md
v22.1/cockroach-debug-zip.md

Addresses DOC-2989
- Added missing `--cpu-profile-duration` flag to General
- Corrected code example for `--exclude-nodes`
- Replaced generic include for Client Connection flags with specific explicit listing based on live output of `cockroach debug zip --help` for all three supported versions. No differences between versions except for additional link present in `--url` flag for two most recent versions. Presenting in alphabetical order to match General.

DOC-2989 update debug zip flags

---

v21.2/cockroach-node.md
v21.2/node-shutdown.md
v22.1/cockroach-node.md
v22.1/node-shutdown.md

Fixes DOC-2211.
Added `--self` flag to `node drain` reference (v22.1 and v21.2).

add --self flag to node drain

---

v21.2/performance-best-practices-overview.md
v21.2/performance-recipes.md
v21.2/sql-tuning-with-explain.md
v22.1/performance-best-practices-overview.md
v22.1/performance-recipes.md
v22.1/sql-tuning-with-explain.md

Stephanie Bodoff (stbof) commented:
These pages were moved to Develop but still had the doc area set to manage. 
It's useful to see the 2nd level headings in recipes.
Jira Issue: DOC-3164

Add 2nd level headings to page TOC. Fix doc area.

---

StyleGuide.md

The style team has decided to include some principles for our style guide. The aim is to provide a framework for our decision process when writing, reviewing, and creating further style guidelines. These follow Cockroach Labs' values.

Add principles to style guide

---

_includes/v21.2/sidebar-data/deploy.json
_includes/v21.2/sidebar-data/manage.json
_includes/v22.1/sidebar-data/deploy.json
_includes/v22.1/sidebar-data/manage.json
v21.2/kubernetes-overview.md
v22.1/kubernetes-overview.md

Fixes DOC-2284.
- Relocated the K8s operational docs to the Manage section of the sidebar.
- Updated the K8s Overview doc to only refer to the deployment methods.

move K8s operational docs to Manage section

---

_config_base.yml

We recently released a new version of the public operator containing a
bugfix that has been coming up in support tickets and Slack (issues with
`cockroachDBVersion` is set and `image` is not).

Bump operator version to v2.5.3

---

_includes/v22.1/misc/session-vars.html
v22.1/date.md
v22.1/interval.md
v22.1/timestamp.md

https://cockroachlabs.atlassian.net/browse/DOC-2593
`datestyle_enabled` and `intervalstyle_enabled` now have no effect because they are always true.
(I just deleted references to those variables, but let me know if there should be a more direct note to say that they are no longer necessary)
There is also no longer any issue with those variables and casting between INTERVALs and STRINGs.

Document non-experimental DateStyle and IntervalStyle session parameters

---

StyleGuide.md

Follow-up on https://cockroachlabs.slack.com/archives/C01NFCXULTX/p1650321116723369.

Removed guidance to place version tags in headers from the style guide

---

.github/workflows/changed_files.yml

Added recursion to Changed Files bot to allow for nested dependency lists.
Circular references and unused references are handled by this with appropriate warning/error messages.

Fixed Changed Files linter for multiple extensions

---

v21.2/set-vars.md
v22.1/set-vars.md

The sql diagram on the 22.1 session vars page is not showing for the `SET SESSION` sql: https://www.cockroachlabs.com/docs/dev/set-vars.html#set-session 
Corrected the URL.

Quick fix to diagram URL

---

v21.1/use-a-local-file-server-for-bulk-operations.md
v21.2/use-a-local-file-server-for-bulk-operations.md
v22.1/use-a-local-file-server-for-bulk-operations.md

Follow-up to #13403 that I missed! Local File Server page also has instances mentioning backup with `http` storage. Updated through to v21.1 per typical docs updated policy.

Removed instances of http storage in local file bulk doc

---

v21.2/cockroach-commands.md
v22.1/cockroach-commands.md

Follow-up on https://github.com/cockroachdb/docs/pull/12260.
Fixes https://cockroachlabs.atlassian.net/browse/DOC-1413.
I don't think the `cockroach convert-url` command merits its own page or an entry in the navbar. I do think users might find it helpful to have it listed in the `cockroach` commands overview page.

Added cockroach convert-url to cockroach commands overview page

---

v21.2/schedule-cockroachdb-kubernetes.md
v22.1/schedule-cockroachdb-kubernetes.md

Fixes DOC-2993.
- Added some docs on the topology spread constraints feature. 
I'm letting the K8s docs do the heavy lifting here. It was difficult to think of an example where these rules would be effectively used, since our default behavior and existing guidance already emphasizes running deployments with an even distribution of pods across failure zones. But if anyone can point out an example that would make sense, I'm happy to add it.

document topology spread constraints

---

_includes/v21.2/orchestration/start-cockroachdb-operator-secure.md
_includes/v22.1/orchestration/start-cockroachdb-operator-secure.md
v21.2/secure-cockroachdb-kubernetes.md
v22.1/secure-cockroachdb-kubernetes.md

Fixes DOC-2467.
- Updated the K8s Operator cert rotation steps to avoid downtime.
- Updated the cert generation snippet to use the Operator's default namespace.

update K8s Operator cert rotation to avoid downtime

---

v21.2/node-shutdown.md

In v21.2 and earlier, a node should always be drained before decommissioning. Updated the v21.2 Node Shutdown guidelines to clarify this.

clarify draining before decommissioning in v21.2

---

v22.1/restore.md

Fixes [DOC-2786](https://cockroachlabs.atlassian.net/browse/DOC-2786)
Added new_db_name option to `RESTORE` sql page options table, an example, and clarified under the "Restore Databases" section.

Rename db on restore option added to docs 22.1

---

v22.1/restore.md

Quick correction to `RESTORE DATABASE` syntax

Correction to typo in `RESTORE` syntax

---

v22.1/backup.md
v22.1/use-cloud-storage-for-bulk-operations.md

Fixes [DOC-3197](https://cockroachlabs.atlassian.net/browse/DOC-3197) [DOC-2761](https://cockroachlabs.atlassian.net/browse/DOC-2761) [DOC-3096](https://cockroachlabs.atlassian.net/browse/DOC-3096) 
This adjusts the privileges listed on the backup page for the updated write-only backups that are the standard behavior with v22.1. 
PR also adds additional section to the Cloud Storage page, so that we can describe upcoming features that we're supporting for cloud storage. Before the 22.1 GA release, intelligent tiering can also be added to this section.
Note: per previous conversations in past PRs, this PR doesn't include how the write-only backups are implemented. This is to avoid going into detail on the file structure of the backup, which changes frequently. Can adjust this as we feel …

Added docs on write-only backups

---

v22.1/show-ranges.md

Addresses: DOC-2514
CRDB Commit: [#75551](https://github.com/cockroachdb/cockroach/pull/75551)
- Updated *Required privileges* section on `SHOW RANGES` reference page to include mention of `ZONECONFIG` priv.
Staging: [show-ranges](https://deploy-preview-13656--cockroachdb-docs.netlify.app/docs/v22.1/show-ranges#required-privileges)

DOC-2514 ZONECONFIG for SHOW RANGES

---

_config_base.yml
v21.2/monitor-cockroachdb-kubernetes.md
v22.1/monitor-cockroachdb-kubernetes.md

Fixes DOC-2994.
- Document K8s logging configuration using the Operator on v21.2 and v22.1.
- Also updated the Operator image version.

configure K8s logging

---

v21.2/cluster-setup-troubleshooting.md
v21.2/node-shutdown.md
v22.1/cluster-setup-troubleshooting.md
v22.1/node-shutdown.md

Fixes DOC-2874.
- Documented an example "stuck ranges" snippet
- Also removed outdated troubleshooting topic on decommissioned nodes being displayed forever in UI.

add stuck ranges snippet and tweak decommission nodes troubleshooting

---

cockroachcloud/troubleshooting-page.md

Users may encounter errors when connecting to Serverless clusters when they have existing certificates in `~/.cockroach-certs`.
Fixes DOC-3377.

Add additional troubleshooting entry for certificate signed by unknown authority errors

---

v22.1/architecture/replication-layer.md

Add docs on replica circuit breakers
Fixes DOC-2584
Fixes DOC-2643
(Related: issue 2495 in the DOC project)
- Add a new section 'Per-replica circuit breakers' to the 'Replication
Layer' page in the architecture docs, which has
- Overview of how the feature works at a (very) high level
- Something about how to configure it (and a note that most shouldn't
need to)
- Notes on a couple limitations of its operation
- Links to the Replication Dashboard and Advanced Debug pages, which
have the circuit breaker observability stuff

Add docs on replica circuit breakers

---

v21.2/monitoring-and-alerting.md
v22.1/common-issues-to-monitor.md
v22.1/monitor-cockroachdb-with-prometheus.md
v22.1/monitoring-and-alerting.md

Addresses: DOC-2123
CRDB: (couldn't find in Jira)
- Added new `Alerting tools` section to `v22.1/monitoring-and-alerting.md`, showcasing new metrics endpoint, including: 
- Accessing the new endpoint, configuring Alertmanager, configuring Prometheus
- Expanded `Events to alert on` to include location of corresponding rules definition, some from old pre-defined `yaml` file, some from this PR.
- Updated code examples to use latest Prometheus | Alertmanager values on `v22.1/monitor-cockroachdb-with-prometheus.md`
- Fixed broken link on `v21.2/monitoring-and-alerting.md`
Please see my comments below in this review -- I had some relevant notes / questions for you. Thank you so much!
[v22.1/monitoring-and-alerting.md](https://deploy-preview-13692--cockroachdb-docs.netlify.app/docs/dev/monitoring …

DOC-2123 add alerting rules endpoint, events

---

_includes/v21.1/sql/insert-vs-upsert.md
_includes/v21.2/sql/insert-vs-upsert.md
_includes/v22.1/sql/insert-vs-upsert.md
netlify/vale/vocab.txt
v21.1/insert.md
v21.1/upsert.md
v21.2/insert.md
v21.2/upsert.md
v22.1/insert.md
v22.1/upsert.md

The behavior of `UPSERT` when a subset of column values is provided is confusing, so I think it deserves some explanation in our docs (see https://github.com/cockroachdb/cockroach/issues/73984). This is my quick attempt to explain it, but I'm hoping that the docs team can take over from here to refine the language and make it as clear as possible. I've include some examples which should help understand the behavior.
I think this should be documented for all past versions that support UPSERT, though I've only included it in 22.1 in this PR.

Explain UPSERT behavior with a subset of columns

---

_config_base.yml
_data/releases.csv
_includes/releases/v22.1/v22.1.0-rc.1.md

Addresses: DOC-1911
- Release notes for `v22.1.0-rc.1`, to be released May 9th, 2022.
[releases/v22.1.html](https://deploy-preview-13823--cockroachdb-docs.netlify.app/docs/releases/v22.1.html#v22-1-0-rc-1)

DOC-1911 v22.1.0-rc.1 release notes

---

CONTRIBUTING.md

- The instructions assume Bash, but ZSH has been the default in macOS for a while, so the instructions as written won't configure your shell correctly by default on macOS.
- The instructions leave you in a halfway state with using Ruby from Homebrew but Gem from the system Ruby. The permission error is a clue that something is wrong, not that you should use sudo.
- I moved installing Git into a separate step to keep all the Ruby / Gem stuff together.

Update instructions to overcome onboarding issues

---

v21.2/cockroach-debug-zip.md
v22.1/cockroach-debug-zip.md

Addresses: DOC-2462
CRDB: [#75239](https://github.com/cockroachdb/cockroach/pull/75239)
- Added entry to `cockroach debug zip` reference page under `Files` to indicate that Replication Reports are now also included in the resulting zip file.
- EDIT: Just noticed [#75794](https://github.com/cockroachdb/cockroach/pull/75794), so performed this also for `v21.2`
[cockroach-debug-zip.html](https://deploy-preview-13827--cockroachdb-docs.netlify.app/docs/v22.1/cockroach-debug-zip#files)

DOC-2462 debug zip incl repl reports

---

_includes/v22.1/backups/advanced-examples-list.md
_includes/v22.1/sidebar-data/reference.json
v22.1/alter-table.md
v22.1/backup.md
v22.1/create-table.md
v22.1/restore.md
v22.1/set-storage-parameter.md
v22.1/take-full-and-incremental-backups.md

Fixes [DOC-3286](https://cockroachlabs.atlassian.net/browse/DOC-3286)
Added docs on new `exclude_data_from_backup` parameter. Included:
- Longer examples on Take Full and Incremental Backups page
- New page for the `SET (storage parameter)` subcommand of `ALTER TABLE`
- Short-form example on `CREATE TABLE`
- Notes/considerations to `BACKUP` & `RESTORE` pages

Docs on exclude_data_from_backup parameter

---

v21.2/change-data-capture-overview.md
v22.1/change-data-capture-overview.md

Fixes [DOC-3306](https://cockroachlabs.atlassian.net/browse/DOC-3306)
Added a key field so when users are on the Stream Data Out of CockroachDB page in v21.1 and earlier the version selector for 21.2+ will take them to the newer stream data section.

Added `key` field to CDC overview docs for version selection

---

_includes/v22.1/metric-names.md
v22.1/cancel-query.md
v22.1/postgresql-compatibility.md

Fixes DOC-2590
- Update the 'Postgres compatibility' page to remove pgwire query
cancellation from the list of unsupported features
- Add `sql.pgwire_cancel.*` metrics to 'Custom Chart Debug Page'

PGwire query cancellation is now supported

---

_includes/cockroachcloud/prefer-sso.md
cockroachcloud/authentication.md
cockroachcloud/cloud-sso.md
cockroachcloud/create-an-account.md

Adds an SSO explainer page with FAQ, and points to it from authentication related pages.
Updates mentions of Github as SSO provider to include Microsoft and Google.
https://cockroachlabs.atlassian.net/jira/software/c/projects/DOC/boards/239?modal=detail&selectedIssue=DOC-2847

Sso updates

---

v21.1/postgresql-compatibility.md
v21.2/postgresql-compatibility.md
v22.1/postgresql-compatibility.md
v22.1/sql-feature-support.md

Fixes DOC-3354
Fixes DOC-3086
- Clarify pgwire version 3.0 compat
- ... in the docs for the following versions: v21.1, v21.2, v22.1 (but
not v20.2 and earlier since they are no longer supported per
https://www.cockroachlabs.com/docs/releases/release-support-policy)
- Hash-sharded indexes supported
- JOINs in table expressions supported
- Default privileges are supported

Update SQL feature and pgcompat docs for v22.1

---

_includes/v22.1/sidebar-data/reference.json
_includes/v22.1/sql/enable-super-region-primary-region-changes.md
_includes/v22.1/sql/enable-super-regions.md
_includes/v22.1/sql/multiregion-example-setup.md
_includes/v22.1/sql/multiregion-movr-add-regions.md
_includes/v22.1/sql/super-region-considerations.md
v22.1/add-region.md
v22.1/add-super-region.md
v22.1/alter-database.md
v22.1/alter-super-region.md
v22.1/demo-low-latency-multi-region-deployment.md
v22.1/drop-region.md
v22.1/drop-super-region.md
v22.1/multiregion-overview.md
v22.1/show-regions.md
v22.1/show-super-regions.md
v22.1/sql-statements.md

Fixes DOC-2581
Fixes DOC-2899
Fixes DOC-3099
Fixes DOC-3110
- Add section on super regions to 'Multiregion Overview' page
- Add SQL reference pages with examples:
- 'ADD SUPER REGION'
- 'DROP SUPER REGION'
- 'ALTER SUPER REGION'
- 'SHOW SUPER REGIONS'
- Add links to the above statements as needed from the 'ALTER DATABASE'
and 'SQL Statements' pages

Add docs on super regions

---

v21.1/take-full-and-incremental-backups.md
v21.2/take-full-and-incremental-backups.md
v22.1/take-full-and-incremental-backups.md

Fixes [DOC-2410](https://cockroachlabs.atlassian.net/browse/DOC-2410)
The error mentioned in the issue is already publicly documented — to provide more visibility have added a link out to the errors page from the incremental backup section v21.1+

Added more detail to GC warning on incremental backups

---

v22.1/connection-pooling.md

Fixes DOC-2877.
Added `connection_wait` guidance to the Connection Pooling doc. It echoes the existing Node Shutdown guidance and links out to that doc for more in-depth considerations.

add `connection_wait` setting to connection pooling doc

---

_includes/v21.2/orchestration/kubernetes-upgrade-cluster-helm.md
_includes/v21.2/orchestration/kubernetes-upgrade-cluster-manual.md
_includes/v22.1/orchestration/kubernetes-upgrade-cluster-helm.md
_includes/v22.1/orchestration/kubernetes-upgrade-cluster-manual.md
_includes/v22.1/sidebar-data/manage.json
cockroachcloud/upgrade-to-v22.1.md
v21.2/upgrade-cockroachdb-kubernetes.md
v22.1/upgrade-cockroach-version.md
v22.1/upgrade-cockroachdb-kubernetes.md

(WIP; not ready to merge)
Fixes DOC-3355.
Fixes DOC 3356.
- Updated the version callouts in the v22.1 upgrade docs (incl. Kubernetes docs), using new liquid variables and conditional url syntax from @nickvigilante 
- Added a provisional list of "upgrade finalization" features. Final verbiage will be taken from the GA release notes.
- Also still need to add an include for "breaking changes" list in the GA release notes.
cc @mikeCRL for visibility.
@trestman do you have availability to review this PR before next Monday, the 24th? It needs to be merged before then, ideally Friday. The PR is a WIP (see above) but the other contents to be included will be coming directly from @mikeCRL, so I think it is safe to review now.

v22.1 upgrade docs

---

_data/advisories.yml
advisories/a81315.md

Addresses: DOC-3443
- Publish TA 81315
Note: staging is live despite build indicating yellow status.
[a81315.md](https://deploy-preview-13911--cockroachdb-docs.netlify.app/docs/advisories/a81315) | [advisories](https://deploy-preview-13911--cockroachdb-docs.netlify.app/docs/advisories/index.html)

DOC-3443 issue TA 81315

---

_includes/v21.2/known-limitations/unordered-distinct-operations.md
_includes/v21.2/misc/session-vars.html
_includes/v22.1/known-limitations/unordered-distinct-operations.md
_includes/v22.1/misc/session-vars.md
v21.2/explain.md
v21.2/known-limitations.md
v21.2/vectorized-execution.md
v22.1/explain.md
v22.1/known-limitations.md
v22.1/vectorized-execution.md

**Remove mention of vectorize_row_count_threshold session variable**
This session variable has been removed in 21.2.0 release.
Fixes: #11301
**Remove known limitation of unordered distinct in the vectorized engine**
This limitation has been addressed in 21.2.0 release.
Fixes: #11348

Update some vectorized execution docs

---

advisories/a81315.md

Now that #13886 is merged, use its anchor link target for v21.2.11 inline in this TA.

Add minor version anchor link for v21.2.11

---

_includes/v21.2/sidebar-data/reference.json
_includes/v22.1/sidebar-data/reference.json
v21.2/alter-database.md
v21.2/alter-role.md
v21.2/cancel-session.md
v21.2/cost-based-optimizer.md
v21.2/experimental-features.md
v21.2/information-schema.md
v21.2/reset-vars.md
v21.2/set-cluster-setting.md
v21.2/set-vars.md
v21.2/show-cluster-setting.md
v21.2/show-vars.md
v21.2/sql-statements.md
v21.2/vectorized-execution.md
v22.1/alter-database.md
v22.1/alter-role.md
v22.1/cancel-session.md
v22.1/cost-based-optimizer.md
v22.1/experimental-features.md
v22.1/information-schema.md
v22.1/reset-vars.md
v22.1/set-cluster-setting.md
v22.1/set-vars.md
v22.1/show-cluster-setting.md
v22.1/show-vars.md
v22.1/sql-statements.md
v22.1/vectorized-execution.md

Addresses: DOC-3631
- Updated all instances of `SET`, `RESET`, and `SHOW` in the corpus to follow the style guide guidance on placeholder usage:
- Bare usage now appended with  `{session variable}`
- Instances with `()` or `<>` now use `{}`
- Code + placeholder text now uniformly monospaced
- Similar text meant to indicate same thing all standardized (example: `var_name ... var_value` and `session_var`).
- Deepest apologies for back and forth but: standardized on singular due to most usage being for single session variables at a time. Example: `SET` only sets one variable at a time, and `SHOW` only prints one variable at a time, unless used as `SHOW ALL`. 
- To accomplish this, most copy could just be updated to `{session variable}` but page titles (front matter) and left-nav entries …

DOC-3631 clarify SQL overview session variables

---

StyleGuide.md

- Add _Escaping special characters_ section covering Jekyll and Unicode situations.
- Linked from _Code block_ and _Placeholders_

Add special character escaping

---

cockroachcloud/ccloud-get-started.md
cockroachcloud/console-access-management.md

Add example on authenticating to different org to ccloud auth docs.

---

_includes/v22.1/sidebar-data/reference.json
v22.1/alter-range-relocate.md
v22.1/alter-range.md
v22.1/configure-zone.md
v22.1/experimental-features.md

Fixes DOC-3344
- Update the existing 'ALTER RANGE' page to make it a list of
subcommands (similar to 'ALTER DATABASE', etc.)
- Add a page, 'ALTER RANGE ... RELOCATE', with some info and examples
about this new command.
- Add some words and back and forth linkage between 'ALTER RANGE
... RELOCATE' docs and the existing 'ALTER TABLE
... EXPERIMENTAL_RELOCATE' statement docs

Add docs for ALTER RANGE ... RELOCATE

---

_redirects

Formerly, anyone trying to follow a link like /docs/releases/v21.1.5 would be given a 404. This should resolve that.

Fix redirects for old RN URLs without .html suffix

---

advisories/a82309.md

v22.1.1 is live today, adding direct anchor link to release notes.

Added v22.1.1 anchor link target
