cockroachdb/docs

v20.2/timestamp.md
=> Cast TIMESTAMP to TEXT without timezone data

v20.2/explain.md
=> Added an INSERT example to the EXPLAIN page

v20.1/array.md, v20.1/jsonb.md, v20.1/release-savepoint.md, v20.2/array.md, v20.2/jsonb.md, v20.2/release-savepoint.md
=> Link array type doc to array functions

v20.1/gssapi_authentication.md, v20.2/gssapi_authentication.md
updated gssapi_authentication.md in v20.1 and v20.2 to have an updated postgresql command
@jseldess  Mentioning you here because the contribution doc specified that all pull requests be assigned to you.
=> updated postgresql command in v20.1 and v20.2

v19.2/insert.md, v20.1/insert.md, v20.2/insert.md
Fixes #8236
Example provided for v19.2, v20.1, v20.2
=> FIX-8236 Provided example to specify columns with insert

v19.2/cockroach-workload.md, v20.1/cockroach-workload.md, v20.2/cockroach-workload.md
=> Remove --concurrency from workload movr docs

v20.2/cockroach-sql.md, v20.2/cockroach-start-single-node.md, v20.2/connection-parameters.md
=> Remove --socket and clarify --socket-dir example

_includes/v20.2/sql/aggregates.md, _includes/v20.2/sql/functions.md, _includes/v20.2/sql/operators.md, _includes/v20.2/sql/window_functions.md, v20.2/array.md, v20.2/install-cockroachdb-spatial.md, v20.2/inverted-indexes.md, v20.2/spatial-data.md, v20.2/spatial-features.md, v20.2/spatial-glossary.md, v20.2/vectorized-execution.md
Refreshing with latest functions/operators.
@rmloveland adding you to review, as most (if not all) of these new functions touch spatial features and will likely resolve issues currently assigned to you.
=> v20.2 functions and operators refresh

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v19.2.11.md
=> v19.2.11 release notes

v20.2/cost-based-optimizer.md
=> Added note about histograms on ARRAY-typed columns

_includes/v19.2/sql/unsupported-postgres-features.md, _includes/v20.1/sql/unsupported-postgres-features.md, v19.1/show-schemas.md, v19.1/sql-name-resolution.md, v19.2/postgresql-compatibility.md, v19.2/show-schemas.md, v19.2/sql-name-resolution.md, v20.1/postgresql-compatibility.md, v20.1/show-schemas.md, v20.1/sql-name-resolution.md, v20.2/alter-schema.md, v20.2/create-schema.md, v20.2/drop-schema.md, v20.2/show-schemas.md, v20.2/sql-name-resolution.md
Fixes #7272.
- Updated Name Resolution page for clarity, formatting, and accuracy.
- Added section on schema namespaces to PostgreSQL Compatibility page.
=> CRDB namespaces updates

v20.2/alter-database.md, v20.2/alter-table.md, v20.2/convert-to-schema.md, v20.2/set-schema.md, v20.2/show-range-for-row.md, v20.2/sql-statements.md
=> Update SHOW RANGE FOR ROW to take indexed columns

_includes/sidebar-data-v20.2.json, v20.2/show-transactions.md, v20.2/sql-statements.md
=> Add SHOW TRANSACTIONS

v20.2/cockroach-debug-zip.md
=> add `cockroach debug zip` node flags

_includes/v20.2/misc/logging-flags.md
Fixes #7871.
@knz I plan to document the logging groups more methodically in a related issue #7202. Thanks for including the table in your PR.
=> add --log-group-max-size

v20.1/inverted-indexes.md, v20.2/inverted-indexes.md
=> Add example of inverted index for array

v20.2/joins.md
=> Lookup joins can use partial indexes

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v20.2.0-rc.1.md
=> v20.2.0-rc.1 Release Notes

v20.2/upgrade-cockroach-version.md
Fixes #8292.
@lucy-zhang I tried to summarize your bullet points in https://github.com/cockroachdb/cockroach/pull/54902, but let me know if you think this can/should be simplified further.
=> add note about v19.2 schema change jobs

v19.2/cockroach-node.md, v20.2/cockroach-node.md, v20.2/remove-nodes.md
=> add --self flag to decommission/recommission

v20.2/alter-schema.md, v20.2/cockroach-demo.md, v20.2/cockroach-gen.md, v20.2/convert-to-schema.md, v20.2/create-schema.md, v20.2/create-view.md, v20.2/drop-database.md, v20.2/drop-schema.md, v20.2/drop-table.md, v20.2/learn-cockroachdb-sql.md, v20.2/make-queries-fast.md, v20.2/partial-indexes.md, v20.2/rename-table.md, v20.2/set-schema.md, v20.2/show-schemas.md, v20.2/show-tables.md, v20.2/temporary-tables.md, v20.2/views.md
This PR fixes https://github.com/cockroachdb/docs/pull/8584...
(I updated the output using a commit that isn't going into v20.2 GA)
FYI @solongordon
=> Updated SHOW TABLES and SHOW SCHEMAS output for v20.2.0-beta-4

v20.2/drop-column.md
=> DROP COLUMN updates

_includes/v20.2/misc/session-vars.html, _includes/v20.2/sql/select-for-update-overview.md, v20.2/explain.md
=> Implicit SELECT FOR UPDATE on UPSERT statements

v20.2/show-grants.md
=> add missing documentation to SHOW GRANTS page

_includes/v20.2/sql/diagrams/create_database.html, v20.2/create-database.md
=> CREATE DATABASE ... CONNECTION LIMIT

interactive-tutorials/explore-db/json-support/foreground.sh, interactive-tutorials/get-started/start-cluster/foreground.sh, interactive-tutorials/playground/foreground.sh, katacoda.yaml
- Fix syntax in katacoda yaml
- Use latest stable version in tutorials
=> Katacoda fix

v20.2/remove-nodes.md
=> mention permanently decommissioned nodes

_includes/v20.2/sql/diagrams/stmt_block.html
This PR includes an updated full syntax diagram on https://github.com/cockroachdb/cockroach/commit/ff5543a960b787e068221edd2ba1c1a26037aa0e.
=> Updated v20.2 full syntax diagram

v20.2/create-sequence.md, v20.2/drop-sequence.md, v20.2/rename-sequence.md, v20.2/set-schema.md, v20.2/show-sequences.md
=> Updated SHOW SEQUENCE output and examples

_includes/v20.2/sql/diagrams/delete.html, v20.2/delete.md, v20.2/update.md
Fixes #8500. 
Note that this PR will conflict with the updates to `UPDATE` documentation in #8667.
=> No-op UPDATE ONLY/DELETE ONLY syntax

v19.2/jsonb.md, v20.1/jsonb.md, v20.2/jsonb.md
Add example for filtering JSONB values through key-value pairs 
Solves #7294 
Signed-off-by: Vipul Gupta (@vipulgupta2048) <vipulgupta2048@gmail.com>
=> Add example for filtering key-value pairs

_includes/v20.2/sql/diagrams/col_qualification.html, v20.2/computed-columns.md
=> GENERATED ALWAYS for computed columns

v20.2/array.md, v20.2/data-types.md, v20.2/string.md
=> Implicit array casting

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v20.2.0-rc.2.md
=> v20.2.0-rc.2 Release Notes

v20.2/information-schema.md
=> Added support for datetime_precision in columns table

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v20.1.8.md
=> Release notes for 20.1.8

v20.2/insert.md, v20.2/performance-best-practices-overview.md
=> Added note about long-running bulk insert transactions

_includes/sidebar-data-cockroachcloud.json, cockroachcloud/authentication.md, cockroachcloud/connect-to-your-cluster.md, cockroachcloud/console-access-management.md, cockroachcloud/create-your-cluster.md, cockroachcloud/deploy-a-python-to-do-app-with-flask-kubernetes-and-cockroachcloud.md, cockroachcloud/monitoring-page.md, cockroachcloud/network-authorization.md, cockroachcloud/security-overview.md, cockroachcloud/user-authorization.md
=> [WIP] VPC Peering docs for GCP clusters

v20.1/jsonb.md, v20.1/known-limitations.md, v20.2/jsonb.md, v20.2/known-limitations.md
=> Updated limitation on ordering by JSON-typed columns

v20.1/array.md, v20.2/array.md
Addresses #7671 
@Amruta-Ranade, please review this PR and let me know if any changes are required. I have slightly modified the example specified in the issue to keep the other examples on the page intact.
=> Added example for array operators

v19.2/known-limitations.md, v19.2/select-clause.md
=> GROUP BY backports

_includes/v20.2/sql/diagrams/for_locking.html, _includes/v20.2/sql/select-for-update-overview.md, v20.2/select-for-update.md
=> SELECT FOR UPDATE NOWAIT and locking mode docs

_includes/v20.2/sql/unsupported-postgres-features.md, v20.1/sql-feature-support.md, v20.2/postgresql-compatibility.md, v20.2/sql-feature-support.md
Fixes #8628. 
- Made some updates to SQL support pages.
- Updated some formatting/output.
I've tried to make these updates as I document a feature, but some have slipped through. Please let me know if I'm missing anything important here.
=> v20.2 SQL feature support

v19.2/sql-audit-logging.md, v20.1/sql-audit-logging.md, v20.2/sql-audit-logging.md
Addresses #4658.
@Amruta-Ranade, can you please review this and let me know if I need to change anything? Thanks.
=> Added tip and link to SQL logging

v20.2/take-and-restore-encrypted-backups.md
Addresses feedback given on #8491.
=> Rename <host> placeholder to <cmk> on KMS Encryption doc

_data/advisories.yml, advisories/a56116.md
X-Ref: https://github.com/cockroachdb/cockroach/issues/56116
=> Technical advisory 56116.

v20.1/cockroach-debug-zip.md
=> backport nodes flags

tutorials/katacoda/build-python-app/finish.md, tutorials/katacoda/build-python-app/foreground.sh, tutorials/katacoda/build-python-app/index.json, tutorials/katacoda/build-python-app/step1.md, tutorials/katacoda/build-python-app/step2.md, tutorials/katacoda/build-python-app/step3.md, v20.2/build-a-python-app-with-cockroachdb-django.md, v20.2/build-a-python-app-with-cockroachdb-pony.md, v20.2/build-a-python-app-with-cockroachdb-sqlalchemy.md, v20.2/build-a-python-app-with-cockroachdb.md
- Add psycopg2 katacoda tutorial
- Will open a separate PR to embed this in our docs once I've validated that the tutorial runs well on katacoda.
- Condense the python toggles
=> Katacoda python

v19.1/int.md, v19.2/int.md, v20.1/int.md, v20.2/int.md
=> Fixed incorrect description of casting behavior

v19.2/set-transaction.md, v19.2/transactions.md, v20.1/set-transaction.md, v20.1/transactions.md, v20.2/set-transaction.md, v20.2/transactions.md
=> Added SET default_transaction_priority examples

v19.2/show-schemas.md, v19.2/show-tables.md, v20.1/show-schemas.md, v20.1/show-tables.md, v20.2/show-schemas.md, v20.2/show-tables.md, v20.2/show-types.md
Fixes https://github.com/cockroachdb/docs/issues/5118.
=> Updated privileges on SHOW SCHEMAS, SHOW TABLES, and SHOW TYPES

tutorials/katacoda/build-python-app/foreground.sh, tutorials/katacoda/build-python-app/index.json, tutorials/katacoda/build-python-app/step1.md, tutorials/katacoda/build-python-app/step3.md, tutorials/katacoda/json-support/foreground.sh, tutorials/katacoda/json-support/index.json, tutorials/katacoda/json-support/step1.md, tutorials/katacoda/json-support/step9.md, v20.2/build-a-python-app-with-cockroachdb.md
=> Revert "Fix python katacoda"

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v20.2.0-rc.4.md
=> v20.2.0-rc.4 release notes

v20.1/flyway.md, v20.2/flyway.md
=> Added section on transactional schema change limitations to Flyway tutorial

_includes/footer.html, _includes/topnav.html
=> Update header and footer

v20.2/manage-a-backup-schedule.md
=> Add scheduled backups metrics

_includes/v20.2/misc/tooling.md, v20.1/flyway.md, v20.2/flyway.md
=> Flyway version 7.1.0

_includes/v19.2/app/django-basic-sample/views.py, _includes/v19.2/app/insecure/django-basic-sample/views.py, _includes/v20.1/app/django-basic-sample/views.py, _includes/v20.1/app/insecure/django-basic-sample/views.py, _includes/v20.2/app/django-basic-sample/views.py, _includes/v20.2/app/insecure/django-basic-sample/views.py
Fixes https://github.com/cockroachlabs/support/issues/654.
=> Added psycopg2.errorcodes import to Django sample

v20.1/cockroach-debug-zip.md, v20.2/cockroach-debug-zip.md
Fixes #8103.
@knz Should this be mentioned in v20.1 and/or earlier?
=> mention CPU profiles in cockroach debug zip

v20.2/authorization.md, v20.2/create-sequence.md, v20.2/drop-role.md, v20.2/drop-user.md, v20.2/owner-to.md
=> Added content for object ownership

v20.1/backup.md, v20.2/backup.md, v20.2/create-schedule-for-backup.md
=> Backup needs write permissions to destination

_includes/sidebar-data-v20.1.json, _includes/sidebar-data-v20.2.json, v20.1/cockroach-statement-diag.md, v20.2/cockroach-statement-diag.md
=> cockroach statement-diag docs

v20.2/admin-ui-overview.md, v20.2/admin-ui-transactions-page.md
Add Transactions to the Admin UI overview table.
=> add Transactions to Admin UI Overview

v20.2/use-userfile-for-bulk-operations.md
=> Remove backticks from userfile title

v20.2/revoke.md
=> v20.2 REVOKE updates

_includes/unsupported-version-soon.md, releases/release-support-policy.md
Fixes #8810 
Also updates Assistance Support end date for v19.2
=> Indicate EOL for v19.1

v20.1/build-a-spring-app-with-cockroachdb-jdbc.md, v20.1/build-a-spring-app-with-cockroachdb-jpa.md, v20.2/build-a-spring-app-with-cockroachdb-jdbc.md, v20.2/build-a-spring-app-with-cockroachdb-jpa.md
Easy navigation and easy reading for others
=> Fix url bugs in docs

cockroachcloud/create-your-cluster.md, cockroachcloud/frequently-asked-questions.md, cockroachcloud/quickstart.md
=> CC automatic coupon codes updates

v20.2/performance-benchmarking-with-tpcc-large.md, v20.2/performance-benchmarking-with-tpcc-medium.md, v20.2/performance-benchmarking-with-tpcc-small.md
Rebrands Admin UI in the new TPCC docs.
=> Admin UI -> DB Console

v20.2/use-userfile-for-bulk-operations.md
=> Update userfile: Example with triple slash

_includes/v20.2/orchestration/start-cockroachdb-operator-secure.md
Relates to https://github.com/cockroachdb/cockroach-operator/pull/241
=> tweak operator cert description

cockroachcloud/frequently-asked-questions.md
=> Add support link to CC / CDC FAQ

cockroachcloud/backups-page.md
=> Remove info about restoring CC clusters/db/tables

v19.2/collate.md, v19.2/known-limitations.md, v20.1/collate.md, v20.1/known-limitations.md, v20.2/collate.md, v20.2/known-limitations.md
The bug was introduced in v19.2 and will be fixed in v21.1
References https://github.com/cockroachdb/cockroach/issues/56335
=> Add known limitation for collation names

_includes/sidebar-data-cockroachcloud.json, releases/cockroachcloud-11192020.md
The content is copied over from the CRDB v20.2.0 release notes.
Closes #8974.
cc: @kannanlakshmi
=> Add Nov 2020 CC Release Notes

v20.2/ui-debug-pages.md
Fixes #7824.
@bdarnell This is a really small update. Please let me know if more detail is needed here.
=> admin requirement on debug endpoints

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v20.2.1.md
=> v20.2.1 Release Notes

jekyll-algolia-dev/lib/jekyll/algolia/indexer.rb
Added synonyms for Admin UI (rebranded to DB Console).
=> add db console synonyms to search

v20.1/cockroachdb-in-comparison.md, v20.2/cockroachdb-in-comparison.md
=> Peter update compare

v19.2/recommended-production-settings.md, v20.1/recommended-production-settings.md, v20.2/recommended-production-settings.md
=> Recommend disabling swap

_includes/marketing-menu.html
=> add k8s menu item

v20.2/remove-nodes.md
=> Fix command to decommission a dead node

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v20.2.2.md
=> Add release notes for v20.2.2

cockroachcloud/upgrade-to-v20.2.md, v20.2/known-limitations.md, v20.2/upgrade-cockroach-version.md
=> known limitation on upgrades and non-terminal jobs

_includes/v20.1/app/hibernate-basic-sample/build.gradle, _includes/v20.1/app/insecure/hibernate-basic-sample/build.gradle, _includes/v20.1/misc/tooling.md, _includes/v20.2/app/insecure/hibernate-basic-sample/build.gradle, _includes/v20.2/misc/tooling.md, v20.1/build-a-java-app-with-cockroachdb.md, v20.1/install-client-drivers.md, v20.2/install-client-drivers.md, v20.2/liquibase.md
=> Liquibase v4.2

v20.2/show-grants.md
=> Fixed syntax typo on SHOW GRANTS page

v20.2/build-a-java-app-with-cockroachdb-hibernate.md, v20.2/build-a-java-app-with-cockroachdb.md
Fixes #8954.
Code changes in cockroachlabs/hello-world-java-jdbc#4 and cockroachlabs/hello-world-java-hibernate#3.
=> Updating doc to use decimal/BigDecimal for monetary units.

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v20.1.9.md
Fixes https://github.com/cockroachdb/docs/issues/8856.
=> v20.1.9 release notes

v19.2/build-a-java-app-with-cockroachdb-hibernate.md, v20.1/build-a-java-app-with-cockroachdb-hibernate.md, v20.2/build-a-java-app-with-cockroachdb-hibernate.md, v21.1/build-a-java-app-with-cockroachdb-hibernate.md
Fixes https://github.com/cockroachdb/docs/issues/8006
=> Fixed link to hibernate client installation instructions

_includes/v19.2/misc/session-vars.html, _includes/v20.1/misc/session-vars.html, _includes/v20.2/misc/session-vars.html, _includes/v21.1/misc/session-vars.html
Fixes https://github.com/cockroachdb/docs/issues/8246.
=> Fixed transaction priorities link

_includes/cockroachcloud/cockroachcloud-pricing.md
=> Add CC machine options

v20.1/build-a-python-app-with-cockroachdb-sqlalchemy.md, v20.1/build-a-python-app-with-cockroachdb.md, v20.1/developer-guide-overview.md, v20.2/build-a-python-app-with-cockroachdb-sqlalchemy.md, v20.2/build-a-python-app-with-cockroachdb.md, v20.2/developer-guide-overview.md
Fixes https://github.com/cockroachdb/docs/issues/8793.
=> Add link to Cockroach University

v21.1/build-a-python-app-with-cockroachdb-sqlalchemy.md, v21.1/build-a-python-app-with-cockroachdb.md, v21.1/developer-guide-overview.md
=> Add link to Cockroach University (follow-up on #8846)

_includes/sidebar-data-cockroachcloud.json, releases/cockroachcloud-12112020.md
Note: Will merge once the new machine options / pricing is in prod.
=> Dec release notes

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v20.2.3.md
Fixes https://github.com/cockroachdb/docs/issues/8921
=> v20.2.3 release notes

v20.2/import-into.md, v20.2/import.md, v20.2/use-userfile-for-bulk-operations.md, v21.1/import-into.md, v21.1/import.md
Addresses https://github.com/cockroachdb/docs/issues/9179
=> Update IMPORT and IMPORT INTO permissions

releases/cockroachcloud-11192020.md, releases/v20.2.0.md
=> Edit release note wording for CC backups

v20.1/show-databases.md
Quick PR to address feedback from https://github.com/cockroachdb/docs/pull/9199#pullrequestreview-553805168 regarding `v20.1/show-databases.md`
cc @lnhsingh
=> apply change to `v20.1/show-databases.md`

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v20.1.10.md
=> v20.1.10 release notes

_includes/cockroach_u_pydev.md, v20.1/build-a-python-app-with-cockroachdb-sqlalchemy.md, v20.1/build-a-python-app-with-cockroachdb.md, v20.1/developer-guide-overview.md, v20.2/build-a-python-app-with-cockroachdb-sqlalchemy.md, v20.2/build-a-python-app-with-cockroachdb.md, v20.2/developer-guide-overview.md, v21.1/build-a-python-app-with-cockroachdb-sqlalchemy.md, v21.1/build-a-python-app-with-cockroachdb.md, v21.1/developer-guide-overview.md
Also remove an extraneous </br> tag that was
breaking the callout in some cases.
=> Use include for Cockroach U pydev callout

v20.2/build-a-python-app-with-cockroachdb-django.md, v21.1/build-a-python-app-with-cockroachdb-django.md
https://cockroachlabs.slack.com/archives/CHZ2NF811/p1609859059220600
=> Updated pip and python commands in Django tutorial

v20.2/show-trace.md
Easy navigation and easy reading for others
=> Fix broken url in docs

_includes/v19.2/start-in-docker/mac-linux-steps.md, _includes/v20.1/start-in-docker/mac-linux-steps.md, _includes/v20.2/start-in-docker/mac-linux-steps.md
=> Fix docker volume remove command

v20.2/build-a-go-app-with-cockroachdb-gorm.md, v20.2/build-a-go-app-with-cockroachdb-pq.md, v20.2/build-a-go-app-with-cockroachdb.md, v21.1/build-a-go-app-with-cockroachdb-gorm.md, v21.1/build-a-go-app-with-cockroachdb-pq.md, v21.1/build-a-go-app-with-cockroachdb.md
=> Updated golang hello world language syntax checker

_includes/cockroachcloud/quickstart/create-a-free-cluster.md, _includes/cockroachcloud/quickstart/set-up-your-cluster-connection.md, cockroachcloud/quickstart.md
=> Update Quickstart for CC Free (beta)

_includes/v19.2/start-in-docker/mac-linux-steps.md, _includes/v20.1/start-in-docker/mac-linux-steps.md, _includes/v20.2/start-in-docker/mac-linux-steps.md, _includes/v21.1/start-in-docker/mac-linux-steps.md
=> Get node startup details from logs in docker container

_includes/v20.2/app/create-a-database.md, _includes/v20.2/app/start-cockroachdb.md, cockroachcloud/quickstart.md, v20.2/build-a-python-app-with-cockroachdb.md
Updates to the prioritized sample apps, which will include:
Closes #5738.
=> Free tier sample apps

v21.1/connect-to-the-database.md, v21.1/connection-parameters.md, v21.1/install-client-drivers.md
=> First pass at Connect to CockroachDB.

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v20.2.4.md
=> Add release notes for v20.2.4

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v19.2.12.md
=> Add release notes for v19.2.12

_includes/sidebar-data-cockroachcloud.json, releases/cockroachcloud-01222021.md
=> January CC Release Notes

tutorials/katacoda/playground-20.2/background.sh, tutorials/katacoda/playground-20.2/foreground.sh, tutorials/katacoda/playground-20.2/index.json
- Run cockroach in foreground
- Load movr in foreground
=> Revise foreground script for 20.2 playground

cockroachcloud/backups-page.md, cockroachcloud/console-access-management.md, v20.2/restore.md, v21.1/restore.md
=> Add restore for CC databases / tables

releases/v20.1.11.md
=> language tweak

v20.2/build-a-python-app-with-cockroachdb-django.md, v20.2/build-a-python-app-with-cockroachdb-sqlalchemy.md, v20.2/build-a-python-app-with-cockroachdb.md
=> Added CC free tier connection step to Python HW tutorials

_includes/v20.2/app/cc-free-tier-params.md, v20.2/build-a-go-app-with-cockroachdb-gorm.md, v20.2/build-a-go-app-with-cockroachdb-pq.md, v20.2/build-a-go-app-with-cockroachdb.md
Related to https://github.com/cockroachdb/docs/issues/5738.
=> Added CC free tier connection step to Golang HW tutorials

cockroachcloud/backups-page.md, tutorials/katacoda/playground-21.1/foreground.sh, tutorials/katacoda/playground-21.1/index.json
Also update foreground script to create a user to access the Console.
=> Update 21.1 playground to include DB Console

cockroachcloud/cluster-management.md
Split doc into CC Free vs. CC since capabilities / fields on each differ
Closes #9459.
=> Update Manage Your Cluster doc

cockroachcloud/upgrade-policy.md
Update the Upgrade Policy doc to include CC Free Tier. Closes #9015
=> Misc CC update

tutorials/katacoda/playground-21.1/foreground.sh, tutorials/katacoda/playground-21.1/index.json
It didn't work. Need to figure out the right way to expose
the DB Console within a Katacoda scenario.
=> Revert https://github.com/cockroachdb/docs/pull/9534

releases/v19.2.12.md, releases/v20.1.11.md, releases/v20.2.3.md, releases/v20.2.4.md
Also fix some release note intros.
=> Tag release notes for docs issue generation

_includes/sidebar-data-cockroachcloud.json, cockroachcloud/free-faqs.md, cockroachcloud/frequently-asked-questions.md
=> Add FAQs for CC Free

tutorials/katacoda/environments/v20.2-running/build/1_install_cockroach.sh, tutorials/katacoda/environments/v20.2-running/build/2_configure_environment.sh, tutorials/katacoda/environments/v20.2-running/katacoda.yaml, tutorials/katacoda/environments/v21.1-running/build/1_install_cockroach.sh, tutorials/katacoda/environments/v21.1-running/build/2_configure_environment.sh, tutorials/katacoda/environments/v21.1-running/katacoda.yaml
Install and start cockroach when environment starts.
=> Create custom Katacoda environments

tutorials/katacoda/build-python-app/foreground.sh, tutorials/katacoda/learn-cockroachdb-sql/foreground.sh, tutorials/katacoda/playground-20.2/foreground.sh, tutorials/katacoda/playground-21.1/foreground.sh
To exit the Katacoda environment when the user
exists the SQL shell.
Also copy the geo libraries to the expected places
in a few scenarios.
=> Run cockroach demo/sql with exec in Katacoda

_includes/cockroachcloud/free-limitations.md, _includes/sidebar-data-v20.2.json, _includes/sidebar-data-v21.1.json, cockroachcloud/free-faqs.md, cockroachcloud/quickstart-trial-cluster.md, cockroachcloud/quickstart.md
- Update FAQs based on feedback from internal stakeholders. Closes 
#9689.
- Change Quickstart to default to the CC Dedicated tab (as discussed on 
email)
cc @kannanlakshmi
=> Update Quickstart / FAQs

_data/advisories.yml, advisories/a58932.md
Adding per [discussion](https://cockroachlabs.slack.com/archives/CSPK16V51/p1612296817023200).
=> Add thanks to reporter in tech advisory

v21.1/connection-pooling.md
=> Add information on connection validation to connection pool topic.

tutorials/katacoda/playground-21.1/foreground.sh
=> Upgrade the 21.1 SQL playground to v21.1.0-alpha.2

_redirects
add redirects for old top level pages
=> add redirects

_data/releases-cc.yml, _includes/sidebar-data-cockroachcloud.json, cockroachcloud/free-faqs.md, releases/cockroachcloud-01222021.md, releases/cockroachcloud-02092021.md, releases/cockroachcloud-12112020.md
=> February 2021 CC Release notes

tutorials/katacoda/playground-21.1/foreground.sh
Now that alpha.3 has been released: https://www.cockroachlabs.com/docs/releases/v21.1.0-alpha.3
=> Upgrade 21.1 sql playground to v21.1.0-alpha.3

releases/release-support-policy.md
=> clarify security fixes policy

_includes/v20.2/app/create-a-database.md, _includes/v21.1/app/create-a-database.md, v20.2/build-a-python-app-with-cockroachdb.md, v21.1/build-a-go-app-with-cockroachdb-gorm.md, v21.1/build-a-go-app-with-cockroachdb-pq.md, v21.1/build-a-go-app-with-cockroachdb.md, v21.1/build-a-python-app-with-cockroachdb-django.md, v21.1/build-a-python-app-with-cockroachdb-sqlalchemy.md, v21.1/build-a-python-app-with-cockroachdb.md
=> port 20.2 sample app changes to 21.1

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v20.1.12.md
=> Add release notes for v20.1.12

_includes/sidebar-data-v1.0.json, _includes/sidebar-data-v1.1.json, _includes/sidebar-data-v19.1.json, _includes/sidebar-data-v19.2.json, _includes/sidebar-data-v2.0.json, _includes/sidebar-data-v2.1.json, _includes/sidebar-data-v20.1.json, _includes/sidebar-data-v20.2.json, _includes/sidebar-data-v21.1.json
=> Add sidenav link to Docs Home

tutorials/katacoda/build-python-app/foreground.sh, tutorials/katacoda/environments/v20.2-running/build/1_install_cockroach.sh, tutorials/katacoda/environments/v20.2-running/build/2_configure_environment.sh, tutorials/katacoda/environments/v20.2-running/katacoda.yaml, tutorials/katacoda/environments/v21.1-running/build/1_install_cockroach.sh, tutorials/katacoda/environments/v21.1-running/build/2_configure_environment.sh, tutorials/katacoda/environments/v21.1-running/katacoda.yaml, tutorials/katacoda/json-support/foreground.sh, tutorials/katacoda/learn-cockroachdb-sql/foreground.sh, tutorials/katacoda/playground-20.2/foreground.sh
Also remove the unused /environments directory.
=> Upgrade Katacodas to 20.2.5

cockroachcloud/authentication.md, cockroachcloud/connect-to-your-cluster.md
Closes #9336
Added a security risks section with descriptions for `require` and `verify-full`.
=> SSL security risks section

cockroachcloud/upgrade-to-v20.2.md, releases/v21.1.0-alpha.1.md, v20.2/known-limitations.md, v20.2/upgrade-cockroach-version.md, v21.1/known-limitations.md, v21.1/upgrade-cockroach-version.md
=> Remove limitations around jobs during rolling upgrades

tutorials/katacoda/spatial-data/finish.md, tutorials/katacoda/spatial-data/foreground.sh, tutorials/katacoda/spatial-data/index.json, tutorials/katacoda/spatial-data/step1.md, tutorials/katacoda/spatial-data/step2.md, tutorials/katacoda/spatial-data/step3.md, tutorials/katacoda/spatial-data/step4.md, tutorials/katacoda/spatial-data/step5.md, tutorials/katacoda/spatial-data/step6.md, tutorials/katacoda/spatial-data/step7.md, tutorials/katacoda/spatial-data/step8.md
This PR puts the tutorial in place for testing on Katacoda.
The tutorial will be embedded in our docs later.
=> Add in-browser version of spatial data tutorial

v21.1/import-into.md
Added nextval() to list of default expressions
Closes #9587
=> Add nextval to default expressions for IMPORT INTO

_includes/sidebar-data-v21.1.json, v21.1/cockroach-commands.md, v21.1/cockroach-import.md, v21.1/cockroach-userfile-upload.md
-Add new `cockroach import` statement to cockroach commands page
-Create new `cockroach import` page
-Add callout to `cockroach userfile upload` page suggesting when to use `cockroach import` instead
Closes: #9139
=> CLI import command

_layouts/homepage.html, cockroachcloud/index.md
=> rel url paths

v20.2/licensing-faqs.md
=> Licensing capitalization typo

_includes/v20.2/app/pkcs8-gen.md, v20.2/build-a-java-app-with-cockroachdb-hibernate.md, v20.2/build-a-java-app-with-cockroachdb.md, v20.2/connect-to-the-database-cockroachcloud.md, v20.2/connect-to-the-database.md
Forgot to do this as a part of #9869...
=> Propagated #9869 to 20.2

_includes/v20.2/prod-deployment/insecure-start-nodes.md, _includes/v20.2/prod-deployment/secure-start-nodes.md, _includes/v21.1/prod-deployment/insecure-start-nodes.md, _includes/v21.1/prod-deployment/secure-start-nodes.md
=> Update deployment tutorial start nodes step for spatial

v20.1/build-a-nodejs-app-with-cockroachdb-sequelize.md, v20.2/build-a-nodejs-app-with-cockroachdb-sequelize.md, v21.1/build-a-nodejs-app-with-cockroachdb-sequelize.md
@ianjevans 
I'll propagate to 20.1 and 21.1 after your approval.
=> Updated node sequelize HW tutorial to use demo/CC

v20.1/build-a-nodejs-app-with-cockroachdb.md, v20.2/build-a-nodejs-app-with-cockroachdb.md, v21.1/build-a-nodejs-app-with-cockroachdb.md
@ianjevans 
I'll propagate the changes to 20.1 and 21.1, and then merge this after your approval and after https://github.com/cockroachlabs/hello-world-node-pg/pull/1 is merged.
=> Updated node.js pg tutorial to use new sample and CC free

_includes/v21.1/misc/source-privileges.md, v21.1/import.md, v21.1/show-backup.md
=> SHOW BACKUP privileges update

_includes/sidebar-data-v20.2.json, _includes/sidebar-data-v21.1.json, v20.2/import-data.md, v20.2/query-spatial-data.md, v20.2/spatial-data.md, v21.1/import-data.md, v21.1/query-spatial-data.md, v21.1/spatial-data.md
=> Added Working with Spatial page to the Develop ToC

v21.1/export.md
=> Update EXPORT privileges

Makefile
=> Add clean target and ensure deps are created in vendor.

_includes/cockroachcloud/quickstart/create-a-free-cluster.md, _includes/v20.1/app/start-cockroachdb.md, _layouts/homepage.html, cockroachcloud/create-a-free-cluster.md, cockroachcloud/create-your-cluster.md, cockroachcloud/deploy-a-python-to-do-app-with-flask-kubernetes-and-cockroachcloud.md, cockroachcloud/index.md, cockroachcloud/quickstart-trial-cluster.md, releases/cockroachcloud-05042020.md, releases/v20.2.0.md
For tracking new CC clusters attributed to docs.
=> Add more specific CC referral ids

_data/releases-cc.yml, _includes/sidebar-data-cockroachcloud.json, releases/cockroachcloud-03082021.md
Closes [CC-3654](https://cockroachlabs.atlassian.net/browse/CC-3654)
=> CC Release Notes - March 2021

_includes/v21.1/misc/session-vars.html
=> Added escape_string_warning to session variables

v1.0/install-cockroachdb.html, v1.1/install-cockroachdb.html, v19.1/install-cockroachdb-linux.html, v19.1/install-cockroachdb-mac.html, v19.1/install-cockroachdb-windows.html, v19.2/install-cockroachdb-linux.html, v19.2/install-cockroachdb-mac.html, v19.2/install-cockroachdb-windows.html, v2.0/install-cockroachdb.html, v2.1/install-cockroachdb-linux.html, v2.1/install-cockroachdb-mac.html, v2.1/install-cockroachdb-windows.html, v20.1/install-cockroachdb-linux.html, v20.1/install-cockroachdb-mac.html, v20.1/install-cockroachdb-windows.html, v20.2/install-cockroachdb-linux.html, v20.2/install-cockroachdb-mac.html, v20.2/install-cockroachdb-windows.html, v21.1/install-cockroachdb-linux.html, v21.1/install-cockroachdb-mac.html, v21.1/install-cockroachdb-windows.html
=> Remove COPY from copy icon on install pages

cockroachcloud/index.md, v19.2/index.md, v20.1/index.md, v20.2/index.md, v21.1/index.md
=> Center Learn More link in landing page cards

_includes/sidebar-data-v20.2.json, _includes/sidebar-data-v21.1.json, v20.2/bulk-update-data.md, v20.2/update-data.md, v20.2/update.md, v21.1/bulk-update-data.md, v21.1/update-data.md, v21.1/update.md
Fixes #9863. 
Related to #9065.
=> Bulk-update data

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v20.1.13.md
=> Add release notes for v20.1.13

v21.1/cockroach-commands.md, v21.1/cockroach-userfile-delete.md, v21.1/cockroach-userfile-get.md, v21.1/cockroach-userfile-upload.md, v21.1/use-userfile-for-bulk-operations.md
Closes #9821 
New page for `cockroach userfile get`
Updates to Cockroach Command and other userfile pages
Note: Required Privileges and Examples sections may need some work
=> New CLI command `cockroach userfile get`

_includes/sidebar-releases.json, tutorials/katacoda/build-python-app/foreground.sh, tutorials/katacoda/json-support/foreground.sh, tutorials/katacoda/learn-cockroachdb-sql/foreground.sh, tutorials/katacoda/playground-20.2/foreground.sh, tutorials/katacoda/spatial-data/foreground.sh
- Highlight All Product Releases in sidenav for v20.2.6
- Upgrade katacoda tutorials to v20.2.6
=> Release and katacoda updates

v20.2/migrate-from-oracle.md, v21.1/migrate-from-oracle.md
Closes #8240
- one capitalization change, one typo
- change python2 to python3
=> Migrate from Oracle small updates

cockroachcloud/frequently-asked-questions.md
Link to information on how to add/delete nodes
=> Add link from FAQ to cluster management

_includes/sidebar-data-v20.2.json, _includes/sidebar-data-v21.1.json, v20.2/update-data.md, v21.1/update-data.md
Fixes https://github.com/cockroachdb/docs/issues/9862.
=> Dev guide v2 Update Data updates

cockroachcloud/free-faqs.md
-Added a Q&A about usage limits
-Moved the sentence about storage from the first question to the usage question
=> CC Free FAQ storage limit

v20.2/import.md, v21.1/import.md
=> User-defined types disabled for IMPORT

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v21.1.0-beta.1.md
=> v21.1.0-beta.1 Release Notes

_includes/windows_warning.md, releases/index.md, releases/v20.2.6.md, v19.1/install-cockroachdb-windows.html, v19.2/install-cockroachdb-windows.html, v2.0/install-cockroachdb.html, v2.1/install-cockroachdb-windows.html, v20.1/install-cockroachdb-windows.html, v20.2/install-cockroachdb-windows.html, v21.1/install-cockroachdb-windows.html
=> Add Windows warning to release list and latest 20.2 notes

_includes/v20.2/misc/session-vars.html, _includes/v21.1/misc/session-vars.html, v21.1/vectorized-execution.md
Fixes https://github.com/cockroachdb/docs/issues/9996.
Fixes https://github.com/cockroachdb/docs/issues/9099.
=> Updated vectorized settings in 20.2, 21.1

v21.1/enum.md, v21.1/known-limitations.md, v21.1/partitioning.md
Fixes https://github.com/cockroachdb/docs/issues/9548.
=> Removed limitation on partitioning by ENUM values

cockroachcloud/connect-to-your-cluster.md
=> Remove extra line break in tab name

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v20.2.7.md
=> draft v20.2.7 release notes

_includes/v21.1/sql/generated/diagrams/alter_type.html, v21.1/alter-type.md, v21.1/cancel-job.md, v21.1/online-schema-changes.md
Fixes https://github.com/cockroachdb/docs/issues/10138.
Fixes https://github.com/cockroachdb/docs/issues/10060.
Fixes https://github.com/cockroachdb/docs/issues/10137.
=> ALTER TYPE ... DROP VALUE

_includes/v20.2/app/see-also-links.md, _includes/v21.1/app/see-also-links.md, v20.2/build-a-go-app-with-cockroachdb.md, v20.2/build-a-java-app-with-cockroachdb.md, v20.2/connection-pooling.md, v21.1/build-a-go-app-with-cockroachdb.md, v21.1/build-a-java-app-with-cockroachdb.md, v21.1/connection-pooling.md
Fixes https://github.com/cockroachdb/docs/issues/9879.
=> pgxpool docs

_layouts/page.html
=> Fix caching bug

v20.2/pg-catalog.md, v21.1/pg-catalog.md
Follow-up of https://github.com/cockroachdb/docs/pull/8909.
=> Updates to pg_catalog tables

v21.1/cockroach-import.md, v21.1/import-performance-best-practices.md, v21.1/import.md, v21.1/migrate-from-postgres.md, v21.1/migrate-from-shapefiles.md, v21.1/spatial-tutorial.md
=> New ignore_unsupported_statements and log_ignored_statements options for PGDUMP

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v21.1.0-beta.2.md
=> Add release notes for v21.1.0-beta.2

cockroachcloud/production-checklist.md, v20.2/connection-pooling.md, v20.2/recommended-production-settings.md, v21.1/connection-pooling.md, v21.1/recommended-production-settings.md
=> Reference new connection pooling topic for prod checklists

v20.2/liquibase.md, v21.1/liquibase.md
Fixes https://github.com/cockroachdb/docs/issues/9895
=> Fixed whitespace typo in Liquibase example

v20.2/build-a-spring-app-with-cockroachdb-jpa.md, v21.1/build-a-spring-app-with-cockroachdb-jpa.md
Fixes https://github.com/cockroachdb/docs/issues/9915.
=> Fixed broken remote includes for Spring JPA tutorial

v21.1/set-vars.md
Fixes https://github.com/cockroachdb/docs/issues/9570.
=> Removed local option from SET TRACING docs

_includes/v20.2/misc/interleave-deprecation-note.md, _includes/v21.1/misc/interleave-deprecation-note.md
Fixes broken formatting here: https://www.cockroachlabs.com/docs/v20.2/sql-feature-support#miscellaneous
=> Fixed interleaving deprecation note formatting

_data/releases-cc.yml, _data/releases.yml, _includes/sidebar-data-cockroachcloud.json, releases/cockroachcloud-04052021.md
Closes https://cockroachlabs.atlassian.net/browse/CC-3655
=> CockroachCloud Release Notes April 5 2021

cockroachcloud/create-an-account.md
Closes: https://cockroachlabs.atlassian.net/browse/CC-3825?atlOrigin=eyJpIjoiMzlmY2NiMWViYmIwNDU1NWIxNTIxOWU3NzVlYWY5YjUiLCJwIjoiaiJ9
Only found two instances of this in the CC docs.
Changes to UI not live yet.
=> Change First/Last Name instances to Name

v20.2/admin-ui-cluster-overview-page.md, v20.2/admin-ui-overview.md, v20.2/admin-ui-statements-page.md, v21.1/admin-ui-cluster-overview-page.md, v21.1/admin-ui-overview.md, v21.1/admin-ui-statements-page.md
Removed some empty pages that were intended for redirects (but aren't necessary).
=> remove empty pages

_includes/v21.1/sql/generated/diagrams/show_enums.html, v21.1/show-enums.md
Fixes https://github.com/cockroachdb/docs/issues/9126.
=> SHOW ENUMS FROM

cockroachcloud/frequently-asked-questions.md
Closes https://cockroachlabs.atlassian.net/browse/CC-3703
Closes https://cockroachlabs.atlassian.net/browse/CC-3684
Closes https://cockroachlabs.atlassian.net/browse/CC-3681
Closes https://cockroachlabs.atlassian.net/browse/CC-3686
Additional questions pulled from [internal FAQ](https://docs.google.com/document/d/1foKgViAVMbXF15SROF3JFKEeWFvX3f4cyCL6dUPgFlo/edit)
=> CC FAQ Expansion & Updates

_includes/sidebar-data-v20.2.json, _includes/sidebar-data-v21.1.json, _includes/v20.2/app/start-cockroachdb.md, _includes/v21.1/app/start-cockroachdb.md, cockroachcloud/connect-to-a-free-cluster.md, cockroachcloud/connect-to-your-cluster.md, cockroachcloud/create-a-free-cluster.md, cockroachcloud/create-your-cluster.md, cockroachcloud/quickstart-trial-cluster.md, cockroachcloud/quickstart.md, v20.2/build-a-spring-app-with-cockroachdb-jdbc.md, v20.2/build-a-spring-app-with-cockroachdb-jpa.md, v21.1/build-a-spring-app-with-cockroachdb-jdbc.md, v21.1/build-a-spring-app-with-cockroachdb-jpa.md
Also fix some tab styling to match new design guidelines.
=> Default to CC Free across docs

v21.1/split-at.md, v21.1/unsplit-at.md
Fixes https://github.com/cockroachdb/docs/issues/9092.
=> Updated SPLIT AT and UNSPLIT AT example output

_includes/v20.1/misc/tooling.md, _includes/v20.2/misc/tooling.md, _includes/v21.1/misc/tooling.md
=> Updated recommended DataGrip version, support level now "Full"

_includes/v21.1/misc/session-vars.html
Fixes https://github.com/cockroachdb/docs/issues/10265.
=> Timeout session variable defaults; updated session variable table formatting

_includes/v21.1/sql/generated/diagrams/create_type.html, v21.1/create-type.md
Fixes https://github.com/cockroachdb/docs/issues/9591.
=> Added IF NOT EXISTS to CREATE TYPE

v20.1/null-handling.md, v20.2/null-handling.md, v21.1/null-handling.md, v21.1/string.md
Fixes https://github.com/cockroachdb/docs/issues/9076.
=> Allow string concat with any non-array type; Update NULL concatenation docs

_includes/v20.2/orchestration/start-cockroachdb-helm-insecure.md, _includes/v20.2/orchestration/start-cockroachdb-helm-secure.md, _includes/v21.1/orchestration/start-cockroachdb-helm-insecure.md, _includes/v21.1/orchestration/start-cockroachdb-helm-secure.md
Tweaked the language of the Helm callout to be more version-specific.
=> tweak Helm callout

v21.1/create-sequence.md, v21.1/rename-database.md, v21.1/rename-sequence.md
Fixes https://github.com/cockroachdb/docs/issues/10095.
=> Sequence renaming enabled for sequences referenced in a table

_includes/v21.1/known-limitations/copy-syntax.md, _includes/v21.1/sql/generated/diagrams/copy_from.html, v21.1/copy-from.md, v21.1/set-schema.md
Fixes https://github.com/cockroachdb/docs/issues/10061.
Fixes https://github.com/cockroachdb/docs/issues/10062.
=> COPY FROM support for CSV, DELIMITER, NULL

cockroachcloud/create-a-free-cluster.md, cockroachcloud/free-faqs.md
Add optional step to select a different region when creating a free cluster
Hold until feature is live
=> CC free regions

_includes/v21.1/misc/session-vars.html, v21.1/pg-catalog.md
Fixes https://github.com/cockroachdb/docs/issues/10307.
=> stub_catalog_tables session variable

releases/v21.1.0-beta.3.md
=> Add beta note to 21.1.0-beta.3

_includes/v20.2/metric-names.md, _includes/v21.1/metric-names.md
Closes https://github.com/cockroachdb/docs/issues/9156
Add `changefeed.running` and `changefeed.failures` metrics and descriptions.
=> Add new changefeed metrics to table

v21.1/use-userfile-for-bulk-operations.md
=> Add `cockroach import` info to userfile for bulk operations

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v21.1.0-beta.4.md
=> v21.1.0-beta.4 release notes

_includes/v21.1/misc/force-index-selection.md, v21.1/inverted-indexes.md, v21.1/partial-indexes.md
=> Partial inverted index support in 21.1.

_includes/head.html, _redirects
=> Change /stable and /dev redirects from 200 to 301

_includes/v21.1/sql/generated/diagrams/show_zone.html, _includes/v21.1/zone-configs/constrain-leaseholders-to-specific-datacenters.md, _includes/v21.1/zone-configs/create-a-replication-zone-for-a-database.md, _includes/v21.1/zone-configs/create-a-replication-zone-for-a-secondary-index.md, _includes/v21.1/zone-configs/create-a-replication-zone-for-a-system-range.md, _includes/v21.1/zone-configs/create-a-replication-zone-for-a-table-partition.md, _includes/v21.1/zone-configs/create-a-replication-zone-for-a-table.md, _includes/v21.1/zone-configs/edit-the-default-replication-zone.md, _includes/v21.1/zone-configs/view-all-replication-zones.md, _includes/v21.1/zone-configs/view-the-default-replication-zone.md, v20.1/show-zone-configurations.md, v20.2/show-zone-configurations.md, v21.1/partitioning.md, v21.1/show-zone-configurations.md
Fixes https://github.com/cockroachdb/docs/issues/10056.
=> Updated SHOW ZONE CONFIGURATIONS diagram, parameters, and example output

v21.1/cockroach-dump.md
=> cockroach dump support for --dump-mode=schema

_includes/v21.1/sql/start-a-multi-region-demo-cluster.md, v21.1/demo-low-latency-multi-region-deployment.md, v21.1/simulate-a-multi-region-cluster-on-localhost.md
=> Include multi-region demo cluster step directly

v21.1/add-region.md
=> Rebalancing will happen when primary region is set

_includes/sidebar-data-cockroachcloud.json, cockroachcloud/alerts-page.md, cockroachcloud/monitoring-page.md
=> draft CC Alerts doc

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v20.2.8.md
=> Add release notes for v20.2.8

_includes/v21.1/sql/generated/diagrams/show_create.html, v21.1/show-create.md
Fixes https://github.com/cockroachdb/docs/issues/10091.
=> SHOW CREATE ALL TABLES

Gemfile.lock, _includes/sidebar-data-v21.1.json, _includes/v21.1/sql/generated/diagrams/show_regions.html, _includes/v21.1/sql/movr-statements-nodes.md, v21.1/add-region.md, v21.1/show-regions.md, v21.1/sql-statements.md
Fixes #9564.
Fixes #9113.
Fixes #9095.
Fixes #9600.
Fixes #9308.
Fixes #9124.
Fixes #10306.
Related to https://github.com/cockroachdb/cockroach/pull/64103.
=> SHOW REGIONS

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v20.1.15.md
=> v20.1.15 release notes.

v20.2/connection-parameters.md, v21.1/connection-parameters.md
Fixes https://github.com/cockroachdb/docs/issues/10069.
=> options=-c support in connection URLs

v20.2/stream-data-out-of-cockroachdb-using-changefeeds.md, v21.1/stream-data-out-of-cockroachdb-using-changefeeds.md
This isn't new behavior, but we had some questions on it recently and did some investigation, and it seems worth calling out.
=> Document delete behavior

cockroachcloud/connect-to-a-free-cluster.md
Closes https://cockroachlabs.atlassian.net/browse/CC-3682?atlOrigin=eyJpIjoiYzkxZDhiYTUxZGMwNDhjMmI2YTQ0YWQwODViMTQ3MTMiLCJwIjoiaiJ9
=> CC Connect to Free Cluster clarification

_includes/sidebar-data-cockroachcloud.json, _includes/sidebar-data-v21.1.json, cockroachcloud/free-faqs.md, cockroachcloud/migrate-from-free-to-dedicated.md, v20.2/migration-overview.md
Add instructions on how to migrate from a CC Free cluster to a paid CC cluster.
Closes [CC-3834](https://cockroachlabs.atlassian.net/browse/CC-3834).
=> Migrate from CC Free to CC Dedicated

_includes/v20.2/known-limitations/restore-aost.md, _includes/v21.1/known-limitations/restore-aost.md, v20.2/known-limitations.md, v20.2/restore.md, v21.1/known-limitations.md, v21.1/restore.md
=> Document historical reads on restored objects as a known limitation

cockroachcloud/connect-to-a-free-cluster.md
Copied the note from Connect to Your Cluster Dedicated docs into Free tier docs.
CC: @emily-horing 
Related to: https://cockroachlabs.atlassian.net/browse/CC-4137
=> Add note about sslmode=require

_data/releases-cc.yml, _includes/sidebar-data-cockroachcloud.json, releases/cockroachcloud-05032021.md
Release notes for May 3, 2021
Closes: https://cockroachlabs.atlassian.net/browse/CC-3656?atlOrigin=eyJpIjoiZGRmZjUwZTFlNDM5NDYzYmEzNTEwYjY4ODJiZjBlNmYiLCJwIjoiaiJ9
=> CC Release Notes May 2021

_data/advisories.yml, advisories/a63162.md
Was actually published on the 30th
=> Correct date for incremental backup advisory

releases/release-support-policy.md
=> Clarify date format on Release Support Policy page

_includes/v21.1/sql/shell-commands.md
=> Document \c shell command

_includes/sidebar-data-v21.1.json, _includes/v21.1/misc/tooling.md, v21.1/community-tooling.md, v21.1/third-party-database-tools.md
Fixes https://github.com/cockroachdb/docs/issues/8248.
Related to https://github.com/cockroachdb/docs/issues/8424, https://github.com/cockroachdb/docs/issues/8423.
@vy-ton 
We should probably add more tools. Also, we need to come up with a list of tools that we currently label as "Beta" support that are, in fact, "Community" support.
=> Added community support page; updated ToC

_includes/cockroachcloud/nodes-limitation.md, cockroachcloud/create-your-cluster.md, cockroachcloud/frequently-asked-questions.md
Closes https://cockroachlabs.atlassian.net/browse/CC-3822?atlOrigin=eyJpIjoiMTczYzBmNTQ1ODJiNGM4M2EzOGMxNmQ3NzI1NGMxOTYiLCJwIjoiaiJ9
Add callout to Create Your Cluster page and FAQs
=> CC Callout that you can't add nodes to a single-node cluster

cockroachcloud/create-your-cluster.md, cockroachcloud/frequently-asked-questions.md
Closes https://cockroachlabs.atlassian.net/browse/CC-4015?atlOrigin=eyJpIjoiYzU1MzU2YzMwZWZmNDg4ZDlkZGQyMWVhNTg1ZmZjYzgiLCJwIjoiaiJ9
Add Mumbai (`asia-south1`) and all city names to list of disabled regions.
=> CC update unavailable regions

cockroachcloud/alerts-page.md
Added the repeat cadences for each alert type.
=> document repeating alerts behavior

cockroachcloud/connect-to-a-free-cluster.md, cockroachcloud/quickstart.md
Added to bottom of Quickstart and top of Connect to a Free Cluster.
Closes https://cockroachlabs.atlassian.net/browse/CC-4122?atlOrigin=eyJpIjoiYjg0ZDg2ZjBlODcxNGE1YmE0YTQyMmUwMWE3Mjg0OGQiLCJwIjoiaiJ9
=> Add links to Connect to Your Cluster video walkthrough

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v20.1.16.md
=> v20.1.16 Release Notes

v20.2/use-cloud-storage-for-bulk-operations.md, v21.1/use-cloud-storage-for-bulk-operations.md
Added a note on TLS encryption for in transit and at rest following the cloud storage options table.
Closes #4699
=> Added note on TLS encryption

_includes/sidebar-data-v21.1.json, _includes/v21.1/sql/generated/diagrams/alter_database_drop_region.html, _includes/v21.1/sql/generated/diagrams/alter_database_primary_region.html, _includes/v21.1/sql/generated/diagrams/create_database.html, _includes/v21.1/sql/multiregion-example-setup.md, v21.1/add-region.md, v21.1/alter-database.md, v21.1/configure-zone.md, v21.1/create-database.md, v21.1/drop-region.md, v21.1/multiregion-overview.md, v21.1/set-primary-region.md, v21.1/sql-statements.md
Fixes https://github.com/cockroachdb/docs/issues/9309.
Fixes https://github.com/cockroachdb/docs/issues/10052.
Fixes https://github.com/cockroachdb/docs/issues/9601.
Fixes https://github.com/cockroachdb/docs/issues/10370.
Fixes https://github.com/cockroachdb/docs/issues/9299.
Fixes https://github.com/cockroachdb/docs/issues/10072.
Fixes https://github.com/cockroachdb/docs/issues/9300.
Fixes https://github.com/cockroachdb/docs/issues/9117.
Fixes https://github.com/cockroachdb/docs/issues/10303.
Fixes https://github.com/cockroachdb/docs/issues/10075.
Fixes https://github.com/cockroachdb/docs/issues/10257.
Fixes https://github.com/cockroachdb/docs/issues/10109.
Fixes https://github.com/cockroachdb/docs/issues/9557.
=> Multi-region SQL docs for CREATE/ALTER DATABASE

_includes/v21.1/sql/shell-commands.md
Fixes https://github.com/cockroachdb/docs/issues/9133.
Fixes https://github.com/cockroachdb/docs/issues/9134.
Fixes https://github.com/cockroachdb/docs/issues/9135.
Fixes https://github.com/cockroachdb/docs/issues/9136
=> New client-side commands in v21.1

cockroachcloud/quickstart.md
Closes https://cockroachlabs.atlassian.net/browse/CC-4219?atlOrigin=eyJpIjoiMDJjYTUxNjJmMjM4NDY3NGI3MWEwNTIzOWNhZjQyYWIiLCJwIjoiaiJ9
Accidentally left Mac steps in before.
=> Quickstart: Correct Linux Install Steps

releases/release-support-policy.md
=> Internationalize the EOL dates

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v20.2.10.md
Fixes #10563.
This release is scheduled for 5/17.
=> v20.2.10 release notes

api/api-spec.json, api/cluster/v2.md, netlify/build
Preview @ https://deploy-preview-10593--cockroachdb-docs.netlify.app/docs/api/cluster/v2
=> Edits to API spec and drop most displayed request languages

_redirects
Also remove old redirects that shouldn't be needed anymore.
=> Add redirect link for homebrew node startup message

v20.2/cockroach-workload.md, v20.2/performance.md, v21.1/cockroach-workload.md, v21.1/performance.md
=> Fix busted external links to TPC-C spec

v21.1/refresh.md
=> Update materialized view required privileges

_includes/v21.1/sql/privileges.md
Closes #10079
Update to the include `_includes/v21.1/sql/privileges.md` updates the table in:
https://deploy-preview-10608--cockroachdb-docs.netlify.app/docs/v21.1/authorization.html
https://deploy-preview-10608--cockroachdb-docs.netlify.app/docs/v21.1/grant.html
https://deploy-preview-10608--cockroachdb-docs.netlify.app/docs/v21.1/revoke.html
=> Add new connect privilege

_includes/footer.html
=> remove link to whats new

_config_base.yml
=> exclude v1

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v21.1.1.md
Fixes https://github.com/cockroachdb/docs/issues/10565.
=> 21.1.1 release notes

_includes/v21.1/known-limitations/cdc.md, releases/v21.1.0.md, v21.1/create-changefeed.md, v21.1/known-limitations.md, v21.1/stream-data-out-of-cockroachdb-using-changefeeds.md
Added note in releases doc, `CREATE CHANGEFEED` kafka section, and streaming docs. 
@stevendanna let me know if you feel more detail is needed here! Thanks
Closes #10597
=> Included note on cdc kafka version incompatibility

Gemfile, Gemfile.lock, _config_base.yml, sitemap.xml
=> Generate sitemap that excludes all versions except stable

v20.2/sql-playground.md, v21.1/sql-playground.md
=> Add more explicit guidance on accessing the DB Console

cockroachcloud/index.md
Change the video (and card text) to be more current & professional looking.
Could be revisited in future if a better fit is found.
Closes https://cockroachlabs.atlassian.net/browse/CC-4246?atlOrigin=eyJpIjoiNmYxYTFlMzdmZTYxNGU1N2E3MDc2NWI1OWE3OWNjZjUiLCJwIjoiaiJ9
=> Update CC landing page video

v20.2/foreign-key.md, v21.1/foreign-key.md
Background: https://github.com/cockroachdb/cockroach/pull/50771#issuecomment-849701585
=> Columns referenced by FK do not need to be indexed

v21.1/logging-use-cases.md
=> document runtime_stats logging event

_data/releases-cc.yml, _includes/sidebar-data-cockroachcloud.json, releases/cockroachcloud-06072021.md
Closes: https://cockroachlabs.atlassian.net/browse/CC-3666
=> CC Release Notes June 2021

cockroachcloud/create-your-cluster.md, cockroachcloud/network-authorization.md
Closes: 
https://cockroachlabs.atlassian.net/browse/CC-3821
https://cockroachlabs.atlassian.net/browse/CC-4282
https://cockroachlabs.atlassian.net/browse/CC-3939
=> VPC peering/privatelink clarifications

v20.2/build-a-go-app-with-cockroachdb.md, v21.1/build-a-go-app-with-cockroachdb.md
Background: https://cockroachlabs.atlassian.net/browse/CC-4073
=> Updated pgx tutorial with cockroachcloud branch references

v20.2/connection-pooling.md, v21.1/cockroach-workload.md, v21.1/connection-pooling.md
=> Pulling out overhead info from PgBouncer docs into the main section.

_includes/v20.2/prod-deployment/insecure-initialize-cluster.md, _includes/v20.2/prod-deployment/secure-initialize-cluster.md, _includes/v21.1/prod-deployment/insecure-initialize-cluster.md, _includes/v21.1/prod-deployment/secure-initialize-cluster.md, v20.2/cockroach-init.md, v20.2/demo-replication-and-rebalancing.md, v20.2/performance-benchmarking-with-tpcc-large.md, v20.2/performance-benchmarking-with-tpcc-medium.md, v20.2/performance-benchmarking-with-tpcc-small.md, v20.2/secure-a-cluster.md, v20.2/start-a-local-cluster.md, v21.1/cockroach-init.md, v21.1/demo-replication-and-rebalancing.md, v21.1/performance-benchmarking-with-tpcc-large.md, v21.1/performance-benchmarking-with-tpcc-medium.md, v21.1/performance-benchmarking-with-tpcc-small.md, v21.1/secure-a-cluster.md, v21.1/start-a-local-cluster.md
=> clarify cockroach init usage

releases/cockroachcloud-06072021.md
=> June release notes amendment

_redirects
Reference: https://docs.google.com/spreadsheets/d/1rFlSdkgy8AjAQAWbBzxPVmdjwZ-FDbVR5_ShWfn55hs/edit#gid=1520542423
=> Add redirects to prevent common 404s

v21.1/community-tooling.md
SchemaHero is a Kubernetes-native implementation of declarative database schema management.
=> add SchemaHero as a 3rd-party tool

v21.1/cockroach-start.md
=> Fix typo on cockroach-start.html

releases/v20.2.11.md, scripts/issues_from_release_notes.py
Also fix error in issue generation script. Will port to
ed-tools repo as well.
=> Tag v20.2.11 release notes for docs issue generation

jekyll-algolia-dev/lib/jekyll/algolia/indexer.rb
Per [this style thread](https://cockroachlabs.slack.com/archives/C01NFCXULTX/p1623339933001700).
Also fixes a missing synonym from the "technical advisory" array.
=> Add synonym for PostgreSQL and Postgres

_includes/sidebar-data-cockroachcloud.json, cockroachcloud/free-faqs.md, cockroachcloud/frequently-asked-questions.md
Also change the CC FAQ UX so that it feels like a single FAQ
page with CC and CC Free options.
=> Clarify that enterprise features are available with CC

cockroachcloud/console-access-management.md
closes https://cockroachlabs.atlassian.net/browse/CC-4379
=> Add authorization info for cc sql users

_includes/v20.1/misc/tooling.md, _includes/v20.2/misc/tooling.md, cockroachcloud/alerts-page.md, cockroachcloud/deploy-a-python-to-do-app-with-flask-kubernetes-and-cockroachcloud.md, v19.1/cockroach-workload.md, v19.1/encryption.md, v19.2/cockroach-workload.md, v19.2/collate.md, v19.2/performance.md, v2.1/cockroach-workload.md, v2.1/encryption.md, v20.1/build-a-python-app-with-cockroachdb.md, v20.1/cockroach-workload.md, v20.1/collate.md, v20.1/performance.md, v20.2/build-a-c++-app-with-cockroachdb.md, v20.2/collate.md, v20.2/developer-guide-overview.md, v20.2/migrate-from-geopackage.md, v21.1/build-a-c++-app-with-cockroachdb.md, v21.1/collate.md, v21.1/developer-guide-overview.md, v21.1/migrate-from-geopackage.md
The nightly run paniced due to one malformed
link, so in additional to fixing some links,
this PR should let the link checker run to
completion.
=> Fix more broken external links

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v21.1.3.md
=> Release notes for v21.1.3

_includes/v21.1/known-limitations/cdc.md
Enterprise changefeeds are currently disabled for CockroachCloud Free Tier - added a known limitation
=> Added known limitations for CDC on Free Tier

v19.1/create-security-certificates-custom-ca.md, v19.2/create-security-certificates-custom-ca.md, v2.1/create-security-certificates-custom-ca.md, v20.1/create-security-certificates-custom-ca.md, v20.2/create-security-certificates-custom-ca.md, v21.1/create-security-certificates-custom-ca.md
=> Fix error in custom CA cert doc

cockroachcloud/connect-to-a-free-cluster.md, cockroachcloud/connect-to-your-cluster.md
Closes https://cockroachlabs.atlassian.net/browse/CC-4378
=> Clarify sslmode=require warning

cockroachcloud/production-checklist.md
https://cockroachlabs.atlassian.net/browse/CC-4284
=> CC application retry logic

cockroachcloud/frequently-asked-questions.md
Update that users can add nodes through the console.
=> CC FAQ Update

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v21.1.4.md, releases/v21.1.5.md
=> Add release notes for v21.1.4, v21.1.5

v21.1/geoserver.md
This is available as of v21.1.4.
=> geoserver: remove "on the fly" simplification recommendation

cockroachcloud/free-faqs.md
https://cockroachlabs.atlassian.net/browse/CC-4586
=> Add call to action in CC Free FAQs

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v20.2.13.md
=> Add release notes for v20.2.13

cockroachcloud/create-your-cluster.md
From C5 to M5
https://cockroachlabs.atlassian.net/browse/CC-4613
=> Update AWS machine type

cockroachcloud/cluster-management.md
to Cluster Management
https://cockroachlabs.atlassian.net/browse/CC-4612
=> Add Upgrade major version action

_includes/cockroachcloud/download-the-cert-free.md, _includes/cockroachcloud/download-the-cert.md, cockroachcloud/connect-to-your-cluster.md, cockroachcloud/quickstart.md
https://cockroachlabs.atlassian.net/browse/CC-4538
=> CC Connect improvements

v20.2/community-tooling.md, v21.1/community-tooling.md
Related to https://github.com/cockroachdb/docs/issues/10222.
=> Added PGBouncer to list of community-supported tools

v20.1/foreign-key.md, v20.2/foreign-key.md, v21.1/foreign-key.md
Fixes https://github.com/cockroachdb/docs/issues/10859.
=> Added Foreign Key marketing content to Foreign Key docs page

_includes/sidebar-data-v20.2.json, _includes/sidebar-data-v21.1.json, _includes/v20.2/misc/tooling.md, _includes/v21.1/misc/tooling.md, v20.2/alembic.md, v21.1/alembic.md
Fixes #10816 
Related to https://github.com/cockroachlabs/simple-crud-python-sqlalchemy/pull/6
=> Alembic support and tutorial

v20.2/create-changefeed.md
Closes #10852 
Added the two backported options
=> Options added to 20.2 create-changefeed

v20.2/build-a-python-app-with-cockroachdb-sqlalchemy.md, v21.1/build-a-python-app-with-cockroachdb-sqlalchemy.md
Follow-up on https://github.com/cockroachdb/docs/pull/10959
=> Added missing cached includes to SQLAlchemy sample app tutorial

v20.2/install-cockroachdb-spatial.md, v21.1/install-cockroachdb-spatial.md
=> Remove unused spatial install files

_includes/sidebar-data-v21.1.json, _includes/v21.1/sql/generated/diagrams/show_full_scans.html, v19.2/sql-statements.md, v20.1/sql-statements.md, v20.2/sql-statements.md, v21.1/show-full-table-scans.md, v21.1/sql-statements.md
Fixes https://github.com/cockroachdb/docs/issues/10745.
@kevin-v-ngo
=> SHOW FULL TABLE SCANS

_includes/sidebar-data-v20.2.json, _includes/sidebar-data-v21.1.json, v20.2/build-a-go-app-with-cockroachdb.md, v20.2/build-a-python-app-with-cockroachdb-sqlalchemy.md, v20.2/example-apps.md, v20.2/hello-world-go-pgx.md, v20.2/hello-world-python-sqlalchemy.md, v21.1/build-a-go-app-with-cockroachdb.md, v21.1/example-apps.md, v21.1/hello-world-go-pgx.md
Follow-up on https://github.com/cockroachdb/docs/pull/10851.
- Added new hello world tutorial
- Updated existing example to tutorial to fit refactor template
Related to https://github.com/cockroachlabs/hello-world-go-pgx/commit/b15a222556b9e80610973af9cb7fa14251927e0d and https://github.com/cockroachlabs/example-app-go-pgx/pull/4
After this is approved, I'll propagate to 20.2 docs, merge https://github.com/cockroachlabs/example-app-go-pgx/pull/4, and then merge this PR.
=> Refactored golang-pgx sample app

v20.1/build-a-spring-app-with-cockroachdb-jdbc.md, v20.1/build-a-spring-app-with-cockroachdb-jpa.md, v20.2/build-a-spring-app-with-cockroachdb-jdbc.md, v20.2/build-a-spring-app-with-cockroachdb-jpa.md, v21.1/build-a-spring-app-with-cockroachdb-jdbc.md, v21.1/build-a-spring-app-with-cockroachdb-jpa.md
Background: https://cockroachlabs.slack.com/archives/C01PHNMUFLN/p1627479643126200
=> Updated app servlet port in spring apps to match source code

v19.1/build-a-java-app-with-cockroachdb.md, v19.2/build-a-java-app-with-cockroachdb.md, v20.1/build-a-java-app-with-cockroachdb.md, v20.2/build-a-java-app-with-cockroachdb.md, v21.1/build-a-java-app-with-cockroachdb.md
Updating includes/links following name change to sample app repos
=> Updated repo name for JDBC sample apps

_includes/sidebar-data-v20.2.json, _includes/sidebar-data-v21.1.json, v20.2/build-a-java-app-with-cockroachdb.md, v20.2/example-apps.md, v20.2/hello-world-java-jdbc.md, v21.1/build-a-java-app-with-cockroachdb.md, v21.1/example-apps.md, v21.1/hello-world-java-jdbc.md
Follow-up on https://github.com/cockroachdb/docs/pull/10851.
- Added new hello world tutorial
- Updated existing example to tutorial to fit refactor template
Related to https://github.com/cockroachlabs/hello-world-java-jdbc/commit/7303bd2007bb8286f8bb259b8ca23eb8e65757e6 and https://github.com/cockroachlabs/example-app-java-jdbc/pull/5
After this is approved, I'll propagate to 20.2 docs, and then merge this PR.
=> JDBC sample app refactor

cockroachcloud/create-your-cluster.md
Closes https://cockroachlabs.atlassian.net/browse/CC-4381
Linking out to relevant docs for GCP and AWS disks.
=> Add CC Disk Performance info

cockroachcloud/free-faqs.md, cockroachcloud/frequently-asked-questions.md
https://cockroachlabs.atlassian.net/browse/CC-4682
=> Remove CC Free Beta FAQ backup/import limitations

v21.1/known-limitations.md
Fixes #10993 
Fixes #10997 
Adding known issues for virtual computed columns and multi-region tables in v21.1.
=> Add known issues to 21.1 for virtual computed columns.

v20.1/cluster-setup-troubleshooting.md, v20.2/cluster-setup-troubleshooting.md, v21.1/cluster-setup-troubleshooting.md
Fixes #10921
Related:
- #10917
=> Add docs on how slow user/pass auth can happen

_includes/v20.2/orchestration/start-cockroachdb-operator-secure.md, _includes/v21.1/orchestration/start-cockroachdb-operator-secure.md, v21.1/deploy-cockroachdb-with-kubernetes-openshift.md
Fixes https://github.com/cockroachdb/cockroach-operator/issues/647
=> document Operator crash + workaround

v20.1/configure-replication-zones.md, v20.1/configure-zone.md, v20.2/configure-replication-zones.md, v20.2/configure-zone.md, v21.1/configure-replication-zones.md, v21.1/configure-zone.md
=> correct zone config privileges

_includes/sidebar-data-v20.2.json, _includes/sidebar-data-v21.1.json, v21.1/cockroach-demo.md, v21.1/ui-cluster-overview-page.md, v21.1/ui-databases-page.md, v21.1/ui-jobs-page.md, v21.1/ui-overview-dashboard.md, v21.1/ui-runtime-dashboard.md
Fixes #9147
Fixes #10668
Fixes #10837 
Fixes #9758
Fixes #9647
Fixes #9164
=> various DB Console release updates

v21.1/topology-follow-the-workload.md
=> FTW is not available with MR abstractions enabled

_data/releases-cc.yml, _includes/sidebar-data-cockroachcloud.json, releases/cockroachcloud-08092021.md
https://cockroachlabs.atlassian.net/browse/CC-3668
=> August release notes for CC

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v21.1.7.md
Fixes https://github.com/cockroachdb/docs/issues/10714.
Related to https://github.com/cockroachdb/cockroach/issues/68428.
=> v21.1.7 release notes

_includes/sidebar-data-v21.1.json, _includes/sidebar-data-v21.2.json, v21.1/data-domiciling.md, v21.2/data-domiciling.md
=> Add vetted docs re: how to do data domiciling

_includes/sidebar-data-v21.1.json, v21.1/build-a-nodejs-app-with-cockroachdb.md, v21.1/example-apps.md, v21.1/hello-world-node-postgres.md
Follow-up on https://github.com/cockroachdb/docs/pull/10851.
- Added new hello world tutorial
- Updated existing example to tutorial to fit refactor template
Related to https://github.com/cockroachlabs/hello-world-node-pg/pull/2.
=> Refactored node-postgres example app

_includes/sidebar-data-v21.1.json, _includes/v21.1/sql/generated/diagrams/reassign_owned_by.html, v21.1/reassign-owned.md, v21.1/sql-statements.md
Fixes https://github.com/cockroachdb/docs/issues/10862.
=> REASSIGN OWNED

_includes/sidebar-data-v21.2.json, _includes/v21.2/sql/generated/diagrams/reassign_owned_by.html, v21.2/reassign-owned.md, v21.2/sql-statements.md
Follow-up on https://github.com/cockroachdb/docs/pull/11014.
=> Added REASSIGN OWNED to 21.2 docs

_includes/v20.2/sql/statement-bundle-warning.md, _includes/v21.1/sql/statement-bundle-warning.md, _includes/v21.2/sql/statement-bundle-warning.md, v20.2/explain-analyze.md, v20.2/ui-statements-page.md, v21.1/explain-analyze.md, v21.1/ui-statements-page.md, v21.2/explain-analyze.md, v21.2/ui-statements-page.md
=> Add warning about statement bundles containing sensitive data.

v19.1/sql-faqs.md, v19.2/sql-faqs.md, v2.0/sql-faqs.md, v2.1/sql-faqs.md, v20.1/sql-faqs.md, v20.2/sql-faqs.md, v21.1/sql-faqs.md, v21.2/sql-faqs.md
Fixes https://github.com/cockroachdb/docs/issues/11079.
=> Updated SQL JOIN FAQ answer

releases/v21.1.0-alpha.1.md, v21.1/cockroach-sql.md, v21.2/cockroach-sql.md
Follow-up on https://cockroachlabs.slack.com/archives/C01PHNMUFLN/p1629387979024400.
=> Fixed incorrect cockroach command --input-file flag

_includes/sidebar-data-v20.2.json, _includes/sidebar-data-v21.1.json, _includes/sidebar-data-v21.2.json, v20.2/deploy-app-gcr.md, v21.1/deploy-app-gcr.md, v21.2/deploy-app-gcr.md
Fixes https://github.com/cockroachdb/docs/issues/11020.
I'll update the existing deployment steps in https://www.cockroachlabs.com/docs/stable/movr-flask-deployment.html#global-application-deployment to use private IPs in a separate PR.
=> Google Cloud Run tutorial

_includes/cockroachcloud/cc-cert-expire.md, cockroachcloud/connect-to-a-free-cluster.md, cockroachcloud/troubleshooting-page.md
Closes https://cockroachlabs.atlassian.net/browse/CC-4790
=> CC Free Cert Expiration

_includes/v20.2/cdc/configure-all-changefeed.md, _includes/v21.1/cdc/configure-all-changefeed.md, v20.2/create-changefeed.md, v20.2/stream-data-out-of-cockroachdb-using-changefeeds.md, v21.1/create-changefeed.md, v21.1/import-into.md, v21.1/stream-data-out-of-cockroachdb-using-changefeeds.md
Closes #10995 
Added a section to the configure changefeeds sections for the main cdc page & `CREATE CHANGEFEED` page. 
Documents the SQL syntax to pause and then resume ALL changefeed jobs.
=> Section on pause all/resume all changefeeds

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v20.2.15.md
=> v20.2.15 release notes

_includes/sidebar-data-v20.2.json, _includes/sidebar-data-v21.2.json, _includes/v20.2/app/init-bank-sample.md, _includes/v21.1/app/init-bank-sample.md, _includes/v21.2/app/init-bank-sample.md, v20.2/build-a-nodejs-app-with-cockroachdb.md, v20.2/example-apps.md, v20.2/hello-world-node-postgres.md, v21.1/build-a-nodejs-app-with-cockroachdb.md, v21.2/build-a-nodejs-app-with-cockroachdb.md, v21.2/example-apps.md, v21.2/hello-world-node-postgres.md
Follow-up on https://github.com/cockroachdb/docs/pull/11003, https://cockroachlabs.slack.com/archives/CBE9QQC4S/p1629564477159100
=> Updated db initialization workflow, copied to 20.2, 21.2

v21.1/deploy-app-gcr.md
Follow-up on internal email thread.
=> Updated GCR tutorial to use CLI commands instead of the web UI

v20.2/deploy-app-gcr.md, v21.1/deploy-app-gcr.md, v21.2/deploy-app-gcr.md
Follow-up of https://github.com/cockroachdb/docs/pull/11117
=> Copied GCR tutorial updates to 20.2, 21.2; added more terms to summary for SEO

v20.2/manage-long-running-queries.md, v21.1/manage-long-running-queries.md, v21.2/manage-long-running-queries.md
=> Add example of canceling multiple queries.

_includes/v21.1/computed-columns/virtual.md, _includes/v21.2/computed-columns/virtual.md, v20.2/jsonb.md, v21.1/jsonb.md, v21.2/jsonb.md
Adding examples per CRDB-2417.
=> Add parse_timestamp info to JSONB docs.

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v21.1.8.md
=> v21.1.8 Release Notes

_data/advisories.yml, _includes/sidebar-releases.json
- Add code-formatting to tech advisory summaries
- Highlight advisory section of sidenav when an advisory is viewed
=> Tech advisory formatting fix

_data/advisories.yml, _data/releases.yml, advisories/a69874.md, releases/v21.1.8.md
=> Technical advisory 69874 (urgent) (wait on timing for merge)

_includes/v19.2/start-in-docker/mac-linux-steps.md, _includes/v20.1/start-in-docker/mac-linux-steps.md, _includes/v20.2/start-in-docker/mac-linux-steps.md, _includes/v21.1/start-in-docker/mac-linux-steps.md, _includes/v21.2/start-in-docker/mac-linux-steps.md, v19.2/secure-a-cluster.md, v19.2/start-a-local-cluster-in-docker-windows.md, v19.2/start-a-local-cluster.md, v20.1/secure-a-cluster.md, v20.1/start-a-local-cluster-in-docker-windows.md, v20.1/start-a-local-cluster.md, v20.2/secure-a-cluster.md, v20.2/start-a-local-cluster-in-docker-windows.md, v20.2/start-a-local-cluster.md, v21.1/secure-a-cluster.md, v21.1/start-a-local-cluster-in-docker-windows.md, v21.1/start-a-local-cluster.md, v21.2/secure-a-cluster.md, v21.2/start-a-local-cluster-in-docker-windows.md, v21.2/start-a-local-cluster.md
=> Add missing word in local cluster tutorials

v21.1/install-client-drivers.md
Hi, I have fixed a typo in a sentence.
=> Fixed a typo

_includes/sidebar.js.html, v20.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md, v20.2/authorization.md, v20.2/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md, v21.1/auto-tls.md, v21.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md, v21.2/auto-tls.md, v21.2/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
Made corrections to the typos i found in the documentations.
=> Fix typos in docs

cockroachcloud/cluster-management.md
https://cockroachlabs.atlassian.net/browse/CC-4888
https://cockroachlabs.atlassian.net/browse/CC-4831
Update that users can scale clusters up and down but cannot go from multi-node to single-node.
Add a callout that contract customers need to contact support to scale.
=> Update cluster scaling callouts

v21.1/sql-feature-support.md
Fixes https://github.com/cockroachdb/docs/issues/10689.
=> Change stored proc support from Planned to X.

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v20.2.16.md
=> v20.2.16 release notes

v20.2/known-limitations.md, v21.1/known-limitations.md, v21.2/known-limitations.md
=> Removing notice about index use for OR.

v20.2/connect-to-the-database.md, v21.1/connect-to-the-database-cockroachcloud.md, v21.1/connect-to-the-database.md, v21.2/connect-to-the-database.md
was accidentally deleted while switching to product name variables
=> Replace missing close tag

_includes/sidebar-data-v20.2.json, _includes/sidebar-data-v21.1.json, _includes/sidebar-data-v21.2.json, v19.1/build-a-go-app-with-cockroachdb-gorm.md, v19.2/build-a-go-app-with-cockroachdb-gorm.md, v20.1/build-a-go-app-with-cockroachdb-gorm.md, v20.2/build-a-go-app-with-cockroachdb-gorm.md, v20.2/example-apps.md, v20.2/hello-world-go-gorm.md, v21.1/build-a-go-app-with-cockroachdb-gorm.md, v21.1/example-apps.md, v21.1/hello-world-go-gorm.md, v21.1/hello-world-go-pgx.md, v21.2/build-a-go-app-with-cockroachdb-gorm.md, v21.2/example-apps.md, v21.2/hello-world-go-gorm.md, v21.2/hello-world-go-pgx.md
Fixes https://github.com/cockroachdb/docs/issues/4207
Fixes https://github.com/cockroachdb/docs/issues/8683
Fixes https://github.com/cockroachdb/docs/issues/8228
This PR updates the existing GORM tutorial to match the refactored sample app now located at https://github.com/cockroachlabs/example-app-go-gorm. It also includes a sample tutorial for the new Hello World app located at https://github.com/cockroachlabs/hello-world-go-gorm.
=> Gorm refactor

_includes/cockroachcloud/postgresql-special-characters.md, cockroachcloud/connect-to-a-free-cluster.md, cockroachcloud/connect-to-your-cluster.md, cockroachcloud/deploy-a-python-to-do-app-with-flask-kubernetes-and-cockroachcloud.md, cockroachcloud/quickstart-trial-cluster.md, cockroachcloud/quickstart.md
https://cockroachlabs.atlassian.net/browse/CC-4772
=> postgresql special character warning

releases/v21.1.7.md, v20.2/cost-based-optimizer.md, v21.1/cost-based-optimizer.md
Apply changes to the v21.1 and v20.2 versions of cost-based-optimizer.md made in 21.2 version in #11707.
=> Propagate fixes in #11707.

v20.2/cluster-setup-troubleshooting.md, v20.2/operational-faqs.md, v21.1/cluster-setup-troubleshooting.md, v21.1/operational-faqs.md, v21.2/cluster-setup-troubleshooting.md, v21.2/operational-faqs.md
Fixes #11245.
Also updated and streamlined the rest of the Operational FAQs.
=> update Operational FAQs

v21.1/migrate-from-csv.md
Migrate from CSV links to Cloud and Local File Server but not to User File
=> ADHOC: Add link to user file for bulk operation

v20.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md, v20.2/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md, v21.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
Backport the fix from  #11225.
=> fix EKS multi-region manifest links

v1.1/architecture/transaction-layer.md, v19.1/architecture/transaction-layer.md, v2.0/architecture/transaction-layer.md, v2.1/architecture/transaction-layer.md
=> Clarify two-phase transaction protocol

v20.2/recommended-production-settings.md, v21.1/recommended-production-settings.md, v21.2/recommended-production-settings.md
=> update Systemd guidance for file descriptors limit

v21.2/set-locality.md
Port to v21.2 of the changes from #10994
=> REGIONAL BY ROW column cannot be nullable

_includes/v21.2/misc/interleave-deprecation-note.md, v21.1/sql-feature-support.md, v21.2/sql-feature-support.md
Fixes https://github.com/cockroachdb/docs/issues/10689 in 21.2.
=> Propagate lack of stored proc support to 21.2.

v20.2/spatial-data.md, v21.1/spatial-data.md, v21.2/spatial-data.md
=> Fix bugs/typos in 'Working with Spatial Data'

cockroachcloud/free-faqs.md
Closes #11726 
Update to the Free tier FAQ page re core changefeeds **are** available.
=> Update to Free Tier FAQs on changefeeds

_includes/sidebar-data-v20.2.json, _includes/sidebar-data-v21.1.json, _includes/sidebar-data-v21.2.json, v20.2/cancel-session.md, v20.2/common-table-expressions.md, v21.1/cancel-session.md, v21.1/common-table-expressions.md, v21.2/cancel-session.md, v21.2/common-table-expressions.md
Related to https://github.com/cockroachdb/docs/pull/8850, https://github.com/cockroachdb/docs/pull/8834.
Fixes https://github.com/cockroachdb/docs/issues/4477.
=> Community edits

v21.1/cluster-setup-troubleshooting.md, v21.2/cluster-setup-troubleshooting.md
=> Add docs on disk stalls (impact/mitigation)

_data/releases-cc.yml, _includes/sidebar-data-cockroachcloud.json, releases/cockroachcloud-10042021.md
https://cockroachlabs.atlassian.net/browse/CC-3670
=> CC October release notes

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v21.2.0-beta.3.md
=> Add release notes for v21.2.0-beta.3

_includes/v20.2/cdc/create-core-changefeed-avro.md, _includes/v21.1/cdc/create-core-changefeed-avro.md, _includes/v21.2/cdc/create-core-changefeed-avro.md, v20.2/stream-data-out-of-cockroachdb-using-changefeeds.md, v21.1/stream-data-out-of-cockroachdb-using-changefeeds.md, v21.2/stream-data-out-of-cockroachdb-using-changefeeds.md
Continuing Abbey's PR #9906 adding updates to v21.1 and v20.2 to update
=> Updates to Confluent start/stop command 

_includes/v20.2/metric-names.md, _includes/v21.1/metric-names.md, _includes/v21.2/metric-names.md
=> Updated metric descriptions

_includes/v21.2/sql/generated/diagrams/alter_role.html, v21.2/alter-database.md, v21.2/alter-role.md
Fixes https://github.com/cockroachdb/docs/issues/11390.
Fixes https://github.com/cockroachdb/docs/issues/11249.
Fixes https://github.com/cockroachdb/docs/issues/11438.
Fixes https://github.com/cockroachdb/docs/issues/11437.
=> ALTER ROLE SET

v19.1/build-a-java-app-with-cockroachdb-hibernate.md, v19.2/build-a-java-app-with-cockroachdb-hibernate.md, v20.1/build-a-java-app-with-cockroachdb-hibernate.md, v20.1/build-a-nodejs-app-with-cockroachdb-sequelize.md, v20.2/build-a-java-app-with-cockroachdb-hibernate.md, v20.2/build-a-nodejs-app-with-cockroachdb-sequelize.md, v20.2/build-a-ruby-app-with-cockroachdb-activerecord.md, v21.1/build-a-java-app-with-cockroachdb-hibernate.md, v21.1/build-a-nodejs-app-with-cockroachdb-sequelize.md, v21.1/build-a-ruby-app-with-cockroachdb-activerecord.md, v21.2/build-a-java-app-with-cockroachdb-hibernate.md, v21.2/build-a-nodejs-app-with-cockroachdb-sequelize.md, v21.2/build-a-ruby-app-with-cockroachdb-activerecord.md
https://github.com/cockroachlabs/example-app-java-hibernate
https://github.com/cockroachlabs/example-app-node-sequelize
https://github.com/cockroachlabs/example-app-ruby-activerecord
=> Updated Hibernate, Sequelize, ActiveRecord sample repo names

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v21.2.0-rc.3.md
=> Add v21.2.0-rc.3 release notes

v21.2/alter-role.md, v21.2/reassign-owned.md
Fixes https://github.com/cockroachdb/docs/issues/11209.
Fixes https://github.com/cockroachdb/docs/issues/11400.
=> Updated ALTER ROLE and REASSIGN OWNED privileges

v21.2/string.md
Fixes https://github.com/cockroachdb/docs/issues/11351.
=> Documented "char" type

v21.1/sql-tuning-with-explain.md, v21.2/sql-tuning-with-explain.md
=> Fix formatting bug.

_includes/v21.2/misc/session-vars.html
=> Add new guardrails to session vars.

v20.2/string.md, v20.2/uuid.md, v21.1/string.md, v21.1/uuid.md, v21.2/string.md, v21.2/uuid.md
Fixes https://github.com/cockroachdb/docs/issues/11306.
=> Updated UUID input format/examples

cockroachcloud/cluster-overview-page.md
https://cockroachlabs.atlassian.net/browse/CC-5303
=> Remove transaction retries from cluster overview page

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v20.2.18.md
=> add v20.2.18 release notes

v21.2/cockroach-workload.md, v21.2/ui-statements-page.md
https://cockroachlabs.atlassian.net/browse/CRDB-6565
=> Add search filters.

_includes/common/transaction-retries.md, cockroachcloud/production-checklist.md, v21.2/recommended-production-settings.md
This PR pulls the transaction retries checklist item into an include in a new common directory and adds conditionals to handle links.
=> Add transaction retries to Dedicated production checklist

v21.2/set-locality.md, v21.2/ui-sessions-page.md
Fixes #11214
Fixes #11454
Fixes #11212
Depends on a link that will exist once we merge #12035
=> Add docs for auto-rehoming of RBR tables

_includes/v21.2/sql/jsonb-comparison.md, v21.2/jsonb.md, v21.2/known-limitations.md
=> Add JSONB comparison operator known limitation

releases/index.md
=> Fix bugs in releases table.

v21.2/known-limitations.md
Change approved in another draft PR: https://github.com/cockroachdb/docs/pull/12160/files#r741972604
=> Remove resolved limitations for inverted index scans

v21.2/architecture/admission-control.md
=> Add alert about completing upgrade before enabling admission control.

_includes/v21.2/sql/cannot-refresh-materialized-views-inside-transactions.md, v21.2/known-limitations.md, v21.2/views.md
=> Cannot refresh materialized views in explicit txns

_includes/v21.2/sql/expressions-as-on-conflict-targets.md, v21.2/expression-indexes.md, v21.2/known-limitations.md
=> Cannot use expressions as ON CONFLICT targets

v21.2/create-table.md
Fixes https://github.com/cockroachdb/docs/issues/11380.
=> CREATE TABLE LIKE copies hidden columns

v21.2/create-database.md, v21.2/show-create.md, v21.2/sql-statements.md
Fixes https://github.com/cockroachdb/docs/issues/11343.
=> SHOW CREATE DATABASE

_includes/v20.2/cdc/configure-all-changefeed.md, _includes/v21.1/cdc/configure-all-changefeed.md, _includes/v21.1/userfile-examples/backup-userfile.md, _includes/v21.1/userfile-examples/import-into-userfile.md, v21.1/cockroach-userfile-upload.md
=> Hardcoded links for bulk/cdc includes

_includes/v21.1/performance/statement-contention.md
Fixes #12269.
Relates to https://github.com/cockroachdb/cockroach/issues/72700.
=> Fix manual contended index view create statement in v21.1.

_includes/v21.1/sql/limit-row-size.md, _includes/v21.2/sql/limit-row-size.md, v21.1/insert-data.md, v21.1/update.md, v21.1/upsert.md, v21.2/insert-data.md, v21.2/update.md, v21.2/upsert.md
https://cockroachlabs.atlassian.net/browse/CRDB-8657
=> Row size guardrails

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v21.1.12.md
Fixes https://github.com/cockroachdb/docs/issues/10726
=> v21.1.12 release notes

releases/release-support-policy.md
=> Small edit on Release Support Policy

_config_base.yml, v20.1/install-cockroachdb-mac.html, v21.1/install-cockroachdb-mac.html
Also remove homebrew as an option in 21.1 and 20.1.
=> Fix 21.2 download and docker image

v21.1/build-a-python-app-with-cockroachdb.md, v21.1/demo-json-support.md, v21.1/learn-cockroachdb-sql.md, v21.1/spatial-tutorial.md, v21.2/sql-playground.md
Exception: Provide SQL playground for a few older
versions.
=> Use Katacodas on stable docs only

_includes/unsupported-version-soon.md
=> Update Assistance Support deadline

v19.1/cockroachdb-in-comparison.md, v19.2/cockroachdb-in-comparison.md, v20.1/cockroachdb-in-comparison.md, v20.2/cockroachdb-in-comparison.md, v21.1/cockroachdb-in-comparison.md, v21.2/cockroachdb-in-comparison.md
=> Fix RPO for crdb on comparison page

_includes/v21.2/misc/session-vars.html
Fixes https://github.com/cockroachdb/docs/issues/11462.
=> is_superuser session variable

v20.2/foreign-key.md, v21.1/foreign-key.md, v21.2/foreign-key.md
Fixes https://github.com/cockroachdb/docs/issues/11347.
=> Document foreign key column ordering

_includes/v21.1/misc/set-enterprise-license.md, _includes/v21.2/misc/set-enterprise-license.md, v21.1/get-started-with-enterprise-trial.md, v21.1/licensing-faqs.md, v21.2/get-started-with-enterprise-trial.md, v21.2/licensing-faqs.md
- Use include for steps to set a license key, shared
with the enterprise faq.
- Add link to Cockroach University.
Fixes #5934
=> Refresh get started with enterprise trail

_includes/common/ui/statements-page.md, _includes/common/ui/transactions-page.md
Fix https://cockroachlabs.atlassian.net/browse/DOC-1743.
=> Fix for DOC-1743.

v20.2/inverted-indexes.md, v21.1/inverted-indexes.md, v21.2/inverted-indexes.md
Fix https://cockroachlabs.atlassian.net/browse/DOC-1675
=> Fix DOC-1675.

_includes/common/ui/statements-page.md, _includes/common/ui/transactions-page.md
https://cockroachlabs.atlassian.net/browse/DOC-1656
https://cockroachlabs.atlassian.net/browse/DOC-1657
https://cockroachlabs.atlassian.net/browse/DOC-1658
=> Document statement and transaction filter updates.

cockroachcloud/serverless-faqs.md
Added per [conversation on Slack](https://cockroachlabs.slack.com/archives/CUVEFUU3C/p1637629526231500).
=> Add a Serverless FAQ entry about cold start latency.

_includes/v21.2/faq/auto-generate-unique-ids.html, v21.2/performance-best-practices-overview.md, v21.2/uuid.md
From SQL best practices, UUID reference doc, and the SQL FAQ.
=> DOC-1866: Link to UUID blog post

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v21.2.1.md
Closes #10727 
Release notes for extraordinary release 21.2.1
=> Release notes for 21.2.1

CONTRIBUTING.md
- Instruct users to update their `$PATH`
- Add `gem update` before installing Jekyll
@lnhsingh Can you please review? Also is there a PR format I should be following?
=> Updated information for Ruby 3 and included reference to update PATH

cockroachcloud/learn-cockroachdb-sql.md, v1.0/learn-cockroachdb-sql.md, v1.1/learn-cockroachdb-sql.md, v19.1/learn-cockroachdb-sql.md, v19.2/learn-cockroachdb-sql.md, v2.0/learn-cockroachdb-sql.md, v2.1/learn-cockroachdb-sql.md, v20.1/learn-cockroachdb-sql.md, v20.2/learn-cockroachdb-sql.md, v21.1/learn-cockroachdb-sql.md, v21.2/learn-cockroachdb-sql.md
=> Fix typo on "Getting started with CRDB SQL" pages

_includes/cockroachcloud/cockroachcloud-pricing.md, cockroachcloud/create-your-cluster.md
Updated pricing and IOPS to the new configuration.
Added a note that existing clusters will be transitioned automatically by end of December.
Closes https://cockroachlabs.atlassian.net/browse/CC-5412
=> CC Dedicated New Pricing and Machine types

_data/releases-cc.yml, _includes/cockroachcloud/sidebar-release-notes.json, releases/cockroachcloud-12062021.md
Closes https://cockroachlabs.atlassian.net/browse/DOC-2043
=> CC Release Notes December

v21.2/grant.md, v21.2/revoke.md
Fixes https://github.com/cockroachdb/docs/issues/11371.
Related to https://github.com/cockroachdb/cockroach/pull/72928, https://github.com/cockroachdb/generated-diagrams/pull/9.
=> GRANT, REVOKE syntax parameter updates

v21.2/ui-sql-dashboard.md
https://cockroachlabs.atlassian.net/browse/DOC-1932
=> Remove dup heading.

v21.2/cockroach-debug-zip.md
=> RocksDB threads file is no longer in debug zip

_includes/v21.1/misc/session-vars.html, _includes/v21.2/misc/session-vars.html
https://cockroachlabs.atlassian.net/browse/DOC-1826
=> Add txn guardrail session variables.

v20.2/community-tooling.md, v21.1/community-tooling.md, v21.2/community-tooling.md
Follow-up on https://cockroachlabs.slack.com/archives/CPD3ANLMB/p1638922222023300.
Related to #10014.
=> Added JDBI to community tooling page

_includes/cockroachcloud/cockroachcloud-pricing.md
=> Fix GCP pricing for 16vcpu machine

v21.2/sql-tuning-with-explain.md
https://cockroachlabs.atlassian.net/browse/DOC-385
=> Use more realistic example.

releases/v21.2.0.md, v1.0/transactions.md, v1.1/transactions.md, v19.1/transactions.md, v19.2/transactions.md, v2.0/transactions.md, v2.1/transactions.md, v20.1/transactions.md, v20.2/transactions.md, v21.1/transactions.md, v21.2/transactions.md
Also fixes bad link to PDF in [Transactions](https://www.cockroachlabs.com/docs/v21.2/transactions.html).
=> Fixing broken link in v21.2.0 release notes and rewording as the webinar has now passed

v21.1/split-at.md, v21.2/split-at.md
=> Remove SPLIT AT note re: resplitting vs TRUNCATE

v21.2/cluster-setup-troubleshooting.md
=> Guide users to check ballast file exists and works

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v21.2.3.md
Closes https://cockroachlabs.atlassian.net/browse/DOC-1890
=> v21.2.3 Release Notes

v21.2/vectorized-execution.md
https://cockroachlabs.atlassian.net/browse/DOC-1387
=> Remove limitation on window functions.

_includes/v21.1/misc/session-vars.html, _includes/v21.2/misc/session-vars.html
https://cockroachlabs.atlassian.net/browse/DOC-1422
https://cockroachlabs.atlassian.net/browse/DOC-1827
=> large_full_scan_rows session variable

v21.1/cost-based-optimizer.md, v21.2/cost-based-optimizer.md
https://cockroachlabs.atlassian.net/browse/DOC-502
=> Clarify definition of join hint and provide example.

cockroachcloud/billing-management.md, cockroachcloud/run-bulk-operations.md, cockroachcloud/troubleshooting-page.md
https://cockroachlabs.atlassian.net/browse/DOC-1982
Add error and solution for Serverless users with no credit card on file trying to access cloud storage.
Fix some stray capitalization errors.
=> Serverless Cloud Storage Troubleshooting

v21.2/performance-best-practices-overview.md, v21.2/transactions.md
@jseldess Can you review this one instead?
=> Added blog post on database contention to performance docs

_includes/v21.1/metric-names.md
https://cockroachlabs.atlassian.net/browse/DOC-1839
=> Add guardrail metrics to 21.1

v21.2/performance-benchmarking-with-tpcc-large.md, v21.2/performance-benchmarking-with-tpcc-local-multiregion.md, v21.2/performance-benchmarking-with-tpcc-local.md, v21.2/performance-benchmarking-with-tpcc-medium.md, v21.2/performance-benchmarking-with-tpcc-small.md
Addresses the on-prem part of DOC-1487
=> Add docs on running multi-region TPC-C

v21.1/use-cloud-storage-for-bulk-operations.md, v21.2/use-cloud-storage-for-bulk-operations.md
Closes #11674 
Added a warning to S3-compatible services section.
=> Draft of S3-compatible services non testing

cockroachcloud/cluster-management.md
https://cockroachlabs.atlassian.net/browse/DOC-1984
Add note that you can delete a Dedicated cluster at any time to stop charges from accumulating
=> Deleting Dedicated cluster note

_includes/v21.2/misc/session-vars.html, v21.2/cost-based-optimizer.md
https://cockroachlabs.atlassian.net/browse/DOC-2164
=> Fix default for reorder_joins_limit.

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v21.1.13.md
Fixes https://cockroachlabs.atlassian.net/browse/DOC-1882.
=> v21.1.13 release notes

_data/releases-cc.yml, _includes/cockroachcloud/sidebar-release-notes.json, releases/cockroachcloud-01102022.md
Docs nav update is tentatively included
Also waiting for finalization on the Dedicated and Serverless versions (link will be broken for now)
https://cockroachlabs.atlassian.net/browse/DOC-2238
=> Cloud January release notes

_includes/v1.1/orchestration/kubernetes-limitations.md, _includes/v19.1/orchestration/kubernetes-limitations.md, _includes/v19.2/orchestration/kubernetes-limitations.md, _includes/v2.0/orchestration/kubernetes-limitations.md, _includes/v2.1/orchestration/kubernetes-limitations.md, _includes/v20.1/orchestration/kubernetes-limitations.md, _includes/v20.2/orchestration/kubernetes-limitations.md, _includes/v21.1/orchestration/kubernetes-limitations.md, _includes/v21.2/orchestration/kubernetes-limitations.md, v19.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md, v19.2/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md, v2.0/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md, v2.1/orchestrate-cockroachdb-with-kubernetes-multi-cluster.md
=> DOC-1310 update minimum supported K8s version to 1.18

cockroachcloud/cluster-management.md
https://cockroachlabs.atlassian.net/browse/DOC-2289
For scaling a multi-node cluster down to a single-node cluster:
Change “if you need to do this, contact support” to “if you need to do this, take a backup and restore into a new single node cluster.”
=> Fix multi-node scale down callout

v21.2/ui-sql-dashboard.md
https://cockroachlabs.atlassian.net/browse/DOC-2103
=> Define statement contention.

_includes/sidebar-data-cockroach-university.json, v21.2/architecture/overview.md, v21.2/frequently-asked-questions.md
=> Update links to Cockroach U courses

_includes/footer.html, releases/v19.2.0.md
Fixes broken links to CU from footer.
=> Fixing broken link to CU index page.

v21.1/restore.md, v21.2/restore.md
Fixes [DOC-1109](https://cockroachlabs.atlassian.net/browse/DOC-1109)
Clarified that the restorer is the owner of restored objects 21.1/21.2
=> Small clarification that restorer is owner of restored objects

_includes/v21.1/sql/covering-index.md, _includes/v21.2/sql/covering-index.md, v21.1/create-index.md, v21.1/indexes.md, v21.1/schema-design-indexes.md, v21.2/create-index.md, v21.2/indexes.md, v21.2/schema-design-indexes.md
=> Add description of covering indexes

_includes/cockroachcloud/nodes-limitation.md
https://cockroachlabs.atlassian.net/browse/DOC-2305
=> Remove scale up from one node limitation

v21.2/follower-reads.md
Currently this renders fine on GH but not on the website
=> Fix bullet formatting on Follower Reads page

v21.1/select-for-update.md, v21.2/select-for-update.md
https://cockroachlabs.atlassian.net/browse/DOC-932
=> Clarify input and output.

_includes/v21.2/sidebar-data/manage.json, releases/release-support-policy.md
=> Adding callout with link to CC upgrade policy doc.

_includes/v21.2/ui/ui-sql-latency-99th-percentile.md
https://cockroachlabs.atlassian.net/browse/DOC-1400
=> Include service latency metrics only from DML.

v21.2/install-client-drivers.md
Fixes https://github.com/cockroachdb/docs/issues/12749.
This PR updates the support level for several client tools and reorders the sections to be consistent with our [Connect to a CockroachDB Cluster](https://www.cockroachlabs.com/docs/v21.2/connect-to-the-database.html) page.
An additional improvement would be to use tabs, like we do for [Connect to a CockroachDB Cluster](https://www.cockroachlabs.com/docs/v21.2/connect-to-the-database.html).
=> Updated client driver install page

v21.2/local-testing.md
=> Add docs on CRDB settings for unit testing / CI

v21.1/partitioning.md, v21.2/partitioning.md
=> DOC-2337: Fix obsolete known limitation with inverted indexes

v21.1/computed-columns.md, v21.1/foreign-key.md, v21.2/computed-columns.md, v21.2/foreign-key.md
=> DOC-1535: Remove limitations of computed columns in FKs

releases/v21.1.0-beta.5.md
=> DOC-1607: Correct RN for #64004

_includes/common/ui/statistics.md, v21.2/pg-catalog.md
https://cockroachlabs.atlassian.net/browse/DOC-2267
=> Fix system catalog terminology.

v21.1/add-constraint.md, v21.2/add-constraint.md
Fixes DOC-1055
Added info about the cluster setting that controls uniqueness checks on gen_random_uuid()
=> DOC-1055: Add info about UUID uniqueness cluster setting

v21.1/create-table.md, v21.2/create-table.md, v21.2/set-locality.md
Follow-up to cockroachdb/docs#10926
=> Use single quotes everywhere we UPDATE region name

api/api-spec.json, v21.2/cluster-api.md
Fixes https://github.com/cockroachdb/docs/issues/11267.
@itsbilal , @mikeCRL  - There are a several TODOs included in the updated JSON. Should I manually remove these? Note that the description for `GCPolicy` only has a TODO item and no description.
=> Updates to Cluster API

_includes/common/ui/statements-page.md, _includes/common/ui/transactions-page.md, cockroachcloud/sessions-page.md, cockroachcloud/statements-page.md, v21.2/ui-overview.md, v21.2/ui-sessions-page.md, v21.2/ui-statements-page.md
https://cockroachlabs.atlassian.net/browse/DOC-2397
=> Reordered tabs.

_includes/common/ui/statements-page.md, _includes/common/ui/transactions-page.md, cockroachcloud/sessions-page.md, cockroachcloud/statements-page.md, v21.2/ui-overview.md, v21.2/ui-sessions-page.md, v21.2/ui-statements-page.md
Reverts cockroachdb/docs#12861
=> Revert "Reordered tabs."

_includes/common/ui/statistics.md
Reverts cockroachdb/docs#12860
=> Revert "Update aggregation interval and stats flushing."

cockroachcloud/migrate-from-serverless-to-dedicated.md, v21.2/export-spatial-data.md, v21.2/import-performance-best-practices.md, v21.2/migrate-from-avro.md, v21.2/migrate-from-csv.md, v21.2/migrate-from-geojson.md, v21.2/migrate-from-geopackage.md, v21.2/migrate-from-mysql.md, v21.2/migrate-from-openstreetmap.md, v21.2/migrate-from-oracle.md, v21.2/migrate-from-postgres.md, v21.2/migrate-from-shapefiles.md
Follow-up to https://github.com/cockroachdb/docs/pull/12878.
=> DOC-2500: Set analytics front-matter for Migrate docs

cockroachcloud/stream-changefeed-to-snowflake-aws.md, v21.2/advanced-changefeed-configuration.md, v21.2/changefeed-examples.md, v21.2/changefeed-sinks.md, v21.2/changefeeds-in-multi-region-deployments.md, v21.2/create-and-configure-changefeeds.md, v21.2/monitor-and-debug-changefeeds.md, v21.2/use-changefeeds.md
Fixes [DOC-2501](https://cockroachlabs.atlassian.net/browse/DOC-2501)
=> DOC-2501: Added stream_data docs area to Stream Data pages

_includes/v21.2/sidebar-data/deploy.json, _includes/v21.2/sidebar-data/develop.json, _includes/v21.2/sidebar-data/manage.json, _includes/v21.2/sidebar-data/reference.json
Reasoning in https://docs.google.com/spreadsheets/d/1JLuOZsbMsFcZib8brtKSw0fZyAas6_saHAR0X9IpPa0/edit#gid=0.
=> DOC-2520: Remove duplicate sidenav links

releases/cloud.md
=> Serverless upgrade clarification

releases/cloud.md
https://cockroachlabs.atlassian.net/browse/DOC-2239
=> Cloud release notes February

releases/v21.2.5.md
=> Remove support for SQL arrays containing JSON for in-memory processing

api/api-spec.json
Minor update to an example in api-spec.json that didn't make it into #12323.
=> update API example

cockroachcloud/cloud-api.md
Adding `spec` wrapper to create cluster endpoint.
=> Update Cloud API GSG with Feb. 8 update

v21.1/show-tables.md, v21.2/show-tables.md
Fixes DOC-940
- Locality information now available in crdb_internal.tables and `SHOW TABLES;`
=> DOC-940: Added information about locality column

v21.1/partitioning.md, v21.2/partitioning.md
=> DOC-413: Added info about global tables for foreign key tables

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v21.1.14.md
=> v21.1.14 release notes

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v20.2.19.md
=> DOC-2510: Added v20.2.19 release notes

_data/advisories.yml, _includes/sidebar-releases.json, advisories/a75758.md
Original TA draft: https://docs.google.com/document/d/1Wt9-BJxmAUszZZ3dH24wGPqO8lILtz87O4sYQC2A8wg/edit#
@kevin-v-ngo Can you tag someone on Support who can review?
@lnhsingh I defaulted to linking the `v21.2` docs here. Let me know if there's a better way.
=> draft TA for cancel sessions issue

v21.2/show-tables.md
fixes https://github.com/cockroachdb/cockroach/issues/76422
=> connect permission required for show tables

_config_base.yml, _data/releases.yml, _includes/sidebar-releases.json, releases/v21.1.15.md
=> v21.1.15 release notes

_includes/v21.2/sidebar-data/develop.json, _includes/v21.2/sidebar-data/get-started.json, v21.2/deploy-app-gcr.md, v21.2/deploy-lambda-function.md, v21.2/serverless-function-best-practices.md
Fixes https://cockroachlabs.atlassian.net/browse/DOC-2283.
Related to https://github.com/cockroachlabs/examples-aws-lambda/pull/3.
=> Serverless function best practices

v21.2/build-a-nodejs-app-with-cockroachdb-prisma.md
Follow-up of https://github.com/cockroachdb/docs/pull/12679#discussion_r807467498
=> Added docs_area front matter to Prisma tutorial

v21.2/cluster-settings.md
https://cockroachlabs.atlassian.net/browse/DOC-2634
=> Tone down warning.

netlify/build
=> DOC-2679: Update Netlify build to fail if Jekyll build fails

netlify/build
Reverts cockroachdb/docs#13059
=> Revert "DOC-2679: Update Netlify build to fail if Jekyll build fails"

v21.2/upsert.md
https://cockroachlabs.atlassian.net/browse/DOC-2658
=> Add link to Upsert blog.

_config_base.yml, _data/releases.csv, releases/v21.2.6.md
=> DOC-1893: Added v21.2.6 release notes

_includes/v21.2/sidebar-data/get-started.json, v21.2/get-started-with-enterprise-trial.md
https://cockroachlabs.atlassian.net/browse/DOC-1167
Benchmarking orphan fixed in https://github.com/cockroachdb/docs/pull/13026.
=> Add Enterprise features to TOC and fix link.

_includes/v21.2/misc/force-index-selection.md
https://cockroachlabs.atlassian.net/browse/DOC-1711
https://cockroachlabs.atlassian.net/browse/DOC-1666
=> Document NO_FULL_SCAN.

v21.2/add-constraint.md, v21.2/check.md
Also added intro sentence for each example.
=> Fix formatting, voice, add heading. Move add behavior closer to ADD CONSTRAINT action.

_includes/sidebar-releases.json
https://cockroachlabs.atlassian.net/browse/DOC-2774
=> Remove Latest.

v21.1/deploy-lambda-function.md, v21.2/deploy-lambda-function.md, v21.2/serverless-function-best-practices.md
Fixes https://cockroachlabs.atlassian.net/browse/DOC-2566.
=> Added Node.js sample to Lambda tutorial

v20.2/install-cockroachdb-mac.md, v21.1/install-cockroachdb-mac.md
https://cockroachlabs.atlassian.net/browse/DOC-2771
=> Fix formatting that breaks page.

_includes/cockroachcloud/prefer-sso.md, cockroachcloud/authentication.md, cockroachcloud/console-access-management.md, cockroachcloud/create-a-serverless-cluster.md, cockroachcloud/create-your-cluster.md
Reverts cockroachdb/docs#13163
=> Revert "DOC-2793: Add SSO note for Cloud Console login"

releases/cloud.md
https://cockroachlabs.atlassian.net/browse/DOC-2240
=> CC March release notes

_includes/cockroachcloud/prefer-sso.md, cockroachcloud/create-your-cluster.md
https://cockroachlabs.atlassian.net/browse/DOC-2846
=> Fix for page formatting with SSO include.

v21.1/primary-key.md, v21.2/primary-key.md, v22.1/primary-key.md
=> DOC-902: Added syntactic sugar for `crdb_region` column in PKs

_data/advisories.yml, _includes/sidebar-releases.json, advisories/a76522.md
=> TA-76522 optimizer omits ON conditions in joins in query plans.

v21.1/crdb-internal.md, v21.1/interleave-in-parent.md
Fixes DOC-1811:
- Added note about new system tables available to identify interleaved objects
=> DOC-1811: Added information about interleaving deprecation

_includes/v21.1/sql/generated/diagrams/alter_database_add_region.html, _includes/v21.1/sql/generated/diagrams/alter_database_drop_region.html
=> DOC-1554: Added IF [NOT] EXISTS syntax to ADD/DROP REGION

v21.1/deploy-cockroachdb-with-kubernetes-openshift.md, v21.2/deploy-cockroachdb-with-kubernetes-openshift.md, v22.1/deploy-cockroachdb-with-kubernetes-openshift.md
Fixes DOC-1590: Corrects minor typo
=> DOC-1590 fix typo: valid

.github/workflows/changed_files.yml
Reverts cockroachdb/docs#13207
=> Revert "DOC-2868: Add first-level references to modified includes in Changed Files bot"

.github/workflows/changed_files.yml
Added fix to Changed Files that skips all sidebar-related files
=> DOC-2868: Added fix for changed files

_includes/releases/v21.2/v21.2.7.md
=> Trivial: typo fix

_includes/cockroachcloud/quickstart/create-a-free-cluster.md, _includes/cockroachcloud/quickstart/get-connection-string.md, cockroachcloud/quickstart.md, v21.2/connect-to-the-database.md, v22.1/connect-to-the-database.md
Related to https://cockroachlabs.atlassian.net/browse/DOC-2823.
See https://github.com/cockroachdb/quickstart-code-samples/pull/1/files.
=> Refactored serverless quickstart for easier connection experience

v22.1/cluster-settings.md, v22.1/eventlog.md, v22.1/functions-and-operators.md, v22.1/log-formats.md, v22.1/logging.md
=> DOC-2817: Updated docgen references to 22.1

_includes/v21.2/sidebar-data/manage.json, _includes/v22.1/sidebar-data/manage.json
=> Add Cloud Billing to navigation

_includes/v21.2/sidebar-data/get-started.json, _includes/v22.1/sidebar-data/get-started.json, v21.2/deploy-app-netlify.md, v22.1/deploy-app-netlify.md
Fixes https://cockroachlabs.atlassian.net/browse/DOC-2324.
This tutorial is dependent on https://github.com/cockroachdb/docs/pull/12679, which documents our full support for Prisma Client.
=> Netlify tutorial

v22.1/security-reference/security-overview.md
Completes https://cockroachlabs.atlassian.net/browse/DOC-2990
=> Fix feature descriptions in Security Overview table

releases/cloud.md
=> Cloud v21.2.7

v21.1/datadog.md, v21.2/datadog.md, v22.1/datadog.md
Extends #12220.
Various tweaks to the Datadog integration for self-hosted clusters, incorporating the PR opened by @gwaldo.
=> Datadog self hosted

_includes/v21.2/sidebar-data/get-started.json, _includes/v22.1/sidebar-data/get-started.json, v21.2/deploy-app-vercel.md, v22.1/deploy-app-vercel.md
Fixes https://cockroachlabs.atlassian.net/browse/DOC-2230.
=> Vercel tutorial

cockroachcloud/cluster-management.md
=> Rate-limiting prevents editing AWS disk

_includes/v21.1/zone-configs/remove-a-replication-zone.md, _includes/v21.2/zone-configs/remove-a-replication-zone.md, _includes/v22.1/zone-configs/remove-a-replication-zone.md
=> DOC-1552: Added note about discarding MR zone configs

v20.2/liquibase.md, v21.1/liquibase.md, v21.2/liquibase.md, v22.1/liquibase.md
Fixes https://cockroachlabs.atlassian.net/browse/DOC-991.
=> Fixed liquibase changelog formatting error

v20.2/example-apps.md, v21.1/example-apps.md, v21.2/example-apps.md, v22.1/example-apps.md
Fixes https://cockroachlabs.atlassian.net/browse/DOC-1187
=> Fixed formatting on C# example app header

_includes/v22.1/misc/session-vars.html, v22.1/transaction-retry-error-reference.md, v22.1/transactions.md
Fixes https://cockroachlabs.atlassian.net/browse/DOC-1212.
=> inject_retry_errors_enabled session variable

v20.2/alembic.md, v20.2/build-a-python-app-with-cockroachdb-sqlalchemy.md, v21.1/alembic.md, v21.1/build-a-python-app-with-cockroachdb-sqlalchemy.md, v21.2/alembic.md, v21.2/build-a-python-app-with-cockroachdb-sqlalchemy.md, v22.1/alembic.md, v22.1/build-a-python-app-with-cockroachdb-sqlalchemy.md
See https://github.com/cockroachlabs/example-app-python-sqlalchemy/pull/7.
Fixes https://cockroachlabs.atlassian.net/browse/DOC-641.
Fixes https://cockroachlabs.atlassian.net/browse/DOC-639.
Fixes https://cockroachlabs.atlassian.net/browse/DOC-638.
=> Updated SQLAlchemy CRUD tutorial to match sample code updates

css/customstyles.css, css/global/_type.scss
https://cockroachlabs.atlassian.net/browse/DOC-2929
To review this you might have to hard clear your browser cache.
=> Reduce left and right padding of inline code.

v21.2/connect-to-the-database.md, v22.1/connect-to-the-database.md
Fixes https://cockroachlabs.atlassian.net/browse/DOC-2440.
=> Fixed navbar bug on connection reference page

_includes/v20.2/app/java-tls-note.md, _includes/v21.1/app/java-tls-note.md, _includes/v21.2/app/java-tls-note.md, _includes/v22.1/app/java-tls-note.md
Fixes https://cockroachlabs.atlassian.net/browse/DOC-1596.
=> Updated Java TLS bug note

v20.2/build-a-java-app-with-cockroachdb.md, v21.1/build-a-java-app-with-cockroachdb.md, v21.2/build-a-java-app-with-cockroachdb.md, v22.1/build-a-java-app-with-cockroachdb.md
Fixes https://cockroachlabs.atlassian.net/browse/DOC-1183.
=> Updated connection config instructions on JDBC tutorial

cockroachcloud/cluster-management.md, releases/cloud.md
https://cockroachlabs.atlassian.net/browse/DOC-2241
=> Cloud Release Notes April 2022

StyleGuide.md
Fixes https://cockroachlabs.atlassian.net/browse/DOC-2415.
=> Updated version tags in style guide

_config_base.yml, _data/releases.csv, _includes/releases/v22.1/v22.1.0-beta.1.md
Add release notes for v22.1.0-beta.
=> Add release notes

v22.1/connect-to-the-database.md
Related to https://cockroachlabs.atlassian.net/browse/CC-6544.
=> Updated go connection docs

_includes/v22.1/known-limitations/schema-changes-within-transactions.md
=> DOC-2731: Drop known limitation about mixing DML and DDL

StyleGuide.md
Fixes https://cockroachlabs.atlassian.net/browse/DOC-1920.
=> Added placeholder guidance to style guide

v21.1/show-create.md, v21.2/show-create.md
=> DOC-939: Multi-region table localities note to SHOW CREATE

v22.1/show-create.md
=> DOC-939: Apply changes to 22.1

v22.1/cost-based-optimizer.md
https://cockroachlabs.atlassian.net/browse/DOC-2407
=> Add KB section on reducing planning time for many joins.

_config_base.yml, _data/releases.csv, _includes/releases/v21.2/v21.2.8.md
=> DOC-1895: Added RN for v21.2.8

v20.2/build-a-typescript-app-with-cockroachdb.md, v21.1/build-a-typescript-app-with-cockroachdb.md, v21.2/build-a-typescript-app-with-cockroachdb.md, v21.2/connect-to-the-database.md, v22.1/build-a-typescript-app-with-cockroachdb.md, v22.1/connect-to-the-database.md
Related to https://cockroachlabs.atlassian.net/browse/DOC-3063, https://cockroachlabs.atlassian.net/browse/CC-6539, https://github.com/cockroachlabs/hello-world-typescript-typeorm/pull/4.
Ahead of merging this PR, I'm going to rename [`hello-world-typescript-typeorm`](https://github.com/cockroachlabs/hello-world-typescript-typeorm) to `example-app-typescript-typeorm`.
=> Updated TypeORM to use DataSource API

_includes/v20.2/sql/unsupported-postgres-features.md, _includes/v21.1/sql/unsupported-postgres-features.md, _includes/v21.2/sql/unsupported-postgres-features.md, _includes/v22.1/sql/unsupported-postgres-features.md
=> DOC-1027: Add color to why dropping PKs is unsupported

_includes/common/ui/statements-page.md
https://cockroachlabs.atlassian.net/browse/DOC-2914
=> Fix column name.

StyleGuide.md
Fixes https://cockroachlabs.atlassian.net/browse/DOC-2065
=> Added Known Limitations to the Style Guide

_data/advisories.yml, _includes/sidebar-releases.json, advisories/a78681.md
=> Added TA-78681

_data/advisories.yml, _includes/sidebar-releases.json, advisories/a79281.md
https://github.com/cockroachdb/cockroach/pull/79293
https://github.com/cockroachdb/cockroach/issues/79281
=> Technical advisory 79281

v20.2/frequently-asked-questions.md, v21.1/frequently-asked-questions.md, v21.1/multi-active-availability.md, v22.1/frequently-asked-questions.md, v22.1/multi-active-availability.md
Fix CockroachDB FAQ page title. Relates to DOC-2377.
=> Fix FAQ page titles

v21.2/frequently-asked-questions.md, v21.2/multi-active-availability.md
=> Apply faq title update to 21.2.

releases/cloud.md
no ca cert only for serverless with certain drivers
=> April release notes correction

v22.1/sql-feature-support.md
Addresses Row-level TTL issue in [DOC-3354](https://cockroachlabs.atlassian.net/browse/DOC-3354).
=> Fix alignment of Row-level TTL row and include Details

v21.2/alter-role.md, v22.1/alter-role.md
The `root` user cannot be configured in this way.
=> Clarify ALTER ROLE ALL behavior

_config_base.yml, _data/releases.csv, _includes/releases/v22.1/v22.1.0-beta.4.md
=> DOC-3367: Added v22.1.0-beta.4 release note

v21.2/ui-overview.md, v22.1/ui-overview.md
=> add Overload Dashboard to DB Console Overview

cockroachcloud/architecture.md
https://cockroachlabs.atlassian.net/browse/DOC-3347
Edit architecture page layout
Add deployment option recommendation
=> Cloud architecture reorganization and clarification

_includes/v22.1/misc/session-vars.html
https://cockroachlabs.atlassian.net/browse/DOC-2185.
=> Session variable to control index recommendations.

v22.1/explain.md
https://cockroachlabs.atlassian.net/browse/DOC-2147
=> Update for index recommendations.

v22.1/information-schema.md, v22.1/show-grants.md
https://cockroachlabs.atlassian.net/browse/DOC-2434
SHOW GRANTS ON TABLE now includes is_grantable column
=> Update SHOW GRANTS ON TABLE to include grant options is_grantable on tables

v22.1/grant.md
SQL Diagram: https://github.com/cockroachdb/cockroach/pull/80330
Closes https://cockroachlabs.atlassian.net/browse/DOC-3296
=> WITH GRANT OPTION support

.github/workflows/vale.yml, netlify/build, netlify/vale/CockroachDB/Spelling.yml, netlify/vale/CockroachDB/Terminology.yml, netlify/vale/extensions.txt, netlify/vale/vale/GenderBias.yml, netlify/vale/vale/Hedging.yml, netlify/vale/vale/Redundancy.yml, netlify/vale/vale/Repetition.yml, netlify/vale/vale/Uncomparables.yml, netlify/vale/vocab.txt
=> DOC-270: Run Vale against changed files only

_includes/v22.1/misc/session-vars.html, v21.1/null-handling.md, v21.1/order-by.md, v21.2/null-handling.md, v21.2/order-by.md, v22.1/null-handling.md, v22.1/order-by.md
https://cockroachlabs.atlassian.net/browse/DOC-1207
https://cockroachlabs.atlassian.net/browse/DOC-1716
https://cockroachlabs.atlassian.net/browse/DOC-1507
https://cockroachlabs.atlassian.net/browse/DOC-1121
=> Null handing issues.

StyleGuide.md
Fixes https://cockroachlabs.atlassian.net/browse/DOC-2072.
=> Added forward-looking guidance to Style Guide

releases/cloud.md
https://cockroachlabs.atlassian.net/browse/DOC-3399
=> Cloud May Release Notes

v21.1/community-tooling.md, v21.2/community-tooling.md, v22.1/community-tooling.md
Fixes https://cockroachlabs.atlassian.net/browse/DOC-2961.
=> Added tokio_postgres to community-supported tools

_config_base.yml, _data/releases.csv, _includes/releases/v22.1/v22.1.0-beta.5.md
=> DOC-1912: Add v22.1.0-beta.5 release note

_includes/v22.1/sql/locality-optimized-search-limited-records.md, v22.1/known-limitations.md
https://cockroachlabs.atlassian.net/browse/DOC-3311
https://cockroachlabs.atlassian.net/browse/DOC-2664
=> Update locality optimized search limitation.

releases/cloud.md
Remove metrics --only avail in 22.1 which is not out yet
=> CC release notes edit

v21.1/schema-design-table.md, v21.2/schema-design-table.md, v22.1/schema-design-table.md
=> DOC-3315: Updated examples surrounding custom types

.github/workflows/vale.yml, _includes/v21.2/sidebar-data/manage.json, _includes/v22.1/sidebar-data/manage.json, cockroachcloud/ccloud-get-started.md, cockroachcloud/cloud-api.md, cockroachcloud/console-access-management.md, netlify/vale/vocab.txt, releases/cloud.md
=> New ccloud getting started topic

StyleGuide.md
Scratching an itch for consistency
=> Style: More fully committing to gerunds

v22.1/admission-control.md, v22.1/architecture/replication-layer.md, v22.1/cost-based-optimizer.md, v22.1/crdb-internal.md, v22.1/null-handling.md, v22.1/order-by.md, v22.1/show-schedules.md, v22.1/show-statistics.md, v22.1/ui-databases-page.md
=> Fix New in markup.

_config_base.yml, _data/releases.csv, _includes/releases/v21.1/v21.1.19.md
=> v21.1.19 release notes

_includes/v22.1/misc/tooling.md, _includes/v22.1/sidebar-data/develop.json, _includes/v22.1/sidebar-data/reference.json, v22.1/satori-integration.md
https://cockroachlabs.atlassian.net/browse/DOC-3294
=> add Satori integration doc

v21.2/ui-hot-ranges-page.md, v22.1/ui-hot-ranges-page.md
Fixes DOC-3270.
Relates to CRDB-15008. (No DOC issue for this yet)
=> tweaks to hot ranges page

v22.1/online-schema-changes.md, v22.1/pause-job.md
=> DOC-2219: Add note about paused schema change jobs

v22.1/drop-user.md
=> DOC-2751: Added note about dropping users with default privileges
